### ISSUE TITLE
Prepend/append a statement before/after each query

### ISSUE THREAD

**Issue by jmealo** [vitaly-t/pg-promise#100]
I would like to prepend/append a statement to each query issued that sets and then clears a GUC variable containing the ``session_id`` of the logged in web user.

If the use case is unclear, it's to enable the following pattern:
https://gist.github.com/jmealo/4dc1c59b8d31009f9262

**Comment by vitaly-t** [comment]
If it is ok for you to throw in an extra variable into each query, you can add your own [Custom Formatting Type](https://github.com/vitaly-t/pg-promise#custom-type-formatting) and then it with each query.

Or else, if you do not want to modify queries and want it to happen for every single query, you can use event `extend` to introduce your own query method that can pre-format each query.

**Comment by vitaly-t** [comment]
@jmealo Note to you, since we last discussed this, a new feature was added to the library, which may also come of help, depending on which way you will decide to do it: [as.format](http://vitaly-t.github.io/pg-promise/formatting.html#.format) has been extended with parameter `options`.

P.S. Anyhow, I'm done for today, till tomorrow now)

**Comment by vitaly-t** [comment]
@jmealo No feedback?

**Comment by jmealo** [comment]
I'll check this out tomorrow... Thanks!

**Comment by vitaly-t** [comment]
@jmealo Anything? You can re-open it when you have something.

**Comment by jmealo** [comment]
@vitaly-t I do not want to add a query parameter to each query.

My issue is, on each incoming request to my API, I attach a ``pg-promise`` insance. I will need each request to prepend/append session data related to the ``request`` object. I need to have that in scope and continue to share the connection pool.

Is this possible?

Just know that this is a pattern in Koa, not something exotic that I'm doing in express or with bare the core http server.

**Comment by jmealo** [comment]
@vitaly-t I cannot re-open a request.

Additionally, I do recall that I tried to "fix" this by wrapping all the pgp methods to perform this and ran into  an issue that the object did not allow modifications to be made.

For performance reasons, I'd really prefer not to wrap this in a ``Proxy``, but it would be a work around.

**Comment by vitaly-t** [comment]
I gave you 2 possible approaches earlier. Have you tried them?

**Comment by jmealo** [comment]
Yes, I tried them last time that we discussed this, they lack the necessary scope to access the session object corresponding to the request. I sunk a few days into this the last time we discussed it couldn't find a way to do it via monkey patching; I would need to fork the library and make changes directly.

I was hoping now that I introduced a concrete use case that shows the state-fulness and needed context.

**Comment by vitaly-t** [comment]
>they lack the necessary scope to access the session object corresponding to the request

When you add your own method via event `extend` it can take the session parameters and append/pre-prend the extra request you need.

**Comment by jmealo** [comment]
``extend`` is global though.

My node app has multiple ``pg-promise`` instances which maintain own connection pool. Each connects  as a different db role with a ``SEARCH_PATH`` and permissions clamped down to that tenant/schema.

Incoming HTTP requests are handled asyncronously, so even if I could ``extend`` and ``unextend`` the session sent to the service would always be the most recent session, not necessarily the one making the queries.

Does that make sense?

**Comment by vitaly-t** [comment]
Node.js enforces singularity of each modules loaded via `require`. It doesn't matter how many times you call it, you will the same instance of the module. It is the `db` instance that would differ, if you are trying to represent different databases. And event `extend` will be called for each of the `db` instances that you have.

**Comment by jmealo** [comment]
I use generators that sleep when waiting on IO. Imagine an API endpoint makes a SQL query, then a REST request to an external HTTP API which lastly makes a second SQL query.

While that external API response is pending, other incoming HTTP requests to my API will use that ``pg-promise`` instance while the generator is sleeping because the SQL connection has been returned to the pool. (Correct?)

**How I picture working around this:**
The session data would be  ``SET`` to a custom ``GUC`` variable in the ``prepend`` and that GUC would be cleared/reset in the ``append``. This is just for safety, it should be fine to only ``prepend``.

**In summary:**
Multiple requests share the ``pg-promise`` instance at the same time. It is not an instance per request. It is an instance per schema/tenant. The same ``pg-promise`` instance can be returned to the connection pool multiple times during a request.

That's why I need a way to always pass in the session context with each query, or somehow wrap it, so the ``context.pgp`` object which points to the ``pg-promise`` instance that request should be using will always set the ``GUC`` variables for that user to make sure audit logging, query logs, and row-level security rules match that user's web application session.

I'm not opposed to a hack, but I'm unsure where I can fit it in.

**Comment by jmealo** [comment]
**Some possible solutions:**
If I could pass in the request context into each query method and then extend it to look for that property and append/prepend to the query that could work.

If not if I can make some kind of ``WrappedQuery`` object that when passed into any of the query methods accomplishes the same goal.

**Comment by vitaly-t** [comment]
>If I could pass in the request context into each query method and then extend it to look for that property and append/prepend to the query that could work.

So add such method via event `extend` and use it. I don't see the problem or relevance of the HTTP that you describe. As far as pg-promise is concerned, this is all very generic.

**Comment by jmealo** [comment]
How would I extend the event get the entire request object if I don't want to pass the request object as a query parameter?

> All pre-defined methods and properties are read-only, so you will get an error, if you try overriding them.

If I can't redefine the extend before every single query that I execute, multiple times per request, I don't see how ``extend`` lets me do what I want to do?

**Comment by jmealo** [comment]
It looks like I could do it with ``QueryFile`` but it's locked down for internal use by the library. That's how most of my ideas/hacks have been thwarted.

**Comment by vitaly-t** [comment]
```js
// with extra parameter:
var options = {
    extend: obj=> {
        obj.myMethodWithParam = (query, values, context)=> {
            // append/pre-pend query parameters, using the context;
            return obj.query(query, values);
        }
    }
};
```

```js
// without extra parameter:
var options = {
    extend: obj=> {
        obj.myMethodWithoutParameter = function(query, values) {
            // append/pre-pend query parameters, using either
            // a global context, or 'this' context.
            return obj.query(query, values);
        }
    }
};
```

**Comment by jmealo** [comment]
@vitaly-t: I don't think that I can do it without the extra parameter because we're re-using the instance, but the extra parameter should work if I do this.

I'm going to try wrapping every query method and that *should* work... not sure if it'll work with tasks and transactions though.

**Comment by vitaly-t** [comment]
If you want it to work through tasks and transactions, then perhaps relying on `this` parameter is better.

**Comment by jmealo** [comment]
Sorry, I don't follow, what would that look like?

**Comment by vitaly-t** [comment]
```js
// passing context via tag:
db.task(myContext, callback);

// passing context via this:
db.call.task(callback);
```

**Comment by jmealo** [comment]
@vitaly-t Okay, that last bit makes sense. I'll give this a shot. Thanks

**Comment by jmealo** [comment]
I ended up just wrapping the basic query methods for now. I'm using my own transactions now (I hope that's sanctioned)... so I haven't had to use any of the built-ins for tx/tasks.

I took this approach because:

1. It will work with IDE's code introspection
2. Each wrapper instance is a reference to the only two things it needs
3. Each method is defined once in the prototype

```javascript
function PgpWrapper(pgp, ctx) {
    this.pgp = pgp;
    this.ctx = ctx;
}

PgpWrapper.prototype.oneOrNone = function(query, values) {
    return this.pgp.oneOrNone.call(this.pgp, this.ctx.guc() + query, values);
};

PgpWrapper.prototype.many = function(query, values) {
    return this.pgp.many.call(this.pgp, this.ctx.guc() + query, values);
};

PgpWrapper.prototype.oneOrNone = function(query, values) {
    return this.pgp.oneOrNone.call(this.pgp, this.ctx.guc() + query, values);
};

PgpWrapper.prototype.manyOrNone = function(query, values) {
    return this.pgp.manyOrNone.call(this.pgp, this.ctx.guc() + query, values);
};

PgpWrapper.prototype.any = function(query, values) {
    return this.pgp.any.call(this.pgp, this.ctx.guc() + query, values);
};

PgpWrapper.prototype.result = function(query, values) {
    return this.pgp.result.call(this.pgp, this.ctx.guc() + query, values);
};
```

**Comment by vitaly-t** [comment]
This looks quite inefficient, and won't work within tasks.

>I believe you said that if I use ES6 multi-line strings that I cannot use your custom goodies. 

I don't believe I ever said that, as it's not true.

**Comment by jmealo** [comment]
@vitaly-t: I'm fairly certain that I need to wrap pg-promise for this to work as a shared instance of pg-promise between requests is not concurrency safe (if multiple requests are ``yield``ing).

The only way I can see getting around that is to pass state in somehow using custom formatting, which I'm still trying to wrap my head around.

If I want to do this 100% transparently, I believe wrapping is the way to go.

To make this work inside of tasks, could I just need to wrap ``this`` inside the task to also use the wrapped methods? I haven't read the code yet.

There's a low-level ``query`` method that'd be ideal to wrap but monkey patching isn't concurrency safe. 

From a meta-programming approach, you'd use a ``Proxy`` that traps all function calls, swaps out ``query`` with a patched version that prepends the query no matter how pg-promise uses it (this would work within tasks).

This would not be performant and is a bit "magic" for my tastes, but it might be the "cleanest" way to do it.

**Comment by jmealo** [comment]
@vitaly-t:

I was able to wrap the ``task`` method, however, as you mentioned, it doesn't look like ``tx`` will be wrappable.

My testing included the queries being wrapped. I'm not sure if ``task`` behaves as documented when wrapped like this.

It might be a good idea for me to try to modify the unit tests to run with my wrapped version to check for regressions possibly.

```javascript
'use strict';

require('generator-bind').polyfill();

function PgpWrapper(pgp, ctx) {
    this.pgp = pgp;
    this.ctx = ctx;
}

/* This wrapper is verbose and minimalistic in order to optimise for:
    1. Garbage collection [each instance is just two references with methods on prototype, not each instance]
    2. Execution speed / V8 Optimization [ES6/ES5 meta-programming features are slow. V8 can optimise simple objects.
    3. Code auto-completion [explicitly defining the methods should work with most IDEs, looping over an array may not]
*/

PgpWrapper.prototype.none = function(query, values) {
    return this.pgp.none(this.ctx.guc() + query, values);
};

PgpWrapper.prototype.one = function(query, values) {
    return this.pgp.one(this.ctx.guc() + query, values);
};

PgpWrapper.prototype.many = function(query, values) {
    return this.pgp.many(this.ctx.guc() + query, values);
};

PgpWrapper.prototype.oneOrNone = function(query, values) {
    return this.pgp.oneOrNone(this.ctx.guc() + query, values);
};

PgpWrapper.prototype.manyOrNone = function(query, values) {
    return this.pgp.manyOrNone(this.ctx.guc() + query, values);
};

PgpWrapper.prototype.any = function(query, values) {
    return this.pgp.any(this.ctx.guc() + query, values);
};

PgpWrapper.prototype.result = function(query, values) {
    return this.pgp.result(this.ctx.guc() + query, values);
};

PgpWrapper.prototype.task = function (p1, p2) {
    p1 = p1.bind({}, this);

    if (p2) {
        p2 = p2.bind({}, this);
    }

    return this.pgp.task(p1, p2);
};

module.exports = PgpWrapper;
```

**Comment by vitaly-t** [comment]
This approach will not work with tasks and transactions. Event [extend](http://vitaly-t.github.io/pg-promise/global.html#event:extend) is the only correct way to extend the protocol.

**Comment by jmealo** [comment]
I'm totally for making a sample application, however, I don't have a way of even moving forward if ``extend`` is the only correct way to do this.

I do not want to extend the protocol, I want to modify every single query on its way to PostgreSQL without exception.

**Questions about ``extend``**:
1. In the documentation, the ``extend`` example defines an ``options`` object. I assume that this is to pass to the pg-promise constructor on a per-instance basis. In which case, I would need a new ``pg-promise`` instance per incoming request because I need to be bound to the context of my request.

2. How do I use extend to override the built-in methods so that all use of ``pg-promise``? I'm not seeing how this would work.

I also do not see how ``extend`` allows me to override the behavior of the built-in methods.

The only thing I see that seems even remotely possible would be to make an ``SqlQuery`` type with a ``String`` prototype to keep a reference to the request. Then a custom formatter could pull the request off and prepend/prefix the query?

**Comment by vitaly-t** [comment]
>In the documentation, the extend example defines an options object. I assume that this is to pass to the pg-promise constructor on a per-instance basis.

No. This refers to the global, once-off instantiation `Initialization Options` object for the entire library.

>How do I use extend to override the built-in methods so that all use of pg-promise?

You do not override anything predefined in the protocol, you add new methods and properties that can extend the existing ones with extra or specific functionality.

>I also do not see how extend allows me to override the behavior of the built-in methods.

I doesn't override anything, it extends.

**Comment by vitaly-t** [comment]
@jmealo I had another look at how this library handles its own global instance, or to put otherwise - how to support more more one instance.

I found some problems here, which may be in part what you were talking about. So, I have started working on it - to make it better, to support multiple instances properly.

This seems like a big change, but an important one.

I have just finished doing it for `spex`, which is used by `pg-promise`. That library has (had) the same problems, being unable to properly handle its own multi-instance mode.

**Comment by vitaly-t** [comment]
Update [spex v. 0.4.2](https://github.com/vitaly-t/spex/releases/tag/v.0.4.2) has been released, with proper multi-instance support.

Now I can start doing it for `pg-promise` :)

**Comment by vitaly-t** [comment]
@jmealo if you want to follow this up, I have created https://github.com/vitaly-t/pg-promise/issues/114

**Comment by jmealo** [comment]
@vitaly-t: I'm interested in getting this to work. I'm not sure if multiple instances would help me personally.

 I would like to commend you for being so diligent in following up and trying to understand my use case. You're a real standup guy :+1:.

**Comment by vitaly-t** [comment]
All updates are here: https://github.com/vitaly-t/pg-promise/issues/114

Cheers! :)

**Comment by vitaly-t** [comment]
@jmealo this may or may not help you in your project, but [version 3.8.0](https://github.com/vitaly-t/pg-promise/releases/tag/v.3.8.0) received support for the database context, which further improves multi-database or status-full databases.

>extend is global though.

It is not that global anymore, as the database context is now available there, same as everywhere else.

**Comment by lloydh** [comment]
I'm trying to achieve something similar — setting the `application_name` to include the current application user's id for use in audit tables (via trigger functions).

How could I set `application_name` in this example (from above), and does this mean having to use `db.myMethodWithParam` vs. `db.any`, `db.one` etc. or does it 'extend' these methods?

```JS
// with extra parameter:
var options = {
    extend: obj=> {
        obj.myMethodWithParam = (query, values, context)=> {
            // append/pre-pend query parameters, using the context;
            return obj.query(query, values);
        }
    }
};
```

Thanks,
Lloyd
