### ISSUE TITLE
Approach for `INSERT`ing an empty array

### ISSUE THREAD

**Issue by ggoodman** [vitaly-t/pg-promise#101]
Consider a table with a column `tags` that is of type `TEXT[]`. When building an insert statement like

```js
var data = {
    other_field: 'something',
    tags: [], // Empty array
};
var stmt = `INSERT INTO table (other_field, tags) VALUES($1, $2)`;

return db.one(stmt, [data.other_field, data.tags]);
```

The resulting query will look something like this:

```sql
INSERT INTO table (other_field, tags) VALUES('something', array[]);
```

Postgres takes offence to this and responds with:

```
ERROR:  cannot determine type of empty array at character 544
HINT:  Explicitly cast to the desired type, for example ARRAY[]::integer[].
```

What approach do you recommend using with `pg-promise` to resolve this ambiguity in a clean and portable way?

**Comment by vitaly-t** [comment]
There is only one solution to this. Since PostgreSQL parser cannot deduct type from the data, you have to tell it explicitly:

```sql
INSERT INTO table (other_field, tags) VALUES('something', array[]::text[]);
```
i.e. change your query to:
```js
var stmt = `INSERT INTO table (other_field, tags) VALUES($1, $2::text[])`;
```

**Comment by vitaly-t** [comment]
Release [v6.7.1](https://github.com/vitaly-t/pg-promise/releases/tag/v.6.7.1) changes these things.
