### ISSUE TITLE
How to disconnect or end connection

### ISSUE THREAD

**Issue by cortopy** [vitaly-t/pg-promise#102]
I was looking at the API docs and I can see there is the possibility of handling a disconnection event. However, I can't see how to trigger the end of connection. 

I can also see that the client is based on node-postgres. However, node-postgres client has an `end()` method, which I can't find with pg-promise

Is there a way to trigger the disconnection?

**Comment by vitaly-t** [comment]
There are events [connect](http://vitaly-t.github.io/pg-promise/global.html#event:connect) and [disconnect](http://vitaly-t.github.io/pg-promise/global.html#event:connect) that represent virtual connection, i.e. from the connection pool.

This library works only via the connection pool, so you never physically open or close connections, only virtually, which you can monitor through those events.

**Comment by cortopy** [comment]
That's what I thought from reading the docs. However, the problem is that after my program finishes, it still hangs until connection is dropped. 

If there was a way to close the connection, the app would be able to exit when it's all done.

**Comment by vitaly-t** [comment]
This is documented in [Library de-initialization](https://github.com/vitaly-t/pg-promise#library-de-initialization) and in [all examples](https://github.com/vitaly-t/pg-promise/tree/master/examples).

**Comment by cortopy** [comment]
That's what I was looking for! Thanks

**Comment by demian85** [comment]
Can someone please explain how is a connection released? Is it released and free to be used when a query ends? I'm running into timeout issues in AWS Lambda and I'm investigating where the problem is, and the pool management is a bit of a mystery to me. Thanks.

**Comment by vitaly-t** [comment]
Release [10.11.0](https://github.com/vitaly-t/pg-promise/releases/tag/10.11.0) pertains to this.
