### ISSUE TITLE
Make a gitter room to discuss about the library

### ISSUE THREAD

**Issue by jgoux** [vitaly-t/pg-promise#103]
Hi,

I'd like to discuss about the lib without polluting the issues.

Would it be possible to make a room on [gitter](https://gitter.im) for this purpose ?

**Comment by vitaly-t** [comment]
I've never used it. If you can set it up, then please - go ahead.

**Comment by jgoux** [comment]
You need to be the owner of the repository to create a room for the project.

You just have to connect via Github and create a room (you will be able to pick your repo) :+1:

**Comment by vitaly-t** [comment]
@jgoux it is done: https://gitter.im/vitaly-t/pg-promise

**Comment by jgoux** [comment]
Thank you ! :sparkler:

**Comment by vitaly-t** [comment]
@jgoux thank you for bringing this up, it does look very useful :)
