### ISSUE TITLE
pgp.as.csv(values) is incorrect when you pass a single Buffer

### ISSUE THREAD

**Issue by nonplus** [vitaly-t/pg-promise#106]
Even after resolving #105, `pgp.as.csv(values)` is incorrect when `values` is a single `Buffer` instance.  It works correctly when you pass in an array that contains Buffer element(s).

Please fix and update documentation.

Steps to reproduce:
```
var pgp = require('pg-promise');

var buf = new Buffer([1, 2, 3]);

console.log("pgp.as.csv(buf)", pgp.as.csv(buf));
console.log("pgp.as.csv([buf])", pgp.as.csv([buf]));
```

```
Expected output:
pgp.as.csv(buf) '\x010203'
pgp.as.csv([buf]) '\x010203'

Actual output:
pgp.as.csv(buf) 1,2,3
pgp.as.csv([buf]) '\x010203'
```

Also, in the documentation, please make it clear that `csv` refers to a comma-separated list of PostgreSQL literal values and not [Comma-separated values](https://en.wikipedia.org/wiki/Comma-separated_values) used in [PostgreSQL's COPY FROM/TO CSV](http://www.postgresql.org/docs/9.5/static/sql-copy.html) command.  This had me confused while discussing #105.

Really, a better name for the `:csv` filter and `as.csv()` function would have been `:array` and `as.array()`, because that's what the [PostgreSQL documentation](http://www.postgresql.org/docs/9.5/static/functions-comparisons.html) uses.

**Comment by vitaly-t** [comment]
If you look at the end of this post: https://github.com/vitaly-t/pg-promise/issues/105#issuecomment-198863916

>The problem, as we discussed it earlier, the purpose of such formatting is unclear. I can't think of any practical example. It least it won't throw an error, and do something logical instead.

What I meant by that, I was going to leave the initial implementation I did, converting `Buffer` as `1,2,3` when it is used as a value directly.

This is exactly what I did and how I tested it.

That's where the misunderstanding came in.

**Comment by vitaly-t** [comment]
I'm thinking it over now, and think you are right, that output should be changed, for consistency with simple values.

**Comment by vitaly-t** [comment]
>Also, in the documentation, please make it clear that csv refers to a comma-separated list of PostgreSQL literal values and not Comma-separated values used in PostgreSQL's COPY FROM/TO CSV command. This had me confused while discussing #105.

Even that very link says:

>In popular usage, however, the term "CSV" may denote some closely related delimiter-separated  formats, which use a variety of different field-delimiters

So, the way it was phrased there was correct.

**Comment by vitaly-t** [comment]
Fixed in [v.3.4.1](https://github.com/vitaly-t/pg-promise/releases/tag/v.3.4.1).

**Comment by nonplus** [comment]
Thanks for the fix.  As far as CSV goes, I missed your comments in the discussion of #105 (middle of my night and I was skimming...).
