### ISSUE TITLE
[Custom Errors] A better way to handle exceptions

### ISSUE THREAD

**Issue by vieks** [vitaly-t/pg-promise#107]
First thanks a lot for your library which is amazing and gives off from shit bloated ORM.

One default is about errors handling in **our app** due to a limitation with the way how you have managed your Error objects inheritance inside **your lib**.

For instance:

```javascript
  async mutateAndGetPayload(payload, { rootValue: { req, db, cache, conf } }) {
    try {
      d(payload);

      // validation: throws custom errors (an instance extended from Error class) on fail
      const res = validator.check(payload, schema);
      
      payload.role       = role.BASIC;
      payload.status     = status.UNREGISTERED;
      payload.created_at = payload.updated_at = +new Date;
      // throws also
      payload.pass       = await bcrypt.hashAsync(payload.pass,
                                                  conf.BCRYPT_ROUNDS);

      // database: throws but a standard Error !!!
      return await db.users.insert(payload);

    } catch(error) {

      // time to handle errors
      let messages;

      if(error instanceof ValidationError){
        messages = validator.messages();
      }else if(error instanceof BcryptError){
        messages = '...';
      }else if(error instanceof DatabaseError){ /* We can't right now pg-promise have not inherited Error */
        messages = {
          message: error.message,
          detail: error.detail,
          //...
        };
      }else{
        // messages = ...
      }

      return messages;
    }
  },

```

As you see, your lib only throws standard Errors, ``` error.contructor === Error``` and it become very tricky to handle them when many kind of errors from other libs can be thrown by the same try block. 

So yeah there is solutions like isolating each portion of code sensitive to throw exception but the code will become messy and unpleasant to ready/follow.

Another way will be to make something like that on the error handler blocks: ``` else if('table' in error && 'constraint' in error) ... ``` but same problems, the code is ugly and harder to manage.

The clean solution is that you implement a bunch of custom extended Errors inherit from Error class, permitting to use/check them with ease.

```javascript
  if(error instanceof DatabaseConstraintViolationError){
    // TODO
  }else if(error instanceof DatabaseQueryError){
     TODO    
  }else if(error instanceof DatabaseError /* This is the common parent Error class of your lib */){
    // TODO
  }
``` 
The common parent Error class implementation is important to allow only one check for those do not want check them all.

**Comment by vitaly-t** [comment]
The most important error in the library, also one that is the most common to occur, is the mismatch between the type of method used and the number of rows returned.

Whenever this happens, the library produces [QueryResultError](http://vitaly-t.github.io/pg-promise/QueryResultError.html), which is referenced ti from every query method in the API.

**Comment by vitaly-t** [comment]
Another very common example, with the use of external SQL files via [QueryFile](http://vitaly-t.github.io/pg-promise/QueryFile.html). When it fails to parse the SQL, it throws custom [SQLParsingError](https://github.com/vitaly-t/pg-minify/blob/master/lib/error.js).

So as you can see, custom errors are used a lot, in all important places in fact.

**Comment by vieks** [comment]
Indeed it's right I have not notice them so far. I was simply not confront to that kind of error.
It seem I was unlucky because the only one I encounter is with an integrity constraint violation and in this case there is not custom error, just a plain Error object with that following shape:

```javascript
{
        "message": "duplicate key value violates unique constraint \"users_name_key\"",
        "name": "error",
        "length": 224,
        "severity": "ERROR",
        "code": "23505",
        "detail": "Key (name)=(fogogdgfsdfgzgifsdgfgngfgfgggfgfgdggggdsad) already exists.",
        "schema": "public",
        "table": "users",
        "constraint": "users_name_key",
        "file": "nbtinsert.c",
        "line": "406",
        "routine": "_bt_check_unique",
}
```

**Comment by vitaly-t** [comment]
This is exactly how such errors arrive from `node-postgres`, and pg-promise doesn't create any overhead on top of it.

But you can easily catch such errors. I'm seeing lots of developers use [pg-error](https://github.com/moll/node-pg-error) to simplify such error handling.

**Comment by vieks** [comment]
Yes node-pg-error-lib is what I need to use in response to my issue or I can implement my own wrapper it's not a problem.

On the other hand, like many of us in my humble opinion, no one want to manage with this low level of code. Your lib is the perfect abstract for Postgres, we just want install it and use it to manage the database without the need to code our own or plug to it other small libs to compensate a very small but important functionality. Pg-promisy to rule them all.

So I can understand parsing and filtering at your level of all errors that Postgres driver pulls up with node-postgres will be a pain and not the purpose of your lib. That's right and it's a good design choice.

But in that case, an elegant and a quick fix is that you only implement one global custom parent Error for your lib (wrapping around node-postgres raw Error whatever their shape don't care about it), so now at our code level we can check easily if your lib has thrown an exception at runtime among other libs.

So please implement just a single DatabaseError (or of course whatever name you want :) ) because at our level coding we can't detect and and wrap it easily (or in an elegant way without touching pgp underlying lib): Our app code <-- pg-promise <-- node-postgres (=Who want manipule that ???) 

And for those that want an advanced Postgresql errors mechanism with custom classes for all possible error cases, they install pg-error.

**Comment by vieks** [comment]
The goal is to have something like that:
```javascript
      try{
        // app code throwing many kind of exceptions
      }catch(error){
        if(error instanceof ValidationError){
          // ...
        }else if(error instanceof BcryptError){
          // ...
        }else if(error instanceof DatabaseError){/* pg-promise Parent error */

          // want advanced customized errors based on low level database parsing use an add-on lib like pg-error
          const errorName = error.constructor;

          switch(errorName){
            case DatabaseConstraintViolationError:
              // ...
            break;
            case DatabaseQueryError:
              // ...
            break;
            // etc...
          }

        }else{
          // ...
        }
      }
```

**Comment by vieks** [comment]
Whatever you choose to do, big thanks for the hard work complete so far. Your lib is really nice and keep up the good work ;)

**Comment by vitaly-t** [comment]
Cheers! :)

**Comment by vitaly-t** [comment]
The type of error handling that you are looking for becomes so much easier if you just handle event [error](http://vitaly-t.github.io/pg-promise/global.html#event:error) ;)

**Comment by vieks** [comment]
I can't use pg-promise global error event handler since there is now way within it to return a new custom error object, append a property or throwing from that place.

The only thing I need is on my code having the possibility to use the instanceof operator (SO no getting a generic Error but a custom one) in a catch block in an async ES7 function.

This is not the case actually with pg-promise, I get a simple Error instance (but with nice properties). I just need an error instance with the proper 'constructor' property in order to use the instanceof operator. But I can't there is now way.

> Note to you, it is difficult to encompass everything within a DatabaseError.

All my code stands in the frontend, where validation occurs. If the client by-pass something or/and an error occurs on the backend, I merely send him back an error. All pretty output and details is no need on backend, just type error dectection. Or at least a custom constraint error violation, since there is no way to check it on frontend stage.

So what is the way in your lib to hook up an errors and customize it ?
Otherwise you advise me to use pg-error but here I don't find the way how to interface it with pg-promise: [pg-error-pg-postgres](https://github.com/moll/node-pg-error#using-with-nodejs-postgresql-client-library)

**Comment by vitaly-t** [comment]
>So what is the way in your lib to hook up an errors and customize it?

There is no error customization in the library.

> I don't find the way how to interface it with pg-promise

I've just looked it it, and it seems kind of obsolete.

You can see how this guys just did it, and perhaps do something similar: https://github.com/evvvvr/q-and-a/blob/345476b509ad5ffb5e001d4428f583753b7c44d3/src/DbService.js

**Comment by vieks** [comment]
> [...] The library provides you with all the error details. All you need is to parse is you you see fit.

Yes details are nice, but the error instance have the type Error not a type inherited from Error that permit to discern it with an ```error instanceof ...``` check.

> You can see how this guys just did it, and perhaps do something similar, for the special types of errors that you want to catch: https://github.com/evvvvr/q-and-a/blob/345476b509ad5ffb5e001d4428f583753b7c44d3/src/DbService.js

Error thrown by pg-promise when an integrity constraint violation occurs have the code ```23505```so that guy make:

```javascript
.catch((err) => {
  if (err.code === PgErrorCodes.FOREIGN_KEY_VIOLATION /*23503 for foreign key*/) {
      throw new QuestionNotFoundError();
  } else {
      throw err;
  }
} );
```

so transposed to my code:

```javascript
} catch(error) {

      if(error instanceof ValidationError){
        // ...
      }else if(error instanceof BcryptError){
        // ...
      /* We can't use instanceof operator here*/
      }else if(error.code === db.INTEGRITY_CONSTRAINT_VIOLATION){
        
    }
```
IT'S QUITE UGLY ! Ok for checking status error code inside the clause but not at this level of check, it will be way better that way:

```javascript
} catch(error) {

      if(error instanceof ValidationError){
        // ...
      }else if(error instanceof BcryptError){
        // ...
      /* We can't use instanceof operator here*/
      }else if(error instanceof DatabaseError){ // or PgError, whatever
        const res = handlerDatabaseCode(error.code)
        // ... or use an switch statement here
        return res;
    }
```

Now IT'S NICE ERROR CODE handling :) , but we can't do it actually only because pg-promise throws raw Error and not a single one which is inherited from Error. Due to that, we lose the power to use ```instanceof``` operator.

**Comment by vitaly-t** [comment]
>Error thrown by pg-promise when an integrity constraint violation occurs

pg-promise doesn't throw those errors, `node-postgres` does, and pg-promises only passes them on.

If you want additional interpretation for such errors, you will have to implement it on your side. Parsing those error objects is simple enough.

**Comment by vitaly-t** [comment]
Here's an example of how you can approach this:

```js
db.any("SELECT * FROM Users")
    .then(data=> {
        // success
    })
    .catch(parseError)
    .catch(error=> {
        if (error instanceof MyCustomError) {
            // do something...
        }
    })
    .finally(pgp.end);


function parseError(error) {
    // parse 'error', and throw an error accordingly;
    throw new MyCustomError("my custom error type");
}
```

**Comment by vitaly-t** [comment]
P.S. That's the best I can advise you. pg-promise won't do it for you, as it would completely break compatibility with all the previous versions. Developers are used to parsing node-postgres errors on their own.

**Comment by vieks** [comment]
It's bad node-postgres does not implement its own Error class. So I thought that pg-promise as a wrapper abstraction layer was a good opportunity to correct this behavior. But as you said:

> it would completely break compatibility with all the previous versions

Your code to correct this issue:
```javascript
db.any("SELECT * FROM Users")
    .then(data=> {
        // success
    })
    .catch(parseError)
    .catch(error=> {
        if (error instanceof MyCustomError) {
            // do something...
        }
    })
    .finally(pgp.end);


function parseError(error) {
    // parse 'error', and throw an error accordingly;
    throw new MyCustomError("my custom error type");
}
```

Is pretty nice for an ES6 promise style.
But with ES7 async syntactic sugar we can't chaining catch clause like that, so finally I create a little wrapper on it to prevent code bloating and handle all exceptions under the hood. The result IMHO is really nice.

Code snippets for those reading this topic later:

Handle user input request (no more try/catch needed)
```javascript
  async mutateAndGetPayload(payload, { rootValue: { mutation, conf } }) {
    d(payload);

    validator.check(input);
    
    payload.role       = role.BASIC;
    payload.status     = status.UNREGISTERED;
    payload.created_at = payload.updated_at = +new Date;
    payload.pass       = await bcrypt.hashAsync(payload.pass,
                                                conf.BCRYPT_ROUNDS);

    return await mutation('user.create', payload);
  },
```

PostgreSQL raw error codes mapping to javascript exception classes
```javascript
import * as errors from '../../errors';


export default {

  /* INTEGRITY_CONSTRAINT_VIOLATION */
  '23505': errors.DatabaseIntegrityConstraintError,

 // [...]
};
```

The interesting part which hiding the raw exceptions pulls up by pg-promise/node-postgres
```javascript
import {
  queries,
  mutations,
} from './actions';
import {
  DatabaseError,
} from '../errors';
import errorCodes from './postgres/error-codes';


// [...]

async function mutation(
  action: string,
  payload: Object,
): Promise<?Object | DatabaseError> {
  return await mutations[action](payload).catch(error => {
    const Exception = errorCodes[error.code];

    if(Exception)
      throw new Exception;

    throw new DatabaseError;
  });
}

export { query, mutation };
```

Done, it works like a charm.
Thanks for your support and the time you took @vitaly-t :)

**Comment by vitaly-t** [comment]
>Thanks for your support and the time you took

You are welcome!

It is worth point out that while the raw errors may look like an inconvenience in some cases, they are consistent with how  node-postgres reports them, and many pg-promise users come from node-postgres, which makes the whole error layer transparent and 100% compatible, and those are good things ;)

**Comment by vitaly-t** [comment]
@vieks 

Now that pg-promise [supports native bindings](https://github.com/vitaly-t/pg-promise/releases/tag/v.3.5.0), it will urk you more to know that errors are reported totally different under native bindings. This has been and continue to be a big pain for everyone who uses `node-postgres`, but no solution exists, as there is no alternative postgres driver.

As a hope, there is a discussion open lately about this, yet again: https://github.com/brianc/node-postgres/issues/972

**Comment by vieks** [comment]
Thanks @vitaly-t for relaying the information. Indeed it seems being messy.
