### ISSUE TITLE
How to handle multiple users

### ISSUE THREAD

**Issue by jcristovao** [vitaly-t/pg-promise#110]
Hi,

I was just wondering, how would you approach multiple (postgres) users.
After some googling I found [this](https://github.com/brianc/node-postgres/issues/936), which seems to recommend:

> a) use a global pg instance and change the connectionString in pg.connect (with user:password stored in session) for each request (API endpoint)

Would this mean something like:

```
var options = { user: userX, ... };

 var pgp = new pgpLib();

var dbUserX = pgp(options);

```

Or is there any other way you would recommend?
Thanks

**Comment by vitaly-t** [comment]
From [Getting Started](https://github.com/vitaly-t/pg-promise#getting-started):

> You need only one database instance per connection details.

You have separate `db` instances for different connection objects/strings.

**Comment by jcristovao** [comment]
So, exactly as I did above, right?
Thanks!

**Comment by vitaly-t** [comment]
>So, exactly as I did above, right?
Ahm, possibly, wasn't too clear to me :)

**Comment by jcristovao** [comment]
Ok, just updated the example :)

**Comment by vitaly-t** [comment]
It still looks strange, as this:
```js
var pgp = new pgpLib();
```
isn't used anywhere in the library...

**Comment by vitaly-t** [comment]
On an unrelated matter, you wanted to contribute into a TypeScript conversion of the library.

If you still want to do it, I'm looking at getting started with it, and I will make you a collaborator ;)

**Comment by vitaly-t** [comment]
@jcristovao if you have time, we can chat here: https://gitter.im/vitaly-t/pg-promise?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge

**Comment by jcristovao** [comment]
Ah, that... Just non standard naming on my part ;)

`const pgpLib    = require('pg-promise');`
