### ISSUE TITLE
[Question] Performance Boost code snippet

### ISSUE THREAD

**Issue by vieks** [vitaly-t/pg-promise#111]
This is not related directly to pg-promise, but about the object structure used in your example:

```javascript
joinQueries([
            {"INSERT INTO Users(name, age) VALUES($1, $2)": ['John', 23]},
            {"DELETE FROM Log WHERE userName = $1": 'AddUser'},
            "SELECT count(*) FROM Users"
        ])
```

You have used values (sql queries) as object keys. For sure all strings are allowed as Object keys but I was wondering if this can have a penalty due to lookup hash table used by JS engine ??? Do you know if a long string as key (so a long SQL query) can impact performance compared to that more common object pattern:

```javascript
joinQueries([
            { query: "INSERT INTO Users(name, age) VALUES($1, $2)", params: ['John', 23]},
            { query: "DELETE FROM Log WHERE userName = $1", params: 'AddUser'},
            "SELECT count(*) FROM Users"
        ])
```

The last one have more keys so must take more space (relatively), but can you tell me more about your pattern, pros/cons compared to the other solution ? It's interesting to know.

**Comment by vitaly-t** [comment]
>I was wondering if this can have a penalty due to lookup hash table used by JS engine 

No, no penalty in such case.

>The last one have more keys so must take more space

Much more space, because you are not considering the full syntax supported:

from the comments there:
>... or multiple ones, if the order of executing such queries is unimportant

i.e. you can write:
{
   "INSERT INTO Users(name, age) VALUES($1, $2)": ['John', 123]
   "INSERT INTO Users(name, age) VALUES($1, $2)": ['Mike', 456]
   "INSERT INTO Users(name, age) VALUES($1, $2)": ['David',789 ]
}

**Comment by vitaly-t** [comment]
The bottom line, there is nothing complex there, you can tweak it any way you like, i.e. have completely your own version of `joinQueries`, if you like ;)

**Comment by vieks** [comment]
Ok thanks a lot I get it.

> No, no penalty in such case.

Do you know when it start to be ?


> The bottom line, there is nothing complex there, you can tweak it any way you like, i.e. have completely your own version of joinQueries, if you like ;)

This is exactly what I was starting to do but it's obvious you are not doing things without a good reason :) that's why I wanted to know more about your choice of of ```{ ['SQL']: params }``` which is not a usual case (long string goes normally as value not key).

**Comment by vitaly-t** [comment]
My version was the simplest and the shortest. That's all ;)

**Comment by vieks** [comment]
Understood Sir ;)

**Comment by vitaly-t** [comment]
@vieks Something that article doesn't mention yet...

When you are designing the system yourself, most of the IO optimization can be done by moving query sequences into PostgreSQL functions ;)

**Comment by vieks** [comment]
Stored procedures at Postgres server so the client send only parameters to them ?
It needs to know PL/SQL so having DBA skill, it's more advanced/specific stuff for a full stack dev I think.

Or I mislead and you speak about other thing ?

**Comment by vitaly-t** [comment]
Like I said, if you are designing the system ;) that implies you know what you are doing :)

**Comment by vieks** [comment]
Lol yeah ok :)

(sorry I don't grab all sentence meaning directly I am sh*t in english )

**Comment by vieks** [comment]
But thanks for all your advises (here from issues and wiki+page lib)

**Comment by vitaly-t** [comment]
@vieks I was thinking, that from the re-usability point of view, it would be better to have a version that uses an object property, like:
```js
{query, values}
```
because the example in the article is useless for dynamically loaded SQL ;)

**Comment by vitaly-t** [comment]
@vieks with that in mind, I have re-implemented the example ;)

**Comment by vieks** [comment]
Nice thank you.

**Comment by vitaly-t** [comment]
**UPDATE:**
There is lots more the library offers now with the [helpers namespace](http://vitaly-t.github.io/pg-promise/helpers.html) when it comes to automatic query generation for `INSERT` or `UPDATE` operations.
