### ISSUE TITLE
Question about "Inserts" function from the "Performance-Boost" section.

### ISSUE THREAD

**Issue by AriaFallah** [vitaly-t/pg-promise#112]
In this function:

```javascript
function Inserts(template, data) {
    if (!(this instanceof Inserts)) {
        return new Inserts(template, data);
    }
    this._rawDBType = true;
    this.formatDBType = function () {
        return data.map(d=>'(' + pgp.as.format(template, d) + ')').join(',');
    };
}
```

what is the point of this block of code?

```javascript
if (!(this instanceof Inserts)) {
    return new Inserts(template, data);
}
```

I've never seen anything like it before.

**Comment by vitaly-t** [comment]
This is a very standard way of checking how the code was invoked - as a class or as a function.

And if it was called as a function, it is automatically translated into a class that way.

**Comment by AriaFallah** [comment]
@vitaly-t why not just enforce always using the `new` keyword instead of doing this?

**Comment by vitaly-t** [comment]
Enforce? You mean to throw an error? That'd wouldn't be friendly :)

**Comment by AriaFallah** [comment]
Thank you! I appreciate how well maintained this library is. Finding it, and seeing 0 issues was really reassuring.

**Comment by vitaly-t** [comment]
n.p. ;)

**Comment by vitaly-t** [comment]
F.Y.I. Important breaking change in [v6.5.0](https://github.com/vitaly-t/pg-promise/releases/tag/v.6.5.0).
