### ISSUE TITLE
Fetch error summary in the catch block

### ISSUE THREAD

**Issue by madhavan020985** [vitaly-t/pg-promise#113]
When there is an error after a DB operation, i like to take the error summary and send it back to the browser. When i  print error object using console.log, it shows, 
````
{ [error: null value in column "text" violates not-null constraint]
  name: 'error',
  length: 170,
  severity: 'ERROR',
  code: '23502',
  detail: 'Failing row contains (14, null, f).',
   ....................
}
````

Now how does, `err` object show a list item inside the map/object as, `[error: null value in column "text" violates not-null constraint]`.  How can one parse this summary message from the `err` object and send it on wire.

Just fyi, my express router looks like this,
````
router.get('/api/v1/todos', function(req, res){
  db.any("select * from itemss")
    .then(function (data) {
      console.log(data)
      res.json(data)
    })
    .catch(function (error) {
      return res.status(500).json({ success: false, data: error[0]['error']})
    });
})
````

**Comment by vitaly-t** [comment]
to get summary message:
```js
data: error.message || error
```
this is not any any way specific to this library, this is just a generic error that arrives from PostgreSQL, and a generic way to get summary from any error context.
