### ISSUE TITLE
pgp typescript typings initialization issues

### ISSUE THREAD

**Issue by awdogsgo2heaven** [vitaly-t/pg-promise#117]
PGP's current TypeScript definition files has issues with initialization, I have got it to work a little bit closer to where it should by making these changes below:

```javascript
function pgPromise(options?: pgPromiseOptions): pgMain;

// Default library interface (before initialization)

// API: http://vitaly-t.github.io/pg-promise/module-pg-promise.html

export interface pgPromiseOptions extends pgRoot {

  pgFormatting?: boolean;

  pgNative?: boolean,

  promiseLib?: any;

  connect?: (client: Client) => void;

  disconnect?: (client: Client) => void;

  query?: (e: EventContext) => void;

  receive?: (data: any[], result: any, e: EventContext) => void;

  task?: (e: EventContext) => void;

  transact?: (e: EventContext) => void;

  error?: (err: any, e: EventContext) => void;

  extend?: (obj: any) => void;

  noLocking?: boolean;

  capSQL?: boolean;

}



export default pgPromise;
```

This fixes the intellisense when using PGP with typescript, but the generated code is still off, as this:

```javascript
'use strict';

import pgp from 'pg-promise';

const pgInit = pgp();
export const db = pgInit("");
```

becomes:

```javascript
'use strict';
const pg_promise_1 = require('pg-promise');
const pgInit = pg_promise_1.default();
exports.db = pgInit("");
```

I believe this is because of the multiple exports in the typing definitions, so when translating the code, it believes it needs to call .default, which isn't the case. Alot of other typings I see would end with export = pgPromise instead, but you can't do that if your exporting any other classes in the module. There may be around this with namespaces. I'll try a few other ideas but wanted to post this issue to let anyone else contribute as I'm pretty new to TypeScript myself.

**Comment by vitaly-t** [comment]
Thank you for your findings.

How did you overcome the issue with including the dependent modules? Did you not have problems there saying that it couldn't find "pg" or "pg-minify"?

**Comment by vitaly-t** [comment]
After much more effort and many questions asked on StackOverflow I was able to make some nice improvements.

The version currently checked in seems quite usable.

**Comment by vitaly-t** [comment]
I have been able to solve all the problems, and [made an official release](https://github.com/vitaly-t/pg-promise/releases/tag/v.3.7.6).

**Comment by awdogsgo2heaven** [comment]
@vitaly-t Looks like I was heading in the right direction with the function and namespace, glad you were able to finish this! I'll check it out tonight and get back with you.

**Comment by awdogsgo2heaven** [comment]
Looks good @vitaly-t! Thanks.

**Comment by vitaly-t** [comment]
@awdogsgo2heaven You may find [release 3.7.8](https://github.com/vitaly-t/pg-promise/releases/tag/v.3.7.8) to be a good further improvement.
