### ISSUE TITLE
'select count(*) from foo' will return the count as a string

### ISSUE THREAD

**Issue by OnionCoder** [vitaly-t/pg-promise#118]
I am running the query 'select count(*) from foo' and it return the count as a string type. Is there a way that I can make the count as a number without explicitly casting it using Number().

**Comment by vitaly-t** [comment]
>Is there a way that I can make the count as a number without explicitly casting it using Number().

No.

See also in the demo: https://github.com/vitaly-t/pg-promise-demo/blob/master/db/repos/products.js

```js
    total: () => rep.one("SELECT count(*) FROM Products")
            .then(data => parseInt(data.count))
```
that's the right way to do it.

**Comment by OnionCoder** [comment]
I see pg-promise uses node-postgres, is it the implementation of node-postgres or it is just the natural behavior of postgres itself?

**Comment by vitaly-t** [comment]
I honestly don't know. You can check that yourself. All type conversions are done by [pg-types](https://github.com/brianc/node-pg-types).

**Comment by OnionCoder** [comment]
Thanks, I will check it out there. :smiley:

**Comment by vitaly-t** [comment]
@OnionCoder did you get to the bottom of it?

**Comment by OnionCoder** [comment]
When I call count(*) in postgres it returns a 64-bit bigint type number. But Javascirpt does not support 64-bit integers (which is also mentioned in pg-types). So it will be converted to string.

**Comment by vitaly-t** [comment]
Proper explanation: [pg-promise returns integers as strings](http://stackoverflow.com/questions/39168501/pg-promise-returns-integers-as-strings).

**Comment by vitaly-t** [comment]
Further development on the subject - [BigInt Support](https://github.com/vitaly-t/pg-promise/issues/657).
