### ISSUE TITLE
Error: Loose request outside an expired connection.

### ISSUE THREAD

**Issue by ferdinandsalis** [vitaly-t/pg-promise#120]
I get the following error: `error: Loose request outside an expired connection.` using bluebird as promise library. I am quite clueless as to why. 

```js
all: () => rep.task('artists with artworks', t =>
  t.any(sql.all).map(artist => {
    const artworks = t.any('SELECT * FROM artworks WHERE artist_id=${id}', artist).return(artworks)
    artist.artworks = artworks;
    return artist;
  })),
```

Very much appreciate any help. Thanks.

**Comment by vitaly-t** [comment]
All these requests are loose:
```js
const artworks = t.any('SELECT * FROM artworks WHERE ${id}', artist).return(artworks)
```
i.e. they are not getting chained to anything.

**Comment by ferdinandsalis** [comment]
How would I chain them?

Amazing support by the way.

**Comment by vitaly-t** [comment]
I'm not very familiar with method `map` of Bluebird. What are you trying to achieve there?

**Comment by ferdinandsalis** [comment]
I want to retrieve all artists with their related artworks.

**Comment by ferdinandsalis** [comment]
Sorry for not providing more detail. I feel inadequate to go more into depth.

**Comment by vitaly-t** [comment]
The problem of your algorithm is the fact that method `map` returns an array full of promises, without binding them to the context of the current task.

If you look at all the examples of resolving the array of promises, we use method `batch` for that always. You are bypassing that, not resolving the inner promises, they become loose, hence the result.

**Comment by vitaly-t** [comment]
This simplified example would resolve with an array of results from the inner requests.
```js
rep.task('artists with artworks', t =>
    t.any(sql.all)
        .then(artists=> {
            return t.batch(artists.map(a=>{
                return t.any('SELECT * FROM artworks WHERE id=${id}', a.id);
            }));
        }));
```
you would just add the additional mapping logic as you need.

**Comment by ferdinandsalis** [comment]
Thanks, you have been very helpful.

**Comment by ferdinandsalis** [comment]
This is what I ended up with. Doesnt feel to elegant though ☺️.

```
rep.task('artists with artworks', t =>
  t.any(sql.all).then(artists => {
    return t.batch(artists.map(artist => {
      return t.any('SELECT * FROM artworks WHERE artist_id=${id}', artist)
        .then(artworks => {
          artworks.length && (artist.artworks = artworks)
          return artist
        });
    }))
  }))
```

**Comment by vitaly-t** [comment]
Maybe there is a way to optimize it with Bluebird, somehow, I don't know.

At least this looks correct.

**Comment by vitaly-t** [comment]
You can compress it to this:
```js
rep.task('artists with artworks', t =>
    t.any(sql.all)
        .then(artists =>
            t.batch(artists.map(artist =>
                t.any('SELECT * FROM artworks WHERE artist_id=${id}', artist)
                    .then(artworks => {
                        artworks.length && (artist.artworks = artworks);
                        return artist;
                    })
            ))
        ));
```
and to me it looks quite elegant, and readable ;)

**Comment by ferdinandsalis** [comment]
Yup! 🖖 Now figuring out where that would go in the repository pattern. Thanks again. I am enjoying learning sql through your library.

**Comment by vitaly-t** [comment]
[pg-promise-demo](https://github.com/vitaly-t/pg-promise-demo) is a good example to understand the pattern ;)

Also, I forgot about the second optional parameter in method [batch](https://github.com/vitaly-t/spex/blob/master/docs/code/batch.md), using which you can re-implement your code like this:

```js
rep.task('artists with artworks', t =>
    t.any(sql.all)
        .then(artists =>
            t.batch(artists, (_, _, artist)=>{
                return t.any('SELECT * FROM artworks WHERE artist_id=${id}', artist)
                    .then(artworks=>{
                        artist.artworks = artworks;
                    });
            })
        ));
```
in case you think it looks any better ;)

**Comment by vitaly-t** [comment]
A detailed example for this was added here: [Get a parents + children tree with pg-promise](http://stackoverflow.com/questions/37664258/get-a-parents-children-tree-with-pg-promise)
