### ISSUE TITLE
Convenience methods

### ISSUE THREAD

**Issue by L-u-k-e** [vitaly-t/pg-promise#123]
Are there any convenience methods available that can infer the proper query syntax from the data containers themselves, rather than requiring a string?

For example, imagine a function like `db.insert_one(table_name, object)` for which the following invocation:
   
```
var my_video =  {id: ''CPgCDlOE09A', title: 'My Title', duration: 400.04, ... };
db.insert_one('video', my_video);
```

is equivalent to:

```
db.one('insert into video (id, title, duration, ...) ' +
'values ( $(id) $(title) $(duration) ... )', my_video);
```

The function can infer the column name directly from the keys. As an example implementation consider the following (I'm using lodash here, but this is all directly translatable to vanilla): 

```
var create_insert_statement = function (table_name, obj) {
	var keys = _.keys(obj);
	var string = 'insert into ' + table_name + ' ' + 
		'(' + keys.join(', ') + ') ' +
		'values (' + _.map(keys, function(s) { return '$('+s+')'}).join(', ') + ')';
	return string;	
};
```

If these functions don't exist, is there an interest in creating them/does anyone have any suggestions? (I'd be happy to contribute)

**Comment by vitaly-t** [comment]
Duplicate of #49

**Comment by L-u-k-e** [comment]
Thanks!

**Comment by vitaly-t** [comment]
@L-u-k-e This is going to change soon. I have started working on 4.1.0 that will introduce [`helpers` namespace](http://vitaly-t.github.io/pg-promise/helpers.html) with all the new useful functions ;)

**Comment by L-u-k-e** [comment]
Awesome!

**Comment by vitaly-t** [comment]
@L-u-k-e I have done a lot of work for this [here](https://github.com/vitaly-t/pg-promise/tree/master/lib/helpers), but it turned out to be a lot more complicated than was initially thought.

A truly generic approach requires so many extra considerations, it's crazy :)

I've got the initial draft working, but there is still a lot of work before it can be released.

**Comment by vitaly-t** [comment]
@L-u-k-e Would you like to have a look at what has been done so far? - [release 4.0.6](https://github.com/vitaly-t/pg-promise/releases/tag/v.4.0.6).

It would be nice to get some feedback ;)

**Comment by L-u-k-e** [comment]
@vitaly-t Definitely. I have a ton of work to do on a project tonight and I will be receiving my bachelors degree tomorrow, so this weekend might not be so productive on that front, but Monday after work  I will definitely get to this.

**Comment by vitaly-t** [comment]
@L-u-k-e any luck there? :)

**Comment by L-u-k-e** [comment]
Sorry. I've been busy. I'm actually at work right now. I won't be able to look deeper until later tonight. I was looking at the Documentation and one question I have is as follows:

For the UPDATE and SELECT queries, you are currently requiring an array of column names when doing a multi values insert/update. What was the reasoning behind that decision?

**Comment by vitaly-t** [comment]
>For the UPDATE and INSERT queries, you are currently requiring an array of column names when doing a multi values insert/update. What was the reasoning behind that decision?

The fact that the array may contain heterogeneous objects, you can't assume any of them to be a full object. Plus you will frequently need a more detailed configuration for columns, if you consider things like:

* default values for non-existing properties;
* value overrides

**Comment by L-u-k-e** [comment]
Regarding the heterogeneous objects: The library function could just infer, then group together the objects have the same set of column names, no? The point about needing more information in general is definitely valid though.


Additionally, I see that we are requiring users to add their own WHERE's to the update statement. I was thinking about ways to do that on my own and I also concluded that you can't offer the same about of expressiveness without making the syntax more pedantic than it already is. However, since the goal is to provide convenience methods, not necessarily the entire SQL functionality, what about allowing a simple object to be passed in for the WHERE, whose property name/value relationship always translated to '=' and whose property/property relationship is always 'AND'. E.G. {ID: my_id}

**Comment by L-u-k-e** [comment]
Tonight I'll actually dive into the code. Maybe I'll take a stab at doing a SELECT just to get the ball rolling, but more likely I'll spend the time just reading the code getting a better feel for things.

**Comment by vitaly-t** [comment]
>The library function could just infer, then group together the objects have the same set of column names, no?

It would make the whole solution very inefficient performance-wise.

`ColumnSet` type is thoroughly optimized to generate queries as fast as possible.

>what about allowing a simple object to be passed in for the WHERE, whose property name/value relationship always translated to '=' and whose property/property relationship is always 'AND'. E.G. {ID: my_id}

That's a lot of assumption. Real use cases can include way more complex conditions. I wanted to keep it as simple and as generic as possible.

**Comment by vitaly-t** [comment]
>Maybe I'll take a stab at doing a SELECT just to get the ball rolling

Did you mean `INSERT`?

**Comment by L-u-k-e** [comment]
Actually, I meant that I would branch and attempt to write a SELECT helper. However, since you've expressed a desire to keep the WHERE clause generation separate from these helpers, that pretty much also throws GROUP BY, HAVING etc. out the window, so would you agree that it would be in best interest not to create a helper for SELECT statements?

**Comment by vitaly-t** [comment]
I was never even considering to create a `SELECT` helper. There is no point. What I created for `INSERT` and `UPDATE` is to simplify the complexity of generating all those queries, to get them formatted correctly, in a dynamic-object environment, and especially for multi-object operations.

A `SELECT` operation does not need any of that.

**Comment by vitaly-t** [comment]
@L-u-k-e I didn't get anymore feedback from you, and I have released the new feature as v.4.1.0.

**Comment by vitaly-t** [comment]
@L-u-k-e I have added an example for type `ColumnSet`: http://vitaly-t.github.io/pg-promise/helpers.ColumnSet.html

this should help understand better why using such an object is a good idea in general, and what kind of situations one can typically run into when automatically generating inserts or updates.
