### ISSUE TITLE
bigint comes back as string instead of integer

### ISSUE THREAD

**Issue by kittles** [vitaly-t/pg-promise#128]
is there a way columns with type bigint can come back to client as integer, not string?

**Comment by vitaly-t** [comment]
They shouldn't because `bigint` is 64-bit, which isn't supported by JavaScript.

You can override it within `pg`:

```js
// numeric
pgp.pg.types.setTypeParser(1700, function (value) {
    return parseFloat(value);
});

// bigint
pgp.pg.types.setTypeParser(20, function (value) {
    return parseInt(value);
});
```

But that implies you will be losing numbers pass 32 bit (4294967296).

**Comment by vitaly-t** [comment]
Best explanation: [pg-promise returns integers as strings](http://stackoverflow.com/questions/39168501/pg-promise-returns-integers-as-strings).

**Comment by ForbesLindesay** [comment]
This answer isn't quite right.  It will actually be fine until `2⁵³ - 1` because JavaScript number become doubles once they exceed the 32-bit range, giving them 53 bits.

**Comment by vitaly-t** [comment]
@ForbesLindesay the link that was provided gives all the proper explanation.

> Best explanation: [pg-promise returns integers as strings](http://stackoverflow.com/questions/39168501/pg-promise-returns-integers-as-strings).

**Comment by vitaly-t** [comment]
Update on this topic - [BigInt Support](https://github.com/vitaly-t/pg-promise/issues/657).
