### ISSUE TITLE
query config, rowMode

### ISSUE THREAD

**Issue by matus123** [vitaly-t/pg-promise#129]
Hello,

Is it possible to send queryconfig ('rowMode':'array') to any of query method provided by pgp promise library?

Similar to one implemented in this pr https://github.com/brianc/node-postgres/pull/393

thank you

**Comment by vitaly-t** [comment]
This is an excellent question! I haven't used that feature, and completely forgot it was there, which introduced a problem in version 4.x

Right up until version 4.0.0 Prepared Statements were only used directly, as a simple, object. As a result, setting `rowMode: 'array'` would have always worked, even though I never thought of it.

But version 4.x introduced new type [PreparedStatement]() that proxies those objects, and it is missing support for parameter `rowMode`. As a result, version 4.x broke the support for `rowMode`.

Thank you so much for checking this back with me!

I am elevating this to bug, and will address this issue right away.

In the meantime, you can start with any 3.x version , where it still worked correctly.

**Comment by matus123** [comment]
I was thinking if it possible to pass object, which would contains query and rowMode similar to this example in pure PG

```
pg.connect(conString, function(err, client, done) {
  if(err) {
    return console.error('error fetching client from pool', err);
  }
  // client.query(`SELECT 'name1' as name, 'name2' as name`, function(err, result) {
  //   //call `done()` to release the client back to the pool
  //   done();

  //   if(err) {
  //     return console.error('error running query', err);
  //   }
  //   console.log(result);
  //   //output: 1
  // });

  client.query({text: `SELECT 'name1' as name, 'name2' as name`, rowMode: 'array'}, function(err, result) {
    //call `done()` to release the client back to the pool
    done();

    if(err) {
      return console.error('error running query', err);
    }
    console.log(result);
    //output: 1
  });
});
```

If it is possible to write something similar with pgp library, for example using db.query(), where i would pass object containing query, values and rowMode, without using PreparedStatement

```
const query = {
	text: `Select 'name1' as name, 'name2' as name`,
	rowMode: 'array'
}

db.result(query)
.then((result) => {
  console.log(util.inspect(result,{depth:null}));
  pgp.end();
})
.catch((err) => {
  console.log(err);
});
```

**Comment by vitaly-t** [comment]
I was originally thinking about modifying the internal PreparedStatement object to allows those properties, but what you are suggesting refers to [Parameterized Queries](https://github.com/brianc/node-postgres/wiki/Prepared-Statements#parameterized-queries), which was never supported by `pg-promise`. It would have to be a new feature.

**Comment by vitaly-t** [comment]
@matus123 I have created [branch 4.1](https://github.com/vitaly-t/pg-promise/tree/4.1) which now contains the complete code with everything you need - support for all advanced properties within both Preppared Statements and Parameterized Queries.

You can use it for the time being. I will need to update a lot of documentation, plus add many new tests before I can merge into into the `master` and release.

**Comment by matus123** [comment]
Thanks a lot for fast reply, i will give it a try.

But wouldn't it be easier just to allow pass additionalProperties object to db.query() methods, so you wouldn't need to support pg parameterized queries, because you already have your own implementation.

Because main reason i asked the question about rowMode was that i have use case where i want to get result from db in form of arrays, because if query contains same column names, then the columns are discarded and i lost data. 

But, thanks a lot for fast implementation, i really appreciate it.

**Comment by vitaly-t** [comment]
>But wouldn't it be easier just to allow pass additionalProperties object to db.query() methods

That's what I implemented. What did you think was it? Just because I added an extra wrapper doesn't mean that you need to use it, it is optional, provided in place automatically when not used.

You still can write: `db.query({text:'select...', rowMode: 'array'})`

**Comment by vitaly-t** [comment]
[4.0.5 release](https://github.com/vitaly-t/pg-promise/releases/tag/v.4.0.5) has it all implemented ;)
