### ISSUE TITLE
Timestamp without timezone and JS Date

### ISSUE THREAD

**Issue by OrKoN** [vitaly-t/pg-promise#130]
Hi,

I have exactly the same problem using pg-promise as described here: http://stackoverflow.com/questions/20712291/use-node-postgres-to-get-postgres-timestamp-without-timezone-in-utc

How to solve it with pg-promise? Can I disable timestamp to JS Date conversion?

Thanks.

**Comment by vitaly-t** [comment]
Why not use the same solution as published there?

**Comment by OrKoN** [comment]
Thanks, the solution is fine. Now I know how to access the pg instance.

**Comment by vitaly-t** [comment]
[How to access the instance of node-postgres that's used?](https://github.com/vitaly-t/pg-promise/wiki/FAQ#how-to-access-the-instance-of-node-postgres-thats-used)

plus [pg in API](http://vitaly-t.github.io/pg-promise/module-pg-promise.html#~pg) ;)

**Comment by OrKoN** [comment]
Some minor issue with the website, bwt

![screen shot 2016-05-04 at 1 15 05 pm](https://cloud.githubusercontent.com/assets/399150/15012605/56f13ec6-11fa-11e6-85cd-a426ce275506.png)

**Comment by vitaly-t** [comment]
Some caching issues perhaps? Try Ctrl+0, and then Ctrl+F5 ;)

**Comment by ferdinandsalis** [comment]
I see the same issue with the website. Hard refresh renders no change.

**Comment by vitaly-t** [comment]
That is in interesting. I have here all browsers (Chrome, FireFox, IE), none of them show the problem your showed me. I wonder now how to reproduce this issue...

**Comment by vitaly-t** [comment]
I have just updated it slightly. Does it look any better?

**Comment by ferdinandsalis** [comment]
Yes it does. No more overlapping. 👍

**Comment by OrKoN** [comment]
Yes, no overlapping. I am on Chrome Version 50.0.2661.94 (64-bit), Mac version. 
But still the font size is too big and the entire left menu does not fit the screen and it is not scrollable.

<img width="955" alt="screen shot 2016-05-04 at 1 36 31 pm" src="https://cloud.githubusercontent.com/assets/399150/15013031/46cd1508-11fd-11e6-997b-64cdbf8ab2b1.png">

**Comment by ferdinandsalis** [comment]
@vitaly-t if you want I could tackle that next week for you. I am a front end dev by trade ;)

**Comment by vitaly-t** [comment]
@ferdinandsalis thank you! so am I :) It's just that I do not see the problem here, which is what makes it harder to fix.

That API website is automatically generated, I am limited to a single CSS file that I'm tweaking.

I have just updated it again, reduced the overall font size. Might look better now ;)

**Comment by ferdinandsalis** [comment]
Yes better. Though I still can’t scroll the list on the left when my window size is not heigh enough. Giving the `.nav` container a fixed height, e.g. `position: fixed; top: 0; bottom: 0;` and setting the `overflow-y: scroll` should do the job.

**Comment by vitaly-t** [comment]
Should be better now ;)

**Comment by maovieira** [comment]
> 
> 
> Why not use the very solution that's already published there?
> 
> ```js
> var pgp = require('pg-promise')({
>     // initialization options
> });
> 
> pgp.pg.types.setTypeParser(1114, function (stringValue) {
>     return stringValue;
> });
> 
> // In ES6 syntax:
> // pgp.pg.types.setTypeParser(1114, s=>s);
> ```

Thanks for your comment. One cent: to force node-pg-types to parse TIMESTAMPTZ (1184) to the same value answered by PostgresQL use the same function but replace 1114 to 1184. I love the way postgresql deals with timestamptz so I always prefer to rely on it.
