### ISSUE TITLE
QueryFile don't support relative path

### ISSUE THREAD

**Issue by minipai** [vitaly-t/pg-promise#133]
Don't know where went wrong.

I have to do 
```
function sql(file) {
    var path = __dirname + '/sql/' + file;

    var options = {
        minify: true,
    };

    return new QueryFile(path, options);
}
```

but can't use the relative path in README.

**Comment by vitaly-t** [comment]
You must be getting the path wrong. Relative path does work fine in `QueryFile`, there is plenty of evidence to that.

**Comment by minipai** [comment]
Thanks for quick response. If I use
```
function sql(file) {
    var path = __dirname + '/sql/' + file;

    var options = {
        minify: true,
    };

    return new QueryFile(path, options);
}
```
Result is
```
QueryFile {
   file: "/Users/Art/Sites/bbs/server/db/sql/findPostsByBoard.sql"
   options: {"debug":false,"minify":true,"compress":false}
   query: ""
}
```

But, if I use
```
function sql(file) {
  console.log('sql')
    var path = './sql/' + file;

    var options = {
        minify: true,
    };

    return new QueryFile(path, options);
}
```

Result is 
```
QueryFile {
   file: "./sql/findPostsByBoard.sql"
   options: {"debug":false,"minify":true,"compress":false}
   error: QueryFileError {
       message: "ENOENT: no such file or directory, open './sql/findPostsByBoard.sql'"
       options: {"debug":false,"minify":true,"compress":false}
       file: "./sql/findPostsByBoard.sql"
   }
}
```
I think __dirname should be same as ./  as a relative path ?
Really confused.

**Comment by minipai** [comment]
I finally find out it is relative to my project root. Thanks.

**Comment by vitaly-t** [comment]
@minipai check out the new addition to Query Files: https://github.com/vitaly-t/pg-promise/issues/153

**Comment by minipai** [comment]
Wonderful !

**Comment by vitaly-t** [comment]
>I finally find out it is relative to my project root.

Not quite, only when your Node.js start-up file is in the root of your project, because the path is relative to your Node.js start-up file.
