### ISSUE TITLE
4.0.5->4.0.6 breaks other modules

### ISSUE THREAD

**Issue by djMax** [vitaly-t/pg-promise#135]
I'm using swagger-client and the act of requiring 4.0.6 or above causes it to fail because it SEEMS like some sort of object.prototype manipulation is happening. Is this on purpose?

**Comment by djMax** [comment]
Modifying Array.prototype is a very bad practice. That's happening here:

https://github.com/vitaly-t/pg-promise/blob/master/lib/array.js#L90

Not sure that's what's blowing things up, but it's definitely not something a module should do.

**Comment by vitaly-t** [comment]
I should have read this one before following up on the PR :)

**Comment by vitaly-t** [comment]
Fixed in v.4.0.13
