### ISSUE TITLE
Add a Dockerfile to ease testing

### ISSUE THREAD

**Issue by Maxwell2022** [vitaly-t/pg-promise#138]
I was about to create a pull request to improve error handling when parsing the configuration when I noticed that the tests are running against all database type: `pg`, `mysql`, `sqlite3` and `mongodb`

It's not very trivial for anyone to install and configure all these database in order to test this library. I would recommend to create a docker-compose file that would take care of pulling the corresponding container and start them all.

I don't really have the time to look into it now, I'll have a look later this week if it's something that you would consider benefic.

**Comment by Maxwell2022** [comment]
Another solution would be to mock all the database drivers.

**Comment by vitaly-t** [comment]
>I was about to create a pull request to improve error handling when parsing the configuration

Which configuration parsing?

>I noticed that the tests are running against all database type: pg, mysql, sqlite3 and mongodb

What are you talking about? This is a PostgreSQL-only library. It doesn't support anything else, it has no tests for anything else.

>It's not very trivial for anyone to install and configure all these database

You really lost me on this one.

**Comment by Maxwell2022** [comment]
Sorry mate, wrong repo... I was meant to post this on `db-migrate`... too many tabs open :/

**Comment by Maxwell2022** [comment]
Awesome work by the way ;) Thank you!

**Comment by vitaly-t** [comment]
Cheers! :)
