### ISSUE TITLE
Not clear how connection pool works.

### ISSUE THREAD

**Issue by EvanCarroll** [vitaly-t/pg-promise#139]
I can't find it in the code, and it's not clear how the connection pool works. Is it based on the db handle, or is it global to the app? Ie, if we're building a webapp or something like that do I need to pass the db handle to everything that will use it? Or, can I simply call connect from the individual modules and rest on pg-promise having stored the pool on a global object?

**Comment by vitaly-t** [comment]
From the [Connection](https://github.com/vitaly-t/pg-promise#connection) section:

>Create a global/shared database object from the connection details:
```javascript
var db = pgp(cn);
```
>Object `db` represents the database protocol, with lazy database connection, i.e. only the actual query methods acquire and release the connection. Therefore, you should create only one global/shared `db` object per connection details.

**Comment by EvanCarroll** [comment]
Still not sure.

> Create a global/shared database object

What makes it global? That's a database handle, is it using the `global.` object to store the details? I would assume so from that.

> you should create only one global/shared db object per connection details.

But, why? If it's using the global object to store the pool it should realize the connection details are the same and return the same handle?

So again my question is how do we wire an app with this internal pool? Do we,

* call `pgp(cn)` with the same `cn` everywhere to get the same `db`?
* have to pass around a `db` to everything that uses the code?
* make no difference?

**Comment by EvanCarroll** [comment]
Perl provides both of these for a reference through [connect_cached](https://metacpan.org/pod/DBI#connect_cached) and [connect](https://metacpan.org/pod/DBI#connect).

**Comment by vitaly-t** [comment]
Check out [pg-promise-demo](https://github.com/vitaly-t/pg-promise-demo), maybe that will make it clear ;)

**Comment by EvanCarroll** [comment]
Yep, that makes it clear! That example is great. What you're doing is wrapping the handle in it's own package and not requiring `pg-promise` anywhere else. This makes sense and is clean, but it's not what the docs would have guided me into doing without that example. Well done.

**Comment by vitaly-t** [comment]
>What you're doing is wrapping the handle in it's own package and not requiring pg-promise anywhere else.

That's what everybody is doing, yes. I thought it was clear. Maybe not so much :)

**Comment by luthv** [comment]
sorry for resurrecting an old thread, I was trying the new managed Azure Postgres as a service offering from Azure, and I noticed that the idle connections was not released properly and I keep getting an exception stating that my application have reach the max connection limit set by Azure.

My understanding is that the connection pool is implemented by pg.Pool component from the base pg library, is this correct?

If so then the problem should be on Azure side that doesn't manage the connection properly. The Azure managed postgres service is still in preview release and I also have logged a question in their feedback forum, I just want to clarify my side of the infrastructure first.

**Comment by vitaly-t** [comment]
>  is that the connection pool is implemented by pg.Pool component from the base pg library, is this correct

No, this library uses version 5.1 of the driver that only uses the internal pool. See #206.

**Comment by luthv** [comment]
I see, thanks for clarifying that up.
Do you have any suggestion on how to investigate this problem with azure connection?
