### ISSUE TITLE
Confused

### ISSUE THREAD

**Issue by cybercoder** [vitaly-t/pg-promise#140]
I got confused
How i can insert fetched data into array?

This is not work:

    data=db.any("xxx xxx")
      .then(function (results) {
        return results
      });

**Comment by vitaly-t** [comment]
`results` is the array of fetched row objects.

**Comment by cybercoder** [comment]
and can access from outside of function?

**Comment by vitaly-t** [comment]
Your question seems to pertain to `how to use data returned from promises`, which isn't relevant to this library.

**Comment by cybercoder** [comment]
I just want to fetch a postgresql table data into an nodejs array, but i can't. It's craziness!

**Comment by vitaly-t** [comment]
Method `db.any` resolves with an array that contains rows-objects ready to be used.

There is absolutely nothing else to it. There only way one may not understand this is when you don't understand how promises work, which you should learn then.

There is nothing crazy here, it is all very trivial.

**Comment by cybercoder** [comment]
I used massive.js and it solved my problem, with that can fetch data into array, simply.

The craziness i mentioned was not about your promise, it was about i tried to fetch but i got deadlock.

Regards.

**Comment by vitaly-t** [comment]
There are no deadlocks in simple queries, and certainly not in the code that you showed.

**Comment by vitaly-t** [comment]
@cybercoder 

Do you want to show a full example of what you were doing?
