### ISSUE TITLE
Named Parameters vs Prepared Statements?

### ISSUE THREAD

**Issue by EvanCarroll** [vitaly-t/pg-promise#141]
Do Named Parameters use prepared statements under the hood? There is no mention of what is using prepared statements, or if to use them we need to do so explicitly?

**Comment by vitaly-t** [comment]
>Do Named Parameters use prepared statements under the hood?
NO

>There is no mention of what is using prepared statements

Nothing is using them, except your own code, in the format of `{name, text, values}`, or type `PreparedStatement` directly.

>if to use them we need to do so explicitly?
You don't (see above).

**Comment by EvanCarroll** [comment]
Why not make everything use them? That's [how other languages do it, afakik](https://metacpan.org/pod/DBD::Pg#prepare). It's the default in Perl for `SELECT`, `INSERT`, `UPDATE`, and `DELETE`?

> Setting pg_server_prepare to "1" means that prepared statements should be used whenever possible. This is the default when connected to Postgres servers version 8.0 or higher.

**Comment by vitaly-t** [comment]
That's not how `pg` library works. And I didn't want to override what it does, only to make it easier to use.

Prepared statements aren't that good really, they have their own problems.

First of all, they offer very limited query formatting, a tiny fraction of what `pg-promise` can do.

Second, there are situations when they perform slower than simple queries.
