### ISSUE TITLE
json support?

### ISSUE THREAD

**Issue by gniquil** [vitaly-t/pg-promise#15]
Sorry to ask this prematurely as I have not tried to use the library yet. But is there json support? Should I just treat a json column as normal and just use JSON.stringify/parse?

**Comment by vitaly-t** [comment]
As far as I know, Postgres deals with JSON as strings, so there is no need for any special JSON support. So yes, you can just do `JSON.stringify()` and then inject it as a parameter.

I will add another example in [Learn by Example](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example), to cover JSON usage.

**Comment by vitaly-t** [comment]
I was curious about JSON myself, so I did a full test:

Created a new table with JSON type and tried to insert and retrieve data, everything works exactly as expected.

I just have extended the [Learn by Example](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example) tutorial to include [INSERT JSON](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#insert-json) example.

I think it is now safe to close the issue. It was a very good question though :+1:

**Comment by gniquil** [comment]
!awesome! Thanks for response.

**Comment by vitaly-t** [comment]
@gniquil , just so you know, [release 0.9.8](https://github.com/vitaly-t/pg-promise/releases/tag/v.0.9.8) added native JSON support, among other things, so you no longer need to do manual serialization with `JSON.stringify` yourself.

[INSERT JSON](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#insert-json) has been updated accordingly.

**Comment by gniquil** [comment]
aweomse! :+1:

**Comment by vitaly-t** [comment]
@gniquil , Unrelated to this, but if you liked this library, I really appreciate if you can give me a feedback on this small addition: [pg-monitor](https://github.com/vitaly-t/pg-monitor)
