### ISSUE TITLE
Join Queries Results

### ISSUE THREAD

**Issue by RyanMcDonald** [vitaly-t/pg-promise#150]
The page here describes a technique to join multiple queries: https://github.com/vitaly-t/pg-promise/wiki/Performance-Boost

However, the example it gives doesn't seem to doing what it says:
```javascript
db.tx(t=> {
        return t.any(joinQueries([
            {query: "INSERT INTO Users(name, age) VALUES($1, $2)", values: ['John', 23]},
            {query: "DELETE FROM Log WHERE userName = $1", values: 'John'},
            "SELECT count(*) FROM Users"
        ]));
    })
    .then(data=> {
        // data[0] = undefined;
        // data[1] = undefined;
        // data[2].count = number of users;
    })
    .catch(error=> {
        // Error
    });
```
`data` in the above example is just the results of all three queries combined, rather than the results being separated into an array. So if I have multiple `SELECT` statements joined together, `data` is just all the selected records in one array, rather than `data[0]` being the results of the first `SELECT` and `data[1]` being the results of the second.

Is there a way to split up the results?

**Comment by vitaly-t** [comment]
This is the limitation of the underlying driver `node-postgres`. There was a PR to get this implemented: https://github.com/brianc/node-postgres/pull/776

But like many others, it never made it into the release.

**Comment by vitaly-t** [comment]
@RyanMcDonald 

[Version 7.0.0](https://github.com/vitaly-t/pg-promise/releases) now can do all that :wink:
