### ISSUE TITLE
error occurs when i use ON CONFLICT CLAUSE, postgres version is 9.5.3

### ISSUE THREAD

**Issue by zzeng4** [vitaly-t/pg-promise#151]
{ [error: syntax error at or near "ON"]
  name: 'error',
  length: 85,
  severity: 'ERROR',
  code: '42601',
  detail: undefined,
  hint: undefined,
  position: '533',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'scan.l',
  line: '1053',
  routine: 'scanner_yyerror' }

error occurs when i use ON CONFLICT CLAUSE, postgres version is 9.5.3 and it works when i test on console.

anyone knows what happened?

**Comment by vitaly-t** [comment]
This means there is a problem with your SQL query, not with this library.

**Comment by zzeng4** [comment]
INSERT INTO listing (unit_number) VALUES ('123123') ON CONFLICT (mls_id) DO UPDATE SET (unit_number) = (${unit_number}) WHERE listing.mls_id = ${mls_id};

this is my query.

**Comment by vitaly-t** [comment]
This is a query before formatting, which doesn't tell me anything.

**Comment by vitaly-t** [comment]
You can use `pgp.as.format(query, values)` to get the final query string.

**Comment by zzeng4** [comment]
INSERT INTO listing (unit_number) VALUES ('123123') ON CONFLICT (mls_id) DO UPDATE SET (unit_number) = (null) WHERE listing.mls_id = 'W3123123';

this is the final string,

and it works when i test it in console

**Comment by vitaly-t** [comment]
Works in console but not when executed from Node.js? I've never heard of such issues before. Are you sure about this?

**Comment by vitaly-t** [comment]
Something else is wrong there. According to your error log, the query being executed is invalid.

**Comment by zzeng4** [comment]
it might be the version misuse. How can I test whether the library is using the 9.5.3 version? as the ON CONFLICT clause is only released after 9.5.0+.

**Comment by vitaly-t** [comment]
The library would use whatever server you connect to.

You can check that:

```js
db.proc('version')
    .then(function (data) {
        // SUCCESS
        // data.version =
        // 'PostgreSQL 9.5.1, compiled by Visual C++ build 1800, 64-bit'
    })
    .catch(function (error) {
        // connection-related error
    });
```

**Comment by zzeng4** [comment]
this is my bad, i test it on my local server, which is the 9.5.3 and the one i am using is the remote server, which is 9.4.7.

that's why it doesn't work..

Thanks for help me......

**Comment by vitaly-t** [comment]
N.P.
