### ISSUE TITLE
Typings information requires adding reference path to source file

### ISSUE THREAD

**Issue by nareshbhatia** [vitaly-t/pg-promise#152]
```
pg-promise: version 4.3.5
typings: version 1.0.4
```
Hi, I am trying out pg-promise with TypeScript. The only way I am able to compile successfully is to add reference paths within my TypeScript files. For example:
```
/// <reference path='../../node_modules/pg-monitor/typescript/pg-monitor.d.ts' />
/// <reference path='../../node_modules/pg-promise/typescript/pg-promise.d.ts' />

import * as Promise from 'bluebird';
import * as pgMonitor from 'pg-monitor';
import * as pgPromise from 'pg-promise';
```

Is there a way to avoid putting reference paths in source files? For other libraries, I am able to install type definitions using typings and everything works. For example:

    typings install --save --global  dt~express

If I try to do the same thing with pg-promise, it doesn't work:

    typings install --save --global  dt~pg-promise

Now compile using `tsc` and I get the following error:

    error TS2307: Cannot find module 'pg-promise'.

For reference, here's my `tsconfig.json`:

```
{
    "compileOnSave": false,
    "compilerOptions": {
        "allowUnreachableCode": false,
        "allowUnusedLabels": false,
        "declaration": false,
        "emitDecoratorMetadata": true,
        "experimentalDecorators": true,
        "module": "commonjs",
        "noEmitOnError": true,
        "noFallthroughCasesInSwitch": true,
        "noImplicitAny": true,
        "noImplicitReturns": true,
        "noImplicitUseStrict": false,
        "noLib": false,
        "outDir": "./dist",
        "pretty": true,
        "removeComments": true,
        "sourceMap": true,
        "target": "es5"
    },
    "files": [
        "src/main.ts",
        "src/typings.d.ts"
    ]
}
```

**Comment by vitaly-t** [comment]
According to [the instructions](https://github.com/vitaly-t/pg-promise/tree/master/typescript#inclusion), you are supposed to add:

```js
{
  "globalDependencies": {
    "pg-promise": "github:vitaly-t/pg-promise#a79eb4bade0493e1edfb03600f5bd73ade8e6f49"
  }
}
```

Have you done so?

**Comment by nareshbhatia** [comment]
When I run the following command:

    typings install --save --global  dt~pg-promise

it automatically add the following to typings.json:

```
{
  "globalDependencies": {
    "pg-promise": "registry:dt/pg-promise#0.0.0+20160417141255"
  }
}
```

This is different from what you are showing. If I switch to your version, everything works fine.

I think the issue is due to the new version of typings (v 1.0.4). Older version (0.8.x) used to work differently. What version of typings are you using?

**Comment by vitaly-t** [comment]
I am using typings 1.0.4, and yes, there are a few differences.

**Comment by nareshbhatia** [comment]
Ok, will do. Thanks for the quick response.

**Comment by vitaly-t** [comment]
P.S. To install the same from the command line you would be using the following:

```
typings install --save --global  github:vitaly-t/pg-promise#a79eb4bade0493e1edfb03600f5bd73ade8e6f49
```

**Comment by nareshbhatia** [comment]
Ah, good to know!

**Comment by vitaly-t** [comment]
I have updated the [installation instructions](https://github.com/vitaly-t/pg-promise/tree/master/typescript#inclusion) to be much simpler.

**Comment by nareshbhatia** [comment]
Like it a lot! Thanks.

I am really enjoying using pg-promise.
