### ISSUE TITLE
Automatic SQL Trees

### ISSUE THREAD

**Issue by vitaly-t** [vitaly-t/pg-promise#153]
This is a new feature that I am working on.

It introduces a new namespace - [utils](http://vitaly-t.github.io/pg-promise/utils.html).

The main feature within that namespace is a set of methods that allow:
* Generating a camelized SQL tree from a folder path
* Generating code from a camelized SQL tree

It is to simplify development when you have many SQL files, to be able to generate an SQL tree, based on the file names and the folders structure, so you can access those directly from the code, either dynamically or explicitly - through generated code.

:mega: **Feel free contributing your ideas on this subject.**

**Example**
```js
// Generating a JavaScript module with complete SQL tree

var fs = require('fs');
var EOL = require('os').EOL;
var utils = require('pg-promise').utils;

// generating an SQL tree from the folder:
var tree = utils.enumSql('../sql', {recursive: true});

// generating the module's code:
var code = "var load = require('./loadSql');" + EOL + EOL + "module.exports = " +
        utils.objectToCode(tree, function (value) {
            return 'load(' + JSON.stringify(value) + ')';
        }) + ';';

// saving the module:
fs.writeFileSync('sql.js', code);
```
Because we keep the tree's object code separate from the module code, the same approach will work for TypeScript, Babel, or any other language that understands JSON notation.

See [enumSql](http://vitaly-t.github.io/pg-promise/utils.html#.enumSql), [objectToCode](http://vitaly-t.github.io/pg-promise/utils.html#.objectToCode).

Output example (file `sql.js`):

```js
var load = require('./loadSql');

module.exports = {
    events: {
        add: load("../sql/events/add.sql"),
        delete: load("../sql/events/delete.sql"),
        find: load("../sql/events/find.sql"),
        update: load("../sql/events/update.sql")
    },
    products: {
        add: load("../sql/products/add.sql"),
        delete: load("../sql/products/delete.sql"),
        find: load("../sql/products/find.sql"),
        update: load("../sql/products/update.sql")
    },
    users: {
        add: load("../sql/users/add.sql"),
        delete: load("../sql/users/delete.sql"),
        find: load("../sql/users/find.sql"),
        update: load("../sql/users/update.sql")
    },
    create: load("../sql/create.sql"),
    init: load("../sql/init.sql"),
    drop: load("../sql/drop.sql")
};
```

`loadSql.js` module example:
```js
var QueryFile = require('pg-promise').QueryFile;

module.exports = function(file) {
    return new QueryFile(file, {minify: true});
};
```

With this approach you can easily manage a project that uses a huge number of SQL files. And if you are using a strongly typed language like TypeScript, it becomes even more efficient, as breaking changes in the external SQL file structure won't go unnoticed, they will be reported during compile time.

**Comment by vitaly-t** [comment]
Initially released in [v.4.3.6](https://github.com/vitaly-t/pg-promise/releases/tag/v.4.3.6).

**Comment by vitaly-t** [comment]
All the work for this feature has been finalized with the release of [v.4.3.7](https://github.com/vitaly-t/pg-promise/releases/tag/v.4.3.7).

**Comment by vitaly-t** [comment]
Added new method [buildSqlModule](http://vitaly-t.github.io/pg-promise/utils.html#.buildSqlModule) in [v.4.3.8](https://github.com/vitaly-t/pg-promise/releases/tag/v.4.3.8) release.

Now the entire module can be generated automatically.

Simply calling the method:
```js
pgp.utils.buildSqlModule();
```

We can get a very nice output module:
```js
/////////////////////////////////////////////////////////////////////////
// This file was automatically generated by pg-promise v.4.3.8
//
// Generated on: 6/2/2016, at 2:15:23 PM
// Total files: 15
//
// API: http://vitaly-t.github.io/pg-promise/utils.html#.buildSqlModule
/////////////////////////////////////////////////////////////////////////

var load = require('./loadSql');

module.exports = {
    events: {
        add: load("../sql/events/add.sql"),
        delete: load("../sql/events/delete.sql"),
        find: load("../sql/events/find.sql"),
        update: load("../sql/events/update.sql")
    },
    products: {
        add: load("../sql/products/add.sql"),
        delete: load("../sql/products/delete.sql"),
        find: load("../sql/products/find.sql"),
        update: load("../sql/products/update.sql")
    },
    users: {
        add: load("../sql/users/add.sql"),
        delete: load("../sql/users/delete.sql"),
        find: load("../sql/users/find.sql"),
        update: load("../sql/users/update.sql")
    },
    create: load("../sql/create.sql"),
    init: load("../sql/init.sql"),
    drop: load("../sql/drop.sql")
};
```

**Comment by vitaly-t** [comment]
Added a guideline: [SQL Files](https://github.com/vitaly-t/pg-promise/wiki/SQL-Files)

**Comment by msaron** [comment]
One problem I had was I was developing on Windows and deploying on linux. The filenames generated have windows back slashes. I had to use npm module normalize-path to generate unix paths.

**Comment by vitaly-t** [comment]
@msaron that would be expected, since you are not re-generating the file on the deployment machine, which would be the alternative :wink:

**Comment by vitaly-t** [comment]
This entire feature has been removed from version 9.0.0.

**Comment by enjunear** [comment]
Hi @vitaly-t, I thought this was a fantastic feature. Are there any plans to implement a similar helper functionality, or do you recommend an alternative method to using a large swathe of query files?

**Comment by vitaly-t** [comment]
@enjunear I wasn't sure anybody ever used it at all. And it shouldn't have been made into the library in the first place, it belongs to a separate module.

Even for a large number of SQL files, the method shown in [pg-promise-demo](https://github.com/vitaly-t/pg-promise-demo) should be sufficient.

And I'm not planning on any replacement for the removed feature.

**Comment by enjunear** [comment]
@vitaly-t should I be using the `enumSql` function to make a 'virtual' tree rather than a static file?

**Comment by vitaly-t** [comment]
Either that or type file names statically, as shown in the demo.

**Comment by enjunear** [comment]
I was getting errors to start with, but I'm sure I've got it working now.

For anyone else searching, it's as easy as this:
```js
// /sql/index.js
"use strict";

const { pgp } = require("../db");

const sql = pgp.utils.enumSql(__dirname, { recursive: true }, (file) => {
  return new pgp.QueryFile(file, { minify: true });
});

module.exports = sql;
```

Once again, thanks for an awesome library.
