### ISSUE TITLE
Typings won't install 

### ISSUE THREAD

**Issue by bali182** [vitaly-t/pg-promise#155]
First, thanks for the package!

I'm trying to install the definitions for it, but this happens (it's installed using npm already):
```
typings install npm:pg-promise --save --global
```
Results in

> typings INFO reference Stripped reference "E:\tsdata-pg\node_modules\pg-promise\typescript\pg-subset" during installation from "pg-promise" (main)
> typings INFO reference Stripped reference "E:\tsdata-pg\node_modules\pg-promise\typescript\pg-minify" during installation from "pg-promise" (main)
> typings INFO reference Stripped reference "E:\tsdata-pg\node_modules\pg-promise\typescript\ext-promise" during installation from "pg-promise" (main)
> typings ERR! message Unable to read typings for "pg". The author of "pg-promise" needs to check the entry paths in "package.json" are up to date
> typings ERR! caused by ENOENT: no such file or directory, open 'E:\tsdata-pg\node_modules\pg-promise\node_modules\pg\lib.d.ts'

Even after I install the `pg` module separately (I think it complains about that one):

```
typings install pg --save 
```

The error persists. Any advice?

**Comment by vitaly-t** [comment]
Why not just follow [the exact instructions](https://github.com/vitaly-t/pg-promise/tree/master/typescript)?

**Comment by bali182** [comment]
My bad then, lesson learned: when there is a readme, always read it :smile:
