### ISSUE TITLE
How to handle errors properly?

### ISSUE THREAD

**Issue by kdex** [vitaly-t/pg-promise#156]
Is there a "cleaner" way to differentiate between errors rather than checking [error.code](https://github.com/kdex/map-game/blob/6fee3651853b6a04aa069616dcb037633a5ac747/src/server/js/db.js#L76) and making [custom mappings](https://github.com/kdex/map-game/blob/6fee3651853b6a04aa069616dcb037633a5ac747/src/server/js/db.js#L9) so the code stays readable? I was wondering if I could just grab these mappings from `pg-promise`, if `node-postgres` exposes something like that.

Also, I was wondering how to get more specific errors (for example, consider a `UNIQUE` index which causes an `INSERT` to fail). The end user in front of a registration form would then like to know which field caused the violation, but to the best of my knowledge, all I could rely on would be `error.message`, which I would have to parse in order to output end-user friendly errors. How is that commonly handled?

**Comment by vitaly-t** [comment]
The library implements many custom errors to help in the error-handling logic, all of which you can see in the [errors namespace](http://vitaly-t.github.io/pg-promise/errors.html).

The error handling can be simpler when used centralized, via the global [error](http://vitaly-t.github.io/pg-promise/global.html#event:error) event.

By the way, have you tried [pg-monitor](https://github.com/vitaly-t/pg-monitor) yet?

**Comment by kdex** [comment]
I've already had a glance at the errors namespace, but I couldn't see a helper that could simplify the task of figuring out which value broke a unique constraint. I found that `error.detail` gives me

  detail: 'Key (account_name)=(kdex) already exists.',

which seems "simple enough" to be parsed for the column's name, but I was really wondering if the column name is directly exposed somewhere in the error I haven't looked yet.

Also, is there a way of detecting a uniqueness violation without using the "magic number" `23505` anywhere in the code?

**Comment by vitaly-t** [comment]
What you are asking about, is an extra parse on top of the basic `node-postgres` driver, for errors reported by PostgreSQL. This library doesn't do it. There were numerous discussions about unifying error reporting within `node-postgres`, but none of them ever yielded much.

**Comment by kdex** [comment]
Huh, so I suppose I'll have to write a custom error parser. What a bummer. :)
Thanks a lot for helping out!

**Comment by vitaly-t** [comment]
If it's any consolation, none of the existing PostgreSQL drivers or libraries do it.

You can have a look at [node-pg-error](https://github.com/moll/node-pg-error).

**Comment by kdex** [comment]
Why don't they? Is the error reporting something that PostgreSQL might completely overhaul at some point then? And thank you for the pointer; looks very promising. :+1:

**Comment by vitaly-t** [comment]
Two reasons:

1. This kind of stuff should be done on the driver level - `node-postgres`, but its author never did it;
2. It would be a major breaking change for all of the code that's out there.

**Comment by kdex** [comment]
That makes sense; but as for breaking changes: that should absolutely not be an issue with close adherence to semver/npm; that's what it's for. I'll have a look at `node-pg-error`, thanks. :)
