### ISSUE TITLE
Problem with SSL Heroku pg connection

### ISSUE THREAD

**Issue by Iazzetta** [vitaly-t/pg-promise#160]
In pg module, we have the `pg.defaults.ssl = true` to connect by localhost to heroku.
How I do this with pgp?

**Comment by Iazzetta** [comment]
Hmmm work for me using this:
`pgp.pg.defaults.ssl = true;`

**Comment by vitaly-t** [comment]
That, plus [during the connection](https://github.com/vitaly-t/pg-promise/wiki/Connection-Syntax).
