### ISSUE TITLE
support for sql "partials"

### ISSUE THREAD

**Issue by tkellen** [vitaly-t/pg-promise#161]
It would be really cool if queryFile was able to read multiple SQL files, here is a naive example:

getId.sql
```sql
SELECT id FROM table WHERE somecolumn = ${value}
```

getRelatedThings.sql
```sql
SELECT column1, column2 FROM otherTable WHERE fkey_id = (${readFile(getId)})
```

Have you considered anything like this or seen any consumers of pg-promise that attempt it?

**Comment by vitaly-t** [comment]
That's not possible, i'm afraid.

Problem 1:

The query formatting engine doesn't have any dependency, while QueryFile uses the formatting engine for partial query formatting. They cannot refer to each other. That's module cross-reference limitation.

Problem 2:

Query formatting engine is highly optimized, and it is fully synchronous. Mixing it up with something like QueryFile would make a mess out of it.

Problem 3:

QueryFile takes many options, parameterizing which from a variable would be a mess.

Problem 4:

Query formatting engine doesn't support the syntax you described for passing in variables. Changing the engine just for that,...I wouldn't do it. Implementing query formatting in QueryFile would be messy, plus again, passing all the options would make it bad.

In all, I don't think I would venture in something like this, sorry.

**Comment by vitaly-t** [comment]
@tkellen it is worth adding, that if you need something like that, it is very easy to inject content of one SQL file into another, using `QueryFile`.

The only issue - it becomes impossible to rely on query promises to reject when your `QueryFile` encounters a problem, and you won't be able to re-load such SQL files automatically.

**Comment by vitaly-t** [comment]
Here's an example of what you can do with the existing `QueryFile` and the formatting engine:

```js
var QueryFile = require('pg-promise').QueryFile;

// file ./sql/inner.sql:
// SELECT count(*) FROM table1
var innerQuery = new QueryFile('./sql/inner.sql', {minify: true});

// file ./sql/full.sql:
// SELECT * FROM table2 WHERE (${counter}) > 0
var fullQuery = new QueryFile('./sql/full.sql', {
    minify: true,
    params: {
        counter: getInnerSql
    }
});

function getInnerSql() {
    if (innerQuery.error) {
        throw innerQuery.error;
    }
    return innerQuery.query;
}

console.log(fullQuery);
//=>
// QueryFile {
//     file: "./sql/full.sql"
//     options: {"debug":true,"minify":true,"compress":false,"params":{}}
//     query: "SELECT * FROM table2 WHERE ('SELECT count(*) FROM table1') > 0"
// }
```

**Comment by vitaly-t** [comment]
Closing, due to inactivity.

**Comment by tkellen** [comment]
thanks @vitaly-t, that's a super helpful example--I may play with that a bit in the future!

**Comment by vitaly-t** [comment]
The demo shown above there is now obsolete. It can be simplified to just the following:

```js
var QueryFile = require('pg-promise').QueryFile;

// file ./sql/inner.sql:
// SELECT count(*) FROM table1
var innerQuery = new QueryFile('./sql/inner.sql', {minify: true});

// file ./sql/full.sql:
// SELECT * FROM table2 WHERE (${counter^}) > 0
var fullQuery = new QueryFile('./sql/full.sql', {
    minify: true,
    params: {
        counter: innerQuery
    }
});

console.log(fullQuery);
//=>
// QueryFile {
//     file: "./sql/full.sql"
//     options: {"debug":true,"minify":true,"compress":false,"params":{}}
//     query: "SELECT * FROM table2 WHERE (SELECT count(*) FROM table1) > 0"
// }
```

**Comment by tkellen** [comment]
Awesome!
