### ISSUE TITLE
promise response

### ISSUE THREAD

**Issue by jamesvanleuven** [vitaly-t/pg-promise#164]
Hey,

I like the idea of your pg-promise node_module, and using it simplistically for testing is fine, but I'm trying to figure out how to actually return the resolve reject using something along the lines of:

```
var q = db.any(sql, params)
.then(function(result){
    var a = {
        status: 200,
        result: result
    };
    return this.resolve(a);
})
.catch(function(err){
    var b = {
        status: 500,
        result: err
    };
    return this.reject(b);
});

console.log( q );
```

and i'm returning 
```
Promise { <pending> }
POSTGRES ERROR >>>  [ReferenceError: resolve is not defined]
```

believe me, I've been scouring the documentation and I'm clearly not getting it...

**Comment by vitaly-t** [comment]
> resolve reject

there is no such thing :)

And what you are trying to do there is very wrong to begin with. It should be:

```
var q = db.any(sql, params)
.then(function(result) {
    var a = {
        status: 200,
        result: result
    };
    console.log(a);
})
.catch(function(err){
    var b = {
        status: 500,
        result: err
    };
    console.log(b);
});
```

**Comment by jamesvanleuven** [comment]
ok, so I noticed it just returns. I don't have to actually deal with the Promise.resolve/reject/define aspects huh? I didn't realize that, I just did a test and it returns it anyway..

I wasn't aware of it. All the examples have the ```console.log(something);``` which is fine, but nobody on earth returns the console log and that's it... lol 

I'm coming from an AngularJS viewpoint so I'm thinking
``` var deferred = $q.defer(); ``` and then the ``` return deferred.resolve(value);``` and ``` return deferred.reject(err);```

but I just doesn't require it... i'm still reading the docs and am realizing this is ES6 not JS so ...

**Comment by jamesvanleuven** [comment]
um, why does your documentation then have a reference to the Javascript Promise reference?
https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Promise

on this page as an external promise? http://vitaly-t.github.io/pg-promise/external-Promise.html

I am reading your docs dude. I've been reading it all day, and as useful as the chaining is, it isn't intuitive...

**Comment by vitaly-t** [comment]
>why does your documentation then have a reference to the Javascript Promise reference

Because it is fully based on promises.

>and as useful as the chaining is, it isn't intuitive...

Do you mean the promises part? One should read about promises in other resources, this library simply uses the promise standard, it is not supposed to re-document promises.
