### ISSUE TITLE
how to use IN operator in SQL

### ISSUE THREAD

**Issue by shesko** [vitaly-t/pg-promise#167]
Hello,
Lets say I have the following query:

```
SELECT venue.name
FROM venue
WHERE venue.type IN (...)
```

where (...) is a list containing different types describing venues. 

I am using a QueryFile approach to call the query from an sql file. The function would look something like this:

`rep.many(sql.get_venues_by_type, list_of_types)`

Assuming in this case that `list_of_type = ['restaurant', 'museum']`, how can I implement the function so that the sql query translates to:

```
SELECT venue.name
FROM venue
WHERE venue.type IN ('restaurant', 'museum')
```

The array size and content being passed will vary depending on the user's request so I cannot do this:
```
SELECT venue.name
FROM venue
WHERE venue.type IN ($1, $2)
```

**Comment by vitaly-t** [comment]
It's all documented.

https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#where-col-in-values

**Comment by shesko** [comment]
oh, must have missed that section. Thank you!
