### ISSUE TITLE
pgp.end is not a function

### ISSUE THREAD

**Issue by jonathan-stone** [vitaly-t/pg-promise#169]
I upgraded from 3.4.4 to 4.7.1 a couple weeks ago. Since then, **calling pgp.end() results in an error message**. It seems pgp.end is not defined. Has it been removed? It's still in the docs and, it appears, still in the code base, but somehow not being applied.

If this has been fixed in a more recent version, I'm fine with updating.

Here is a simple code example:

```
'use strict';
var pgp = require('pg-promise');
var qrm = pgp.queryResult;

var dbConfig = {
  user: "my_actual_db_username",
  password: "my_actual_password",
  host: "localhost",
  port: "5432",
  database: "my_actual_db_name"
};

var db = pgp()(dbConfig);

var sql = 'select * from tbl_user';

db.query(sql, null, qrm.any)
.then(function(data){
  console.log("Query returned: " + data);
  return Promise.resolve(data);
})
.catch(function(err){
  console.log("Query failed: " + err);
  return Promise.reject(err);
})
.then(()=>{
  console.log("Calling end:");
  pgp.end();
})
.catch(function(err){
  console.log("Calling end failed: " + err);
  return Promise.reject(err);
})
.then(()=>{
  console.log("Called end.");
});
```
Here's the output:
Query returned: [object Object],[object Object],[object Object],[object Object],[object Object]
Calling end:
Calling end failed: TypeError: pgp.end is not a function

**Comment by vitaly-t** [comment]
[As stated in the documentation:](http://vitaly-t.github.io/pg-promise/module-pg-promise.html#~end)

>Available as `pgp.end`, **after initializing the library**.

**Comment by jonathan-stone** [comment]
Thanks for your response!

Maybe I don't understand what "initializing the library" means. I thought this line did that:

`var db = pgp()(dbConfig);`

What is your definition of initializing the library? And what is "the library?" These probably sound like silly questions to you, but I can't tell from reading the docs.

**Comment by vitaly-t** [comment]
It is at the very beginning: https://github.com/vitaly-t/pg-promise#initialization

**Comment by jonathan-stone** [comment]
Oh, I think I get it. So I need to change my require call to:
`var pgp = require('pg-promise')();`

Tested it and no longer got the error. Thanks!

**Comment by vitaly-t** [comment]
n.p. ;)
