### ISSUE TITLE
rowCount unavailable after UPDATE / INSERT / DELETE

### ISSUE THREAD

**Issue by vitaly-t** [vitaly-t/pg-promise#17]
Created on behalf of @mdvorak, after [his merge request](https://github.com/vitaly-t/pg-promise/pull/16).

Method `query` provides no access to `rowCount` after successful execution of `INSERT` or `UPDATE`.

**Comment by mdvorak** [comment]
MyBatis solves this by having methods like `selectOne`, `selectList`, `selectMap` for data retrieval
and `delete`, `update`, `insert` for modifications. It is explicit, but i thing actually method `update` with `rowCount` as result would suffice.

My original solution provides you access to full result object, which allows future users to get any possible future properties available there :) Also might allow easier transition from pure pg/other libraries to this one. Therefore, I would still include it.

**Comment by vitaly-t** [comment]
I'd like to see that no other fix is possible in the meantime, before opting for a breaking change.

**Comment by mdvorak** [comment]
My PR wasn't breaking, it just added new queryResult. But having `.update(...).then(function(rowCount) {});` would serve as well. I can't think of case where you would need both data and rowCount.
If you don't want to have generic passthru method, this is my suggestion.

**Comment by vitaly-t** [comment]
Method `query` already has all the information, it just needs to return the extra result. This can be achieved either through an extra option added to the method or another method name. I would't call it anything specific to update/insert/delete, because it should remain generic.

**Comment by vitaly-t** [comment]
You know, I think I have a better idea...

How about, we add method called something like `raw` and have it resolve with the entire `result` object as returned from `pg`?

**Comment by vitaly-t** [comment]
>I can't think of case where you would need both data and rowCount.
Well, if you execute something like this:
```
UPDATE test SET description = 'test' WHERE id = 1 RETURNING id
```

**Comment by mdvorak** [comment]
Well, that still produces rows array, therefore you have its length property.
But I was also originally thinking about `raw` as `queryResult`, so `rawQuery` or `queryRaw` sounds fine to me. queryRaw fits me better, since you are executing query and consuming raw result. While rawQuery would make me think i'm bypassing pg-promise query formatting (pgFormatting=true).

**Comment by vitaly-t** [comment]
Very good. I'm adding support for `queryRaw` right now ;) It makes perfect sense. Cheers!

**Comment by vitaly-t** [comment]
I have implemented, tested, and checked in the changes. You can get them from the current index.js in the master branch.

There will be some documentation, and perhaps extra tests added before I release it as 1.0.3 (it's not a breaking change).

**Comment by mdvorak** [comment]
Thats great news, thanks!

**Comment by vitaly-t** [comment]
Version 1.0.3 has been released. There were some changes in the source after all, to fix an issue found after adding a few good tests, which is always nice.

I will be adding an example to [Learn by Example](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example) tutorial shortly, but in the meantime the issue is closed.

Thank you for your help! :+1:

**Comment by vitaly-t** [comment]
[Affected Rows](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#affected-rows) example has been added to the [Learn by Example](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example) tutorial ;)

**Comment by vitaly-t** [comment]
@mdvorak,  Unrelated to this, but if you liked this library, I really appreciate if you can give me a feedback on this small addition: [pg-monitor](https://github.com/vitaly-t/pg-monitor)

**Comment by vitaly-t** [comment]
@mdvorak reflecting on some of the passed changes, added method `result` in [release 1.7.4](https://github.com/vitaly-t/pg-promise/releases/tag/v.1.7.4) as another alias to `queryRaw`, because this is what it should have been called.

**Comment by miraage** [comment]
https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#affected-rows
broken. could you please update wiki?

**Comment by vitaly-t** [comment]
Where is this link declared?

**Comment by vitaly-t** [comment]
@miraage The link has been updated: [Raw Result](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#raw-result)

Cheers!
