### ISSUE TITLE
Compiling with typescript w/ pg-promise@5.0.3

### ISSUE THREAD

**Issue by sbusch99** [vitaly-t/pg-promise#171]
I'm using the latest typings for pg-promise and I'm getting: 

> typings/globals/pg-promise/index.d.ts(9,30): error TS2307: Cannot find module 'spex'

I answered my own question. Add below. You can close the issue
>     "spex": "github:vitaly-t/spex",

**Comment by vitaly-t** [comment]
yeah, spex not ships with its own typescript, and they way I merged them - doesn't work automatically, for some reasons, I'm still trying to figure out how to improve this.

In the meantime, you can reference `spex` directly, as explained [here](https://github.com/vitaly-t/spex/tree/master/typescript): 

run script:
```
typings install --save --global github:vitaly-t/spex
```

**Comment by sbusch99** [comment]
Thanks

**Comment by vitaly-t** [comment]
P.S. I asked a question about this: [A reusable library with typings from GitHub](http://stackoverflow.com/questions/38037911/a-reusable-library-with-typings-from-github)
