### ISSUE TITLE
Array of pairs

### ISSUE THREAD

**Issue by bellshill** [vitaly-t/pg-promise#172]
Hi, 
I have a sql file with the following code:
```sql
SELECT *
FROM user
WHERE (user.forename, user.surname) IN ($1:csv)
```

to call this script I use the following function:

`rep.many(sql.get_requested_users, pgp.as.csv( [ ['John', 'Winningham'], ['Kate', 'Soromoth'] ] ))
`
What do I need to change for the sql script to translate as such:

```sql
SELECT *
FROM user
WHERE (user.forename, user.surname) IN  (('John', 'Winningham'), ('Kate', 'Soromoth'))
```

**Comment by vitaly-t** [comment]
there are several ways, here's just one of them:

```js
var data = [['John', 'Winningham'], ['Kate', 'Soromoth']];
var values = data.map(d=>'(' + pgp.as.csv(d) + ')').join();
rep.many(sql.get_requested_users, values);
```
in this case you would change your sql query to this:
```sql
SELECT *
FROM user
WHERE (user.forename, user.surname) IN ($1^)
```
