### ISSUE TITLE
optional parameters

### ISSUE THREAD

**Issue by tkellen** [vitaly-t/pg-promise#173]
When using named parameters, what do you think about the possibility of allowing undefined parameters? If they were missing, they'd default to null.

```sql
UPDATE table
SET (fieldOne, fieldTwo) = (
  COALESCE(${fieldOne}, fieldOne),
  COALESCE(${fieldTwo}, fieldTwo)
);
```

Alternatively, can you suggest another approach?

**Comment by vitaly-t** [comment]
This would go against the logic of partial formatting where variables can be set in more than one step.

See parameter `partial` in the [format](http://vitaly-t.github.io/pg-promise/formatting.html#.format) method.

`QueryFile` relies on it usage, for example.

**Comment by vitaly-t** [comment]
In theory, we could have another parameter within the `format` function, say `default`, to provide default value for variables that do not exist.

But i'm not sure how much value it would add, since you do not have access to formatting options from within query methods.

**Comment by vitaly-t** [comment]
@tkellen any feedback on this?

**Comment by vitaly-t** [comment]
Added option `default` in [v.5.0.4](https://github.com/vitaly-t/pg-promise/releases/tag/v.5.0.4)

**Comment by tkellen** [comment]
hey @vitaly-t, you are too fast! thank you so much! can you share an example usage?

**Comment by vitaly-t** [comment]
Have you seen the API? It is quite self-explanatory: [as.format](http://vitaly-t.github.io/pg-promise/formatting.html#.format).

**Comment by tkellen** [comment]
Indeed it is, thanks again @vitaly-t!

**Comment by vitaly-t** [comment]
@tkellen many things have changed with the release of [v.5.2.0](https://github.com/vitaly-t/pg-promise/releases/tag/v.5.2.0), in relation to what was discussed here, making it way simpler to use external SQL as templates of any nesting level.

**Comment by tkellen** [comment]
That's awesome @vitaly-t! Will you be spinning up any examples for this? I'm pretty sure I understand what you're describing based on the release notes but I haven't had a chance to try it yet.

**Comment by vitaly-t** [comment]
@tkellen you would be right to think of it in very simple terms, `QueryFile` is now a type that can be a formatting parameter, to inject sub-queries :) And you can use this type with method `as.format` directly.

If you try, I'm sure it will just work for right off the way you think it should ;)

**Comment by vitaly-t** [comment]
@raine Can you clarify what kind of queries you are trying to build. Are those by any chance INSERT or UPDATE queries?

**Comment by raine** [comment]
Oh yeah, the properties are actually missing, not defined set as undefined. That was just the example which I thought would clarify but I guess it had the opposite effect. 😁

**Comment by vitaly-t** [comment]
@raine In that case, as per what I wrote above...

```js
const DEFAULT = {
    rawType: true,
    toPostgres: () => 'default'
};

const s = pgp.as.format('SELECT ${first}', {}, {default: DEFAULT});
```
