### ISSUE TITLE
TypeScript issue with versions >=5.0.1

### ISSUE THREAD

**Issue by mamobyz** [vitaly-t/pg-promise#178]
After installing the newest version 5.1.0, my code does not compile due to missing typings/index.ts file, which is required by https://github.com/vitaly-t/pg-promise/blob/master/typescript/pg-promise.d.ts#L8. You possibly forgot to add an 'postinstall' script like `typings install`in you package.json.

**Comment by vitaly-t** [comment]
@mamobyz looks that way :+1:

**Comment by vitaly-t** [comment]
Fixed in [5.1.2](https://github.com/vitaly-t/pg-promise/releases/tag/v.5.1.2)
