### ISSUE TITLE
Incorrect condition for checking isSimple in ColumnSet

### ISSUE THREAD

**Issue by tomaszlukasik** [vitaly-t/pg-promise#181]
I think calculating isSimple has a bug.
https://github.com/vitaly-t/pg-promise/blob/master/lib/helpers/columnSet.js#L220

If you assign `ColumnConfig.def` a falsy value, condition `(c.prop || c.def || c.init)` will be resolved as `false`.

**Comment by vitaly-t** [comment]
Thank you for reporting this! Fixed in [5.1.3](https://github.com/vitaly-t/pg-promise/releases/tag/v.5.1.3).
