### ISSUE TITLE
Formatting Date Output

### ISSUE THREAD

**Issue by jpdesigndev** [vitaly-t/pg-promise#182]
It seems that [node-postgres](https://github.com/brianc/node-postgres) is converting timestamptz strings from postgres into JavaScript date objects.

Upon stringification of this date object, JavaScript returns an IETF-compliant RFC 2822 timestamps such as `"Fri Jul 15 2016 20:49:50 GMT-0400 (EDT)"`. I'd prefer that my API server return ISO 8601 string such as `"2016-07-16T00:49:50.000Z"`. 

It seems that this can be accomplished using the [node-pg-types](https://github.com/brianc/node-pg-types) as @brianc [suggests](https://github.com/brianc/node-postgres/issues/285#issuecomment-14181801).

I'm not sure how to get direct access to pg-promise's `pg` dependency. Is this exposed? Is there a better way to go about doing this?

**Comment by vitaly-t** [comment]
see wiki, faq ;) it is `pgp.pg` ;)

**Comment by jpdesigndev** [comment]
Oh, wow. I suppose I was just too deep to see what was right in front of me. Thanks!
