### ISSUE TITLE
How to get Raw Date Strings from DB

### ISSUE THREAD

**Issue by nsisodiya** [vitaly-t/pg-promise#183]
I am using `pg-promise`. And I am not getting proper data. I was expecting proper date strings, but I got Date Object. I have logged issue here - Please guide me

https://github.com/brianc/node-postgres/issues/1084

**Comment by vitaly-t** [comment]
This library does not do any data interpretation, it is done by [node-postgres](https://github.com/brianc/node-postgres), which in turn uses [pg-types](https://github.com/brianc/node-pg-types) to convert the data received, which you can access via `pgp.pg.types`.
