### ISSUE TITLE
cannot find .sql file when running app with mocha test

### ISSUE THREAD

**Issue by shesko** [vitaly-t/pg-promise#184]
Hi,
I am testing my API with mocha and chai and while running it I get an error due to an implementation in pg-promise.

This is my test: 
```
var chai = require('chai');
var chaiHttp = require('chai-http');
var server = require("../../../server");
var should = chai.should();

chai.use(chaiHttp);
describe('api/venues', function() {
	it('should return all venues on GET /api/venues', function(done) {
		chai.request("http://localhost:8086")
			.get('/api/venues')
			.end(function(err, res) {				
				res.should.have.status(200);
				done();
			});
	});
});
```

When the server receive this http request it performs a db query with pg-promise. The command is the following: 

`get_venue_list: () => rep.many(sql.get_venue_list)`

Where sql.get_venue_list extracts the get_venue.list.sql file and performs the query implemented within the file.

Everything works fine when I run the api, but the moment I try to run the request through the test case shown above I get the following error:

`ENOENT: no such file or directory, open '/usr/local/lib/node_modules/mocha/bin/server/units/sql/venue/get-venue-list.sql`

The issue seems to be caused by line `151` and `154` of the file `pg-promise/lib/utils/index.js`, where mocha sets the value for process.argv[1]:

```
var mainFile = process.argv[1];

// istanbul ignore next
exp.startDir = mainFile ? $path.dirname(mainFile) : process.cwd();
```
I am having the same problem when I try to deploy my application with Phusion Passenger. Except that in this case the process.argv[1] value is different of course.
Is there something I should change on my end or is this something you can fix?

**Comment by vitaly-t** [comment]
[As per documentation](http://vitaly-t.github.io/pg-promise/QueryFile.html):

>Path to the SQL file with the query, either absolute or relative to the application's entry point file.

If you use a relative path, and then change the execution root file, that's the kind of trouble you would run into, naturally.

Change the path to the absolute, by appending to the global `__dirname` variable, and that will solve it.

**Comment by shesko** [comment]
thnx!
