### ISSUE TITLE
How to chain one query with a set of queries and keep the intermediate results?  

### ISSUE THREAD

**Issue by vince166** [vitaly-t/pg-promise#186]
Based on the idea from here: http://stackoverflow.com/questions/28250680/how-do-i-access-previous-promise-results-in-a-then-chain , I was trying to chain query A with dependent queries [B1, B2, B3 ...]. and also want save and reuse the results from query A. 

I was not able to get the following code to work. (I tried shared task, nested tasks, nested transactions, all separate queries, or promise.all()). Always get the `Loose request outside an expired connection` error.

Any help will be greatly appreciated. 

```
 function getUserSettings (userId) {
  return db.task(function (t) {
            var userSettingsPromise =
                t.many(" SELECT s.name AS name, s.description AS description, " +
                    "        s.default_value AS default_value, us.user_value AS user_value " +
                    " FROM " +
                    " (SELECT setting_id, name, description, default_value, $1::uuid AS user_id FROM setting) AS s " +
                    " LEFT JOIN user_setting us ON s.setting_id = us.setting_id AND s.user_id = us.user_id " +
                    " WHERE s.user_id = $1", userId);
            var defaultValuesPromise = userSettingsPromise
                .then(function (userSettingRecs) {
                    return t.task(function (t2) {
                        logger.debug("Got userSettingRecs: " + JSON.stringify(userSettingRecs));
                        var queries = [];
                        for (var i = 0; i < userSettingRecs.length; i++) {
                            var userSettingRec = userSettingRecs[i];
                            var defaultValue = userSettingRec.default_value;
                            if (userSettingRec.user_value === null && isDefaultValuePlaceHolder(defaultValue)) {
                                queries.append(getUserSpecificDefaultValue(t2, defaultValue, userId));
                            }
                        }
                       // Never seen this debug ... 
                        logger.debug("Making batch queries for defaultValuePlaceHolders: count=%d", queries.length);
                        if (queries.length === 0) {
                            return [];
                        }
                        else {
                            return t2.batch(queries);
                        }
                    });
                }).then(function (results) {
                    // Never able to reach here ... 
                    logger.debug("Got defaultValuePlaceHolder map: " + JSON.stringify(results));
                    var defaultValues = {};
                    for (var i = 0; i < results.length; i++) {
                        defaultValues[results[i].name] = results[i].value;
                    }
                    return defaultValues;
                });

            return t.batch([userSettingsPromise, defaultValuesPromise]);
        })
        .then(function (results) {
            //  Never able to reach here ...
            logger.debug("Got both userSettingRecs and defaultValue map: " + JSON.stringify(results));
           ....
        }); 

function getUserSpecificDefaultValue(t, defaultValuePlaceHolder, userId) {
    logger.debug("Getting value for the placeholder: %s", defaultValuePlaceHolder)
    if (defaultValuePlaceHolder === USER_EMAIL_AS_ARRAY) {
        return t.one(" SELECT email FROM \"user\" " +
                " WHERE user_id = $1 ", userId)
            .then(function (data) {
                // Depending on how the code is tweaked, sometimes I was able to reach here ... 
                logger.debug("Got value for the placeholder %s: %s", defaultValuePlaceHolder, data.email);
                return {
                    "name": defaultValuePlaceHolder,
                    "value": [data.email]
                };
            })
            .catch(function (error) {
                logger.error(error);
            });
    }
    else {
        throw Error("DefaultValuePlaceHolder '" + defaultValuePlaceHolder + "' is unknown. Cannot resolve it to a value.");
    }
}
```

I also don't understand the `doesn't settle queries;` comment in the following example. I thought it was just inefficient, but why would Promise.all() not settle promise? Does settling promises and settling queries have different meanings? 

```
function badCode(someData) {
    // someData = your array of objects for inserts;
    var queries = [];
    someData.forEach(function (data) {
        // querying against root database protocol:
        queries.push(db.none('insert into...', data));
    });
    return Promise.all(queries); // doesn't settle queries;
}
```

**Comment by vitaly-t** [comment]
>but why would Promise.all() not settle promise?

Because it is not supposed to, as per the Promise spec. Once the first promise in the chain rejects, the whole `promise.all` rejects at once.

>Does settling promises and settling queries have different meanings?

No, it is the same.

---

This shows a good example of how to do what you want: http://stackoverflow.com/questions/37664258/get-a-parents-children-tree-with-pg-promise

**Comment by vince166** [comment]
Thank you for the lightning fast reply! The example you gave seems to be the `Explicit pass-through` approach in the stackoverflow link that I mentioned. I will give it a try. 

Best regards.

**Comment by vitaly-t** [comment]
You are welcome. And just so, you definitely do not need more than one `.task` there.

**Comment by vitaly-t** [comment]
anyway, avoid manual loops through multiple records. Instead, use methods [map] and [each] for that, they produce much shorter and more efficient code ;)

[many]:http://vitaly-t.github.io/pg-promise/Database.html#.many
[each]:http://vitaly-t.github.io/pg-promise/Database.html#.each

**Comment by vince166** [comment]
Thanks a lot for the tips. 

What is the effective way to debug? The exceptions seem to be caught internally by pg-promise. The final error caught by the expressjs error handler doesn't contain much useful information. Is adding print statements or adding more catch() the only way to go? 

I am now stuck at this error  `TypeError: undefined is not a function`. Which seems to originate from the line `queries.append (t.one(" SELECT email FROM \"user\" WHERE user_id = $1 ", userId))`. 

```
        return db.many(" SELECT s.name AS name, s.description AS description, " +
                "        s.default_value AS default_value, us.user_value AS user_value " +
                " FROM " +
                " (SELECT setting_id, name, description, default_value, $1::uuid AS user_id FROM setting) AS s " +
                " LEFT JOIN user_setting us ON s.setting_id = us.setting_id AND s.user_id = us.user_id " +
                " WHERE s.user_id = $1", userId)
            .then(function (userSettingRecs) {
                return db.task(function (t) {
                    logger.debug("Got userSettingRecs: " + JSON.stringify(userSettingRecs));
                    var queries = [];
                    var seenDefaultValuePlaceHolders = {};
                    logger.debug("userSettingRecs: count=%d", userSettingRecs.length);
                    for (var i = 0; i < userSettingRecs.length; i++) {
                        logger.debug("looping");
                        var userSettingRec = userSettingRecs[i];
                        var defaultValue = userSettingRec.default_value;
                        logger.debug("default_value type is: " + typeof(defaultValue));
                        if (userSettingRec.user_value === null &&
                            isDefaultValuePlaceHolder(defaultValue) &&
                            !_.has(seenDefaultValuePlaceHolders, defaultValue) ) {
                            logger.debug("appending ");
                            queries.append(
                               t.one(" SELECT email FROM \"user\" WHERE user_id = $1 ", userId)
                            );

                            // Never reach here...

                            logger.debug("after appending ");
                            // getUserSpecificDefaultValue(t, defaultValue, userId));
                            _.set(seenDefaultValuePlaceHolders, defaultValue, true);
                        }
                    }
                    //logger.debug("Making batch queries for defaultValuePlaceHolders: count=%d", queries.length);
                    logger.debug("Making batch queries for defaultValuePlaceHolders: ");
                    return t.batch(queries);
                })
                .then(function (results) {
                    logger.debug("Got defaultValuePlaceHolder map: " + JSON.stringify(results));
                    var defaultValues = {};
                    for (var i = 0; i < results.length; i++) {
                        defaultValues[results[i].name] = results[i].value;
                    }
                    return [userSettingRecs, defaultValues];
                })
                .catch(function (error) {
                    logger.debug(error);
                });
            })
            .then(function (results) {
                logger.debug("Got both userSettingRecs and defaultValue map: " + JSON.stringify(results));
                var userSettingRecs = results[0];
                var userSpecificDefaultValues = results[1];
```


2016-07-20T01:23:39.180 - debug:  TypeError: undefined is not a function
    at Task.<anonymous> (index.js:118:37)
    at callback (\node_modules\pg-promise\lib\task.js:191:25)
    at Function.Task.exec (\node_modules\pg-promise\lib\task.js:291:12)
    at \node_modules\pg-promise\lib\database.js:1177:45
    at tryCallOne (\node_modules\promise\lib\core.js:37:12)
    at \node_modules\promise\lib\core.js:123:15
    at flush (\node_modules\promise\node_modules\asap\raw.js:50:29)
    at process._tickCallback (node.js:355:11)

**Comment by vitaly-t** [comment]
According to the error log your show here, you are trying to call a function on something that is undefined. Could be `isDefaultValuePlaceHolder`, or `_.has`, or `seenDefaultValuePlaceHolders`, I don't know, because you do not include code lines with your example.

**Comment by vitaly-t** [comment]
@vince166 

>I am now stuck at this error TypeError: undefined is not a function. Which seems to originate from the line queries.append (t.one(" SELECT email FROM \"user\" WHERE user_id = $1 ", userId)).

LOL. Arrays do not have method `append`, only `push`.

**Comment by vince166** [comment]
Thank you so much! The` append ` is exactly the cause. Is there any suggestion to catch this kind of error early? In Expressjs, I usually do not catch errors in the intermediate steps and instead depend on the final error handler. With pg-promise this seems to result in the hard-to-find errors. For example in this case when I added the catch() to the wrong place I got the` Loose request outside an expired connection` error instead. Any suggestion on debugging and error handling when using pg-promise?

**Comment by vince166** [comment]
Sorry... I should have read the documentation more thoroughly: 
http://vitaly-t.github.io/pg-promise/global.html

``var options = {

    // pg-promise initialization options...

    error: function (err, e) {

        // e.dc = Database Context

        if (e.cn) {
            // this is a connection-related error
            // cn = safe connection details passed into the library:
            //      if password is present, it is masked by #
        }

        if (e.query) {
            // query string is available
            if (e.params) {
                // query parameters are available
            }
        }

        if (e.ctx) {
            // occurred inside a task or transaction
        }
      }

};

**Comment by vitaly-t** [comment]
yes, global event [error](http://vitaly-t.github.io/pg-promise/global.html#event:error) is what can help you here ;)

**Comment by vitaly-t** [comment]
I take it the original issue is settled then :)
