### ISSUE TITLE
Can't patch default query behavior

### ISSUE THREAD

**Issue by dzaman** [vitaly-t/pg-promise#188]
I want to change the default behavior of queries so that queries can be made using query builder objects without calling toString(), but that seems impossible unless I maintain a forked, patched repo.

I've looked to both the query event and the extend event, but these don't cover my use case. Queries are rejected as being of an invalid format prior to the query event being sent and the extend event doesn't allow overriding of existing methods -- the query method is read-only.

What is the canonical way to patch default query behavior?

**Comment by vitaly-t** [comment]
If I understand right, you want to use a custom object that represents the query.

The only way you can do this is by introducing your own methods via event [extend](http://vitaly-t.github.io/pg-promise/global.html#event:extend).

**Comment by dzaman** [comment]
The downside of solving this problem by introducing custom methods via the extend event is that I lose the ability to use existing convenience methods like one, many, etc. without re-implementing them on top of my custom query event. Those methods were 1/2 of the reason I adopted this library.

It might be useful to have a query-preparation event called before "Invalid query format" error is thrown or to allow the existing methods (like query) to be redefined. (Why are they read-only?)

**Comment by vitaly-t** [comment]
Existing methods cannot be changed, as they are used by the library itself, in such cases as a transaction, for one thing.

Another reason - having the standard base protocol simplifies integration with third-party libraries.

>I lose the ability to use existing convenience methods like one, many, etc. without re-implementing them on top of my custom query event.

Re-implementation would be formal, as we are talking only about forwarding into the existing methods, nothing else.

For example, adding namespace `$`:

```js
var pgOptions = {
    extend: obj=>(
        obj.$ = {
            one: (query, values, cb, thisArg)=>obj.one(query.toString(), values, cb, thisArg),
            many: (query, values)=>obj.many(query.toString(), values)
        }
    )
};
```

**Comment by dzaman** [comment]
That's fair, I can see cases when people might accidentally get themselves into trouble by overriding these behaviors in a way that isn't backwards compatible.

I think it's valuable to let users easily customize modules, but the solutions available (namespacing, forking) are reasonable alternatives.

Thanks for your time!

**Comment by vitaly-t** [comment]
Throwing overrides into separate namespaces as shown earlier would prevent such a confusion when the method outcome changes from the standard one. It is a safer approach ;)
