### ISSUE TITLE
Alias obj.func as obj.exec

### ISSUE THREAD

**Issue by paulovieira** [vitaly-t/pg-promise#19]
The `func` method would have a more semantic meaning if the method's name was a verb. The most obvious candidate I can remember is `exec`. So instead of code like this:
```javascript
db.func('findAudit', [123])
    .then(function(data){
        console.log(data);
    });
```
we could have
```javascript
db.exec('findAudit', [123])
    .then(function(data){
        console.log(data);
    });
```

This would actually be more familiar to people coming from sql server, as to call a stored procedure one should use 
```sql
EXEC my_sp 'arg1', 'arg2'
```
If there's interest in this change, I can submit a PR for it.

**Comment by vitaly-t** [comment]
What carries a semantic meaning here is that calling `func` implies that:
1. we are injecting all passed parameters as CSV into the function;
2. we execute `select * from findAudit(params)`.

Calling `exec` implies none of that, so cannot be considered a semantic substitute.

And what `exec` does is already implemented by method `query`. And if you like calling exec - just add it to your application: event [extend](https://github.com/vitaly-t/pg-promise#extend) allows you to do that easily.

**Comment by vitaly-t** [comment]
Closing the issue, as there was no follow-up.

**Comment by vitaly-t** [comment]
@paulovieira,  Unrelated to this, but if you liked this library, I really appreciate if you can give me a feedback on this small addition: [pg-monitor](https://github.com/vitaly-t/pg-monitor)

**Comment by paulovieira** [comment]
> Calling exec implies none of that, so cannot be considered a semantic alias.

My idea was more in the fact that "exec" is a verb, which is the natural choice for methods. By "db.exec" it is implict (for me) that we are executing a pg function. But this is a matter of opinion in the naming, of course.

Here's an analogy: if the library had a sugar method for `select * from users`, a natural choice for me would be `db.readAll("users")`, not `db.table("users")` (or even `db.all("users")`)

> just add it to your application; event extend allows you to do that easily:

Thanks for the tip! Will do it.

I will try your other library. Looks interesting!

**Comment by vitaly-t** [comment]
@paulovieira , I have added another good example of how to make the best out of event `extend`, by using entity repositories. See [Extend Event](https://github.com/vitaly-t/pg-promise#extend)

**Comment by paulovieira** [comment]
@vitaly-t I just tried pg-monitor. It's a very cool addition to pg-promise!

**Comment by vitaly-t** [comment]
@paulovieira , thank you! Unfortunately it hasn't received the attention it deserves. It is the component that gives you the perfect picture of how your app is interacting with the database, and what is going on exactly in terms of the queries.

**Comment by paulovieira** [comment]
Consider adding it to pg-promise directly. It would definitely add value. Maybe something like:

```javascript
var pgp = pgpLib({
    monitor: true  // call monitor.attach with the default options (monitor all events)
});
```

```javascript
var pgp = pgpLib({
    monitor: ["query", "error"]  // monitor only some events (with the default message)
});
```

```javascript
var pgp = pgpLib({
    monitor: {  // monitor some events using a custom message
        query: function (e) {
            /* do some of your own processing, if needed */
            monitor.query(e); // monitor the event;
        },
        error: function (err, e) {
            /* do some of your own processing, if needed */
            monitor.error(err, e); // monitor the event;
        }
}
});
```

**Comment by vitaly-t** [comment]
@paulovieira, this is a very good idea! I might do it later indeed. For the time being though, [pg-promise](https://github.com/vitaly-t/pg-promise) is far more mature a product than [pg-monitor](https://github.com/vitaly-t/pg-monitor), even though the latter has been vigorously tested.
