### ISSUE TITLE
helpers.ColumnSet ignores the schema name

### ISSUE THREAD

**Issue by erichrutz** [vitaly-t/pg-promise#190]
I created a new ColumnSet with this syntax:

    var columnSet = new pgp.helpers.ColumnSet(columns, new pgp.helpers.TableName(table, schema));

The constructur of ColumnSet ignores however the provided schema name. In any chosen syntax for the table parameter, always only the table name is parsed and not the schema.

As a result it is not possible to create bulk inserts into a table not in the public schema.

**Comment by vitaly-t** [comment]
Look at the [ColumnSet API](http://vitaly-t.github.io/pg-promise/helpers.ColumnSet.html) and the examples, you are using it wrong.

The correct call is: 
```js
var cs = new pgp.helpers.ColumnSet(columns, {table: new pgp.helpers.TableName(table, schema)});
```
i.e. table is an option.
