### ISSUE TITLE
Possibility to set 'partial' as default globally

### ISSUE THREAD

**Issue by Richie765** [vitaly-t/pg-promise#191]
Could an initialization option 'partial' be added so that it would format missing fields as NULL by default? Something like:

```javascript
var pgp = require('pg-promise')({
  // Initialization Options
  partial: true
});
```

Perhaps it is already possible somehow but I couldn't find it. Using `pgp.as.format(..., { partial: true })` all the time gets a bit boring.

Thanks!

**Comment by vitaly-t** [comment]
Why would you want to use partial query formatting by default?

You will end up with queries not fully formatted, so they cannot be executed.

**Comment by Richie765** [comment]
Thanks for the fast response. Perhaps I misunderstood the function of it, but what I'm looking for is this. I have an array of items I'd like to insert, but not all fields are set. For instance:

```javascript
var countries = [
 { name: 'Canada', currency: 'CAD' },
 { name: 'Australia' },  // Currency not yet set
];
```

Then I iterate each item and insert the record in the db:

```javascript
// loop countries
db.none('INSERT INTO Country(name, currency) VALUES(${name}, ${currency})', country);
```
That would succeed for the first row, but fail for the second: `Property 'currency' doesn't exist.` So I have to put something in like this:

```javascript
if(! ('currency' in country)) country.currency = undefined;
```

I've quite a bit of data like that, and it would be nice it it would just insert NULL values where the property doesn't exist.

I suppose it could be done like this, but a default partial = true somewhere would make it easier.
```javascript
db.none(pgp.as.format('INSERT INTO Country(name, currency) VALUES(${name}, ${currency})', country, { partial: true }));
```

**Comment by vitaly-t** [comment]
The right approach in this case is via [helpers.insert](http://vitaly-t.github.io/pg-promise/helpers.html#.insert).

**Comment by vitaly-t** [comment]
See also: [Multi-row insert with pg-promise](http://stackoverflow.com/questions/37300997/multi-row-insert-with-pg-promise).

**Comment by Richie765** [comment]
That looks good, I'm going to try it after the weekend! Thank you!

**Comment by vitaly-t** [comment]
Closing for now. You can re-open it, if there are still issues with it ;)

**Comment by noinkling** [comment]
How do you let the database determine a default for the column?

When feeding columns to `helpers.update` at least I can specify `skip: ({exists}) => !exists` to omit a column that doesn't exist on the object (even if it feels clunky), but `helpers.insert` ignores that property. `def: null` and `def: undefined` both set `NULL` regardless of any default set on the column in the db itself, and `def: 'DEFAULT'` just sets that string.

**Comment by vitaly-t** [comment]
@noinkling this depends on the type of the column data. If it is not a string, and can be injected as a [Raw Text], then you can just do:
```js
{def: 'DEFAULT', mod: ':raw'}
```
If it is a string, then you will need to create a more generic solution:

```js
var setDefault = col => {
    return col.exists ? col.value : {_rawDBType: true, formatDBType: () => 'DEFAULT'};
}

// which then you can use with the ColumnSet:

{init: setDefault}
```

[Raw Text]:https://github.com/vitaly-t/pg-promise#raw-text

**Comment by vitaly-t** [comment]
F.Y.I. Important breaking change in [v6.5.0](https://github.com/vitaly-t/pg-promise/releases/tag/v.6.5.0).
