### ISSUE TITLE
Surround Unit Tests in Transaction

### ISSUE THREAD

**Issue by RyanMcDonald** [vitaly-t/pg-promise#192]
I use mocha for unit testing, and currently I have an `afterEach()` set up to execute commands to wipe the database after each test. I'm wondering if there's a way to use pg-promise to wrap each unit test in a transaction, and then just roll back when it's finished.

The code that I'm testing already utilizes transactions via the `.tx()` method, so I can't just wrap each test in `BEGIN` and `ROLLBACK` commands, otherwise I get `WARNING:  there is already a transaction in progress` and `WARNING:  there is no transaction in progress`.

**Comment by vitaly-t** [comment]
If you wrap your tests into transactions, then all actual transactions will not be working as expected, as PostgreSQL doesn't support nested transactions.

The library itself supports nested transactions by having the actual transaction on the top level and partial nested transactions as save points.

In all, you cannot use transactions for tests without affecting the result of the transactions in your code that won't work as a result.

So, I think this idea is a no go.

**Comment by RyanMcDonald** [comment]
@vitaly-t Thanks for the info. It was worth a shot. 😄
