### ISSUE TITLE
Simple, most example of UPDATE (?)

### ISSUE THREAD

**Issue by netaisllc** [vitaly-t/pg-promise#194]
I must be missing something, but all the basic docs use **SELECT** and **INSERT** to demonstrate proper use of the library.  Is there an equivalent topic for **UPDATE**?  That would help me resolve my issue with "syntax error at or near..."

**Comment by vitaly-t** [comment]
Can post the code that gives you trouble?

**Comment by netaisllc** [comment]
No worries.  I was confused in trying to compose the query string itself.  Found the 'helpers' which worked for me.  Thanks for your efforts.
