### ISSUE TITLE
Cant  DELETE FROM `table` WHERE id IN (264, 265)

### ISSUE THREAD

**Issue by sveip** [vitaly-t/pg-promise#195]
I'm trying to delete multiple rows from a table with a query that should be ` DELETE FROM table WHERE id IN (264, 265)`

I've tried ``client.query(`DELETE FROM Users WHERE id IN ($1)`, [ids])`` where `ids` is a comma separated string of ids.

I have also tried named parameters, but no luck.

It's probably just me, but I can't find any examples that support passing an arbitrary number of values to a query?

**Comment by vitaly-t** [comment]
```js
.query(DELETE FROM Users WHERE id IN ($1:csv), ids)
```
ids in this case should be an array of integers.

**Comment by sveip** [comment]
Thanks, but I get `{ error: syntax error at or near ":"`?

**Comment by vitaly-t** [comment]
Show me the full code, please.

**Comment by sveip** [comment]
Hi, here is the exact query:

``.query(`DELETE FROM Users WHERE id IN ($1:cvs)`, [ids])`` where `ids` is an array of ints.

**Comment by vitaly-t** [comment]
the extension is csv, not cvs

**Comment by sveip** [comment]
Sorry, just a typo here in my post. It's correct in the code. Still same error.

**Comment by vitaly-t** [comment]
what is that 'client' object you are calling against?

**Comment by sveip** [comment]
pg.connect(connStr).then(result => {
    const client = result.client;

I'm on my phone until Monday, sorry for the missing formatting.

**Comment by vitaly-t** [comment]
This is a complete misuse of the library :)

This project offers [a myriad of examples](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example), and none of them do what you are doing there.

Do not call method `connect` to execute queries, this is not what that method is there for.

See [the examples that are everywhere](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example) and follow them...

**Comment by sveip** [comment]
Thanks! I will for sure :)
