### ISSUE TITLE
Release client back to pool

### ISSUE THREAD

**Issue by vastus** [vitaly-t/pg-promise#20]
How to manually release the client back to pool after running a query?

**Comment by vitaly-t** [comment]
@vastus exactly as shown in chapter [Shared Connections](https://github.com/vitaly-t/pg-promise#shared-connections), by calling method `done()` in the end.

But if you just start using the library, to let you know that you hardly will ever need to do that. 

And [Learn by Example](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example) tutorial is a good place to start, once you got it all up and running ;)

**Comment by vastus** [comment]
That's why I asked b/c that example didn't work for me. Still hangs that 30s or what was it?

**Comment by vitaly-t** [comment]
Pardon, but your question was about how to release a client connection to the application pool, and now you are asking about how to shut-down the application pool. These are two different things :)

The second one is explained in chapter [Library De-initialization](https://github.com/vitaly-t/pg-promise#library-de-initialization)

Please clarify the trouble you are having. Are you making that call to shut down the pool and it doesn't work?

**Comment by vitaly-t** [comment]
If I got you right, here's the same example, but one that also terminates PG's application pool in the end:
```javascript
var sco; // shared connection object;
db.connect()
    .then(function(obj){
        sco = obj; // save the connection object;
        // find active users created before today:
        return sco.query("select * from users where active=$1 and created < $2::date",
            [true, new Date()]);
    })
    .then(function(data){
        console.log(data); // display all the user details;
    }, function(reason){
        console.log(reason); // display reason why the call failed;
    })
    .done(function(){
        if(sco){
            sco.done(); // release the connection, if it was successful;
        }
        pgp.end(); // End of application, so shutting down the PG's connection pool;
    });
```

I didn't want to include `pgp.end()` in the demo so people wouldn't think that they have to do that in the end of connection. It's only used when exiting the application.

**Comment by vastus** [comment]
When using promises on cmd line the connection stays open (what I think) and doesn't close before the set time out.

So this https://gist.github.com/vastus/02e27b9b954d08d4d1e3 works nicely and closes the connection when the query is run. But when using pg-promise it hangs til the time out.

**Comment by vitaly-t** [comment]
try the example I did just above, that should work nicely ;)

**Comment by vastus** [comment]
Yeah that's exactly what I was looking for, thanks :) Didn't just catch it in the docs. Thanks for this btw, I started doing my own little lib but luckily found yours.
