### ISSUE TITLE
need connection support currentSchema

### ISSUE THREAD

**Issue by rendongsc** [vitaly-t/pg-promise#201]
var cn = {
    host: 'localhost', 
    port: 5432, 
    database: 'MyDB',
    user: 'user1',
    password: '123',
    currentSchema:'C0001'
};

**Comment by vitaly-t** [comment]
PostgreSQL supports many connection parameters, of which the underlying driver [node-postgres](https://github.com/brianc/node-postgres) supports only a tiny sub-set, and as of today the default schema is not supported.

Other than that, it is a matter for [node-postgres](https://github.com/brianc/node-postgres), not this library, which only uses it.

**Comment by rendongsc** [comment]
@vitaly-t  Query Files. can't meet our needs.
thank you!

**Comment by vitaly-t** [comment]
See the following discussion: https://github.com/vitaly-t/pg-promise/issues/154

The same approach can solve the issue of setting the schema automatically.

**Comment by rendongsc** [comment]
````
var options = {
    promiseLib: promise,
    connect: function(client){
        client.query('SET search_path = cust');
    } 
};
can be used.
thanks very much！

**Comment by vitaly-t** [comment]
Almost... as per the discussion that I gave a link previously...

```js
var options = {
    promiseLib: promise,
    connect: function (client, dc, isFresh) {
        if (isFresh) {
            client.query('SET search_path = cust');
        }
    }
};
```

otherwise you will end up executing it non-stop for each connection request from the pool.

**Comment by vitaly-t** [comment]
[Version 8.3.0](https://github.com/vitaly-t/pg-promise/releases/tag/v.8.3.0) simplifies this, with automatic support for option `schema`.

**Comment by vitaly-t** [comment]
[Version 8.4.0](https://github.com/vitaly-t/pg-promise/releases/tag/v.8.4.0) affects the functionality described here.

Best is to avoid use of event `connect` for this, and just use option `schema` instead.
