### ISSUE TITLE
Error when :csv is used in db.any({text: "...", values: "..."}) 

### ISSUE THREAD

**Issue by m12i** [vitaly-t/pg-promise#203]
The following way of using `:csv` does not work and gives me the following error:
```javascript
db.any({
    text: "SELECT * FROM table WHERE id IN ($1:csv)",
    values:  [data] 
})
```
```
ERROR:  syntax error at or near ":" at character X 
```
where `X` is the location of `:`. I am wondering why it doesn't work, while the one below does:

```javascript
db.any("SELECT * FROM table WHERE id IN ($1:csv)", [data])
```

**Comment by vitaly-t** [comment]
You can't use query-formatting features of the library within prepared statements or parameterized queries. The whole purpose of those is to be formatted by the server.
