### ISSUE TITLE
async/await interface

### ISSUE THREAD

**Issue by dandv** [vitaly-t/pg-promise#204]
Any plans? If not, would you recommend @langpavel's [node-pg-async](https://github.com/langpavel/node-pg-async)? (I saw you two debating in another project's issues.)

**Comment by vitaly-t** [comment]
It already works via Babel, plus the library supports ES6 generators. What else is there to plan?

**Comment by langpavel** [comment]
Haha.. My library is tiny but powerful. It offers you template strings. Difference is, you escaping input variables but I'm passing them to pg library. It is better do less..

**Comment by vitaly-t** [comment]
@langpavel two reasons why template strings are not suitable for query formatting:

1. Most of data exchanged between the server and the client is in the form of arrays, objects and arrays of objects, not as public variables.

Template strings require that formatted data being always visible within the current scope. This would require additional code for injecting data into the scope everywhere before the query can be formatted, resulting in a lot of duplicate code.

2. Template strings are not customizable, they are limited to the syntax of `${variable}`. Query formatting requires support for many formatting filters.

This library supports many filters - all highly demanded and used everywhere. Examples: `^`, `~`, `#`, `:name`, `:json`, `:csv`, `:value`. These are essential, and one cannot write proper query formatting without such filters.

**Comment by langpavel** [comment]
You are not right. Look at my code and then you can make assumptions. My escaping is better then yours.

**Comment by langpavel** [comment]
Btw escaping inside library is reason why I don't use your library and write my own. I know that my library is used by real projects with thousands of requests and it works well because it is tiny and just works

**Comment by vitaly-t** [comment]
@langpavel Now that's some classy trolling.
