### ISSUE TITLE
node-postgres fixed @5.1

### ISSUE THREAD

**Issue by vitaly-t** [vitaly-t/pg-promise#206]
This is a must-read for anyone who is considering direct use of [node-postgres](https://github.com/brianc/node-postgres) versus `pg-promise`.

---

There is a serious reason why this library is fixed strictly to version 5.1 of the [node-postgres](https://github.com/brianc/node-postgres) driver at present, and not being upgraded to the latest anymore.

Version 5.2 of [node-postgres](https://github.com/brianc/node-postgres) introduced [the new connection pool module](https://github.com/brianc/node-pg-pool), replacing the old one.

The new connection pool adds independent multiple instantiation, which can benefit only very specific projects where more than one database server is used heavily and concurrently from the same process.

It can benefit less than 0.1% of projects out there, while increasing complexity and confusion over the new pool usage. In terms of usability I see this being a step back for the driver.

But this is not the reason the driver reference isn't upgraded. I could easily hide the extra complexity within this library. The real reason is explained below.

The new connection pool compromises restoring broken connections with the database server. Up until version 5.1, the driver could reliably restore lost connectivity, once it is properly handled. The new connection pool can no longer guarantee the same. It is known to regularly fail to restore broken database connectivity, either crashing the application or - either way, unable to restore the connection till the app is restarted.

This is a major problem for any application, as database server availability is an issue everywhere, especially with shared hosting, like [Heroku](https://www.heroku.com/), [OpenShift](https://www.openshift.com/) and others. It goes unnoticed, as long as your library can pick it up and restore automatically, but when it can't - your whole product is compromised, and it is basically a killer for the product.

A few discussions were started around this problem, but as of today ([version 6.1.0](https://github.com/brianc/node-postgres/releases/tag/v6.1.0)) there is no progress in resolving it. The worst thing - you don't get caught by it till you deploy a real product, is where the pain begins, without any good solution, as it is impossible to detect when the driver fails to restore a connection.

My advise - stay away from [node-postgres](https://github.com/brianc/node-postgres) that's after 5.1, it is not a good platform for production, not yet. And `pg-promise` will continue using [node-postgres](https://github.com/brianc/node-postgres) 5.1 till the problem with the driver is resolved.

Related issues raised:
- [Handling connection timeouts](https://github.com/brianc/node-postgres/issues/1075)
- [Database disconnect handling](https://github.com/brianc/node-postgres/issues/1060)

**Comment by vitaly-t** [comment]
Another serious issue I stumbled upon in `6.x` version of the driver - broken connection strings support: https://github.com/brianc/node-postgres/issues/1141

**Comment by vitaly-t** [comment]
I keep going back and forth on this, considering to re-branch the entire `node-postgres` 5.1 as [pg-core], just wish I had enough time to finish it all.

Node.js 7 requires some changes, in order to stop throwing warnings. That's one good reason.

[pg-core]:https://github.com/vitaly-t/pg-core

**Comment by abenhamdine** [comment]
Hi, Vitaly,
I'm concerned about all this stuff, since we heavily use node-postgres in our HR application and don't want to get stuck with pg 5.1 for years.
I was wondering if this project would be interesting for you : https://github.com/mscdex/pg2
The author is a core contributor of nodejs.

**Comment by vitaly-t** [comment]
@abenhamdine thanks! It is interesting, academically. At this stage though, completely switching the driver would mean breaking compatibility all over the place. For example, I wouldn't even be able to implement such useful method as `stream`, and method `result` would be gone completely, these examples alone would break too much.

**Comment by devspacenine** [comment]
What is the relevent issue on the `node-postgres` project?

**Comment by vitaly-t** [comment]
@devspacenine it is right in the first post...

>Related issues raised:
>- [Handling connection timeouts](https://github.com/brianc/node-postgres/issues/1075)
>- [Database disconnect handling](https://github.com/brianc/node-postgres/issues/1060)

**Comment by vitaly-t** [comment]
Presently, the library can work with the latest version of `node-postgres`, which you can force by overriding the dependency. For that, add file `npm-shrinkwrap.json` to your project's root, with the following content:

```js
{
  "dependencies": {
    "pg-promise": {
      "version": "5.7",
      "dependencies": {
        "pg": {
          "version": "6.x"
        }
      }
    }
  }
}
```
This will force the latest version of the driver, which will work, though not optimally, still using the traditional `pg.connect` for connections rather than the new `pg-pool`. For the latter, I have created new branch `6.x` to start playing with, and to make some changes.

**Comment by vitaly-t** [comment]
### Important Update

Now there is full version of this library that uses the latest driver: [Branch 6.x of the library](https://github.com/vitaly-t/pg-promise/tree/6.x)

Although it is fully functional now, it is presently distributed as `pgp` package rather than `pg-promise`, until further notice.

**Comment by vitaly-t** [comment]
If somebody wants to provide feedback on switching from `pg-promise` package to `pgp`, it would be much appreciated! :wink:

**Comment by jmeas** [comment]
Nice @vitaly-t ! Were there any upstream changes around this, or are you just allowing this option in the meantime?

**Comment by vitaly-t** [comment]
@jmeas I continue improving branch 6.x right now, and just released 0.1.0. It is now an independent branch.

**Comment by vitaly-t** [comment]
[pg-promise 6.0.0 Beta](https://github.com/vitaly-t/pg-promise/releases/tag/v.6.0.0) has been released.

**Comment by vitaly-t** [comment]
Before closing this overly important issue...

Many of the points that have been discussed here at the beginning are still as valid, as there haven't been any fixes in the [driver](https://github.com/brianc/node-postgres) to address them.

However, [pg-promise v6] (branch `6.x`) has reached a point when it is as reliable as it can be, considering those issues in the driver (it is version 6.0.11 as of writing). Nonetheless, for the very same reasons, it is likely to stay as Beta for some time to come.

Feel free to use it, and report any new issues, if found. I will continue using this issue for references later, but closing it now, as it's been here for too long.

[pg-promise v6]:https://github.com/vitaly-t/pg-promise/tree/6.x

**Comment by AlJohri** [comment]
Just wanted to note that it seems like https://github.com/brianc/node-postgres/issues/1075 is resolved as of 6.2.4. https://github.com/brianc/node-postgres/issues/1060 may still exist

**Comment by vitaly-t** [comment]
@AlJohri we are way pass this...

**Comment by AlJohri** [comment]
Haha, I'm just catching up and updating old code. Still on 5.x right now 😄
