### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by taylorknopp** [vitaly-t/pg-promise#207]
I am trying to install a piece of software called Parse on top of Ubuntu.  I have managed to solve every error it throws other than a failure to install pg-promise. It also fails to install pg-promise if try to install it separately(sudo npm install pg-promise). I have tried installing on ubuntu 16.04 as well as 14 and 12.  every time I get this eror.

sh: 1: node: not found
npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.14
npm ERR! Linux 4.4.0-36-generic
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "install" "pg-promise"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn

npm ERR! pg-promise@5.3.3 postinstall: `node install.js`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the pg-promise@5.3.3 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the pg-promise package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs pg-promise
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls pg-promise
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/taylor/parse-server/npm-debug.log

I will also include that log file.
[npm-debug.zip](https://github.com/vitaly-t/pg-promise/files/468435/npm-debug.zip)

**Comment by vitaly-t** [comment]
Considering that the library has been in use on all existing OS-s for a very long time without any installation error, or any changes to the installation, I am inclined to think that something is wrong with your local software configuration.

**Comment by vitaly-t** [comment]
What are the versions of your Node.js and `typings`?

I would suggest reinstalling both.

**Comment by taylorknopp** [comment]
I believe my typings version is 1.3.3. My node.js version is 3.5.2 if I'm looking at the right thing. I made sure typings is installed and still get the same errors.

**Comment by vitaly-t** [comment]
>My node.js version is 3.5.2 

There is no such version of Node.js, and never existed.

**Comment by taylorknopp** [comment]
I have version 4.2.6 of Node.js  I just tried reinstalling it, though, and for some reason, this time, that fixed it.  Thanks for the help and patients with my noobishness in this area.

**Comment by vitaly-t** [comment]
Great! :)
