### ISSUE TITLE
Performance: task vs individual queries 

### ISSUE THREAD

**Issue by zevanb** [vitaly-t/pg-promise#208]
Hello,

I have to load massive amount of datas (over 20 millions values) distributed in about 2500 objects (I have to use stored procedures forcing me to load one object at time)

First, I tried something like this :

```
const objectList = await db.func('get_objectList')
  await Promise.all(objectlist.map(async function (objectId) {
    const rawData = await db.func('get_raw_data', [objectId])
    const object = transform_data(rawData)
    await db.func('insert_object', [object])
  }))
```

But I keep getting random ECONNRESET errors, and even when I catch the error and retry to load the object I get a new  error : `Error: Cannot invoke client.end() directly`

Then I looked at tasks :
https://github.com/vitaly-t/pg-promise/wiki/Common-Mistakes#tasks-versus-rootdirect-queries

Using tasks works well but it force me to create a single object with all the queries before running the batch to load objects. This single object is too massive and the processing time rise up from few minutes to more than five hours, which is not acceptable :

```
async function load() {
  return db.t(async function(t) {
    var queries = await Promise.all(
      objectList.map(async function(ojectID) {
        const rawData = await db.func('get_raw_data', [objectId])
        const object = transform_data(rawData)
        return t.func('insert_object', [object])
      })
    )
    return t.batch(queries)
  })
}
```

I also tried to run several task simultaneously by slipting  the objectList in several smaller list but my code just gets blocked when i try to get my raw_datas for the second batch while loading the first batch.

Do you have any idea to make it works ?

**Comment by vitaly-t** [comment]
Either of your approaches are wrong for this sort of thing. Never use `Promise.all` with this library, it is guaranteed to deplete your connection pool in no time and then go berserk.

The second one is not usable, as you will run into the IO limit on a single channel.

The only right approach is as follows...

Split your rows into multi-insert queries, with 1,000 - 10,000 rows per query, depending on size of each row, and then execute each such query.

I would to do it within a transaction.

You definitely should read this: [Performance Boost](https://github.com/vitaly-t/pg-promise/wiki/Performance-Boost).

And you definitely should use [helpers.insert](http://vitaly-t.github.io/pg-promise/helpers.html#.insert) to generate your multi-row inserts.

**Comment by zevanb** [comment]
I grouped my queries, and used sequence instead of promise.all in a single transaction. It works pretty well in few minutes.

Thank you for your help !
