### ISSUE TITLE
Doesn't return multiple columns with the same name properly

### ISSUE THREAD

**Issue by markasoftware** [vitaly-t/pg-promise#209]
When I am selecting multiple columns with the same names from different tables using a join, the result object simply is missing one of the columns. It would be nice to have some way to refer to the results based on which table they came from.

**Comment by vitaly-t** [comment]
This library returns exactly what [the driver](https://github.com/brianc/node-postgres) sends back, unchanged. If there is any issue like that, it should be logged against the driver.
