### ISSUE TITLE
Prepared statement with array as parameter

### ISSUE THREAD

**Issue by stanislasdrg** [vitaly-t/pg-promise#210]
Hello,
I encounter a `syntax error at or near ":"` when passing an array as parameter in a prepared statement.

Here is my code :
```
var myVar = new PS('myVar',getMyQuery(),[array]);

function getMyQuery(){
var query = "SELECT * IN tableName AS A WHERE A.tableEntry IN ($1:csv) ";
return query;
}

```

The SQL sentence works well when not in a prepared statement.
Is it a possible bug or the feature is unsupported in prepared statements  ? 

Thanks !

**Comment by vitaly-t** [comment]
It is a feature. See http://stackoverflow.com/questions/37782423/query-formatting-for-parameterized-queries/37790918#37790918

You have no access to the library's query formatting from inside Prepared Statements or Parameterized Queries.
