### ISSUE TITLE
Refcursor support for Node.js

### ISSUE THREAD

**Issue by nguruyeshwanth** [vitaly-t/pg-promise#212]
Hello,

I am trying to call a stored proc from node which returns a refcursor, ideally I would like to FETCH ALL from the refcursor and utilize that result set for my front end dashboard data population.

Please let me know if this feature is supported and/or if there are any other packages that offer this functionality.

Regards,
Guru

**Comment by vitaly-t** [comment]
See [Functions and Procedures](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#functions--procedures).

No other feature is needed, rows are all fetched automatically, if the function returns a recordset.
