### ISSUE TITLE
How to process refcursor from postgres function in pg-promise

### ISSUE THREAD

**Issue by alpeshrpatel** [vitaly-t/pg-promise#213]
How to process refcursor from postgres function in pg-promise ? 

We need resultset to process at client side . Do we have support functionality in pg-promose ? 

Syntax : 

CREATE OR REPLACE FUNCTION <function_name>(ref refcursor)
  RETURNS refcursor AS
$BODY$

declare
BEGIN
 OPEN ref FOR <select statement >;
 RETURN ref;

END;
$BODY$
  LANGUAGE plpgsql VOLATILE
  COST 100;

**Comment by vitaly-t** [comment]
See [Functions and Procedures](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#functions--procedures).
