### ISSUE TITLE
float is returned as string

### ISSUE THREAD

**Issue by Romsan01** [vitaly-t/pg-promise#214]
The results from DB supposed to be the float but it is returned as the string.
Here is my set up:
Table

Column        |            Type             |                       Modifiers                       | Storage  | Stats target | Description 
----------------------+-----------------------------+-------------------------------------------------------+----------+--------------+-------------
id                   | integer                     | not null default nextval('register_id_seq'::regclass) | plain    |              | 
mac_id               | text                        |                                                       | extended |              | 
temperature          | numeric(2,0)                |                                                       | main     |              | 
state                | boolean                     |                                                       | plain    |              | 
battery              | smallint                    |                                                       | plain    |              | 
position             | smallint                    |                                                       | plain    |              | 
temperature_internal | numeric(10,2)               |                                                       | main     |              | 
create_date          | timestamp without time zone |                                                       | plain    |              | 
last_updated         | timestamp without time zone |                                                       | plain    |              | 

Raw response
=========================
{ command: 'SELECT',
  rowCount: 1,
  oid: NaN,
  rows: 
   [ { id: 3,
       mac_id: 'AAAA',
       temperature: '24',
       state: true,
       battery: 1000,
       position: 1,
       temperature_internal: '22.50',
       create_date: Fri Aug 26 2016 16:42:04 GMT-0400 (EDT),
       last_updated: Fri Aug 26 2016 16:42:04 GMT-0400 (EDT) } ],
  fields: 
   [ { name: 'id',
       tableID: 16491,
       columnID: 1,
       dataTypeID: 23,
       dataTypeSize: 4,
       dataTypeModifier: -1,
       format: 'text' },
     { name: 'mac_id',
       tableID: 16491,
       columnID: 2,
       dataTypeID: 25,
       dataTypeSize: -1,
       dataTypeModifier: -1,
       format: 'text' },
     { name: 'temperature',
       tableID: 16491,
       columnID: 3,
       dataTypeID: 1700,
       dataTypeSize: -1,
       dataTypeModifier: 131076,
       format: 'text' },
     { name: 'state',
       tableID: 16491,
       columnID: 4,
       dataTypeID: 16,
       dataTypeSize: 1,
       dataTypeModifier: -1,
       format: 'text' },
     { name: 'battery',
       tableID: 16491,
       columnID: 5,
       dataTypeID: 21,
       dataTypeSize: 2,
       dataTypeModifier: -1,
       format: 'text' },
     { name: 'position',
       tableID: 16491,
       columnID: 6,
       dataTypeID: 21,
       dataTypeSize: 2,
       dataTypeModifier: -1,
       format: 'text' },
     { name: 'temperature_internal',
       tableID: 16491,
       columnID: 7,
       dataTypeID: 1700,
       dataTypeSize: -1,
       dataTypeModifier: 655366,
       format: 'text' },
     { name: 'create_date',
       tableID: 16491,
       columnID: 8,
       dataTypeID: 1114,
       dataTypeSize: 8,
       dataTypeModifier: -1,
       format: 'text' },
     { name: 'last_updated',
       tableID: 16491,
       columnID: 9,
       dataTypeID: 1114,
       dataTypeSize: 8,
       dataTypeModifier: -1,
       format: 'text' } ],
  _parsers: 
   [ [Function],
     [Function: noParse],
     [Function: noParse],
     [Function: parseBool],
     [Function],
     [Function],
     [Function: noParse],
     [Function: parseDate],
     [Function: parseDate] ],
  RowCtor: [Function],
  rowAsArray: false,
  _getTypeParser: [Function],
  duration: 15 }

temperature filed and temperature_internal needs to be returned as 24, and 22.50 and not as '24' and '22.50'.

**Comment by vitaly-t** [comment]
This is the only safe way to do it, so this is how [pg-types]() does it.

See also [pg-promise returns integers as strings](http://stackoverflow.com/questions/39168501/pg-promise-returns-integers-as-strings).

For `numeric` typeid is 1700, but the idea is exactly the same.
