### ISSUE TITLE
Debug db connection and parsed query

### ISSUE THREAD

**Issue by Luchillo** [vitaly-t/pg-promise#215]
My issue is very simple, i have certain query that executed in `PgAdmin 3` gives me one result, while executing it through the express api using this lib gives me null.

To debug better i would like to have a way to tell which DB is connected (since mine deals with multiple db depending on user data).

The important one is a way to log how does the query looks parsed, say my query accepts params and the query itself has `$1` placeholders, i would like to log the parsed query where the `$1` is replaced with the actual param `'2016-01-01` for example.

**Comment by vitaly-t** [comment]
For that there is [pg-monitor](https://github.com/vitaly-t/pg-monitor).

**Comment by Luchillo** [comment]
I've tried the monitor lib, however haven't been able to make it work, maybe i lacked some sort of config, it worked with the connections but query events were not working, dunno why.

Ended up using the manual `options` config.

**Comment by vitaly-t** [comment]
Did you use the basic `monitor.attach(options)`?

**Comment by Luchillo** [comment]
Yup, like this:
```js
    pgPromiseOptions = {
        query: (e) => {
            console.log('QUERY: ', e.query);
            if (e.params) {
                console.log('PARAMS:', e.params);
            }
        }
    }
    pgPromise = require('pg-promise')(pgPromiseOptions);
    pgMonitor = require('pg-monitor');
    pgMonitor.attach(pgPromiseOptions, ['query', 'error']);
```

**Comment by vitaly-t** [comment]
that should work.

**Comment by Luchillo** [comment]
Ok i see it working but it is duplicating the log.

Also the error i'm seeing is that the query itself returns a date like `2016-01-01` in `PgAdmin 3` while through pg-promise returns like `Thu, 01 Sep 2016 05:00:00 GMT`, does pg-promise makes any parsing on dates?

**Comment by vitaly-t** [comment]
>Ok i see it working but it is duplicating the log.

that's what you code does, you either log through monitor or event query, not both.

> does pg-promise makes any parsing on dates?

No. The underlying driver does, converting Date/Time into a  Javascript object.

**Comment by Luchillo** [comment]
>that's what you code does, you either log through monitor or event query, not both.

Then i pass options only to monitor?
>No. The underlying driver does, converting Date/Time into a Javascript object.

How do i stop it from converting it? do i need to format in JS to string then?

**Comment by vitaly-t** [comment]
You do as you like.

What's wrong with the current Date presentation?

**Comment by Luchillo** [comment]
I use it as param to another query and is messing up my query.

**Comment by vitaly-t** [comment]
[pg-types](https://github.com/brianc/node-pg-types) does all the conversion, which can be access via `pgp.pg.types`, if you want to change the formatter.

**Comment by Luchillo** [comment]
That's somewhat cumbersome, i'll just parse the JS Date object as needed. Thanks.

**Comment by vitaly-t** [comment]
That's actually the standard way to add your own type parsers within that library. It is not in any way cumbersome, but it is global.

**Comment by dfloresgonz** [comment]
this is printing all the queries, is there a way to just print when I want it? thanks

**Comment by vitaly-t** [comment]
> his is printing all the queries, is there a way to just print when I want it?

Format the query via [pap.as.format](http://vitaly-t.github.io/pg-promise/formatting.html#.format), and print the result.
