### ISSUE TITLE
Publish typings at DefinitelyTyped?

### ISSUE THREAD

**Issue by Retro64** [vitaly-t/pg-promise#216]
Is there any plan to provide the new typings to DefinitelyTyped as there is just the deprecated header available? [https://github.com/DefinitelyTyped/DefinitelyTyped/tree/70107076ee251e9dd786cf749df73125d079663e/pg-promise](url)

**Comment by vitaly-t** [comment]
Your link is invalid, and if it were valid, you would see that the file there says:

`// deprecated. see https://github.com/vitaly-t/pg-promise/tree/master/typescript`.

**Comment by Retro64** [comment]
Therefore I asked if there will be any update

**Comment by vitaly-t** [comment]
No, no such plans. The TypeScripts will remain shipping with the library, for now.
