### ISSUE TITLE
Simple insert

### ISSUE THREAD

**Issue by gkiely** [vitaly-t/pg-promise#217]
Correct me if there's already a way to do this.

Use case: often times I find myself updating the insert query in three different places. It would be great if I could just pass an object and let it generate the query automatically.

Given a post object:
`db.query('insert into posts (title, description, amount, date) values($1, $2, $3, $4)', [post.title, post.description, post.amount, post.date]);`

Would become:
`db.insert('posts', post);`

Currently I'm using the following function in this way:
```js
let generateInsert = function(str, obj){
  let count = 0;
  let vals = "values (";
  let arr = [];

  str = 'insert into ' + str + ' (';
  for(let i in obj){
    count++;
    str += i + ',';
    vals += '$' + count + ',';
    arr.push(obj[i]);
  }
  str = str.replace(/,$/, ')');
  vals = vals.replace(/,$/, ')');

  return db.query(str +  vals, arr);
};

let query = generateInsert('posts', obj);
```

**Comment by L-u-k-e** [comment]
Check out the helpers namespace:  http://vitaly-t.github.io/pg-promise/helpers.html

`db.insert(post, null, 'post')`

**Comment by vitaly-t** [comment]
@gkiely there is method [helpers.insert](http://vitaly-t.github.io/pg-promise/helpers.html#.insert) for it.

**Comment by gkiely** [comment]
Awesome, thanks guys.
