### ISSUE TITLE
Scalar query helper

### ISSUE THREAD

**Issue by BrianRosamilia** [vitaly-t/pg-promise#218]
I have been starting to use this library and thought something like the following could be useful in the core of the library
```
var pg = require('pg-promise')({
    extend: function (obj, dc) {
        obj.scalar = async function (query, ...params) {
            var res = await obj.one(query, ...params);
            return res[Object.keys(res)[0]];
        }
    }
});
``` 

You might like to add some more sanity checks (ensure there's only one key returned), but I think being able to automatically exhume a scalar from its object in one statement is really nice.  There are a few other database libraries that offer this functionality.

Thoughts?

**Comment by vitaly-t** [comment]
To extract the name of the the first property? What use is it?

**Comment by vitaly-t** [comment]
Define the function to get your first-property value:
```js
var scalar = a=>a[Object.keys(a)[0]];
```
then you can write your query like this:
```js
db.one(query, values, scalar);
```
It is better, being explicit, and lets you do more specific stuff, like defining this:
```js
var scalarInt = a=>+a[Object.keys(a)[0]];
```

**Comment by BrianRosamilia** [comment]
I just thought it would be convenient for 

```db.scalar('select count(*) from users``` 

to be supported to return a single value, not an object.  Of course this can be done in numerous ways,  I'm surprised a simple way to get a scalar value back is not supported and that objects are the minimum a user is able to work with.

Also your library already coerces integers, no need to have a scalarInt function.

**Comment by vitaly-t** [comment]
> objects are the minimum a user is able to work with

Row objects are the basic that any application needs.

>Also your library already coerces integers, no need to have a scalarInt function

Not quite. All 64-bit integers arrive as string ([see why](http://stackoverflow.com/questions/39168501/pg-promise-returns-integers-as-strings)), like in that example I showed.

**Comment by BrianRosamilia** [comment]
>Row objects are the basic elements that any application needs.

Many database libraries would disagree with you that the user needs to always be dealing with a complex object

http://docs.sqlalchemy.org/en/latest/orm/tutorial.html#returning-lists-and-scalars
https://github.com/StackExchange/dapper-dot-net/blob/61e965eed900355e0dbd27771d6469248d798293/Dapper.Tests/Tests.Async.cs#L406
http://docs.doctrine-project.org/projects/doctrine-orm/en/latest/reference/dql-doctrine-query-language.html#query-result-formats

It doesn't matter much to me though, the library is pluggable so this isn't a burden for me--just your other users.  I honestly thought it was just an oversight not offering this.  You seem to really be against it so feel free to close.

**Comment by vitaly-t** [comment]
The bottom line is, this is not an ORM, it is lower-level, to work with queries directly, to allow access to complete underlying structure, for maximum flexibility. In that purpose it succeeds.
