### ISSUE TITLE
What is `task` for?

### ISSUE THREAD

**Issue by markasoftware** [vitaly-t/pg-promise#219]
Sorry, this is more of a question than an issue, but why does the `task` method exist? Doesn't pg promise use client pooling to put everything into one connection by default anyways?

**Comment by vitaly-t** [comment]
[From documentation](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#tasks):

>[Tasks] are for executing multiple queries against the same connection. Also see [Chaining Queries].

If you do not use tasks, then each query acquires its own connection from the pool, and then releases it back when the query is finished.

[Tasks]:https://github.com/vitaly-t/pg-promise#tasks
[Chaining Queries]:https://github.com/vitaly-t/pg-promise/wiki/chaining-queries

**Comment by markasoftware** [comment]
Is there any reason that it does not automatically put queries on the same connection when possible, like node-Postgres does by default? Doesn't the current implementation encourage opening a new db connection for every http request because the only other way is to basically wrap your whole application in a db.task?09.10.2016, 05:19, "Vitaly Tomilov" <notifications@github.com>:From documentation:


Tasks are for executing multiple queries against the same connection. Also see Chaining Queries.


If you do not use tasks, then each query acquires its own connection from the pool, and then releases it back when the query is finished.

**Comment by vitaly-t** [comment]
>like node-Postgres does by default

What do you call the default? There is a recommended approach to query execution within `node-postgres`, using the connection pool, which is what this library is built upon. It is best in terms of performance and predictable connection management.

>Doesn't the current implementation encourage opening a new db connection for every http request

It does, and this is what this library encourages also. You should use direct query execution when only one query needs to be executed, and you should use tasks when executing more than one query.

**Comment by markasoftware** [comment]
Correct me if I'm wrong, but doesn't the pool keep connections open, even when you're not using them, for up to 30 seconds, and will automatically put new queries onto the existing connections if they're idle?

**Comment by vitaly-t** [comment]
You are correct.

**Comment by markasoftware** [comment]
So, to be clear, if I do something like this:

`db.query('query here').then(r => db.query('another query'));`

Will they use the same connection? The second query does not start until the first is completed, so shouldn't the client from the first one be idle and waiting in the pool?

**Comment by vitaly-t** [comment]
They **presumably** will. Note, presumably, because we indeed have finished the first query, but due asynchronous nature of Node.js IO and promises, there can be a query elsewhere that will acquire the connection in between, pending a racing condition, so there is never any guarantee.

**Comment by markasoftware** [comment]
Ok, I think I understand now, thank you for all your help. But when exactly would somebody want to use a task? Shouldn't the connection pool put queries onto already-open connections if possible, meaning that a task doesn't have any real performance benefit?

**Comment by vitaly-t** [comment]
The issue is not with performance, but with the fact that you get very limited number of physical connections that you have to use concurrently. For that one needs a reliable mechanism for controlling the number of connection being used, trying to keep them to the minimum.

Another side of the coin - transactions, which require use of the same physical connection.

**Comment by markasoftware** [comment]
Doesn't pg pool support a connections limit so that you can't ever get too many connections, task or no task?

**Comment by vitaly-t** [comment]
All these considerations are not some sort of invention in this library, they are inherent from `node-postgres`, which in turn inherits them from what Node.js can do in terms of concurrent IO + PostgreSQL limits.

You can set the number of connections of up to 100, but at that point you will start seeing Node.js choking trying to process so many physical connections in a single process.

**Comment by markasoftware** [comment]
Ok, I think I get it. Thanks!
