### ISSUE TITLE
money[] not being converted into JavaScript array

### ISSUE THREAD

**Issue by devspacenine** [vitaly-t/pg-promise#22]
Not sure if this is an issue for pg-promise or pg. Columns of the type "money[]" are not being converted into JavaScript arrays. For example, given the following table and data:

``` sql
CREATE TABLE public."MoneyArrayTest"
(
  moneys money[],
  int_array integer[]
);

INSERT INTO public."MoneyArrayTest" (moneys, int_array)
VALUES ('{2.50, 1.99, 200.00}', '{1,2,3}')
```

Exucuting the following:

``` javascript
db.any('select * from "MoneyArrayTest"').then(function (results) {
    console.log('results: ', results);
});
```

Will return this:

``` json
[
     {
          "moneys": "{$2.50,$1.99,$200.00}",
          "int_array": [ 1, 2, 3 ]
     }
]
```

**Comment by vitaly-t** [comment]
I won't get a chance to look at it till tomorrow, but it looks like definitely an issue in pg, as pg-promise doesn't interpret that kind of result, just forwards what pg sends back.

**Comment by vitaly-t** [comment]
I have looked into this in detail, and logged this bug against node-postgres: https://github.com/brianc/node-postgres/issues/781

You can try to persuade node-postgres author for a quick fix, but as far as pg-promise goes, it does not post-process any of the data returned from pg, as was stated earlier. I'm not sure if it is even worth leaving this issue open here.

**Comment by vitaly-t** [comment]
Anything related to the issue will be posted at: https://github.com/brianc/node-postgres/issues/781

And in the meantime, I am closing the issue here, as not relevant to **pg-promise**.

**Comment by vitaly-t** [comment]
This issue won't be addressed by [node-postgres](https://github.com/brianc/node-postgres), it seems, because of the locale involved in this.

And it seems that the proper way to do it is via [node-pg-types](https://github.com/brianc/node-pg-types), like this:

```javascript
pgp.pg.types.setTypeParser(791, function(val) {
  // parse and return;
});
```

**Comment by Aysnine** [comment]
I also encountered this problem.

some data:
```sql
create table foo (
    my_array text[]
);
insert into foo (my_array) values (ARRAY['hello', 'world']::text[]);
```
if select like: 
```sql
select my_array from foo; -- output string: '{hello,world}'
``` 
but try this:
```sql
select my_array::text[] from foo; -- output array: ['hello', world]
```
simple and nice :)

**Comment by vitaly-t** [comment]
@Aysnine This got nothing to do with the issue, where arrays of `money` were discussed.
