### ISSUE TITLE
using Array.prototype.formatDBType doesn't seem to work correctly with positional parameters

### ISSUE THREAD

**Issue by kay999** [vitaly-t/pg-promise#221]
I tried using Array.prototype.formatDBType to convert array-values to json instead of using the default formatting. But it doesn't work with positional queries because pg-promise is now formatting the whole parameter-list of a query as a single JSON-object instead of formatting each parameter. 

Shouldn't formatting only been applied to single parameters instead of the values-object as a whole?

**Comment by vitaly-t** [comment]
Are you trying to create a JSON object that represents the entire array or you want an array where each value is turned into JSON?

**Comment by kay999** [comment]
I just want to insert arrays as json by default. So I tried to override formatting by using Array.prototype.formatDBType. 

This works perfectly as long as I supply the query parameters as an object, for example

`db.query('update data=$[data] where id=$[id]', { id:id, data:data });`

But if I use positional parameters, it doesn't work anymore:

`db.query('update data=$2 where id=$1', [id, data]);`

The reason is that the whole `[id, data]` is now converted to a json-string and inserted as "$1" in the query.

**Comment by vitaly-t** [comment]
First of all, do not override Array, this is though possible, also dangerous, as it affects too much.

Second, change your query to this:

```js
db.query('update table set data=$2:json where id=$1', [id, data]);
```

**Comment by kay999** [comment]
My problem with your solution is that using ":json" only works if I know that "data" expects json. This is easy to to in hand-written code but it doesn't work for me because it's auto-generated based on the column names (without type informations). 

Now everything works fine as long I don't try to insert array-values in json-columns. Everything else works: Strings, Numbers, Objects. But because pg-promise converts arrays to "Array[]" syntax inserting array-valued data doesn't work for json columns.

Using Array.prototype.formatDBType works fine as long parameter-values are supplied as Object. Only with positional parameter it doesn't work because pg-promise translates the whole value-array instead each value of it's own. I suspect that this behaviour is easily patchable just by using a "map" on the values object instead of translating the thing from top-level recursively.

This is IMO quite unexpected so It took me some time to figure out why positional parameters doesn't work. If you don't intend to change this, please add a small note in the docs about this behaviour.

**Comment by vitaly-t** [comment]
So what's wrong then with the original solution I gave you?

**Comment by kay999** [comment]
This solution doesn't work directly. For example

` Pgp.as.format('Result: $1, $2', [arrayAsJSON([1, 2]), arrayAsJSON('x')]`

gives 

`'[1,2]', '"x"'`

instead of 

`'[1,2]', 'x'`

But if Array override is to dangerous, I can use map/mapValues/isArray to find and map all arrays in the value-array to JSON. It just looked as a simple and direct solution to use formatDBType on arrays...

**Comment by vitaly-t** [comment]
> instead of `'[1,2]', 'x'`

`x` is not a valid JSON literal presentation, it is `"x"`.

Your expectation is an invalid JSON.

**Comment by kay999** [comment]
You're right. My code only uses JSON arrays and objects as values so I never ran into this problem.

But if I convert all input data this way normal text fields will get still the wrong input. So I need to do a selective transformation of the input data anyway. Not really a big deal but always needs a wrapper-call.

**Comment by vitaly-t** [comment]
You can wrap into a Custom-Type function any type, and format it in any way you like, as shown with function `arrayAsJSON`.

I'm not sure though why one would need it. My feeling is telling me there is something you are trying to achieve that can already be done automatically, but you do not use it. This is the most common case with this library :)

**Comment by kay999** [comment]
I have code which creates sql-statements like insert/update based on a table and column-names. The data are simply arrays of data-elements which should be inserted via those statements. The data elements are basic values (string, number, bool, null) but also objects and arrays. Objects and arrays should both written into JSONB-type columns. The type of the columns is not known to the statement-generator so it can't create something like "$1:json".

With objects this is no problem, because pg-promise automatically converts objects to JSON, but with arrays this doesn't work automatically because pg-promise converts to array(...) notation (which is no valid JSON and thus rejected from Postgresql).

I've solved it now by using your code to selectively wrap arrays in the the input data via checking by Array.isArray.

**Comment by vitaly-t** [comment]
It was a standard solution anyway, not the Array extension. So I think it is sorted now.

**Comment by vitaly-t** [comment]
F.Y.I. Important breaking change in [v6.5.0](https://github.com/vitaly-t/pg-promise/releases/tag/v.6.5.0).
