### ISSUE TITLE
Question about SQL injection

### ISSUE THREAD

**Issue by cmelone** [vitaly-t/pg-promise#223]
I've seen other libraries automatically protect against it, does pg-promise too? Or do I need to implement my own solution/use prepared statements?

Thanks.

**Comment by vitaly-t** [comment]
You can prepared statements, or if you only send column names, then you can use [SQL Names] to escape them properly.

[SQL Names]:https://github.com/vitaly-t/pg-promise#sql-names

**Comment by cmelone** [comment]
If I created my query with something like this:

```javascript
function insert(table, values) {
  const keys = Object.keys(values),
  columns = keys.join(', '),
  placeholders = keys.map((k, i) => '$' + (i + 1)).join(', '),
  query = `INSERT INTO ${(table)} (${columns}) VALUES (${placeholders})`;

  return db.none(query, keys.map(k => values[k]));
}

...

const data = {
  name: req.body.name,
  email: req.body.email,
  phone: req.body.phone
}

...

insert('farms', data)
  .then(function() {
    console.log('Success');
  })
  .catch(function(err) {
    console.log('Error: ' + err);
  })
```

Would it be protected against SQL injection?

**Comment by vitaly-t** [comment]
Bot quite, but this would be:

```js
function insert(table, values) {
  const keys = Object.keys(values),
  columns = keys.join(),
  placeholders = keys.map((k, i) => '$' + (i + 1)).join(),
  query = 'INSERT INTO ${table~} (${columns}) VALUES (${placeholders})';

  return db.none(query, keys.map(k => values[k]));
}
```

However, using [helpers.insert](http://vitaly-t.github.io/pg-promise/helpers.html#.insert) is so much better ;)

**Comment by DISKONEKTeD** [comment]
I'm trying to do something like this:

```javascript
function getSingleUser(req, res, next) {
  let id = req.params.id;
  db.one('SELECT * FROM users WHERE id = $1~', id)
    .then(function (data) {
      res.status(200)
        .json({
          status: 'success',
          data: data,
          message: 'retrieved ONE user'
        });
    })
    .catch(function (err) {
      return next(err);
    });
}
```

but that obviously wraps the value with double quotes, and this in turn, causes an error to be thrown with postgres (column does not exist etc). So I'm assuming I'm misunderstanding on how to protect my query from SQL injection? Is there a method I overlooked in the library? I searched the issues and I couldn't find anything.
