### ISSUE TITLE
Question (best practice)

### ISSUE THREAD

**Issue by jdabbs003** [vitaly-t/pg-promise#224]
Are there examples of a transaction containing dependent operations (_i.e., an insert returning the new row key that's used in subsequent updates and inserts, an optimistic update checking a row revision in the where clause, etc_)?  I assume this has to be done with nesting but I can't see how to make result sets from a prior operation available to the next operation.  Sorry if this is the wrong forum.  Thanks.

**Comment by vitaly-t** [comment]
>I can't see how to make result sets from a prior operation available to the next operation

This is a generic promise question, not exactly related to this library. See how it is done with promises in general.

**Comment by vitaly-t** [comment]
See http://stackoverflow.com/questions/28250680/how-do-i-access-previous-promise-results-in-a-then-chain

**Comment by jdabbs003** [comment]
Thank you for this.  With the promise chain, the underlying PosgreSQL transaction wraps the outermost Promise inside the tx object?
