### ISSUE TITLE
pgp.helpers.insert doubt

### ISSUE THREAD

**Issue by jmpmscorp** [vitaly-t/pg-promise#226]
Hi and thanks for your work.

How can i use pgp.helpers.insert() with a auto generated primary key like serial? If I put "cnd:true" only on upgrade query is skipped. Of course, if I put 'def: null', a database conflict is shown due to pkey can't be NULL. is there anyway to solve it??

Thanks and bye : )

**Comment by vitaly-t** [comment]
Type `ColumnSet` is used for generating queries. If you have a column that's never to be generated, then why have it in the `ColumnSet` in the first place?

Are you trying to reuse a `ColumnSet` for both `UPDATE` and `INSERT`?

**Comment by jmpmscorp** [comment]
Thank you for reply.

As you supposed, I'm trying to reuse same ColumnSet on UPDATE and INSERT queries. I found an approach like:

```
class Persona(){
    constructor(){
        this.InsertColumnSet = pgp.helpers.ColumnSet([
            {
                name:'name',
                skip:function (name){
                    return !this.hasOwnProperty(name);
                }
            },
            {
                name:'surname',
                skip:function (name){
                    return !this.hasOwnProperty(name);
                }
            },
            {
                name:'city',
                skip:function (name){
                    return !this.hasOwnProperty(name);
                }
            }            
        ], {table:{table:'person', schema:'public'}});

        this.ColumnSet = this.InsertColumnSet.extend(['?idPerson']);
    }
}
```

Is there better approach?

Another question: Is there anyway to get only name columns in Array? I was looking for in API but I didn't find this helper or method. I use:

```
this.getNameColumnsAsArray()
{
    let columns = [];

    for (let i in this.ColumnSet.columns)
        columns.push(this.ColumnSet.columns[i].name);

    return columns
}
```
Bye : )

**Comment by vitaly-t** [comment]
This code:

```js
class Persona(){
    constructor(){
        this.InsertColumnSet = pgp.helpers.ColumnSet([
            {
                name:'name',
                skip:function (name){
                    return !this.hasOwnProperty(name);
                }
            },
            {
                name:'surname',
                skip:function (name){
                    return !this.hasOwnProperty(name);
                }
            },
            {
                name:'city',
                skip:function (name){
                    return !this.hasOwnProperty(name);
                }
            }            
        ], {table:{table:'person', schema:'public'}});

        this.ColumnSet = this.InsertColumnSet.extend(['?idPerson']);
    }
}
```

can be replaced with:

```js
class Persona(){
    constructor(){
        this.table = new pgp.helpers.TableName('person', 'public');
        this.InsertColumnSet = pgp.helpers.ColumnSet(['name', 'surname', 'city'], {table: table});
        this.ColumnSet = this.InsertColumnSet.extend(['?idPerson']);
    }
}
```

I don't understand why you do this:
```js
                skip:function (name){
                    return !this.hasOwnProperty(name);
                }
```
as this is the default behavior already.

If you wanted to do the opposite:
```js
                skip:function (name){
                    return this.hasOwnProperty(name);
                }

```
the you would simply add option `inherit` when constructing your `ColumnSet` object.

**Comment by jmpmscorp** [comment]
Hi again.

I use 
```
skip:function (name){
       return !this.hasOwnProperty(name);
}
```
because f I put 'def:value' on a column and I do UPGRADE query, if property is not in JSON object passed, default value is set and I don't want this. I upgrade fields through PATCH verb and request JSON object hasn't all properties than ColumnSet has. Due to this, defs values are set and I want to skip this default value because I needn't. If I only want to upgrade a field, I don't need pass any other value... (I don't know if I explain well, i wish you can understand me...).

Maybe, there is a better way to attach this behavior.

Thank you.

**Comment by vitaly-t** [comment]
Uh, ok, I got you now, I wasn't looking at the code close enough to see you were checking for the object properties and not columns :)

In this case I would just use it like this:

```js
function skipMissingProp(name) {
    return !this.hasOwnProperty(name);
}

class Persona {
    constructor() {
        this.table = pgp.helpers.TableName('person', 'public');
        this.csInsert = pgp.helpers.ColumnSet([
            {
                name: 'name',
                skip: skipMissingProp
            },
            {
                name: 'surname',
                skip: skipMissingProp
            },
            {
                name: 'city',
                skip: skipMissingProp
            }
        ], {table: this.table});

        this.csUpdate = this.csInsert.extend(['?idPerson']);
    }
}
```

**Comment by jmpmscorp** [comment]
Thank you very much for your help.

I was working in a rigth way more or less. I'll change code like you advised me.

Thank you again.

**Comment by vitaly-t** [comment]
n.p. ;)

**Comment by vitaly-t** [comment]
@jmpmscorp This story continued as feature request #239
