### ISSUE TITLE
Error during pg-promise when typings is not installed

### ISSUE THREAD

**Issue by goenning** [vitaly-t/pg-promise#227]
Hey,

I'm currently trying to deploy an app that uses pg-promise in a Docker container, but the following error (not helpful) is being thrown.

Looking at `install.js`, seems like a problem with typings because I don't have it installed inside the container. 

> pg-promise@5.3.4 postinstall /usr/src/app/node_modules/pg-promise
> node install.js

> ERROR: compose.cli.main.main: Service 'api' failed to build: The command '/bin/sh -c npm install --production' returned a non-zero code: 1

According to https://docs.npmjs.com/misc/config#production, NODE_ENV is set to `production` when executing `npm install --production`. 

What if pg-promise check NODE_ENV before calling typings? `typings install` should only be executed on non-production environments.

I'll run some tests to make sure this is really the reason, just wanted to log this issue to get your thoughts about it.

**Comment by vitaly-t** [comment]
By any chance this one is related? - https://github.com/vitaly-t/pg-promise/issues/207

**Comment by goenning** [comment]
Not really. 

But I found the answer here https://github.com/npm/npm/issues/11100

My docker host is a Digital Ocean 512mb server which is causing trouble due to its low memory. Just tried yarn instead of npm. It worked 😄

Anyway, it's not pg-promise related.
