### ISSUE TITLE
Scalar function return values?

### ISSUE THREAD

**Issue by scharris** [vitaly-t/pg-promise#228]
I'm seeing scalar return values from proc() calls from functions wrapped in an object with the function name as key, wondering if this is the desired behavior?

-- Example function which should just return an int.
create function foo() returns int as $$begin return 22; end;$$ language plpgsql;

-- Call function with pg-promise "proc".
db.proc('foo', []).then( (num) => res.status(200).json({ returned_num: num }) );
 
-- {"foo": 22} was returned, not just 22.
===> { "returned_num": { "foo": 22 } }

I would have expected just { "returned_num": 22 }.  Is there a way to prevent the extra wrapping of the scalar values in results from proc() or is this by design?

**Comment by vitaly-t** [comment]
The same way as for other methods:
`db.proc('foo', [], a=>a.returned_num)`

**Comment by scharris** [comment]
Thanks for your comments, that makes sense.

I hadn't realized Postgres actually treats the return value of foo as a "result-set" like object itself also, at least in psql,  and not just a simple scalar, because in psql it shows the result with label "1 row(s)" and with a column name "foo".  So the library is just being consistent to map those to one or more js objects in the usual way.  So in that light it's not surprising behavior at all.

**Comment by vitaly-t** [comment]
>I hadn't realized Postgres actually treats the return value of foo as a "result-set" like object itself

Well, PostgreSQL iteself doesn't, it returns just raw data, but the underlying driver `node-postgres` does, converting all returned rows into objects.

**Comment by scharris** [comment]
Libraries are not involved in this point I was trying to make - I think what I was trying to get at could be summarized as:  functions can only be evaluated by the SQL engine (even for local assignments within functions in Postgres the SQL engine is invoked), and that the SQL engine will only give back relations not scalars.

postgres=# select * from foo();
 foo
-----
  22
(1 row)

And I guess that "foo" is what becomes the key in the result object when the libraries receive the result.
