### ISSUE TITLE
DB connections are not closed and have idle status

### ISSUE THREAD

**Issue by lexakozakov** [vitaly-t/pg-promise#229]
Please, correct me if I'm wrong. But I still see idle connections in DB after pgp.end(). Why?
I'm closing all connections after all DB queries are executed. 

config.js
```
var Promise = require("bluebird");
var pgp = require('pg-promise')({
    promiseLib: Promise
});
module.exports.db = pgp("postgres://....");
```

getItems.js
```
var db = require("./config").db;
module.exports = () => {
    return db.any("SELECT * FROM table");
};
```

main.js
```
var pgp = require('pg-promise')();
var getItems = require("./getItems");

Promise.all([getItems()])
  .spread((items) => console.log(items))
  .catch(error => reject(error))
  .finally(() =>  pgp.end()

```

**Comment by vitaly-t** [comment]
>I'm closing all connections after all DB queries are executed.

You should absolutely NOT do that. Calling `pgp.end()` shuts down the connection pool, and effectively the entire library. It is only to be called when implementing a command-line utility that needs to exit right after it is finished.

>Please, correct me if I'm wrong. But I still see idle connections in DB after pgp.end(). Why?

I'm not sure what kind of side effect one might run into after trying to call `pgp.end()` repetitiously - something it was never designed for.

**Comment by lexakozakov** [comment]
I'm using pg-promise in AWS Lambda. You might be aware about the issues with AWS Lambda. How can I control the connections?

**Comment by vitaly-t** [comment]
Sorry, I know nothing about  AWS Lambda.

**Comment by lexakozakov** [comment]
AWS Lambda is a microservices architecture. Multiple services (AWS Lambda) speak to my PostgresSQL and i'm running out of all available pool connections. 

Can I use pg-promise without pool connection, but just general connection - connect to DB, trigger a query, close connection?

**Comment by vitaly-t** [comment]
>i'm running out of all available pool connections

That means there is an issue in how you use your connections, which is what should be fixed.

>Can I use pg-promise without pool connection

Such a solution cannot scale well.

**Comment by lexakozakov** [comment]
I just read some docs. We have to stop using connection pooling in AWS Lambda. Amazon handles this very badly.

How can I terminate any connection manually? What function I have to call?

**Comment by lexakozakov** [comment]
I set poolSize option to 0 and I see that connections are still alive until I terminate the script. How can I release connection even when script is alive?

**Comment by lexakozakov** [comment]
Sorry, I used wrong terminology. I have to terminate the pool connections, not just to release a connection to pool.

**Comment by vitaly-t** [comment]
I'm afraid you are looking at it from the wrong angle. If you use the connection pool correctly, it will give you no trouble. You just need to understand better what that correct pool usage actually means.

Is your code published on GitHub?

**Comment by lexakozakov** [comment]
Unfortunately, no. But I'm not the one who have a such issue. 
Quite fresh comments can be found [here](https://github.com/brianc/node-postgres/issues/930) and [here](https://forums.aws.amazon.com/thread.jspa?threadID=216000).

**Comment by vitaly-t** [comment]
Those issue relate to invalid use of the pool.

**Comment by lexakozakov** [comment]
Definitely, the issue is not related to connection pool itself. 

Thank you. I appreciate your help.
