### ISSUE TITLE
Pool size and timeout settings.

### ISSUE THREAD

**Issue by knexp** [vitaly-t/pg-promise#23]
How to set the pool size and connection timeout settings through pg-promise configuration?

Thanks

**Comment by vitaly-t** [comment]
**pg-promise** doesn't control **node-postgres** settings, and if you need to access those, the library exposes property `pgp.pg` - instance of the **node-postgres** library.

So, for example, to change the pool size, you can do:

```javascript
pgp.pg.defaults.poolSize = 20;
```

Note that normally you do not need to change the pool size, using the automated connection support provided by **pg-promise**.

As for the connection timeout, I'm not sure if **node-postgres** supports that, and if it does, somehow, this question should be addressed to **node-postgres**.

**Comment by knexp** [comment]
Thanks @vitaly-t .

**Comment by woolfi182** [comment]
thanks @vitaly-t, it work for me. I tried to set this parameter in "cn" option but it not worked.
