### ISSUE TITLE
Issue With Promise Returns?

### ISSUE THREAD

**Issue by paulxtiseo** [vitaly-t/pg-promise#236]
I have the following code. For some reason, the promise returned by the `oneOrNone` line does not work. However, the other two simpler returns (of a value and a Bluebird `Promise.resolve('yay')`) does seem to drop into the `then` in the uppermost (third) block of code below. Those two result in the console message from `console.log('dbMan.initializeMigrations then', data);` but the `oneOrNone` results in nothing. No error, no anything, silently ignoring the `then` and the `catch`.

Any suggestions on determining what's going on?

```
const pgp = require('pg-promise')({ promiseLib: promise });

providers.postgres = {};

providers.postgres.connect = (connection) => {
  connection.adapter = pgp(connection.settings);
  return connection;
};

providers.postgres.initMigrate = function(connection) {
  console.log('providers.postgres.initMigrate', connection);
  //return 'yay';
  //return promise.Promise.resolve('yay');
  /*return connection.adapter.oneOrNone('SELECT table_name FROM information_schema.tables WHERE table_name=\'migration\';')
    .then(data => {
      console.log('OneOrNone data',data);
      return 'yay';
    });*/
```
Called from:
```
DatabaseManager.prototype.initializeMigrations = function(nameOrAlias) {
  let self = this;
  return self.connect(nameOrAlias)
    .then(conn => {
      switch(conn.settings.dialect) {
        case 'postgres':
          return providers.postgres.initMigrate(conn);
          break;
        default:
          return promise.Promise.reject('Dialect ' + conn.settings.dialect + ' not implemented.');
          break;
      }
    });
};
```
And, further upstream in the caller stack (where dbMan is an instance of DatabaseManager):
```
return dbMan.initializeMigrations(configObj.name)
    .then(data => {
      console.log('dbMan.initializeMigrations then', data);
    })
    .catch(err => {
      console.log('wut!', err);
    });
```

**Comment by vitaly-t** [comment]
How is it that you are `.then` for the result from the `connect` that does not return any promise?

**Comment by paulxtiseo** [comment]
Actually, the `connect` being called is:

```
DatabaseManager.prototype.connect = function(nameOrAlias) {
  let self = this;
  return new promise(function(resolve, reject) {
    let conn;
    try {
      conn = self.getConnectionByNameOrAlias(nameOrAlias);

      if(!conn) {
        reject(new verror('No match on name/alias.'));
      }

      if(!conn.adapter) {
        switch(conn.settings.dialect) {
          case 'postgres':
            resolve(providers.postgres.connect(conn));
            break;
          default:
            reject(new verror('Not implemented!'));
            break;
        }
      }
    }
    catch(e) {
      reject(new verror(e, 'Could not connect.'));
    }

    resolve(conn);
  });
};
```

_(Eventually, there would be more dialects handled, hence the layers; postgres is my first one, via pg-promise.)_

**Comment by vitaly-t** [comment]
Can you even see method `oneOrNone` being executed? You can always add some logging to see whether you are getting inside that method at all.

**Comment by paulxtiseo** [comment]
I actually go and add a `console.log` in the library code or `oneOrNone()`, and it was triggered/displayed. The odd thing is that it doesn't seem to be percolating back up properly. Neither the `then` nor the `catch` in `initMigrate` are being hit.

**Comment by vitaly-t** [comment]
Method `oneOrNone` uses generic execution logic which works always, with exhaustive tests to prove that, and long usage history without anyone reporting any issue there.

Your description of the issue seems a bit odd. I would suggest debugging it further to see what really is going there underneath.

**Comment by paulxtiseo** [comment]
If I have a `console.log(connection.adapter.oneOrNone('SELECT table_name FROM information_schema.tables WHERE table_name=\'migration\';'));`, I do get a Promise object back: 

```
Promise {
  _bitField: 0,
  _fulfillmentHandler0: undefined,
  _rejectionHandler0: undefined,
  _promise0: undefined,
  _receiver0: undefined }
```

Does anything look suspicious to your better eye?

**Comment by vitaly-t** [comment]
no, that looks exactly like an unresolved Promise object returned by `bluebird`.

**Comment by vitaly-t** [comment]
Try to see track the execution path inside the method. Could there be something that suddenly interrupts the execution.

**Comment by vitaly-t** [comment]
@paulxtiseo have you made any progress with it? It would be nice to close the issue knowing what was causing it :wink:

**Comment by paulxtiseo** [comment]
The issue happens only in the tests under the Mocha-Chai harness. If I use the same codebase without Mocha overlayed over it, I don't get the strange behavior.

You are welcome to close the ticket. I will likely drill down on why, and can always post here for posterity once I find a better answer.

**Comment by vitaly-t** [comment]
Thank you for coming back on this! I will re-open it, if needed later.

My only guess so far - some call gets interrupted by Mocha, so it doesn't give that promise a chance to settle.
