### ISSUE TITLE
Array of object converted to array of string

### ISSUE THREAD

**Issue by sunilgupta123** [vitaly-t/pg-promise#237]
Have array as below, need to be saved in JSONB column:
[{"FoodType":"veg","pref":"High"}
,{"FoodType":"sea food","pref":"Medium"}
{"FoodType":"Chicken","pref":"Low"}]

**PG DB throws error : 
{ [error: column "foodpref" is of type jsonb but expression is of type text[]]
  name: 'error',
  length: 196,
  severity: 'ERROR',
  code: '42804',
  detail: undefined,
  hint: 'You will need to rewrite or cast the expression.',
  position: '123',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_target.c',
  line: '529',
  routine: 'transformAssignedExpr' }
POST /api/member 500 638.510 ms - 57

**Comment by vitaly-t** [comment]
This is an SQL-level error, not relevant to this library. Try StackOverflow :wink:

**Comment by sunilgupta123** [comment]
Thanks for reply Vitaly, shall hook on Stackoverflow.
i thought its driver issue cos array: function (arr) in formatting.js returns string and postgres cant digest it. If array is nested in object then it works smoothly e.g. "MyPref" : <Same Object as above>. 
Here MyPref gets through in column "FoodPref" without any issue.
