### ISSUE TITLE
ColumnSet reuse for INSERTS

### ISSUE THREAD

**Issue by skatcat31** [vitaly-t/pg-promise#239]
`pg-promise@helpers@insert` with `pg-promise@helpers@ColumnSet` based generation does one bad nono: Doesn't skip columns that don't exist in the data. So I'd like to formally request a feature that if a ColumnSet finds a missing field in an object that we have a way to skip this for inserts. This has some use in a few cases that are really common:

 - default values
 - uhhh... umm... I'm sure there are others?

Really the first one is pretty wide spread. This would prevent developers from having to default the values in node(which leads to some variance of `node@Date` vs `prostgreSQL@now` and other such defaults) AND would allow reuse of `ColumnSet` objects for `Inserts` and `Updates`

**Comment by vitaly-t** [comment]
I have published a lot about it in the [project's chat](https://gitter.im/vitaly-t/pg-promise), and just to reiterate that here...

The SQL syntax doesn't allow for skipping values for multi-row inserts, only for single-row inserts.

For single-row inserts, property `cnd` (conditional) column cannot be used, because there are no condition that can be appended to the insert query.

This leaves with only one scenario: use of `skip` callback for single-row inserts. And I'm still considering the real value of adding support for this one case.

**Comment by vitaly-t** [comment]
Only when I start thinking about this in the context of adding a single record, so we can simplify building an insert, then I can see some benefit in supporting it, but perhaps not that much...

**Comment by vitaly-t** [comment]
@skatcat31 you haven't come back on this ever since, so I'm closing it for now, due to inactivity.

**Comment by skatcat31** [comment]
Works for me. If it's not useful for multi inserts or it requires a lot of odd work around then it isn't really a useful piece of code. I'll just deal with using more than one columnset

**Comment by vitaly-t** [comment]
@skatcat31 you are talking about use of `skip` logic for single-row inserts, specifically. Even `cnd` rule cannot be applied there as being pointless.

This is why I questioned the need of supporting it.

**Comment by skatcat31** [comment]
Honestly it sounds like there isn't a need. Having multiple columnsets doesn't take up much memory, and it's not hard making multiple and an if statements so if it isn't useful in any other case then it isn't a useful feature.

**Comment by vitaly-t** [comment]
@skatcat31 

yes, that, plus the useful methods [extend] and [merge] is what makes it easy configuring/mutating `ColumnSet` objects ;)

[extend]:http://vitaly-t.github.io/pg-promise/helpers.ColumnSet.html#.extend
[merge]:http://vitaly-t.github.io/pg-promise/helpers.ColumnSet.html#.merge
