### ISSUE TITLE
Using Buffer without `new` will soon stop working.

### ISSUE THREAD

**Issue by paleite** [vitaly-t/pg-promise#242]
Hey, I'm getting a warning when using pg-promise.

I'm using `node@7.2.0` and `pg-promise@5.4.3`.

> var pgp = require('pg-promise')();

yields the following output:

> (node:60294) DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.

**Comment by MitMaro** [comment]
I believe this is a duplicate of #234

**Comment by vitaly-t** [comment]
@MitMaro thnaks, it is a duplicate indeed.

@paleite it will get attention by the time Node.js 7.x becomes an LTS ;)

Granyed, the driver's support is less than good these days, so I'm looking at alternatives.

**Comment by vitaly-t** [comment]
Version 7.2.1 of Node.js removed both the warning and the plans for making the change in 7.x :smile:

Problem solved! 😸

**Comment by paleite** [comment]
That's what I call effective problem solving! :)
