### ISSUE TITLE
postgres no data returned error

### ISSUE THREAD

**Issue by mathisonian** [vitaly-t/pg-promise#247]
Hi,

I'm experiencing some strange `queryResultErrorCode.noData` query errors, that seem to be exacerbated by using prepared statements. I'm getting the following error, I'm trying to track down exactly what's going on, so any help pointing me in the right direction would appreciated! 

```js
QueryResultError {
    code: queryResultErrorCode.noData
    message: "No data returned from the query."
    received: 0
    query: {"name":"ARR_DELAY-9","text":"\n      SELECT width_bucket(\"ARR_DELAY\", $1, $2, $3) as bucket, count(*)\n      FROM flights\n      WHERE $4 < \"ARR_DELAY\" and \"ARR_DELAY\" < $5 and \"DEP_DELAY\" < $6 and $7 < \"DISTANCE\" and \"DISTANCE\" < $8\n      GROUP BY bucket order by bucket asc;\n    ","values":[0,100,25,0,100,27.4,779.35,1227.85]}
}
```

this translates to the following query, which I confirmed does return results when I run it by hand:
```sql
SELECT 
	width_bucket("ARR_DELAY", 0, 100, 25) as bucket,
	count(*),
	min("ARR_DELAY"),
	max("ARR_DELAY")
FROM flights
WHERE 0 < "ARR_DELAY" AND "ARR_DELAY" < 100 and  "DEP_DELAY" < 14.8 and 779.35 < "DISTANCE" and "DISTANCE" < 1227.85
GROUP BY bucket order by bucket asc;
```

if I omit the `name` parameter things to work for the most part, but I'm still occasionally seeing the error. To add some context, I am more or less sending non-stop queries to postgres, but rate-limiting them so there are never more than `MAX_CONNECTIONS` queries running at a time. Is this possibly just a strange failure mode of postgres, or could it be something in this library?

**Comment by vitaly-t** [comment]
It is only as strange as your query returning no data from time to time. Otherwise the library wouldn't report this to you.

**Comment by vitaly-t** [comment]
If you simply switch to method `any` and log whenever 0 records are returned, you will get the same results, guaranteed. So again, this is an issue with your database logic, not with the library, that's why I'm closing it.

**Comment by mathisonian** [comment]
Thanks @vitaly-t, that is helpful. I'll try with `any` and see whats going on at the database layer.

**Comment by vitaly-t** [comment]
@mathisonian were you able to get to the bottom of it? :wink:
