### ISSUE TITLE
QueryFile as separate package

### ISSUE THREAD

**Issue by Caspinol** [vitaly-t/pg-promise#248]
Hello Vitaly,

Any chance you could extract the Query file into its own package.
It would simplify the usage with different DB drivers.

Regards.

**Comment by vitaly-t** [comment]
It is not realistic, considering the features the class has that are specific to this library:

- use of `pg-minify` for compressing SQL (designed for PostgreSQL only)
- reliance on the library's query formatting engine to format the SQL after loading (for two-step query formatting)
- custom protocol + promise logic for detecting issues: `if (qf.error) {reject(qf.error)} else {resolve(qf.query)}` + `qf.prepare()`

**Comment by Caspinol** [comment]
Understood. I suspected this could be the case after looking at the code but was hoping that i'm missing something :)

Thanks for great library!
