### ISSUE TITLE
Make warnings display always?

### ISSUE THREAD

**Issue by vitaly-t** [vitaly-t/pg-promise#250]
Should we display warnings always, and not just in DEV environments?

It seems that the most frequent misuse of the library is often accompanied by the development environment not set up correctly (`NODE_ENV = development`), so relying on it becomes double evil.

Please vote! :+1:

**Comment by leebenson** [comment]
I'd vote always. I usually have a lot of environments that are 'devvy', but not strictly `development` - e.g. staging, testing, etc. I'd like for warnings to display in all of those.

For production, I generally monkey patch logging to push messages via Winston to some kind of third-party tool, so warnings/errors are relevant too.

I'm not a fan of hiding useful messages just for the sake of a 'clean' console. I'd rather know about them and do something about them, than risk them slipping through the cracks!

**Comment by vitaly-t** [comment]
Implemented in version [5.5.0](https://github.com/vitaly-t/pg-promise/releases/tag/v.5.5.0).
