### ISSUE TITLE
Spreading values like `$<this~>`?

### ISSUE THREAD

**Issue by leebenson** [vitaly-t/pg-promise#251]
_Disclaimer: I'm new to this lib, so please forgive me if this is a stupid question, or if I've missed something._

I see there's `$<this~>` to spread column names. Is there an equivalent to spread values?

Rather than:

```js
db.query('INSERT INTO tables($<this~>) VALUES($<name>, $<email> $<password>....)');
```

I'm thinking something like:

```js
db.query('INSERT INTO tables($<this~>) VALUES($<~this>)'); // *~ = keys, ~* = values
```

Have I missed it?

**Comment by vitaly-t** [comment]
Spreading values isn't very useful, because way too often you would need to provide certain modifiers for your values.

For fully automatic query generation see the [helpers](http://vitaly-t.github.io/pg-promise/helpers.html) namespace :wink:

**Comment by leebenson** [comment]
Thanks @vitaly-t. Hopefully that concludes my newbie questions for the day 😄
