### ISSUE TITLE
Accomodating IN keyword 

### ISSUE THREAD

**Issue by popara** [vitaly-t/pg-promise#252]
Hello, 

First of, thanks so much for this awesome library! (I will put some money in the jar as soon we hit production and start rolling :) 

I am having issues constructing straight forward query having IN keyword. 

For example say we have `SELECT * FROM foo WHERE bar IN ('zoo', 'moo', 'goo');`

Using pg-promise, that would translate into 
`SELECT * FROM foo WHERE bar IN ($1:raw);` 
where I need to concat array of ['zoo', 'moo', 'goo'] into ` 'zoo', 'moo', 'goo' ` manually and plug it as raw value. 

I have been reading all that you have written, but I couldn't find any hint that you can archive something like that straightforwardly. 

Am I missing something, or this in deed is small feature that is missing from lib? 

All best!

**Comment by vitaly-t** [comment]
Did you see this - [WHERE col IN (values)](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#where-col-in-values)?

**Comment by vitaly-t** [comment]
Closing, since there was no reply.

**Comment by popara** [comment]
Oh, sorry, yes this makes sense. 
I did not saw this piece of code! 
 Maybe csv name is a bit missleading but except that, all is good!

thank you very much! 

:)

**Comment by vitaly-t** [comment]
@popara you are welcome! 😸
