### ISSUE TITLE
Errors when bundling with Webpack

### ISSUE THREAD

**Issue by hassankhan** [vitaly-t/pg-promise#255]
Hi, thanks for your library!

I can't seem to include it into my Webpack-based project at all, is there any way of working around this?

Thanks

**Comment by vitaly-t** [comment]
I'm not familar with the WebPack, never used it.

Isn't WebPack is primarily a tool for the frond-end?

**Comment by hassankhan** [comment]
Sorry, here's the actual error I'm getting now:

`TypeError: Path must be a string. Received undefined`.

We're using Webpack as a bundler only for our Node projects, as bundling/minifying improves performance on Lambda.

**Comment by vitaly-t** [comment]
Thank you for the clarification. Still, I know nothing about Webpack to advise you.

**Comment by vitaly-t** [comment]
Closing it, because I don't think it will receive any attention here. Maybe it is relevant to the driver, or maybe there is an issue with how it used in the Webpack.

I personally won't be investigating it, since I've never used Webpack, and I'm not sure about its value for this library.

**Comment by hassankhan** [comment]
Fair enough, I was hoping someone else might have tried the same and gotten somewhere.
