### ISSUE TITLE
Catch Notices raised in trigger function?

### ISSUE THREAD

**Issue by MagnumDopus** [vitaly-t/pg-promise#259]
Forgive me, still somewhat new to all of this.  I have a plsql function that is acting as a gate keeper for insertions on a user database.  It raises notices if the user name or email is already in use and returns null for the insertion so it won't take place (the user table also has unique constraints on it).

When I test this in at the command line level it works fine and I see the notice appropriately.  But when I am using pg-promise through node it just returns an empty set (which at least indicates the insertion didn't take place which is good) but it does not relay any of the information in the returned data so I cannot properly inform the user why the insertion failed.

Is there some magic way to get this reported to the user?  I have verified that my logging level to the client is appropriate for notices to appear.

**Comment by vitaly-t** [comment]
Can you include the code of the call you are making?

**Comment by MagnumDopus** [comment]
`CREATE OR REPLACE FUNCTION new_user()
RETURNS TRIGGER AS $$

DECLARE
    key TEXT;
    emailQry TEXT;
    userQry TEXT;
    found TEXT;
BEGIN

    emailQry := 'SELECT 1 FROM ' || quote_ident(TG_TABLE_NAME) || ' WHERE email = ' || quote_literal(NEW.email);
    userQry := 'SELECT 1 FROM ' || quote_ident(TG_TABLE_NAME) || ' WHERE username = ' || quote_literal(NEW.username);

    EXECUTE emailQry INTO found;
    IF found IS NOT NULL
    THEN
        RAISE NOTICE 'Email % already in use.', NEW.email
            USING HINT = 'Do you already have an account?';
        RETURN NULL;
    END IF;

    EXECUTE userQry INTO found;
    IF found IS NOT NULL
    THEN
        RAISE NOTICE 'Username % taken.', NEW.username
            USING HINT = 'Try a different name';
        RETURN NULL;
    END IF;

    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER new_user BEFORE INSERT ON users FOR EACH ROW EXECUTE PROCEDURE new_user();
`

And then the test case where I am just trying to catch the notice in some way is very simple:

`
...[setup db using appropriate settings]
let username = process.argv[1];
let email= process.argv[2];

db.any(`
    INSERT INTO
        users (
            username,
            email,
            salt,
            password
        )
    VALUES (
        '${username}',
        '${email}',
        'salt',
        'pass'
    )
    ON CONFLICT
        DO NOTHING
    RETURNING
        confirmation_link AS link, email
`)
`

**Comment by vitaly-t** [comment]
I'm not sure what that trigger is expected to return back to you.

I can only recommend - try use function [result](http://vitaly-t.github.io/pg-promise/Database.html#.result) instead, to see if that object gives you anything extra on the second call.

If you can't find out the difference, it may be a good question to ask on StackOverflow, there may be something special regarding return of triggers.

Also, you should not use ES6 strings to format queries, they can end up broken. Always use the library's own query formatting engine.

**Comment by MagnumDopus** [comment]
Well with node-postgres which this is built upon you can listen for notices: https://github.com/brianc/node-postgres/wiki/Client#notice--object-notice

I'm assuming this behavior isn't extended into pg-promise?  Also about the es6 strings, I am only doing that for testing, not a production solutions!

**Comment by vitaly-t** [comment]
That is quite interesting. You are the first one to ever ask this question :smile:

I'm thinking now whether such a notification should be a `reslove` or `reject`...

**Comment by MagnumDopus** [comment]
Typically in postgres the raise levels are: DEBUG, LOG, INFO, NOTICE, WARNING, and EXCEPTION

Only exception raises an error and typically rollsback a transaction.  In that regard I would imagine everyhting except exception would resolve and exception would reject.  

As per the Postgres documentation: https://www.postgresql.org/docs/current/static/plpgsql-errors-and-messages.html

**Comment by vitaly-t** [comment]
I'm not sure there can be an unequivocal approach to treating such notices as success or failure.

It is possible to handle those globally, if you need it just for logging...

**Comment by MagnumDopus** [comment]
Well, and perhaps I am approaching this the wrong way, but what would be the best approach to inform a user that the user they are trying to add to teh table does not exist?  Should I abandon a plpgsql command and instead just perform two statements in a transaction, one query the database for emails/usernames, and one then performing the insert?  I suppose that might be the more appropriate solution, I felt like using notices might have been the most appropriate response but maybe not...

**Comment by vitaly-t** [comment]
>what would be the best approach to inform a user that the user they are trying to add to teh table does not exist

Typically, you execute something like this:

```sql
db.oneOrNone('SELECT * FROM Users WHERE name=$1', [userName])
```
see [oneOrNone](http://vitaly-t.github.io/pg-promise/Database.html#.oneOrNone).

**Comment by vitaly-t** [comment]
At the moment you can intercept those notifications globally, like this:

```js
var options = {
    connect: function (client, dc, isFresh) {
        if (isFresh) {
            client.on('notice', function (msg) {
                console.log("notice: %j", msg);
            });
        }
    }
};

var pgp = require('pg-promise')(options);
```

**Comment by MagnumDopus** [comment]
I would assume since this has barely been requested that I am approaching this improperly from a sql perspective.  I will just use a transaction block with a query followed by the insert.  Since the table has appropriate constraints the insert will fail if the user/email is present anyway.  I think I was trying to over-engineer this problem.

**Comment by vitaly-t** [comment]
> I think I was trying to over-engineer this problem

Looks that way, since no-one ever pointed at this before, and the user base for this library is huge today.

**Comment by MagnumDopus** [comment]
Indeed, its a super rad library.  I will just go about and do it the non-ridiculous way.  I'll just get rid of the trigger functions and do it the proper way.  Thanks for the swift responses!

**Comment by vitaly-t** [comment]
I have done some estimates for adding support for custom exceptions.

The main trouble is the concept: The idea of non-critical errors (like warnings) is alien to promises, which means it requires a separate/dedicated method perhaps for executing queries, while also providing information about those notices.

**Comment by vitaly-t** [comment]
Initial implementation to support non-critical messages has been commited.

**Comment by vitaly-t** [comment]
It looks like there is no solution to the issues highlighted earlier, except to add the missing functionality into the driver :(

I've logged the issue here: https://github.com/brianc/node-postgres/issues/1226

I fear without that feature properly supported there is no point having it half-way, i.e. not supporting multiple queries with notifications.

I may remove the previous commits because of that.

**Comment by vitaly-t** [comment]
Closing again, once I've realized notifications cannot be linked to queries, makes them so useless.

**Comment by prostgles** [comment]
Used this to prevent duplicate listeners being attached:

```
if (isFresh && !client.listeners('notice').length) {
  client.on('notice', function (msg) {
  ...
```

**Comment by dspinellis** [comment]
> 
> At the moment you can intercept those notifications globally, like this:
> 
> ```js
> var options = {
>     connect: function (client, dc, isFresh) {
>         if (isFresh) {
>             client.on('notice', function (msg) {
>                 console.log("notice: %j", msg);
>             });
>         }
>     }
> };
> 
> var pgp = require('pg-promise')(options);
> ```
> 
> See event [connect](http://vitaly-t.github.io/pg-promise/global.html#event:connect).
> 
> But it won't affect the result of your query calls.

The third [connect](http://vitaly-t.github.io/pg-promise/global.html#event:connect) parameter is (now?) `useCount`, hence the code should be as follows.
```js
var options = {
    connect: function (client, dc, useCount) {
        if (useCount === 0) {
            client.on('notice', function (msg) {
                console.log("notice: %j", msg);
            });
        }
    }
};
```
