### ISSUE TITLE
return data using Postgre Promise - pg-promise

### ISSUE THREAD

**Issue by gutasaputra** [vitaly-t/pg-promise#260]
recently im using pg-promise to connect my postgre db to my nodejs application.
there is a case when i want to retrieve single data from pg-promise.

here is my code :
 ```
    function getLastID(req, res, next) {
        db.one("select MAX(id) + 1 as maxID from clinic")
        .then(maxID => {
          console.log("the value is :  " + maxID)
        })

        .catch(function (error) {
            return next(error);
        });
    }
   getLastID();
```

when i run it on my console. i got this result : 
the value is : [object Object]

i try to use util.inspect, so i change my code into this :
```
 function getLastID(req, res, next) {
        db.one("select MAX(id) + 1 as maxID from clinic")
        .then(maxID => {
          let id_dummys = util.inspect(maxID, false, null);
          console.log("======")
          console.log("the value is :  " + id_dummys)
        })

        .catch(function (error) {
            return next(error);
        });
    }

   getLastID();
```

when i run it on my console. i got this result : 
the value is : anonymous { maxid: 73 }

what i really want is to get the value, in this case, the number of 73.

how can i do that?

thank you.

**Comment by vitaly-t** [comment]
So your question translates into how to get an object property in JavaScript...

I don't want to sound arrogant, but this is not the place to ask such questions.
