### ISSUE TITLE
add db.close method?

### ISSUE THREAD

**Issue by AlJohri** [vitaly-t/pg-promise#261]
hi, I was wondering if you might consider adding a db.close method similar to the mongodb's db.close method?

currently in mongo I can close the database like so:

```javascript
(async () => {
  const db = await MongoClient.connect(process.env.MONGO_URL);
  db.close();
})().catch(e => console.error(e.message, e.stack))
```

I think the implementation of `close` would look something like

```javascript
close = () => {
  return this.$config.pgp.end()
}
```

assuming that there is only one database being connected to.

Because of `$npm.utils.lock` I can't seem to add the function myself. Any ideas on how to subclass properly? I'm quite new to node.

My goal is to have a relatively consistent interface between mongo and postgres as I'm creating an application that needs both. Currently, I created a new class to compose `pgp` but this requires redefining every single method. Inheritance would be easier than composition here.

pg-wrapper.js
```javascript
import pgPromise from 'pg-promise';

class pgpWrapper {
	constructor() {
		this.pgp = pgPromise();
	}
	connect(uri) {
		this.client = this.pgp(uri);
		return this;
	}
	close() {
		this.pgp.end();
	}
}

export const PostgresClient = new pgpWrapper()
```

index.js
```javascript
import { MongoClient } from 'mongodb';
import { PostgresClient } from './pg-wrapper';

(async () => {
  const mongoDb = await MongoClient.connect(process.env.MONGO_URL);
  const postgresDb = await PostgresClient.connect(process.env.POSTGRES_URL);

  // db.Articles.find({date: { $gt: }});

  mongoDb.close();
  postgresDb.close();
  
})().catch(e => console.error(e.message, e.stack))
```

thanks for the help!

**Comment by vitaly-t** [comment]
This library is built on a connection pool, you should not allocate connections manually, they are all managed automatically.

**Comment by AlJohri** [comment]
Cool, thanks I'll give this a shot. Mongo also similarly maintains a connection pool and tests the connection on the first .connect.

1) I was wondering if there is a way to close the single connection pool (all connections in a single pool) instead of doing pgp.end?

2) Is there an easy way you know of to extend your Database class? This question is more general as I'm failing to understand how to extend classes in general in Node.

Thanks for your help!

**Comment by vitaly-t** [comment]
> I was wondering if there is a way to close the single connection pool

Not at present.

> Is there an easy way you know of to extend your Database class.

See event [extend](http://vitaly-t.github.io/pg-promise/global.html#event:extend) and [pg-promise-demo](https://github.com/vitaly-t/pg-promise-demo).

**Comment by AlJohri** [comment]
Awesome. Would you accept a PR to close all the connections in a single pool?

**Comment by vitaly-t** [comment]
I'm not sure that's even possible at the moment.

**Comment by AlJohri** [comment]
@vitaly-t It seems there is no public API that makes this possible at the moment. I made a request upstream: https://github.com/brianc/node-postgres/issues/1193

**Comment by AlJohri** [comment]
Ok, in light of the slow changing dependency, if you would accept a PR that uses the `node-postgres` internal API, I'd be happy to make one. The implementation would look pretty much like this:

```javascript
const poolName = JSON.stringify(config);
const pool = config.pgp.pg._pools[poolName];
delete config.pgp.pg._pools[poolName];
pool.end(function() {
  if (Object.keys(config.pgp.pg._pools).length == 0) {
    config.pgp.pg.emit('end');
  }
});
```

The most likely location would be in `connect.js` as `function poolDisconnect(config)` and exposed in `database.js` via a `close` function.

**Comment by vitaly-t** [comment]
It would require a comprehensive testing.

**Comment by AlJohri** [comment]
Yeah, that makes sense.

Since my use case involves only one postgres connection pool per application I think this abstraction works for me:

index.js
```javascript
import { MongoClient } from 'mongodb';
import { PostgresClient } from './pg-wrapper';

(async () => {
  const mongoDb = await MongoClient.connect(process.env.MONGO_URL);
  const postgresDb = await PostgresClient.connect(process.env.POSTGRES_URL);

  const docs = await mongoDb.collection('Articles').find().toArray(); // {date: { $gt: }}
  console.log(docs);

  mongoDb.close();
  postgresDb.close();
})().catch(e => console.error(e.message, e.stack))
```

pg-wrapper.js
```javascript
import pgPromise from 'pg-promise';

export const PostgresClient = {
  async connect(uri) {
    const pgp = pgPromise({
      extend: function (obj, dc) {
          obj.close = () => { obj.$config.pgp.end() }
        }
    });
    const db = pgp(uri);
    const obj = await db.connect();
    obj.done();
    return db;
  }
}
```

Adapted from the stackoverflow for checking the connection and pg-promise-demo for using extend.

I appreciate your help and responsiveness!

Please let me know if you find anything wrong in the example above.

**Comment by vitaly-t** [comment]
If you use `db.connect` directly, such solution will not scale. Any application should rely on the connection pool.

**Comment by AlJohri** [comment]
@vitaly-t Maybe you can take another look? I do believe I'm using the connection pool properly. My wrapper `PostgresClient.connect` function does a `return db;` where `db` is the connection pool.

**Comment by vitaly-t** [comment]
Then it should be fine ;)
