### ISSUE TITLE
db connection string does not work if there is no password

### ISSUE THREAD

**Issue by goncalopereira** [vitaly-t/pg-promise#262]
Should work:
% psql -h localhost -p5432 -U postgres
select * from table;

Should not work (your user cannot access the tables):
% psql -h localhost -p5432 
select * from table;

Doesn't work:
const db = pgp('postgres://postgres@localhost:5432');
select * from table;

But DB connection object works.

**Comment by vitaly-t** [comment]
* What error are you getting back?
* Does configuration object work for you?

**Comment by goncalopereira** [comment]
Hello,

I'm getting the 'relation does not exist' error from postgres but only because it's not setting up the 'postgres' user and failing back to my own.

Configuration object works without a password field.

**Comment by goncalopereira** [comment]
Might be from https://github.com/iceddev/pg-connection-string/blob/master/index.js

When there is no password and cannot split auth.

**Comment by vitaly-t** [comment]
There must be something else you are doing, as it worls for me perfectly, and works for lots of other developers out there.

**Comment by goncalopereira** [comment]
Fair enough. Feel free to close this issue then, was just letting you know in case it was an actual issue.

Regards

**Comment by vitaly-t** [comment]
Try to debug it. After all a connection string is converted into a connection object, so you can see what kind of connection object you are getting and then compare it to your manually defined connection object.

**Comment by goncalopereira** [comment]
Okay let me get around to it and I'll give some feedback tomorrow.

**Comment by vitaly-t** [comment]
@goncalopereira any update there?

**Comment by goncalopereira** [comment]
No updates I'm afraid - I tried to replicate the issue by getting 'current_user' with different connection strings but it was fine on my machine. I only saw this at a colleague's machine so cannot reproduce it at the moment.

I'm sure you can close this for now. Thank you.

**Comment by vitaly-t** [comment]
Cheers!
