### ISSUE TITLE
Named Parameters ${this} values

### ISSUE THREAD

**Issue by allbto** [vitaly-t/pg-promise#263]
For the `Named Parameters` I understand that `${this}` can be used as such:

```javascript
var doc = {
    id: 123,
    body: "some text"
};

db.none("INSERT INTO documents(${this~}) VALUES(${id}, ${body})", doc)
// => INSERT INTO documents("id", "body") VALUES(123, 'some text')
```

But I can't seem to find anything in your docs to do the following:

```javascript
db.none("INSERT INTO documents(${this~}) VALUES(${this[missing something here]})", doc)
// => INSERT INTO documents("id", "body") VALUES(123, 'some text')
```

So instead of writing all the values for an object (`${id}, ${body}`) it would be something like `${this:values}`.
Did I miss it in the docs or it is intentional?
I think it would be a great addition. Especially because it can be done with `pgp.helpers.insert` but the code looks way different then.

Thanks in advance! (love your work)

**Comment by vitaly-t** [comment]
Use of helpers is the best way to generate queries when you need to support multi-row operations.

Other than that, the library doesn't have anything like `this:values}`, and there is little point in having it either, you should use helpers instead :wink:
