### ISSUE TITLE
Connection pool not reused with different key order

### ISSUE THREAD

**Issue by MitMaro** [vitaly-t/pg-promise#264]
## Description

This is a follow up to #175.

Providing an equivalent configuration to `pg-promise` where the order of the configuration keys are different does not result in the reuse of the connection pool.

## Expected

I would expect that the following would result in reuse in reuse of the same connection pool. I would also expect pg-promise to show a "Creating a duplicate database object for the same connection" warning. Note that the `username` and `password`properties are swapped in the second configuration.

```
const db1 = pgp({
	user: 'user',
	password: 'password',
	database: 'database',
	poolSize: 2
});
const db2 = pgp({
	password: 'password',
	user: 'user',
	database: 'database',
	poolSize: 2
});
```

```
$ lsof -i tcp:5432

COMMAND     PID    USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
com.docke  5058 timoram   22u  IPv4     0xa      0t0  TCP *:postgresql (LISTEN)
com.docke  5058 timoram   23u  IPv6     0xa      0t0  TCP localhost:postgresql (LISTEN)
com.docke  5058 timoram   24u  IPv4     0xa      0t0  TCP localhost:postgresql->localhost:56394 (ESTABLISHED)
com.docke  5058 timoram   28u  IPv4     0xa      0t0  TCP localhost:postgresql->localhost:56395 (ESTABLISHED)
node      49279 timoram   15u  IPv4     0xa      0t0  TCP localhost:56394->localhost:postgresql (ESTABLISHED)
node      49279 timoram   16u  IPv4     0xa      0t0  TCP localhost:56395->localhost:postgresql (ESTABLISHED)
```

## Actual

When providing the above configurations to a test script I instead see a total of four connections and no warning from pg-promise.

```
COMMAND     PID    USER   FD   TYPE  DEVICE SIZE/OFF NODE NAME
com.docke  5058 timoram   22u  IPv4     0xa      0t0  TCP *:postgresql (LISTEN)
com.docke  5058 timoram   23u  IPv6     0xa      0t0  TCP localhost:postgresql (LISTEN)
com.docke  5058 timoram   26u  IPv4     0xa      0t0  TCP localhost:postgresql->localhost:56623 (ESTABLISHED)
com.docke  5058 timoram   28u  IPv4     0xa      0t0  TCP localhost:postgresql->localhost:56624 (ESTABLISHED)
com.docke  5058 timoram   30u  IPv4     0xa      0t0  TCP localhost:postgresql->localhost:56625 (ESTABLISHED)
com.docke  5058 timoram   32u  IPv4     0xa      0t0  TCP localhost:postgresql->localhost:56626 (ESTABLISHED)
node      49967 timoram   15u  IPv4     0xa      0t0  TCP localhost:56623->localhost:postgresql (ESTABLISHED)
node      49967 timoram   16u  IPv4     0xa      0t0  TCP localhost:56624->localhost:postgresql (ESTABLISHED)
node      49967 timoram   17u  IPv4     0xa      0t0  TCP localhost:56625->localhost:postgresql (ESTABLISHED)
node      49967 timoram   18u  IPv4     0xa      0t0  TCP localhost:56626->localhost:postgresql (ESTABLISHED)
```

## Problem

The issue is caused by how postgres-node does it's [detection of a duplicate connections](https://github.com/brianc/node-postgres/blob/v5.1.0/lib/pool.js#L15). It works by using `JSON.stringify` on the connection configuration. pg-promise also performs the [same check](https://github.com/vitaly-t/pg-promise/blob/master/lib/database.js#L1194) for duplicate connections. I would report this issue to postgres-node, however given that pg-promise is stuck using 5.1 I don't know how productive that would be.

## Solution

The [solution](https://github.com/vitaly-t/pg-promise/issues/175#issuecomment-271969662) that I used was to provide a key order to `JSON.stringify`, however this would require a change to node-postgres and I am not sure how viable that would be for the old version.

## Reduced Test Case

```javascript
'use strict';

const pgPromise = require('pg-promise');

const pgp = pgPromise();

const db1 = pgp({
	user: 'blnapi',
	password: 'blnapi',
	database: 'blnapi',
	poolSize: 2
});
const db2 = pgp({
	password: 'blnapi',
	user: 'blnapi',
	database: 'blnapi',
	poolSize: 2
});

for (let i = 0; i < 10; i++) {
	db1.query('select \'foo\'');
}

for (let i = 0; i < 10; i++) {
	db2.query('select \'foo\'');
}

setInterval(() => {}, 100)
```

**Comment by vitaly-t** [comment]
> The solution that I used was to provide a key order to JSON.stringify, however this would require a change to node-postgres

I don't see why this would require a change in `node-postgres`. It can be easily fixed by inside `pg-promise` itself.

**Comment by vitaly-t** [comment]
Fixed in [v.5.5.1](https://github.com/vitaly-t/pg-promise/releases/tag/v.5.5.1).

**Comment by vitaly-t** [comment]
@MitMaro can you confirm the issue as resolved, please?

**Comment by MitMaro** [comment]
The warning message issue is resolved but I am still seeing a set of duplicate connections. I was hoping to do some further testing on this last week, but was unable to find time.
