### ISSUE TITLE
Typescript query result type can be improved

### ISSUE THREAD

**Issue by ubershmekel** [vitaly-t/pg-promise#266]
Looking at this: https://github.com/vitaly-t/pg-promise/blob/2152496c6749ee0f1fa8453e5bb20e67017e6bc0/typescript/pg-promise.d.ts#L545

```
query(query: TQuery, values?: any, qrm?: pgPromise.queryResult): XPromise<any>;
```

The `any` in the result promise isn't very useful for reading results from queries. I'm actually still not sure how I'm supposed to get the value out of `query('select 2 + 2;');`.

**Comment by ubershmekel** [comment]
Now I notice that it's just the `pg` query result. So the only possible improvement would be to change it from `any` to `any[]`.

**Comment by vitaly-t** [comment]
You think that changing `any` into `any[]` is an improvement? It won't affect how you write your code at all.

**Comment by ubershmekel** [comment]
I understand. Thank you for clearing that up. I did read the beginning of "Learn by Example" before posting. But I did not immediately see the value or intent behind using a method called `any` to query the db. Also on the github repo readme the first thing to show up under `Usage` is the function `query` so I assumed that's what I should be using.

**Comment by vitaly-t** [comment]
The main Readme file is the one that was written initially, and even though I keep updating it, it is still not the best reference. The API and Wiki though make up for it :wink:

Method `any` is result-specific, it means anything can be returned, while method `query` expects the data according to its third parameter, which specified how to treat the result.
