### ISSUE TITLE
Rather than showing warning when duplicate connection, just return existing connection

### ISSUE THREAD

**Issue by FrankShaw** [vitaly-t/pg-promise#268]
Currently, if you try to create a new Database connection with a connection that has already been used, the library logs a warning to the console and then creates the duplicate connection. Would it be possible/better to just cache the already created connections and then, rather than showing the warning, just return the already cached connection to the caller?

**Comment by vitaly-t** [comment]
The duplicate connection is not so much an issue itself, as being a bad development pattern, so no, it shouldn't try to outsmart you, it should tell you that what you are doing seems wrong.

**Comment by vitaly-t** [comment]
I hope this answers it ;)
