### ISSUE TITLE
How to escape ORDER BY, LIMIT, and OFFSET?

### ISSUE THREAD

**Issue by brandonros** [vitaly-t/pg-promise#269]
```
db.many('SELECT foo FROM bar WHERE accountId = ${accountId} ORDER BY ${sortKey} ${sortDir} LIMIT ${limit} OFFSET ${offset}', {
	'accountId': decodedToken.accountId,
	'sortKey': sortKey,
	'sortDir': sortDir,
	'limit': limit,
	'offset': offset
});
```

yields

```
SELECT foo FROM bar WHERE accountId = 12 ORDER BY 'name' 'ASC' LIMIT '10' OFFSET '0'
```

which is invalid due to `'ASC'` not being `ASC`, etc.

How can I get the benefits of not forming a string manually and risking injection but still get valid queries?

This should really be documented as I feel it is pretty common? Sorry if I missed it.

**Comment by brandonros** [comment]
I found :raw, thanks!

**Comment by vitaly-t** [comment]
Those should be: `${sortKey~} ${sortDir^}`, which is the same as `${sortKey:name} ${sortDir:raw}`, i.e. the first one is an SQL name, and the second one is just an open-text variable.

See also:

* [SQL Names](https://github.com/vitaly-t/pg-promise#sql-names).
* [Raw Text](https://github.com/vitaly-t/pg-promise#raw-text)

**Comment by bdharrington7** [comment]
@vitaly-t From the docs, there is the warning not to use user-supplied variables in the `:raw` or the `:value` filters. What's the preferred safe way of getting user-supplied values for limits and offsets?

**Comment by vitaly-t** [comment]
@bdharrington7 For `LIMIT` and `OFFSET` you can just pass in integers, and then use regular variables.

**Comment by bdharrington7** [comment]
I know, but what if you're taking limit and offset as query params? 

i.e. for a url `GET /resource/items?limit=10`, within the router, you would have to do

```js
const limit = req.query.limit; // "10"
await db.query(`SELECT * FROM items LIMIT $(limit:raw)`, { limit });
// because `$(limit)`  without the filter would render as `LIMIT "10"`
```

However there's danger in doing that if someone passes `GET /resource/items?limit=10;SELECT * from users;`

The only only way to guard against that that comes to mind is something like

```js
await db.query(`SELECT * FROM items LIMIT $(limit:raw)`, { parseInt(limit) });
// or, call parseInt beforehand and handle NaN, etc. 
```

Is there a better, or pg-promise way of handling this?

**Comment by vitaly-t** [comment]
@bdharrington7 This is what your code should look like:

```js
const limit = parseInt(req.query.limit);
await db.query(`SELECT * FROM items LIMIT $(limit)`, { limit });
```
