### ISSUE TITLE
Question about the return data

### ISSUE THREAD

**Issue by jgamio** [vitaly-t/pg-promise#270]
I using something like these

`            db.any({
                name: "list_users",
                text: 'select  *, id as UserId from user ',      

            })
            .then(function (data) {

            })`

But I always got on the data userid (low case) and each user group like anonymous

Do I need change the my return data  ? or I have an option to

1 - got the UserId like return name
2- change anonymous to for example user 
 

thank you

**Comment by vitaly-t** [comment]
See the links below:

* http://stackoverflow.com/questions/20878932/are-postgresql-column-names-case-sensitive
* https://github.com/brianc/node-postgres/issues/1062

**Comment by jgamio** [comment]
vitaly-t  thanks for your response

1 That work when I use a field on the database but when i try to create a alias the return is a low case name. 

Already make the change to 

'select *, id as "UserId" from user '

but the return value is userid 

2 Thanks you I didn't know that.

**Comment by vitaly-t** [comment]
See  the following links:

* Event [receive](http://vitaly-t.github.io/pg-promise/global.html#event:receive)
* Article: https://coderwall.com/p/irklcq/pg-promise-and-case-sensitivity-in-column-names
