### ISSUE TITLE
Difference in join results between 

### ISSUE THREAD

**Issue by jorisdegeringel** [vitaly-t/pg-promise#273]
Forgive me if this is not a bug, but can't imagine it's not at the moment ;).

Performing:

`db.any("select * from gameuser left join gameresult on gameuser.gameid = 10 and gameresult.gameid = gameuser.gameid and gameresult.userid = gameuser.userid").then(function (data) {
      console.log(data); 
....`

results in:
`[ anonymous {
    gameid: 10,
    userid: 7,
    title: 'VS invName',
    timestamp: 2017-01-27T11:22:04.631Z,
    usergamestatus: 1,
    resultid: 4,
    round: 1,
    score: 11,
    scoreunit: 'seconds' },
  anonymous {
    gameid: null,
    userid: null,
    title: 'VS orgName',
    timestamp: null,
    usergamestatus: 0,
    resultid: null,
    round: null,
    score: null,
    scoreunit: null } ]`

Performing the exact same query on pg console or pgadmin query window give this result:

![image](https://cloud.githubusercontent.com/assets/2649136/22371025/eb8abbf8-e494-11e6-8253-90e3bdfaa4a9.png)

**Comment by jorisdegeringel** [comment]
ahem, minute I posted it realised it was duplicate column names, pretty lame ;). as attunement i will donate aomething to this great lib👍

**Comment by vitaly-t** [comment]
@jorisdegeringel Thank you for your donation! 👍
