### ISSUE TITLE
Add connection Error handling examples.

### ISSUE THREAD

**Issue by haysclark** [vitaly-t/pg-promise#274]
I would love some help on Error handling either in the 'best practices' or 'learn by example' section.  I was confused for a bit until I saw that the connection was lazy, which make me wonder what is the best way to deal with both 'retry' and 'DB fallback' scenarios.

Thanks for putting together this library!

- Cheers

**Comment by vitaly-t** [comment]
What do you intend to re-try - query execution? Then just do it as you would with any promise-based interface, there is nothing extra to consider here.

Otherwise, please formulate more specific questions, as what you published here is just too wide.

**Comment by vitaly-t** [comment]
@haysclark feel free to re-open, if you have a clarification.
