### ISSUE TITLE
SET balance = balance + delta with helpers.update

### ISSUE THREAD

**Issue by phiresky** [vitaly-t/pg-promise#275]
Hi!

I'm trying to create a query that looks as follows:

```sql
UPDATE users set balance = balance + v.delta FROM (values (1, 1), (2, 2)) as v("id", "delta")
WHERE v.id = users.id
```

But I can't figure out how to get this to work without manually reading the balance from the table first. ColumnSet has some settings but from what I can tell nothing that would enable this. Should this be possible?

**Comment by vitaly-t** [comment]
Yes and No. You can use make a limited use of `ColumnSet`, as your case is too unique, by using method `pgp.helpers.values`, as your case is too unique:

```js
var cs = new pgp.helpers.ColumnSet(['id', 'delta']);
var data = [{id: 1, delta: 2}, {id: 2, delta: 2}];
var values = pgp.helpers.values(data, cs);
var update = pgp.as.format('UPDATE users SET balance = balance + v.delta FROM(VALUES$1^) AS v(id, delta) WHERE v.id = users.id', values);
//=>UPDATE users SET balance = balance + v.delta FROM(VALUES(1,2),(2,2)) AS v(id, delta) WHERE v.id = users.id
```

**Comment by vitaly-t** [comment]
@phiresky this was a question worthy of StackOverflow :wink:

**Comment by vitaly-t** [comment]
Re-opening it for now, because this question gave me an idea of an improvement, to be able to get the list of prepared/escaped column names for unique cases such as this one.

To that end, I have done an initial commit, and will re-release the library shortly.

The idea is to use `cs.names` to get `"id","delta"`, with reference to our example, so we can use it as part of more intelligent query formatting.

**Comment by phiresky** [comment]
Thank you!

**Comment by vitaly-t** [comment]
[Release v5.5.5](https://github.com/vitaly-t/pg-promise/releases/tag/v.5.5.5) adds new properties [names] and [variables] to class [ColumnSet].

@phiresky now the same example can be updated to a little more civilized version:

```js
var cs = new pgp.helpers.ColumnSet(['id', 'delta']);
var data = [{id: 1, delta: 1}, {id: 2, delta: 2}];

var values = pgp.helpers.values(data, cs);
//=> (1,1),(2,2)

var update = pgp.as.format(`UPDATE users SET balance = balance + v.delta FROM(VALUES $1^)
AS v($2^) WHERE v.id = users.id`, [values, cs.names]);
//=> UPDATE users SET balance = balance + v.delta FROM(VALUES(1,1),(2,2)) AS v("id", "delta") WHERE v.id = users.id
```

[ColumnSet]:http://vitaly-t.github.io/pg-promise/helpers.ColumnSet.html
[names]:http://vitaly-t.github.io/pg-promise/helpers.ColumnSet.html#names
[variables]:http://vitaly-t.github.io/pg-promise/helpers.ColumnSet.html#variables
