### ISSUE TITLE
Display SQL logs

### ISSUE THREAD

**Issue by benoittgt** [vitaly-t/pg-promise#276]
Hello

I would like to know if it's possible to returns logs on query (in a batch).
For example : 
```javascript
db.tx(function(t) {
    return t.batch([
      t.none('CREATE SCHEMA IF NOT EXISTS public;'),
      t.none('CREATE TABLE IF NOT EXISTS pg_promise (id integer);'),
    ]);
  })
  .then(function(result) {
    console.log(result);
  })
});
// ['CREATE SCHEMA', 'CREATE TABLE']
```
I saw mentions about debug but tried with `NODE_ENV='development'` and did see any logs.

Thanks in advance

**Comment by vitaly-t** [comment]
Are you asking about how to monitor queries being executed by the library?

**Comment by benoittgt** [comment]
Not exactly. I would like to get the numbers of rows inserted in case of an `INSERT TO`.

Good job for pg-monitor. Didn't know it exists.

**Comment by vitaly-t** [comment]
Number of rows inserted? You lost me. Whatever rows you insert, that's the number.

What do you want the library to tell you and in what particular case?

And method `.batch` resolves with whatever the set of promises/values you provide there.

**Comment by benoittgt** [comment]
I'm sorry. For example if I have this query : 
```sql
INSERT INTO sensor_log_b (location, reading, reading_date)
  SELECT id, location, reading, reading_date
  FROM sensor_log_a
  WHERE reading = 22;
```
I would like to log the answer (for example: `INSERT 0 5230`)

**Comment by vitaly-t** [comment]
How is this relevant to this library? This is a pure SQL question.

**Comment by benoittgt** [comment]
Yes you are probably right. 
In my case I have an AWS lambda that runs an INSERT INTO query often against Redshift database and sometimes (around 1%)  rows are not inserted. I thought displaying this log could have help me find the issue.

That's a very specific case.

**Comment by vitaly-t** [comment]
If you are inserting inside a transaction, then your `.catch` will contain the error details. But if you are inserting from another select that fails for one specific value - i'm not even sure how to debug it, rather than use pgAdmin and see where the problem is, since it is all just one query.

**Comment by benoittgt** [comment]
Thanks a lot @vitaly-t for your answer and your time.

**Comment by vitaly-t** [comment]
That means your insert is successful, you but perhaps your select is simply returning less data than you hoped for, which is a data/business problem, that needs database logic analysis of what is going on there.
