### ISSUE TITLE
TIMESTAMP without timezone incorrectly localized 

### ISSUE THREAD

**Issue by FrankV01** [vitaly-t/pg-promise#278]
In querying a table with pg-promise where the table was created without TIMESTAMP, the results always assumed my local time zone (not sure if it was relative to the nodejs client or postgres server). 

So if '`2017-02-10T00:00:00Z`' was in the database, the result in the JavaScript Date would end up as '`Oct 02 2017 12:00 AM GMT -0600`' (not exact output but it should illustrate my intended point)

According to research (granted, incomplete), the behavior of Postgres in this case is that `TIMESTAMP` should be stored and returned as UTC. Therefore, I'd expect that the JavaScript `Date` object would be loaded as such...  

_Note_: I suppose this might be a bug in [node-postgres](https://github.com/brianc/node-postgres) but I encountered it using pg-promise so that is where I am starting. Apologizes if that is the case.

**Comment by vitaly-t** [comment]
This library does not do any value formatting, it is all handled by [node-postgres](https://github.com/brianc/node-postgres) and its [pg-types](https://github.com/brianc/node-pg-types) sub-module, which you can access via `pgp.pg.types`.

**Comment by FrankV01** [comment]
Ok, thanks.
