### ISSUE TITLE
Double quotes when using QueryFile

### ISSUE THREAD

**Issue by benoittgt** [vitaly-t/pg-promise#279]
Hello

I have a big query with lot's of string interpolation and I don't know why I get double simple quote (see CET and s3path).

```
 QueryFile {
    file: "/Users/bti/code/lambda/export_stats/downloads_by_users.sql"
    options: {"debug":true,"minify":false,"compress":false,"params":{"timezone":"CET","s3path":"mypath"}}
    query: "UNLOAD ($UNLOAD_QUERY$
    SELECT 
-- query cut
                to_char((created_at AT TIME ZONE ''CET'')::timestamptz, 'YYYY-MM-DD HH24:MI:SS OF') 
-- query cut
    $UNLOAD_QUERY$)
TO ''s3://mypath''  --
DELIMITER ','
ALLOWOVERWRITE
PARALLEL OFF;
"
}
```

SQL looks like this (I tried different stuff) : 
```sql
                to_char((created_at AT TIME ZONE ${timezone~})::timestamptz, 'YYYY-MM-DD HH24:MI:SS OF' AS created_at
    $UNLOAD_QUERY$)
TO ${s3path}
```

I have this

```js
function sql(file, params) {
  var fullPath = path.join(__dirname, file);
  return new pgp.QueryFile(fullPath, {debug: true, params: params});
}

const params = {
  timezone: timezone,
  s3path: s3path
};
const unloadQuerySQL = sql('downloaded_versions_by_users.sql', params);
console.log('Query is:\n', unloadQuerySQL);
```

I look at [your test](https://github.com/vitaly-t/pg-promise/blob/5beb5565b1c7a8544433db2da3ca798070b625f6/test/fileSpec.js#L47-L56) without finding the answer.

**Comment by vitaly-t** [comment]
Please post here...

* The complete SQL file that you have
* The exact values for `timezone` and `s3path` variables that you are passing in

Then I will be able to test it.

**Comment by benoittgt** [comment]
Thanks @vitaly-t 
I was wrong. Query was correct but not properly reloaded. After adding `debug: true`. It's correct. 

Sorry

PS: I ran my own test using a fork of pg-promise and a lot's of tests were failing because of wrong database setup. Do you think a `CONTRIBUTING.md` shouldn't be useful to help to run project locally?

**Comment by vitaly-t** [comment]
@benoittgt are you saying that you followed the [test steps](https://github.com/vitaly-t/pg-promise#testing) and they didn't work?

**Comment by benoittgt** [comment]
@vitaly-t My bad... I scroll down the Readme looking for those infos and didn't see them in the middle. I was wrong again. I promise that I would read the doc 3 times before opening an issue the next time. Thanks again for your patience.
