### ISSUE TITLE
Formatting Error when storing ${name} values with embedded $1

### ISSUE THREAD

**Issue by macprog-guy** [vitaly-t/pg-promise#28]
Hello, 

There seems to an error when substituting values that may contain embedded $1, $2, etc. values. Such is the case, for example, with bcrypt hashed passwords.  Here is an example:

    f.formatQuery('${x}', {x:'$2a$10$tZ2eG7mVV2LfndEpIGNJi.BKSr36jcR6fqAG3mIZTnJDRdztMxkd2'})
    # output: '\'a{0$tZ2eG7mVV2LfndEpIGNJi.BKSr36jcR6fqAG3mIZTnJDRdztMxkd2\''

While the following returns the expected result:

    f.formatQuery('$1', '$2a$10$tZ2eG7mVV2LfndEpIGNJi.BKSr36jcR6fqAG3mIZTnJDRdztMxkd2')
    # output:  '\'$2a$10$tZ2eG7mVV2LfndEpIGNJi.BKSr36jcR6fqAG3mIZTnJDRdztMxkd2\''

Otherwise, this is really an excellent project. 
Keep up the good work.

Cheers

**Comment by vitaly-t** [comment]
@macprog-guy which version of the library are you using? There was a change related to the same issue #27.

**Comment by macprog-guy** [comment]
Apologies. I had not noticed that I was running an older version. Thanks.

**Comment by vitaly-t** [comment]
@macprog-guy that's ok. I did a test in the meantime against the current version 1.5.1 and I got the expected result.

Thank you for your support! :)
