### ISSUE TITLE
How to load multiple query files?

### ISSUE THREAD

**Issue by saidkholov** [vitaly-t/pg-promise#282]
If I want to make query files reusable and split them into pieces. How can I achieve that?

**Comment by vitaly-t** [comment]
See how files are organized in [pg-promise-demo](https://github.com/vitaly-t/pg-promise-demo).

In the demo you can see each SQL using variable `${schema~}` to inject a schema.

Using the same approach you can link multiple SQL files into a single file, although you would inject them as raw text (`:raw` / `^`), like this: `${externalFile^}`, then parameterize the constructor accordingly.

**Comment by vitaly-t** [comment]
Here, I've come up with a simple example of it...

```js
var QueryFile = require('pg-promise').QueryFile;
var path = require('path');

// independent queries:
var queries = {
    one: sql('sql/one.sql')
};

// adding dependent queries:
queries.two = sql('sql/two.sql', queries.one);

function sql(file, external) {
    var fullPath = path.join(__dirname, file); // generating full path;
    var options = {
        params: {
            external: external
        }
    };
    return new QueryFile(fullPath, options);
}

module.exports = queries;
```
**sql/one.sql**
```sql
FIRST QUERY
```
**sql/two.sql**
```sql
SECOND QUERY
${external^}
```

**Comment by vitaly-t** [comment]
Closing now, for the lack of feedback.

**Comment by saidkholov** [comment]
Thanks for you example. Looks neat. I will try it tonight.

**Comment by saidkholov** [comment]
It worked very well thanks. The only thing i had to change is that parameter `external` to default to empty string. QueryFile does not accept null or undefined apparently. 

ES6:

```
function sql(file, external = '') {
 // ....
}
```

**Comment by vitaly-t** [comment]
If you make the initialization sequence correct, then it will work exactly as in the example, which by the way was tested.

The issue you refer to is about not being able to use `null`/`undefined` values for a raw-text variable, as interpretation of those becomes ambiguous.

**Comment by saidkholov** [comment]
Yep my bad. It worked just fine. The problem was in my query. Cheers

**Comment by vitaly-t** [comment]
Something to keep in mind... the very useful option `debug` of type `QueryFile` will not work for nested SQL files, obviously :wink:

**Comment by saidkholov** [comment]
Thanks, I'll bear that in mind

**Comment by allthesignals** [comment]
Very interested in this - have you found queries to be more composable using this method? For example, maybe I would like to split out a query and pass through `limit`s or `offset`s using the `external` query file variable so that some queries aren't limit-able. The idea is that we'd have less duplication but risk abstracting the wrong way.

**Comment by allthesignals** [comment]
For example, I would like to be able to setup a "paginate" helper like so:

```
    const projects =
      await db.any(listProjectsQuery, {
        communityDistrict,
        itemsPerPage,
        dcp_publicstatus,
        paginate,
        offset: (page - 1) * itemsPerPage,
      });
```

... where `paginate` is a query file with named parameters. The problem is I don't know how to setup the `paginate` SQL fragment with the parameters. I wonder if I can render the parameters directly before sending it to `db.any`?

**Comment by vitaly-t** [comment]
@allthesignals 

```js
const paginateQuery = new pgp.QueryFile(path, options);

function paginate(values) {
    return {
        toPostgres: pgp.as.format(paginateQuery, values),
        rawType: true
    };
}
```

Now you can pass in `paginate(values)` as your paginate value.

**Comment by allthesignals** [comment]
🙌 thank you, @vitaly-t - you're a saint! I was digging through source and was JUST about to look up the docs for using functions as values. 

Only difference is I needed to use `toPostgres` directly when passing my paginate value:

```javascript
    const projects =
      await db.any(listProjectsQuery, {
        communityDistrict,
        itemsPerPage,
        dcp_publicstatus,
        paginate: paginate({ itemsPerPage, offset: (page - 1) * itemsPerPage }).toPostgres,
      });
```

Which seems wrong to me, but it works

**Comment by vitaly-t** [comment]
You should never use `.toPostgres`, which defeats the ideas of custom type formatting, which must work as an object, like I showed in the code above.

**Comment by allthesignals** [comment]
@vitaly-t I agree, it seems wrong - I think am not using the proper syntax for CTF in my query file for the `paginate` value.

**Comment by allthesignals** [comment]
```javascript
function paginate(values) {
  return {
    toPostgres() { return pgp.as.format(paginateQuery, values); },
    rawType: true,
  };
}
```

`toPostgres` probably needs to be a method not a property

**Comment by vitaly-t** [comment]
Ops, yes, I corrected the code ;)

**Comment by vitaly-t** [comment]
@allthesignals 

A small correction, after reviewing the code. I forgot that I implemented auto-update within the regular query formatting, so using this approach will guarantee auto-update automatically:

```js
const paginateQuery = new pgp.QueryFile(path, options);

function paginate(values) {
    return {
        toPostgres: () => pgp.as.format(paginateQuery, values),
        rawType: true
    };
}
```
