### ISSUE TITLE
Design question: intercepting requests

### ISSUE THREAD

**Issue by djMax** [vitaly-t/pg-promise#283]
We are trying to integrate our services with prometheus, which is a monitoring framework. I'd like to get timing of all the pg requests without having to change the clients too much. Is there a central place I can catch all that traffic in pg-promise (since we mostly talk to that and not directly to pg underneath).

**Comment by vitaly-t** [comment]
Event [query](http://vitaly-t.github.io/pg-promise/global.html#event:query) is reported for every query executed, which happens just before it executes.

Many requests provide additional details about the duration, but that's only available locally, not globally.

Also see: https://github.com/vitaly-t/pg-promise/pull/243

I wonder if it is worth reviving now... :)

**Comment by djMax** [comment]
I kind of agree with the sentiment that #243 was doing too much (e.g. the stats). But I do think there has to be a reliable query completion event of some sort, and receive doesn't seem to fire all the time. In my case I have a layer I can just insert this into by overriding our relatively thin method usage (one, many, oneOrNone, etc). But I'd be happy to avoid that if there was a finish type event. It should include some access to something that was passed in the query event to allow linking it all back together.

**Comment by vitaly-t** [comment]
> and receive doesn't seem to fire all the time

As per the API, it only fires when there is data received, to allow post-processing.

**Comment by vitaly-t** [comment]
As I mentioned earlier, most of methods expose property `duration` on the result, like `any`, `many`, `manyOrNone`, `result`,...

**Comment by vitaly-t** [comment]
@djMax documentation has been updated to mention whenever property `duration` is available :wink:

**Comment by vitaly-t** [comment]
[Release 5.5.8](https://github.com/vitaly-t/pg-promise/releases/tag/v.5.5.8) included updates for better support of property `duration` everywhere.

**Comment by christiangalsterer** [comment]
If somebody is still interested in monitoring with prometheus, there is a new prometheus exporter for pg-promise now available at  https://www.npmjs.com/package/@christiangalsterer/pg-promise-prometheus-exporter.
