### ISSUE TITLE
Question: How to terminate a database connection?

### ISSUE THREAD

**Issue by tobymurray** [vitaly-t/pg-promise#284]
I looked over the documentation and the code a bit, and I'm not quite sure what I'm missing. I have a `Database` object. I want to release any clients that object holds so that I can create a new database with that the first database as a template.

```
  var pgp = require('pg-promise')();
  ... <snip> ...
  var database = new pgp(testDatabaseConfig);
  database.task(provisionDatabase);
  // Release the connection to avoid "source database is being accessed by other users" 
  pgp.end(); 
  pgp = require('pg-promise')();
  // start cloning with the values from `testDatabase` as the target
```

This appears to work, but I'm suspicious I may be doing something stupid...

**Comment by vitaly-t** [comment]
`pgp.end()` is all that's needed to kill all connections within the client.
