### ISSUE TITLE
pgp.helpers.insert is double quoting table name

### ISSUE THREAD

**Issue by msjoshi** [vitaly-t/pg-promise#285]
I recently upgraded to Postgres 9.6.1 and noticed pgp.helpers.insert is double quoting table name which results in relation does not exist error.
```javascript
        const data = {
                resource_id: uuid.v4(),
                data: {
                    content: 'some content'
                },
                version: 'application/vnd.integration.v2+json'
            };
            const stmt = pgp.helpers.insert(data, null, `${schema}.fake_entity_one`) + 'RETURNING id';
            console.log(stmt);
            cs.one(stmt).then(result => {
                result.id.should.equal(1);
                done();
            });
```
This results in the query

> insert into "tenant_00000000_0000_0000_0000_000000000000.fake_entity_one"("resource_id","data","version") values('64ab28aa-c173-4172-8d93-9ec5c598acb4','{"content":"some content"}','application/vnd.integration.v2+json')

If I remove the double quotes on table name, query works fine from the psql console. Any thoughts?

**Comment by vitaly-t** [comment]
Invalid use of parameter `table`. Declare your table parameter as this:

```js
var table = new pgp.helpers.TableName(schema, table);
```

See: [TableName](http://vitaly-t.github.io/pg-promise/helpers.TableName.html).

**Comment by msjoshi** [comment]
Perfect! Thanks @vitaly-t
