### ISSUE TITLE
Precision about connexion release

### ISSUE THREAD

**Issue by abenhamdine** [vitaly-t/pg-promise#286]
Hi Vitaly,

Sorry it this is more suited for a SO question, but I didn't found this point in the documentation, so perhaps it's also a docs enhancement request 😉 .

We are currently using pg module (not pgp), and we used to struggle with connexion leaks, because in some pieces of code, some forgot to call client.release() 😠 
As you can imagine, it's very penalizing because with pg (at least with pg < 6.0), AFAIK pg.connect sends no error when the pool is exhausted (see https://github.com/brianc/node-postgres/pull/1006#issuecomment-282077764).
So the server is simply blocked and hangs indefinitly.

I'm currently evaluating if we should switch to pgpromise, but, because it's build on top of pg, I wonder if the problem is also present

So with pgpromise : 
- should we have to releave every connexion ? or are they released automatically after every query ?
- what happens if the pool is exhausted ? Is an error sent back ? Or the query is queued until a connexion is available ? Is it possible to set a timeout for that ?

Or in other words : what are the differences with pg on this ?

Thx a lot by advance !

**Comment by vitaly-t** [comment]
> should we have to release every connection?

No. It is all done automatically. There are some very unique cases when method `connect` is used, to be released when no longer needed, but again, you would barely ever need it.

> or are they released automatically after every query?

They are indeed, released automatically.

And when you need to execute more than one query at a time against the same connection, you use either tasks (method `task`) or transactions (method `tx`).

> what happens if the pool is exhausted ? Is an error sent back ? Or the query is queued until a connexion is available ? Is it possible to set a timeout for that?

It will be waiting till a connection becomes available, no error is thrown. The whole `pg-promise` architecture is however built around the idea of efficient connection use, so it would never happen, if you design your database layer correctly.

**Comment by abenhamdine** [comment]
Thx a lot for this detailled answer !
IMHO this should be more highlighted in the docs, it's useful to know for a newcomer.
