### ISSUE TITLE
Insert JSON object into JSONB column instead of text array

### ISSUE THREAD

**Issue by hoangphuoc25** [vitaly-t/pg-promise#287]
```
var Promise = require('bluebird');
var pgp = require('pg-promise')({
  promiseLib: Promise
});

var config = {
  user: process.env.DB_USER,
  database: process.env.DB_NAME,
  password: process.env.DB_PASSWORD,
  host: process.env.DB_HOST,
  port: 5432,
  poolSize: 10
};

var db = pgp(config);

db.query(`insert into x values ($/val/)`, {
  val: [{
    x: 1,
    y: 2
  }]
})
.then(() => {
  process.exit(0);
})
.catch(err => {
  console.log(err);
  process.exit(1);
});
```

In Postgres I ran this query `create table x (a jsonb);`

When running the script above, pg log tells me that `pg-promise` sent this query to server `insert into x values (array['{"x":1,"y":2}'])`, which is wrong because `a` requires jsonb type, not text[] type.

How do I get `pg-promise` to tell Postgres to insert it as a JSONB instead of a text array?

**Comment by vitaly-t** [comment]
You need to tell the query-formatting engine of the library that your parameter is JSON.

For the change `$/val/` to `$/val:json/`
