### ISSUE TITLE
Prepared Statement with named parameter

### ISSUE THREAD

**Issue by hoangphuoc25** [vitaly-t/pg-promise#288]
Document says only basic variables can be used in a prepared statement because it is formatted by server. Is it possible to write named parameters and have `pg-promise` translate it to a Prepared Statement and send to server? I prefer the server to format the query for me to avoid SQL Injection.

**Comment by vitaly-t** [comment]
Duplicate. Search for existing questions: https://github.com/vitaly-t/pg-promise/issues?utf8=%E2%9C%93&q=named%20parameter%20server
