### ISSUE TITLE
Only update values passed?

### ISSUE THREAD

**Issue by davegri** [vitaly-t/pg-promise#289]
Is it possible to only update values passed? I would like to do
```
const updateContact = contact => db.none(
  'UPDATE contacts SET email = $/email/, password = $/password/, orgId = $/orgId/, sfId = $/sfId/ WHERE id = $/id/',
  contact
);
```

If one of the values passed is missing this fails, whats the correct way to do this?

**Comment by vitaly-t** [comment]
>whats the correct way to do this?

via [helpers.update](http://vitaly-t.github.io/pg-promise/helpers.html#.update).

see also: [skip update columns with pg-promise](http://stackoverflow.com/questions/40697330/skip-update-columns-with-pg-promise)
