### ISSUE TITLE
Mocking

### ISSUE THREAD

**Issue by JacobSoderblom** [vitaly-t/pg-promise#292]
Hi!

I'm trying to find a way to mock `pg-promise` results for unit-testing, I could not find any documentation about this in your wiki. Is it and will it be possible to use mock results in unit-testing with this lib?

**Comment by vitaly-t** [comment]
You test it the same as you would any promise-based interface, nothing special there.

Some useful links:

* http://stackoverflow.com/questions/37368261/how-should-i-do-asynchronous-unit-testing
* https://coderwall.com/p/axugwa/cleaning-the-database-in-between-mocha-tests-with-pg-promise

**Comment by JacobSoderblom** [comment]
Thank you for your answer!

I'm familiar with how to test promise-based interfaces, but what I want to achieve is to remove the database connection when running my tests. Maybe `sinon` will make this possible.

Btw, great library!

**Comment by vitaly-t** [comment]
It is doable, but in my experience it is too limiting.

Best is to use something like Travis CI where you get all PostgreSQL versions for granted. This is how this library tests itself also.
