### ISSUE TITLE
question about opening a connection and  pgp.end(); 

### ISSUE THREAD

**Issue by blendsdk** [vitaly-t/pg-promise#295]
Hi,

I have a web application created using Express. I would like to know what the best practices are to use pg-promise regarding opening and closing connections in a request-response cycle.

Thanks.

**Comment by vitaly-t** [comment]
You do not open connections, the library does it automatically.

When executing more than one query within a request-response cycle you should use tasks, or transactions when needed.

See: [Tasks](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#tasks).

**Comment by blendsdk** [comment]
Thank you. Does this also mean that I don’t need to close the connection because it will automagically close due timeout?

**Comment by vitaly-t** [comment]
The library automatically releases connections back into the pool, those close after a non-use timeout.
