### ISSUE TITLE
Are multi-statement queries guaranteed to be run on the same connection?

### ISSUE THREAD

**Issue by dzaman** [vitaly-t/pg-promise#297]
For example:

    db.query('SET config.var = 'foo'; SELECT ...');

Is the `SELECT` statement guaranteed to be run on the same connection as the `SET` statement?

**Comment by vitaly-t** [comment]
Method `query` doesn't parse the query for sub-queries, neither does anything else in this library for that matter.

So, naturally, yes, of course everything in the query string executes against the same connection.
