### ISSUE TITLE
data with $s in quoted strings

### ISSUE THREAD

**Issue by ZeusIV** [vitaly-t/pg-promise#30]
I love this library and hope I wasn't too sarcastic with this bug last time :)
got a couple of issues with this format function
object: function (query, obj) { 
80         var pattern = /\$(?:({)|(\()|(<)|(\[)|(\/))\s*[a-z0-9\$_]+\^?\s*(?:(?=\2)(?=\3)(?=\4)(?=\5)}|(?=\1)(?=\3)(?=\4)(?=\5)\)|(?=\1)(?=\2)(?=\4)(?=\5)>|(?=\1)(?=\2)(?=\3)(?=\5)]|(?=\1)(?=\2)(?=\3)(?=\4)\/)/gi; 
81          
etc.....

looks like it limits replacing to only 5 params which would break when you have 6 and some text in the string such as " I will pay you $6 for that used bus ticket"
a bit new to git so don't want to do a pull and a push or whatever so can I suggest a better way

object: function (query, obj) { 
query.split(/(\$[0-9]+)/g).map(function (val) {
  if (mat = val.match(/^\$([0-9]+)$/)) { return obj[mat[1] - 1]; }
  return val;
}).join('');
etc... (with your raw stuff)

so with a call like so 
var values = ['first', 'second', 'third', 'fourth', 'fifth', 'i bought this house for $6', 'seventh', 'eighth'];
var text = 'update username="$1" where id=$2 and email="$3" and addr1="$4" and addr2="$5" and addr3="$6" and addr4="$7" and addr5="$8"';
return db.query(text, values);

it would split the query string like so
[ 'update username="',
  '$1',
  '" where id=',
  '$2',
  ' and email="',
  '$3',
  '" and addr1="',
  '$4',
  '" and addr2="',
  '$5',
  '" and addr3="',
  '$6',
  '" and addr4="',
  '$7',
  '" and addr5="',
  '$8'
  ]
map the array to
[ 'update username="',
  'first',
  '" where id=',
  'second',
  ' and email="',
  'third',
  '" and addr1="',
  'fourth',
  '" and addr2="',
  'fifth',
  '" and addr3="',
  'i bought this house for $6',
  '" and addr4="',
  'seventh',
  '" and addr5="',
  'eighth'
  ]
avoiding any clashes with quoted values with a '$' in them
then join it to
'update username="first" where id=second and email="third" and addr1="fourth" and addr2="fifth" and addr3="i bought this house for $6" and addr4="seventh" and addr5="eighth"'
which wouldn't blow up with an address line3 of "i bought this house for $6" :)

thanks Zeus

p.s. the nice thing about pg is that you can call a query with  an object 
pg.query({text: 'some query', values: []})
and the nice thing about squel is the toParam() method returns that object and can be passed direct to pg.
var qobj = squel....
pg.query(qobj);
would be nice to do the same with pg-promise :)
not sure how easy that would be?

**Comment by vitaly-t** [comment]
Hi Zeus,

>looks like it limits replacing to only 5 params

It looks or it does? It passes tests with any number of variables, so it isn't relevant what it looks like. And 1-5 in the reg-ex refers to the number of variations for open-close symbols, it got nothing to do with the number of variables being formatted.

I can't replicate the issue you described. Could you, please, give one simple example where formatting breaks?

Also, regarding strings like this:
```javascript
var text = 'update username="$1" where id=$2 and email="$3" and addr1="$4" and addr2="$5" and addr3="$6" and addr4="$7" and addr5="$8"';
```
You should not put double-quote symbols around variable, the formatting inserts single-quote symbols around strings automatically as ti should.

**Comment by ZeusIV** [comment]
many apologies vitally
I didn't test it because I switched to pgFormatting: true when I was getting problems and came back to see if it had been fixed. not fluent in regex it looked like a fix for this problem and a bit finite :)

why an object?
well pg accepts an object and if you promisify pg you could pass it the object, add the .then, continue coding. if later you want to switch to pg-promise it is a lot more coding. a similar calling interface would make it easier. that's all.
sorry to go on about squel but it returns this object because a few sql interfaces use it like that. it would be nice to change database engine without having to rewrite gobs of code. however the extend framework looks like it might do the job :)

Regards Zeus

p.s. I dunno how to like, unless this is it :+1:

**Comment by vitaly-t** [comment]
@ZeusIV this is confusing, you are saying that you are using `pgFormatting = true`, but then what issues are you having there?

I'm trying to understand the original problem, if there is still any.

P.S. Here Like = Star ;)

**Comment by vitaly-t** [comment]
@ZeusIV please either provide details about the issue or close it.
