### ISSUE TITLE
Db connection pool needs reference to helpers

### ISSUE THREAD

**Issue by skylize** [vitaly-t/pg-promise#302]
Currently the top level pgp object is required in order to access helpers. To use helpers in another file, all of pgp must be passed around or else re-imported and re-instantiated in each file. A reference to helpers should be attached to the connection pool, so only the pool must be passed around.

Example useage: 
*app.js*
```javascript
//...
// instantiate connection pool
const db = require('pg-promise')(opts)(config)
// insert some data through a data model from another file
require('./model').insert(db, data, table)
//...
```
*model.js* (currently working, but too much overhead)
```javascript
// Model would normally have some business logic and/or validation,
//   but for simplicity of example we just do the insert.
module.exports = {
   // Even though we already have the connection pool at hand,
    //    we must also pass around pgp object to access helpers 
    //    or, as done here, include & instantitate an entirely new copy of pgp.
  insert (data, db, table){
    // build query using helpers
    const query =
      require('pg-promise')().helpers
      .insert(data, Object.keys(data), table)
    // insert and return result
    return db.query(query)
  }
}
```
*model.js* (better solution, but currently won't work)
```javascript
// Model would normally have some business logic and/or validation,
//   but for simplicity of example we just do the insert.
module.exports = {
      // This would be much better, but fails because the connection 
    //    pool has no reference to helpers
  insert (data, db, table){
    // build query using helpers
    const query = 
      // Error: cannot read property 'insert' of undefined
      db.helpers.insert(data, Object.keys(data), table) 
    // insert and return result
    return db.query(query)
  }
}
```
Fix needs to be done internally as shown by this attempted patch
*app.js* (failed patch)
```javascript
//...
// instantiate connection pool
const pgp =require('pg-promise')(opts) 
const db = pgp(config)

// Attempt to attach a helpers reference to our connection pool
//    before passing it to the model.
//    TypeError: Can't add property helpers, object is not extensible
db.helpers = pgp.helpers

// insert some data through a data model from another file
require('./model').insert(db, data, table)
//...
```

**Comment by vitaly-t** [comment]
It is already there, see [Database.$config](http://vitaly-t.github.io/pg-promise/Database.html#.$config).

Whenever you need access to the helpers where only `db` object is available, you can do:

```js
var helpers = db.$config.pgp.helpers;
```

As for the protocol extensibility, it has always been fully extensible via event [extend](http://vitaly-t.github.io/pg-promise/global.html#event:extend).

See also [pg-promise-demo](https://github.com/vitaly-t/pg-promise-demo) to understand how a large-scale project should be organized.

**Comment by skylize** [comment]
> `const query = require('pg-promise')().helpers`
>
> You should never do such coding. Variable pgp must be created only once and then exported around. See: http://stackoverflow.com/questions/34382796/where-should-i-initialize-pg-promise

Yes. I absolutely agree. That's why I came here. Lol

> `var helpers = db.$config.pgp.helpers;`

That's perfect! Thanks. Don't think I would have found that without your help.

> I think you should read more of the documentation, to understand better how this library works and what one can do with it 😉

Yep, working on it.  😏

**Comment by vitaly-t** [comment]
I have updated the question ;) http://stackoverflow.com/questions/34382796/where-should-i-initialize-pg-promise

**Comment by skylize** [comment]
👍
