### ISSUE TITLE
task generator vs async function

### ISSUE THREAD

**Issue by rafaelkallis** [vitaly-t/pg-promise#303]
Question regarding tasks and transactions:

Are there any side effects when using async functions in tasks and transactions instead of generators?  Until now I didn't have any issues using async functions with `pg-promise` and would like continue using them.

Here's an example:

```
db.tx(async (t) => {
    const result1 = await t.one(" ... ");
    const result2 = await t.one(" ... ", [result1.foo]);
    return result2.bar;
});
```

EDIT: replaced `transaction` with `tx`

**Comment by rafaelkallis** [comment]
Great, thanks for clarifying!

**Comment by vitaly-t** [comment]
All 3 approaches work as native with this library for methods [task] and [tx]:

* regular promise chain
* ES6 generators
* ES7 await clause

See examples: https://github.com/vitaly-t/pg-promise/blob/master/examples/select-insert.md

[task]:http://vitaly-t.github.io/pg-promise/Database.html#.task
[tx]:http://vitaly-t.github.io/pg-promise/Database.html#.tx

**Comment by rafaelkallis** [comment]
@vitaly-t mind If I make a pull request with an additional **ES7 await clause** example for the `select-insert` you referenced?

**Comment by vitaly-t** [comment]
I suppose why not, but mind you all examples I provided do not require any additional setup, while ES7 await implies there is a full Babel setup in the background.

I myself haven't done a project with Babel yet, but I get an impression there is quite a bit to it: http://stackoverflow.com/questions/33624104/how-do-i-setup-babel-6-with-node-js-to-use-es6-in-my-server-side-code

**Comment by rafaelkallis** [comment]
@vitaly-t will do, even though I have used babel in bigger projects, I currently explicitly use Typescript for all my code, which supports and transpiles the ES7 async clause. 

Additionally if using latest `node`, async await is natively supported.

Will create a PR with extended documentation later. Thanks again.

**Comment by vitaly-t** [comment]
Yeah, I just did a local ES7 await test here:

```
$ node --harmony-async-await test.js
```

and it worked fine.

**Comment by rafaelkallis** [comment]
@vitaly-t you dont have to use `--harmony-async-await` since Node.js 7.6

**Comment by vitaly-t** [comment]
My first test threw compilation errors, so I thought that was the reason, but now without the paremeter it works, not sure what happened earlier :)

**Comment by vitaly-t** [comment]
@rafaelkallis By the way, it is worth noting that ES7 await offers no advantage over ES6 Generators, at least as far as this library is concerned, because the syntax is almost identical, you just use `yield` instead of `await`.

**Comment by rafaelkallis** [comment]
@vitaly-t I am aware that anything done with `await` can be done using `yield`. I just find it more pleasing working with promises instead of generators. 

If I remember correctly, the only difference in theory is that you can use arrow functions with an async clause, which is not possible using generators. (haven't tested it)

```
// async await
        ...
        await this.database.tx(async tx => {
            if (await this.personModel.loginExists(login, tx)) {
                throw new LoginExistsError();
            }
            const [personId, hash]: [number, string] = await Promise.all([
                this.personModel.create(login, firstName, lastName, tx),
                BCrypt.hash(password, 12)
            ]);

            await this.authModel.create(personId, hash, tx);
            return personId;
        });
```

```
// generators
        ...
        const self = this;
        yield this.database.tx(function* (tx) {
            if (yield self.personModel.loginExists(login, tx);) {
                throw new LoginExistsError();
            }
            const [personId, hash]: [number, string] = yield Promise.all([
                self.personModel.create(login, firstName, lastName, tx),
                BCrypt.hash(password, 12)
            ]);

            yield self.authModel.create(personId, hash, tx);
            return personId;
        });
```

**Comment by vitaly-t** [comment]
Note, you should never use `Promise.all` on queries ;) See: https://github.com/vitaly-t/pg-promise/wiki/Common-Mistakes#tasks-versus-rootdirect-queries

**Comment by rafaelkallis** [comment]
`this.personModel.create(login, firstName, lastName, tx)` executes one query.
`BCrypt.hash(password, 12)` executes no queries.

If `Promise.all` executes only one query, just like in the example above, shouldn't there be no issues at all?

That would be the equivalent of:
```
const result = await Promise.all([
    t.any('select * from users')
]);
```

**Comment by vitaly-t** [comment]
One query, if it is first one, that's it's fine, but it is hardly ever the case in practice ;)

Best is to be consistent, and use `t.batch` instead ;)
