### ISSUE TITLE
Unexpected errors being logged to stdout – is there any way to disable them?

### ISSUE THREAD

**Issue by jmeas** [vitaly-t/pg-promise#305]
I'm executing the following code:

```js
console.log('Just before...\n');
const result = await this.db.tx(t => {
  const primaryTableQuery = t.one(query);
  return t.batch([primaryTableQuery]);
}).catch(r => r);
console.log('\nJust after\n\n');
```

Before you mention it, I know we talked about that pesky `.catch(r => r);`...I haven't gotten around to refactoring it away. But this issue seems unrelated to that.

Also, I understand that (right now), the use of a transaction here is unnecessary. Soon it will be necessary, though, as I plan to add more queries to the batch.

Anyway, when I execute that code with a bad query (intentionally), this is what gets logged:

```
Just before...

ERROR:  duplicate key value violates unique constraint "dog_device_id_key"
DETAIL:  Key (device_id)=(1) already exists.
STATEMENT:  INSERT INTO "dog"("name","device_id") VALUES('please','1') RETURNING *

Just after
```

That part in the middle, with information related to the dog, is unexpected. If I wanted to add logging related to failed queries, I could do that myself using the error object. Is there any way to disable these logs? I tried disabling it with the `noWarnings` option, but that didn't remove them.

I looked around the pg-promise and node-postgres source to find whatever is logging this out, but I couldn't find anything. Any thoughts, @vitaly-t ?

To add to the mystery, these unexpected logs aren't appearing on Travis. 🤔

**Comment by vitaly-t** [comment]
This library doesn't generate any of these. I don't know where you got them from. It is in anyway related to this library.

**Comment by vitaly-t** [comment]
@jmeas a little googling took me to this page: https://www.postgresql.org/message-id/BANLkTimQ_mqPq0iFc-Xqzubzz81AtvGrLA@mail.gmail.com

**Comment by jmeas** [comment]
Thanks for the confirmation that it isn't in this lib, @vitaly-t . I'll google around a little more to see if i can find a way to disable it on the DB side of things. If I find a solution, i'll post it here. I'll close this out for now, since it's unrelated to this project ✌️

**Comment by vitaly-t** [comment]
@jmeas did you get to the bottom of it?

**Comment by jmeas** [comment]
I did not, but I also didn't spend too much more time on it since it was just an inconvenience

**Comment by kartblanch** [comment]
@jamesplease Hi! Did you solve this problem? Do you know any solutions of this problem?

**Comment by jamesplease** [comment]
Nope, sorry.
