### ISSUE TITLE
Blank space after text

### ISSUE THREAD

**Issue by xemox** [vitaly-t/pg-promise#308]
Hi @vitaly-t 
I just want to ask, that there are blank space after text I insert into column in table of postgresql.

For example when I define a field with char(100), but I filled with 30 characters, so I got 70 blank space characters after text in this column.

Therefore, when I return the value from table, I have to delete these multiple spaces using regex. 
Is this default behavior of postgres or this plugin? Is there any option to omit this? 

Thanks
Stomy

**Comment by vitaly-t** [comment]
This library does not create any extra blank spaces in SQL. You need to learn PostgreSQL  and SQL in general, to understand what type `char(x)` is and how it works. It is documented everywhere that the type is filled with spaces by the server, which is standard.
