### ISSUE TITLE
executing an stored procedure fails to fetch all reocords

### ISSUE THREAD

**Issue by GunasekaranR** [vitaly-t/pg-promise#309]
Hi,

If i execute this below function it has to return 150 records from database, but it returns only one record and terminate the process

But if i execute same in batch queries task with multiple queries, i getting the correct output.

db.func('schema_name.procedure_name', [
        arg1, arg2, arg3, arg4, arg5, arg6
    ])
    .then(function(data) { 
        res.json(data); // Return the json 
    }).catch(function(error) {
        console.log(error); // printing the error
    });
could any one please help me out? am i doing anything wrong?

Thanks in advance.

**Comment by vitaly-t** [comment]
You didn't provide enough detail about how it works otherwise.

Anyway, this type of question is better suited for StackOverflow. Publish it there with all the details, and either I or somebody else will answer it.
