### ISSUE TITLE
pgp.end() bteween two pgp(config)

### ISSUE THREAD

**Issue by Michal-dia** [vitaly-t/pg-promise#310]
Some very minor issue :
When creating duplicate Database instances for the same connection 
but with a call to 
`pgp.end(); `
in between, results the warning message :
WARNING: Creating a duplicate database object for the same connection.
from http://vitaly-t.github.io/pg-promise/database.js.html#line1221
It seems that dbObjects[cnKey] it only set to true , but never deleted or set to false.
When running pgp.end();  shouldn't dbObjects[cnKey] be reset?
I bumped into this only in unit tests.

**Comment by vitaly-t** [comment]
There is no practical need to ever create the same database connection after shutting down the connection pool via `pgp.end()`.

You only call `pgp.end()` just before exiting a run-through application. Otherwise, you are using it wrong.

**Comment by Michal-dia** [comment]
As I said - I'm using it in unit tests while testing different scenarios with the same connection. Is there a problem is creating the same database connection after shutting down the connection pool in unit tests?

**Comment by vitaly-t** [comment]
Again, why do you want do call `pgp.end()`, if you are not exiting the test process? There's no point doing it then.

You should call it only when you want to exit the test.

For example, `pg-promise` in its own tests does this:

```js
if (jasmine.Runner) {
    var _finishCallback = jasmine.Runner.prototype.finishCallback;
    jasmine.Runner.prototype.finishCallback = function () {
        // Run the old finishCallback:
        _finishCallback.bind(this)();

        pgp.end(); // closing pg database application pool;
    };
}
```

so the pull is shut down after the test has finished.

**Comment by Michal-dia** [comment]
Thanks you!

**Comment by vitaly-t** [comment]
@Michal-dia I've never tried, need to look into that...

Maybe it is possible to get the pool instance from the connection object...

**Comment by Michal-dia** [comment]
ok thanks!

**Comment by vitaly-t** [comment]
@Michal-dia I had a quick looks, and see that `pgp.pg.pools.all` gives you access to the object in which every property is a `Pool` object from the `generic-pool` module (v.2.4.2)

In that object there is property `_count` that I believe what you are looking for.

So you can do:

```js
        var pools = pgp.pg.pools.all;
        var firstPoolName = Object.keys(pools)[0];
        console.log('First Pool Size:', pools[firstPoolName]._count);
```
