### ISSUE TITLE
Problem with a query against postgres as a document store

### ISSUE THREAD

**Issue by socketwiz** [vitaly-t/pg-promise#311]
I can make the following query in psql:

`select data from hosts where (data->'budget') @> '500' AND (data->'website') ? 'personal';`

But when I try to convert that to a pg-promise query I keep running into errors:

```javascript
const QUERY = 'select data from hosts where (data->\'budget\') @> \'${budget}\' AND (data->\'website\') ? \'${website}\'';
const BUDGET = parseInt(request.query['filter[budget]'], 10);
const WEBSITE = request.query['filter[website]'];

DB.query(QUERY, {'budget': BUDGET, 'website': WEBSITE})
    .then(data => reply(data))
    .catch(error => {
        console.log(error);
        return reply(error);
    });
```

> error: syntax error at or near "personal"

If I remove the second part of the query it works fine:

`const QUERY = 'select data from hosts where (data->\'budget\') @> \'${budget}\'';`

Am I forming this query incorrectly or is this a bug?
If it helps, I am using postgres as a document store.  Here is how I created the tables.

```sql
CREATE TABLE "hosts" (
    id TEXT PRIMARY KEY,
    data JSONB,
    created TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
    updated TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);
```

And I imported data (using pg-promise) that looks like this:

```sql
    "hosts": [
        {
            "_id": 1,
            "budget": [500, 1000, -1],
            "domain": true,
            "host": "foohost",
            "link": "https://www.foohost.com/",
            "skill": ["none", "basic", "advanced"],
            "website": ["personal", "ecommerce", "small-business", "blog"]
        }
]
```

**Comment by vitaly-t** [comment]
Just log the resulting query into the console, and then you can see where you make a formatting error.

```js
var s = pgp.as.format(query, values);
console.log(s);
```

Also see [pg-monitor](https://github.com/vitaly-t/pg-monitor).

**Comment by socketwiz** [comment]
Ah thats what I needed, thanks!  It looks like if your parameter is a string you don't need to wrap it in quotes like I was doing.  Thanks for the quick response.

**Comment by vitaly-t** [comment]
Yep, you got it right! :wink:
