### ISSUE TITLE
Expose an interface to create a single connection

### ISSUE THREAD

**Issue by gajus** [vitaly-t/pg-promise#312]
* `pg-promise#query` operates using a connection pool.
* If series of queries need to be executed within a single connection, this can be done using [tasks](https://github.com/vitaly-t/pg-promise/tree/5eb3215a6a21d6a1f997535cfdaa6a64a811e5e6#tasks).

The problem is when the entire application is designed to rely on a single connection. This is the reason why `mysql` driver differentiates between `createConnection` and `createPool`.

Using `ph-promise#task` for this is not an option since task initiates a transaction (`CONNECT->COMMIT/ROLLBACK`).

A simple method `ph-promise#connect` would be enough (with `end` method to end the connection). The underlying implementation could simply take the connection from the connection pool (just like `#task`) and return it to the pool once `end()` is called.

**Comment by vitaly-t** [comment]
Please check the API documentation before opening an issue. Method [connect] has always been there.

[connect]:http://vitaly-t.github.io/pg-promise/Database.html#.connect

**Comment by gajus** [comment]
> Please check the API documentation before opening an issue. Method connect has always been there, which does exactly that.

Sorry. I've scanned through the docs but could not find it. To be specific, I only found the event "connect" thats visible in the sidebar. The documentation is lacking an index of all functions, e.g. like in the lodash documentation https://lodash.com/docs/4.17.4.

> A task (method task) does not initiate any transaction. Only method tx does that.

Right. I misread the docs:

> A transaction, for example, is just a special type of task, wrapped in `CONNECT->COMMIT/ROLLBACK`.

– https://github.com/vitaly-t/pg-promise#tasks

Thats a dangerous sentence to put just above `task` usage example.

**Comment by vitaly-t** [comment]
I'm open to the PR-s that would improve the documentation :wink:
