### ISSUE TITLE
Using pg-promise in AWS Lambda (Best Practices)

### ISSUE THREAD

**Issue by msjoshi** [vitaly-t/pg-promise#314]
Before I start, this is not a pg-promise issue but would like some feedback from the author and contributors on what are the best practices to use pg-promise in AWS Lambda functions. I'm exclusively using pg-promise in Lambda functions and use the best practices like using db.task() and db.batch() as recommended so that lambda function finishes its job in a single database session. 

I initialize pgp with poolSize = 1 and poolIdleTimeout = 1000. In a high concurrency situation, I observed that connections stay open for few minutes in DB even though I use pgp.end() in the lambda function. Also, I noticed in CloudWatch logs that I get warning "creating a duplicate database object for the same connection".

I'm requesting a guidance on using pg-promise efficiently in Lambda functions. I'll be happy to share my code snippets and logs if there is interest.

**Comment by vitaly-t** [comment]
Your question is too wide. And there is nothing lambda-specific in this library.

> I observed that connections stay open for few minutes in DB even though I use pgp.end()

`pgp.end` cannot terminate connections that haven't been released yet, hence the delay.

> creating a duplicate database object for the same connection

See: http://stackoverflow.com/questions/34382796/where-should-i-initialize-pg-promise

**Comment by mythical-programmer** [comment]
@msjoshi did you get the solution for this in AWS lambda? Do we need to make the connection everytime the lambda is invoked?

**Comment by msjoshi** [comment]
@mythical-programmer 
We ended up using a very small connection pool (3-4) with low idle timeout (5 secs). This way if the request comes to the same lambda container, it uses connection from the pool. Ours was a high concurrency requests to Lambda functions so we got good mileage of this strategy.

**Comment by mythical-programmer** [comment]
@msjoshi Thanks. I will be soon using it in production. Good to know.

**Comment by dfloresgonz** [comment]
@mythical-programmer How exactly did you managed to do it? I create a connection in each call but I don't end() them, what's the correct way to handle connections and lambdas?

**Comment by wickedman1976** [comment]
+1 here

**Comment by Crypt-iQ** [comment]
> @mythical-programmer
> We ended up using a very small connection pool (3-4) with low idle timeout (5 secs). This way if the request comes to the same lambda container, it uses connection from the pool. Ours was a high concurrency requests to Lambda functions so we got good mileage of this strategy.

Hey @msjoshi !  Just a quick question that we can move to a private chat if necessary.  How were your lambda functions designed wrt pg-promise such that the containers maintain connection pools to the database?  I am working on a project that uses AWS Lambda + pg-promise and I was wondering what happens when the lambda exits / times out.  In this case, wouldn't the pool be destroyed?  Or is it frozen and possibly thawed out with a later invocation?  Any help appreciated! Thanks!

**Comment by lfreneda** [comment]
@msjoshi do you have any feedback of your implementation in production? I'm facing the same situation.
