### ISSUE TITLE
Wrong node version identified?

### ISSUE THREAD

**Issue by luchillo17** [vitaly-t/pg-promise#315]
So i'm using pg-promise inside a typescript app and the node it asks is wrong, i have v7.8.0 and this is the output of the log in the `index.js` of the loader of pg-promise:

![image](https://cloud.githubusercontent.com/assets/9698639/25254515/981af83c-25eb-11e7-8729-1eed0dd383e7.png)

**Comment by vitaly-t** [comment]
From your log it says clearly: Node: `1.2.0`.

What are you getting when you run command `node --version`?

**Comment by vitaly-t** [comment]
I've closely into this, and there is no issue with the library. You are trying to run it against an ancient version of Node.js, which is evident not only from your log saying `Node: 1.2.0`, but also all the other version details that point at some very old Node.js version.

**Comment by luchillo17** [comment]
Dude... if you look closely at the image in the bottom it shows the output of the `node -v` command, it says `7.8.0`.

**Comment by vitaly-t** [comment]
Dude, if you install Node.js 7.8.0, and output `process.versions`, you will get the following:

```js
{
  http_parser: '2.7.0',
  node: '7.8.0',
  v8: '5.5.372.43',
  uv: '1.11.0',
  zlib: '1.2.11',
  ares: '1.10.1-DEV',
  modules: '51',
  openssl: '1.0.2k',
  icu: '58.2',
  unicode: '9.0',
  cldr: '30.0.3',
  tz: '2016j'
}
```
Now compare it with what you have. Either your installation is broken, or you've got a ghost Node.js installed somewhere in addition, which is the one that tries to run the library.

**Comment by luchillo17** [comment]
Hmm, does it affect if it's runned by the karma testing framework?

**Comment by vitaly-t** [comment]
> Hmm, does it affect if it's runned by the karma testing framework?

It does, if you set it up to run as client-side, which implies the use of the old ES5, not real Node.js environment, which would explain what you are getting. If you want to test this library, you should run run it as a server-side module only.

> Funny thing is it was working... until i hit npm update, had to revert to previous version of this package.

Older version of `pg-promise`? It was [version 5.6.0](https://github.com/vitaly-t/pg-promise/releases/tag/v.5.6.0) that dumped the old Node.js versions.

**Comment by luchillo17** [comment]
Soo i think i now know where's the issue, i'm using a package `karma-nodewebkit-launcher` to be able to run testing in karma, it uses NW.js to simulate node code.

I suspect such package either uses an old version of NW.js that uses an old Node.js version, or NW.js itself has never updated it's NW.js, i'll try and change to an Electron based karma launcher instead, though fixing the version of `pg-promise` to one before 5.6.0 should still work ok.

**Comment by vitaly-t** [comment]
That must be the cause, yes.

**Comment by luchillo17** [comment]
Tested with electron, it runs actually faster and doesn't complain for the node version, thanks for taking the time to answer.
