### ISSUE TITLE
Log queries

### ISSUE THREAD

**Issue by dmnBrest** [vitaly-t/pg-promise#316]
Hello, I need your advice.
How can I debug result queries? Is there any way how to log final query string?
I received error: syntax error at or near "user" for my insert query and I can't find the problem as my query is very simple. So logging would be very helpfull.
(here is my strange string db.query('INSERT INTO user (email, username, password) VALUES(${email}, ${username}, ${password})', user))
Sorry for newbie question, I've just started with your lib.
Thanks

**Comment by dmnBrest** [comment]
Found it so quickly :)
http://vitaly-t.github.io/pg-promise/global.html#event:query
Just need to add "query" event handler.

**Comment by vitaly-t** [comment]
Use either event `query` to log queries globally, or `pgp.as.format(query, values)`, to check locally what you're getting on the output.
