### ISSUE TITLE
Should I rely on ColumnSet.names method in Query Files?

### ISSUE THREAD

**Issue by illarionvk** [vitaly-t/pg-promise#317]
I'm using Query Files in my app to keep the code clean and build verbose queries, e.g. [parents + children tree queries](http://stackoverflow.com/a/39807816).

I rely on [ColumnSet.names](http://vitaly-t.github.io/pg-promise/helpers.ColumnSet.html#names) to provide the column names to the query, but the documentation states the method is for internal use.

Is there a better way or should I continue using `cs.names`?

Query:

```js
var data = {
  'first_name': 'Test',
  'last_name': 'Testing'
}
var cs = new pgp.helpers.ColumnSet(keys(data))
var params = {
  names: cs.names,
  data: pgp.helpers.values(data, cs),
  sets: pgp.helpers.sets(data, cs)
}
db.one(sql.upsertItem, params).then(reply).catch(reply)
```

Query file:

```sql
/* Upsert an item */
INSERT
  INTO items(${names:raw})
  VALUES ${data:raw}
  ON CONFLICT(id)
  DO UPDATE SET
    ${sets:raw},
    updated_at = now()
  RETURNING *
```

**Comment by vitaly-t** [comment]
There is no problem using it this way, the code looks correct. And as for property `ColumnSet.names` being for internal use, it used to be that way, then later on became exposed. Perhaps I should remove that internal use note, to avoid confusion.

Type `ColumnSet` represents most value for multi-row inserts and updates. When you plan only on single-row inserts and updates, its value isn't that great, unless you have lots of columns, and/or need to implement additional logic for manipulating values.

WIll your code work though for multi-row operations? I'm not sure it will, as the sets would need to be prefixed with something like `excluded.`.

Anyway, you are on the right track! :wink:

**Comment by illarionvk** [comment]
My queries have up to 10-12 columns and the number of columns with actual data may vary in partial update requests.

The `data` is a sanitized output from [Joi validator](https://github.com/hapijs/joi), where the defaults are set and some fields are stripped, e.g `created_at`.

With `cs.names` and `pgp.helpers`, I can rely on the `data` object shape to build the query.

I haven't tried to build multi-row operations yet. Thank you for the advice!

**Comment by vitaly-t** [comment]
I've never heard of `joi validator` before. But I suspect, what you do with it, you can di via `ColumnSet` natively, as it uses very flexible column configuration.

**Comment by vitaly-t** [comment]
With the update in [v5.9.0](https://github.com/vitaly-t/pg-promise/releases/tag/v.5.9.0), there is now even easier way to resolve conflicts when the intent it to update `excluded` columns.

One can append `'ON CONFLICT DO UPDATE SET + cs.assign({prefix: 'excluded'})`, and the last part will generate:

```
"excluded".column1 = ${columns1},
"excluded".column2 = ${columns2}
etc...
```
