### ISSUE TITLE
Idiomatic way to perform update with arbitrary data (e.g. strings containing "$8")

### ISSUE THREAD

**Issue by kiejo** [vitaly-t/pg-promise#318]
I want to perform an update query using data which is submitted by the user and which can contain arbitrary content including strings that contain for example `$8` or `${hello}`. I'm trying to get this working using the `helpers.update` function, but I'm facing the following problem.

The code looks similar to this:
```javascript
db.one(pgp.helpers.update({
  content: 'earn $8.00 now',
}, null, 'table') + ' WHERE id = $1 RETURNING id, content', ['id'])
```
This causes the error `RangeError: Variable $8 out of range`.

I can work around the issue with code like this:
```javascript
db.one(pgp.helpers.update({
  content: '$2#',
}, null, 'table') + ' WHERE id = $1 RETURNING id, content', ['id', 'earn $8.00 now'])
```

But this solution does not feel right, especially if you're trying to update many fields. What would be the idiomatic approach to perform such a query? Originally I had expected `helpers.update(data, null, 'table')` to work with arbitrary data, but this does not seem to be the case.

**Comment by vitaly-t** [comment]
Methods like `.insert` and `.update` are expected to generate the final SQL, to be executed directly, not another formatting template. You are doing the same mistake as [this guy](http://stackoverflow.com/questions/39492889/pg-promise-inserting-text-with).

If your formatting parameter is as simple an an integer Id to be appended, you can do:

```js
var update = pgp.helpers.update({
  content: 'earn $8.00 now',
}, null, 'table') + ' WHERE id = ' + id;
db.one(update)
```

And if your condition does require proper escaping, then you should format it separately, and then append the result:

```js
var update = pgp.helpers.update({
  content: 'earn $8.00 now',
}, null, 'table');
var where = pgp.as.format('WHERE id = $1 AND name = $2', [123, 'John']);
db.one(update + where)
```

**Comment by kiejo** [comment]
Thanks for the fast reply. This is very helpful!

**Comment by vitaly-t** [comment]
P.S. Doing single-row updates like this is of little value. It would offer you a cleaner approach just to keep the SQL externally, via [Query Files](https://github.com/vitaly-t/pg-promise#query-files). See also: [pg-promise-demo](https://github.com/vitaly-t/pg-promise-demo).

**Comment by kiejo** [comment]
Using external SQL files is an interesting approach which I'm already using for my database migrations, but I haven't applied it to my application logic queries yet. Thanks for the demo link :) This gives me a better idea of how this looks in real code.
