### ISSUE TITLE
Inserting fails with suspect errors in postgresql log

### ISSUE THREAD

**Issue by dothebart** [vitaly-t/pg-promise#32]
NodeJS v0.10.25 (ubuntu package: nodejs  0.10.25~dfsg2-2ubuntu1 ) 
( libpq5:amd64                         9.4.4-0ubuntu0.14.10 but thats not used afaik? )
against postgresql-9.4.3 server
npm installed:
pg-promise@1.4.3 

var columns = [
    "AGE",
    "I_am_going_to_concerts",
    "I_am_working_in_field",
    "I_like_books",
    "I_like_movies",
    "I_like_music",
    "I_like_specialties_from_kitchen",
    "I_like_watching_movie",
    "I_most_enjoy_good_food",
    "I_mostly_like_listening_to_music",
    "art_culture",
    "body",
    "body_type",
    "cars",
    "children",
    "companies_brands",
    "completed_level_of_education",
    "completion_percentage",
    "computers_internet",
    "education",
    "eye_color",
    "favourite_color",
    "fun",
    "gender",
    "hair_color",
    "hair_type",
    "health",
    "hobbies",
    "hobbies_interests",
    "last_login",
    "life_style",
    "love_is_for_me",
    "marital_status",
    "more",
    "movies",
    "music",
    "my_active_sports",
    "my_eyesight",
    "my_partner_should_be",
    "my_passive_sports",
    "on_pokec_i_am_looking_for",
    "pets",
    "politics",
    "profession",
    "public",
    "region",
    "registration",
    "relation_to_alcohol",
    "relation_to_casual_sex",
    "relation_to_children",
    "relation_to_smoking",
    "relationships",
    "science_technologies",
    "sign_in_zodiac",
    "spoken_languages",
    "sport",
    "the_idea_of_good_evening",
    "travelling"
];
The table is created with this statement:
db.query('create table test_table (id VARCHAR PRIMARY KEY,' + columns.join(" VARCHAR, ") + ' VARCHAR)')

The insert statement is created like this:
    var insertColumns = ['id'];
    var binds = ['$1'];

    for (var i in columns) {
      insertColumns.push(columns[i]);
      var j = parseInt(i, 10) + 2;
      binds.push('$'+ j);
    }
    module.exports.singleWriteQuery = 'insert into Profiles_temp  ('+ insertColumns.join(', ') + ') values(' + binds.join(',')+')' ;

And later on executed with multiple datasets. This one fails:
[ 'P/25720',
  15,
  'zriedkavo. :|',
  'studujem, ale budem pracovat v zdravotnictve. :)',
  'len a len: twilight saga. &lt;3 *-*',
  'komedie, fantasy, rodinne, romanticke. ^^',
  'vsetky. :p',
  null,
  'u priatela, priatelky, v kine. :)',
  null,
  'na posteli, v aute, kedykolvek a kdekolvek, na dobru noc. ^^',
  null,
  '172 cm',
  null,
  null,
  'v buducnosti chcem mat velaaa. *-*',
  null,
  'zakladne. :d',
  59,
  null,
  null,
  'nadherne modre. *-*',
  'biela, cervena, hneda, cierna, modra, zelena. &lt;3',
  null,
  0,
  'hnede, ale chcem to odfarbit na rysave. *-*',
  'dlhe. niekedy rovne, niekedy kucerave. :p',
  null,
  'cestovanie, pozeranie filmov, nakupovanie, stanovanie, fotografovanie, surfovanie po webe, pocuvanie hudby, diskoteky, kino, priatelia. *-*',
  null,
  '2012-05-12 22:14:00.0',
  null,
  'nie je nic lepsie, ako byt zamilovana. :$',<--------------this quote vanishes!
  'cakam na zazrak. :d',
  null,
  null,
  null,
  null,
  'vyborny. ;)',
  'moj najlepsi priatel. ;)',
  null,
  'dobreho priatela, priatelku. :)',
  'psy. ^^',
  null,
  'este nic. :d ale budem zdravotna sestra. :p',
  0,
  'trnavsky kraj, galanta',
  '2011-11-23 00:00:00.0',
  'hmm.. len niekedy pijem. :d',
  null,
  null,
  'nefajcim. ^^',
  null,
  null,
  'blizenci. :)',
  'madarsky!, slovensky, nemecky, anglicky. :d',
  null,
  'zhasnut svetla a meditovat, pocuvat dobru hudbu, surfovat na sieti a chatovat, ist do kina, pozerat dobry film v tv. :)',
  null ]

**Comment by vitaly-t** [comment]
Version 1.4.3 of the library is quite out of date now.

What you are describing looks and sounds exactly like issue #27, which was fixed in version 1.5.0 of the library.

Updating the library to the latest should resolve the issue.

**Comment by dothebart** [comment]
yes, the new version, which indeed works without issues. You've been very busy doing new releases ;-)

**Comment by vitaly-t** [comment]
Since 1.4.3, yes, with 1,706 additions and 1,289 deletions, you could say that :) In fact, the library has been almost rewritten from scratch since 1.4.3, considering the number of changes made.

But that's probably normal for a library that had its first draft published about 4 month ago.

But the good news, the current version is very solid, no known issues. And most importantly, it has 100% test coverage since 1.6.1.
