### ISSUE TITLE
How to identify the source of a long running query

### ISSUE THREAD

**Issue by xiamx** [vitaly-t/pg-promise#320]
Hi!

This is not a bug/issue, but something we encountered in our workflow

Like suggested by pg-promise, we put each SQL query in separate file and use it like this.

```typescript
const query1sql = fs.readFileSync('query1.sql');
const query2sql = fs.readFileSync('query1.sql');
const query3sql = fs.readFileSync('query1.sql');

function query1(params) {
  db.manyOrNone(query1sql, {params}).then(...))
}
function query2(params) {
  db.manyOrNone(query2sql, {params}).then(...))
}
function query3(params) {
  db.manyOrNone(query3sql, {params}).then(...))
}
```

There are queries that warrant optimization, we usually look at `select * from pg_stat_activity` to determine which query takes long. But it would also be nice to know which query (identified by name, i.e. query1.sql, query2.sql) is slowing us down. Our naive proposal so far is to taint each `.sql` file with a comment `-- query1.sql` identifying each one of them. But I wonder if there's a better solution.

Thanks

**Comment by vitaly-t** [comment]
est is to rely on [EXPLAIN](https://www.postgresql.org/docs/9.6/static/sql-explain.html).

Alternatively, you can throw each query in question into its own task, and use [pg-monitor](https://github.com/vitaly-t/pg-monitor) to see how long each task takes.

**Comment by vitaly-t** [comment]
I hope this answers it ;)

**Comment by xiamx** [comment]
awesome thanks for the help :)
I'm going to look into using pg-monitor and task tags.

We do use Query Files internally ;) don't know why I chose to use `fs` in my example :joy:
