### ISSUE TITLE
Soft-deprecated usage of node-postgres?

### ISSUE THREAD

**Issue by jmeas** [vitaly-t/pg-promise#323]
I may be misreading the pg-promise code (there's a quite a bit that goes on between going from requiring node-postgres to actually building a connection!), but it might be that this lib is using a soft-deprecated connection method. tl;dr: [`pg.connect` is soft-deprecated](https://github.com/brianc/node-postgres/issues/1238), and it [looks like this lib is using it here](https://github.com/vitaly-t/pg-promise/blob/a0e21970dc3ee4c6f65ad21455d5006487ec0336/lib/connect.js#L11).

Since this API is undocumented, and slated to be removed eventually, it'll likely be necessary to refactor this at some point.

Switching to the pg-pool API would have additional benefits, too. You could add APIs to allow `pg-promise` to share its pool with other tools. At the moment, even if some other lib accepts a pool argument (rather than making its own pool), pg-promise's pool isn't exposed, so it can't be passed in.

I'm using pg-promise with a separate library, and they're creating two pools.

**Comment by vitaly-t** [comment]
@jmeas everything is explained [here](https://github.com/vitaly-t/pg-promise/issues/206).

And `pg.connect` is the only connection method that exists in v5.1.

**Comment by jmeas** [comment]
Very helpful and informative! Thanks @vitaly-t !

**Comment by vitaly-t** [comment]
@jmeas 

There is [branch 6.x](https://github.com/vitaly-t/pg-promise/tree/6.x) available now, for anyone who is interested :wink:
