### ISSUE TITLE
not in array numbers

### ISSUE THREAD

**Issue by cedvdb** [vitaly-t/pg-promise#324]
I believe there is an issue here. If anything it's not straight forward. I wish to create a query where some results are omitted. To do so I use the following query:

```
`SELECT * 
from tags where 
title like $1
AND id not in ($2)
ORDER BY TITLE ASC
```

I use the following to query:

```
let omit = [4, 5, 5]
return pg.manyOrNone(SELECT_PATTERN_OMIT_SOME, [pattern, omit]);
```

Apparently I can't use an array: 

Error: operator does not exist: bigint <> integer[].

Thus I tried turning it into a string

```
let omit = [4, 5, 5]
return pg.manyOrNone(SELECT_PATTERN_OMIT_SOME, [pattern, omit.toString()]);
```
error (by memory something along the lines of : "4, 5, 5" not a valid integer.

**Comment by vitaly-t** [comment]
You need to use `:csv` (comma-separated values) filter for that:

```sql
SELECT * FROM tags WHERE title LIKE $1 AND id NOT IN ($2:csv) ORDER BY title ASC
```

**Comment by cedvdb** [comment]
Thanks for the quick reply. It wasn't directly obvious to me as I read the part of the doc on array.
