### ISSUE TITLE
Docs should use a different variable delimiter than ${var}

### ISSUE THREAD

**Issue by darknoon** [vitaly-t/pg-promise#325]
At first I thought this was a major limitation of this library, because ESLint was complaining about trying to use an ES6 template literals with 'blah' instead of \`blah\`.

It turns out you can use anything like `SELECT id, name FROM table WHERE id = $(var)`, which is great, I just thought I would have to put a bunch of lines disabling that ESLint warning all over my codebase so it seems like a docs issue.

**Comment by vitaly-t** [comment]
The best / professional approach of working with SQL is via external files / [Query Files](https://github.com/vitaly-t/pg-promise#query-files), and as shown in [pg-promise-demo](https://github.com/vitaly-t/pg-promise-demo). In that context the syntax of `${}` appears to be the friendliest.

It is considered the default syntax, from which you can deviate as you wish, depending on the situation.

I don't think it is worth changing the documentation to an alternative syntax.

**Comment by darknoon** [comment]
@vitaly-t I considered using external `.sql` files but didn't find any information about how to integrate with webpack (I compile the server code as well as the client with webpack before deployment, and currently do not copy any files outside of this bundle).

**Comment by vitaly-t** [comment]
@darknoon How to include external files into Webpack - that's a trivial task, if you research it, lots of people are doing it. I won't even go there, as it is way outside of this library topic.

It seems this discussion has been concluded, so I'm closing the issue.
