### ISSUE TITLE
No way to escape $ in a query

### ISSUE THREAD

**Issue by daveisfera** [vitaly-t/pg-promise#326]
It appears that there's no way to escape a $ in a query when replacing positional arguments. I tried $$, \$ and \\$ and none of them worked.

Here's a sample example to demonstrate the issue:
```
#!/usr/bin/env node

const pgp = require('pg-promise')();
const os = require('os');

const host = process.argv[2] || 'localhost';
const database = process.argv[3] || os.userInfo().username;
const user = process.argv[4] || os.userInfo().username;

const config = { host, database, user };
const db = pgp(config);
db.connect()
.then(() => {
    const values = ['$1.00', '$2.00'];

    return db.none('DROP TABLE IF EXISTS test;')
    .then(() => db.none('CREATE TABLE test (a TEXT, b TEXT, c TEXT);'))
    .then(() => db.none('INSERT INTO test (a, b, c) VALUES ($1, $2, "$3.00");', values));
})
.catch(err => {
    console.log('Error:', err);
});
```

**Comment by vitaly-t** [comment]
You have many problems in your code:

1. Do not use `db.connect()` like that, it is not what the method is there for, see the API
2. Not only you use method `db.connect()`, but you also do even release the connection, a compound error
3. When executing queries in that manner, you are supposed to use a transaction, see [Chaining Queries](https://github.com/vitaly-t/pg-promise/wiki/chaining-queries)
4. For problem you asked about, read this: https://github.com/vitaly-t/pg-promise/issues/318

**Comment by daveisfera** [comment]
Ok, here's the updated code with issues 1-3 resolved:
```
#!/usr/bin/env node

const pgp = require('pg-promise')();
const os = require('os');

const host = process.argv[2] || 'localhost';
const database = process.argv[3] || os.userInfo().username;
const user = process.argv[4] || os.userInfo().username;

const config = { host, database, user };
const db = pgp(config);
db.tx(t => {
    const values = ['$1.00', '$2.00'];

    return t.batch([
        t.none('DROP TABLE IF EXISTS test;'),
        t.none('CREATE TABLE test (a TEXT, b TEXT, c TEXT);'),
        t.none('INSERT INTO test (a, b, c) VALUES ($1, $2, "$3.00");', values)
    ]);
})
.catch(err => {
    console.log('Error:', err);
});
```

For 4, I understand that doing the value replacement is the ideal way of handling things, but is "thou shalt never put values directly in a query" really the stance that pg-promise is taking?

**Comment by vitaly-t** [comment]
> thou shalt never put values directly in a query" really the stance that pg-promise is taking

If you follow the link that I gave you,...you have a formatting template + values, that's what you use to format the final query. You cannot take a resulting query, and then re-use it as a formatting template yet again. It is not what this library does, it is the common sense.
