### ISSUE TITLE
Initializing connections [question]

### ISSUE THREAD

**Issue by elmigranto** [vitaly-t/pg-promise#328]
First of all, thanks for a nice lib :)

I'd like to run some SQL on every created connection before pool considers it as ready. Specifically, I need some `SET` commands executed before any other query.

Haven't found a way to do that, can you help? Thanks.

**Comment by vitaly-t** [comment]
```js
function setupFreshConnection(client) {
    client.query('SET bla-1');
    client.query('SET bla-2');
    client.query('SET bla-3');
}

var pgOptions = {
    connect: (client, dc, isFresh) => {
        if (isFresh) {
            setupFreshConnection(client);
        }
    }
};

var pgp = require('pg-options');
```

**Comment by elmigranto** [comment]
Since `connect` is an event handler, would it be possible for queries to be executed before `setupFreshConnection` runs? I guess not, since `EventEmitter#emit` is usually done on the same tick? Though I am a bit concerned about [surpressing errors part](http://vitaly-t.github.io/pg-promise/global.html#event:connect).

**Comment by vitaly-t** [comment]
> would it be possible for queries to be executed before setupFreshConnection runs

Executed against what? The connection just has been allocated there.

> Though I am a bit concerned about surpressing errors part.

What we do there is basically a hack, it was never meant to be a feature. That's why you cannot throw any error there. But then again, you should not execute there any queries, apart from simple `SET`-s, those should not error out.

**Comment by vitaly-t** [comment]
I trust the question has been answered then ;)

**Comment by elmigranto** [comment]
> The connection just has been allocated there.

[From sources](https://github.com/vitaly-t/pg-promise/blob/master/lib/connect.js#L9), looks like event is "emitted" *after* promise is resolved but I tried to actually run it and it seems to work in correct order, though. Not sure how that happens, tried to figure out proper order of stuff but got a bit lost, maybe later :)

And for errors, I could always `process.reallyExit(1)`.

So yeah, thanks for a prompt reply :)

**Comment by vitaly-t** [comment]
This approach guarantees execution of queries before anything else for fresh connections :wink:

**Comment by danihodovic** [comment]
> This approach guarantees execution of queries before anything else for fresh connections :wink:

That doesn't seem to be the case in the example below:
```
$ cat pg-promise-example.js
'use strict';

const config = require('./config/config.js');

const options = {
  connect: (client, dc, isFresh) => {
    setTimeout(() => console.log('Initializing now'), 10000);
  }
};
const pgp = require('pg-promise')(options);
const db = pgp(config);

db.any('select 1').then(() => console.log('selected 1'));
```
Outputs:
```
$ node pg-promise-example.js
selected 1
Initializing now
```

The use case I need this for is initializing custom type parsers before performing any queries in my application. Specifically I need to execute the query below before any point queries happen:

```
  const customPoint = require('./type-parsers/custom-point');
  const oidSQL = `SELECT oid FROM pg_type WHERE typname = 'geometry'`;
  const { rows } = yield client.query(oidSQL);
  pgp.pg.types.setTypeParser(rows[0].oid, customPoint);
```

I tried putting this code in the `connect` callback, but as seen in the simple example above, the `connect` callback isn't blocking, so other queries may execute before it.

Is there any other workaround for executing arbitrary blocking queries upon initialization?

**Comment by vitaly-t** [comment]
@danihodovic   You can't use `timeout` in that case, that's what breaks your sequence.

**Comment by danihodovic** [comment]
Since the function is asynchronous without a `done()` callback the setup logic may take longer than initial queries. If you have a long running query in the `connect` callback other queries might execute before this is done (as simulated by the timeout).

**Comment by elmigranto** [comment]
I would think queries run in order on connection without multiplexing. E.g. running this will always return `1, 2, 3` in order.

``` js
const result = await Promise.all([
  conn.one('select 1;'), // no waiting
  conn.one('select 2;'), // queue next query right away
  conn.one('select 3;'), // it probably is buffered
]);
```

However, you can't run initialization that depends on query results. You'd have to wrap the library in some way.

<hr />

Once again: I haven't checked sources, so **this is just a guess**.

**Comment by vitaly-t** [comment]
> Since the function is asynchronous

Queries execute in the same order in which they get into the IO. The one in onConnect will always be the first one.

**Comment by danihodovic** [comment]
Ah, so there is a FIFO mechanism when storing pending queries. Neat!

Thanks @vitaly-t and @elmigranto !

**Comment by vitaly-t** [comment]
It depends on the execution pattern, really. If you want to be sure your queries in onConnect are executed first always, you should do something like this:

```js
connect: (client, dc, isFresh) => {
   if(isFresh) {
       client.query('SET 1...;SET 2...;ETC.'); // do fail-proof concatenated queries only!!!! to guarantee their all preceed everything else.
   }
}
```

**Comment by danihodovic** [comment]
My concrete use case is to set a custom point type parser before any other queries are executed. 

```
const init = Bluebird.coroutine(function * (client) {
  // Oids varies so we need to query it instead of hardcoding it.
  const oidSQL = `SELECT oid FROM pg_type WHERE typname = 'geometry'`;
  const { rows } = yield client.query(oidSQL);
  pgp.pg.types.setTypeParser(rows[0].oid, point);
  pgParseFloat(pgp.pg);
});

const options = {
  promiseLib: Bluebird,
  connect: (client, dc, isFresh) => {
    if (isFresh) {
      init(client);
    }
  }
};
```

Is the point parser guaranteed to be set-up before any other query executes?

**Comment by vitaly-t** [comment]
1) You can use ES6 generators within `connect`
2) You should call `setTypeParser` in the beginning, not during queries.

**Comment by danihodovic** [comment]
> 1. You can use ES6 generators within connect
Could you provide an example based on the above code?

> 2. You should call setTypeParser in the beginning, not during queries.
This is not possible in my use case since the oidc number varies between our Postgres instances. So it has to be queried for dynamically and set after the query is executed.

**Comment by vitaly-t** [comment]
[Version 8.4.0](https://github.com/vitaly-t/pg-promise/releases/tag/v.8.4.0) affects the functionality described here.
