### ISSUE TITLE
Query values as object containing another object

### ISSUE THREAD

**Issue by LoiKos** [vitaly-t/pg-promise#329]
Hello,

```javascript
var obj = {
 name: "value"
picture: "value"
}

db.one("update table name set (${obj~}) = (${obj.values}) where id = ${id} returning *",{
obj:obj,
id:id
}) 

```
I'm trying to understand how i can deal with this data to catch the value of name picture containing in obj. There is no problem retrieving keys.

Do you have an idea ?

**Comment by vitaly-t** [comment]
What is the final SQL string that you are expecting?

**Comment by LoiKos** [comment]
to be sure you understand my need i give you 2 examples :

``` javascript
var obj = {
     name: "$1",
     picture: "$2"
}
```
```sql
update tablename set ("name","picture") = ('$1','$2') where id = myid returning *
```
============
``` javascript
var obj = {
     firstname: "$1",
     lastname: "$2"
     picture: "$3"
     email: "$4"
     phone: "$5"
}
```
```sql
update tablename set ("firstname","lastname","picture","email","phone") = ('$1','$2','$3','$4','$5') where id = myid returning *
```

My need it to adapt the request to an object data. 
`(${obj~})` does the job to get keys but passing the obj in another object make it impossible to retrieve values and i can't add id to obj because it make no sense.

**Comment by vitaly-t** [comment]
> update tablename set ("name","picture") = ('$1','$2') where id = myid returning *

> update tablename set ("firstname","lastname","picture","email","phone") = ('$1','$2','$3','$4','$5') where id = myid returning *

Those two represent your final query? I don't get it. Are you trying to insert variable names into the database?

**Comment by vitaly-t** [comment]
Maybe you are having some misunderstanding similar to this: #318

**Comment by LoiKos** [comment]
Sorry I see,

``` javascript
var obj = {
     firstname: "Jean",
     lastname: "Jean"
     picture: "https://www.w3schools.com/css/img_fjords.jpg"
     email: "jean.jean@gmail.com"
     phone: 333
}
```
```sql
update tablename set ("firstname","lastname","picture","email","phone") = ('Jean','Jean','https://www.w3schools.com/css/img_fjords.jpg','jean.jean@gmail.com',333) where id = myid returning *
```

**Comment by LoiKos** [comment]
I wasn't trying to insert variable i choose bad name sorry

**Comment by vitaly-t** [comment]
The simplest is to throw your `myid` into the same object:
```js
obj.id  = 123;
```

Then you can write your query:
```js
db.one('UPDATE tablename SET firstname = ${firstname}, lastname = ${lastname}, picture=${picture}, email = ${email}, phone = ${phone} WHERE id = ${id}', obj);
```

**Comment by LoiKos** [comment]
Okay i see,
Thanks !
