### ISSUE TITLE
Detached transaction using results from one query for remainder queries

### ISSUE THREAD

**Issue by Maximization** [vitaly-t/pg-promise#33]
Hi Vitaly,

First of all let me say a big thank you to you for the time and effort you've spend creating this library. The documentation is well-written. I'm surprised to see so few stars but I'm sure it will gain a lot of traction in the near future.

I have one specific use case which I can't seem to resolve. I have a detached transaction starting with a query returning one result and several subsequent queries which make use of that result. It seems like a simple task but I couldn't find guidance in any of the examples. I'm not a promise expert either so that doesn't help. Here's an example of what I have:

```javascript
db.tx(function (t) {
    return t.one('INSERT INTO table1(col1) VALUES($1) RETURNING id', [123])
        .then(function (data) {
            return promise.all([
                t.none('INSERT INTO table2(col1, col2) VALUES($1, $2)', [data.id, "John"]),
                t.none('INSERT INTO table2(col1, col2) VALUES($1, $2)', [data.id, "Mary"])
            ]);
        });
})
    .then(function (data) {
        // Success, do something with data...
        return res.status(200).json(data);
    }, function (reason) {
        // Error
        return res.json(reason);
    });
```

As you can use I use the result from the first query in subsequent queries. I also use this result after the transaction resolves successfully. What am I doing wrong here?

**Comment by vitaly-t** [comment]
The following line makes no sense:
```javascript
    return t.one(function ( 'INSERT INTO table1(col1) VALUES($1) RETURNING id', [123])
```
In fact, it won't even compile. That's invalid JavaScript syntax altogether.

**Comment by Maximization** [comment]
Made a typo there, shouldn't be a function. Original post edited.

**Comment by vitaly-t** [comment]
Ok, this way it looks fine. What error are you getting?

**Comment by Maximization** [comment]
None as a matter of fact. The rows are inserted fine in the db but the transaction as a whole never resolves. Neither of these execute

```
.then(function(data) {
    // Success, do something with data...
    return res.status(200).json(data);
  }, function(reason) {
    // Error
    return res.json(reason);
  });
```

Does it have anything to do with the fact that I have those two queries inside the first one?

**Comment by vitaly-t** [comment]
That's not possible, at least of them has got to be executing.

I just tested this whole piece of code locally, and it worked just fine.

Add `console.log("DATA", data)` and `console.log("REASON", reason)` in the corresponding result sections. One of them has got to execute there.

**Comment by Maximization** [comment]
You're right, the success promise does execute.

However, I get undefined for console.log(data). That's preventing returning a success status back to the client. I was manipulating the data which I didn't have. Do you know how I could get the result from the first query passed all the way to the end?

**Comment by vitaly-t** [comment]
As I mentioned above, the design of your transaction is such, it expects to be resolved with `[ undefined, undefined ]`, which is what `promise.all` returns when successful.

If you need something else, then resolve with the data you need:

```javascript
db.tx(function (t) {
    return t.one('INSERT INTO table1(col1) VALUES($1) RETURNING id', [123])
        .then(function (data) {
            return promise.all([
                t.none('INSERT INTO table2(col1, col2) VALUES($1, $2)', [data.id, "John"]),
                t.none('INSERT INTO table2(col1, col2) VALUES($1, $2)', [data.id, "Mary"])
            ])
                .then(function () {
                    return promise.resolve(data.id);
                });
        });
})
    .then(function (data) {
        // Success, do something with data...
        return res.status(200).json(data);
    }, function (reason) {
        // Error
        return res.json(reason);
    });
```

This is really, a question about promises and how they work, not so much about this library, which just uses promises.

**Comment by Maximization** [comment]
It works indeed, thanks a lot.

You're right, in the end it was a promise related issue rather than anything with this library. Thank you for you quick response. Keep up the good work.

**Comment by vitaly-t** [comment]
You are welcome, and thank you for your support! :)

**Comment by vitaly-t** [comment]
P.S. That's because the first draft was published just 4 month ago, while code coverage was added only 3 weeks ago, so it is simply a very young library. So hopefully, yes, it will get noticed later :)

> I'm surprised to see so few stars but I'm sure it will gain a lot of traction in the near future.

**Comment by vitaly-t** [comment]
@Maximization just as an update, we found [some issues](https://github.com/vitaly-t/pg-promise/issues/40) related to the use of `promise.all` for executing a batch of queries.

Since then the library received a much better, internal implementation for this: [batch](https://github.com/vitaly-t/pg-promise/blob/master/API.md#module_pg-promise.Task+batch), which is now the recommended way for executing a batch of queries within tasks and transactions.

**Comment by Maximization** [comment]
@vitaly-t Thank you for the heads up. I read through the discussion and it can indeed be quite dangerous in certain cases. I've updated to latest and started using batch in all new transactions. Will refactor old transactions asap too.

Keep up with the good work!

**Comment by BeeDi** [comment]
I would like to thank you both, @vitaly-t for this great library & @Maximization for his question. 
I have found in your conversation very good answers to my own questions. 

@vitaly-t  would you consider adding your example concerning the use of a transaction intermediate data to the documentation ?

**Comment by vitaly-t** [comment]
@BeeDi the information provided here is now obsolete, and is not correct in relation to the current version of the library.

One must never use `promise.all` anymore, only `t.batch` method, as shown in all examples.

**Comment by wprudencio** [comment]
End if I have a loop?

```javascript

for (let city in fileContent.Sheets) {
    if (fileContent.Sheets.hasOwnProperty(city)) { // This kind of check must be executed as good practice
        let citySheet = fileContent.Sheets[city];

        db.one("insert into common_city(name, state_id, time_zone_id) values($1, $2, $3) returning id", [city, 5, 2])
            .then(function(data) {
                console.log(`--> Created city "${city}";`);

                for (let row in citySheet) {
                    if (citySheet.hasOwnProperty(row) && citySheet[row].hasOwnProperty("v") && citySheet[row].v !== city) {
                        let neighborhood = citySheet[row].v;

                        db.none("insert into common_neighborhood(city_id, name) values($1, $2)", [data.id, neighborhood])
                            .then(function() {
                                console.log(`----> Created neighborhood "${neighborhood}" from city "${city}";`);
                            })
                            .catch(function(error) {
                                console.log(`Error creating "${neighborhood}" from "${city}": ${error.message || error};`);
                            });
                    }
                }
            })
            .catch(function(error) {
                console.log(`Error creating "${city}": ${error.message || error};`);
            });
    }
}

```

Should I put 'db.tx(function (t)' inside loop?

**Comment by vitaly-t** [comment]
> Should I put 'db.tx(function (t)' inside loop?

No, you should put the loop inside `db.tx`.

**Comment by kundan1047** [comment]
`db.any('SELECT sdo_id FROM mdas_discom_sdo_master WHERE discom_id = $1 OR circle_id = $1 OR zone_id = $1 OR division_id = $1 OR sdo_id = $1', ['ZNE12'])
        .then(function(dat){
            var send_data = [];

            async.each(dat, function(val, callback){
                db.any('SELECT DISTINCT a.com_seq, a.acct_id, a.description, a.status, c.com_status_name, a.inserted_by, a.inserted_date, a.com_id, a.sdo_code, b.category FROM mdas_user_complaint a, mdas_complaint_master b, mdas_complaint_status_master c WHERE a.sdo_code = $1 AND a.com_id = b.com_id AND b.status = $2 AND a.status = c.com_status_val ORDER BY a.com_seq, a.inserted_date DESC', [val.sdo_id, 'Y'])
                .then(function(data){
                    
                    if(Object.keys(data).length == 0){
                        callback();
                    }
                    else{
                        var i = 0;
                        data.forEach(function(item){
                            send_data.push(item);
                            i++;
                        })

                        if(i == (data.length)){
                            callback();
                        }
                        else{
                            setTimeout(function(){
                                if(i == (data.length)){
                                    callback();
                                }
                            }, 2000)
                        }
                    }
                })
                .catch(function(error){
                    console.log(error);
                    
                })
            }, 
            function(err, result){
                if(err){
                    console.log(err);
                }
                else{
                    console.log(send_data);
                    console.log(send_data.length);
                    console.log(d.getMilliseconds());
                    
                }
            })
        })
        .catch(function(error){
            console.log(error);
            
        })`


and query with db.task

`db.task(t => {
    return t.many('SELECT sdo_id FROM mdas_discom_sdo_master WHERE discom_id = $1 OR circle_id = $1 OR zone_id = $1 OR division_id = $1 OR sdo_id = $1', ['ZNE12'])
        .then(dat => {
            console.log(dat.length);
            var queries = dat.map(val => {
                return t.any('SELECT DISTINCT a.com_seq, a.acct_id, a.description, a.status, c.com_status_name, a.inserted_by, a.inserted_date, a.com_id, a.sdo_code, b.category FROM mdas_user_complaint a, mdas_complaint_master b, mdas_complaint_status_master c WHERE a.sdo_code = $1 AND a.com_id = b.com_id AND b.status = $2 AND a.status = c.com_status_val ORDER BY a.com_seq, a.inserted_date DESC', [val.sdo_id, 'Y']);
            });
            return t.batch(queries);
        });
})
    .then(data => {
        console.log(data[0])
        console.log(data[0].length)
        console.log(d.getMilliseconds())
    })
    .catch(error => {
        console.log(error)
    });`


But the first one is running much faster than the second one
