### ISSUE TITLE
Option to escape backslashes?

### ISSUE THREAD

**Issue by AriaFallah** [vitaly-t/pg-promise#332]
The database I'm working with currently has `standard_conforming_strings` off, which means that I need to escape backslashes i.e. make `\` into `\\`.

Is there any feature in pg-promise that does this for me, or will I have to do it myself? For example in the following code:

```js
const postgres = require('pg-promise')

const pgp = postgres()
const db = pgp({
  host: 'localhost',
  port: '5432',
  user: 'test',
  database: 'postgres',
  password: ''
})


const cs = new pgp.helpers.ColumnSet(['a', 'b'])
const table = new pgp.helpers.TableName('test', 'public')
const data = [{
  a: '\\',
  b: 'test'
}, {
  a: 'hi',
  b: 'there'
}]

const insert = pgp.helpers.insert(data, cs, table)

db.none(insert)
  .then(() => console.log('success!'))
  .catch((err) => console.log(err))
  .then(pgp.end)
```

The generated insert statement is

```
insert into "public"."test"("a","b") values('\','test'),('hi','there')
```

with the `\` not escaped.

**Comment by vitaly-t** [comment]
I never heard of such a thing before. I will have to escape such special cases manually.

But if you have a special column within `ColumnSet`, you can define such column as:

```js
{name: 'columnName', init: c => c.value.replace(/\//g, '\/\/')}
```

**Comment by AriaFallah** [comment]
@vitaly-t 

Alright, thank you!

Also I'm not surprised you haven't heard of it, because if you `ctrl-f` for `standard_conforming_strings` [here](https://www.postgresql.org/docs/9.1/static/runtime-config-compatible.html) you'll see that since `9.1`, ~6 years ago, it's defaulted to `on` instead of `off`.

> This controls whether ordinary string literals ('...') treat backslashes literally, as specified in the SQL standard. Beginning in PostgreSQL 9.1, the default is on (prior releases defaulted to off). Applications can check this parameter to determine how string literals will be processed. The presence of this parameter can also be taken as an indication that the escape string syntax (E'...') is supported. Escape string syntax (Section 4.1.2.2) should be used if an application desires backslashes to be treated as escape characters.

Also as a side note, perhaps [dollar-quoting](https://www.postgresql.org/docs/current/static/sql-syntax-lexical.html#SQL-SYNTAX-DOLLAR-QUOTING) could be the solution to escaping issues.

**Comment by vitaly-t** [comment]
Related: https://stackoverflow.com/questions/44389063/postgresql-returning-fails-with-regexp-replace
