### ISSUE TITLE
[question] Best practice to access multiple databases

### ISSUE THREAD

**Issue by aberenyi** [vitaly-t/pg-promise#333]
Hi there,

I was wondering what is the "official" way to query multiple databases (hosted by a single server) and avoid [WARNING: Creating a duplicate database object for the same connection](https://github.com/vitaly-t/pg-promise/wiki/FAQ#warning-creating-a-duplicate-database-object-for-the-same-connection)?

I've found #1, #175 and a couple of references on SO (e.g. [this one](https://stackoverflow.com/questions/44096522/get-executed-sql-statement-from-pgpromise-query-result)), but I'm still not convinced what is the best way to implement this functionality - ` noWarnings: true` seems a bit cheeky :)

I guess I could just go ahead with multiple [pools](https://github.com/brianc/node-pg-pool) (with a relatively low max value) or some sort of a caching mechanism (a possible solution is mentioned here https://github.com/vitaly-t/pg-promise/issues/175#issuecomment-271969662, however, I am keen to know what would you suggest for such a use case?
Also, it is a bit unclear how to utilise [$dc](http://vitaly-t.github.io/pg-promise/Database.html#.$dc) for this.

Cheers

**Comment by vitaly-t** [comment]
When you create one `db` per database connection, you are not going to get the warning. So what is really the question then?

**Comment by aberenyi** [comment]
Sorry if I wasn't clear enough, nevertheless you've answered my question.

I've gone ahead with a small wrapper class and a cache.

```js
const dbCache = new Map()

export class PostgreSQL
{
  db: IDatabase<IExtensions>&IExtensions
  constructor({dbName = defaultDbName}: {dbName?: string} = {})
  {
    const connObj: IPgConnObj = config.pgConnObj
    connObj.database = dbName

    const {host, port, database, user} = connObj
    const dbKey = JSON.stringify({host, port, database, user})

    if (dbCache.has(dbKey))
    {
      this.db = dbCache.get(dbKey)
    }
    else
    {
      const pgpOptions =
      {
        capSQL: true,
        pgFormatting: true,
        pgNative: true,
        extend: (obj: any) =>
        {
          obj.close = () => obj.$config.pgp.end()
        }
      }
      const pgp: IMain = pgPromise(pgpOptions)
      this.db = <IDatabase<IExtensions>&IExtensions>pgp(connObj)
      dbCache.set(dbKey, this.db)
    }
  }
}
```

Thanks.

**Comment by vitaly-t** [comment]
I don't know if a wrapper is necessary.

See:

* [pg-promise-demo](https://github.com/vitaly-t/pg-promise-demo)
* [where to initialize](https://stackoverflow.com/questions/34382796/where-should-i-initialize-pg-promise)
