### ISSUE TITLE
Does this library work with pg-copy-streams?

### ISSUE THREAD

**Issue by napalm272** [vitaly-t/pg-promise#34]
If so, can you provide an example please?  Thank you.

**Comment by vitaly-t** [comment]
Hard to say, given that [pg-copy-streams](https://github.com/brianc/node-pg-copy-streams) has non-existing support. According to its build history, it hasn't built successfully for the last year.

**Comment by vitaly-t** [comment]
@napalm272 
**UPDATE** Version 2.0 of the library will have support for streams as implemented by libraries [node-pg-query-stream](https://github.com/brianc/node-pg-query-stream) and [node-pg-copy-streams](https://github.com/brianc/node-pg-copy-streams).
