### ISSUE TITLE
Examples for Update queries using named parameters

### ISSUE THREAD

**Issue by jdalrymple** [vitaly-t/pg-promise#340]
I cant seem to figure this out i've tried something like:

```
  const obj =  {prop1: "a", prop2:"b"}
  const query = 'UPDATE tableName SET ($<this~>) = ($<prop1>, $<prop2>)';

  await db.none(query, obj);

```
but I cant seem to get it to work. Any ideas?

**Comment by vitaly-t** [comment]
Your `UPDATE` has invalid SQL syntax.

**Comment by jdalrymple** [comment]
How so? 

basic syntax:
`UPDATE table SET (cola, colb) = (4, 6)`

Using a similar named params seen here: 
```
var obj = {
    one: 1,
    two: 2
};

format('INSERT INTO table(${this~}) VALUES(${one}, ${two})', obj);

```
but attempting to do the similar object replacement technique in an Update command.

**Comment by vitaly-t** [comment]
What error are you getting?

**Comment by jdalrymple** [comment]
Played with it a little longer, figured it out. I think i was sending an incorrect type for the where clause, though the error never pointed to it. My bad! 

Thank you for the help :D

**Comment by vitaly-t** [comment]
@jdalrymple Very good, I thought it was something like that :smile:
