### ISSUE TITLE
Make library initialization optional

### ISSUE THREAD

**Issue by demurgos** [vitaly-t/pg-promise#345]
Hi,
I am currently interested in using this library, but the fact that this library is stateful makes it hard to integrate. I cannot access static properties that do not depend on the initialization options (root namespace) unless I create an instance of the library, and this initialization pattern is a bit awkward. This is not the only library that uses an initialization step, but usually this step is optional.

One of the main issues with the fact that the root namespace is not exposed as part of the main module but requires initialization is that it does not play well with ES6 imports.

Here is an example that does not work:
```javascript
import {txMode} from "pg-promise";

export const myTxMode = new txMode.TransactionMode({...});
```

Currently I need to either wrap the construction it in a function and pass a reference to pgp (some small dependency injection) or require my own pg-promise factory, instantiate it, get txMode and then throw away this instance of the library.

```javascript
// Pass the initialized library as an argument, but now I cannot do `import {myTxMode} from ...`
// (the "stateful-ness" propagates)
export function(pgp) {
  return new pgp.txMode.TransactionMode({...});
}
```

```javascript
// This works, but unless you know pg-promise, it is not obvious that txMode is independant
// of the initialization.
import pgpFactory = require("pg-promise");
const pgp = pgpFactory();
const txMode = pgp.txtMode;

export const myTxMode = new txMode.TransactionMode({...});
```

What I'd recommend is to use an approach similar to [Request](https://github.com/request/request). The main module exported by request is an instance of the library configured with the default values. If you want a custom version with a special configuration, you can do it by calling a function on the exported object (`.options`) and it will return you a new instance that does modify the original instance of the library.

You already have a good architecture to implement this sort of feature because all the configuration is injected by the main module so it should be pretty easy to implement.

For compatibility, the call function of the main module should still be the factory function that produces instances of the library. The call operator is the only the only conflict between the "interfaces" of the "library factory" and "library instance". The functions have distinct signatures so it could be possible to determine determine which behavior to do (create a library instance or connect to a database) but determining the type of behavior by checking the options object adds a lot of complexity. I'd recommend an easier solution: adding a method `createDatabase` to library instances, this function would simply create a db (just like `require("pg-promise")()()` does currently) and would be accessible from the main module. Just for consistency, and to make "pg-promise" compliant with strict ES modules (the exported object cannot be a function), I'd also add a `.options` method that is simply an alias for the factory function.

Here is an example of how it would work:

```javascript
const pgPromise = require("pg-promise");

assert(pgPromise.txMode !== undefined); // members of rootNamespace directly exposed
pgPromise.spex; // Spex with default initialization
pgPromise.helpers; // helpers with default initialization
// Create a db, with default initialization, can be used as usually
const defaultDb = pgPromise.createDatabase({/* IConfig */}); 

// Call on main module still works and produces an initialized library
const initializedPgPromise = pgPromise({/* IOptions */});
// Alias initialization that does not involve a call on the main module
const initializedPgPromise2 = pgPromise.options({/* IOptions */});
// It still produces a new object, it does not mutate the default context
assert(pgPromise !== initializedPgPromise);
assert(pgPromise !== initializedPgPromise2);

// A call to the function still creates a database
const initializedDb = initializedPgPromise();
// The same method as for the default object is available (equivalent to the line above)
const initializedDb2 = initializedPgPromise.createDatabase();

// This pattern would also allow successive initializations. For the moment I'd throw an error
// until this behavior is better specified
const overInitializedPgPromise = initializedPgPromise.options({/* IOptions */});
```

This a feature I'd be happy to work on and send a PR.

**Comment by vitaly-t** [comment]
This is a lot of assumptions, and as it happens, they are not correct.

At the center of this library is the [Database] object, which is what meant for integration with other libraries. And specifically for that purpose it exposes property [$config] that gives you access to everything in the library, including its initialized instance - `$config.pgp`.

[Database]:http://vitaly-t.github.io/pg-promise/Database.html
[$config]:http://vitaly-t.github.io/pg-promise/Database.html#.$config

**Comment by demurgos** [comment]
With all respect, could you point out which are my wrong assumptions?

To get a reference to a database, you need two calls. One to initialize the library, one to configure the database. This issue is about removing the initialization step of the library.

```javascript
// Currently:
var db = require("pg-promise")({promiseLibrary: Bluebird})("pg://localhost/db");
// Proposed:
var db = require("pg-promise").createDatabase("pg://localhost/db");
```

I am fully aware of the two integration methods to get a reference for the central **Database** object. These two methods and the hybrid approach are the best to get a reference for a Database object.
These steps make sense for a stateful object such as the Database.

This issue is about accessing an instance of the main **pgPromise** object. Since this object currently requires an initialization step, I also have to either pass it as a parameter or initialize my own instance.

The two problems caused by the required library initialization are:
- Passing a reference or initializing my own pgPromise library instance when I only want access to static properties from the root namespace does not make sense.
- This is cumbersome when I do not want to provide custom initalization and just want to create a database

I differentiate three things:
- The factory function: what I get from: `var factory = require("pg-promise");`
- The library instance: what I get by calling the factory function: `var pgp = factory();`
- The database instance: what I get by calling the library instance: `var db = pgp("pg://...")`

**Comment by vitaly-t** [comment]
What you are suggesting isn't possible, the library needs to initialize itself before it can start creating database objects.

One of the most important, global initialization parameters are `promiseLib` and `pgNative` that affect how everything else works.

The library was implemented is for a good reason, considering the logic of the existing driver, its connection pool, promises and other parameters.

**Comment by demurgos** [comment]
> What I'd recommend is to use an approach similar to Request. The main module exported by request is an instance of the library configured with the default values. If you want a custom version with a special configuration, you can do it by calling a function on the exported object (.options) and it will return you a new instance that does modify the original instance of the library.

Why wouldn't a similar approach be possible for this library? With defaults using the system `Promise` and `pgNative` being false? It would match the hybrid approach you described in the Wiki page but applied for the whole library: pass parameters or rely on defaults, there's no real difference.

There would be some other changes, but the main one would be to replace [the main export](https://github.com/vitaly-t/pg-promise/blob/master/lib/main.js#L348) by:
```javascript
const default = $main();
$npm.utils.addReadProperties($main, default);
$npm.utils.addReadProperty($main, "createDatabase", () => default());
module.exports = $main;
```

**Comment by vitaly-t** [comment]
> Why wouldn't a similar approach be possible for this library? With defaults using the system Promise and pgNative being false?

This library was designed and implemented when such thing as ES6 Promise didn't exist, and required a promise library to be explicitly specified always.

Some other of its aspects also refer to the legacy design aspects.

I did consider changing the initialization approach, but it would always result in a major breaking change, and I never liked the idea for a library with such huge user base. May be some day though.

**Comment by demurgos** [comment]
Thank you for your time on this.
I was using the `pg` package for a long time and wanted to upgrade to your package because it has many interesting features: it's way more than just "`pg` with promises".

If I remember well, even when ES6 Promises did not exist, the mongodb driver shipped with `q` and let you override it if you want. The reason why I opened this issue is that your library no longer has any required initialization option so it _could_ provide a default. Now, I understand that you are busy working on the next version, but would you be interested by a PR bringing this feature? It could be for a next major version eventually, but I guarantee that this would allow to simplify the work with your library (see the example in my first message where you could define free-floating transaction functions).
Still, I know that it wouldn't be as easy: having a very tight control over the instances of your components brings guarantees that could be challenged otherwise (its mainly about the reliability of the `instanceof` operator).

Overall, it's not that I do not want to track my references, but because I feel that this kind of architecture where you have to pass references creates dependencies that tend to be harder to reason about. My example with a custom transaction mode needing a reference to the pgp object is a "plugin" problem similar to the one encountered by grunt, gulp, webpack, etc. These have three approaches:
- Grunt tasks are factory functions that take a reference to the current grunt instance. They are highly tight to grunt and work similarly to the method currently available to expose a custom transaction mode consumable by pg-promise. 
- Gulp tasks do not depend on gulp, they are simple functions that work on vinyl files. It is closer to the use of conventions / structural typing. The identity of the parameters do not matter as long as they provide the right interface. You can reuse them outside of gulp (this file abstraction is pretty handy). This is the kind of architecture I am more fond of.
- Webpack's plugin management is more oriented on "peers". This is the third way to deal with references (not mentioned previously): have a single `db.js` file and rely on the cache of Node's resolution algorithm to always get the valid reference. Works fine for the top level package, not so well when trying to compose multiple small packages (I consider peer-dependencies an anti-pattern for node).

The grunt way is already well working with this library, I'd like a more gulp'y way, the webpack way is fine for top-level consumers.

**Comment by vitaly-t** [comment]
> but would you be interested by a PR bringing this feature?

Sorry, but presently I cannot accept a PR with such breaking changes. It would have to be a new major version, with some major changes in functionality and documentation, for which I do not have the time.

I will wait till matters with the 6.x branch to finalize before looking at it again.

And thank you for all other considerations you've made here! 👍

**Comment by vitaly-t** [comment]
I take it this subjected has exhausted itself, so I'm closing it for now.

B.t.w., if you want the best form this library, I suggest that you use [pg-monitor](https://github.com/vitaly-t/pg-monitor) from the beginning :wink:

**Comment by quanganhtran** [comment]
Now that we are already at major version 10, would you consider revisiting this topic?

I think all the for and against arguments have been presented above, so I would like to just add some of the anecdotal frictions I stumbled into when working with `pg-promise` stateful library instance:

- Initializing the library at application main requires passing the library down to dependencies. OTOH, initializing it in a userland module makes that module side-effectful itself.
  - I suppose one approach would be to run a memoized init wrapper every time, for _every_ namespace access. If the library is already initialized then return a stable reference. At least then initialization is opaque to the dependencies.
- Helpers can be accessed through `db.$config`, but through checking the source I don't think it requires an actual database connection. When trying to encapsulate query builder functions into a module it is awkward to require `Database` to be able to format strings.
  - As a side note perhaps helpers can just be a root namespace instead (the protocol locking can get in the way and I have not yet thought too much about workarounds but would not quickly consider it impossible).
