### ISSUE TITLE
Async await

### ISSUE THREAD

**Issue by fibo** [vitaly-t/pg-promise#347]
I am using pg-promise in production with Redshift since more than one year ago and it works great, thank you for sharing this awesome package.

My question is the following: is it possible to use pg-promise with async await? Are there some examples online?

If not, I will try by myself and publish an article about this topic I can share.

**Comment by dustincjensen** [comment]
I haven't tried it myself, but any call that returns a promise can be converted to async/await assuming you are using a version of Javascript or Typescript that supports it. I don't know the versions off by heart, but here is an example (from the examples)...

```
db.any('SELECT * FROM users WHERE active = $1', [true])
    .then(function(data) {
        // success;
    })
    .catch(function(error) {
        // error;
    });
```

Would translate to...

```
try {
    let data = await db.any('SELECT * FROM users WHERE active = $1', [true]);
} catch (error) {
    // error
}
```

**Comment by vitaly-t** [comment]
ES7 `async`/`await` supports promises automatically, out of the box.

Lots of developers have been using it via Babel for a long time. And since Node.js 7.6 the `async`/`await` is available by default.

**Comment by fibo** [comment]
Cool!

Thank you for confirm me that this new awesome feature will work out of the box, it would be a pretty hard work to refactor the code base but it is worth to increase the readability and for other reasons.

It looks like an happy ending of the JavaScript fatigue :)

**Comment by vitaly-t** [comment]
On the final note, the real value of the new `async`/`await` syntax is when executing more than one query at a time.

When executing just one query, you typically use the root `db` object, with one `.then` and `.catch`, which isn't any worse or better than using a `try` / `catch` syntax that you have otherwise.

But when executing more than one query at a time, you are supposed to use tasks (see [Chaining Queries](https://github.com/vitaly-t/pg-promise/wiki/chaining-queries)), which automatically gives you access to the callback that can use the new syntax:

```js
db.task(async (t) => {
    let a = await t.any('SELECT...1');
    let b = await t.any('SELECT...2');
    return {a, b};
})
  .then(data =>{
  })
  .catch(error=>{
  });
```

And this is how the new syntax should be used :wink:

**Comment by fibo** [comment]
Ok, I will try that syntax, thank you for the hint.

**Comment by pawelfus** [comment]
Thanks for the example @vitaly-t !

Any pros/cons over using this syntax? 
```javascript
try {
 return await db.task(async (t) => {
    let a = await t.any('SELECT...1');
    let b = await t.any('SELECT...2');
    return {a, b};
  });
} catch (err) {
  logger.error(err);
}
```

**Comment by gvaartjes** [comment]
Tested fully now. The problem was that the unit_test was testing this pattern, and of coursenever works! (obviously)
Because it immediately returns the promise

```ts
const test = (): Promise<void> => {
  try {
     return Promise.reject('raise-error');
  } catch (error) {
    console.log('errrorrr')
  }
}
```

**Comment by gvaartjes** [comment]
For documentation's sake
```ts
import dotenv from 'dotenv';
// Set environment variables from .env in root folder
dotenv.config();
import { ITask } from 'pg-promise';
import { db } from '../src/db/index';
import { User } from '../src/@types/model.types';

console.log('env pg-user', process.env.PGUSER);

const createKeyForGuestForOneLock = async function(
  tx: ITask<any>,
  id: number
): Promise<User> {
  const u1 = await tx.one('SELECT * from users where id = $1', [id]);
  const u2 = await tx
    .none('SELECT * from users where id = $1', [id])
    .catch(e => {
      throw new Error('user-error'); // THIS WILL THROW, THERE IS A USR FOUND.
    });
  return u1;
};

const _createKeysForGuest = async (
  tx: ITask<any>,
  userIds: number[]
): Promise<User[]> => {
  // create and save keys for the locks, for this message
  const userQueries: Promise<User>[] = [];
  for (const id of userIds) {
    // the message needs access to one or more locks
    // In this loop create a key + key_operation for one message
    userQueries.push(createKeyForGuestForOneLock(tx, id));
  }

  return tx.batch(userQueries);
};

const createKeysForGuest = async (
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  userIds: number[]
): Promise<User[]> => {
  return db.tx('create-key-for-guest', async tx => {
    return _createKeysForGuest(tx, userIds);
  });
};

//test2();
const test = async (): Promise<User[]> => {
  try {
    // return createKeysForGuest([1, 2, 3]);  // THIS RETURNS THE PROMISE AND WILL NOT BE CATCHED BY TRY-CATCH
    const users = await createKeysForGuest([1, 2, 3]); // THIS WILL TRIGGER THE CATCH IF-ERROR
    console.log(JSON.stringify(users));
    return users;
  } catch (error) {
    // THIS WILL NEVER BE CATCHED, BECAUSE OF THE RETURN!!
    // THIS WILL WORK IF WE AWAIT THE PROMISE
    console.log('MY ERRRRR!');
    throw new Error('catch-me-if-you-can');
    //console.error(error);
  }
};

const t: any = test()
  .then(d => {
    console.log('ok');
  })
  .catch(e => {
    console.error('catched-or-not');
  });
```

**Comment by vitaly-t** [comment]
@pawelfus Nope. What makes you think there would be some cons?

**Comment by gvaartjes** [comment]
Because of me... ;) I'm working together with @pawelfus. We noticed errors not being catched with db.task, but later we narrowed it down to this bug in our code base. 
```ts 
const myAsyncFunction = (): Promise => {
   return db.task( t => {} )
}
try {
  return myAsyncFunction()
} catch (err) {
  throw new Error  // THIS WON'T BE CATCHED OBVIOUSLY... 
}
```
Well sorry for wasting your time, but thank you for your library... we have much pleasure working with your library.

**Comment by vitaly-t** [comment]
@gvaartjes You are welcome! b.t.w. I'm currently available for hire ;)
