### ISSUE TITLE
Calling pgp.end() at the end of a Lambda handler

### ISSUE THREAD

**Issue by kamek-pf** [vitaly-t/pg-promise#348]
Hey there !

First of all, thank you for this awesome lib, I've been using it for quite some time now, awesome work.
We're relying on AWS Lambda more and more at work, I'd like to discuss what should be done after each invocations.

Let's take a simple example :

```typescript
import * as pg from "pg-promise";
import { SQL as sql } from "sql-template-strings";
import { Context, Callback } from "aws-lambda";

const cn = {
    host: process.env.PG_URL,
    port: process.env.PG_PORT,
    database: process.env.PG_DB_NAME,
    user: process.env.PG_USER,
    password: process.env.PG_PWD
};

const pgp = pg();
const db = pgp(cn);

export const handler = async (
    event: any
    context: Context,
    callback: Callback
): Promise<void> => {
    const res = await db.one(sql`select count(*) from whatever`);
    console.log(res);
    
    // pgp.end(); // <- not sure about that
    callback();
};
```

Now if we don't specify `pgp.end()`, the lambda idles for 30 seconds before exiting.
This is specified in the readme, and as I understand, is the expected behavior of the connection pool.

I'd like to clarify what actually happens if we do specify it.
Is it the correct thing to do or am I shooting myself in the foot ?
If not, what do you think should be done after a Lambda call ?

**Comment by vitaly-t** [comment]
It is documented everywhere:

* [Main documentation](https://github.com/vitaly-t/pg-promise#library-de-initialization)
* [API documentation](http://vitaly-t.github.io/pg-promise/module-pg-promise.html#%7Eend)
* Examples
  - [query](https://github.com/vitaly-t/pg-promise/blob/master/examples/query.js)
  - [transaction](https://github.com/vitaly-t/pg-promise/blob/master/examples/transaction.js)

**Comment by kamek-pf** [comment]
Thanks @vitaly-t.
Definitely not what we want then, because Lambda re-uses containers as much as possible.

For future reference, setting `callbackWaitsForEmptyEventLoop` to false at the top of the handler is probably what you're looking for.
The only down side I can think of if that fire and forget write queries probably won't work, because AWS will freeze the process before they can complete.

**Comment by Crypt-iQ** [comment]
@kamek-pf 
Hey! I am a little confused by what you mean by this "fire and forget" possibility.  If you are using pg-promise correctly with promise chaining, then there shouldn't be any write queries in the event loop by the time you use AWS Lambda's callback function.  Am I missing something? Thanks!

**Comment by kamek-pf** [comment]
What I meant is that the execution will stop as soon as the callback function is executed :
```typescript
longRunningAsyncJob();
callback();
```

In this case, `longRunningAsyncJob` might not run to completion before the Lambda is frozen.

But as you said, this is an issue only if you don't chain promises correctly.

**Comment by Crypt-iQ** [comment]
@kamek-pf Thanks, that's what I thought! One more question that we could maybe move to some sort of private chat.  What happens when the lambda function times out - is the connection to the database eventually closed or is it frozen in the event loop and possibly thawed out on lambda invocation?  Where can I find out more about AWS Lambda container re-use?

**Comment by lfreneda** [comment]
@kamek-pf I'm facing the same situation, how did you end up implementing?
