### ISSUE TITLE
different behavior of methods

### ISSUE THREAD

**Issue by cultulhul** [vitaly-t/pg-promise#349]
when i user oneOrNone and the query returns no data in the then promise data is empty but when i use manyOrNone or any data is an empty object

**Comment by vitaly-t** [comment]
> when i user oneOrNone and the query returns no data in the then promise data is empty

It is not empty, it is `null`, as per the API documentation: http://vitaly-t.github.io/pg-promise/Database.html#.oneOrNone

> when i use manyOrNone or any data is an empty object

It is not an empty object, it is an empty array, again, as per the API: http://vitaly-t.github.io/pg-promise/Database.html#.manyOrNone

What is your question?

**Comment by cultulhul** [comment]
thanks i thought all the methods return null if the query returned no rows

**Comment by vitaly-t** [comment]
All methods return data according to their naming semantics, and as documented in the API.

From the [Learn by Example](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example):

> Query method names reflect how many rows the query is expected to return: [none], [one], [many], [oneOrNone], [manyOrNone] = [any]. Do not confuse it with the number of rows affected by the query, which is a different thing.

[Chaining Queries]:https://github.com/vitaly-t/pg-promise/wiki/chaining-queries
[UNLISTEN]:https://www.postgresql.org/docs/9.5/static/sql-unlisten.html
[poolIdleTimeout]:https://github.com/brianc/node-postgres/blob/master/lib/defaults.js#L44
[connect]:http://vitaly-t.github.io/pg-promise/Database.html#.connect
[func]:http://vitaly-t.github.io/pg-promise/Database.html#.func
[proc]:http://vitaly-t.github.io/pg-promise/Database.html#.proc
[map]:http://vitaly-t.github.io/pg-promise/Database.html#.map
[each]:http://vitaly-t.github.io/pg-promise/Database.html#.each
[extend]:http://vitaly-t.github.io/pg-promise/global.html#event:extend
[as.name]:http://vitaly-t.github.io/pg-promise/formatting.html#.name
[QueryFile]:http://vitaly-t.github.io/pg-promise/QueryFile.html
[ParameterizedQuery]:http://vitaly-t.github.io/pg-promise/ParameterizedQuery.html
[PreparedStatement]:http://vitaly-t.github.io/pg-promise/PreparedStatement.html
[pgNative]:http://vitaly-t.github.io/pg-promise/module-pg-promise.html
[Open Values]:https://github.com/vitaly-t/pg-promise#open-values
[SQL Names]:https://github.com/vitaly-t/pg-promise#sql-names
[task]:http://vitaly-t.github.io/pg-promise/Database.html#.task
[tx]:http://vitaly-t.github.io/pg-promise/Database.html#.tx
[func]:http://vitaly-t.github.io/pg-promise/Database.html#.func
[proc]:http://vitaly-t.github.io/pg-promise/Database.html#.proc
[query]:http://vitaly-t.github.io/pg-promise/Database.html#.query
[none]:http://vitaly-t.github.io/pg-promise/Database.html#.none
[one]:http://vitaly-t.github.io/pg-promise/Database.html#.one
[many]:http://vitaly-t.github.io/pg-promise/Database.html#.many
[oneOrNone]:http://vitaly-t.github.io/pg-promise/Database.html#.oneOrNone
[manyOrNone]:http://vitaly-t.github.io/pg-promise/Database.html#.manyOrNone
[any]:http://vitaly-t.github.io/pg-promise/Database.html#.any
[result]:http://vitaly-t.github.io/pg-promise/Database.html#.result
[stream]:http://vitaly-t.github.io/pg-promise/Database.html#.stream
[batch]:http://vitaly-t.github.io/pg-promise/Task.html#.batch
[sequence]:http://vitaly-t.github.io/pg-promise/Task.html#.sequence
[page]:http://vitaly-t.github.io/pg-promise/Task.html#.page
[Generators]:https://github.com/vitaly-t/pg-promise#generators
[ES6 generators]:https://github.com/vitaly-t/pg-promise#generators
[Performance Boost]:https://github.com/vitaly-t/pg-promise/wiki/Performance-Boost
