### ISSUE TITLE
SELECT * returns null for all columns when using LEFT JOIN

### ISSUE THREAD

**Issue by zhaosjason** [vitaly-t/pg-promise#350]
I'm trying to perform a simple left join on two tables like so:

users:
```
uid | name  | ...
-----------------
1   | jason | ...
```

sessions:
```
uid | sid  | ...
----------------
[empty]
```

code:
```
db.any("SELECT * FROM users as u LEFT JOIN sessions as s ON u.uid = s.uid;")
.then(rows => {
	console.log(rows);          // prints null for all fields
})
.catch(error => {
	console.log(error);
});
```

If you `SELECT u.uid, u.name, ...` instead of `*` then I get the correct values.  I can't figure out why `SELECT *` only returns null.  I tried the same query in psql, and both variations exhibit correct behaviors.

**Comment by vitaly-t** [comment]
> why SELECT * only returns null

Method `any` never resolves with `null`. What are you really getting?

**Comment by zhaosjason** [comment]
Yes, that's what I meant by null for all fields.  Sorry if that wasn't clear, I was trying to be brief.  What I am trying to say is that when I use the wildcard (*) selector in my SELECT statement with a LEFT JOIN then I only get an array of nulls.  See below for more examples from pgp and psql (what I'm using as my reference).

Users:
```
    uid    | name | dob | sex 
-----------+------+-----+-----
 123456789 |      |     |

(1 row)
```

Sessions:
```
 sid | uid | environment | location | created 
-----+-----+-------------+----------+---------

(0 rows)
```

psql:
```
mydb=> SELECT * FROM users AS u LEFT JOIN sessions AS s ON u.uid = s.uid;

    uid    | name | dob | sex | sid | uid | environment | location | created 
-----------+------+-----+-----+-----+-----+-------------+----------+---------
 123456789 |      |     |     |     |     |             |          | 
 
(1 row)
```
Ok, looks good.  Users has one row and Sessions is empty so this statement should just return that one record from Users.

pgp (example from previous post):
```
db.any("SELECT * FROM users as u LEFT JOIN sessions as s ON u.uid = s.uid;")
.then(rows => {
	console.log(rows);          // prints null for all fields
})
.catch(error => {
	console.log(error);
});
```
```
[ anonymous {
    uid: null,
    name: null,
    dob: null,
    sex: null,
    sid: null,
    environment: null,
    location: null,
    created: null } ]
```

pgp (without wildcard):
```
db.any("SELECT u.uid, u.name, u.dob, u.sex, s.sid, s.environment, s.location, s.created FROM users as u LEFT JOIN sessions as s ON u.uid = s.uid;")
.then(rows => {
	console.log(rows);
})
.catch(error => {
	console.log(error);
});
```
```
[ anonymous {
    uid: '123456789',
    name: null,
    dob: null,
    sex: null,
    sid: null,
    environment: null,
    location: null,
    created: null } ]
```

pgp (without LEFT JOIN):
```
db.any("SELECT * FROM users as u;")
.then(rows => {
	console.log(rows);
})
.catch(error => {
	console.log(error);
});
```
```
[ anonymous {
    uid: '123456789',
    name: null,
    dob: null,
    sex: null } ]
```

As you can see I'm only getting this error when I use the wildcard and the join.  I'm currently using pg-promise@5.9.0, PostgreSQL 9.6.2 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.2 20140120 (Red Hat 4.8.2-16), 64-bit.  I'm also hosting my database on an Amazon AWS RDS instance, not sure if that'd make a difference.

// Jason

**Comment by zhaosjason** [comment]
Just noticed that my pg-promise is outdated.  Upgraded to 5.9.4 but still getting the same issue.

// Jason

**Comment by vitaly-t** [comment]
Let me get this right, your question is why `uid` gets the value without the star and not with?

That's because you've got overlapping column names, which creates a conflict, i.e. the driver cannot tell the difference between `u.uid` and `s.uid`.

The driver does not support join results through `*` when the tables being joined have columns with the same name. You have to specify the columns explicitly. And in order to show different columns with the same name, you must give them aliases, like `u.id as userId, s.uid as sessionId`.

Also, this is all how the [underlying driver] works, not relevant to this library. If you want to research this further, open the issue against the driver.

[underlying driver]:https://github.com/brianc/node-postgres

**Comment by vitaly-t** [comment]
Closing it here, because this library doesn't change the data served by [the driver], which is what should be researched against.

[the driver]:https://github.com/brianc/node-postgres

**Comment by zhaosjason** [comment]
Ah ok, sounds good.  Thanks for the info!
