### ISSUE TITLE
error from pg-promise connecting to azure hosted PG, mitigated by using 'native' (apparently)

### ISSUE THREAD

**Issue by aahoughton** [vitaly-t/pg-promise#354]
We're just now trying to bring up our stack on azure against their hosted PG instances.  I have spent zero time tracking this down yet (I'm supposed to be on vacation), but thought I'd log it here for the time being.

We have a legacy portion of our system that directly interacts with pg (v. 5.1.0).  We also have a newer portion of our stack that uses pg-promise (v 5.3.5).  At startup, if we *don't* use `.native` on our legacy pg, the following error is thrown by pg-promise a few seconds after startup.

If we *do* use .native, the error never shows up.

Note that this is before any actual *use* (on our side) of the pg-promise built connection.  

```
{
  "message": "Cannot read property 'options' of undefined",
  "name": "TypeError",
  "stack": "TypeError: Cannot read property 'options' of undefined
    at PG.onError (/usr/local/ahoughton/api/4e308e49/node_modules/pg-promise/lib/database.js:1267:26)
    at emitTwo (events.js:106:13)
    at PG.emit (events.js:191:7)
    at emitTwo (events.js:106:13)
    at Pool.emit (events.js:191:7)
    at Client.<anonymous> (/usr/local/ahoughton/api/4e308e49/node_modules/pg/lib/pool.js:40:20)
    at emitOne (events.js:96:13)
    at Client.emit (events.js:188:7)
    at Connection.<anonymous> (/usr/local/ahoughton/api/4e308e49/node_modules/pg/lib/client.js:174:19)
    at emitOne (events.js:96:13)
    at Connection.emit (events.js:188:7)
    at TLSSocket.<anonymous> (/usr/local/ahoughton/api/4e308e49/node_modules/pg/lib/connection.js:94:12)
    at emitOne (events.js:96:13)
    at TLSSocket.emit (events.js:188:7)
    at emitErrorNT (net.js:1278:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)"
}
```

**Comment by vitaly-t** [comment]
Too many things have changed around the use of `options` between v5.3.5 and the current v5.9.5

You need to upgrade and re-test.

**Comment by vitaly-t** [comment]
@aahoughton I'm closing it for now, will reopen when you come back with more details.

**Comment by aahoughton** [comment]
Back, but I don't think this is a pg-promise issue.  I worry that I won't get much input from the node-postgres side due to the old version.

After upgrading pg-promise, and with some help from longjohn, this appears to be some variant of https://github.com/brianc/node-postgres/issues/314.  The error shows after 5s (i.e., once around the block) from this code:

```
require('longjohn');
const pg = require('pg');

const DSN = 'postgres://my_uid:my_pwd@my_hosted_azure_pg_instance:5432/test?ssl=true';

function status(cb) {
    var start = Date.now();
    var client = new pg.Client(DSN);
    client.connect(function(err) {
        if (err) {
            return cb(err);
        }

        client.query("select 1 as pong", function(err, results) {
            client.end();

            if (err) {
                return cb(err);
            }

            if (!results.rows || results.rows.length !== 1 || results.rows[0].pong !== 1) {
                return cb(new Error("expected ping of 1"));
            }

            return cb(null, Date.now() - start);
        });
    });
}

setInterval(function() {
    status(function(err, latency) {
        if (err) {
            console.error(err);
        } else {
            console.log(latency);
        }
    });
}, 5000);
```

**Comment by aahoughton** [comment]
Oh, also:

```
Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:569:26)
---------------------------------------------
    at Client.connect (/home/andrew/tmp/node_modules/pg/lib/client.js:167:7)
    at status (/home/andrew/tmp/test-unpooled-pg.js:9:12)
    at Timeout.<anonymous> (/home/andrew/tmp/test-unpooled-pg.js:31:5)
    at ontimeout (timers.js:365:14)
    at tryOnTimeout (timers.js:237:5)
    at Timer.listOnTimeout (timers.js:207:5)
```

**Comment by vitaly-t** [comment]
@aahoughton That is interesting. I wonder, if you would still get the same error with `pg-promise 6.0.22`.

Any chance you could try?

**Comment by aahoughton** [comment]
.. and the same issue with the latest pg driver:
```
Error: read ECONNRESET
    at exports._errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:569:26)
---------------------------------------------
    at Client.connect (/home/andrew/tmp/node_modules/pg/lib/client.js:184:7)
    at status (/home/andrew/tmp/test-unpooled-pg.js:9:12)
```

**Comment by aahoughton** [comment]
Still want me to try with latest pg-promise?  It's pretty clear this isn't a pg-promise issue. :)

**Comment by vitaly-t** [comment]
I thought for a moment that was something to do with this library, but now I'm not sure anymore. Still, on the off-chance that you are doing something wrong with the driver, it would be no harm trying to use `pg-promise 6.0.22`.

**Comment by vitaly-t** [comment]
I think I have an idea of what is going on there,...

As per my comment here: http://vitaly-t.github.io/pg-promise/Database.html#.connect

> Do not use this option for regular query execution, because it exclusively occupies one physical connection, and therefore cannot scale. This option is only suitable for global connection usage, such as event listeners.

Also, another reason I put that note there is that repeated use of Client.connect does fail quickly. I think this is what you are running into.

**Comment by aahoughton** [comment]
Yes, but this use-case is exactly where I *do* want to use a single connection -- I need to verify the DB is up for a regular health check, and I don't want to get stuck behind other queries in a pool.  I haven't looked at the latest pg code -- there may be a way to force a connection from a pool even if the pool is considered full (which would be incredibly dangerous, clearly).

**Comment by vitaly-t** [comment]
> es, but this use-case is exactly where I do want to use a single connection -- I need to verify the DB is up for a regular health check, and I don't want to get stuck behind other queries in a pool

Still, you've got to use the connection pool.

> I haven't looked at the latest pg code -- there may be a way to force a connection from a pool even if the pool is considered full (which would be incredibly dangerous, clearly).

No, it is not possible, and shouldn't be either.

**Comment by vitaly-t** [comment]
> I need to verify the DB is up for a regular health check

Check out: https://stackoverflow.com/questions/36120435/verify-database-connection-with-pg-promise-when-starting-an-app

**Comment by aahoughton** [comment]
You can try to convince me I want something other than what I *think* I want, I suppose, but right now I think I want this:
1. I have multiple API servers, in multiple locations.  Any one of them could suffer a net split or something equivalently problematic at any time.
2. Each API server is checked by the load balancer to verify it's working.  To support that, each API server periodically checks to verify that PG -- among other data stores -- is available.
3. This isn't just at startup
4. I only care that I *can connect and issue queries* -- I really don't want to be stuck behind a whole bunch of long-running queries that are filling up the queue

.. and finally, there might be work-arounds, but this does seem like a bug (and, obviously, not in your code).

Anyway -- close this, I'll file a variant with node-postgres.

Thank you!
