### ISSUE TITLE
Connection strings do not work with 6.x default settings

### ISSUE THREAD

**Issue by joux3** [vitaly-t/pg-promise#356]
By default `pg-promise` 6.x uses a pool. As far as I could understand the code, `pg-promise` passes the connection details to `pg-pool`. `pg-pool` however [does not support connection strings](https://github.com/brianc/node-pg-pool#note).

It looks like in order to support connection strings `pg-promise` would have to do the parsing. I personally worked around this directly using `pg-connection-string` before passing the connection details to `pg-promise`.

**Comment by vitaly-t** [comment]
@joux3 you are right. This was the only thing on my mind, to document that connection strings do not quite work in 6.x, I just didn't realize they do not work at all.

I will re-test it and post an update.

**Comment by vitaly-t** [comment]
According to this: https://node-postgres.com/features/connecting#connection-uri

You can do `pgp({conectionString: 'postgresql://...'})` and it will work well with connection strings.

Somehow I've missed that in my tests and documentation. Will be updating it shortly.

**Comment by vitaly-t** [comment]
Fixed in [v6.1.1](https://github.com/vitaly-t/pg-promise/releases/tag/v.6.1.1).

Now connection strings work with 6.x the same as they did in 5.x

**Comment by juanpaco** [comment]
Sorry to comment on an old issue, if I'm missing something or you'd like me to open a different issue, I'm happy to do that.

I'm trying to use a connection string like in the last comment, but I get an error.  Here is the attempt to make the connection:

```
const db = pgPromise({ connectionString: env.postgresConnectionString })
```

**Comment by vitaly-t** [comment]
@juanpaco Please follow the [getting started steps](http://vitaly-t.github.io/pg-promise/), you first initialize the library, then connect.
