### ISSUE TITLE
DeprecationWarning: Using the automatically created return value from client.query as an event emitter is deprecated and will be removed in pg@7.0.

### ISSUE THREAD

**Issue by phips28** [vitaly-t/pg-promise#357]
I am using the latest 6.x version and getting the following error:
`DeprecationWarning: Using the automatically created return value from client.query as an event emitter is deprecated and will be removed in pg@7.0. Please see the upgrade guide at https://node-postgres.com/guides/upgrading`

Am I doing something wrong or is it a warning from usage inside the pg-promise module?

**Comment by vitaly-t** [comment]
The warning comes from the [underlying driver](https://github.com/brianc/node-postgres), an donly if you misuse directly somehow. 

This library doesn't use any depreciated methods of the driver. You are probably using something directly, bypassing it?

Can you locate and show the code that produces the warning?

**Comment by vitaly-t** [comment]
Seems like it is this issue: https://github.com/brianc/node-postgres/issues/1332

But it was fixed a while ago, and only some pre-release 6.x versions were exposed to the issue.

Which 6.x version are you using?

**Comment by phips28** [comment]
I am using 6.1.1 (installed it some hours ago)

I reinstalled everything on my server and it seems to work now. Will text you if it appears again!

thank you for now.

**Comment by vitaly-t** [comment]
The last version where those warnings were possible was 6.0.19 pre-release, gone in 6.0.20.

I am confident there are no such warnings in any of the release 6.x versions. If you find otherwise, please come back with details.

In the meantime, I am closing it.

**Comment by phips28** [comment]
Now I found a re-produceable way to get the Warning.

I have a initialize file for the pg-promise database:
_/model/pg/index.js_
```javascript
const Promise = require('bluebird'); // eslint-disable-line

const initOptions = {
  promiseLib: Promise,
  query: function query(e) {
    console.log('----------------------------------\n', e.query);
  },
  error: function error(err, e) {
    if (global.dvel.config.production) {
      return; // do not log it in production, you should catch the errors
    }
    if (e.cn) {
      // A connection-related error;
      // Connections are reported back with the password hashed,
      // for safe errors logging, without exposing passwords.
      console.error('CN:', e.cn);
    }
    if (e.query) {
      // query string is available
      console.error('query string: ', e.query.substr(0, 1000));
      if (e.params) {
        // query parameters are available
        console.error('query params: ', e.params);
      }
    }
    if (e.ctx) {
      // occurred inside a task or transaction
      console.error('CTX: ', JSON.stringify(e.ctx));
    }
    console.error('pg error:', err.message || err);
  },
};
exports.pgp = require('pg-promise')(initOptions); // eslint-disable-line

// parse numeric, float as floats: https://github.com/vitaly-t/pg-promise/issues/128
exports.pgp.pg.types.setTypeParser(1700, (value) => {
  return parseFloat(value);
});

exports.db = exports.pgp(global.dvel.config.postgres);

exports.connect = function connect() {
  console.log('connect...');
  return exports.db.one('SELECT version()'); // <-- it fails here if I execute the connect() function from a route
};
```

In another file I have a /status route (express) to check the database status:
_/routes/ApiStatus.js_
```javascript
const model = require('../model');

Router.route('/status').get((req, res) => {
    model.pg.connect()
      .then(() => {
        return util.Response.sendOK(req, res); // OK
      })
      .catch(() => {
        return util.Response.sendError(req, res); // FAIL
      });
  });
```

When I curl this route `curl localhost/status` it throws the warning. If I remove the model.pg.connect() in the route, it doesnt select and therefore no error.

I tried to execute the connect() function in a different way, I just added the following script in the _ApiStatus.js_ file:
```javascript
setTimeout(() => {
  model.pg.db.one('SELECT version()'); // works
  model.pg.connect(); // works
}, 2000);
```
both queries gets executed 2sec after node startup. => no warning!?

Is there something wrong with express? 
Or maybe **new relic**? afaik it injects/listen all DB queries? 🤔

**Comment by vitaly-t** [comment]
There is nothing in your code that would help me reproduce the issue. I never see any warnings.

Could you, please try to narrow it down to something more precise?

**Comment by vitaly-t** [comment]
@phips28  any chance there is still a dependency issue, using the older version of the driver?

I would suggest, to delete the entire `node_modules` folder and then run `npm install` afresh.

**Comment by phips28** [comment]
It is **new relic**. When I remove the line `require('newrelic');` no warnings popping up.

**Comment by vitaly-t** [comment]
Well, that's it then. That relic package must be trying to attach itself to the driver through events that the driver considers deprecated.

**Comment by phips28** [comment]
yes, sry for bothering you ;)

I will get in touch with newrelic.

**Comment by vitaly-t** [comment]
I believe the issue isn't with the driver and isn't with the relic package.

The relic package must be hacking into other packages through events, and it cannot know when some package decides to make those events obsolete.

So it's like no-one to blame, really, just an awkward situation.

**Comment by vitaly-t** [comment]
b.t.w., best for event monitoring is to use [pg-monitor](https://github.com/vitaly-t/pg-monitor) :wink:

**Comment by vitaly-t** [comment]
The same issue reported against the driver: https://github.com/brianc/node-postgres/issues/1348
