### ISSUE TITLE
db.any is not a function

### ISSUE THREAD

**Issue by ntaboada** [vitaly-t/pg-promise#358]
Hi there,

I am trying to integrate the library on my project. I am using Node with ES6 (transpiling with babel).
The error output: TypeError: _database2.default.any is not a function.
I am having troubles using it like this:

`import pgp from 'pg-promise';

const cn = {
    host: 'localhost',
    port: 5432,
    database: 'test',
    user: 'postgres',
    password: 'roman9393'
};

const db = pgp(cn);

export default db;`

I don' t know if the problem is the ES6 module import. Please help me!

**Comment by vitaly-t** [comment]
You are missing the library's initialization step. See [Getting Started](https://github.com/vitaly-t/pg-promise#getting-started):

```js
const initOptions = {/* initialization options */};
const pgp = require('pg-promise')(initOptions);
const db = pgp(connection);
```
