### ISSUE TITLE
What will happen upon calling t.task where t is the result of another t.task?

### ISSUE THREAD

**Issue by OrKoN** [vitaly-t/pg-promise#359]
What I mean is what is the behavior for nested tasks? Do nested tasks grab a new connection from the pool or do they use the connection obtained by the parent task (given that the t param is used correctly)?

```js
t.task(t => {
// t.queries..
 return t.task(t2 => {
   // t2.queries...
   // two connections or one?
 });
});
```

Thanks in advance.

**Comment by vitaly-t** [comment]
> do they use the connection obtained by the parent task

they do.

**Comment by vitaly-t** [comment]
Updated API documentation for methods [task] and [tx] to explicitly mention how the connection is used.

[task]:http://vitaly-t.github.io/pg-promise/Database.html#task
[tx]:http://vitaly-t.github.io/pg-promise/Database.html#tx

**Comment by OrKoN** [comment]
Thanks for the prompt response!

**Comment by vitaly-t** [comment]
@OrKoN you are welcome!

And changes in [Release 6.2.0](https://github.com/vitaly-t/pg-promise/releases/tag/v.6.2.0) are very much relevant to your question, as you can change your task/transaction logic based on its nested level of execution.
