### ISSUE TITLE
Unref?

### ISSUE THREAD

**Issue by olalonde** [vitaly-t/pg-promise#360]
It would be useful to have an `unref()` method so that pg-promise doesn't prevent the process from terminating (e.g. in tests).

**Comment by vitaly-t** [comment]
Could you, please clarify that? I'm not clear on what it is exactly you are suggesting and why.

**Comment by elmigranto** [comment]
@olalonde [more details](http://vitaly-t.github.io/pg-promise/module-pg-promise.html#~end), basically:

``` js
const pgPromise = require('pg-promise')();
const pgp = pgPromise('postgres://localhost:5432/database-name');

pgPromise.end(); // close all conections in all pools
database.$pool.end(); // close that particular one

// In tests this should work:
afterAll(() => pgp.$pool.end());
```

**Comment by vitaly-t** [comment]
Just to avoid the naming confusion, renaming the variables:
```js
const pgp = require('pg-promise')();
const db = pgPromise('postgres://localhost:5432/database-name');

pgp.end(); // shuts down all connections pools
db.$pool.end();  // shuts down one specific pool

// In tests this should work:
afterAll(db.$pool.end);
```

API references:

* [pgp.end](http://vitaly-t.github.io/pg-promise/module-pg-promise.html#~end)
* [$pool](http://vitaly-t.github.io/pg-promise/Database.html#$pool)

**Comment by olalonde** [comment]
@elmigranto @vitaly-t thanks, that solves the example I mentioned but it would still be useful to have `unref()`. To clarify what I meant, see the `unref` methods in the Node.js [API docs](https://nodejs.org/dist/latest/docs/api/all.html):

- [timeout.unref()](https://nodejs.org/api/timers.html#timers_timeout_unref)
- [server.unref()](https://nodejs.org/dist/latest/docs/api/all.html#net_server_unref)
- [socket.unref()](https://nodejs.org/dist/latest/docs/api/all.html#net_socket_unref)

The general idea is that by "unreferencing" some object, Node.js will terminate the process even if the "unrefed" object is still waiting/listening for I/O.

This would probably be achieved in pg-promise by calling `.unref()` on the postgres socket(s).

**Comment by elmigranto** [comment]
I get usecases for timeout and server/socket, but not sure about Postgres.

You probably don't want to deal with [undetermenistic "fire and forget" situations](https://dba.stackexchange.com/questions/81408/is-a-postgres-long-running-query-aborted-if-the-connection-is-lost-broken), so the only thing I can imagine is when you have some rows streaming in from read-only `select`, or listening for `PGNOTIFY`, but even then, there are better ways to kill that IO. (Or is there, @vitaly-t is it possible to cancel queries?)

**Comment by olalonde** [comment]
I actually implemented something like `unref()` for the pg client in one of my libraries: https://github.com/binded/advisory-lock/blob/master/src/index.js#L20-L53

It made sure that it would only unref if there weren't any pending queries. It probably doesn't support all use cases like `PGNOTIFY`.

In hindsight, it may be too tricky to implement in a fool proof way.

**Comment by vitaly-t** [comment]
@olalonde I don't see the `unref` logic applicable to this database driver. The only thing we do or can do - to shut down the connection pool. Our only choice is to shut down all pools or just one.

**Comment by olalonde** [comment]
@vitaly-t I realize this feature isn't implemented, it was more of a request. I think it would be possible to implement but perhaps it would be complex.

**Comment by vitaly-t** [comment]
Sorry, I don't see it happen in a foreseeable future, as I do not recognize a real need for it.

For that reason, and since the original question about releasing the connection pool has been answered, I am closing the issue.
