### ISSUE TITLE
queryResultErrorCode

### ISSUE THREAD

**Issue by kmarchenko** [vitaly-t/pg-promise#361]
```
/node_modules/pg-promise/lib/errors/queryResult.js:151
            gap1 + 'code: queryResultErrorCode.' + errorMessages[this.code].name,
                                                                                                                           ^
TypeError: Cannot read property 'name' of undefined
```

```js
db.one('SELECT * FROM users WHERE id = $1', 1)
```

**Comment by vitaly-t** [comment]
How do you get this type of error?

You can't get it simply by executing that query. Need to see more context.

Also, which `pg-promise` version are you using?

**Comment by anonrig** [comment]
```javascript
db.one('SELECT * FROM users WHERE id = $1', 1)
```

Shouldn't this line be like at the bottom?

```javascript
db.one('SELECT * FROM users WHERE id = $1', [1])
```

**Comment by vitaly-t** [comment]
@anonrig not sure what you mean...

**Comment by anonrig** [comment]
The second parameter of the function `db.one` can it be an integer or should it be an array, in order to parse `$1` to its corresponding value?

**Comment by vitaly-t** [comment]
@anonrig it works either way.

**Comment by kmarchenko** [comment]
version: 6.2.1
export function getById(id) {
    return db.one('SELECT * FROM users WHERE id = $1', id)
}

**Comment by vitaly-t** [comment]
@kmarchenko I can execute the same type of query, with all types of possible results, but I never get the type of error you described.

**Comment by kmarchenko** [comment]
@vitaly-t 
```
db.connect().then(() => {
  console.log('[INFO] Successful database connection!')
  db.none('SELECT * FROM users WHERE id = $1', 123).then(console.log).catch(error => console.log(error.code))
}).catch((error) => {
  console.log('[DB ERROR]: ', error.message || error)
})
```

> [INFO] Successful database connection!
> node_modules/pg-promise/lib/errors/queryResult.js:151
>             gap1 + 'code: queryResultErrorCode.' + errorMessages[this.code].name,
>                                                                            ^
> 
> TypeError: Cannot read property 'name' of undefined
>     at QueryResultError.toString (node_modules/pg-promise/lib/errors/queryResult.js:151:76)
>     at Function.prepareStackTrace (node_modules/source-map-support/source-map-support.js:372:16)
>     at Function.captureStackTrace (<anonymous>)
>     at new QueryResultError (node_modules/pg-promise/lib/errors/queryResult.js:123:15)
>     at Result.ctx.db.client.query (node_modules/pg-promise/lib/query.js:164:45)
>     at Result.Query.handleReadyForQuery (node_modules/pg/lib/query.js:144:10)
>     at Connection.<anonymous> (node_modules/pg/lib/client.js:180:19)
>     at emitOne (events.js:101:20)
>     at Connection.emit (events.js:189:7)
>     at Socket.<anonymous> (node_modules/pg/lib/connection.js:133:12)
> error Command failed with exit code 1.

**Comment by vitaly-t** [comment]
When I run exactly this code, I'm getting:

```
[INFO] Successful database connection!
0
```

**Comment by vitaly-t** [comment]
@kmarchenko the only way an error such as yours can happen, is when

**Comment by vitaly-t** [comment]
@kmarchenko the only way such an error can happen, if if we try to hack the error class `toString` method, by doing this:

```js
error.toString.call({});
```

the code above makes direct string conversion on the invalid context.

The thing is, there is no such situation inside `pg-promise` anywhere, so I cannot fathom how this can possibly happen.

I'm beginning to assume something is else is wrong with your app, like maybe there is some dumb library, like `newrelic`, trying to hack into `toString` or `Error` implementations.

I have no other explanation. You will need to investigate this on your end, as I have done everything I could think of at this point.

**Comment by kmarchenko** [comment]
@vitaly-t I'm downgraded pg-promise version to 5.9.0, and all is fine. I have no idea too, when I tried to debug vars in QueryResultError, I just get undefined on all vars.

**Comment by vitaly-t** [comment]
@kmarchenko what version of Node.js are you using?

**Comment by vitaly-t** [comment]
@kmarchenko also, could you, please try 2 specific versions: `6.0.24` and `6.0.25`. There was a change between those two, which I suspect may somehow contribute to the problem. If that's the case, then it will work for you in `6.0.24`, but not `6.0.25`. That's just the best guess right now.

**Comment by vitaly-t** [comment]
A related question has been asked on StackOverflow: https://stackoverflow.com/questions/44850862/custom-es6-javascript-error-issue

**Comment by kmarchenko** [comment]
@vitaly-t 
node version: v7.6.0
With v6.0.24 all works fine, with v6.0.25 crashes.

```
const error = new pgp.errors.QueryResultError(0, {rows: []}, 'select', 1);
console.log(error);
```

> v6.0.24
> QueryResultError {
>     code: queryResultErrorCode.noData
>     message: "No data returned from the query."
>     received: 0
>     query: "select"
>     values: 1
> }

> v6.0.25 error
> node_modules/pg-promise/lib/errors/queryResult.js:151
>             gap1 + 'code: queryResultErrorCode.' + errorMessages[this.code].name,
> TypeError: Cannot read property 'name' of undefined

**Comment by vitaly-t** [comment]
@kmarchenko thank you! Than means most likely if you pull it from branch `error-test`, it should work. Have you tried though?

**Comment by kmarchenko** [comment]
@vitaly-t Yes, I tried it and it work.

**Comment by vitaly-t** [comment]
Ok, cool, we are getting somewhere. I'm preparing one last test for you to see if it works, and then I can apply the fix to the master. Give me 10 mins, please ;)

**Comment by vitaly-t** [comment]
@kmarchenko could you, please, run your test against branch `error-test-2`, and tell me if it works!

Thank you!!!

**Comment by kmarchenko** [comment]
@vitaly-t Updated, but unfortunately old error returns back.

**Comment by vitaly-t** [comment]
@kmarchenko Thank you!

I honestly still do not understand how the error you are getting is even possible. But still, based on your results, I'm going to revert the `master` to the version that's in `error-test`, and re-release it shortly (within an hour).

Thank you for finding and reporting the issue, and if you somehow stumble upon the reason of why this was happening, please let me know.

**Comment by kmarchenko** [comment]
@vitaly-t Okay, I'll let you know. Thank!

**Comment by vitaly-t** [comment]
@kmarchenko the issue has been fixed in [Version 6.2.3](https://github.com/vitaly-t/pg-promise/releases/tag/v.6.2.3). Please re-test, and if all is good - close the issue.

Thank you for your help!

**Comment by kmarchenko** [comment]
@vitaly-t  Everything works. Thank you.

**Comment by redben** [comment]
Just a note if anyone else still sees similar errors (version: 6.3.1)

You get the error bellow if you are using bluebird somewhere in the chain and have not set pg-promise to use bluebrid. At least in my case.

```
TypeError: Cannot set property 'name' of undefined
      at QueryResultError (node_modules/pg-promise/lib/errors/queryResult.js:122:27)
      at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by vitaly-t** [comment]
@kmarchenko Is this what was happening? - 

> You get the error bellow if you are using bluebird somewhere in the chain and have not set pg-promise to use bluebrid

@redben thank you!
