### ISSUE TITLE
err_Connection_Not_Estb.

### ISSUE THREAD

**Issue by sachinavinaw** [vitaly-t/pg-promise#362]
Hi there.

I am new to pg-promise. Can anyone tell me how to handle "connection not established" error in pg-promise?
This is my code:
```
var pgp = require('pg-promise')();
const databaseConfig = {
    "host": systemsetting.DB_SERVER,
    "port": systemsetting.DB_PORT,
    "database": systemsetting.DB_NAME,
    "user": systemsetting.DB_USER_NAME,
    "password": systemsetting.DB_PASSWORD
};
var db = pgp(databaseConfig);
```

Where exactly I can handle connection?
Thanks in advance.

**Comment by anonrig** [comment]
Did you try?

```javascript
db.connect().catch(error => console.error(`Connection error ${error.message}`);
```

**Comment by vitaly-t** [comment]
@sachinavinaw the code that you showed wouldn't create the kind of problem. Can you show the code that produces the error?

**Comment by vitaly-t** [comment]
@sachinavinaw please get back with more details. Closing until then.
