### ISSUE TITLE
.then before .catch

### ISSUE THREAD

**Issue by nokizorque** [vitaly-t/pg-promise#366]
Hi,

Today I spent hours debugging receiving multiple callbacks from a function, where db.any was invoked with the `.then` and `.catch` methods. The problem ultimately was me putting `.catch` before `.then`, as I traditionally prefer to put all my error checking before my processing.

So, if anyone could possibly enlighten me as to why `.then` must be called before `.catch` as to not receive two callbacks.

Example of what I'm talking about:
```js
db.any(qryString, params)
    .then(function(data) {
        cb(null, data);
    })
    .catch(function(err) {
        cb(err, null);
     });
```

Thanks!

**Comment by vitaly-t** [comment]
Unrelated. You should research it against promises in general, not this library:

* https://stackoverflow.com/questions/42013104/placement-of-catch-before-and-after-then
