### ISSUE TITLE
Casting inside :csv

### ISSUE THREAD

**Issue by jckkong** [vitaly-t/pg-promise#368]
Hey there, 

I am trying to run a query like the below with argument = an array of bigint (in js, it will be of type string as it is bigger than an integer)

```
SELECT id FROM
table_name
WHERE id IN ($1:csv)
```

:csv is converting the array as an array of string. Since id is a column of bigint, postgres is throwing an `error: operator does not exist: text = bigint`

Is there any way to format the array with an explict cast?

input: `["105110058177674083", "105110058177674082", "105110058177674084"]`
output: `["105110058177674083"::bigint, 105110058177674082"::bigint, "105110058177674084"::bigint]`

Please help :)

**Comment by vitaly-t** [comment]
Explicit cast to what? JavaScript doesn't have native presentation for 64-bit integers. There is nothing that operand `:csv` can do there for you. You will need convert those and recast on your side.

**Comment by jckkong** [comment]
great. thank you!
