### ISSUE TITLE
Checking for no data found with db.one("select ...")

### ISSUE THREAD

**Issue by freakent** [vitaly-t/pg-promise#37]
How can I check for a no data found or a too many rows error when using the db.one("select ...") style of query? At the moment I am catching an error, if it's a real syntax error I get a complex object, but for no data found it's just a string saying "No data returned from the query.". It would be nicer if there were a error object with a code and message for no data found.

**Comment by vitaly-t** [comment]
[oneOrNone](https://github.com/vitaly-t/pg-promise/blob/master/lib/index.js#L207) is what you want ;)

**Comment by vitaly-t** [comment]
trying to update...
