### ISSUE TITLE
Incorrect date insertion

### ISSUE THREAD

**Issue by clicktravel-pavel** [vitaly-t/pg-promise#38]
A date is created from the string 2015/08/01 this way: new Date("2015/08/01"). When printed it is Sat Aug 01 2015 00:00:00 GMT+0300 (EEST).

Data is saved into the amazon redshift database.
- If we use https://github.com/brianc/node-postgres it is saved correctly.
- If we use https://github.com/vitaly-t/pg-promise it is saved 1 day back, i.e. 2015/07/31

**Comment by vitaly-t** [comment]
I'm trying to understand, how come that the following code:
```javascript
var t = new Date("2015/08/01");
console.log(t);
```
prints `Sat Aug 01 2015 00:00:00 GMT+0100 (GMT Daylight Time)`;
in the meantime the following code:
```javascript
var t = new Date("2015/08/01");
console.log(t.toUTCString());
```
prints: `Fri, 31 Jul 2015 23:00:00 GMT`

Something doesn't add up here, and I'm gonna look into that. It's not so much the library issue, rather something strange in Java Date conversion...

Feel free to follow up with any thought on this ;)

**Comment by vitaly-t** [comment]
@clicktravel-pavel is there still a question about use of Date/Time?

**Comment by clicktravel-pavel** [comment]
Thanks for the advice!

Using var date = new Date(Date.UTC(year, month, day)); works correctly.

Thanks for the support!

**Comment by vitaly-t** [comment]
This however gave me an idea for adding support for generic type conversion. The code is finished, will release once the documentation has been updated.

For absolutely any type, including the standard ones, like `Date` and `Array`, if it has function `formatDBType` on it, it overrides any other formatting in the library.

So, for example, if you want to format `Date` in your own way, you could do:

```javascript
Date.prototype.formatDBType = function () {
    return new Date(Date.UTC(this.getFullYear(), this.getMonth(), this.getDate()));
};
```

**Comment by vitaly-t** [comment]
F.Y.I. Important breaking change in [v6.5.0](https://github.com/vitaly-t/pg-promise/releases/tag/v.6.5.0).
