### ISSUE TITLE
'Invalid or missing stream object' with 6.3.7 and Node 6/7

### ISSUE THREAD

**Issue by dmfay** [vitaly-t/pg-promise#380]
I just noticed Massive's results streaming tests start failing after upgrading to 6.3.7 with Node versions 6 and 7 (8 is somehow fine). It looks like pg-query-stream released version 1.1.0 today, and QueryStream's `state` property moved under `cursor`. Some other changes too; notably `context` in the pg-promise test/streamSpec is no longer defined.

**Comment by vitaly-t** [comment]
I don't see how pg-promise update from 6.3.6. to 6.3.7 could break anything.

Only the update of [QueryStream](https://github.com/brianc/node-pg-query-stream) from 1.0.0 to 1.1.0 could have done it.

I suppose you can continue using version 1.0.0 of it, till pg-promise is updated to support the latest version?

**Comment by vitaly-t** [comment]
I can see that [QueryStream](https://github.com/brianc/node-pg-query-stream) 1.1.0 is a complete breaking change from 1.0.0, should have been 2.0.0 instead.

**Comment by dmfay** [comment]
The 6.3.7 upgrade itself didn't break anything -- the build passed on the dependency update. It's just pg-query-stream. I expect it'll be breaking your build soon too though, since you depend on `1.x` :)

**Comment by vitaly-t** [comment]
I have released [v6.3.8](https://github.com/vitaly-t/pg-promise/releases/tag/v.6.3.8) just to avoid the dependency issue.

@dmfay you can set it as the new dependency ;)

I've tried to do a quick fix on the new version of `pg-query-stream`, but it didn't work. I will need to spend a bit more time with it.

**Comment by vitaly-t** [comment]
There some issues there: https://github.com/brianc/node-pg-query-stream/issues/28

So I wouldn't rush trying to support the latest, especially considering that version 1.1 doesn't fix any issues, just refactors for ES6, while breaking some existing functionality, as evident.

**Comment by dmfay** [comment]
Thanks! :)

**Comment by vitaly-t** [comment]
I'm going to wait till Brian follows up on this: https://github.com/brianc/node-pg-query-stream/issues/30, before making any changes that is.

**Comment by vitaly-t** [comment]
More to the fire: https://github.com/brianc/node-pg-query-stream/issues/32

**Comment by vitaly-t** [comment]
Replacing this issue with #383.
