### ISSUE TITLE
Select columns between parentheses strange behavior

### ISSUE THREAD

**Issue by reinert** [vitaly-t/pg-promise#382]
I'm almost sure this is an issue from node-postgres, but I'm opening here because I reproduced in pg-promise.

The problem is related to formatting a simple select. When putting the select columns between parentheses the result is a big string with the values in parenthesis. See the log below:

```sql
SELECT (id, email, first_name, last_name, role) FROM users
```
returns
```sql
[
  { row: '(142,user_b@example.com,"User B","User B",ARTIST)' },
  { row: '(143,user_c@example.com,"User C","User C",ARTIST)' }
]
```

while...

```sql
SELECT id, email, first_name, last_name, role FROM users
```
returns
```sql
[
  {"id":"154","email":"user_b@example.com","first_name":"User B","last_name":"User B","role":"ARTIST"},
  {"id":"155","email":"user_c@example.com","first_name":"User C","last_name":"User C","role":"ARTIST"}
]
```

It smells like a bug.

Is it ok?

**Comment by vitaly-t** [comment]
You get exactly what you query for when you do `SELECT (col1, col2 ....)` instead of `SELECT col1, col2,...`.
