### ISSUE TITLE
Dealing with functions and empty arrays.

### ISSUE THREAD

**Issue by MadsRC** [vitaly-t/pg-promise#384]
I have a Postgres function that I'm invoking like this:
```
pgp.func('createUser', [
  data.username,
  ... Lots of other data...
  data.tenants
])
```
The function expects the second argument to be of type "text[]", but I keep getting this error:
```
ERROR:  cannot determine type of empty array at character XXX
HINT:  Explicitly cast to the desired type, for example ARRAY[]::integer[].
```
As you might expect, it works like a charm when the array isn't empty.
I had a look at issue #101 - If I try to pgp.as.array(tenants)+'::text[]' the actual array statement looks legit, however it is enclosed in single-quotes, which makes Postgres interpret it as a string instead of an empty array of text.

For reference, here's the pg-migrate source for the function:
```
exports.up = (pgm) => {
  pgm.createFunction('createUser', [
    {name: 'firstname', type: 'text',},
    {name: 'lastname', type: 'text',},
    {name: 'salt', type: 'bytea',},
    {name: 'password', type: 'text',},
    {name: 'username', type: 'text',},
    {name: 'email', type: 'text',},
    {name: 'tenants', type: 'text[]'}
  ], {
    replace: true,
    returns: 'uuid',
    language: 'plpgsql'
  }, `/*
  Function that creates a user.
*/
DECLARE
  userid uuid;
  x text;
  tenantexists uuid;
BEGIN
  INSERT INTO users (firstname, lastname, passwordsalt, email, username, password)
  VALUES (firstname, lastname, salt, email, username, password)
  RETURNING id INTO userid;

  FOREACH x IN ARRAY tenants
  LOOP
    SELECT tenants.id INTO tenantexists FROM tenants WHERE id = UUID(x);
    IF tenantexists IS NULL
    THEN
      RAISE EXCEPTION 'Provided tenant(s) does not exist';
    ELSE
      INSERT INTO usertenantmap (relateduserid, relatedtenantid) VALUES (userid, UUID(x));
    END IF;
  END LOOP;

RETURN userid;
END`);

};
```

Any directions as to how one is supposed to handle this?

**Comment by vitaly-t** [comment]
Method [func] is there to simplify regular function calls, i.e. the ones where default type casting is sufficient, which isn't your case, so the method isn't suitable there.

The simplest solution is to generate the query yourself:

```js
db.any('SELECT * FROM createUser($1, $2::integer[])', [username, tenants])
```

[func]:http://vitaly-t.github.io/pg-promise/Database.html#func

**Comment by MadsRC** [comment]
Thank you very much vitaly, that did it! (Had to rename the function to lowercase or encase createUser in double-quotes though, but that's a minor issue).

**Comment by vitaly-t** [comment]
@MadsRC yes, I didn't notice at first the use of the camel-case in the name. I have corrected my example by using double-quotes for the function name.

**Comment by vitaly-t** [comment]
Release [v6.7.1](https://github.com/vitaly-t/pg-promise/releases/tag/v.6.7.1) changes these things.
