### ISSUE TITLE
update to pg@6.4.2 to address code execution vulnerability

### ISSUE THREAD

**Issue by jonotron** [vitaly-t/pg-promise#385]
Upstream package `pg` has released a security fix for a code execution vulnerability. Details: https://node-postgres.com/announcements#2017-08-12-code-execution-vulnerability

**Comment by vitaly-t** [comment]
Cheers! I will up the dependency in the next update ;)

**Comment by vitaly-t** [comment]
Updated in [v6.4.0](https://github.com/vitaly-t/pg-promise/releases/tag/v.6.4.0).
