### ISSUE TITLE
Connecting with "postgres://" does not work as it expects an object

### ISSUE THREAD

**Issue by jllodra** [vitaly-t/pg-promise#39]
The README says that you can use either an Object or an String to connect, but following code is not working:

```javascript
var db = pgp("postgresq://user:password@host:port/database");
```
getting a run-time exception:
```javascript
        throw new Error("Invalid parameter 'options' specified.");
```

Switched to an Object representation and worked like a charm.

**Comment by vitaly-t** [comment]
You make the wrong call into the library object, not following the [Getting Started](https://github.com/vitaly-t/pg-promise#getting-started) instructions.

Your `pgp` object must is set to `require("pg-promise")`, as opposed to `require("pg-promise")(/*options*/)`.

As a result, you are making a call to initialize the library with `options`, but instead you are passing it the connection string, which is part of the next step - database initialization.

**Comment by jllodra** [comment]
I should RTFM more carefully.
Finally figured it out, thanks for answering.

**Comment by RichardJECooke** [comment]
It's weird that you have call pgp() twice. I just had the same issue. There should probably be a line in the manual clarifying it a little so others don't struggle too.

**Comment by vitaly-t** [comment]
The library clearly defines it as a two-step process:
1. Load and initialize the library: `var pgp = require('pg-promise')(/*options*/)`
2. Create the database instance: `var db = pgp(connection);`

And it is everywhere, in all the [examples](https://github.com/vitaly-t/pg-promise/tree/master/examples).

You are second person asking about, since ever, so I don't know if there is any issue there....

**Comment by tjmcewan** [comment]
@vitaly-t because 'options' is in comments I didn't "see" the extra function call.  I don't know if it's the same reason for the others.

**Comment by vitaly-t** [comment]
@tjmcewan Thank you! I wasn't sure how to update the docs to make it more clear. Plus all the examples show the same thing.

I can't say this is ideal, no, but this is the way it has been implemented from day one, so for the sake of compatibility... The bottom line, once you figure that one out once, you won't make the same mistake again ;)

I will consider an update, should I start on version 3.0.0

Cheers!

**Comment by tjmcewan** [comment]
I'm not commenting on the api, just the way I read the docs. :)
Maybe pass in an actual options object with some defaults instead of the
commented text? Just to make it clearer that it's not something that can be
ignored.

Thanks!

**Comment by vitaly-t** [comment]
@tjmcewan `null` / `undefined` or `{}` are the defaults.

**Comment by vitaly-t** [comment]
[Version 3.0](https://github.com/vitaly-t/pg-promise/releases/tag/v.3.0.3) is out, and this small amendment is there also.

**Comment by kaizokuace** [comment]
I also ran into this problem, this issue thread helped solve it for me.  What made it hard for me to notice was that I am using ES6 import statements instead of require. The docs go from the require description to connection settings.

**Comment by vitaly-t** [comment]
[Getting Started](https://github.com/vitaly-t/pg-promise#getting-started) explicitly says:
```js
// Loading and initializing the library:
var pgp = require('pg-promise')({
    // Initialization Options
});
```

Two-step is what it takes to set up universal use of promises throughout the library.

**Comment by vitaly-t** [comment]
I'm gonna look at making the error more intelligent/descriptive.

**Comment by vitaly-t** [comment]
This functionality has been improved in [version 3.4.3](https://github.com/vitaly-t/pg-promise/releases/tag/v.3.4.3).

**Comment by mattdeluco** [comment]
IMO these docs could be updated, just arrived here searching for answers with the same confusion:
https://github.com/vitaly-t/pg-promise/wiki/Connection-Syntax

**Comment by vitaly-t** [comment]
The same confusion? [The docs have been rewritten since](https://vitaly-t.github.io/pg-promise/). There should be no confusion anymore, if you just follow the documentation.

**Comment by mattdeluco** [comment]
If one lands directly on the [Connection Syntax wiki page](https://github.com/vitaly-t/pg-promise/wiki/Connection-Syntax) I linked there's no indication of the correct way to require the pgp module - i.e. `const pgp = require('pg-promise')({})`.

That wiki page just needs the update you mentioned earlier in this thread:
```
// Loading and initializing the library:
var pgp = require('pg-promise')({
    // Initialization Options
});
```
