### ISSUE TITLE
Using many instances for queries

### ISSUE THREAD

**Issue by JonathanGonczoroski** [vitaly-t/pg-promise#390]
Hello, I received the following error: **remaining connection slots are reserved for non-replication superuser and rds_superuser connections**. I imagine there are many instances trying to access the database. I wonder if there is any way to not use as many instances, or the form I'm using is wrong.

I create a configuration file like this:

```javascript
var pgp = require("pg-promise")();

// Config contains the address of the database
var db = pgp(config.database);

module.exports = {
    pgp,
    db
};
```

And I use it like this:

```javascript
const pgPromise = require("../../commom/utils/pgPromise");

pgPromise.db.any("select * from table");
```

Is it an incorrect way to use it ?

If yes, what would be the best way? 
If not, is there any way I can decrease the number of instances?

Thanks for the help

**Comment by vitaly-t** [comment]
Your usage pattern is correct, but error message tells you that your provider refuses to allocate enough connections for you.

You need to find out how many connections are allowed, and set it within the connection config, using parameter `poolSize`:

```js
const db = pgp({
    poolSize: 5,
   // other connection parameters
});
```

**Comment by JonathanGonczoroski** [comment]
It Worked! Thank you!
