### ISSUE TITLE
IN (<empty set>) queries

### ISSUE THREAD

**Issue by liammclennan** [vitaly-t/pg-promise#391]
pg-promise supports querying for rows with values in a set as described [in the documentation](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#where-col-in-values).

However, this fails if the set is empty. This is the [behaviour of Postrgres](
http://www.postgresql-archive.org/empty-set-td2146237.html), however the following query is common and will always fail:

```
db.any('SELECT * FROM table WHERE id IN ($1:csv)', [[]])
    .then(data => {
        // success;
    })
```

Should pg-promise replace `[]` with something like `select 1 from false` so the user gets what they expect?

**Comment by vitaly-t** [comment]
The following query is not a valid SQL:
```sql
SELECT * FROM table WHERE id IN ()
```
which means you are not supposed to even try to execute it.
