### ISSUE TITLE
pg-promise with Ionic

### ISSUE THREAD

**Issue by Brizak** [vitaly-t/pg-promise#392]
Hi Vitaly,

I'm developing a cross platform mobile application with Ionic (v3) and trying to include your module pg-promise to connect my app with a postgresql database.

Impossible to run the app since i initialize the database object with typescript .. 

I have this 2 typescript errors : "Cannot find namespace 'NodeJS'." and "Cannot find name 'Buffer'."

Here are the dependencies and config:

`{
  "dependencies": {
    "@angular/common": "4.1.3",
    "@angular/compiler": "4.1.3",
    "@angular/compiler-cli": "4.1.3",
    "@angular/core": "4.1.3",
    "@angular/forms": "4.1.3",
    "@angular/http": "4.1.3",
    "@angular/platform-browser": "4.1.3",
    "@angular/platform-browser-dynamic": "4.1.3",
    "@ionic-native/core": "3.12.1",
    "@ionic-native/keyboard": "^4.1.0",
    "@ionic-native/native-storage": "^4.1.0",
    "@ionic-native/splash-screen": "3.12.1",
    "@ionic-native/status-bar": "3.12.1",
    "@ionic/storage": "2.0.1",
    "@types/node": "^8.0.25",
    "cordova-android": "^6.2.3",
    "cordova-ios": "^4.4.0",
    "cordova-plugin-console": "^1.0.5",
    "cordova-plugin-device": "^1.1.4",
    "cordova-plugin-nativestorage": "^2.2.2",
    "cordova-plugin-splashscreen": "^4.0.3",
    "cordova-plugin-statusbar": "^2.2.2",
    "cordova-plugin-whitelist": "^1.3.1",
    "ionic-angular": "3.6.0",
    "ionic-plugin-keyboard": "^2.2.1",
    "ionicons": "3.0.0",
    "pg-promise": "^6.5.1",
    "rxjs": "5.4.0",
    "sw-toolbox": "3.6.0",
    "zone.js": "0.8.12"
  },
  "devDependencies": {
    "@ionic/app-scripts": "2.1.3",
    "@ionic/cli-plugin-cordova": "1.5.0",
    "@ionic/cli-plugin-ionic-angular": "1.4.0",
    "ionic": "3.7.0",
    "typescript": "2.3.4"
  },
  "description": "An Ionic project",
  "cordova": {
    "plugins": {
      "cordova-plugin-console": {},
      "cordova-plugin-device": {},
      "cordova-plugin-splashscreen": {},
      "cordova-plugin-statusbar": {},
      "cordova-plugin-whitelist": {},
      "ionic-plugin-keyboard": {},
      "cordova-plugin-nativestorage": {}
    },
    "platforms": [
      "android",
      "ios"
    ]
  },
  "config": {
    "ionic_bundler": "webpack",
    "ionic_source_map": "source-map"
  }
}
`

Here are 2 images with errors description :

![bug1](https://user-images.githubusercontent.com/31404076/29772504-631b86f0-8bf9-11e7-9977-8f45fea74833.png)

![bug2](https://user-images.githubusercontent.com/31404076/29772505-631f7882-8bf9-11e7-8c36-fd88710f29dc.png)

In the pg-subset.d.ts file, i had an error on the buffer type but since i execute "npm install @types/node --save-dev", the error disappeared as you can see on the following image : 

![buffertype](https://user-images.githubusercontent.com/31404076/29772732-521abcee-8bfa-11e7-8f7a-0a34cdf009e0.png)

Can you help me please ? or do you need more information ?

**Comment by vitaly-t** [comment]
You need to add the Node.js types, like here: https://github.com/vitaly-t/pg-promise-demo/blob/master/package.json#L35

It includes all the standard types, including `Buffer`.

**Comment by Brizak** [comment]
That does not work.

**Comment by vitaly-t** [comment]
@Brizak What doesn't work?

The current TypeScript version of the library has been used by developers for a very long time. You are the first one to log this kind of issue, which most likely means you are doing something wrong there.

Please be more specific why can't you install and use the Node.js TypeScript definitions, or best yet - ask it on StackOverflow, as it is likely to find answer there much quicker :wink:

**Comment by Brizak** [comment]
Ok, i will do that. 

Sorry for the inconvenience and thank you for your quick replies !
