### ISSUE TITLE
Unable to run a parameterized query to create user

### ISSUE THREAD

**Issue by ashishjain14** [vitaly-t/pg-promise#395]
I am trying to run a query to create a user using parameterized query as follows
 new PQ('CREATE USER $1 WITH PASSWORD \'$2\'', [username, password])

It just fails all the time with the following error:
ERROR: { error: syntax error at or near "$1"

What is wrong here?

**Comment by vitaly-t** [comment]
This issues keeps coming up all the time. Here's the most recent duplicate: https://stackoverflow.com/questions/46062417/how-to-declare-a-string-with-double-quotes-in-query-config-object-in-node-postgr

**Comment by ashishjain14** [comment]
Thanks, that helps to run the query. However my user authentication fails for the created new user. If I write the same query as below it works with out any issue.
'CREATE USER '+ username + ' WITH PASSWORD ' + "'"+password+"'";

**Comment by vitaly-t** [comment]
That means you are not escaping it right. `username` is an SQL Name, while `password` is a string value.

This means the query must be:

```sql
db.query('CREATE USER $1:name WITH PASSWORD $2', ['myUserName', 'password']);
```

**Comment by ashishjain14** [comment]
Super awesome, it works now thanks a lot.
