### ISSUE TITLE
ERROR TypeError: Cannot read property 'options' of undefined

### ISSUE THREAD

**Issue by cryptcoin-junkey** [vitaly-t/pg-promise#396]
I got errors like logs below.
I see it's my failure that conections are over limit.
The issue is next to the error.

I'm not sure but it should be `cnOptions` instead of `options` ?

```
(snip)
{ error: remaining connection slots are reserved for non-replication superuser connections
   at Connection.parseE (/usr/src/app/node_modules/pg/lib/connection.js:567:11)
   at Connection.parseMessage (/usr/src/app/node_modules/pg/lib/connection.js:391:17)
   at TLSSocket.<anonymous> (/usr/src/app/node_modules/pg/lib/connection.js:129:22)
   at emitOne (events.js:96:13)
   at TLSSocket.emit (events.js:191:7)
   at readableAddChunk (_stream_readable.js:178:18)
   at TLSSocket.Readable.push (_stream_readable.js:136:10)
   at TLSWrap.onread (net.js:561:20)
(snip)
 [Fri Sep 08 2017 01:44:03 GMT+0000 (UTC)] ERROR TypeError: Cannot read property 'options' of undefined
   at BoundPool.onError (/usr/src/app/node_modules/pg-promise/lib/database.js:1320:25)
   at emitTwo (events.js:106:13)
   at BoundPool.emit (events.js:194:7)
(snip)
```

**Comment by vitaly-t** [comment]
Duplicate of #354

**Comment by cryptcoin-junkey** [comment]
Hmm... I'm using v6.3.8 newer than v5.9.5 (described on #354).
Surely it is older than the newest. I'm going to upgrade it.

**Comment by cryptcoin-junkey** [comment]
I got same errors even tough I upgraded it to pg-promise@6.5.1.

**Comment by cryptcoin-junkey** [comment]
An additional issue possibly related this.

As you know, the default pool size on node-postgres is 10.
My PostgreSQL instance (actually on AzureDB) is assigned 50 connects.
It shouldn't be exhausted all connections if there is no bugs.

Just guess but I suspect there have some inconsistency between pg-pool and pg-promise...

**Comment by vitaly-t** [comment]
@cryptcoin-junkey can you come up with a usable reproducible example?

I will have a look at it when I get a chance ;)

**Comment by vitaly-t** [comment]
@cryptcoin-junkey Update [v6.5.2](https://github.com/vitaly-t/pg-promise/releases/tag/v.6.5.2) includes the change, though I will be surprised if it makes a difference.

**Comment by cryptcoin-junkey** [comment]
Thank you for your quick response. I tried 6.5.2. But it seems no effect.
I'll inspect it deeper today.

**Comment by vitaly-t** [comment]
@cryptcoin-junkey it contained the change you were looking for.

Looks you are gonna need to come up with a usable example that reproduces the issue. Otherwise I wouldn't even know where to look at.

**Comment by cryptcoin-junkey** [comment]
I found this : https://github.com/brianc/node-postgres/issues/1344
It looks node-postgres has some issues on using with AzureDB.
(also #354 was on AzureDB.)

I close this since there is less sense to analysis in situations where there have bugs in the dependent library.
I'll recheck this issue after brianc/postgres#1334 was resolved.

Thank you for your kind support.

**Comment by vitaly-t** [comment]
Issue  [brianc/node-postgres#1334](https://github.com/brianc/node-postgres/pull/1334) was merged there on June 20, and it is included into v6.4.2 that's used by this library.

**Comment by cryptcoin-junkey** [comment]
My mistake. Not brianc/node-postgres#1334 but brianc/node-postgres#1344.

**Comment by ubreddy** [comment]
upgrade to 6.5.2 doesnt fix the issue.  any final solution for this issue?

**Comment by vitaly-t** [comment]
@ubreddy as per the message above, you should follow this issue: https://github.com/brianc/node-postgres/issues/1344

From what I can see, it is still not resolved within the driver.

**Comment by ubreddy** [comment]
@vitaly-t  
the driver is still not updated.. There is a pull request pending.
meanwhile to avoid this crash is there a workaround?

**Comment by vitaly-t** [comment]
@ubreddy not that I know of, sorry.

**Comment by ubreddy** [comment]
making the pg point to this version resolves the issue..
"pg": "pasieronen/node-postgres#ssl-close-econnreset",
this pull request is pending.

**Comment by ubreddy** [comment]
@vitaly-t  can you update the dependency to 7.4.1  ? the driver is updated with the pull request.

**Comment by vitaly-t** [comment]
@ubreddy Current dependency is set as `"pg": "~7.4.0"`, which means it will install `7.4.1`, if you re-install the dependencies :wink:
