### ISSUE TITLE
FAQ should be updated.

### ISSUE THREAD

**Issue by cryptcoin-junkey** [vitaly-t/pg-promise#397]
https://github.com/vitaly-t/pg-promise/wiki/FAQ#how-to-access-the-instance-of-node-postgres-thats-used

```diff
- pgp.pg.defaults.poolSize = 20;
+ pgp.pg.defaults.max = 20
```

Reason: https://github.com/brianc/node-postgres/commit/3b3e52cdc2501f92a65cac4a5097143b29f2cfe4

**Comment by vitaly-t** [comment]
both versions work the same, no need for an update ;)

**Comment by cryptcoin-junkey** [comment]
I see. I agree there are less reason to fix now.
