### ISSUE TITLE
Unwanted backslash escaping

### ISSUE THREAD

**Issue by Inkata** [vitaly-t/pg-promise#398]
I'm using pg-promise with much success on many dozens of queries. All of them work fine except one.
It seems like pg-promise is stripping a backslash that I need to define a regexp match.

What I wrote is:
``` 
CASE when 
 p._is_delisted and p._delisted_reason ~* 'TXNNN\d{5,}' then
  'Transacción' else
 'FUUU' 
end as _field
```
but looking at the server logs it gets turned into:
``` 
CASE when 
 p._is_delisted and p._delisted_reason ~* 'TXNNNd{5,}' then
  'Transacción' else
 'FUUU' 
end as _field
```
This is inside an ES6 template literal, but only for newlines and general formatting, I am not building my queries by concatenating or anything. I format the queries like so:

```Javascript
let sql={
 text:`..sql statement with $1 placeholders between backtics`,
 values:[val1]
}
```

I tried to find some references to this particular issue, but found none. Would you consider this a bug?

Thanks!

**Comment by Inkata** [comment]
I did got it working by escaping the backslash, but it took me a while.

Maybe a brief note about naked backslash in the docs?

Thanks again.

**Comment by vitaly-t** [comment]
If you defined `\d` in JavaScript, then it is not valid for SQL,as it is a special symbol, and you should use `\\d` for that. But I'm only guessing, since you didn't show the actual code + value.
