### ISSUE TITLE
stream.read combined with QueryStream(1.1.1) does not return any rows

### ISSUE THREAD

**Issue by pdanpdan** [vitaly-t/pg-promise#403]
Hello.

I tried the new 6.8.0 with pg-query-stream 1.1.1.
It looks like in speex read.js in process function ```page = stream.read(readSize);``` returns null and I get no rows, so no call to receiver.

The code is working with 6.7.1 and 1.0.0

```
const streamRead = pgp.spex.stream.read;
const qs = new QueryStream( `
        SELECT
          "rowNr",
          "data"
        FROM app."tblFileTabInRows"
        WHERE "idFileTab"=$1
          AND "rowNr" > 0
        ORDER BY "id"
      `, [ definition.idFileTab ] );
return request[ "db" ]
            .stream( qs, ( stream: any ) => streamRead( stream, receiver ) )
```

**Comment by vitaly-t** [comment]
Looks like a bug in the new `pg-query-stream`, it stopped supporting `readable` event.

**Comment by pdanpdan** [comment]
Thank you. Should I open an issue there?

**Comment by vitaly-t** [comment]
> Thank you. Should I open an issue there?

I already have: [`readable` event no longer works](https://github.com/brianc/node-pg-query-stream/issues/37).

**Comment by vitaly-t** [comment]
@pdanpdan [Version 6.9.0]() got it all resolved.

For [pg-query-stream](https://github.com/brianc/node-pg-query-stream) you need to use option `readChunks: true` (see [stream.read](http://vitaly-t.github.io/spex/stream.html#.read)), as it presently only supports event `data`.

**Comment by pdanpdan** [comment]
It works as advertised, thank you very much.
