### ISSUE TITLE
Named parameters not supporting camel case anymore

### ISSUE THREAD

**Issue by jtwebman** [vitaly-t/pg-promise#412]
A resent change to this library makes it so it now doesn't support named parameters in a query that are camel cased.

Here is an example that use to work:
```javascript
conn.manyOrNone('select username from user where id = $[userId]', {userId: 1});
```

This now errors with an error: `Property 'userId' doesn't exist` stack starting here `at query.replace.name (/usr/src/app/node_modules/pg-promise/lib/formatting.js:142:19)`.

**Comment by vitaly-t** [comment]
I cannot reproduce the issue.

What version of pg-promise are you using? Do be absolutely sure, do this:

```js
console.log(db.$config.version);
```

**Comment by vitaly-t** [comment]
Something doesn't add up. When it comes to supporting camel cases, the library has very comprehensive set of tests. They must be something important missing in your example, is what I suspect.

**Comment by jtwebman** [comment]
`conn.$config.version` = `6.10.2` from the log output and here are the exact values I am passing as it is a more complex query then the example above:

This is how I call it:

```javascript
return conn.manyOrNone(query, queryValues);
```

This is what is in query:
```sql
WITH partner_members (partner_id, member_id) AS (
  SELECT DISTINCT
     p.id,
     m.id
  FROM partner AS p
  INNER JOIN rider_group AS rg ON p.id = rg.partner_id
  INNER JOIN rider_group_member AS rgm ON rg.id = rgm.rider_group_id
  INNER JOIN rider_group_member_status AS rgms ON rgm.status = rgms.id
  INNER JOIN member AS m ON rgm.member_id = m.id
  WHERE p.agency = $[agency]
  AND rgms.name = 'active'
), partner_access (partner_id) AS (
  SELECT DISTINCT
    c.partner_id
  FROM contact AS c
  WHERE c.auth_user_id = $[authUserId]
)
SELECT
  p.id,
  p.type,
  pt.name AS "typeName",
  ps.name AS status,
  p.name,
  p.description,
  p.url,
  COUNT(pm.member_id)::integer AS "riderCount"
FROM partner p
INNER JOIN type AS pt ON pt.id = p.type
INNER JOIN status AS ps ON ps.id = p.status
LEFT JOIN partner_members AS pm ON p.id = pm.partner_id
LEFT JOIN partner_access AS pa ON p.id = pa.partner_id
WHERE p.agency = $[agency]
AND (1=$[accessToAll] OR pa.partner_id IS NOT NULL)
GROUP BY p.id, p.type, pt.name, ps.name, p.name, p.description, p.url
```

This is what I am passing in queryValues:
```javascript
{
  "agency": "san-diego",
  "authUserID": 1,
  "accessToAll": 1
}
```

**Comment by vitaly-t** [comment]
`authUserId` != `authUserID` 😄

**Comment by jtwebman** [comment]
Wow, so sorry!

**Comment by vitaly-t** [comment]
No worries, it happens! :smile:
