### ISSUE TITLE
Best practice for dynamic column names?

### ISSUE THREAD

**Issue by MattBz** [vitaly-t/pg-promise#415]
One time the query should look like

```sql
SELECT colum1 FROM table...
INNER JOIN...
```

but it should also be able to look like this

```sql
SELECT colum1, colum2, column3,
INNER JOIN ...
LEFT JOIN...
```

Can this be done with query files? If not, how would it look like in Javascript?

Thanks!

**Comment by vitaly-t** [comment]
```sql
SELECT ${columns:name} FROM table...
INNER JOIN...
```
in JavaScript:
```js
const values = {
    columns: ['column1']
};

if (/*need to add columns*/) {
    values.columns = values.columns.concat(['column2', 'column3']);
}
```

**Comment by vitaly-t** [comment]
Following this question, I did a complete rewrite of the [SQL Names] documentation, which now explains everything nicely, with examples.

**Comment by MattBz** [comment]
Thank you for your detailed answer!

Regarding adding addtional JOINS and other parts of the query dynamically . Would I have to use "Raw Text" then?

**Comment by vitaly-t** [comment]
> Regarding adding addtional JOINS and other parts of the query dynamically . Would I have to use "Raw Text" then?

Yes.

**Comment by MattBz** [comment]
Okay, thank you!
