### ISSUE TITLE
db.func with named parameters?

### ISSUE THREAD

**Issue by msageryd** [vitaly-t/pg-promise#423]
Is there any way to use the func() method with named parameters? The documentation only shows an array with parameter values as possible input.

**Comment by vitaly-t** [comment]
> Is there any way to use the func() method with named parameters?

No. The method takes an array of dynamic parameters, which normally doesn't go along with named parameters that are all known in advance.

You can just execute the function yourself:

```js
db.any('SELECT * FROM my_func_name(${param1}, ${param2})', {param1, param2})
```

**Comment by msageryd** [comment]
Thanks.
I thought func was neat, but I'm using the SELECT statement instead so I can see what I put in.
