### ISSUE TITLE
typedef out of sync with real API

### ISSUE THREAD

**Issue by lifeiscontent** [vitaly-t/pg-promise#425]
I've got a function here:

``` ts
export const close = <T>(db: pgPromise.IConnected<T>): void => {
  db.done()
  db.client.end()
}
```

but typescript complains about `end` property not existing on client, when it obviously does.

**Comment by vitaly-t** [comment]
You are not supposed to call it directly, ever! That's why it is not there.

Calling `db.done()` will internally call it correctly when it is the right time.

**Comment by lifeiscontent** [comment]
@vitaly-t thanks, didn't know that.

**Comment by pyramation** [comment]
@vitaly-t `Calling db.done() will internally call it correctly when it is the right time.`

so, when is the right time? I'm using `db.done()` and the client is not disconnecting when I need it (essentially after I call `db.done()`

**Comment by vitaly-t** [comment]
@pyramation what do you mean the client is not disconnecting?

Best is to provide an example of what you you doing ;)

**Comment by pyramation** [comment]
Sure! thanks for the response ;) I’m building a module to spin up temporary databases and destroy them for testing purposes.

I made a wrapper for `close`ing because calling `db.client.end()` was the only way to achieve a true disconnection with db client:

```
export const close = (db: any): void => {
  db.done()
  db.client.end()
}
```

All I have to do to create errors and non-passing tests, it comment out the line that calls `db.client.end()`:

https://github.com/pyramation/pg-utils/blob/master/src/lib/connection.ts#L16

When I do this, as it’s cleaning up the database, postgres is not too happy because the client is still connected:

```
 Command failed: dropdb -U postgres -h localhost -p 5432 testing-db-95ad9251-680c-4d61-b97d-56cb4f828761
    could not find a "dropdb" to execute
    dropdb: database removal failed: ERROR:  database "testing-db-95ad9251-680c-4d61-b97d-56cb4f828761" is being accessed by other users
    DETAIL:  There is 1 other session using the database.
```

**Comment by vitaly-t** [comment]
@pyramation You cannot call `client.end()` against connections managed by the pool, it is against the API of the underlying driver `node-postgres`, and against the overall concept of automatic connection management.

There are two types of connections - automatic (via the pool), and independent - when you call [connect], passing it `{direct: true}`. For the latter, calling `.done()` will result in immediate physical disconnection. See the API :wink:

[connect]:http://vitaly-t.github.io/pg-promise/Database.html#connect

**Comment by vitaly-t** [comment]
@pyramation did you get this working as per my earlier comments?

**Comment by pyramation** [comment]
@vitaly-t yes! thank you. Fixed my issue perfectly :) cheers!
