### ISSUE TITLE
Conditionally formatting/modifying a query loaded with QueryFile

### ISSUE THREAD

**Issue by vince166** [vitaly-t/pg-promise#426]
Is it possible to conditionally formatting a query loaded by QueryFile? For example, we have one use case the predicate would be either "= number" or "IS NULL", and another user case where the predicate could be either " ~ pattern" or "= pattern". Is there a way to load a common query by QueryFile and then append to it conditionally?

**Comment by vitaly-t** [comment]
`QueryFile` formats the query with the variables as you provide those. So what stops from applying htose any way you want?

**Comment by vitaly-t** [comment]
Or are you talking about a single generic query file that needs to be pre-formatted differently upon loading?

**Comment by vince166** [comment]
Thanks for quick response. I was under the impression that a query, once loaded by QueryFile, can no longer be appended to.  Please let me know if I was wrong. For example:  two complex queries only vary by one predicate: "col1 = $1" or "col1 IS NULL".  We want to take advantage of QueryFile to maintain the query in a file while still want to be able to append to the query conditionally (so that we don't have to create two sql files that are almost identical). It would obviously work if the common part of the query is maintained as a string in code, but I am not sure how it would work with QueryFile.

**Comment by vince166** [comment]
Now I think the return from QueryFile is just a string. So there should be no problem modifying it further. I will try this. Thanks.

**Comment by vince166** [comment]
Hmm. The return from QueryFile is an object with a 'query' getter. But I'm not sure if it makes sense to modify a "prepared" query, and then prepare it again: 
`db.any(sqlByQueryFile.query + (isNullCase ? 'AND col1 IS NULL' : 'AND col1 = $1), targetCol1Value); `

**Comment by vitaly-t** [comment]
You can never do things like this: `sqlByQueryFile.query`. In fact, in the latest version of the library it won't even let you.

You must add a variable in your generic query and then inject the variable part, through, ahem a variable, obviously.

**Comment by vitaly-t** [comment]
Your generic SQL query:

```slq
-- some generic part here

-- dynamic part:
${condition:raw}

-- more generic part
```

**Comment by vince166** [comment]
Aha, that's how we use `:raw`. Thank you so much!
