### ISSUE TITLE
How do I write tx calls with async/await?

### ISSUE THREAD

**Issue by matbz** [vitaly-t/pg-promise#427]
At the moment I have thise code:

`  createMultiple(list) {
    db.tx(t => {
      const queries = list.map(l => {
        const query = SQL`
        insert into categorybudgeted
        (category_id, budgeted_date, amount)
        values
        (${l.category_id}, ${l.budgeted_date}, ${l.amount})
        `;
        return t.none(query);
      });
      return t.batch(queries);
    })
      .then(data => {
        return;
      })
      .catch(error => {
        console.log(error);
      });
  }`

It works. But I want the whole method as async await. What would I need to change inside to make this work. Sorry for this basic question. Thanks!

**Comment by vitaly-t** [comment]
First of all, [Contributing Notes](https://github.com/vitaly-t/pg-promise/blob/master/CONTRIBUTING.md).

Examples of such transactions can be found everywhere, if you searched for those...

```js
db.tx(async t =>{
    // await statements
});
```
