### ISSUE TITLE
using psql variable format in QueryFiles

### ISSUE THREAD

**Issue by bsouthga** [vitaly-t/pg-promise#428]
First off, thanks for making a great library!

I was wondering if there was a way to use `psql` style variables in files parsed by `QueryImport`. If this was possible, it would make it nicer to debug an sql script in isolation before using in app code via `pg-promise`.

For example, instead of 

```sql
SELECT * FROM foo WHERE bar = $1
```

It would be awesome if we could do

```sql
SELECT * FROM foo WHERE bar = :myvariable
```

and have `pg-promise` be able to handle the named interpolation.

**Comment by vitaly-t** [comment]
This library does named interpolation under the [Named Parameters](https://github.com/vitaly-t/pg-promise#named-parameters), which is far more advanced, as it supports both [Formatting Filters](https://github.com/vitaly-t/pg-promise#formatting-filters) and nested names.

**Comment by bsouthga** [comment]
yeah woops, I meant `QueryFile`. The desired usecase is basically wanting to be able to run the same sql script from the command line under `psql -f myfile.sql -v1=12` for debugging while also being able to import the script into `pg-promise`, without having to switch between variable notation (`:v1` vs `${v1}`).

**Comment by vitaly-t** [comment]
The `${name:filter}` syntax is more verbose, as it supports filters, so it doesn't map back to `:name` syntax. And for the opposite direction, you''d have to do the transformation yourself, i'm afraid.

**Comment by bsouthga** [comment]
makes sense, thanks

**Comment by vitaly-t** [comment]
@bsouthga You are welcome!

Just worth saying that once you start using the full syntax of the [Named Parameters], with use of [Formatting Filters], [Nested Named Parameters] and [Custom Type Formatting] you will see that whatever psql can support is just way too basic and of little help in projects that do need the flexibility :wink:

[Named Parameters]:https://github.com/vitaly-t/pg-promise#named-parameters
[Nested Named Parameters]:https://github.com/vitaly-t/pg-promise#nested-named-parameters
[Custom Type Formatting]:https://github.com/vitaly-t/pg-promise#custom-type-formatting
[Formatting Filters]:https://github.com/vitaly-t/pg-promise#formatting-filters
