### ISSUE TITLE
How to check connections is alive?

### ISSUE THREAD

**Issue by trylovetom** [vitaly-t/pg-promise#429]
After I call this function `pgp.end()`, how can I check connection is dead or alive?

```
export class PostgresStorageAdapter {
  // Private
  _collectionPrefix: string;
  _client;
  _pgp;

  constructor({
    uri,
    collectionPrefix = '',
    databaseOptions
  }) {
    this._collectionPrefix = collectionPrefix;
    const { client, pgp } = createClient(uri, databaseOptions);
    this._client = client;
    this._pgp = pgp;
  }

  handleShutdown() {
    if (!this._pgp) {
      return
    }
    this._pgp.end();
  }
...
```

```
  it('handleShutdown, close connection', (done) => {
    const adapter = new PostgresStorageAdapter({ uri: databaseURI });
    adapter.handleShutdown();
    done();
  });
```

What's different after `pgp.end()`. And how could I test it ?

**Comment by vitaly-t** [comment]
For one thing, you should not use `pgp.end()`, it is just bad coding. I should update both library and documentation for that. That call kills all of the connection pools in the library.

If you want to shut down a connection pool on the database object that you allocated, use `db.$pool.end()` instead. But even then, it is normally not needed, except in some special cases, like to exit a process without delay.

So, you need to understand the implications of that call.

> What's different after `pgp.end()`. And how could I test it ?

After you kill the pool, all database methods will fail with error: `Connection pool of the database object has been destroyed.`

**Comment by trylovetom** [comment]
@vitaly-t  It's useful. Thanks a lot.
I change `_pgp.end()` to `_client.end()`.
And test it expect `db.$pool.end()` is `true`.

reference: https://github.com/parse-community/parse-server/pull/4361

**Comment by vitaly-t** [comment]
You are welcome! Though I have no idea what your `_client` represents, you didn't show that.

**Comment by trylovetom** [comment]
`_client` in parse-server [PostgresStorageAdapter.js](https://github.com/trylovetom/parse-server/blob/953c84b5045e5aa00a572da2896827b5e3487fb6/src/Adapters/Storage/Postgres/PostgresStorageAdapter.js#L573)

**Comment by vitaly-t** [comment]
[Library de-initialization](https://github.com/vitaly-t/pg-promise#library-de-initialization) has been fully updated (documentation).
