### ISSUE TITLE
Named Parameters Not Working with WHERE col IN (values)

### ISSUE THREAD

**Issue by AmberDean** [vitaly-t/pg-promise#430]
I'm having trouble getting the ':csv' suffix to work for named parameters.  Is this an issue on my end, or is this feature not supported?  If it's not supported, is there any particular reason why?

```js
const foo = [1, 'two', 3, 'four'];

db.any('SELECT * FROM table WHERE id IN ($foo:csv)', {foo})
    .then(data => {
        // success;
    })
    .catch(error => {
        console.log('ERROR:', error);
    }); 
```

**Comment by vitaly-t** [comment]
Your variable syntax is incorrect, it is not `$foo`, it is `${foo}`, see [Named Parameters], so the full formatting variable is `${foo:csv}`.

Please next time format your code properly ;)

[Named Parameters]:https://github.com/vitaly-t/pg-promise#named-parameters

**Comment by AmberDean** [comment]
Got it.  I was actually using ${foo}:csv

**Comment by vitaly-t** [comment]
`${foo}:csv` is also as incorrect, see [Formatting Filters](https://github.com/vitaly-t/pg-promise#formatting-filters).
