### ISSUE TITLE
Insert "DEFAULT" value in bulk insert with helpers.

### ISSUE THREAD

**Issue by YaTree** [vitaly-t/pg-promise#431]
Hello.

Is it possibe to use `helpers` for request like this:

```sql
INSERT INTO core.products (product_id) VALUES (DEFAULT),(DEFAULT),(DEFAULT),(DEFAULT),(DEFAULT),(DEFAULT),(DEFAULT),(DEFAULT)  returning product_id;
```

So question is how to use `helpers` to make request like this if it is possible.
In my case table products has only one field - `product_id`, and the field is auto-incremental and I need to add there several/a lot of new "product_id".

For now I just generate string for this request. 

This is not an issue, but a question :)

**Comment by vitaly-t** [comment]
You can define the column like this:
```js
{name: 'product_id', mod: ':raw', init: () => 'DEFAULT'}
```
See [Column].

[Column]:http://vitaly-t.github.io/pg-promise/helpers.Column.html
