### ISSUE TITLE
Issue with :csv in Prepared Statements

### ISSUE THREAD

**Issue by njlr** [vitaly-t/pg-promise#435]
I have a query like this: 

```javascript=
    const things = [ 'apples', 'oranges' ];
    const q = {
      name: 'my-query', 
      text: ```INSERT INTO things (id, name)
        SELECT 
          1 AS id, 
          name
        FROM unnest(ARRAY[ ($1:csv) ]) name ```,
      values: [ things ]
    };
    await db.query(q);
```

But this gives the error: 

    TypeError: "" is not a function...

Have I misunderstood `:csv`?

**Comment by vitaly-t** [comment]
You misunderstood [Prepared Statements] that are executed on the server side, while `:csv` is the client-side filter.

[Prepared Statements]:http://vitaly-t.github.io/pg-promise/PreparedStatement.html

**Comment by njlr** [comment]
I have to admit that I'm a bit confused by the API. 

For example, this gives the same error: 

```javascript=
await db.one(
    ```INSERT INTO users (username, password_hash) 
      VALUES ($<username>, $<passwordHash>) 
      RETURNING id```, {
      username,
      passwordHash,
    });
```

However, it seems to follow the same conventions as this example: https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#named-parameters

**Comment by vitaly-t** [comment]
The same error? That's hardly possible, unless you set flag `pgFormatting` during the library's initialization. Did you?

**Comment by njlr** [comment]
I did not set that flag. 

Interestingly this works: 

```javascript
await db.one(
    'INSERT INTO users (username, password_hash) 
      VALUES ($<username>, $<passwordHash>) 
      RETURNING id', {
      username,
      passwordHash,
    });
```

**Comment by vitaly-t** [comment]
Why are you using triple `````? That's what's causing it.

See:
```js
console.log(``````);
```
the same output.

And this got nothing to do with this library.

**Comment by vitaly-t** [comment]
P.S. I have just asked a related question on StackOverflow: [Nested template string error in Node.js
](https://stackoverflow.com/questions/47903470/nested-template-string-error-in-node-js).

**Comment by njlr** [comment]
Yep, I got the JS syntax wrong. Thanks 👍
