### ISSUE TITLE
Created promise issue/warning.

### ISSUE THREAD

**Issue by andyzaharia** [vitaly-t/pg-promise#436]
Hi Vitaly, 

Do you know why the batch transaction will throw a promise warning?

![Screen shot](https://i.imgur.com/h9hq346.png)

This is the piece of code that throws the warning.. . somehow a promise is not handled correctly, I looked into the provided examples and it doesnt look like I'm doing anything wrong. (Thou I'm actually new to nodejs and I definitely can screw up things).

```javascript
        db.tx(t => {
           var order = t.none("DELETE FROM orders WHERE id = 267");
           return t.batch([order]);

        }).then(data => {
          console.log("Transaction finished.");
          reply({
            statusCode: 'Success',
            data: data,
            message: 'Deleted order.'
          });
        }).catch(error => {
            console.error(error);
            reply(error); 
        });
```

Any ideas what might be the cause? 

Thank you and thanks a lot for creating this awesome library!

ps. I'm using the latest version.

**Comment by vitaly-t** [comment]
According to your own error log, it is pointing at line 293, which isn't the code you are showing here.

**Comment by andyzaharia** [comment]
Thanks for the fast response!

I was looking at the code, the problem is I dont have a domain.js file in my project. Searched in node_modules... nothing in there. Which definitely seems really weird 🙃, will try to look into it more maybe I find something. 

Learning by debugging... 😊

**Comment by vitaly-t** [comment]
It may or may not be one of those stupid cases where `Bluebird` wants you to return promise even when it is handled locally, i.e. replacing `db.tx()` with `return db.tx()`. You can try it ;)
