### ISSUE TITLE
Providing custom pg library on pg-promise initialisation 

### ISSUE THREAD

**Issue by timReynolds** [vitaly-t/pg-promise#437]
AWS X-Ray includes functionality to capture trace information from the `pg` library by decorate it in the provided `aws-xray-sdk-postgres`. 

Is it possible to to initialise `pg-promise` with a decorated version of pg? Based on the Initialization Options documentation and skimming the code this doesn't look possible. 

Allowing users to provider a version of `pg` probably opens up a raft of compatibility issues. Is their a way of supporting/using `aws-xray-sdk-postgres` in a maintainable way?

**Comment by vitaly-t** [comment]
> Is it possible to to initialize pg-promise with a decorated version of pg?

No idea, needs to be looked into. As of now, there is no provision for that.

> Allowing users to provider a version of pg probably opens up a raft of compatibility issues.

It definitely would, the driver had plenty of breaking changes from one version to the next, which were accommodated through changes within this library.

**Comment by vitaly-t** [comment]
I have just read the documentation and examples of using `aws-xray-sdk-postgres`, and from what I could see, everything you can do with that module is already available within `pg-promise`, simply start using [pg-monitor], and you will get the best logging for everything.

Alternatively, there are events, such as [query], etc, which [pg-monitor] simply handles in its own way, but you can use those yourself, directly.

[query]:http://vitaly-t.github.io/pg-promise/global.html#event:query
[pg-monitor]:https://github.com/vitaly-t/pg-monitor

**Comment by timReynolds** [comment]
@vitaly-t thanks for the quick response. Writing something similar to `aws-xray-sdk-node` that works with pg-promise is probably my best option. I'll take a look at that as an option, the implementation looks straight forward.

**Comment by vitaly-t** [comment]
@timReynolds why not just use [pg-monitor]?

[pg-monitor]:https://github.com/vitaly-t/pg-monitor

**Comment by vitaly-t** [comment]
I take it the subject has been exhausted? I'm closing it then....

**Comment by timReynolds** [comment]
Sorry I've not had a chance to look at this. Yea, I was thinking of using pg-monitor to some extent. I'll come back when I've looked at this more.
