### ISSUE TITLE
How to share transaction across multiple node processes?

### ISSUE THREAD

**Issue by tsemerad** [vitaly-t/pg-promise#439]
I'm trying to create a Google Cloud function that loads large datasets into Postgres. My function currently works fine on small datasets, but for larger datasets it will time out since the maximum execution time on Google Cloud Functions is 9 minutes. To work around this, and to just make importing large datasets quick, I'd like to execute multiple processes in parallel to insert.

Let's say I have 5 million rows to insert. I'd like to launch 50 node JS Cloud Functions in parallel which each insert 100,000 rows. Would it be possible to have each of these 50 node executions using the same transaction, so that if one fails they all roll back? I'm looking into making my insert function faster by following the guidelines [here](https://github.com/vitaly-t/pg-promise/wiki/Data-Imports#massive-inserts), but I'd still like to know if this "transaction sharing" is possible, or if I should be looking into something else.

**Comment by vitaly-t** [comment]
Read [Data Imports](https://github.com/vitaly-t/pg-promise/wiki/Data-Imports).

**Comment by tsemerad** [comment]
Thanks for the quick response. That answers all of my questions. It's good to know that what I was considering trying is not supported by this library, and probably a bad idea anyway. I'll work on speeding up my inserts and see if that's sufficient for my use case. Thanks.
