### ISSUE TITLE
Ой, я не знал что вы это удалите все!

### ISSUE THREAD

**Issue by khusamov** [vitaly-t/pg-promise#44]
Уф, а восстановить уже нельзя??? Если бы я знал что вы удалите вопрос, я бы скопировал... там же много было информации которую я еще не усвоил(((

**Comment by vitaly-t** [comment]
I didn't remove anything: https://github.com/vitaly-t/pg-promise/issues/43

I simply closed the question, as I thought it was fully answered. So, is this one, I believe, so please close it if so.

P.S. Also, please do not open new issues in Russian language.

**Comment by khusamov** [comment]
I got it! Thank you!
