### ISSUE TITLE
authentication error using Ubuntu 

### ISSUE THREAD

**Issue by t-0-m-1-3** [vitaly-t/pg-promise#441]
![screenshot from 2018-01-02 11-10-10](https://user-images.githubusercontent.com/20537914/34490458-f6f4f9ac-efad-11e7-8c18-7b7b3a238c91.png)
I'm having some issues trying to connect to the database using pg-promise.
I'm able to pull in and create data using the command line commands for psql but cannot get the module commands to work. 
I'm receiving a auth error from my username and the default one. I've tried removing and reinstalling and changing the defaults. 
I know it's something I'm doing, but tunnel vision won't let me see it.
Any help is appreciated

**Comment by vitaly-t** [comment]
Problems with authentication is best to investigate on StackOverflow, as they are generic, always outside of this library, and that's why we do not address them here.

**Comment by t-0-m-1-3** [comment]
I'm sorry for the clutter, I did end up fixing it by changing the uname/passwords again.
