### ISSUE TITLE
Improve error message for empty argument to :csv ?

### ISSUE THREAD

**Issue by njlr** [vitaly-t/pg-promise#442]
I have a query like this: 

```javascript=
const fetchBooks = (db, titles) => db.query(`SELECT id
    FROM books 
    WHERE title IN ( $<titles:csv> ) `, {
      titles,
    });
```

When `titles` is `[]`, the error message is quite confusing: 

> ... error: syntax error at or near ")" ...

This is the error forwarded from the underlying `pg` library, but perhaps `pg-promise` could provide a better error for this scenario? 

Something like... 

> Empty arrays are not valid for the ":csv" syntax. 

(Related: https://github.com/brianc/node-postgres/issues/1079)

**Comment by vitaly-t** [comment]
> This is the error forwarded from the underlying pg library, but perhaps pg-promise could provide a better error for this scenario?

It can't, because it doesn't know the context in which filter `:csv` is used, and formats it correctly, according to the filter's specification.

You should instead check `titles.length`, and when it is 0, do not execute such invalid query at all.

**Comment by njlr** [comment]
Yes, that was my work-around. It would have been easier to identify the error with a more specific message though. 

If there are cases in which `:csv` is valid without any elements then my suggestion will not work.

**Comment by vitaly-t** [comment]
> If there are cases in which :csv is valid without any elements then my suggestion will not work.

There are plenty.

**Comment by vitaly-t** [comment]
The same issue opened on StackOverflow: https://stackoverflow.com/questions/48344888/best-practice-for-creating-sql-select-queries-while-handling-potential-undefined

**Comment by vitaly-t** [comment]
More on this question: [WHERE col IN Query with empty array as parameter
](https://stackoverflow.com/questions/49188085/where-col-in-query-with-empty-array-as-parameter/).
