### ISSUE TITLE
Impractical type for db.task

### ISSUE THREAD

**Issue by sgronblo** [vitaly-t/pg-promise#445]
I think the type for db.task `task<T=any>(cb: (t: ITask<Ext> & Ext) => T): XPromise<T>` is a bit impractical for most use cases. Your `cb` function is probably going to be asynchronous in 99% of all cases, which means that the end result of db.task will be `XPromise<XPRomise<T>>` in most cases.

You can see this in action also in this route in the TS pg-promise-demo:

```
// add a new user, if it doesn't exist yet, and return the object:
GET('/users/add/:name', req => {
    const x = db.task('add-user', t => {
        return t.users.findByName(req.params.name)
            .then(user => {
                return user || t.users.add(req.params.name);
            });
    });
    return x
});
```

Where hovering over the x in VSCode shows that the type is `Promise<Promise<any>>`. I know that calling then on a double-promise works the same as if it was just a normal Promise because of `then`, but it makes it a bit ugly if you wanna put this call to db.task inside of a service module. It seems you have to either make your functions return double-wrapped promises or unwrap the inner promise manually.

I know this would be a breaking change for the probably small minority of people who are passing a synchronous function to db.task, but it seems like it would make things a lot easier for anybody who is actually doing database calls inside of db.tasks callback.

I think it would make more sense for the type to be:
`task<T=any>(cb: (t: ITask<Ext> & Ext) => PromiseLike<T>): XPromise<T>`

This way you could just call a normal database method which returns XPromise and that would also satisfy PromiseLike but if you use any other Promise library in your own code that would also satisfy promise like. If you for some reason are not doing anything asynchronous you would have to wrap your return in a Promise.resolve. But I think it would be better to place the inconvenience on the synchronous function case rather than the async case.

What do you think?

**Comment by sgronblo** [comment]
Another possibility might be to use `Promise.resolve` on the result of the callback and have the type be:

`task<T=any>(cb: (t: ITask<Ext> & Ext) => T | PromiseLike<T>): XPromise<T>`

This way the change wouldn't be breaking. But people who return promises would not get double-wrapped promises either.

**Comment by sgronblo** [comment]
Dug around some more. If I understand `Task.execute` correctly there is a check at the end to see if the returned object is PromiseLike and if so just return it as is. It seems that maybe just changing the type definition would work for most cases. But to make things more correct, perhaps the PromiseLike interface check should just be dropped and we should just call `$p.resolve(result)` no matter what to make sure that what we get is actually of type XPromise and not PromiseLike.

**Comment by vitaly-t** [comment]
> Your cb function is probably going to be asynchronous in 99%

It doesn't matter what `cb` does, the result is always treated as asyncronous.

**Comment by vitaly-t** [comment]
Fixed with [this commit](https://github.com/vitaly-t/pg-promise/commit/4c18687f75b62601de685b8630ce2fc205743c0f), will be available in the next release.

**Comment by vitaly-t** [comment]
@sgronblo [Release v7.4.0](https://github.com/vitaly-t/pg-promise/releases/tag/v.7.4.0) now has the update :wink:
