### ISSUE TITLE
Question about connection pool options

### ISSUE THREAD

**Issue by sgronblo** [vitaly-t/pg-promise#446]
We are planning to use `pg-promise` inside of a Lambda. I still need to do some more research but currently it seems to me that connection pooling would be unnecessary at best and harmful at worst within Lambda. Many sources I've seen indicate that concurrent invocations of Lambdas always happens in separate execution contexts. It is only after a Lambda function invocation has finished that it _may_ be re-used to serve another function. This seems to defeat the purpose of doing connection and would actually have a negative effect if you used a pool that greedily starts connections. Even though that would make sense in a traditional node.js app.

Due to the above restriction it seems important to be able to control the pool settings when using pg-promise.

1. I noticed from one of the examples that `IMain` can be called with either a connection string or a `Tconfig = pg.TConnectionParameters`. However it seems this interface doesn't seem to accept the connection configuration as a connection string? We would prefer to set the connection string as an environment variable for the Lambda and use that for connection without having to parse it into its separate components (host, username, etc)

2. The `pg-pool` seems to be used under the hood for the pool. The `pgpool.Pool` constructor seems to allow specifying both an upper and a lower limit (max, min) for the pool size. How is the poolSize used to specify max and min when using pg-promise?

**Comment by vitaly-t** [comment]
> However it seems this interface doesn't seem to accept the connection configuration as a connection string?

It accepts both connection string and a connection config object. What is `connection configuration as a connection string` - there is just a connection string. 😕 

> How is the poolSize used to specify max and min when using pg-promise?

In the exact same way as for the `pg-pool` - `min`, `max`, `poolSize`. What seems to be the issue?

**Comment by sgronblo** [comment]
1. I was just wondering if it was possible to use both a connection string AND a config at the same time.

`pg.TConnectionParameters` doesn't seem to contain any property where you could assign the connection string. Instead you provide the host, username, etc directly. But maybe this would be ok to just use `pg-connection-string` to parse the values.

2. I didn't notice `min` and `max` when I checked earlier. Sorry about that.

**Comment by vitaly-t** [comment]
> I was just wondering if it was possible to use both a connection string AND a config at the same time.

No, it is not. Either one or the other.

**Comment by sgronblo** [comment]
Oh one more follow-up question: Can I disable pooling?

**Comment by vitaly-t** [comment]
You can either set the pool size to 1, which will prevent creation of more than one connection, or you can make use of the global connection. However, for the latter you would have to monitor yourself, in case the connection is lost.

**Comment by sgronblo** [comment]
Thanks. So the pool will keep track of whether the connection has been disconnected and re-connect it if necessary?

**Comment by vitaly-t** [comment]
> the pool will keep track of whether the connection has been disconnected and re-connect it if necessary?

Yes, as its one of the most important functions.

**Comment by vitaly-t** [comment]
@sgronblo In version 8.0.0 it is now possible to use both connection string and the config:

```js
const connection = {
   connectionString: 'postgres://user...',
   database: 'db-name',
   user: 'user-name'
};
```

i.e. the same way that [connectionString](https://github.com/brianc/node-postgres/blob/master/lib/defaults.js#L26) was intended in the driver:

>// a Postgres connection string to be used instead of setting individual connection items
  // NOTE:  Setting this value will cause it to override any other value (such as database or user) defined
  // in the defaults object.
