### ISSUE TITLE
Make documentation about transactions more explicit about when a rollback will be performed

### ISSUE THREAD

**Issue by sgronblo** [vitaly-t/pg-promise#447]
I would assume that the transaction gets rollbacked when the promise returned by the function you pass to tx is rejected, but it would be nice to have this explained more explicitly in the documentation.

**Comment by vitaly-t** [comment]
It is kind of implied, that returning a rejected promise or simply throwing an error from the transaction callback will result in `ROLLBACK`.

**Comment by sgronblo** [comment]
Thanks.

**Comment by vitaly-t** [comment]
[This commit](https://github.com/vitaly-t/pg-promise/commit/ec178295443e0eec23bf740a17c4a953a49881a9) adds this onto the main page also :wink:

**Comment by TheRusskiy** [comment]
@vitaly-t probably a stupid question, but what happens if node process is `ctrl+c`\`ed?
To me it strangely looks like if the transaction isn't rolled back.

**Comment by vitaly-t** [comment]
@TheRusskiy This is outside the scope here, as nothing this library can do.

See also [What are the consequences of not ending a database transaction?](https://stackoverflow.com/questions/33815267/what-are-the-consequences-of-not-ending-a-database-transaction).
