### ISSUE TITLE
Inserting multiple values at once

### ISSUE THREAD

**Issue by willm** [vitaly-t/pg-promise#451]
I'd like to insert many rows into a table at once something like:

```sql
CREATE TEMP TABLE tmp(
  name character varying(10),
  age integer
);

INSERT INTO tmp (name, age)
VALUES ('Bob', 34), ('Alice', 25);
```

I'd like to due this in one call in a similar way to the python [postgres adapter](http://initd.org/psycopg/docs/extras.html?highlight=execute_values#psycopg2.extras.execute_values).

I'd like to protect against SQL injection and therefor avoid concatenating strings. I'd rather avoid looping over each row to insert for performance reasons.

Is there a way to do this with pg_promise?

**Comment by willm** [comment]
I think I found a solution doing the following, since this is using the same substitution function that pg-promise uses, I guess it's fairly safe?:

```javascript
const pgp = require('pg-promise');
const connection = {};
const db = pgp(connection);

const inserts = [
  {name: 'Bob', age: 34},
  {name: 'Alice', age: 25},
].map(
  person => pgp.as.format(
    'INSERT INTO tmp (name, age) VALUES (${name}, ${age})',
    person
  );

const query = [
  `CREATE TEMP TABLE tmp(
    name character varying(10),
    age integer
  )`
].concat(inserts).join('\n');

await db.none(query);
```

**Comment by vitaly-t** [comment]
This is one of the most duplicated question. See [Multi-row insert with pg-promise
](https://stackoverflow.com/questions/37300997/multi-row-insert-with-pg-promise).
