### ISSUE TITLE
Support setting statement_timeout

### ISSUE THREAD

**Issue by danihodovic** [vitaly-t/pg-promise#452]
I have a use case where I would like to set a statement_timeout for the Postgres client. I want queries that run longer than 30 seconds to be killed.

Postgres docs: https://www.postgresql.org/docs/9.4/static/runtime-config-client.html
node-postgres supports this use case: https://node-postgres.com/api/client.

Ideally this can be implemented as an option that's passed to the pg-promise client (https://vitaly-t.github.io/pg-promise/module-pg-promise.html).

Another possibility is to allow arbitrary queries to be ran on connection setup (https://github.com/vitaly-t/pg-promise/issues/328#issuecomment-359721726).

**Comment by vitaly-t** [comment]
It has always been supported. Have you even tried?

Just pass `statement_timeout` within your connection parameters.

**Comment by danihodovic** [comment]
It wasn't listed in the official docs (https://vitaly-t.github.io/pg-promise/module-pg-promise.html) so I assumed it wasn't used.

**Comment by vitaly-t** [comment]
> It wasn't listed in the official docs

You are pointing at the library's initialization options, not database connection parameters :wink:

**Comment by vitaly-t** [comment]
[Version 8.5.3](https://github.com/vitaly-t/pg-promise/releases/tag/v.8.5.3) started also supporting `query_timeout`.
