### ISSUE TITLE
suppressing NOTICE: logs

### ISSUE THREAD

**Issue by vekexasia** [vitaly-t/pg-promise#454]
Hello, I've been reading other issues related to notice messages but it seems i'm unable to get it working just the way I want.

I would like to suppress ALL `NOTICE:  ` messages as i'm running this in test environments when a lot of `TRUNCATE table CASCADE` are happening and test output is flooded by such `NOTICE: ` messages.

Is there a way to suppress them entirely?

**Comment by vitaly-t** [comment]
Can you do this using the base driver [node-postgres](https://github.com/brianc/node-postgres)?

If yes, then please show an example. Then I could figure out how to do it within this module.

And if you cannot do this in the base driver, then you won't be able to do it here either.

**Comment by vitaly-t** [comment]
Closing due to non-response. Will re-open, if there is any.
