### ISSUE TITLE
Query duration in receive event

### ISSUE THREAD

**Issue by kiejo** [vitaly-t/pg-promise#459]
I am currently in the process of upgrading to version 7, but I've noticed that the `duration` field of the `result` object in the `receive` event is gone.
I want to log the duration of all queries for monitoring and using the `receive` event has worked quite well in earlier versions of pg-promise. What would be the recommended solution for getting the duration of all executed queries in version 7?

**Comment by vitaly-t** [comment]
Patching `Result` object with duration was removed when new method [multiResult] was introduced, which would create ambiguity, as the array would contain `Result` objects without any `duration`.

This library now provides `duration` only within its own API, such as tasks + transactions, i.e. you can handle events `task` and `transact` and log `duration` from those.

**Comment by kiejo** [comment]
Thanks for the fast answer! I think it makes sense to not have this ambiguity on the `Result` object. Another approach that I think could work well, would be to make the `duration` available via the `event` that gets passed to `receive` as the third parameter. It could represent the complete duration of a database call regardless of whether it was called using `multiResult` or any of the other database methods. What do you think?
Overall, I don't really like the idea of having to wrap all database calls in a `Task` just to get access to the duration.

**Comment by vitaly-t** [comment]
* Event `receive` is called for all data reads, including the data coming from a stream, in which case there can be no `duration` applicable.
* Event `receive` is presently not called for queries that return no data, which makes it useless for logging any `duration`.

**Comment by kiejo** [comment]
Thanks for the detailed information. Changing the way `receive` works definitely sounds like a bad idea and I can see now why `receive` isn't a good solution for `duration` logging after all. Based on this information I think a new and separate event analogous to the `query` event would be a much nicer solution for my particular use case:
* While the `query` notification happens just before the query execution, this new event would be triggered right after the query execution
* The event would be triggered after a streaming query completes
* The event would be triggered for queries that return no data
* The event would make the `duration` available to the handler
* Based on the names of the other events it could for example be called `result` or `complete`

Of course I don't expect you to implement this just for me. I'm just looking to provide feedback based on my use case and hope that others might benefit from such a feature as well. I also don't know how much work this would be to implement as I haven't worked with the pg-promise source yet. Thanks for all the work you put into pg-promise and the great support you provide.

**Comment by vitaly-t** [comment]
I had similar requests before, but to change the `receive` event, and I'd rather be inclined to do just that, for version 8.x, as a breaking change.

**Comment by kiejo** [comment]
That would work for me too as "duration logging" is currently my only use case for the `receive` event!

**Comment by vitaly-t** [comment]
I have opened new issue for this - #461, and closing this one. If you have more comments, please add them in the new issue :wink:

**Comment by vitaly-t** [comment]
The feature is now available in [Version 8.0.0](https://github.com/vitaly-t/pg-promise/releases/tag/v.8.0.0).
