### ISSUE TITLE
The new locks feature introduces in 1.10.3 made unit test mocking/stubbing impossible

### ISSUE THREAD

**Issue by jniemin** [vitaly-t/pg-promise#46]
When the locks was introduced it also added side effect that mocking libraries like Sinon.js cannot create mocks from db object. Now mocking library throws error "TypeError: Cannot redefine property:" as locking also sets configurable property to false for functions. Here is the test case that worked with at least version 1.4.4 but now with latest 1.10.7 is broken with TypeError error

```javascript
var chai = require("chai");
var assert = chai.assert;
var sinon = require("sinon");
var pgpLib = require('pg-promise');

describe("Database query", function(){

  it("health check executed correct", function(){
    var pgp = pgpLib();
    var cn = {
      host: 'localhost', // server name or IP address;
      port: 5432,
      database: 'my_db_name',
      user: 'user_name',
      password: 'user_password'
    };
    var db = pgp(cn);
    var stub = sinon.stub(db, "one");
    var sqlString = "SELECT $1::int AS number";
    var params = ["1"];
    db.one("SELECT $1::int AS number", ["1"]);
    assert.isTrue(stub.calledWith(sqlString, params), "one should have been called");
    stub.restore();
  });
});
```

**Comment by jniemin** [comment]
Maybe could be something that would be on by default but could be turned off for testing purposes?

**Comment by vitaly-t** [comment]
The locks on the database level exist so that the protocol extension via event `extend` is consistent:

* Make sure you cannot extend the protocol outside of the `extend` event;
* Make sure you cannot override any existing method within the protocol while extending it.

So, as you can see, it is actually a very useful feature. Switching it off would make it more error-prone.

**Comment by jniemin** [comment]
I totally get it that having those Locks are important to not let people do mistakes by accident. 

I like the idea of using initialization option as then people don't have to play and set env variables while running tests but just initialize it with different options.

**Comment by vitaly-t** [comment]
Ok, I will add `unlocked` as a new option within Initialization Options. Will let you know when it is ready ;)

**Comment by vitaly-t** [comment]
@jniemin It is done in [Release 1.11.0](https://github.com/vitaly-t/pg-promise/releases/tag/v.1.11.0)

If it all works for you - just close the issue ;)

**Comment by jniemin** [comment]
Work nicely in 1.11.0, thanks. I'll close the case
