### ISSUE TITLE
Insert array of objects

### ISSUE THREAD

**Issue by gigiosilva** [vitaly-t/pg-promise#460]
How can I insert an array of objects at once?

`
let myArray = [
    {
        name: 'teste',
        age: 2
    },
    {
        name: 'teste1',
        age: 3
    }
]
`

**Comment by vitaly-t** [comment]
See [Multi-row insert with pg-promise](https://stackoverflow.com/questions/37300997/multi-row-insert-with-pg-promise).

**Comment by gigiosilva** [comment]
Thank you vitaly.

My solution below:

`
let myMultiInsert = (obj, callback) =>  {

      const cs = new pgp.helpers.ColumnSet(Object.keys(obj[0]), { table: 'table' });

      let query = pgp.helpers.insert(obj, cs);

      connection.none(query)
        .then(data => callback(data))
        .catch(err => {
          callback();
          console.log(err);
        });
 }
`

**Comment by vitaly-t** [comment]
You can replace `Object.keys(obj[0])` with just `obj[0]`, as that's the default.
