### ISSUE TITLE
Error while using LIKE in query

### ISSUE THREAD

**Issue by hillbrm** [vitaly-t/pg-promise#472]
Hi!
When i trying to use
`db4.any('SELECT table_name FROM information_schema.tables WHERE table_name LIKE $1', ['string%'])` it perfectly works.
But when i trying `db4.any('SELECT table_name FROM information_schema.tables WHERE table_name LIKE $1', ['%string'])` it doesn't work at all.
I get:
`{"success":false,"data":{"name":"error","length":86,"severity":"ERROR","code":"42601","position":"57641","file":"scan.l","line":"1082","routine":"scanner_yyerror"}}`
If i trying this query in phppgadmin console it works.
Thanx!

**Comment by vitaly-t** [comment]
I have done the same test, and cannot reproduce it, the code always works no matter where you place `%`, in front or in the end.

Plus, the error that you see comes from the PostgreSQL server, and not this library.

I would suggest taking the generated SQL and executing it directly against pgAdmin, then you should be able to see the problem.

```js
const sql = pgp.as.format('SELECT table_name FROM information_schema.tables WHERE table_name LIKE $1', ['%string']);
console.log('SQL:', sql);
```

**Comment by hillbrm** [comment]
> const sql = pgp.as.format('SELECT table_name FROM information_schema.tables WHERE table_name LIKE $1', ['%string']);
> console.log('SQL:', sql);
i used resulting query in pgadmin and it works.

**Comment by vitaly-t** [comment]
Then it should work through pg-promise also.

**Comment by vitaly-t** [comment]
Since no other details are provided, I cannot help you. And besides, as I wrote earlier, your query error comes from the server, which is a bit outside of this library.
