### ISSUE TITLE
Wrong comment "leading `+` is short for `parseInt()`" 

### ISSUE THREAD

**Issue by nidin** [vitaly-t/pg-promise#475]
https://github.com/vitaly-t/pg-promise/blob/d261e894e76744e522266ae01ab2f1c1785a260d/lib/database.js#L1152

### Wrong comment found in documentation.
**Wrong ->** leading `+` is short for `parseInt()`
**Correct ->** leading `+` is short for `parseFloat()`

Correct short hand for parseInt() is trailing `|0` 
To see this working, try `console.log(+"1.6")` and `console.log("1.6"|0)` in Console

**Comment by vitaly-t** [comment]
I think it was copied from another context where `+` was used for converting a string that always contains an integer into type `number`. In that context `+` was indeed just a shorter version of `parseInt`. But in general, you are correct.
