### ISSUE TITLE
Connection pool limit

### ISSUE THREAD

**Issue by karsep5** [vitaly-t/pg-promise#478]
We are currently using pg-promise in our micro service architecture. The default poolsize is currently set to 10. We have multiple instances of the node application accessing a single postgres server. Due to the multiple instances, the total pool size exceeds the postgres max connection limit. To handle this, we are looking at using pgpool or pgbouncer to start accessing slave postgres nodes to increase the number of connections which can be made to postgres. Can this be done seamlessly through pg-promise?

**Comment by vitaly-t** [comment]
pg-promise doesn't control the number of connections, the underlying driver `node-postgres` does via its connection parameters, which you simply pass through with pg-promise.

Neither can control he number of connections outside the process.

**Comment by vitaly-t** [comment]
See related issue: #406

**Comment by vitaly-t** [comment]
I take it the question has been answered? :wink:
