### ISSUE TITLE
WHERE col IN (values)

### ISSUE THREAD

**Issue by RyanMcDonald** [vitaly-t/pg-promise#48]
This is the example given in the docs:
```
var data = [1, 2, 3, 4];
db.query("SELECT * FROM table WHERE id IN ($1^)", pgp.as.csv(data))
    .then(function (data) {
        console.log(data); // print data;
    }, function (reason) {
        console.log(reason); // print error;
    });
```
Is there a way to apply this to arrays of string values? If done like above, the strings end up not being surrounded in quotes.

Thanks!

**Comment by vitaly-t** [comment]
The strings inside the array would be surrounded in quotes. Would you like to give an example of the code your are using?

**Comment by vitaly-t** [comment]
@RyanMcDonald Please follow up on your question, or close if it has been resolved.

**Comment by RyanMcDonald** [comment]
Thanks for the quick responses @vitaly-t! It's working for me now; it was a different issue that was causing my strings not to be surrounded in quotes.
