### ISSUE TITLE
CSV Filter returning Syntax Error

### ISSUE THREAD

**Issue by Johnb21** [vitaly-t/pg-promise#482]
I am trying to use a csv filter as part of an IN statement and it throws a syntax error `syntax error at or near ":"`

Here is the code (with sensitive data removed)

```
getActive(ids, fromDate, toDate){
      let query = `
      SELECT count(mid) AS active
      FROM srm
      INNER JOIN mbl
        ON srm.mid = mbl.mid
      WHERE srm.sid IN ($(ids):csv)
      AND mbl.date >= $(fromDate)
      AND mbl.date <= $(toDate)
`
      

      return this.connection.tConnection.one(query, {
          ids: ids,
          fromDate: fromDate,
          toDate: toDate
      })
  }
```

Any ideas as to why this throws an error instead of converting the ids array from [1,2,3,4] into `IN(1,2,3,4)`?

**Comment by vitaly-t** [comment]
The syntax is ` IN ($(ids:csv))`, not ` IN ($(ids):csv)`. See [the documentation](https://github.com/vitaly-t/pg-promise#formatting-filters):

> Filters use the same syntax for `Index Variables` and `Named Parameters`, following immediately the variable name
