### ISSUE TITLE
how to auto increase a value using update helper?

### ISSUE THREAD

**Issue by DanielLausch** [vitaly-t/pg-promise#487]
hello,

i want to use helpers agains normal queries to do not loose performance. but im unable to increase an integer value in one of my rows in this way. so how it can be done?

at the moment i update my table like this:

```
const cs = new pgp.helpers.ColumnSet(['user', 'group', 'points'], {
  table: 'users'
});

const values = [{
  user: "testuser",
  group: "testgroup",
  points: 10 //this should be actual points + 10
}];

const query = pgp.helpers.update(values, cs);

db.none(query)
  .then(data => {

  })
  .catch(error => {
    say("error", 'Error while performing Query! Error: ' + error);

  });
```

so what i want to do is adding points to the actual value

like "points = points + 10"

is there any way to do it?

best wishes

Daniel

**Comment by vitaly-t** [comment]
Define your `ColumnSet` like this:

```js
const cs = new pgp.helpers.ColumnSet([
    'user',
    'group',
    {name: 'points', init: c => c.value + 10;}
], {
  table: 'users'
});
```

See flexible type [Column] :wink:

[Column]:http://vitaly-t.github.io/pg-promise/helpers.Column.html

**Comment by DanielLausch** [comment]
thats amazing!
was so "easy" in the end.

thank your so much for your help!

and thanks for the reference.

best wishes

Daniel
