### ISSUE TITLE
Since version 8 on install (MacOs) :  pg_config: command not found

### ISSUE THREAD

**Issue by minotogna** [vitaly-t/pg-promise#489]
Hi,
I'm trying to use pg-promise, however if I use the version >= 8.0.0 ("pg-promise": "^8.0.0") I get the following error during yarn install.
/bin/sh: pg_config: command not found
gyp: Call to 'pg_config --libdir' returned exit status 127 while in binding.gyp. while trying to load binding.gyp

If I use the version 7.5.4 it works.

Did the library become pg native dependent ?

Thank you,
Mino

**Comment by vitaly-t** [comment]
This is all because of the stupid #488

**Comment by minotogna** [comment]
thank you!
