### ISSUE TITLE
Problems reading stream data

### ISSUE THREAD

**Issue by chitombo** [vitaly-t/pg-promise#493]
Hi there, 
I have been trying to follow the streaming examples in Learn by Example, 
but I can't seem to get the following code to log to the console.
```js
const QueryStream = require('pg-query-stream');
const streamRead = pgp.spex.stream.read;
const qs = new QueryStream('SELECT * FROM users');

function receiver(_, data) {
    console.log('USER:', data[0]);
}

db.stream(qs, s => {
        return streamRead(s, receiver);
    })
    .then(data => {
        // success;
    })
    .catch(function (error) {
        // error;
    });
```

### Expected behavior
I was expecting it to list out my users basically one row at a time.
I managed to get the From Database streaming using
```js s.pipe(JSONStream.stringify()).pipe(process.stdout);```
to work fine, but was trying to process my table one row at a time.

### Actual behavior
When I run the function, my console remains blank during the streaming. Only giving me the done console.log
```js
console.log('Total rows processed:', data.processed,
            'Duration in milliseconds:', data.duration);
```

### Environment

* Version of pg-promise: 8.2.2
* OS type Linux/Windows/Mac: Mac
* Version of Node.js: v9.5.0

**Comment by vitaly-t** [comment]
`db.stream` provides a callback function in which you are expected to initiate streaming.

Method `read` within spex is to read data from a stream. Why you passed `read` into `db.stream` and expect it to work - I don't know :smile: Those are two totally separate things.

**Comment by chitombo** [comment]
😅 Ahhhh that makes sense now, I was just following the examples you put in the **Learn by Example**, and copied the **Mixing Up** code but couldn't get it to work. 

Thank you for your fast response. 👍
