### ISSUE TITLE
TypeError: Invalid column syntax: "source-layer".

### ISSUE THREAD

**Issue by stepankuzmin** [vitaly-t/pg-promise#494]
It seems that `pg-promise` doesn't support column names with `-` sign.

### Expected behavior

```js
ColumnSet {
    columns: [
        Column {
            name: "source-layer"
        }
    ]
}
```

### Actual behavior

```
TypeError: Invalid column syntax: "source-layer".
    at parseColumn (/Users/stepan/projects/protoproto/node_modules/pg-promise/lib/helpers/column.js:279:11)
    at new Column (/Users/stepan/projects/protoproto/node_modules/pg-promise/lib/helpers/column.js:136:22)
    at ColumnSet.columns.columns.map.c (/Users/stepan/projects/protoproto/node_modules/pg-promise/lib/helpers/columnSet.js:213:57)
    at Array.map (<anonymous>)
    at new ColumnSet (/Users/stepan/projects/protoproto/node_modules/pg-promise/lib/helpers/columnSet.js:212:32)
```

### Steps to reproduce

```js
const pgp = require('pg-promise')();
new pgp.helpers.ColumnSet(['source-layer']);
```

### Environment

* Version of pg-promise: 8.2.2
* Version of Node.js: 9.7.1

**P.S.** I've tried different modifiers with

```js
new pgp.helpers.Column({ name: '"source-layer"', mod: ':raw' })
```

but it didn't succeeded.

**Comment by vitaly-t** [comment]
This is by design, see the API: http://vitaly-t.github.io/pg-promise/helpers.Column.html

> Destination column name + source property name (if prop is skipped). The name must adhere to JavaScript syntax for variables, unless prop is specified, in which case name represents only the column name, and therefore can be any string.

**Comment by stepankuzmin** [comment]
So there is no way to use helpers with this kind of columns then?

**Comment by vitaly-t** [comment]
Are you using string presentation for your source property names? If not, then what is your source property name?

**Comment by stepankuzmin** [comment]
I've `"source-layer" text` in my `create table`. And trying to use `insert` and `update` helpers on this table.

**Comment by vitaly-t** [comment]
I understand that, I asked about the name of the property in the source object that contains the value.

**Comment by stepankuzmin** [comment]
What do you mean by source object? Query result object? If yes, then it is `source-layer` too.

**Comment by vitaly-t** [comment]
> I'm using string presentation for property names.

If property names in your source object do not satisfy the open-variable syntax for JavaScript, then type [Column] cannot directly map to such properties.

This is because the whole idea of the `helpers` namespace is around preparing high-performance formatting templates that use [Named Parameters], which in turn can only use open-variable syntax for properties.

What you are doing is very unusual, and can only happen when trying to work-around some legacy bad written database. New databases should never use names like `column-bla-name`, that's a horrible idea. The standard is `column_bla_name`, which then can even be auto-camelized with pg-promise.

If you still have such awkward columns to deal with, you would have to provide a value override, i.e. your column would be:

```js
{name: 'column-layer', prop: 'unused', init: c => c.source['column-layer']}
``

[Named Parameters]:https://github.com/vitaly-t/pg-promise#named-parameters
[Column]:http://vitaly-t.github.io/pg-promise/helpers.Column.html

**Comment by stepankuzmin** [comment]
Thanks for the reply! That makes things clear.

**Comment by kduraiswami** [comment]
Hey, I am dealing with something similar here I can't seem to figure out. The column name is "Account Number" provided in an array such as let columns = ["Status", "Account Number", "Account Name" ... ]. I have tried this but it still doesn't like the space: 

```
let insertColumnSet = new pgp.helpers.ColumnSet(
                tableConfig.columns.map(column => {
                    return {
                        name: column, 
                        mod: ":raw", 
                        init: c => c[column]
                    }
                }),
                {table: tableConfig.tableName}                
            );
```

Error
```
/Users/Workspace/pg-promise/lib/helpers/column.js:151
                    throw new TypeError(`Invalid 'name' syntax: ${npm.utils.toJson(col.name)}.`);
                          ^

TypeError: Invalid 'name' syntax: "Account Number".
    at new Column (/Users/Workspace/pg-promise/lib/helpers/column.js:151:27)
    at /Users/Workspace/pg-promise/lib/helpers/column-set.js:204:57
    at Array.map (<anonymous>)
    at new ColumnSet (/Users/Workspace/pg-promise/lib/helpers/column-set.js:203:36)
```
