### ISSUE TITLE
Improve stack tracing

### ISSUE THREAD

**Issue by ericandrewlewis** [vitaly-t/pg-promise#496]
Thanks for pg-promise, it's a great library ❤️ 

pg-promise can output confusing error messages. I think it is related to the fact that the callstack output with error messages is separate from the callstack context where the bug exists.

For example, considering the code in `index.js`

```js
const pgp = require("pg-promise")({});
const connectionURL = "postgres://localhost:5432/some-nonexistent-database";
const db = pgp(connectionURL);

db.one("SELECT * FROM table").then(data => {
  console.log(data);
});
```

When I run this script, I get the error:

```
20:40 $ node index.js 
(node:79335) UnhandledPromiseRejectionWarning: error: database "some-nonexistent-database" does not exist
    at Connection.parseE (/Users/ericlewis/Desktop/r/node_modules/pg/lib/connection.js:545:11)
    at Connection.parseMessage (/Users/ericlewis/Desktop/r/node_modules/pg/lib/connection.js:370:19)
    at Socket.<anonymous> (/Users/ericlewis/Desktop/r/node_modules/pg/lib/connection.js:113:22)
    at Socket.emit (events.js:160:13)
    at addChunk (_stream_readable.js:269:12)
    at readableAddChunk (_stream_readable.js:256:11)
    at Socket.Readable.push (_stream_readable.js:213:10)
    at TCP.onread (net.js:602:20)
(node:79335) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:79335) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

The error message is relevant, `database "some-nonexistent-database" does not exist`, but if this error was in the middle of a large application, I wouldn't know where to start looking. Perhaps I could search for the `some-nonexistent-database` string...but I wonder if we could offer users some better error message here to let them know where they should start debugging.

I know some of these errors are surfaced through the `pg` package's interface...so I'm sorry if this report is mis-attributed. pg-promise is the package I've seen this through so I thought i'd present it here first 😄

**Comment by vitaly-t** [comment]
So use Bluebird with long stack traces then...

```js
const promise = require('bluebird');
promise.config({
    longStackTraces: true
});

const initOptions = {
    promiseLib: promise
};

const pgp = require('pg-promise')(initOptions);
```

**Comment by vitaly-t** [comment]
@ericandrewlewis It's been 3 days, and no response, so I'm closing it.
