### ISSUE TITLE
Enable connection pooling

### ISSUE THREAD

**Issue by ZachMilne** [vitaly-t/pg-promise#499]
I threw some event handlers on 'connect' and 'error' and discovered they were firing only when a query was being executed. I assumed a connection pool would be established and queries would utilize a connection from the pool before returning it. Is this not the behavior? If there is a pool created, how then do I verify that the pool successfully connected to the db? if I supply the wrong db credentials no error is currently thrown at app startup.

Thanks

**Comment by vitaly-t** [comment]
See [Verify database connection with pg-promise when starting an app](https://stackoverflow.com/questions/36120435/verify-database-connection-with-pg-promise-when-starting-an-app).
