### ISSUE TITLE
INSERT batch w/no transaction

### ISSUE THREAD

**Issue by paulxtiseo** [vitaly-t/pg-promise#50]
I have a function that processes large CSV data files (>1GB). The code below errors out due to memory exhaustion. Basically, I'm creating a promise (db.none) asynchronously for each CSV record which is not good. Any recommendations? In my case, I don't need transaction support, although I do want to report on failed rows. 

```javascript
return promise.map(this.mappedFiles, function(file) {
  var stream = fs.createReadStream(file.file_name);
  return api.parsers.processCsvStream(stream, function(data) {
    return db.none('INSERT ...', data).then(function(result) { return result; });
  })
}
```

```javascript
api.parsers.processCsvStream = function(passedStream, processor) {
  if(!(passedStream instanceof stream.Stream)) {
    return promise.reject('No passedStream received.');
  }

  if(!_.isFunction(processor)) {
    return promise.reject('No processor received.');
  }

  var parser = csv.parse(passedStream, {trim: true});

  parser.on('readable', function() {
    var data;
    while(data = parser.read()) {
      processor(data);
    }
  })

  passedStream.pipe(parser);

  return new Promise(function(resolve, reject) {
    parser.on('end', resolve);
    parser.on('error', reject);
  });
}
```

**Comment by vitaly-t** [comment]
You definitely need to use method [sequence](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#massive) for that, either as part of a transaction or as a task.

**Comment by paulxtiseo** [comment]
I did look at using task() (don't need a transaction) and sequence(), but unless I am mistaken, that simply helps me run the promises sequentially inside a shared connection. How do I control the amount of promises being created, or does sequence() ensure that I create-destroy one promise before moving on to the next one?

I also am not sure how to use sequence() in conjunction with a stream. (You seem to allude to a  [benchmark](https://github.com/vitaly-t/pg-promise#sequence-benchmark) that would maybe shed some light on it, but not sure where it is.)

PS: I guess at this point, seems  I should have gone to StackOverflow... I apologize.

**Comment by vitaly-t** [comment]
>does sequence() ensure that I create-destroy one promise before moving on to the next one?

Exactly!

>I also am not sure how to use sequence() in conjunction with a stream

It has a very simple interface, expecting requests one by one. Any API can be channelled into such logic easily ;)

>I guess at this point, seems I should have gone to StackOverflow... I apologize.

And then it will be myself again answering all the questions on StackOverflow again :)

**Comment by vitaly-t** [comment]
@paulxtiseo Have you been able to sort out this issue?

**Comment by paulxtiseo** [comment]
Not quite.

From my original code, I have an array (`mappedFiles`) that has multiple large files (paths, really). I `bluebird.map()` the array to a function that creates a stream and processes it. The data being read must be stored to a DB. The function doing this is the `none()` function from your library that returns a promise. So, at my first pass above, I keep generating a ton of pending DB operations that eventually would resolve, but also cause tremendous memory pressure, oftentimes causing an abort by Node.

I can see that the burden of throttling resides entirely in processCsvStream(). I was about to bring in `async` and use `queue` to do this. Thanks for the ref to `spex`. I am looking at `page()` (instead of `sequence()`) as a way to batch the data into the DB. Haven't done it just yet due to a support issue in my work day and having a hard time wrapping my head around streams-mixed-with-promises. :)

**Comment by vitaly-t** [comment]
You have all the right tools to implement proper throttling, methods [sequence](https://github.com/vitaly-t/spex/blob/master/docs/code/sequence.md) and [page](https://github.com/vitaly-t/spex/blob/master/docs/code/page.md) provided by the [spex](https://github.com/vitaly-t/spex).

I can't point you more precisely, because you are just describing the problem in general. But using those methods you shouldn't have a problem to solve the problem.

If you use method [sequence], then your code would be something like this:

```javascript
var promise = require('bluebird');
var spex = require('spex')(Promise);

// returns a promise with the next data read;
function readNextDataFromStream(index, data, delay) {

    // 1. Read next 1-row data from stream;
    // 2. Once read is finished, resolve with that row-data;

    // If failed to read, reject;
    // If no more data left, either return `undefined` or reject with undefined;

}

function dest(index, data, delay) {

}

spex.sequence(readNextDataFromStream, dest)
    .then(function (data) {
        console.log("Read total:", data.total);
        console.log("Duration:", data.duration);
    }, function (reason) {
        console.log("FAILED:", reason);
    });
```
And if you use method [page], then your code would barely change:
```javascript
// returns a promise with the next page of data read;
function readNextDataPageFromStream(index, data, delay) {

    // 1. Read the next page of data from stream;
    // 2. Once read is finished, resolve with that data;

    // If failed to read, reject;
    // If no more data left, either return `undefined` or reject with undefined;

}

function dest(index, data, delay) {
    // process the next page of data;
}

spex.page(readNextDataFromStream, dest)
    .then(function (data) {
        console.log("Pages:", data.pages);
        console.log("Total:", data.total);
        console.log("Duration:", data.duration);
    }, function (reason) {
        console.log("FAILED:", reason);
    });
```

**Comment by vitaly-t** [comment]
Your task has just become even easier, because I released version [2.0.11](https://github.com/vitaly-t/pg-promise/releases/tag/v.2.0.11) that adds support for `spex.page` natively.

At this point I suggest that you try and come up with a solution based on the methods available to you, which is more than enough. And if you are stuck along the way with something more specific, you can open an issue accordingly, and I will try to help you.

In the meantime, this issue here is too broad to make any progress, so I'm closing it.

**Comment by paulxtiseo** [comment]
One last question, do you have or know of any real, working example that processes a stream using these methods()?

**Comment by vitaly-t** [comment]
@paulxtiseo If I did I would point you at it as the first thing instead of writing you a generic example of how to approach it. Sometimes we need to write things ourselves. Don't let the initial misunderstanding get in the way ;)

**Comment by vitaly-t** [comment]
@paulxtiseo quite expectedly, I was the one to answer your question on StackOverlfow in the end :)

**Comment by vitaly-t** [comment]
@paulxtiseo have you finished this research or are you still experimenting?

I've been playing around with the idea of joining a readable stream with promises, and made some good progress there. Let me know if you are still interested.
