### ISSUE TITLE
Question: Async/Await Transactions

### ISSUE THREAD

**Issue by jdalrymple** [vitaly-t/pg-promise#500]
Is there a way to run transactions in this fashion:

```
const t = db.tx('my transaction');

try {
    const value1 = t.one('my query)

    await t.commit()
} catch(e) {
    await t.rollback()
}
```

Similar to : https://node-postgres.com/features/transactions

Thank you !

**Comment by vitaly-t** [comment]
Transactions in this library are automatic, one never needs to do `COMMIT` or `ROLLBACK` manually.

**Comment by jdalrymple** [comment]
I understand! I want to be able to access a transaction from outside of the callback for a specific implementation, but I can't do that currently. That's why I I'm asking if the implementation shown in node-postgres is possible with pg promise :)

**Comment by vitaly-t** [comment]
> access a transaction from outside of the callback for a specific implementation

Such ideas typically pointing at misunderstanding how automatic transactions work. If you can provide an explanation of your specific case, then I should be able to point you at how to approach it within the existing protocol.

**Comment by jdalrymple** [comment]
Perhaps my solution isn't an automatic solutions I guess.

I'm trying to begin a transaction and maintain a id to that transaction

Perform some queries in that transaction
And then separately commit/rollback that transaction. 

Practically exactly like my example code above. 

I would like to execute it this way because at the time of beginning the transaction all the qeuries that I would like to run within that transaction are not know yet. That's why i can't use the implementation in the docs ( where the execution happens within the callback)

**Comment by vitaly-t** [comment]
> I would like to execute it this way because at the time of the beginning the transaction all the queries that I would like to run within that transaction are not known yet.

So here's the misunderstanding: The callback returns a promise, so you can chain any dynamic context into it.

**Comment by jdalrymple** [comment]
Ah, Hmm, so how would I execute that? Could you provide an example? Thank you!

**Comment by vitaly-t** [comment]
Are you asking to how to chain promises? That's all it takes, but it is not a question to be asking here.

If you are not familiar with promises, you should read about those.

**Comment by jdalrymple** [comment]
😂 No i meant with reference to the db.tx. 

Do you mean like this:

```
db.tx('my transaction', t => {
    // creating a sequence of transaction queries:
    const q1 = t.none('UPDATE users SET active = $1 WHERE id = $2', [true, 123]);
})
.then(t => {
    const q2= t.none('UPDATE users SET active = $1 WHERE id = $2', [true, 123]);
})
```

Does that mean it could also then be executed like:

```
await db.tx('my transaction', t => {
    // creating a sequence of transaction queries:
    const q1 = t.none('UPDATE users SET active = $1 WHERE id = $2', [true, 123]);
})

await db.tx('my transaction', t => {
    const q2= t.none('UPDATE users SET active = $1 WHERE id = $2', [true, 123]);
})
```

Where the second query (q2) is part of the same transaction?

**Comment by vitaly-t** [comment]
No, both examples you provided are wrong...

Depending on asynchronous pattern required, you change the implementation, but always inside the callback function:

```js
db.tx(t => {
    /*
      either chain you queries one by one, or via batch, or via ES6 generator
   */
})
.then(data => {
    // data = what transaction returned
})
.catch(error => {
    // error
});
```

**Comment by jdalrymple** [comment]
So clarifying, transaction queries must happen within the same transaction callback. Thanks
