### ISSUE TITLE
ETIMEDOUT Error 

### ISSUE THREAD

**Issue by ubreddy** [vitaly-t/pg-promise#509]
### Expected behavior
Connection should be obtained from the pool. or, if number of connections requested exceed the size it should say Connection limit reached error.

### Actual behavior
connect ETIMEDOUT host:5432
Once I restart the server, the connections are working fine again. But this mandates a restart every few hours, which is bad.

### Steps to reproduce
After a few hours of the server running, this problem is occuring. Say after 10 hours or so. 
Tried with keepAlive : true option too 
I am using max : 100 

### Environment

* Version of pg-promise: "^7.3.3",
* OS type Linux/Windows/Mac: linux
* Version of Node.js: boron 6.14.2

**Comment by vitaly-t** [comment]
You should upgrade to the latest version of the library, and then research it against the [driver](https://github.com/brianc/node-postgres). Here's a [related issue](https://github.com/brianc/node-postgres/issues/1555).

Maybe adding `?ssl=1` to the connection string, or switching ver to the object will help, as explained there. But either way, if there is an issue, it is the driver's issue, and not in this library.
