### ISSUE TITLE
pg-promise hangs

### ISSUE THREAD

**Issue by HueyNemud** [vitaly-t/pg-promise#510]
Hi,

When trying to acces a database and execute a query, the promise is never resolved. After a few investigations, it seems that `connect()` hangs indefinitely.
When I try to manually execute the same query with `psql` and the same connection string, everything goes fine.

What could cause pg-promise and the postgres client to act differently?

## Expected behavior
```
const config = {
    host: my_host,
    port: 5433,
    database: 'db',
    user: my_user,
    password: my_password
};
const pgp = require('pg-promise')( { promiseLib: promise } );
const db = pgp(config);
db.connect()
    .then(function (obj) {
        console.log('SUCCESS');
        obj.done();
    })
    .catch(function (error) {
        console.log("ERROR:", error.message);
    });
```
`> SUCCESS`
### Actual behavior

Nothing happens.

### Environment
* pg-promise 8.2.2
* Ubuntu 16.04
* nodejs v10.1.0

**Comment by vitaly-t** [comment]
I would say that 99% chance it is an issue with your PostgreSQL configuration. The thing is, can access the server in its own way. You need to sort out the connection configuration, to make sure the server is accessible from an app :wink:

**Comment by jmtorresg** [comment]
For anyone who also encounters this issue, I was experiencing it on one of my machines in particular but none of the others. What did the trick for me was updating `pg-promise` from version 10.5.0 to version 10.5.6 (via `npm update pg-promise`).

**Comment by ParasDoshi** [comment]
> For anyone who also encounters this issue, I was experiencing it on one of my machines in particular but none of the others. What did the trick for me was updating `pg-promise` from version 10.5.0 to version 10.5.6 (via `npm update pg-promise`).

had the same issue updating to 10.5.6 works for me

**Comment by christiaanwesterbeek** [comment]
Today in 2 projects without any changes, pg-promise could not make a connection to the database anymore. One project was on 8.4.6 for a long time, the other on 9.1.4 for also pretty long. Both were not able to connect anymore.

I didn't change the code. I also was able to connect to those databases using Postico on the same computer. Maybe it is something network related that has changed to my Mac recently. No idea. After upgrading them both to the latest pg-promise (10.6.2), it was fixed.

_Insering the next line for google indexing:_
Without any code changes suddenly pg-promise doesn't connect to the database anymore

**Comment by vitaly-t** [comment]
@christiaanwesterbeek SOmething did change, obviously. Mayme NodeJS version, which would make sense. Or could be a network issue.

**Comment by christiaanwesterbeek** [comment]
You're right, I upgraded NodeJS version yesterday! That must have been it. Thanks

**Comment by VivekBari92** [comment]
> For anyone who also encounters this issue, I was experiencing it on one of my machines in particular but none of the others. What did the trick for me was updating `pg-promise` from version 10.5.0 to version 10.5.6 (via `npm update pg-promise`).

Thanks a lot for this valuable information , I have been struggling for hours on this.

**Comment by kumar-ujjwal** [comment]
> 
> 
> Today in 2 projects without any changes, pg-promise could not make a connection to the database anymore. One project was on 8.4.6 for a long time, the other on 9.1.4 for also pretty long. Both were not able to connect anymore.
> 
> I didn't change the code. I also was able to connect to those databases using Postico on the same computer. Maybe it is something network related that has changed to my Mac recently. No idea. After upgrading them both to the latest pg-promise (10.6.2), it was fixed.
> 
> _Insering the next line for google indexing:_
> Without any code changes suddenly pg-promise doesn't connect to the database anymore

Thank you so much, you are a life saver!

**Comment by vitaly-t** [comment]
Many things can change without you notice.... NodeJS version, OS-wide SSL configuration, those would impact secure connectivity of many modules.
