### ISSUE TITLE
Named parameters default example uses ES6 template string syntax

### ISSUE THREAD

**Issue by ericandrewlewis** [vitaly-t/pg-promise#511]
Named parameters are cool. The example in the [Learn By Example: Named Parameters section](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#named-parameters) uses the `${}` format, while also suggesting `$()`, `$<>`, `$[]`, and `$//` as options.

Since ES6 template syntax conflicts with `${}`, I would suggest the default example use one of these alternate syntaxes. Perhaps `$<>` since it is different enough for identification from template string syntax?

**Comment by vitaly-t** [comment]
The default examples remain using `${prop}` syntax because this is the syntax you'd want when building a proper database layer, one where all your SQL is in external SQL files.

See [Lisk database layer](https://github.com/LiskHQ/lisk/tree/development/db) as an example.

**Comment by ericandrewlewis** [comment]
> The default examples remain using ${prop} syntax because this is the syntax you'd want when building a proper database layer, one where all your SQL is in external SQL files.

I understand separating SQL into external files, but why is `${prop}` preferred syntax in external SQL files over something like `$<prop>`?

**Comment by vitaly-t** [comment]
Thank you for the suggestion, but I won't be making the change, as it is too much to change and for little-to-none benefit.
