### ISSUE TITLE
This is more of a question about your library than an issue

### ISSUE THREAD

**Issue by myDeveloperJourney** [vitaly-t/pg-promise#512]
First of all, I love this library, it's made using PostgreSQL extremely easy with my express backend. I do have a question as far as the proper way to INSERT a row into a table.

I was thinking about using ES6 destructuring to extract the properties from the request body and then use them inside of my route handler/create method like this:

```js
UsersRouter.post('/', (req, res) => {
  const {user_name, email, password} = req.body;
  return db.one(`INSERT INTO users(user_name, email, password)
  VALUES('${user_name}', '${email}', '${password}') RETURNING *`)
  .then((user) => {
    res.json(user);
  }).catch((error) => {
    console.log('Error: ', error);
    res.status(500).json({message: '500 Internal Server Error'});
  });
});
```
I was just curious if the query formatting you designed would accept something like this and be okay.

Thank you so much and again, I really appreciate your work.

**Comment by vitaly-t** [comment]
It will work, if you use query formatting correctly, i.e. you cannot use ES6 templates that way, only strings:

```js
return db.one('INSERT INTO users(user_name, email, password)
  VALUES('${user_name}', '${email}', '${password}') RETURNING *')
```

For ES6 templates you'd need a different format.

**Comment by vitaly-t** [comment]
P.S. Please post future questions on StackOverflow.

**Comment by myDeveloperJourney** [comment]
Thank you so much sir, 🙏 I really appreciate your taking the time to answer this. I will use the proper protocol for asking questions next time. 😅
