### ISSUE TITLE
Questionmark in password breaks connection via connection string

### ISSUE THREAD

**Issue by Nop0x** [vitaly-t/pg-promise#513]
### Expected behavior
Normal connection via string.

### Actual behavior
Breaks and tries to use the username as host.

### Steps to reproduce
Use a "?" symbol in the password portion of a connection string.

### Environment

* Version of pg-promise: 8.4.4
* OS type (Linux/Windows/Mac): Windows / Linux
* Version of Node.js: 8.11.1

**Comment by vitaly-t** [comment]
Note that after some testing, I found an issue in that module, which I'm going to fix soon: https://github.com/vitaly-t/connection-string/issues/2

**Comment by vitaly-t** [comment]
That issue with connection string module has been fixed.

And closing this one, due to non-response.
