### ISSUE TITLE
helpers.update not casting objects to JSONB

### ISSUE THREAD

**Issue by benhjames** [vitaly-t/pg-promise#514]
### Expected behavior

Let's say I have a table (`mySchema.myTable`) with a column of JSONB type (`myColumn`).

I'm expecting the following multi-update to work:

```js
const keys = ['id', 'myColumn:json'];
const columnSet = new helpers.ColumnSet(keys, {
  table: { schema: 'mySchema', table: 'myTable' },
});

await db.query(`
  ${helpers.update([
    { id: 1, myColumn: {} },
    { id: 2, myColumn: {} },
  ], columnSet)} where v.id = t.id
`);
```

### Actual behavior

It currently throws an error:

`error: column "myColumn" is of type jsonb but expression is of type text`

The query that is produced by `helpers.update` (formatted) is:

```sql
update "mySchema"."myTable" as t
set "id"=v."id", "myColumn"=v."myColumn" from
(values(1,'{}'),(2,'{}')) as v("id","myColumn")
where v.id = t.id
```

If I change `"myColumn"=v."myColumn"` to `"myColumn"=to_jsonb(v."myColumn")` and run it in `psql`, it would then succeed.

Would it be possible to automatically cast `'{}'` into `to_jsonb` here? Hopefully I'm missing a trick! Thanks! 🙂

**Comment by benhjames** [comment]
This is additionally the case for `json` and custom `enum` fields, for example:

`error: column "myField" is of type "mySchema"."myEnum" but expression is of type text`

**Comment by benhjames** [comment]
Never mind - I just read the https://github.com/vitaly-t/pg-promise#custom-type-formatting docs! I'll give this a go.

**Comment by benhjames** [comment]
Turns out I just needed to do:

```js
const keys = ['id', new helpers.Column({ name: 'myField', cast: 'jsonb' })];
```

where `cast` is whatever the field type is!

**Comment by vitaly-t** [comment]
I've just noticed this post, since you closed it quick :smile:

So basically yes, use of `cast` within the column definition is all you needed in your case.

As for [Custom Type Formatting], you can do anything with it, but in your specific case it would be an overkill :wink:

[Custom Type Formatting]:https://github.com/vitaly-t/pg-promise#custom-type-formatting

**Comment by vitaly-t** [comment]
@benhjames  b.t.w., you do not need to use type `Column` explicitly, it is used implicitly always:

```js
const keys = ['id', { name: 'myField', cast: 'jsonb' }];
```
