### ISSUE TITLE
SSL issue with pg-promise@8.2.2

### ISSUE THREAD

**Issue by cd10anil** [vitaly-t/pg-promise#517]
### Expected behavior
The pg-promise@8.2.2 should support and connect SSL when using bluebird in AWS. 

### Actual behavior
The pg-promise@8.2.2 failed to use SSL and throws error on using ?ssl=true
"name":"error","length":89,"severity":"FATAL","code":"3D000","file":"postinit.c","line":"876","routine":"InitPostgres"}

### Steps to reproduce
Use the below nodejs snippet 
```
var promise = require('bluebird');  // call bluebird
var options = {    // Initialization Options
    promiseLib: promise
};
var Pgp = require('pg-promise')(options);
if( Pgp == null) {
     console.log('Failed to load PostgreSQL.');   return;
 }
console.log('PostgreSQL GET Function loaded successfully.');
this._username = "usernamehere";
this._password = "passwordhere";
var mID = "123";
 
var conn = 'postgres://' + this._username+':'+this._password+'@mytestencryptiondbinstance.rds.amazonaws.com?ssl=true';//?sslmode=verify-full';//&sslrootcert=/root/.postgresql/rds-combined-ca-bundle1.pem';
var db = Pgp(conn);
if( db == null) {
    console.log('Failed to connect AWS PostgreSQL DB.'); return;
} else 

 // allows for using callbacks as finish/error-handlers
console.log('Fetching data from AWS PostgreSQL DB.');
await db.one('select * from products where my_code = $1', mID.toString()) 
  .then(function (data) {
    console.log('Row Details:', JSON.stringify(data));
	   })
  .catch(function (err) {
      console.log("In ERROR BLOCK..."+JSON.stringify(err));
      return JSON.stringify(err);
  });
  
```
  The error is thrown if usign ?ssl=true, after enable ssl and reboot instance in postgresql group in db instance.
  
  2018-05-28T09:05:13.502Z	395c4d86-xxxx-xxxx-xxxx-65288d7b464d	
  In ERROR BLOCK...{"name":"error","length":89,"severity":"FATAL","code":"3D000","file":"postinit.c","line":"876","routine":"InitPostgres"}

### Environment
AWS lambda function. 
pg-promise@8.2.2
"bluebird@3.5.1"

* Version of pg-promise:8.2.2
* OS type (Linux/Windows/Mac):aws lambda
* Version of Node.js:8.10
Aurora PostgreSQL 9.6.6

**Comment by vitaly-t** [comment]
This must be something to do with the specifics of using SSL under AWS, and not with this library.

**Comment by cd10anil** [comment]
Thanks @vitaly-t , on your comment , I am closing the issue.

**Comment by cd10anil** [comment]
Closing on @vitaly-t comments.
