### ISSUE TITLE
pg-promise hangs by unknown cause (?)

### ISSUE THREAD

**Issue by grebmeg** [vitaly-t/pg-promise#518]
### Expected behavior

pg-promise returns result after making request.

### Actual behavior

pg-promise return nothing and pg-monitor doesn't display.

### Steps to reproduce

This is strange problem, but I think it have do to with pg-promise.

I have a couple app instances, which use pg-promise (pg-monitor is enabled to debug). In a while one app instance discontinues to return result of request and pg-monitor display nothing.

There is a logging before and after query to db through pg, but request hangs and in logs I see only first logging (before request). Maybe, can I get additional info for debugging?

Could you please to help me to resolve this issue?

### Environment

* Version of pg-promise: 8.4.0
* Version of pg-monitor: 1.0.0
* OS type (Linux/Windows/Mac): Linux
* Version of Node.js: 8.11.1

**Comment by vitaly-t** [comment]
May have something to do with the query you are executing, if the query itself hangs. Sometimes the issue is with the hosting environment, when connection hangs.

**Comment by grebmeg** [comment]
But this happens in one instance of the application, the other works fine, but they are on different servers. I suppose it may be have to do with pool, but I am not sure...

Thanks for helping.

**Comment by grebmeg** [comment]
Thanks. But I didn't figure out yet in which problem. I will try to locate.
I think this issue can be closed.
