### ISSUE TITLE
Custom SQL in Column/ColumnSet

### ISSUE THREAD

**Issue by dfairaizl** [vitaly-t/pg-promise#520]
### Expected behavior
Create a `Column` (and `ColumnSet`) with custom formatted SQL columns e.g. `titles[1] as title` as a column in the select statement.

### Actual behavior

```javascript
Unexpected error in 'extend' event handler.
TypeError: Invalid column syntax: "slugs[1] as slug".
```

### Steps to reproduce

```javascript
new pgp.helpers.ColumnSet([
  'titles[1] as title'
]);
```
I've tried lots of different options and CFT formatting here as well but `Column` still tries to format the `name` key it seems.

### Environment

* pg-promise: 7.5.4 / Node 8 / OSX

**Comment by vitaly-t** [comment]
The error you are getting is perfectly correct, and there by design.

`titles[1] as title` isn't a valid column name.

**Comment by dfairaizl** [comment]
Hi vitaly-t - thanks for the quick reply! Here's some more context.

We're making extensive use of QueryFiles and want to share the columns for select statements between the different queries. But most of these queries involve the logic above - retrieving an element in an array or jsonb column and aliasing it for the output.

The query files for example look like:

```sql
select
  ${cols:raw}
from ${table}
where type = ${type}
and ${criteria.field:raw} < ${criteria.val}
order by ${orderBy.field:raw} ${orderBy.direction:raw} nulls last
limit ${limit};
```

Can this be achieved via ColumnSets?

**Comment by vitaly-t** [comment]
[ColumnSet] is there to automatically generate inserts and updates, so when it comes to multi-row inserts and updates, they can work in the same way. Selects were never in the scope, and they do not need type [ColumnSet] at all.

In your example, if you select dynamic columns with aliases then you would use `${cols:raw}` indeed. For columns without aliases you would simply use `${cols:name}`.

And in case of `${criteria.field:raw}` you should be using `${criteria.field:name}` instead, to generate [SQL Names] automatically.

[ColumnSet]:http://vitaly-t.github.io/pg-promise/helpers.ColumnSet.html
[SQL Names]:https://github.com/vitaly-t/pg-promise#sql-names

**Comment by dfairaizl** [comment]
I see thanks for clarifying that. So do you have an example of how to build up a list of columns for a select statement where certain columns have different formats?

This is what I was able to come up with:

```javascript
this.cols = [
      'id',
      pgp.as.format('$1:name[1] as $2:name', ['slugs', 'slug'])
    ].join();
```

And formatting `cols` as raw in the query file.

**Comment by dfairaizl** [comment]
Actually something like this generates the correct sql but its very verbose, is there an alternative?

```javascript
this.cols = [
  pgp.as.name('id'),
  pgp.as.name('description'),
  pgp.as.format('$1:name[1] as $2:alias', ['slugs', 'slug']),
  // + 12 more columns
].join(', ');
```

**Comment by vitaly-t** [comment]
A better question - why would you want to do this? It would only make sense if the columns were dynamic, but in your example it looks static. What are you trying to achieve, on higher level?

**Comment by vitaly-t** [comment]
After your update, ok, it is possible to automate what you are doing, for a much nicer syntax...

```js
function aliasName(name, alias) {
    return {
        toPostgres: () => pgp.as.format('$1 as $2:alias', [name, alias]),
        rawType: true
    };
}

this.cols = ['id', 'description', aliasName('slugs', 'slug')];

// Now you can inject it all via filter `:name`.

```

**Comment by dfairaizl** [comment]
To answer your first question - I'm trying to specify a "static" list of columns in my model class, and reuse those columns across a handful of query files so we have to do less maintenance.

Appreciate the help!

**Comment by vitaly-t** [comment]
A simpler syntax for sure would be to create your own Custom Type formatting class, to encapsulate list of columns, and optional aliased ones, and then format the set automatically.

**Comment by vitaly-t** [comment]
Just one crazy example to show that everything is possible, including the types override:

```js
Array.prototype.asNames = function(){
    return this.map(pgp.as.name).join();
}
```
...which you can extend to also support something like `{name, alias}` inside the array of names.

And then inside your SQL, with the help of nested named parameters:

```js
SELECT ${cols.asNames}
```

`cols` must be simply of type `Array`.

**Comment by dfairaizl** [comment]
Ah yes thats a much cleaner solution. Can you clarify our point about extending it?

> ...which you can extend to also support something like {name, alias} inside the array of names.

**Comment by vitaly-t** [comment]
You can check for each individual array element, if `{name, alias}` found, format it accordingly.

**Comment by vitaly-t** [comment]
I think this discussion has come to a happy end :smile:

**Comment by dfairaizl** [comment]
Hi @vitaly-t yes I think we're good now too. I'll give this a shot.

Thank you for adding an example!

Cheers,
Dan
