### ISSUE TITLE
pg-promise error syntax error at or near "as"

### ISSUE THREAD

**Issue by pavan6cs** [vitaly-t/pg-promise#522]
### Expected behavior
it should return the result of the query

### Actual behavior
its giving error as syntax error at or near "as".its not giving line number of error also its hard to figure out.

error:
syntax error at or near "as"
error: syntax error at or near "as"
    at Connection.parseE (D:\X157312\todo-api-master\todo-api-master\node_modules\pg-promise\node_modules\pg\lib\connection.js:539:11)
    at Connection.parseMessage (D:\X157312\todo-api-master\todo-api-master\node_modules\pg-promise\node_modules\pg\lib\connection.js:366:17)
    at Socket.<anonymous> (D:\X157312\todo-api-master\todo-api-master\node_modules\pg-promise\node_modules\pg\lib\connection.js:105:22)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:607:20)

### Steps to reproduce
im using prepared statement to query the db.below is the query when i ran the query in pg-admin it didn't give any error but it giving error when using pg-promise
 const Data = new PS({
        name:'Data',
        text: 'select ref.app_name app,ref.task_name,ifnull(g1.task_status,0) as task_status,g1.comments,g1.time_end' +
            'from gap_reports_ref as ref left join gap_reports g1' +
            'on ref.app_name=g1.app_name and ref.task_name=g1.task_name and g1.type=ref.type and ref.run_id=g1.run_id and time_end=(' +
            'select MAX(time_end)' +
            'from gap_reports as g2' +
            'where g1.app_name=g2.app_name and g1.task_name=g2.task_name and g1.run_id=g2.run_id and g2.type=g1.type ) ' +
            'where ref.run_id=$1  and ref.type=$2' +
            'order by app,g1.time_end',
        value: [runId,runType]

### Environment
* Version of pg-promise:5.97
* OS type (Linux/Windows/Mac):windows
* Version of Node.js: 8.11.3

**Comment by vitaly-t** [comment]
1. Include the full error that you are getting
2. I do not do support for such ancient version of the library as 5.9.7; You need to upgrade.

**Comment by pavan6cs** [comment]
i have update the issue with full error. please check

**Comment by vitaly-t** [comment]
@pavan6cs But you haven't upgraded the library as I asked you to.

Also, please format the code that you paste there.

**Comment by vitaly-t** [comment]
After another look, you definitely got the SQL syntax wrong there, so it's got nothing to do with this library, so I'm closing this issue as unrelated.

**Comment by pavan6cs** [comment]
hello i have upgrated the library to latest version 8.4.4 then also im getting same error,below is the formatted code but the query is working fine in pg admin
------------------------------
const PS = require('pg-promise').PreparedStatement;
const MonthlyData = new PS(MonthlyData,"select ref.app_name app,ref.task_name,ifnull(g1.task_status,0) as task_status,g1.comments,g1.time_end from gap_reports_ref as ref left join gap_reports g1 on ref.app_name=g1.app_name and ref.task_name=g1.task_name and g1.type=ref.type and ref.run_id=g1.run_id and time_end=
( 
        select MAX(time_end) 
        from gap_reports as g2 
        where g1.app_name=g2.app_name and g1.task_name=g2.task_name and g1.run_id=g2.run_id and g2.type=g1.type )  
        where ref.run_id=$1  and ref.type=$2 
        order by app,g1.time_end", [runId, runType]);

**Comment by vitaly-t** [comment]
You need to find where the syntax is broken in your SQL, and fix it. I can't help you with that, as it is not related to this library.

**Comment by pavan6cs** [comment]
ok thank u i will check the query and debug step by step
