### ISSUE TITLE
Simpler interface for array.parse()

### ISSUE THREAD

**Issue by daveisfera** [vitaly-t/pg-promise#523]
### Expected behavior
`array.parse()` can be used directly.

### Actual behavior
A function has to be written to call `create()` and `parse()`

### Steps to reproduce
[This issue](https://github.com/vitaly-t/pg-promise/issues/22#issuecomment-111827775) shows an example of using `arrayParser` and it's fairly complicated. It would be nice to be able to use `array.parse()` directly like the following (without needing to import `postgres-array`):

```
const array = require('postgres-array');
const replace = require('lodash/fp/replace');
pgp.pg.types.setTypeParser(1115, str => array.parse(str, replace(' ', 'T')));
```

### Environment

* Version of pg-promise: 8.4.4
* OS type (Linux/Windows/Mac): Mac OS X 10.13.3
* Version of Node.js: 8.11.2

**Comment by vitaly-t** [comment]
As explained in that issue, parsing an array like that is locale-dependent, and that's why it doesn't have embedded support.

**Comment by daveisfera** [comment]
Sorry, I'm not requesting that `pg-promise` have embedded support, but just that it expose the ability to call `array.parse()` directly instead of having to use `arrayParser`.

**Comment by vitaly-t** [comment]
This library doesn't validate or parse any data that arrives. All that is handled within [node-pg-types](https://github.com/brianc/node-pg-types), so I'm not sure what you are suggesting for `pg-promise`.

**Comment by daveisfera** [comment]
That I can do something like the following:

```
const replace = require('lodash/fp/replace');
pgp.pg.types.setTypeParser(1115, str => pgp.pg.types.array.parse(str, replace(' ', 'T')));
```

Basically, be able to call `array.parse()` without needing to import `postgres-array`.

**Comment by vitaly-t** [comment]
As per my previous answer, parsing data is outside of this library's scope.

And why can't you use that approach presently? What is the issue with that?

**Comment by daveisfera** [comment]
I can, but it's 1 line of code vs 10+ lines of code. It sounds like you're not interested in addressing something like this, so go ahead and close it.

**Comment by vitaly-t** [comment]
What 10 lines of code?

And I've mentioned twice that data parsing is out of scope here.

**Comment by daveisfera** [comment]
I have to do the following instead of the single line I showed above:
```
const replace = require('lodash/fp/replace');
var parseTimestampArray = function (val) {
    if (!val) {
        return null;
    }
    var p = arrayParser.create(val, function (entry) {
        if (entry !== null) {
            entry = replace(' ', 'T', entry);
        }
        return entry;
    });

    return p.parse();
};
pgp.pg.types.setTypeParser(1115, str => parseTimestampArray(str));
```

**Comment by vitaly-t** [comment]
The underlying driver generally does not support parsing arrays of custom types, so it is unavoidable that the client needs to provide its own parser. And this library cannot help you with that, as it does not parse any data coming from the driver, so it is out of scope.
