### ISSUE TITLE
Leaking active handles in azure webapp container

### ISSUE THREAD

**Issue by shaunakv1** [vitaly-t/pg-promise#524]
Hi @vitaly-t 

I have a node application which is setup exactly according to best practices prescribed , and using the [pg-promise-demp](https://github.com/vitaly-t/pg-promise-demo).

**Some background on the application:** 
Uses a postgis database to make about 40 parallel queries on various table and return analytics. Each parallel query(tasks) are returned over API and socket events.  Basically takes an polygon as area of interest and returns 40 events after data for each is processed.  We use pm2 to run the node processes and monitor them.

Good news, this works beautifully and super fast on local machines or VM installations. Problem starts when this is deployed to a Azure node web app container. 

### Expected behavior
Each request (area of interest)  starts 41 active handles (as shown in screenshot below), corresponding to connections the pool checks out form postgres.  Now on all tests, except on azure,  The **active handles** go up 41 at a time, and more as needed according to load. 

When data is processed, postgres eventually (about 30secs) drops the connections (as verified by `pg_stat_activity`). Eventually the **active handles** drop in node process as expected. 

 ### Actual behavior
**Only on azure webapp** these active handles in the node app **never drop!** they keep climbing over time, and eventually the application crashes. I have confirmed that postgres properly drops connections. Just that node doesn't recover these handles. Because code performs and scales perfectly in all non-azure installations, its very hard to debug why this could be happening. 

This is where I am hoping you can help with ideas, to debug, monitor or clues as to why this could be happening. 

### Debugging already performed: 

1. This is not related to sockets. Confirmed by taking them out of equation. 
2. Most postgres settings are same. Production postgres on azure is just lot more beefier. 
3. Tried without SSL connections. 
4. Confirmed that all code uses tasks properly where needed for related queries. 
5. Active Handles are properly collected on non azure installations. 
6. All exceptions are correctly handled and eliminated such possibilities of leaks.
7. No visible exceptions or errors on azure when this happens. Both in app and postgres logs. 
8. Active handles drop back to normal when pm2 is restarted. 

![image](https://user-images.githubusercontent.com/732604/41692274-508f464e-74cd-11e8-80f7-60400052c22d.png)

### Environment

* Version of pg-promise: `8.4.0`

* OS type (Linux/Windows/Mac): Works fine on Linux, mac and windows. but doesn't on [azure node docker container](https://github.com/Azure-App-Service/node/tree/master/9.4.0).

* Version of Node.js: 8.10.0 (9.4.0 on azure)

Also started a [stackoverflow question](https://stackoverflow.com/questions/50959142/node-postgres-pg-promise-leaking-active-handles-only-in-azure-webapp-container)

**Comment by vitaly-t** [comment]
I know nothing about Azure dock container to make any suggestions, sorry. You should instead research why connections in a Node.js app are not released on Azure as expected, and how to resolve it.

**Comment by shaunakv1** [comment]
Thanks @vitaly-t. From knowledge of the library, do you have any recommendations on how I debug why connections are not released? I have been chasing my tail on this by trying stuff. Any tooling or ideas are appreciated.

**Comment by vitaly-t** [comment]
pg-monitor only logs query-related things, nothing to do with connections.

I suspect it is something to do with the environment configuration, and definitely not on pg-promise level.

**Comment by vitaly-t** [comment]
@shaunakv1 

Found it! - https://github.com/brianc/node-postgres/issues/1627

So apparently, the issue was fixed since version 7.4.2 of the driver, which means if you use the latest pg-promise, it should just work.

**Comment by shaunakv1** [comment]
@vitaly-t  thanks much for looking it up for me! works perfectly just by bumping the library!  I must be searching the webs with wrong keywords (node handles and stuff.. ).

I say this with every issue I open, but than's for being an awesome maintainer and quick to reply!
