### ISSUE TITLE
noWarrnings not working

### ISSUE THREAD

**Issue by bbaltatu** [vitaly-t/pg-promise#525]
### Expected behavior

I expected when i call the library like this
`const pgp = require('pg-promise')({
      noWarnings: true
    });`
to not see any 
'WARNING: Creating a duplicate database object for the same connection.' messages in console.log

### Actual behavior
I see the WARNING in log

### Steps to reproduce
just run the code..

### Environment

* Version of pg-promise:
8.4.4
* OS type (Linux/Windows/Mac):
MAC
* Version of Node.js:
8.9.4

Thank you in advance

**Comment by vitaly-t** [comment]
I cannot reproduce the issue, the library works as documented. Perhaps you are doing something else that you did not enclose here.

**Comment by bbaltatu** [comment]
Sorry, it was my mistake
I called from 2 libraries and in the second one i dont use noWarnings: true
