### ISSUE TITLE
QUESTION: column names convention

### ISSUE THREAD

**Issue by jaimesangcap** [vitaly-t/pg-promise#526]
Is there a way to handle naming convention of columns? For example underscore from database to camelcase in js?

**Comment by vitaly-t** [comment]
Have you seen the example within event [receive]?

[receive]:http://vitaly-t.github.io/pg-promise/global.html#event:receive

**Comment by jaimesangcap** [comment]
Cool! exactly what I'm looking for. I gave up too quickly, sorry 😄
