### ISSUE TITLE
COPY TO and COPY FROM with async/await not working

### ISSUE THREAD

**Issue by KanishkaGit** [vitaly-t/pg-promise#527]
### Prelude
First time developer on node and postgres. having issues running pg promise with async await.

### Expected behavior

Async/Await seems NOT to be working as expected when COPY FROM or COPY TO is being called

/*------------------------------------------------ */

async function getBuildingView(req, res, next) {
                                try{
                                var filepath = '\\<server>\<directory>\<file_name>.csv';                            
                                await db.any("COPY (Select f1,f2,f3 from ( Select Cast(json_array_elements(file_content)->>'f1' as BigInt) as id, Cast(json_array_elements(file_content)->>'f2' as float) as f2, cast(json_array_elements(file_content)->>'f3' as float) as f3 FROM TBL_1   WHERE ID='"+req.params.id+"' ) TBL_1 ) TO '"+filepath+"' DELIMITER ',' CSV HEADER;").then(data => 
{
                                                                res.status(200)
                                                                                .json({
                                                                                                status: 'Success',
                                                                                                data: data[0]
                                                                                });          
                                })
                                .catch(error => {
                                                console.log('ERROR:', error);
                                });
                }catch(err){
                                console.log(err);
                }
Is  there any other specific way to wait for  complete generation of file ?
### Actual behavior

The function (db.any or db.func) is responding before complete generation of file .

### Environment

 

* Version of pg-promise: 8.4.0

* OS type (Linux/Windows/Mac): windows

* Version of Node.js: 9.2.0

**Comment by vitaly-t** [comment]
`COPY` operation isn't supported, not by this library, not by its `node-postgres` driver, because it requires specific protocol of communicating with the server, which the driver doesn't provide on its own.

This is why there is [node-pg-copy-streams](https://github.com/brianc/node-pg-copy-streams) out there, which ones has to use, unfortunately.
