### ISSUE TITLE
Support for request context

### ISSUE THREAD

**Issue by ThomWright** [vitaly-t/pg-promise#529]
This is more of a feature request than an issue, I hope this is the right place to discuss.

Basically I would like to be able to log queries a bit like so (from the docs):

```js
const initOptions = {
    query(e) {
        console.log('QUERY:', e.query);
    }
};
```

But when this query is made from an HTTP request, I want a correlation ID from the request in the log. At the moment, I don't think I can do this without recreating a connection pool for every request.

I don't know what a suitable API would be for this, this just an example to illustrate the point:

```js
const initOptions = {
    query(e) {
        // will get called when a query is made outside the context of a request
        console.log('QUERY:', e.query)
    }
};

const pgp = require('pg-promise')(initOptions)

const cn = {
  // connection params
}

const db = pgp(cn)

function(req, res) {
  const correlationID = req.headers['x-correlation-id']
  const dbWithContext = db.withContext({
    // should override the `query` callback set above
    query(e) {
      console.log(correlationID, 'REQUEST QUERY:', e.query)
    }
  })
  dbWithContext.query('SELECT * from my_table')
  // ...
}
```

An alternative I was considering was to create a wrapper with the same interface as `IDatabase`, like so:

```js
const db = pgp(cn)

function wrap(correlationID, wrappedDb) {
  return {
    query(query, values) {
      console.log(correlationID, query)
      return wrappedDb.query(query, values)
    }
    // ...
  }
}

function(req, res) {
  const correlationID = req.headers['x-correlation-id']
  const dbWithContext = wrap(correlationID, db)
  dbWithContext.query('SELECT * from my_table')
  // ...
}
```

Is there an existing API that I've missed which would allow me to do this? If not, is this something you'd be willing to support? I'm happy to discuss API and implementation if it helps.

Additionally, it would be great to be able to support something like `open-tracing`. For this, I'd like to start a _span_ on the `query` event, and end it on the `receive` event. If I were to use the event system (rather than wrapping), I'd need some way of correlating these two together for a specific query. I don't think this exists if the query isn't part of a task/tx, but I could be wrong!

Thanks for the library, it's an excellent upgrade to plain old `pg`.

**Comment by vitaly-t** [comment]
Dumbest hack - attach `correlationID` to each query string/object:

```js
const query = 'SELECT * FROM table';
query.correlationID = 123;
```
That way inside the `query` event you can access `e.query.correlationID `.

**Comment by vitaly-t** [comment]
And if you are using [Prepared Statements] or [Parameterized Queries], things get even simpler:

Example:

```js
function createParameterized(query, values, correlationID) {
    const ps = new PreparedStatement(query, values);
    ps.correlationID = correlationID;
    return ps;
}
```

[Prepared Statements]:http://vitaly-t.github.io/pg-promise/PreparedStatement.html
[Parameterized Queries]:http://vitaly-t.github.io/pg-promise/ParameterizedQuery.html

**Comment by ThomWright** [comment]
Thanks for the quick response!

Ideally I'm after an API where I can write my queries without needing to worry about correlation IDs, or any other request context.

For example, my code currently looks something like this, where the logger I pass in already has the correlation ID, so the rest of my code doesn't need to manually pass it around.

```typescript
function createDataAccess({logger, pg}: {logger: Logger; pg: IDatabase<{}>}) {
  return {
    getUser(id: string): Promise<any> {
      logger.info("getting a user")
      return pg.oneOrNone("SELECT id, username FROM users WHERE id = ${id}", {
        id,
      })
    },
  }
}
```

I have a much fuller example which I can post later, but it will have to wait until I get home!

And yeah, we're using TypeScript!

The Tags feature is useful, is there a reason there couldn't be a context for a single query outside of a task/tx?

**Comment by vitaly-t** [comment]
Wrapping the protocol like this isn't practical, as it wouldn't be reusable from inside tasks and transactions. Event [extend] should be used when extending the protocol. See also [pg-promise-demo](https://github.com/vitaly-t/pg-promise-demo).

> The Tags feature is useful, is there a reason there couldn't be a context for a single query outside of a task/tx?

Tasks and transactions provide context to be easily locate any specific query in the code, since those become reusable and can be called from anywhere. You are trying to accomplish a different task, injecting traceable parameters into queries that are not part of the query.

[extend]:http://vitaly-t.github.io/pg-promise/global.html#event:extend
