### ISSUE TITLE
can we use ENVIRONMENT_VARIABLE to the connection instance?

### ISSUE THREAD

**Issue by jared201** [vitaly-t/pg-promise#530]
example:

`const cn = {url: process.env.DATABASE_URL};`

### Environment

* Version of pg-promise:
* OS type (Linux/Windows/Mac):
* Version of Node.js:

**Comment by vitaly-t** [comment]
What's stopping you from doing so? Why did you open an issue here? See [Contributing](https://github.com/vitaly-t/pg-promise/blob/master/.github/CONTRIBUTING.md).
