### ISSUE TITLE
Example code on Performance Boost page seems incorrect (but may not be!)

### ISSUE THREAD

**Issue by danh293** [vitaly-t/pg-promise#535]
The code in question:
```
db.tx(t => {
  var queries = users.map(u => {
    return t.none('INSERT INTO Users(name, age) VALUES(${name}, ${age})', u);
  });
  return t.batch(queries);
})
```

The above is from the first code snippet on the Performance Boost page and when creating the array of queries using the map, `t.none('INSERT INTO Users(name, age) VALUES(${name}, ${age})', u)` gets evaluated immediately each time.

So, before the call to `t.batch(queries)` is even reached, `t.none()` has already been called `users.length` times.

Is this the intended behaviour? To me it seems like it should be more like:
```
db.tx(t => {
  var queries = users.map(u => {
    return () => t.none('INSERT INTO Users(name, age) VALUES(${name}, ${age})', u);
  });
  return t.batch(queries);
})
```
Notice the map returns a function now, rather than the result of calling `t.none()`.
`t.batch()` can then call the queries in turn internally however it does that.

My reasoning for questioning the behaviour is because, following a similar pattern, I had issues where I was having foreign key violations when creating the `queries` variable, because the calls were being made before I had inserted the row that the foreign keys referenced in the `t.batch()` call.
Something like:
```
db.tx(t => {
  var queries = users.map(u => {
    return t.none(<an insert with a foreign key constraint>, u);
  });
  return t.batch([<an insert that the foreign keys referenced>, ...queries]);
})
```
Maybe I'm wrong but I thought I'd double check. Great library btw :)

**Comment by vitaly-t** [comment]
The example pushes all queries as far as the IO where Node.js parallel thread will be processing them. That's how Node.js works.

Using queries as functions will only delay it, but not solve your problem. It sounds like you have a racing condition, which you should resolve by properly chaining the dependency.

**Comment by danh293** [comment]
Making the queries into functions was just a naive suggestion that prevents them from executing immediately. The main issue is that the call, `t.batch([<an insert that the foreign keys referenced>, ...queries])` looks like it is going to run the first insert and then proceed to run the queries, but, in reality, the queries have already been run when creating the `queries` variable.

**Comment by danh293** [comment]
I guess the main point I'm trying to make is that the API makes it seem like `t.batch` executes all of the queries, but this isn't the case. The queries have already been executed when creating the `queries` variable and the call to `t.batch` just does some other stuff.

**Comment by vitaly-t** [comment]
`batch` settles promises, means it makes sure each promise to its end-of-life. The way queries go through IO is another matter. If you have a dependency, you should enforce it explicitly, by not creating queries till the point where it is possible.

Makes you easier to understand when you use `ES7` async/await, or at least `ES6` generators ;)

**Comment by vitaly-t** [comment]
ES6 version:

```js
db.tx(function * (t) {
    for(let i = 0; i < queries.length; i ++) {
        yield t.none(<an insert with a foreign key constraint>, queries[i]);
    }
})
```

**Comment by danh293** [comment]
To answer your edit, yes I have now switched to using helpers :)

The main thing I find confusing about using the library in this context is that if I inline the creation of the `queries` variable into the `t.batch` call, then it will all work fine.

**Comment by danh293** [comment]
In your ES6 snippet above, where would you create the `queries` variable?

**Comment by vitaly-t** [comment]
> In your ES6 snippet above, where would you create the queries variable?

`queries` in that context in fact would be an array of objects with parameters, so really, anywhere.

**Comment by danh293** [comment]
Okay, yeah, I see that now. So instead of calling `t.batch`, you would do something like...
```
db.tx(function * (t) {
    t.none(<an insert that the foreign keys referenced>)
    .then(() => {
        for(let i = 0; i < queries.length; i ++) {
            yield t.none(<an insert with a foreign key constraint>, queries[i]);
        }
    })
})
```

Forgive me if I've completely misunderstood how ES6 generators work; haven't used them before. The main thing I was trying to do was to get it work with `t.batch` as I thought you had to use this when inside `t.tx`.

**Comment by vitaly-t** [comment]
More like this:

```js
db.tx(function * (t) {
    yield t.none(<an insert that the foreign keys referenced>)
    for(let i = 0; i < queries.length; i ++) {
        yield t.none(<an insert with a foreign key constraint>, queries[i]);
    }
})
```

**Comment by danh293** [comment]
Thanks for your help :)
