### ISSUE TITLE
Cannot figure out how to append data to a json column using pg-promise

### ISSUE THREAD

**Issue by txssseal** [vitaly-t/pg-promise#536]
### Expected behavior
Append new object to json field in postgres

### Actual behavior
it just replaces the existing object

### Steps to reproduce
this is how I am attempting to do it, and it just replaces the existing column.  I know how to do it in straight sql, but have not been able to find documentation on how to append to json column.
```
let query = pgp.helpers.update({
        transfer_states: {
          "state": "processing", 
          "created_at": new Date()}
        }, 
        null, "transfers") + `WHERE id = ${transfer.id}`;
```
### Environment

* Version of pg-promise: `8.4.5`
* OS type (Linux/Windows/Mac): `Linux`
* Version of Node.js: `8.11.3`

**Comment by vitaly-t** [comment]
This is not related to this library. It doesn't do anything JSON-specific, it just executes queries as they are.

**Comment by txssseal** [comment]
@vitaly-t very true, would love any help if you have done this

**Comment by txssseal** [comment]
nvm, I just appended the raw sql to the end of the helper.
