### ISSUE TITLE
Accept undefined and "" for null values of pg bigint

### ISSUE THREAD

**Issue by ea167** [vitaly-t/pg-promise#537]
Hello,

First of all, congrats Vitaly for this great library!

I faced several unexpected bugs using pg-promise when dealing 
with a Nullable Bigint pg column.

When I provide an object with a property that is either an empty string or is undefined,
I would have expected it would have been considered as Null in pg.
However I got either:
* Error: invalid input syntax for integer: ""
* Error: Property 'member_id' doesn't exist
 
I understand that it fully makes sense, but it would be less error-prone 
to have an option to tolerate these values as Null

### Environment

* Version of pg-promise: "8.4.5"
* OS type (Linux/Windows/Mac): Linux Ubuntu
* Version of Node.js: 10.8.0

**Comment by vitaly-t** [comment]
> When I provide an object

Objects are formatted as JSON, which is the standard. So i'm not sure what you mean by unexpected bugs :)

And if you use `undefined` as a formatting parameter, it is formatted as `null`.

> Error: Property 'member_id' doesn't exist

That's an error on your side, missing the property in the object.

> it would be less error-prone to have an option to tolerate these values as Null

You can implement it on your side either by using [Custom Type Formatting] or [helpers].

[Custom Type Formatting]:https://github.com/vitaly-t/pg-promise#custom-type-formatting
[helpers]:http://vitaly-t.github.io/pg-promise/helpers.html

**Comment by ea167** [comment]
Good to know, thank you Vitaly!
