### ISSUE TITLE
How do I use prepared statements?

### ISSUE THREAD

**Issue by nickretallack** [vitaly-t/pg-promise#54]
The changelog says you support them, but they aren't mentioned anywhere in the documentation.

**Comment by vitaly-t** [comment]
@nickretallack Here: [Prepared Statements](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#prepared-statements)

**Comment by nickretallack** [comment]
Oops, should have checked the wiki.  I guess I expected to see a link from the README file, since it's what shows up on the NPM page.

**Comment by vitaly-t** [comment]
From the main page, [Getting Started](https://github.com/vitaly-t/pg-promise#getting-started):

>To get started quickly, see our [Learn by Example](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example) tutorial.

;)

**Comment by nickretallack** [comment]
Yeah I'm blind I guess.  What lead me astray actually was [this description of the query function](https://github.com/vitaly-t/pg-promise#queries-and-parameters) which doesn't seem to leave room for passing in an object.

**Comment by vitaly-t** [comment]
Every query method that expects a text string as the first parameter, can also take a prepared statement instead.

**Comment by vitaly-t** [comment]
I your question has been answered, please close the question ;) Anyhow, I'm outta here for now , 4am local :)
