### ISSUE TITLE
[Question] When listening for trigger data, is it posisble to have the data grouped?

### ISSUE THREAD

**Issue by hawkeye64** [vitaly-t/pg-promise#540]
Sorry for communicating in the "Issues" area. I just don't know how to contact you otherwise.
Using pg-promise, I have the following class function:
```
  dbNotification (notificationCallback) {
    return new Promise((resolve, reject) => {
      this.db.connect()
        .then((connection) => {
          return connection.none('LISTEN json_notification_trigger;')
            .then(() => {
              // handler for database event notifications
              connection.client.on('notification', (data) => {
                // parse the payload from the database (needs it twice)
                let payload = JSON.parse(JSON.parse(data.payload))
                // console.log('Notification trigger:', payload)

                if (notificationCallback) {
                  // get this to the client
                  const table = payload.table_name
                  const operation = payload.sql_operation
                  const keys = payload.primary_keys
                  // call the callback with the data
                  notificationCallback(table, operation, keys)
                }
              })
              resolve(connection)
            })
        })
        .catch(function (error) {
          console.error('Database::dbNotification error:', error.message)
          reject(error)
        })
    })
  }
```
where *this.db* is:
```
  connectWithOptions (options) {
    const pgp = require('pg-promise')(this.pgpInitOptions)

    // database instance
    this.db = pgp(options)

    if (!this.db) {
      console.error('Could not get connection to database...exiting.')
      process.exit(1)
    }

    // save the pool to use its helpers
    this.pgp = pgp

    return this.db
  }
```
It basically gets our database update trigger and forwards them to *interested* code.
The problem is, if we send a query that modifies a number of rows in a table (in a transaction), then we are getting notification for each row. But testing in python shows it comes as an array, which would be much better and less overhead.
I am wondering if you have any enlightment on this or advice?
Thanks for your time.

**Comment by vitaly-t** [comment]
I'm not sure what you are really asking here...

**Comment by vitaly-t** [comment]
Closing, since no clarification provided after 3 days.

**Comment by hawkeye64** [comment]
Sorry, was on vacation and just got back.
Basically, we have some triggers on various tables in the database. PostgreSQL sends Operation (UPDATE, INSERT, DELETE)[String], table name [String] and keys ( {[table_id: 21]} ) [Array of objects] through the notification to the Node back end.
When a large update is done via a single UPDATE command, the Node back end is getting each individual ID (key) as a single message via pg-promise. However, in testing with Python, it's coming as an array for the "keys" part of the notification. I am wondering if I am not doing it right? Or, perhaps this is by design for pg-promise?

**Comment by vitaly-t** [comment]
Are you asking why Python receives data differently from Node.js?

I don't know what code you are using in Pyton :)

Within Node.js driver used here, you can request data as an array, via option `array` within [ParameterizedQuery](http://vitaly-t.github.io/pg-promise/ParameterizedQuery.html):

```js
const PQ = require('pg-promise').ParameterizedQuery;

const query = new PQ({
   text: 'some query',
   values: /* some values */,
   rawMode: 'array'
});
```

**Comment by hawkeye64** [comment]
Perfect! Thanks. I'll give it  a try. :)
