### ISSUE TITLE
Returned stream has data event handlers unexpectedly attached

### ISSUE THREAD

**Issue by bradleykirwan** [vitaly-t/pg-promise#541]
In `stream.js:49`, the stream passed to the callback has a data event handler added already:

    const stream = ctx.db.client.query(qs);

    stream.on('data', onData);
    stream.on('error', onError);
    stream.on('end', onEnd);

    try {
        initCB.call(this, stream); // the stream must be initialized during the call;

I was running into an issue in one of my components, where I was periodically piping and unpiping the stream, only to find out that the stream was not being paused after I unpiped, and thus data was lost.

I am not too sure on what the most idiomatic approach should be here, or whether it is fine to return a stream that has data event handlers added already?

I ended up piping the returned stream into a `PassThrough` stream on my end, and manipulating that instead, but I wonder if similar logic could/should be applied in this library?

Thank you

**Comment by vitaly-t** [comment]
Some of that code was to work-around shortcomings within [pg-query-stream](https://github.com/brianc/node-pg-query-stream), for which I spent quite a bit of time. If you can find a way to improve it, PR-s are welcome!

**Comment by bradleykirwan** [comment]
Sure thing - would be keen to look into this.

Some brief reading of the node stream docs reveals:
>In general, developers should choose one of the methods of consuming data and should never use multiple methods to consume data from a single stream.

So in this case I think the returned stream should be wrapped (perhaps in a PassThrough stream) so that the consumer can use data-events/piping freely.

**Comment by vitaly-t** [comment]
In my view, the biggest issue with that driver is that it fails in its very basic purpose - actually streaming data. It only makes the query interface compatible with the streaming, but the actual data is consumed as a whole at once, which defeats the very purpose of streaming large data, making it quite useless.

Typically, developers expect to process data record-by-record, and with that driver they cannot.

**Comment by bradleykirwan** [comment]
@vitaly-t Not sure I follow - are you talking about pg-query-stream? From what I understand and have read of the source, it uses a refcursor and reads n rows at a time (default 100) - further, PgQueryStream is an object mode stream, and produces a single chunk for each row, so I'm not sure what you mean by processing record-by-record; I might be missing something here?

Anyway, after thinking some more, I think the main issue with the stream implementation in pg-promise, is that a data event handler is already attached to the returned stream, which can cause a few undesirable effects, the main one being:

- Stream is switched into flowing mode automatically - this means if your consumer fails to attach to the stream before it starts producing data, then data will invariably be lost.

**Comment by vitaly-t** [comment]
After a long wait to get the PR fixed, it was closed unmerged, due to non-response. Therefore, closing this issue as well.
