### ISSUE TITLE
Support ON CONFLICT clause for bulk inserts

### ISSUE THREAD

**Issue by jamo** [vitaly-t/pg-promise#542]
While https://github.com/vitaly-t/pg-promise/wiki/Data-Imports makes massive inserts a breeze. However,  I've run frequently in cases where the bulk insert fails because of conflicts (e.g., when filling in data from export).

Postgres supports setting [`ON CONFLICT`](https://www.postgresql.org/docs/10/static/sql-insert.html#SQL-ON-CONFLICT) for bulk inserts to help to deal with these cases.

It doesn't seem to be possible to set `on conflict` clause for the inserts without manually patching the module source.

It would be nice to see first-class support for `ON CONFLICT` to land here.

**Comment by vitaly-t** [comment]
You simply append the `ON CONFLICT` part to your query, and that's it.
