### ISSUE TITLE
Type casting support in func method.

### ISSUE THREAD

**Issue by GHNewbiee** [vitaly-t/pg-promise#545]
Hi,

For more details, please visit:

https://stackoverflow.com/questions/52171970/pg-promise-support-polymorphic-types

Tia

**Comment by vitaly-t** [comment]
Your question was answered there long before you re-published it here. So why you re-published it here?

Also see [CONTRIBUTING](https://github.com/vitaly-t/pg-promise/blob/master/.github/CONTRIBUTING.md).

**Comment by GHNewbiee** [comment]
Just consider it as a feature request.

I wouldn't like to put `Feature Request` in the title. If you wish, you can consider it so and put a label.

**Comment by vitaly-t** [comment]
What feature request?

**Comment by GHNewbiee** [comment]
For type casting, such as:
```
db.func("check_value_existence", [account.username::text, "username"::text, "account"::text, "customer"::text])
.then(found => { ...})
.catch(error => {...});
```
If you do not agree, just ignore it!

**Comment by vitaly-t** [comment]
I believe I explained you well in my answer on StackOverflow that type casting has no relation to this library, as it simply executes queries. There is no feature to be considered here whatsoever.
