### ISSUE TITLE
Named Parameters in QueryFile are lost when executed within a tx

### ISSUE THREAD

**Issue by oldschoolbg** [vitaly-t/pg-promise#546]
### Expected behavior

I can use the same Query Files and Parameters within a tx / batch call as when called normally 

### Actual behavior

Error returned claiming  Property '....' doesn't exist.

### Steps to reproduce

I have the following insert/update QueryFile (insert_tournament.sql):

`INSERT INTO tournaments (id, creator_id, name, description, game_system_id, currency_id, dates, latitude, longitude, location_name, postcode, address)
VALUES (${id}, $(creator_id), ${name}, ${description}, ${game_system_id}, ${currency_id}, ${dates}, ${latitude}, ${longitude}, ${location_name}, ${postcode}, ${address})
ON CONFLICT ON CONSTRAINT tournaments_pkey
DO 
  UPDATE SET 
  creator_id = $(creator_id), 
  name = ${name},
  description = ${description},
  game_system_id = ${game_system_id},
  currency_id = ${currency_id},
  dates = ${dates},
  latitude = ${latitude},
  longitude = ${longitude},
  location_name = ${location_name},
  postcode = ${postcode},
  address = ${address},
  date_edited = CURRENT_TIMESTAMP;`

When I call it as follows (no tx) this file works correctly:

`
    queries.none("./tournaments/insert_tournament.sql", tournament)
    .then(resolve)
    .catch(reject)
`

However when I attempt to include this in a tx batch process (inserting/updating tournament, then inserting/updating competitions as related objects etc) it fails not on ${id} but on ${creator_id} - not even the first parameter on the file?

`db.tx("update_tournament", t => {
      console.log(data);
      let allQueries = [queries.none("./tournaments/insert_tournament.sql", data)];

      allQueries = allQueries.concat(data.competitions.map((c) => {
        return queries.none("./tournaments/insert_tournament_competition.sql", c)
      }));

      allQueries.push(queries.any("./tournaments/get_tournament.sql", { tournament_id : data.id }));

      return t.batch(allQueries);
    })
    .then(resolve)
    .catch(reject);`

I can see the property on the data object at that console.log(...) point:

`{ id: 'b8c49f5d-7a6f-4e0e-b886-ef29d24396dc',
  creator_id: 1,
  name: 'test',
  description: 'test',
  game_system_id: 1,
  currency_id: 1,
  is_active: undefined,
  dates: '{2018-10-18T21:00:00.000Z,2018-10-19T21:00:00.000Z,2018-10-20T21:00:00.000Z,2018-10-21T21:00:00.000Z}',
  latitude: 39.98947917011462,
  longitude: -76.84271240234375,
  location_name: 'test',
  postcode: null,
  address: 'test' }`

I have no competitions yet being saved so allQueries is an array with two promises.

### Environment

* Version of pg-promise: ^8.4.6
* OS type (Linux/Windows/Mac): Windows
* Version of Node.js: 8.9.1

**Comment by vitaly-t** [comment]
I suggest a bit more diagnostics, as transactions and `QueryFile` are unrelated, i.e. the latter doesn't care in which context it is used.

**Comment by oldschoolbg** [comment]
Hey thanks for getting back to me; I spent a good couple of hours before posting the question and have identical code, other than one called within the tx and the other (now without tx safety) from a normal promise and the promise works but the tx doesn't - I'll attach some diagnostics as soon as I can and try to find out what is actually going to the server.

Thank you for the suggestions regarding generated; I will have a look at that as well! I'm very new to postgres and am learning a lot every day so that really helps.

Cheers

**Comment by oldschoolbg** [comment]
Hey - just a quick update. I have altered my code to use the generated solution you suggested and this works with the transaction. I have not got to the bottom of why the previous attempt didn't work however this can be closed I reckon.

Thanks again for your assistance.

**Comment by vitaly-t** [comment]
I'm sure the issue you had was an overlap of sorts, because the behavior you referred to is fundamental, and if there were an issue, it would have been reported long time ago, considering how large the user base is.
