### ISSUE TITLE
Comments starting with '--' not concatenated with line break.

### ISSUE THREAD

**Issue by tumber033** [vitaly-t/pg-promise#547]
### Expected behavior
Comments starting with '--' are concatenated with line break.
Example:

    -- comment
    select * from table

### Actual behavior
Comments starting with '--' not concatenated with line break.
Example:

    -- comment;select * from table

### Steps to reproduce

    import * as pgPromise from 'pg-promise';
    const s = pgPromise().helpers.concat(['select * from table\n-- comment', 'select * from table']);
    console.log(s);

### Environment

* Version of pg-promise: 8.4.5
* OS type (Linux/Windows/Mac): Windows
* Version of Node.js: 8.11.3

**Comment by vitaly-t** [comment]
[helpers.concat](http://vitaly-t.github.io/pg-promise/helpers.html#.concat) is supposed to work with either regular flattened SQL or SQL files presented by [Query Files](https://github.com/vitaly-t/pg-promise#query-files). The latter can remove comments and flatten the SQL, by passing in option `minify`, so it is never an issue.
