### ISSUE TITLE
Can't input arrays of time without time zone

### ISSUE THREAD

**Issue by amangeot** [vitaly-t/pg-promise#548]
I'm calling a script defined on database server passing an array of inputs to `func()`, it works fine but for one type of input: `time without time zone[]`.

This is the input logged from the EventContext's query: `array['09:00:00','11:30:00','16:00:00','18:00:00']`
Which won't be recognized by db server as `time without time zone[]`,
Throwing with:
> No function matches the given name and argument types. You might need to add explicit type casts.

Shouldn't `HH:MM:SS` be recognized as time without time zone?

Sorry if I'm misusing the library and this isn't an issue with formatting inputs.

* Version of pg-promise: v8.4.6
* OS type (Linux/Windows/Mac): Windows 10
* Version of Node.js: v6.11.2

**Comment by vitaly-t** [comment]
This is a PostgreSQL-related issue/error, not related to this library.

**Comment by amangeot** [comment]
Sorry I'm new to this and thought we had to enforce array types with something like `array[]::time without timezone[]`.

I'll close this issue, thank you!
