### ISSUE TITLE
returning date and time when the column type is data

### ISSUE THREAD

**Issue by srunicornio** [vitaly-t/pg-promise#550]
pg-promise is returning date and time when the column type is data

### Steps to reproduce
```
CREATE TABLE films (
    id SERIAL PRIMARY KEY,
    name jsonb,
    release date
);
```

`pg.none('INSERT INTO films (release) VALUES ('2018/07/13')`

`const data = pg.one('SELECT release FROM films WHERE id = 1')`

### Expected behaviour

> { "release": "2018-07-13" }

### Actual behavior

> { "release": "2018-07-12T22:00:00.000Z" }

### Environment

* Version of pg-promise: 8.4.6
* OS type (Linux/Windows/Mac): Mac OS X 10.13.6
* Version of Node.js: 10.10.0

**Comment by vitaly-t** [comment]
What you describe here has no relevance to this library. It is the PostgreSQL server that auto-converts the string into the expected type `date`, and that's why it returns the value.
