### ISSUE TITLE
Question: Best practices for joins

### ISSUE THREAD

**Issue by zaidqureshi2** [vitaly-t/pg-promise#551]
What is the best practices for joins and how can the data be efficiently fetched in object format.

For example there is a user table, and an address table. They have one to one relationship, and each user has an address_id

So a sample query

`Select u.*, a.* from users u left join addresses a on a.id = u.address_id`

Is there a way to get two objects for each row say {u: {..userData...), a: {...address..data}}

I'm looking for a way to write the least amount of code.
My current solution to this problem, to write less and maintainable code is (again as an example):

```
let data = await findById(userId)
let user = new User(data)
user.address = await findAddressById(data.address_id)
...
```
Thank you.

**Comment by vitaly-t** [comment]
See the following questions.

* [Nested query object mapping with pg-promise](https://stackoverflow.com/questions/40273308/nested-query-object-mapping-with-pg-promise)
* [Combine nested loop queries to parent array result - pg-promise
](https://stackoverflow.com/questions/50391680/combine-nested-loop-queries-to-parent-array-result-pg-promise)
* [get JOIN table as array of results with PostgreSQL](https://stackoverflow.com/questions/39805736/get-join-table-as-array-of-results-with-postgresql-nodejs0

Other than that, please follow [CONTRIBUTING](https://github.com/vitaly-t/pg-promise/blob/master/.github/CONTRIBUTING.md) notes. Here's just for issues, not for questions abymore.
