### ISSUE TITLE
function uuid_generate_v1() does not exist

### ISSUE THREAD

**Issue by akhchan99** [vitaly-t/pg-promise#553]
### Expected behavior
return generated uuid

When I exectue the command directly from pgAdmin, it returned an UUID value, but when I execute it with pg-promise, I got an internal error saying uuid_generate_v1() does not exist.  

uuid_ossp extension is installed on the pg server already (that's why executing it on pgAdmin works)

### Actual behavior
function uuid_generate_v1() does not exist

### Steps to reproduce
db.one('SELECT uuid_generate_v1()');

### Environment

* Version of pg-promise: 8.4.6
* OS type (Linux/Windows/Mac): Windows
* Version of Node.js: 8.10.0

**Comment by vitaly-t** [comment]
This is a server-side error, not related to this driver.

**Comment by akhchan99** [comment]
For anyone encountering the same problem...

Its a combination of user privilege and schema...

my user account has privilege to schema Test, but the uuid-ossp is installed under public, and I set global pg-promise's schema to Test, therefore it couldn't find the function. As pg-promise send a SET schema command to the server, which makes it not able to access public's uuid-ossp extension.

So on the pg-promise init, i set mutliple schema ['public', 'Test'] and it works

**Comment by vitaly-t** [comment]
There also must be a way to configure the server to do the same. Support for option `schema` is there for cases when it is somehow not possible, or creates a lot of inconvenience.

**Comment by waynewaynetsai** [comment]
@akhchan99, thanks for the info! I had the same issue with custom Postgres syntax and solved it by setting the schema.
