### ISSUE TITLE
Rollback question

### ISSUE THREAD

**Issue by akhchan99** [vitaly-t/pg-promise#554]
I have a simple test code
Lets say user table only have 1 user (id = 1) with first_name 'X', last_name 'Y'

      let tasks = [];
      tasks.push(db.none('UPDATE userTable SET first_name = $2 WHERE user_id = $1', [1, 'A']))
      tasks.push(db.none('UPDATE userTable SET last_name = $2 WHERE user_id = $1', [1, 'B']))
      tasks.push(db.none('UPDATE userTable SET first_name = $2 WHERE user_id = $1', ['XXX', 'C']))

      db.tx(t => {
        return t.batch(tasks);
      })
      .then(data => {
        console.log(data)
      })
      .catch(error => {
        console.log(error)
      })

So the 3rd query will fail because 'XXX' doesn't match the type of id field, so it throw an error.
But when I check the table, first_name is now 'A' and last_name is now 'B' instead of rolled back to 'X' and 'Y' respectively.

Am I missing anything?

**Comment by vitaly-t** [comment]
You are mistakenly executing queries against the root context `db`, while you need to execute them against the transaction context `t`:

Here's a simplified example, using ES7 syntax:

```js
db.tx(t => {
    await t.none('UPDATE userTable SET first_name = $2 WHERE user_id = $1', [1, 'A']);
   await t.none('UPDATE userTable SET last_name = $2 WHERE user_id = $1', [1, 'B']);
   await t.none('UPDATE userTable SET first_name = $2 WHERE user_id = $1', ['XXX', 'C']);
})
  .then(console.log)
  .catch(console.error)
```

**Comment by akhchan99** [comment]
Got it, thank you
