### ISSUE TITLE
More in-template helpers for a probably all template file usage

### ISSUE THREAD

**Issue by isikfsc** [vitaly-t/pg-promise#555]
### Expected behavior
In-template template formatter syntax would be very handy, and symmetric in some way, since pg-promise already have some

### Actual behavior
However, for queries that have different syntax than some with in-template helpers, javascript helpers used for these related different syntax.
There is ${this:name} and ${this:csv} for use in an sql insert query, it is very handy, it does not require user to change and use a different query file for payloads with different keys. However, that is not available for sql update queries in-template

### Steps to reproduce
N/A

### Environment
N/A
* Version of pg-promise: n/a
* OS type (Linux/Windows/Mac): n/a
* Version of Node.js: n/a

**Comment by vitaly-t** [comment]
@isikfsc Could you, please provide examples? I'm not clear on what you are talking about.

**Comment by vitaly-t** [comment]
Closing, as the author didn't clarify what he wanted, and it is not clear from the initial context without examples.
