### ISSUE TITLE
Dynamically setting default schema for application on new request

### ISSUE THREAD

**Issue by EsaNuurtamo** [vitaly-t/pg-promise#556]
I have multitenant app that has all the tenants in different schemas. Im trying to set default search path for new requests to server depening on which url the request came from. 

At server startup i check all schemas in db and create a new db object for every one and i save these to a hashmap:
```
const createSchema = (schema) => {
  const obj = {
    ...options,
    connect: (client, dc, isFresh) => {
      if (isFresh) {
        client.query(`SET search_path TO ${schema}`);
      }
    }
  }
  return pg(obj);
}

```

In my middleware I  add the database object to req object based on url:
```
const db = databaseMap[url]
req.db = db
```

When I create these database objects on server startup i get warning:
> Creating a duplicate database object for the same connection.

Is there a better way to achieve this in multitenant application without using ${schema}.tablename in all my queries?

* Version of pg-promise: 6.4.0
* OS type (Linux/Windows/Mac): Mac
* Version of Node.js: 8.8.8

**Comment by vitaly-t** [comment]
You are supposed to be using parameter `dc` - Database Context, that's it primary purpose, to differentiate between different databases.

Also, upgrade the library to the latest, and use initialization option [schema], setting it based on on the `dc`. That is all that you need.

[schema]:http://vitaly-t.github.io/pg-promise/module-pg-promise.html
