### ISSUE TITLE
Mass import from stream using t.page

### ISSUE THREAD

**Issue by kristjank** [vitaly-t/pg-promise#561]
Trying to make mass import elegant and effective using the stream from file -> to destination DB.
I follow and tested most of the options, however looking at stream read, as I have data in a file something like this looks like the best option:
https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#into-database

I used the example above with `t.sequence` works, by passing one-by-one element, I'd like to use `t.page` to wait for let's say 50K elements to fill and then do a mass insert. and then continue. 

Some of the examples I am playing with and the working function is here:
https://github.com/ArkEcosystem/core/blob/feat/snapshosts-new/packages/core-snapshots-cli/lib/transport/index.js#L97-L129
So the questions:
- how is sequence or page performed, since during the large file import, memory got filled first and then and only after the final callback was done https://github.com/ArkEcosystem/core/blob/feat/snapshosts-new/packages/core-snapshots-cli/lib/transport/index.js#L60 the data started to save to database and not before, during batches

- how to change and effectively use t.page and set chunk size to a few thousands of records.

I also tested docs here: https://stackoverflow.com/questions/41795332/massive-inserts-with-pg-promise.  Also in that file, there are several other examples for using different import options...

**Comment by vitaly-t** [comment]
> how is sequence or page performed

http://vitaly-t.github.io/spex/global.html#page

**Comment by kristjank** [comment]
Sure, get well soon. 👍 

What troubles me is the memory consumptions and why is not writing to db during the stream read.

**Comment by vitaly-t** [comment]
@kristjank I'm still baddling here. Have you made any progress in the meantime? I gave the link to method [page] documentation earlier, and as you can see, it supports option `limit` there.

[page]:http://vitaly-t.github.io/spex/global.html#page

**Comment by kristjank** [comment]
Used a different approach. Would still like to see it working with stream. 

Get better ;)

**Comment by kristjank** [comment]
Yes I used that one from the start combining with stream. Wanted a cleaner solution for stream (source, destination)-but looks like the example is faster anyway so will stick with him. tnx

**Comment by kristjank** [comment]
if you have any comments on this import here : https://github.com/ArkEcosystem/core/blob/feat/snapshosts-new/packages/core-snapshots-cli/lib/transport/index.js#L34-L73. feel free to add some. tnx
