### ISSUE TITLE
[Question] QueryFile -> RawTextQuery

### ISSUE THREAD

**Issue by kristjank** [vitaly-t/pg-promise#563]
Is there a way to convert a loadedQueryFile to raw text query before it hits the server. 
Would need it for QueryStream operation where only string query is accepted.

So is it possible to load a query from queryFile directly to this method.
https://github.com/ArkEcosystem/core/blob/feat/snapshosts-new/packages/core-snapshots-cli/lib/transport/index.js#L22 
`new QueryStream('SELECT * FROM TABLE names')` - works
`new QueryStream(sql.find, {name: user.name}) - fails.

So is there an efficient way to get raw text representation of queryFile loaded query, with values already replacing parameters.

tnx

**Comment by vitaly-t** [comment]
Yeah, that `QueryStream` is a third-party type, so it can't handle type `QueryFile`.

Type `QueryFile` supports [Custom Type Formatting](https://github.com/vitaly-t/pg-promise#custom-type-formatting) (the [Symbolic](https://github.com/vitaly-t/pg-promise#symbolic-ctf) one), so you can do:

```js
// qf = your QueryFile object

const ctf = pgp.as.ctf;
const query = qf[ctf.ToPostgres](); // gets the most current query, according to the internal `debug` option
```

**Comment by vitaly-t** [comment]
On second thought though, it would be a much better use of the library to rely on the internal query-formatting engine manually in this situation:

```js
const query = pgp.as.format(qf, params);
```

That way you will automatically get the query + format it using pg-promise native syntax, so for example you can use [Named Parameters](https://github.com/vitaly-t/pg-promise#named-parameters), i.e. full formatting syntax supported by the library.

**Comment by kristjank** [comment]
ok, nice thanks for the answer, will use the second option and let you know. 👍

**Comment by vitaly-t** [comment]
I take it, this has been resolved.
