### ISSUE TITLE
wiki/Connection-Syntax miss SSL informations

### ISSUE THREAD

**Issue by Raphyyy** [vitaly-t/pg-promise#564]
Hello and thank you for your work !

Like described here : https://stackoverflow.com/questions/22301722/ssl-for-postgresql-connection-nodejs
pg-promise is lacking of documentation about SSL settings here : https://github.com/vitaly-t/pg-promise/wiki/Connection-Syntax

**Comment by vitaly-t** [comment]
Thank you for reporting!

I have updated the [Connection Syntax](https://github.com/vitaly-t/pg-promise/wiki/Connection-Syntax) page to mention type [TSSLConfig] that's explicit when using TypeScript.

[TSSLConfig]:https://github.com/vitaly-t/pg-promise/blob/master/typescript/pg-subset.d.ts#L53
