### ISSUE TITLE
Massive Insert from readable stream

### ISSUE THREAD

**Issue by yhrchan** [vitaly-t/pg-promise#570]
I have been scratching my head and spent 2 days to try and figure out how to get the Massive Insert from readable stream (json file) to work. I got the basic Massive Insert running as documented where the data was generated from a loop along with the page index and have also consulted the Data Imports page. However, without luck. Any help or examples with that would be greatly appreciated!

Thanks!

**Comment by yhrchan** [comment]
I have came across this: https://github.com/spion/promise-streams/issues/7
and your first comment there is what exactly I am trying to solve but without luck =(

**Comment by vitaly-t** [comment]
Do you want to shared your code? Otherwise I cannot advise any better than it is done within [Data Imports].

[Data Imports]:https://github.com/vitaly-t/pg-promise/wiki/Data-Imports

**Comment by yhrchan** [comment]
Thanks for your quick reply. Below is what I have currently, been trying different things but couldn't figure it out. Right now it reads a json file (theoretically a huge file) but that will bomb (javascript heap out of memory) since it reads everything in one go and ingest that into the "t.none(insert)" command. I am not an advance user of Streams and also recognize that there might be complications due to the nature of Streams and Promises. I am just not sure how to break reading the stream into batches and have many "t.none(insert)" so that it will keep the memory footprint manageable. Thanks!



let reader = fs.createReadStream('some json file');

const jsonStream = JSONStream.parse(['properties']);
let lineNumber = 0;

// commented the below out since not sure how pageIndex relates to a Stream
//function getNextData(t, pageIndex) {
function getNextData() {

  return new Promise((resolve, reject) => {
    let data = [];

    reader
      .pipe(es.split())
      .pipe(jsonStream)
      .pipe(es.mapSync(line => {
        ++lineNumber;

        //console.log(`${lineNumber} => ${JSON.stringify(line)} \n`);

        data.push(line);
      })
      .on('end', function() {
        console.log('Read entirefile. ' + data.length);
        resolve(data);
      })
    );

    
  })
}

db.tx('massive-insert', t => {
    //return t.sequence(index => {
      //return getNextData(t, index)
        return getNextData().then(data => {
          if (data) {
            const insert = pgp.helpers.insert(data, cs);
            return t.none(insert);
          }
        });
  })
  .then(data => {
    // COMMIT has been executed
    //console.log('Total batches:', data.total, ', Duration:', data.duration);
  })
  .catch(error => {
    // ROLLBACK has been executed
    console.log('oh no');
    console.log(error);
  });

**Comment by vitaly-t** [comment]
You should read data in chunks that can be kept in memory, then insert those, and only then read the next one. Instead, you are reading everything in, which overloads the memory.

**Comment by vitaly-t** [comment]
It needs to be debugged to see the exact issue. I cannot do with a piece of code, neither I'd have the time. I suggest that if you still have this problem, try to narrow it down, and ask it on StackOverflow.

**Comment by mypirateapp** [comment]
Same issue [HERE](https://stackoverflow.com/questions/62670472/how-do-i-run-an-update-while-streaming-using-pg-query-stream-and-pg-promise) The real question now is how to invoke getNextData and t.sequence inside the pg-query-stream s 'data' event because as per @yhrchan I understand that he s filling the array completely first then trying to call db.tx at the end which obviously holds everything in memory. My understanding is that somehow this has to be done inside the data event where you get rows one by one

**Comment by mypirateapp** [comment]
I did not figure out how to use the getNextData() and t.sequence method inside a stream but I have made a workaround that does roughly the same thing

```
const BATCH_SIZE = 5000
async function batchInsert({ db, pgp, logger, data }) {
  try {
    // https://vitaly-t.github.io/pg-promise/helpers.ColumnSet.html
    const cs = new pgp.helpers.ColumnSet(
      [
        { name: 'feed_item_id', cast: 'uuid' },
        { name: 'tags', cast: 'varchar(64)[]' },
      ],
      {
        table: 'feed_items',
      }
    )
    const query =
      pgp.helpers.update(data, cs) + ' WHERE v.feed_item_id=t.feed_item_id'
    await db.none(query)
  } catch (error) {
    logger.error(error)
  }
}

async function tagAll({ db, pgp, logger, tagger }) {
  // you can also use pgp.as.format(query, values, options)
  // to format queries properly, via pg-promise;
  const qs = new QueryStream(
    'SELECT feed_item_id,title,summary,content FROM feed_items ORDER BY pubdate DESC, feed_item_id DESC'
  )
  try {
    const queryValues = []
    const result = await db.stream(qs, (s) => {
      // initiate streaming into the console:
      s.pipe(JSONStream.stringify())
      s.on('data', async (item) => {
        try {
          s.pause()
          // eslint-disable-next-line camelcase
          const { feed_item_id, title, summary, content } = item

          // Process text to be tagged
          const text = prepareText(title, summary, content)
          const tags = tagger.tag(text)
          queryValues.push({ feed_item_id, tags })

          if (queryValues.length >= BATCH_SIZE) {
            const data = queryValues.splice(0, queryValues.length)
            await batchInsert({ db, pgp, logger, data })
          }
        } catch (error) {
          logger.error(error)
        } finally {
          s.resume()
        }
      })
    })
    await batchInsert({ db, pgp, logger, data: queryValues })
    return result
  } catch (error) {
    logger.error(error)
  }
}

```

**Comment by yhrchan** [comment]
@mypirateapp so you are able to resolve this using the code you've provided above? I think I've used something similar to solve my issue in the past using stream pause and resume, batch the jobs together until a threshold number and then initiate the pg batch inserts until all of the stream has been processed, this way, it won't eat up the memory

**Comment by oneilk** [comment]
@yhrchan Would you be able to provide a code snippet? I am trying to do the same exact thing. Every time I come across someone asking the same question, there's never really an example posted.

Thanks so much for any insight.

**Comment by sachi9verma** [comment]
I was trying to do something similar sometime ago. Here is the workaround I remember trying. I was getting a readable stream from a csv file so piped the it to the csv parser fastcv.
Basically reading from the stream within the transaction funtion and forming batches of inserts statements inside the stream's on 'data' event handler and adding it to transcation.
I wait for the stream to finish before returning from the transaction function:

transactionStream(instream){
let tBatch=[];
let insVal=[];
let batchSize=1000;
const colSet=new pgp.helpers.ColumnSet(['name'],{table:'demo'})
db.tx('massive-insert', async t=>{
//function to read stream and add transaction batches
 const readTransactionalStream=()=> new Promise((resolve,reject)=>{
 let csvStream = fastcsv.parse()
 .on("data", function(data){
 row={name:data[0]};
 insVal.push(row);
 if(insVal.length==batchSize){
   const insertSt=pgp.helpers.insert(insVal,colSet);
   tBatch.push(t.none(insert));
   insVal=[];
 }
 }).on("end", function(){
  //add remaining data if any
  if(insVal.length){
   const insertSt=pgp.helpers.insert(insVal,colSet);
   tBatch.push(t.none(insert));
  })

 //instream is the readableStream from CSV file
  instream.pipe(csvtream).on("finish",resolve).on("error",reject)
 )}
 await readTransactionalStream()
 return t.batch(tBatch)
 })
.then(data=>{console.log("total batches: ", data.total)}
.catch(error=>console.log(error))
 }
