### ISSUE TITLE
When updating data it takes not the current query but the previous one and run it

### ISSUE THREAD

**Issue by Guzzur** [vitaly-t/pg-promise#572]
### Expected behavior
Updating data should use the current query

### Actual behavior
Updating data takes not the current query but the previous one and run it

### Steps to reproduce
Run two or more subsequent query, check the updated data in the DB after each one

### Environment
* Version of pg-promise: v8.4.6
* OS type (Linux/Windows/Mac): Ubuntu 16.04
* Version of Node.js: v10.10.0

**Comment by vitaly-t** [comment]
I don't mean to be rude, but this is absurd.
