### ISSUE TITLE
How does pg Task works

### ISSUE THREAD

**Issue by balars** [vitaly-t/pg-promise#575]
I have node js backend and each request has ten select queries to execute.  I can see that postgres always runs one query per connection at a point of time and next query is getting executed once the previous query is completed. If i use pg task, then all the queries are going to use one connection. Each query would be waiting for the previous query to complete. Does this waiting time increase event queue delay on app side or the waiting happens on postgres side

* Version of pg-promise: 6.4
* OS type (Linux/Windows/Mac): Linux
* Version of Node.js: 6.4

**Comment by vitaly-t** [comment]
This forum is for rising issues. For questions please use [StackOverflow](https://stackoverflow.com) in the future.

> Does this waiting time increase event queue delay on app side or the waiting happens on postgres side

It is on the app side. If you want it to be on the server side, then execute it all as one query. For an example, see this recent question: [Returning different queries together as a JSON object vs. multiple queries](https://stackoverflow.com/questions/53851409/returning-different-queries-together-as-a-json-object-vs-multiple-queries).
