### ISSUE TITLE
Table alias in generated insert script

### ISSUE THREAD

**Issue by aldobrynin** [vitaly-t/pg-promise#576]
Hi!
Is there any way to generate insert script using [helpers](http://vitaly-t.github.io/pg-promise/helpers.html#.insert) with alias for target table? (which is correct syntax for PostgreSQL https://www.postgresql.org/docs/11/sql-insert.html)

For example:
```sql
INSERT INTO public.users AS t (name, email)
VALUES ('John Doe', 'doe@example.com')
```
Real use-case for this this alias is to use this script as base for upsert sql script:
```sql
INSERT INTO public.users AS t (name, email)
VALUES ('John Doe', 'doe@example.com')
ON CONFLICT (email)
DO UPDATE SET t.name = EXCLUDED.name
WHERE t.name IS NOT NULL
```
Without that alias in where clause postgresql will throw an error:
`column reference "name " is ambiguous`

What do you think on adding option to set alias for target table?

**Comment by vitaly-t** [comment]
In your example, if you simply remove `t` everywhere, it will work the same.

**Comment by vitaly-t** [comment]
Example of how to format such a query:

```js
const q = pgp.as.format(`INSERT INTO public.users AS t($1:raw) VALUES $2:raw ON CONFLICT(email) 
                         DO UPDATE SET $3:raw WHERE t.name IS NOT NULL`,
    [cs.names,
    pgp.helpers.values(data, cs),
    cs.assignColumns({from : 'EXCLUDED', to: 't'})]);
```

where `cs` is the ColumnSet, and `data` is the array of insert objects.

**Comment by aldobrynin** [comment]
Yay, thanks! I knew it possible but didn't look at format method.
Yea, query is very special and this probably shouldn't be part of common API

**Comment by vitaly-t** [comment]
`format` method is just an example, you do not need to use it, you can just pass the query template + formatting parameters directly into your query method.

> And you can pass in the template + formatting parameters directly into your query method, to be formatted by it.
