### ISSUE TITLE
Database result: doc outdated?

### ISSUE THREAD

**Issue by tmtron** [vitaly-t/pg-promise#581]
from [Database result](http://vitaly-t.github.io/pg-promise/Database.html#result):
>When receiving a multi-query result, only the last result is processed, ignoring the rest.

I think (and hope) that this info is outdated since #405 has been fixed

**Comment by vitaly-t** [comment]
It is not outdated. What makes you think it would be? :)

**Comment by tmtron** [comment]
yes, I am confused...  
So is there currently a way to execute a multi-query and get back [node-result](https://node-postgres.com/api/result) objects for each of them?

**Comment by vitaly-t** [comment]
[multiResult](http://vitaly-t.github.io/pg-promise/Database.html#multiResult).

**Comment by tmtron** [comment]
thanks - somehow I missed that and concentrated too much on the `result` function..
