### ISSUE TITLE
Question: It seems to me the main selling point for this library is to wrap node-postgres and provide a promise based interface...

### ISSUE THREAD

**Issue by johncmunson** [vitaly-t/pg-promise#582]
...however, looking at the docs for node-postgres it seems that they already provide a promise interface out of the box (in addition to supporting callbacks). Am I missing something here? I'm just a little confused and trying to decide which library to move ahead with.

https://node-postgres.com/features/queries

**Comment by vitaly-t** [comment]
Perhaps start with the [About](https://github.com/vitaly-t/pg-promise#about) section, that's why it is there, at the very beginning.
