### ISSUE TITLE
Questions about using `ST_GeomFromText` function.

### ISSUE THREAD

**Issue by yepengfan** [vitaly-t/pg-promise#583]
Hey there,
I am an absolute noob in the geolocation database, and currently, I am trying to use `pg-promise` to add some polygon/point in my tables. I followed this link on StackOverflow which wrote by the library author. Here is the link: https://stackoverflow.com/questions/41856222/pg-promise-pass-a-function-as-parameter-to-func

Here I have a table structured like this
Table A
- id (Number)
- position (Geometry)

And when I tried to execute a query
```
const point = (polygon) => ({
  toPostgres: () => pgp.as.format('ST_GeomFromText(\'POLYGON($1)\', 4326)', [polygon]),
  rawType: true,
});
return this.db.one('INSERT INTO table_a(id, position) VALUES($1, $2) RETURNING id', [index, point]);

```
I got an error as `"errorMessage": "parse error - invalid geometry"`. 

It looks like the term `POLYGON` is not acceptable from the query. Could you advise me which is the best way to insert a polygon to the table?

Cheers

**Comment by vitaly-t** [comment]
Your question pertains to SQL syntax, and not this library.
