### ISSUE TITLE
[question] Obtain Access Locks on the table

### ISSUE THREAD

**Issue by AkshayMehta90** [vitaly-t/pg-promise#586]
We need to get transaction level locks on the database. Meaning only transaction, irrespective of read or write, should be running on the database. Can we achieve that with pg-promise?

**Comment by vitaly-t** [comment]
This library doesn't impose any limitation on transactions, so you can whatever you like with them.

Other than that, as per [Contributing] document, post your questions on StackOverflow. Here's just for issues reporting.

[Contributing]:https://github.com/vitaly-t/pg-promise/blob/master/.github/CONTRIBUTING.md
