### ISSUE TITLE
Consider using es6 template strings for queries parameters

### ISSUE THREAD

**Issue by krzkaczor** [vitaly-t/pg-promise#588]
You might want to consider using es6 template strings to format queries. Something like https://www.npmjs.com/package/sql-template-strings

**Comment by vitaly-t** [comment]
No thank you. The query-formatting engine in this library is way more powerful and flexible.

And when it comes to external SQL files, those ES6 template strings are completely useless.

**Comment by krzkaczor** [comment]
If anyone feels like they really need this feature, [slonik](https://github.com/gajus/slonik) supports it.
