### ISSUE TITLE
Queries not parametrized

### ISSUE THREAD

**Issue by EsaNuurtamo** [vitaly-t/pg-promise#595]
### Expected behavior
I expect every method to be parametrized and prevent sql-injection.

### Actual behavior
However the parameter accepts sql injection:
```
db.one('SELECT * FROM Table WHERE id = $1#, '35 AND 50=50')
=>
query: SELECT * FROM Table WHERE id = 35 AND 50=50
```

It only works if i use prepared statement formatting:
```
db.one({text: 'SELECT * FROM Table WHERE id = $1, values: ['30 AND 50=50']})
=>
error: invalid input syntax for integer: "26 AND 50=50"
```

### Steps to reproduce
Use single or multiple parameter method showed in examples of this repo and put sql injektion string as parameter.

### Environment

* Version of pg-promise: 8.6.4
* OS type (Linux/Windows/Mac): Mac Sierra
* Version of Node.js: 10.12

**Comment by vitaly-t** [comment]
You specifically put `#` filter to allow the injection, and then complain it injected the value?

Filters such as raw text and open value are by definition, not safe, so if you decide to use them, you need to take other precautions.

**Comment by EsaNuurtamo** [comment]
Oh, my mistake. I still think there could be a clear warning that open values.

What is the recommended way to prevent sql injection then? 
Is there some drawback to always using Parameterized Queries?

**Comment by vitaly-t** [comment]
I have done it more explicit, by adding the following warning to [Open Value] and [Raw Text]:

**WARNING:**
This filter is unsafe, and should not be used for values that come from the user input, as it may result in [SQL injection].

[Open Value]:https://github.com/vitaly-t/pg-promise#open-values
[Raw Text]:https://github.com/vitaly-t/pg-promise#raw-text
[SQL injection]:https://en.wikipedia.org/wiki/SQL_injection
