### ISSUE TITLE
not working multi-update with NULL values(casting null type)

### ISSUE THREAD

**Issue by eldosnarbay** [vitaly-t/pg-promise#597]
### Expected behavior
Should handle null values when updating multiple rows

### Actual behavior
`error: column "col1" is of type integer but expression is of type text`

### Steps to reproduce
 pgp.helpers.update() for multi-row 'update' generates query like: 
`=> UPDATE "mytable" AS t SET "col1"=v."col1","msg"=v."msg" FROM (VALUES(1,123,'hello'),(2,456,'world!'))
  AS v("id",null,"msg") WHERE v.id = t.id`
, but if updating numeric type column with NULL value, it thrown error:

### Environment

* Version of pg-promise: 8.6.3
* OS type (Linux/Windows/Mac): Windows
* Version of Node.js: v10.13.0

**Comment by vitaly-t** [comment]
You are talking about updating with `null` value, but I do not see any `null` value in your update query. Could you, please correct your code query accordingly, so we can see what values are indeed being updated.

**Comment by eldosnarbay** [comment]
@vitaly-t For example, I have table:
`CREATE TABLE mytable
(
  id integer primary key,
    col1 integer,
   msg varchar(50)
)`

and when I try update values:
`
 const dataMulti = [{id: 1, col1: null, msg: 'hello'}, {id: 2, col1: null, msg: 'world!'}];
 const cs = new pgp.helpers.ColumnSet(['?id', 'col1', 'msg'], {table: 'mytable'});
 pgp.helpers.update(dataMulti, cs) + ' WHERE v.id = t.id';
`
it throws error:
`error: column "col1" is of type integer but expression is of type text`

**Comment by vitaly-t** [comment]
Here, I've just done the exact code run you provided:

```js
const pgp = require('pg-promise')({
    capSQL: true
});

const dataMulti = [{id: 1, col1: null, msg: 'hello'}, {id: 2, col1: null, msg: 'world!'}];
const cs = new pgp.helpers.ColumnSet(['?id', 'col1', 'msg'], {table: 'mytable'});
const query = pgp.helpers.update(dataMulti, cs) + ' WHERE v.id = t.id';
console.log(query);

//-> UPDATE "mytable" AS t SET "col1"=v."col1","msg"=v."msg" FROM (VALUES(1,null,'hello'),(2,null,'world!')) AS v("id","col1","msg") WHERE v.id = t.id
```

All looks as it's supposed to be. There must be something else going on there. Please check.

**Comment by eldosnarbay** [comment]
try add records to table
`
insert into currency_user.mytable(id, col1, msg) values (1, 5, 'test');

insert into currency_user.mytable(id, col1, msg) values (2, 45, 'test');`
 execute the query: 
`db.any(query);`

**Comment by vitaly-t** [comment]
The issue in your case is that you are trying to update an integer with a `null`, which in SQL syntax requires explicit type casting as `::integer`.

To that end you need to correct your ColumnSet definition:

```js
const cs = new pgp.helpers.ColumnSet(['?id', {name: 'col1', cast: 'integer'}, 'msg'], {table: 'mytable'});
```

It is as simple as that :smile: See also type [Column](http://vitaly-t.github.io/pg-promise/helpers.Column.html) for the full column syntax.

**Comment by eldosnarbay** [comment]
thanks, thats work))
