### ISSUE TITLE
Is it possible to dynamically create database connections?

### ISSUE THREAD

**Issue by michaelangeliu** [vitaly-t/pg-promise#598]
We have set up a database with an access layer where different database users can have access to views which change based on their access level. However, that database user may not exist when the request is made, so they may need to be created and granted access.

Essentially our desired workflow is as follows:

1. User makes a request from the application
2. pgp connects to the database as an admin and checks if the user exists
  a. if the user does not exist, create the user and grant the appropriate permissions, return the user credentials.
  b. if the user does exist, return the user credentials
3. Using the returned user credentials, create a new pgp connection to the database as that user.
4. Using the new pgp connection, complete the application request
5. Release the connection from this user
6. Release the connection from the admin

I'm running into an issue where it seems like the connection has been released, but the database object from the user to the database still exists, so on a subsequent request from the same user. It's finding the duplicate database object for the same connection.

Should I just call `pgp.end()` to terminate all connections and make a new connection for each request?

**Comment by vitaly-t** [comment]
As per the [Library De-Initialization](https://github.com/vitaly-t/pg-promise#library-de-initialization), you should do `db.$pool.end()` on the database object you want to release.

**Comment by michaelangeliu** [comment]
That worked perfectly! Thanks!
