### ISSUE TITLE
In POST request, unknown colums have values

### ISSUE THREAD

**Issue by prajmehta** [vitaly-t/pg-promise#60]
How can I structure a .post using pg-promise when I have unknown number of columns with values?  So I don't know how many of $1, $2, $3 .. should i put and which maps to which column.

I am building my api server using expressjs and postgres.
My postgres table is

<pre>
$=> \d+ locations
                       Table "$.locations"
       Column        |            Type             | Modifiers                    | 
---------------------+-----------------------------+--------------------------------
 location_id         | integer                     | not null default nextval ... | 
 short_name          | character varying(100)      | not null                      
 long_name           | character varying(300)      |                                
 physical_address1   | character varying(300)      | not null                       
 physical_address2   | character varying(300)      |                                
 physical_city       | character varying(100)      | not null                       
 physical_state      | character varying(20)       |                                
 physical_postalcode | character varying(20)       |                                
 physical_country    | character varying(100)      | not null                       
 physical_latitude   | numeric(12,0)               |                                
 physical_longitude  | numeric(12,0)               |                                
 mailing_address1    | character varying(300)      |                                
 mailing_address2    | character varying(300)      |                                
 mailing_city        | character varying(100)      |                                
 mailing_state       | character varying(20)       |                                
 mailing_postalcode  | character varying(20)       |                                
 mailing_country     | character varying(100)      |                                
 created_at          | timestamp(6) with time zone | default now()                  
 modified_at         | timestamp(6) with time zone |                                
Indexes:
    "locations_pkey" PRIMARY KEY, btree (location_id)
</pre>

My post block looks like
<pre>
router.post('/locations', function(req, res){
     // convert req.body json object into array of values
     var locationVar = Object.keys(req.body).map(function(index) { return req.body[index]; });
     db.one("insert into findnow.locations " +
                 "values ($1, $2, $3, $4) "
                 +"returning location_id "
                 , locationVar)
         .then(function (data) {
             console.log(data.location_id);
         }, function (reason) {
             console.log('Insert into /locations failed for ', reason); // print error;
         })
         .done(function () {
             pgp.end(); // closing the connection pool, to exit immediately.
         });
  });
</pre>

My issue is that the user may provide some of these values and I'd like to still accept her post.  How can I structure my code to not have to test what she is sending?

Thanks so much in advance.

Raj

**Comment by vitaly-t** [comment]
Looking at the list of columns that you provided, they don't look dynamic, they look quite predefined, and if you try to treat known fields as generic ones, then you loose their type information, which already prevents you from doing any kind of intelligent query formatting. For example, date fields won't even work.

You shouldn't treat such list of fields as dynamic, and access fields normally, while converting to their appropriate types, so query formatting can work properly.

And you shouldn't use this section within your post section:
```javascript
 .done(function () {
                        pgp.end(); // closing the connection pool, to exit immediately.
                    })
```
because this shuts down the library, and to be used only when exiting the application.

**Comment by prajmehta** [comment]
Thanks for your quick comment.

Is there any way to dynamically match the req.body names with the column names in the insert sql?

**Comment by vitaly-t** [comment]
As explained earlier, if you treat your fields as generic, you are missing their type information. Without type information you query formatting doesn't know how to format the values, and in fact neither can you. You cannot, for example, treat strings and date fields in the same way. Your fields aren't of the same type, they are of different types, so you have to treat them according to their type, you cannot do it in a generic way.

>Is there any way to dynamically map the req.body names with the column names in the insert sql?

Only when they are of the same known data type, which they aren't in your example.

**Comment by vitaly-t** [comment]
@prajmehta if your question has been answered, then please close the issue.
