### ISSUE TITLE
Cockroach DB Support 

### ISSUE THREAD

**Issue by vivinjoy** [vitaly-t/pg-promise#602]
Are there plans to support Cockroach DB ? Cockroach DB is compatible with PostgresSQL and uses almost the same dialect. (https://www.cockroachlabs.com/blog/why-postgres/).  It will be great if you can mention in the documentation whether Cockroach DB is explicitly supported and if so, what all features are currently supported ?

**Comment by vitaly-t** [comment]
Actually, no need, see [Using this package with cockroachdb](https://github.com/brianc/node-postgres/issues/1260). There you have it.
