### ISSUE TITLE
Why empty result is error?

### ISSUE THREAD

**Issue by soshnikov** [vitaly-t/pg-promise#605]
### Expected behavior
Empty SELECT result is a normal result

### Actual behavior

Empty SELECT result is error

### Steps to reproduce

SELECT any empty query

### Environment

* Version of pg-promise: 8.6.5
* OS type (Linux/Windows/Mac): Linux
* Version of Node.js: 10.15.2

Thanks.

**Comment by vitaly-t** [comment]
Please include the error details.

**Comment by soshnikov** [comment]
```javascript
const PgPromise = require('pg-promise');

const ParamQuery = PgPromise.ParameterizedQuery;
const db = require('../db/db');

module.exports = async id => {
  const coursePromise = db.one(
    new ParamQuery(
      `SELECT id, name, summary, published, private, description 
       FROM public.school_course 
       WHERE id = $1`,
      [id],
    ),
  );

  const studentsPromise = db.many(
    new ParamQuery(
      `SELECT username, email, first_name, last_name, '' AS avatar
       FROM auth_user
       WHERE
        auth_user.id IN ( SELECT school_student.user_id FROM school_student WHERE course_id = $1)`,
      [id],
    ),
  );

  const lecturesPromise = db.many(
    new ParamQuery(
      `SELECT id, title, summary, published
      FROM school_lecture
      WHERE course_id = $1
      ORDER BY title
      `,
      [id],
    ),
  );

  const results = await Promise.all([coursePromise, studentsPromise, lecturesPromise]);
  const course = results.shift();
  course.students = results.shift().map(v => ({
    email: v.email,
    full_name: `${v.first_name} ${v.last_name}`.trim(),
    avatar: v.avatar,
  }));
  course.lectures = results.shift();
  return course;
};
```
If studentsPromise or lecturesPromise have no data I get __"No data returned from the query."__ ( http://vitaly-t.github.io/pg-promise/errors.QueryResultError.html )

Don't understand why empty result is error. It's normal, Ok? Yes, no data. It's may be null or {} or []. But error... I'm doing something wrong?

**Comment by vitaly-t** [comment]
You should read the docs, it is at the very beginning of the library's introduction, explaining how methods are to be used - [Methods](https://github.com/vitaly-t/pg-promise#methods).

**Comment by soshnikov** [comment]
Thanks for your job and support.
