### ISSUE TITLE
Column Name format for table.column

### ISSUE THREAD

**Issue by AhmedFat7y** [vitaly-t/pg-promise#606]
I'm not sure if this is an issue or it's intended

### Expected behavior
`pgp.as.name('Users.ID')` should generate `"Users"."ID"`

### Actual behavior
`pgp.as.name('Users.ID')` generates `"Users.ID"` which is invalid

### Environment

* Version of pg-promise: 8.6.5
* OS type (Linux/Windows/Mac): Mac
* Version of Node.js: 10.5.0

**Comment by vitaly-t** [comment]
There is no issue there, the method does exactly what it is supposed to, escapes a single identifier.

**Comment by AhmedFat7y** [comment]
@vitaly-t Could we have that functionality as part of the formatting engine? Sometimes one need to use `"Table"."column"` to avoid ambiguity errors.

**Comment by vitaly-t** [comment]
@AhmedFat7y For that there are [SQL Names](https://github.com/vitaly-t/pg-promise#sql-names):

```js
('${table:name}.${column:name}', {table, column})
```

**Comment by AhmedFat7y** [comment]
The use case was sth like this
`
SELECT "firstName", "lastName", "Users"."userID", "email",
    "userPassword", "phone", "Users"."createdAt",
    "resetPasswordHash", "resetPasswordHashExpiry",
    "userRole", "hasPets", "status", "isOptInNewsLetter",
    "facebookID", "googleID", "dataSource", "isSocial"
...
`

I had to include them in the query because one of them needed "Users"."userID" while it would have been better for example to use the `$(columns:name)` and provide `values: {firstName, lastName, ...}`

Although this one is static and was ok to go for hardcoding the columns, I wanted to investigate if it happens to be dynamic, should we revert back to string interpolation using js template literals?

**Comment by vitaly-t** [comment]
> it would have been better for example to use the `$(columns:name)` and provide `values: {firstName, lastName, ...}`

Filter `:name` already supports objects and arrays to automatically inject a list of names. If you want to customize it somehow, to split strings, like based on `.` in the name, you can easily do so yourself, with the help of [Custom Type Formatting](https://github.com/vitaly-t/pg-promise#custom-type-formatting).

If the latter confuses you, I can help you, just give me a usable example of the formatting template as the parameter object/array with values, and I will show an example for that.
