### ISSUE TITLE
advertise ts-sql-plugin

### ISSUE THREAD

**Issue by xialvjun** [vitaly-t/pg-promise#609]
[ts-sql-plugin](https://github.com/xialvjun/ts-sql-plugin)
TypeScript Language Service Plugin for SQL with a tagged template strings SQL builder.

If you feel uncomfortable, close this issue and I'm sorry.

![readme_0](https://github.com/xialvjun/ts-sql-plugin/raw/master/readme_0.gif)

**Comment by vitaly-t** [comment]
This is for issues with the library, not for advertising other libraries.

**Comment by vitaly-t** [comment]
This is for issues with the library, not for advertising other libraries.
