### ISSUE TITLE
Compatibility with node-pg-types

### ISSUE THREAD

**Issue by jcristovao** [vitaly-t/pg-promise#61]
Hi,
This is just a question, but I was wondering if we can use [node-pg-types](https://github.com/brianc/node-pg-types) with pg-promise, since they seem to address different needs: pg-promise has its own code to format queries, but not their result, right?

But then I don't know exactly how to 'plug it on', since with pg-promise with don't have access to the inner pg object. Do I use connect option?

Thanks for your help!

**Comment by vitaly-t** [comment]
We do have direct access to the `pg` instance, from the library's root, it has property `pg` which represents the instance.

`pgp.pg.types` - your pg's type interface;

**Comment by vitaly-t** [comment]
@jcristovao please close the issue, if your questions has been answered ;)

**Comment by jcristovao** [comment]
Yes it is, tks! :)

**Comment by vitaly-t** [comment]
Included this question into [FAQ](https://github.com/vitaly-t/pg-promise/wiki/FAQ)
