### ISSUE TITLE
Please update FAQ with regards to max pool size

### ISSUE THREAD

**Issue by fancydev18** [vitaly-t/pg-promise#610]
Seems the FAQ 
https://github.com/vitaly-t/pg-promise/wiki/FAQ
hasn't been updated after upgrading to node-postgres 7, which uses pgpool.

Looks like this is the proper way to set pool size now?
https://github.com/vitaly-t/pg-promise/wiki/Connection-Syntax

Thanks!

**Comment by vitaly-t** [comment]
What are you talking about? The FAQ section never mentions anything about the connections.

**Comment by fancydev18** [comment]
This section
```
or to change the default size of the connection pool:
```

Is that the best way to set the pool max now? This seems to work fine:
```
const db = pgp('postgres://john:pass123@localhost:5432/products?max=8');
```

**Comment by vitaly-t** [comment]
Documentation updated.
