### ISSUE TITLE
Update Connection Syntax docs 

### ISSUE THREAD

**Issue by fancydev18** [vitaly-t/pg-promise#611]
https://github.com/vitaly-t/pg-promise/wiki/Connection-Syntax

> Connection strings support only a subset of connection parameters as show below

### Expected behavior

Connection strings supports all connection parameters. Here's the update:
https://github.com/iceddev/pg-connection-string/commit/9ab62ff9f3050bc8d1096cd6f1258cd288be75fd

**Comment by vitaly-t** [comment]
The example may need to be updated for additional parameters, but it does not support all parameters. In fact, there are many parameters that are not supported.

**Comment by vitaly-t** [comment]
Documentation has been updated.
