### ISSUE TITLE
Simpler Query parameters suggesion

### ISSUE THREAD

**Issue by fancydev18** [vitaly-t/pg-promise#612]
Hello!

Before switching to pg-promise, I was using query paramters like this
```
SELECT * FROM users WHERE created < ? AND active = ?
```
with a wrapper which changed these just before running the query:
```
prepareSql(sql) {
        var p = 0
        return sql.replace(/\?/g, function() {
            return '$' + ++p
        })
```

Would it be possible to support this natively with pg-promise?

Besides simpler queries in general, an use case which really could benefit would be dynamically-constructed sql, eg.
```
  var sql_base = 'UPDATE items SET '
  var sql_set = []
  var sql_params = []

  if (typeof req.body.title == 'string') {
    sql_set.push('title = ?')
    sql_params.push(req.body.title)
  }
  if (typeof req.body.content == "string") {
        sql_set.push("content = ?")
        sql_params.push(req.body.content)
    }
  if (typeof req.body.notes == 'string') {
    sql_set.push('notes = ?')
    sql_params.push(req.body.notes)
  }
```

This simplifies code as one doesn't need to use an extra var, incremented in each block, which would be required for "$1", "$2" ....

I know that another more clear option would be Named Parameters, but that's also more code to handle. Still, it's better than "$1", "$2"...

Would you consider supporting "?" as a parameter?

Thanks!

**Comment by vitaly-t** [comment]
> Would it be possible to support this natively with pg-promise?

PostgreSQL does not support `?` syntax, so there is nothing native about it for PostgreSQL.

There is definitely a NO.
