### ISSUE TITLE
How to handle 1000 new connections every second in pg-promise?

### ISSUE THREAD

**Issue by sachinavinaw** [vitaly-t/pg-promise#613]
### Expected behavior
In my application, there are 250 applications. Each application is calling Node server to execute 4 different type of query in postgreSql. 

So in short, 1000 commands are getting executed per second. The type 'findAll' command retrieves 25k records. How to handle this condition? Most of the 'findAll' commands showing 'ERRCONRST' which I have tested using Artillery CLI. Please help me solving this use case.
### Environment

* Version of pg-promise: 8.6.5
* OS type (Linux/Windows/Mac): Windows 10
* Version of Node.js: 10.15.3

**Comment by vitaly-t** [comment]
You should really ask this on StackOverflow.
