### ISSUE TITLE
Include $config on tx instance

### ISSUE THREAD

**Issue by porsager** [vitaly-t/pg-promise#615]
Hi Vitaly.

First off. Thanks a lot for this brilliant library! It's such a pleasure to work with! 

I've got functions which take a tx instance to work with simply to ensure everything they do happens in the same transaction. 

It's just a minor inconvenience, but if I want to use insert helpers etc, I need to pass `pgp` too. I think it would fell natural to have the $config property on tx objects as well.

Would you consider adding that? (I can also do a PR to add it if you like)?

**Comment by vitaly-t** [comment]
This historically done so, the root database object can be differentiated by the presence of extra properties, like `$config`. That's why I never planned to add it into the connected/task/tx object.

I think that exporting `pgp` isn't much of inconvenience to export.

**Comment by porsager** [comment]
Ok :) Thanks for the fast response.
