### ISSUE TITLE
Support for camel cased column names in ON CONFLICT clause

### ISSUE THREAD

**Issue by bstanley0811** [vitaly-t/pg-promise#616]
### Expected behavior
Declaring a camel cased column name in an ON CONFLICT clause should work without having to quote and escape it.

### Actual behavior
I'm having to quote and escape camel cased columns in the ON CONFLICT which is not intuitive, specifically in a bulk insert.

### An Example
```javascript
// both tables here have composite primary keys that contain camel-cased names (teamId, taskId)

// generate bulk inserts
const projectsQuery = this._helpers.insert(projects, this._projectsColumnSet) + " ON CONFLICT (id, teamId) DO NOTHING";
const tasksQuery = this._helpers.insert(tasks, this._tasksColumnSet) + " ON CONFLICT (id, taskId) DO NOTHING";

this._db.tx(t => {
    return t.batch([
      t.none(projectsQuery),
      t.none(tasksQuery),
    ])
  })
  .then((data: queryResult) => {
    console.log('much success!', data)
  })
  .catch((err: Error) => {
    console.log(err)
  })
```

When running the above, I'll get an error message like:
```
BatchError: column "teamid" does not exist
```

Note the error message is stating the ON CONFLICT is suggesting an all _lowercase_ column name. The only way I've found to make this work is to quote and escape the values in the ON CONFLICT clause, like such.  But again, this just seems unintuitive to me since it's already quoted.
```javascript
const projectsQuery = this._helpers.insert(projects, this._projectsColumnSet) + " ON CONFLICT (id, \"teamId\") DO NOTHING";
const tasksQuery = this._helpers.insert(tasks, this._tasksColumnSet) + " ON CONFLICT (id, \"taskId\") DO NOTHING";
```

Apologies if this is just a preference thing, but I also could not find anything documented about this.

### Environment

* Version of pg-promise: 8.7.2
* OS type (Linux/Windows/Mac):  Mac (Mojave 10.14.5)
* Version of Node.js: 10.15.3

**Comment by vitaly-t** [comment]
You statically provide the `ON COFLICT` clause, and so you escape it. What did you expect?

If you want, you can format it with the library:

```js
pgp.as.format(' ON CONFLICT ($1:name) DO NOTHING', [['id', 'teamId']])
;
```

but that's it.
