### ISSUE TITLE
Connection dies when using SOCKS proxy

### ISSUE THREAD

**Issue by foundryspatial-duncan** [vitaly-t/pg-promise#620]
I'm trying to use a SOCKS proxy ("Fixie Socks" Heroku addon) to connect to a DB server. Referring to the [Fixie Socks documentation (which uses node-postgres)](https://devcenter.heroku.com/articles/fixie-socks#using-with-node-js), I'm using the (undocumented?) `stream` element in the connection options object.

### Expected behavior

Known, valid queries should return appropriate responses. Even after repeated queries.

### Actual behavior

Sometimes, the first query works, but the second query always fails with an error:

> expected password response, got message type 0

The first query sometimes fails, too, but it's hard to reproduce.

### Steps to reproduce
A minimal reproduction script looks like this:

```javascript
const pgp = require('pg-promise')();
const SocksConnection = require('socksjs');

    const pgServer = {
        host: process.env.PGHOST,
        port: process.env.PGPORT,
    };
    const proxyConnection = new SocksConnection(pgServer, {
        user: process.env.PROXY_USER,
        pass: process.env.PROXY_PASS,
        host: process.env.PROXY_HOST,
        port: process.env.PROXY_PORT,
    });
    const dbConnectionOptions = {
        stream: proxyConnection, // note "stream" instead of host
        database: process.env.PGDATABASE,
        user: process.env.PGUSER,
        password: process.env.PGPASSWORD,
    };
    const dbConnection = pgp(dbConnectionOptions);

// run some queries that are known to work with regular connections
db.one(`SELECT * FROM mytable limit 1`)
    .then((result) => {
        console.log('result!', result);
    })
    .catch((e) => {
        console.error('some error', e);
    });

db.one(`SELECT * FROM othertable limit 1`)
    .then((result) => {
        console.log('result!', result);
    })
    .catch((e) => {
        console.error('some error', e);
    });

```

### Environment

* Version of pg-promise: 8.7.2
* OS type (Linux/Windows/Mac): Ubuntu 18.04
* Version of Node.js: v10.15.1

**Comment by vitaly-t** [comment]
That error - `expected password response, got message type 0` does not come from this library. Most likely it comes from that `socksjs` library. There is nothing to track here, unless you tell me that it works with the lower-level [node-postgres], but not with this library.

[node-postgres]:https://github.com/brianc/node-postgres

**Comment by foundryspatial-duncan** [comment]
Using the syntax in the Fixie Socks documentation above, it does work, but it looks like they're using a "connect once per query" pattern...

I tried it with the node-postgres `pg.Pool` style connection and it also works as expected over here. I made a quick test script and ran 4 queries from the same pg.Pool "client" connection.

Are there any caveats I should know about when trying to use pg-promise through a proxy? I've never tried it before now.

**Comment by vitaly-t** [comment]
`Connect once per query` is a bad idea, as it does not scale at all. You can do the same with this library, by using method [connect]. But I cannot advise it in general.

[connect]:http://vitaly-t.github.io/pg-promise/Database.html#connect

**Comment by foundryspatial-duncan** [comment]
To clarify, I mean the sample code in the proxy documentation uses `Client`, and that works, but I also made a test script that uses `Pool` and that worked as well.

**Comment by vitaly-t** [comment]
@foundryspatial-duncan 

I tried to run this test, but getting error right on this line:

```js
const proxyConnection = new SocksConnection(pgServer, {
        user: process.env.PROXY_USER,
        pass: process.env.PROXY_PASS,
        host: process.env.PROXY_HOST,
        port: process.env.PROXY_PORT,
    });
```
I passed in the same details as for the postgresql database connection. Or is it not correct?

**Comment by foundryspatial-duncan** [comment]
It needs a SOCKS proxy server to connect to. In my case, I'm using the free one provided by the "Fixie Socks" addon on Heroku, but my experience with proxies is very limited. 

The ultimate goal here was to be able to connect my Heroku app to my Postgres database, but Heroku apps don't have a fixed IP address so that wouldn't work with host-based authentication (`pg_hba.conf`). The proxy would have provided a single IP (actually just 2) to connect from. I wasn't able to get the proxy stuff working, so in the mean time I've changed my database configuration, but it would be nice to get this going!

**Comment by vitaly-t** [comment]
Guys, I do not really have time resources to investigate third-party proxy libraries for this issue. and i do not know much about them either.

If it is important, and you can reproduce the issue, then please investigate what is happening underneath, so we can make progress on this issue.

If there is no further effort comes from anybody, I will have to close it as a third-party issue.

**Comment by foundryspatial-duncan** [comment]
I understand. Now that it's documented, let's close it and see if anybody mentions it in the future.

**Comment by Ding-Fan** [comment]
I ran into a similar error `expected password response, got message type 0` . I figured that it might because the connection wasn't closed yet. ([like this](https://stackoverflow.com/a/12324461)) I remove my `Connect once per query` pattern and change it to `connect - do queries - end` pattern. The error disappear! 🎉

**Comment by vitaly-t** [comment]
@Ding-Fan That doesn't sound right. Did you opt for direct connection? (`connect({direct: true}`) Such solution cannot scale well.

**Comment by Ding-Fan** [comment]
> @Ding-Fan That doesn't sound right. Did you opt for direct connection? (`connect({direct: true}`) Such solution cannot scale well, and manual connection management can be treacherous.

I didn't use pg-promise 😅 I sad similar because the error message looks exactly the same. I was using [deno-postgres](https://github.com/denodrivers/postgres) which might be responsible for the error.
