### ISSUE TITLE
wrong type for IDefaults.max

### ISSUE THREAD

**Issue by tmtron** [vitaly-t/pg-promise#622]
# Expected behavior

`IDefault.max` should be of type number, so that we can assign an arbitrary max pool-size.
I guess the default for this member should be 10 (defined elsewhere).

### Actual behavior

currently the type of `IDefault.max` is `10`: [code-ref](https://github.com/vitaly-t/pg-promise/blob/63895e8b21db876e521fb04061e48193e20b2506/typescript/pg-subset.d.ts#L143)
```ts
 interface IDefaults {
        // Connection pool options - see https://github.com/brianc/node-pg-pool
        // number of connections to use in connection pool
        // 0 will disable connection pooling
        max: 10,
```
and thus typescript (3.4.5) will show an error when we want to assign any other number

### Steps to reproduce
try to compile the following code with typescript 3.4.5:
```ts
    const customMaxPoolSize: number = 5;
    this.pgp.pg.defaults.max = customMaxPoolSize;
```
it will fail with this error: `TS2322: type 'number' is not assignable to type '10'`

### Workaround
use an explicit type-cast:
```ts
(this.pgp.pg.defaults.max as number) = dbPoolSize;
```
### Environment

* Version of pg-promise: 8.7.2
* OS type (Linux/Windows/Mac): Window 10 64-bit
* Version of Node.js: 12.6.0

**Comment by vitaly-t** [comment]
Fixed. Thanks for finding.
