### ISSUE TITLE
Select return string for array

### ISSUE THREAD

**Issue by dohoangn** [vitaly-t/pg-promise#623]
When query 
select data->>'tags' as tags from tag
### Expected behavior
pgAdmin or any db explorer return 
tags as arrays of string
like this
["Baby", "Beer"]
### Actual behavior
pgpromise return
 "[
        "Baby",
        "Beer"
    ]"
it wraps array in string
### Steps to reproduce
create Table 
CREATE TABLE tag (
  id BIGSERIAL PRIMARY KEY,
  data jsonb
);

INSERT INTO tag(data) VALUES ('{
    "tags": [
        "Baby",
        "Beer"
    ]
}')

select data->>'tags' as tags from tag

### Environment

* Version of pg-promise: any
* OS type (Linux/Windows/Mac): any
* Version of Node.js: any

**Comment by boromisp** [comment]
The `json[b] ->> text` operator returns the value as text. pgAdmin might not display surrounding quotes for text values, but what you see is in fact text and not an array. You will have better luck using the `->` operator instead.

Relevant postgres documentation: [Table 9.43. json and jsonb Operators](https://www.postgresql.org/docs/current/functions-json.html#FUNCTIONS-JSON-OP-TABLE).

**Comment by dohoangn** [comment]
Yes, that's correct.
Working fine with -> operator
Many thanks! Peter
