### ISSUE TITLE
csv and list filter not working for array of string

### ISSUE THREAD

**Issue by Ktchan825** [vitaly-t/pg-promise#624]
### Expected behavior
`pgp.as.format('SELECT * FROM TABLE WHERE id IN (${a:csv})', {a:[1, 'text']})`
should return 
`'SELECT * FROM TABLE WHERE id IN (1,'text')'`

### Actual behavior
`pgp.as.format('SELECT * FROM TABLE WHERE id IN (${a:csv})', {a:[1, 'text']})`
returns
`'SELECT * FROM TABLE WHERE id IN (1,\'text\')'`

### Steps to reproduce
`pgp.as.format('SELECT * FROM TABLE WHERE id IN (${a:csv})', {a:[1, 'text']})`

### Environment
MAC

I guess the escape character is for the security issue, but I can create a valid SQL with that

**Comment by vitaly-t** [comment]
The output is perfectly correct. Are you displaying it somewhere that replaces ' with `\'`. That seems to be the case. The function works correctly.
