### ISSUE TITLE
Using pg-promise to return value

### ISSUE THREAD

**Issue by aHumanBeing** [vitaly-t/pg-promise#63]
Hi,

Would you please help me understand why 'location' is always returned undefined? Debug shows the value but I'm trying to figure out where exactly my problem is.  Thanks.

```
function findById(_id){
    winston.log('debug', 'searching for location with id: ' + _id);
    var sco; // shared connection object;
    var location;
    db.connect()
        .then(function (obj) {
            sco = obj; // save the connection object;
            // find the location
            return sco.one("select * from location where id = $1 ",
                [_id]
            );
        }).then(function (obj) {
            location = obj; // save the location object;
            winston.log('debug', 'found location: ' + location.locationname);
        })
        .catch(function (err) {
        winston.log('error', err);
    })
    .finally(function () {
        if (sco) {
            sco.done();
        }
            return location;
    });
```

**Comment by vitaly-t** [comment]
* Are you sure that you have the right record with the `id` that you specified?
* Are you sure that `_id` you are passing is of the same type as the one used in the database? Check what's being executed.

And why are you using such a complex approach to get your records? The following implementation would do just the same:

```javascript
function findById(_id) {
    return db.one("select * from location where id = $1", _id);
}
```

**Comment by aHumanBeing** [comment]
I'm sure for the first question and will double check the 2nd.  In using the simple approach, I don't have the location object data but something else:
2015-11-09T15:43:19.442Z - debug:  _41=0, _86=null, _17=[]

This result appears no matter what id I use.

**Comment by vitaly-t** [comment]
You need to do some basic diagnostics on your side, as I don't have your database anyway.

**Comment by vitaly-t** [comment]
@aHumanBeing is it sorted?

**Comment by aHumanBeing** [comment]
My apologies for the late response.  Yes, I was able to get over this hurdle but not as I wished.   No need to reopen. This code works:
```
var client = new pg.Client(conString);
    client.connect(function (err) {
        if (err) {

            next(new Error('could not connect to database'));
        }
        var _id = req.params.id;
        client.query("select * from table where id = $1", [_id], function (err, result) {
            if (err) {

                next(new Error('error running query'));
            }
            if (result === undefined || result.rows[0] === undefined) {
                winston.log('error', 'Unknown provider with id: ' + _id);
                client.end();
                res.redirect('/aroute');
            }
            req.provider = result.rows[0];
            client.end();

            res.render('routeView', {
                title: 'Route View'
            });
        });
    })
```

**Comment by vitaly-t** [comment]
This is not a good approach, it has too many holes in it. If you were to single out an issue, I would be able to explain ho to do it properly with pg-promise. Going back to the basic pg is only gonna cost you more time lost eventually. pg-promise can do everything pg does, and much more, and a lot easier, but not the other way round.

**Comment by aHumanBeing** [comment]
I see.  Well, I'll try to take some time over the next few weeks and get back to you.  I'm willing to understand better and appreciate the help thus far!
