### ISSUE TITLE
Drop ES6 Generators support

### ISSUE THREAD

**Issue by vitaly-t** [vitaly-t/pg-promise#633]
Because of #628, the major feature deletion in v 9.0 is ES6 Generators, because they should should no longer be used, in favor of the newer `async` / `await` syntax.

**Comment by vitaly-t** [comment]
This has been implemented in `v9` branch, in a safe way, i.e. if you are passing an ES6 generators into a task or transaction, it will reject with the following error - `ES6 generator functions are no longer supported!`.

**Comment by botic** [comment]
I stumbled over the `CHANGELOG` when looking for breaking changes. Should such breaking changes be added to it, even if you explicitly maintain it in a minimal form? I had some doubts before updating to 9.0 without knowing the big breaking changes.

**Comment by vitaly-t** [comment]
Yes, sorry about that, I've left that `CHANGELOG` in the past, focusing on detailed Release Notes, which also includes the list of all changes, to navigate you through.

**Comment by botic** [comment]
Oh, thanks for the hint … I was only looking for the changelog, my bad!
