### ISSUE TITLE
Promise library must be specified

### ISSUE THREAD

**Issue by Rabinzon** [vitaly-t/pg-promise#64]

**Comment by vitaly-t** [comment]
What does this mean? An issue without a description at all...

**Comment by Rabinzon** [comment]
I don't know how i can delete this  issue.

**Comment by vitaly-t** [comment]
You mean, delete your post?

**Comment by Rabinzon** [comment]
Yes:)

**Comment by vitaly-t** [comment]
You can't delete posts here :) Only replies can be deleted. I wouldn't worry about it though.

I take it the issue you were having has been resolved - correct?

**Comment by Rabinzon** [comment]
Yes. 
I had this error "Promise library must be specified". It's appeared with version 2.5. and I didnt know what to do, because it was not in 2.4.
I added, bluebird library. Now all works.

I hope you understand me:) Thank

**Comment by vitaly-t** [comment]
If you are referring to the difference between 2.2.4 and 2.2.5, then there wasn't any.

And the error you referred to related to the fact that you used the library in Node JS prior to 0.12, while not specifying any promise library, which starting with version 2.0 wouldn't work, throwing that error, as explained in [2.0 Migration](https://github.com/vitaly-t/pg-promise/wiki/2.0-Migration) tutorial.

And the code I saw in an email notification looked wrong also, I could have never worked before.

This line:
```javascript
var pgp = require('pg-promise');
```
is supposed to be:
```javascript
var pgp = require('pg-promise')(/*options*/);
no matter which version of the library you are using.

```
