### ISSUE TITLE
Inconsistency between undefined and null when using :list or :csv

### ISSUE THREAD

**Issue by yeedle** [vitaly-t/pg-promise#640]
### Expected behavior
```js
pgp.as.format('select ($1:list)', [[1, 2, 3]])
//=> 'select (1, 2, 3)' 

pgp.as.format('select ($1:list)', [null])
//=> 'select (null)'

pgp.as.format('select ($1:list)', [undefined])
//=> 'select (null)'

// not sure about this last one
pgp.as.format('select ($1:list)', [[]])
//=> 'select (null)'
```

If `null` and `undefined` are both formatted as `null`, adding `:list` or `:csv` shouldn't change that.

### Actual behavior
```js
pgp.as.format('select ($1:list)', [[1, 2, 3]])
//=> 'select (1, 2, 3)' 

pgp.as.format('select ($1:list)', [null])
//=> 'select (null)'

pgp.as.format('select ($1:list)', [undefined])
//=> 'select ()'

pgp.as.format('select ($1:list)', [[]])
//=> 'select ()'
```

### Environment

* Version of pg-promise: 8.5.3
* OS type (Linux/Windows/Mac): Linux
* Version of Node.js: 10.0.0

**Comment by vitaly-t** [comment]
It is consistent with how the library formats all single values, as per documentation:
> property values `null` and `undefined` are both formatted as `null`.

Compare the following:

```js
const s1 = pgp.as.format('select ($1)');
const s2 = pgp.as.format('select ($1)', [undefined]);
```

The first case won't even attempt formatting, because there are no variables specified. The second one will insert `null`.

**Comment by yeedle** [comment]
What is the difference between the following two
```js
pgp.as.format('select ($1)', [undefined]); 
//=> select (null)

pgp.as.format('select ($1:list)', [undefined]); 
//=> select ()
```
Shouldn't they both output `select (null)`?

**Comment by yeedle** [comment]
Would it be inconsistent for `undefined` and an empty array to be formatted as `null` instead?

**Comment by vitaly-t** [comment]
The difference is that in the first case `undefined` is a single value, converted into `null`, while the second one is a missing array, which tells the formatting - do nothing, the same as trying to do `pgp.as.format('select $1', undefined)` - this won't even run the formatter.

For `select (null)` with the undefined via array, you would place it inside the array, i.e:

```js
pgp.as.format('select ($1:list)', [[undefined]]); //=> select (null)
```

**Comment by yeedle** [comment]
Ok, that actually makes sense. My issue was with passing in possibly undefined object params, but I can always use `[].concat(obj.possiblyUndefinedArrayParam)` to make sure I get the desired `[undefined]` which will be properly formatted as `null`.

**Comment by vitaly-t** [comment]
Yes, so when dealing with `:list` or `:csv` filters, it is best not to parameterize them with single values, to avoid a confusion, always give them an array, even if it is `[]`, `[null]` or `[undefined]`.

**Comment by yeedle** [comment]
Empty array will still cause unexpected problems.

**Comment by vitaly-t** [comment]
> Empty array will still cause unexpected problems.

Not if it is inside an object.

**Comment by yeedle** [comment]
I was referring to a case like this:

```js
pgp.as.format('select (${values:list})', {values: []})
//=> select ()
```
