### ISSUE TITLE
connection refused when running on Docker

### ISSUE THREAD

**Issue by pabloegpf1** [vitaly-t/pg-promise#641]
### Expected behavior
pg-promise connects succesfully

### Actual behavior
ERROR: connect ECONNREFUSED 172.18.0.2:5433

### Steps to reproduce
(I use sequelize for migrations and pg-promise for querying)
When I run my node project locally using nodemon and connecting to a local postgres db everything works like a charm. 
However if I run it via Docker, sequelize connects succesfully to the postgres container but pg-promise returns connection refused. (note that I'm using the same connection parameters for both modules)

This is how I set up my connection: 

```
require("dotenv").config();

const pgp = require("pg-promise")({
    error: function (error, e) {
        if (e.cn) {
            console.log("CONNECTION:", e.cn);
        }
    }
});

const connection = pgp({
    "host": process.env.DB_HOST,
    "port": portNumber = process.env.DB_PORT,
    "database": process.env.DB_DATABASE,
    "user": process.env.DB_USER,
    "password": process.env.DB_PW
  });
```

### Environment

* Version of pg-promise: 8.7.2
* OS type (Linux/Windows/Mac): Mac/Linux(Docker)
* Version of Node.js: 12.3.1

**Comment by vitaly-t** [comment]
Maybe your default port is wrong, or something similar, but it is not an issue with pg-promise.

**Comment by pabloegpf1** [comment]
You're right. It is caused by docker-compose and how it passes env variables.

For people in the same situation, in macos you need to pass "host.docker.internal" instead of the name of the docker image of your database.

**Comment by vitaly-t** [comment]
@pabloegpf1 Thanks for returning with the solution.

**Comment by FER-Marijan-Tadijal** [comment]
Related issue, I had a similar problem. To fix it, I had to change my app.js from:
const db = pgp('postgres://postgres:password@localhost:5432/ORbaza')
to
const db = pgp('postgres://postgres:password@host.docker.internal:5432/ORbaza')
