### ISSUE TITLE
Releasing dropped connections

### ISSUE THREAD

**Issue by vitaly-t** [vitaly-t/pg-promise#642]
Following up on [this issue](https://github.com/brianc/node-postgres/issues/1942), it may be the case that we should stop releasing dropped connections back to the pool.

This requires further investigation.

**Comment by vitaly-t** [comment]
[As per the comment I added there](https://github.com/brianc/node-postgres/issues/1942#issuecomment-520886133), we need to identify how the client really should detect dropped connections.

**Comment by vitaly-t** [comment]
[The issue] has received some useful follow up, so I have created branch [connections](https://github.com/vitaly-t/pg-promise/tree/connections), to start working on this.

**Comment by vitaly-t** [comment]
Released within [9.1.0-Beta.0](https://github.com/vitaly-t/pg-promise/releases/tag/9.1.0-Beta.0).

@johanneswuerbach Please give it a go.

**Comment by vitaly-t** [comment]
Help is needed to review the change and to field-test the heck out of it.

**Comment by vitaly-t** [comment]
@jmacmahon, @johanneswuerbach guys, it's been 5 days since I gave you the update you wanted. Any chance you can test [9.1.0-Beta.0](https://github.com/vitaly-t/pg-promise/releases/tag/9.1.0-Beta.0), and provide feedback?

**Comment by johanneswuerbach** [comment]
@vitaly-t we still haven't upgrade to v9 so that takes more time then anticipated. I've probably a result for you tomorrow (CET).

**Comment by jmacmahon** [comment]
I'll test it on our dev environment tomorrow (BST). Thanks for the work!

**Comment by johanneswuerbach** [comment]
Our tests pass, so this change seems good to go from our perspective 🚢 👍

**Comment by vitaly-t** [comment]
@johanneswuerbach Can you, please, tell a little how you tested, and what difference manifested itself?

**Comment by johanneswuerbach** [comment]
We have a fairly extensive test suite around testing connection failures between transaction, in the middle of transactions, when the instance just goes away, etc. as we use pgbouncer running inside kubernetes internally and have a lot of connection churn.

In our tests I was able to remove our monkey patch of https://github.com/brianc/node-pg-pool/pull/119 as in at least all those cases broken clients are not being re-added to the pool.

We would still keep that patch as an additional safety net though.

**Comment by vitaly-t** [comment]
Thanks @johanneswuerbach! I think even with that check removed it should be good, because we now check for any broken connection after every query that failed. In fact, I'm not sure if that patch doesn't counteract what I have done. Your test should be done without that patch, or else the test has no value to us.

**Comment by jmacmahon** [comment]
I have been unable to test the DB disconnect behaviour as there seems to be a regression introduced regarding the type parsing.

We have
```

**Comment by jmacmahon** [comment]
I have been unable to test the DB disconnect behaviour as there seems to be a regression introduced regarding the type parsing.

We have configured:
```
  pgTypes.setTypeParser(pgDataTypes.int8, stringToNumber)
  pgTypes.setTypeParser(pgDataTypes.numeric, stringToNumber)
  pgTypes.setTypeParser(pgDataTypes.date, passThroughAsString)
```

But when querying a table with an integer row, these values are coming back as strings. This is causing our acceptance tests to fail and therefore I am unable to deploy the service consuming the beta library to our development environment.

**Comment by vitaly-t** [comment]
@jmacmahon Check out [my answer](https://stackoverflow.com/questions/39168501/pg-promise-returns-integers-as-strings) (last update in it).

**Comment by vitaly-t** [comment]
I have released another beta - [9.1.0-Beta.1](https://github.com/vitaly-t/pg-promise/releases/tag/9.1.0-Beta.1), now merged into the `master` with all the latest TypeScript updates.

@jmacmahon Please try again, now using this update, see if you have any issues, and if so, use that StackOverflow reference I gave earlier. Cheers!

**Comment by jmacmahon** [comment]
Apologies for not including our `pgTypes` dictionary. It's a hangover from the days of v7 which (I believe) didn't include the `TypeID` enum. You are correct that `pgDataTypes.int8` is set to 20.

In any case, the new 9.1.0-Beta.1 still has this regression.

**Comment by vitaly-t** [comment]
@jmacmahon Are you going to fix this on your end? Because it seems nothing can be done on this end anymore.

**Comment by vitaly-t** [comment]
Ok, this is a bit too slow as a follow up. I am releasing [9.1.0](https://github.com/vitaly-t/pg-promise/releases/tag/9.1.0) now, as it seems to be working as expected. If any issues arise related to the change, they will be addressed in their own turn.

**Comment by vitaly-t** [comment]
#675 Is effectively an extension to this.
