### ISSUE TITLE
pgp undefined in utility functions when using repo pattern

### ISSUE THREAD

**Issue by kissmygritts** [vitaly-t/pg-promise#647]
### Expected behavior
pgp to be defined in utility functions that I am attempting to use in a repo, as described in the repo example you have in the pg-promise-demo.

### Actual behavior
pgp is undefined. I think this has to do with the order modules are initialized when starting a server.

### Steps to reproduce
standard set up as described in pg-promise-demo

create a utils/index.js file
```js
// util index.js
const { pgp } = require('./../db')

const pagination = limit => {
// limit is a single number
  return pgp.as.format('LIMIT $1', limit)
}
```

Then alter the the all method in `db/repo/products.js`
```js
const { pagination } = require('./../../util')
... other code

async all(limit) {
  return this.db.any('SELECT * FROM products $1:raw', pagination(limit))
}
```

When attempting to run this method the follow error is returned:

"TypeError: Cannot read property 'as' of undefined"

I can get around this by require pgp as a parameter for the pagination function, as this is then passed in from the Products class. Alternatively I can require the pg-promise library as [mentioned here](https://github.com/vitaly-t/pg-promise/wiki/FAQ#can-i-use-only-the-query-formatting-from-pg-promise-and-nothing-else). 

I suppose I'm mostly just curious about this behavior. I understand why it is happening (because the repos are being initialized before db and pgp are initialized, and therefore before the utility functions are). What are your thoughts? Should I require the pg-promise library in my utility functions? Or provide pgp as a parameter to my utility functions?

I apologize if this isn't truly a pg-promise issue. Any help is much appreciated.

### Environment

* Version of pg-promise: 8.7.4
* OS type (Linux/Windows/Mac): Mac
* Version of Node.js: 10.16.3

**Comment by vitaly-t** [comment]
The steps you provided are not enough to reproduce the issue.

Clone [pg-promise-demo], and add the code necessary to see the issue. And then post the clone link here.

**Comment by vitaly-t** [comment]
You are creating a loop-reference:

* https://github.com/kissmygritts/pg-promise-demo/blob/master/JavaScript/db/index.js#L5
* https://github.com/kissmygritts/pg-promise-demo/blob/master/JavaScript/db/repos/users.js#L2
* https://github.com/kissmygritts/pg-promise-demo/blob/master/JavaScript/utils/index.js#L1

That's a coding mistake on your part, it is not an in issue with this library.

**Comment by kissmygritts** [comment]
Got it. Thank you.
