### ISSUE TITLE
Sharing Connection Across Middleware in Express

### ISSUE THREAD

**Issue by edcolyer** [vitaly-t/pg-promise#648]
Hi all,

I'm using pg-promise in an Express app. I'm wondering what the best way is to share, for example, a database task object across middleware. I have multiple layers of middleware that make database calls and would rather each request not using up multiple connections to the database.

Presently I have a piece of middleware which basically calls this:

```js
await db.task(t => {
  res.locals.db = t;
});
```

I then use `res.locals.db` in my controller functions at each of my endpoints. What I've found is it works for querying the connection once, but then throws the following error:

`Querying against a released or lost connection.`

Am I missing something very simple? Any help would be appreciated for the best way to do this!

Thanks!

**Comment by vitaly-t** [comment]
The task is there to make sure the connection is released just as the task callback completes. Therefore, you cannot share the connection context outside of that callback. Any attempt to use a task connection outside of the callback will result in executing queries against a released connection, hence the error.

**Comment by edcolyer** [comment]
Thank you @vitaly-t. This answers my question and makes sense.

:)
