### ISSUE TITLE
Promise Compatibility with Babel-Core/Register

### ISSUE THREAD

**Issue by JaxCavalera** [vitaly-t/pg-promise#65]
The documentation currently does not list Babel-Core/Register as being a compatible option for Promise/A+ Compliance and I'm fairly certain that it is based on the following.

When Babel-Core is required using : 
```javascript
require("babel-core/register");
```
As explained : https://babeljs.io/docs/setup/#babel_register

It states that using this require automatically includes polyfill.

Polyfill contains core.js : https://github.com/zloirock/core-js

Core.js includes polyfills for promises, which based on my understanding of the spec at the Promise/A+ website is compliant, as demonstrated in the examples provided in this link  : 
https://github.com/zloirock/core-js#ecmascript-6-promise

So my question would be, what code do I need to use so I can make pg-promise use the babel-core/register promise polyfill as shown for using bluebird?

https://github.com/vitaly-t/pg-promise#promiselib

I'm guessing we don't do the following : 
```javascript
var promise = require('babel-core/register');
var options = {
    promiseLib: promise
};
var pgp = require('pg-promise')(options);
```

If we are already transpiling each ES6 file through babel-core/register using the following code, do we still need to specify a second time to use the babel-core polyfill? :
```javascript
//  server.js  ENTRY file
require("babel-core/register");
require("./src/config.js");
//
//  config.js is an ES6 file used to load all other ES6 files in and would contain :
//  var pgp = require('pg-promise')(options);
//
//  plus the previously mentioned command for choosing babel's promise polyfill if needed
```

**Comment by vitaly-t** [comment]
If it is ES6 that you are using then ES6 promise should be sufficient. Otherwise, specify your promise library as shown in the example.

**Comment by vitaly-t** [comment]
@JaxCavalera Adding a link to a similar discussion: https://github.com/babel/babel-loader/issues/23#issuecomment-151498013

And closing the issue here, because I can't really help with Babel promise usage, as I'm not familiar with it.
