### ISSUE TITLE
QueryResultError defaulting to Error

### ISSUE THREAD

**Issue by sstaley-sparkpost** [vitaly-t/pg-promise#650]
### Expected behavior
I imagine one should be able to instantiate QueryResultError like you have done here: 
https://github.com/vitaly-t/pg-promise/issues/361#issuecomment-312278658

unless something has changed in the library in the meantime.  

I'm attempting to do the same with typescript to no avail.

### Actual behavior

However,  I'm getting the default Error constructor, which is looking for a string, which results in this error if you try to instantiate it in that way:
```
TypeError: Cannot read property 'message' of undefined
    at new QueryResultError (/path/to/node_modules/pg-promise/lib/errors/query-result-error.js:129:45)
    at Object.<anonymous> (path/to/index.js:4:9)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```
### Steps to reproduce
(using typescript)

file:
```
import * as PGP from 'pg-promise';

let x = new PGP.errors.QueryResultError();
```
then:
```
tsc file-name.ts
node file-name.js
```
### Environment

* Version of pg-promise:
9.1.4
* OS type (Linux/Windows/Mac):
Mac OSX 10.14.6
* Version of Node.js:
8.10
* Version of TypeScript
3.6.3

**Comment by vitaly-t** [comment]
That error is not meant to be created by the client, only internally by the library itself.

What is the reason you are trying to create one?

**Comment by vitaly-t** [comment]
Anyway, to create a synthetic error, you usually just peek at the constructor signature...

```ts
import * as pgp from 'pg-promise';

function createSyntheticQueryError(errCode: pgp.errors.queryResultErrorCode) {
    return new (pgp.errors.QueryResultError as any)(errCode, {rows: []});
}

const err = createSyntheticQueryError(pgp.errors.queryResultErrorCode.noData);

console.log(err);
```

Outputs:

```
QueryResultError {
    code: queryResultErrorCode.noData
    message: "No data returned from the query."
    received: 0
    query: undefined
}
```

**Comment by sstaley-sparkpost** [comment]
Thank you for the quick reply! Looks like I just wasn't getting the syntax right. I appreciate the help!

**Comment by sstaley-sparkpost** [comment]
And to answer your question, this is just for testing.
