### ISSUE TITLE
func mapping to SELECT * FROM func() instead of SELECT func()

### ISSUE THREAD

**Issue by realcarbonneau** [vitaly-t/pg-promise#651]
When I call a PostgreSQL function using pg-promise method func, the logging indicates that PostgreSQL receives a "SELECT * FROM func()" instead of "SELECT func()" as per the PostegreSQL docs https://www.postgresql.org/docs/11/sql-syntax-calling-funcs.html

This causes a problem when calling functions defined as FUNCTION ... RETURNS RECORD since "SELECT func()" works as expected, but "SELECT * FROM func()" gives error "ERROR:  a column definition list is required for functions returning "record""

Is there a specific reason pg-promise is not sending func() as "SELECT func()"?  I would like to use the PostgreSQL functions in pg-promise as designed.   If not possible, is there a workaround other than building my own call "SELECT func()"?

PostgreSQL version 11.5
pg-promise version 9.1.4
Node version v10.16.3
npm version 6.11.3

**Comment by realcarbonneau** [comment]
As a temporary workaround:
`const result = await db.any('SELECT func1($1, $2)', [1,2])`

Instead of the following, which currently seems broken in pg-promise for functions that returns a RECORD:
const result = await db.func(func1, [1,2])`

Start of example PostgreSQL function definition as reference:
`CREATE OR REPLACE FUNCTION func1(var1 int, var2 int) RETURNS RECORD ...`

**Comment by vitaly-t** [comment]
`SELECT * FROM func` is the most common way of using functions in PostgreSQL, that' why that method was added there. If in your case you specifically need `SELECT func()`, then use the query.

There is no issue in pg-promise, [it works as documented](https://vitaly-t.github.io/pg-promise/Database.html#func).

**Comment by realcarbonneau** [comment]
PostgreSQL documentation https://www.postgresql.org/docs/11/sql-syntax-calling-funcs.html and the broken use case I present both disagree with your statement.

**Comment by realcarbonneau** [comment]
Thank you for your quick response and your contribution and hard work with pg-promise.  :)

**Comment by vitaly-t** [comment]
I have updated [the docs](https://vitaly-t.github.io/pg-promise/Database.html#func), to clarify it for the future:

> Executes a database function as `SELECT * FROM funcName(values)`.

> This is to help with the most common scenario of using functions. If, however, you need to type-cast parameters, or use the `SELECT funcName` form, then you should use a regular query method.
