### ISSUE TITLE
While in transaction avoid closing connection for handled errors

### ISSUE THREAD

**Issue by avinersan** [vitaly-t/pg-promise#656]
Sorry for the formatting. I filled this on my phone.
### Expected behavior
While in transaction avoid closing connection for handled errors

### Actual behavior
After a handled error the connection is dropped (or not reusable) and any following queries fail.

### Steps to reproduce
```
db.tx(async t => {
try{
await t.query('insert into missing_table ...');
} catch (err) {
// Ignore
}
// next query would fail with error similar to connection closed
await t.query('select 1');
});
```

### Environment

* Version of pg-promise: 8.6.4
* OS type (Linux/Windows/Mac): any
* Version of Node.js: ^8.15.1

**Comment by vitaly-t** [comment]
You interpret this wrong - handling errors that way inside a transaction does not affect the state of the transaction or its connection. The state of every transaction is controlled solely by the server.

When in transaction, once you execute a query that results in an error, the transaction state is automatically switched into `failed-state` by the server.

You should ever try do `try->catch` inside a transaction that way, you should do `try->catch` on the entire transaction only, i.e.

```js
try {
    await db.tx(t => {
        // transaction logic
    })
} catch(e {
})
```

**Comment by avinersan** [comment]
Is there a possibility to control the transaction on the client side? My intention is to use some kind of transaction scope that wraps multiple repositories. In some cases we catch SQL errors and compensate in some way like inserts that might fail if data is already there and then take the existing row. I know that each case like this can be changed to avoid this behaviour but would not want to enforce this or change it

**Comment by vitaly-t** [comment]
> Is there a possibility to control the transaction on the client side

No, as I explained, transaction status is controlled by the server only.

> My intention is to use some kind of transaction scope that wraps multiple repositories

Multiple repositories work fine within a single transaction. And then there are nested transactions, aka save-points in PostgreSQL.

> In some cases we catch SQL errors and compensate in some way like inserts that might fail if data is already there

That's called `insert or update`, which PostgreSQL supports fine.

> I know that each case like this can be changed to avoid this behavior but would not want to enforce this or change it

I think you need a bit more practice with PostgreSQL. For the most part, it does things better than MS-SQL.

**Comment by avinersan** [comment]
I'm not used to not having control of transactions on the client side, but I guess that's how it is. 

Thank you for the nice and prompt answers

**Comment by vitaly-t** [comment]
I think there's some sort of misunderstanding in controlling transactions, because that part works the same with MS-SQL: It is the server that flags a transaction as failed, and stops accepting the further queries, not the client. It is only by wrapping the entire transaction into a single-query request that you can implement certain overrides, though I'm not sure you'd want this. And it works the same way in all SQL implementations.

**Comment by avinersan** [comment]
In the ms sql case, errors with high severity automatically rollback a transaction on the server side while lower severity errors can be handled on the client side with a standard try catch that wraps the query that produces the error. I can provide an example if needed.

**Comment by avinersan** [comment]
Here is also a proposal for implementing similar behaviour using implicit savevepoints in the pgjdbc driver which I do understand is not easy or nice.

**Comment by vitaly-t** [comment]
This library has always supported automatic SAVEPOINT rollbacks.

**Comment by avinersan** [comment]
If I would wrap each query inside a tx with a child tx (which would create a Savepoint) and then in a try catch to avoid rolling back the entire transaction work then?

**Comment by vitaly-t** [comment]
I don't think that wrapping each query into a transaction would generally be a good idea. But beside that, SAVEPOINTS within this library work exactly as they are supported by PostgreSQL - check the official logic documentation for SAVEPOINT-s ;)

**Comment by vitaly-t** [comment]
It was once explained [here](https://stackoverflow.com/questions/46229132/is-there-a-way-in-pg-promise-to-trigger-an-inner-transaction-that-wont-affect-t).

**Comment by avinersan** [comment]
Thanks for the tips. 

Now regarding the SAVEPOINT, the pgjdbc driver solution to allow control on the client side is to automatically do the following: 
- wrap each query (when a certain option is enabled) with a savepoint
- in case of error, rollback the savepoint and then raise the error on the client side
- if error is catched on the client side it would continue just fine with the next statements, if not, it would rollback the entire transaction.
They implemented this feature to allow migrations of java applications (that were using same approach as I did) from oracle, ms sql, mysql and others to postgresql. 

Here is a very good example of catching errors on the client side in Java that works on many database engines except postgresql: https://postgrespro.com/list/id/na9uij$9vn$1@ger.gmane.org

I do understand that this is something that introduces performance penalties and it's not natural coming from postgresql which is strict on this subject compared to many other database engines.
