### ISSUE TITLE
BigInt Support

### ISSUE THREAD

**Issue by vitaly-t** [vitaly-t/pg-promise#657]
Node.js v10.4.0 started official support of type [BigInt]. And any client of [pg-promise] can make the underlying driver automatically convert the corresponding types as they come from the server:

* JavaScript:

```js
pgp.pg.types.setTypeParser(20, BigInt);
```

* TypeScript:

```ts
pgp.pg.types.setTypeParser(TypeId.INT8, BigInt); // TypeId.INT8 = 20 = BIGINT | BIGSERIAL
```

Conversion in the other direction is however missing, as [pg-promise] does not support [BigInt] within its query-formatting engine.

This issue is to track adding such support, so you can parameterize queries with [BigInt] values directly.

Then in combination with adding the above converters, support for [BigInt] within the library will be considered complete.

[pg-promise]:https://github.com/vitaly-t/pg-promise
[BigInt]:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt

**Comment by vitaly-t** [comment]
The feature has been implemented and tested within branch `bigint`.

Note that when you want the driver to also support returning an array of [BigInt] natively, you need to provide a separate type converter, as shown below:

```
// 1016 = Type for arrays of BigInt values
const parseBigIntegerArray = pgp.pg.types.getTypeParser(1016);
pgp.pg.types.setTypeParser(1016, a => parseBigIntegerArray(a).map(BigInt));
```

[BigInt]:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt

**Comment by vitaly-t** [comment]
Support for `BigInt` has been released in [v9.3.0](https://github.com/vitaly-t/pg-promise/releases/tag/9.3.0).

**Comment by vitaly-t** [comment]
I am re-opening this issue, because after some more testing it would appear that something major fell through the cracks here: JSON serialization for `BigInt`.

I wasn't aware that JSON serialization for `BigInt` has been an old, painful and ongoing discussion in the JavaScript community. I have just discovered it, after finding out that you cannot use `JSON.stringify` for type `BigInt` or anything that contains the type...

**Comment by vitaly-t** [comment]
[This commit](https://github.com/vitaly-t/pg-promise/commit/7d0cce277baaeadde8666a604ccc9a4ca7897328) takes care of the above issue.

Now [JSON Filter] and all inner functions will work with type `BigInt` beautifully.

**Comment by vitaly-t** [comment]
Re-opening again, blimey!

[JSON Filter] serializes [BigInt] as a string, instead of number. Needs one fix for this.

[JSON Filter]:https://github.com/vitaly-t/pg-promise#json-filter
[BigInt]:https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt

**Comment by dmfay** [comment]
It's a corelib problem, and right now the choices do look like polyfill or nothing (comedy option: substitute uuid placeholders and regexp-replace the stringify output). The polyfill is dubiously acceptable unless it's opt-in like configuring promise libraries, and even then seems not worth the effort. I have to think that if I were in the situation of needing to store BigInts in a JSON field, I'd likely as not already have run into & worked around around the stringification issue.

**Comment by vitaly-t** [comment]
@dmfay Did you read [my answer](https://stackoverflow.com/questions/58249954/json-stringify-and-postgresql-bigint-compliance)? Because it sounds like you are repeating what I've just done :smile:

**Comment by dmfay** [comment]
I'd read the question and comments earlier but hadn't seen an answer! It still might be good to make that toggleable just in case -- counterexamples seem highly unlikely (storing newton measurements lowercase?) but not impossible.

**Comment by vitaly-t** [comment]
I have released [v9.3.2](https://github.com/vitaly-t/pg-promise/releases/tag/9.3.2) that contains the fix. So the feature now works fully.

@dmfay It may be possible to improve the implementation slightly, so if we do not have any `BigInt` in the source, then not run `replace` at all. I will think about it...

**Comment by vitaly-t** [comment]
@dmfay Maybe a better solution is simply to extra-obfuscate the format? i.e. the algorithm allows easy use of any format, so instead of `123n` we can use something like `${^^123^^}`, and thus reduce the chance of a conflict into nothing.

**Comment by vitaly-t** [comment]
Release [v9.3.3](https://github.com/vitaly-t/pg-promise/releases/tag/9.3.3) finalizes the feature, by adding many tests, and changing the inner replacement pattern to `123#bigint`.

@dmfay I hope you will concur that using `123#bigint` is weird enough not to cause any accidental replacement ;)

On this note, I am closing the issue, with the feature being complete 😌

**Comment by vitaly-t** [comment]
As I made a suggestion [here](https://stackoverflow.com/questions/58249954/json-stringify-and-postgresql-bigint-compliance) (see `UPDATE-2`), this can be made completely safe, like this:

```js
// Like JSON.stringify, but with safe support for BigInt (irreversible)
function toJson(data) {
    if (data !== undefined) {
        let intCount = 0, repCount = 0;
        const json = JSON.stringify(data, (_, v) => {
            if (typeof v === 'bigint') {
                intCount++;
                return `${v}#bigint`;
            }
            return v;
        });
        const res = json.replace(/"(-?\d+)#bigint"/g, (_, a) => {
            repCount++;
            return a;
        });
        if (repCount > intCount) {
            // You have a string somewhere that looks like "123#bigint";
            throw new Error(`BigInt serialization pattern conflict with a string value.`);
        }
        return res;
    }
}
```

**Comment by dmfay** [comment]
All my sufficiently large numbers are in honest-to-god columns, but good to know! ;)

**Comment by vitaly-t** [comment]
@dmfay They are thus far. This release kind of opens the floodgate, so people will start using `BigInt` directly inside class properties, because they now can. And they will expect it to work all the way through. So it is a good idea to start making provisions ;)

**Comment by vitaly-t** [comment]
[BigInt Manual](https://github.com/vitaly-t/pg-promise/wiki/BigInt) has been added in WiKi.

**Comment by vitaly-t** [comment]
[pg-monitor] has been updated to version `1.3.0` that can handle displaying `BigInt` in parameters. See [#23](https://github.com/vitaly-t/pg-monitor/issues/23).

[pg-monitor]:https://github.com/vitaly-t/pg-monitor
