### ISSUE TITLE
error: syntax error at or near ":"

### ISSUE THREAD

**Issue by demian85** [vitaly-t/pg-promise#659]
I'm trying to use the `csv` filter in this query:

```js
const customers = await db.manyOrNone(
      {
        name: 'customers-tags',
        text: `SELECT C.id, C."deviceId", array_agg(TC2."tagId") FILTER (WHERE TC2."tagId" IS NOT NULL) as "removedTags", C.phone, C."storeVisits", C."smsNotifications"
        FROM "Campaigns" Cm
          INNER JOIN "Customers" C
            ON C."accountId" = Cm."accountId"
          INNER JOIN "CampaignActions" CA
            ON Cm.id = CA."campaignId"
          INNER JOIN "Tags_Customers" TC
            ON TC."customerId" = C.id
            AND TC."deletedAt" IS NULL
          LEFT JOIN "CampaignActions_Customers" CC
            ON CC."customerId" = C.id
            AND CC."campaignActionId" = CA.id
          LEFT JOIN "Tags_Customers" TC2
            ON TC2."customerId" = C.id
            AND Cm."startAt" <= TC2."deletedAt"::date
            AND Cm."endAt" >= TC2."deletedAt"::date
        WHERE Cm.id = $1
          AND CC."campaignActionId" IS NULL
          AND TC."tagId" IN ($2:csv)
          AND C."deviceId" IS NOT NULL
        GROUP BY C.id`,
      },
      [1, [1,2,3]]
    )
```

I read the docs and I'm 100% sure I'm using this feature correctly. I even tried using named parameters, but getting a similar syntax error instead.

What's going on?

### Expected behavior
Query just works...

### Actual behavior
```
 error: syntax error at or near ":"

      at Connection.Object.<anonymous>.Connection.parseE (node_modules/pg/lib/connection.js:604:11)
      at Connection.Object.<anonymous>.Connection.parseMessage (node_modules/pg/lib/connection.js:401:19)
      at Socket.<anonymous> (node_modules/pg/lib/connection.js:121:22)
```

### Environment

* Version of pg-promise: 9.3.3
* OS type (Linux/Windows/Mac): Mac
* Version of Node.js: 12.x

I'd appreciate your help.

**Comment by vitaly-t** [comment]
You are using a [PreparedStatement](https://vitaly-t.github.io/pg-promise/PreparedStatement.html), which is formatted on the server side, where you are limited to just the basic `$1, $2, ...` variables, and no filters obviously.

[Formatting Filters], and well as [Named Parameters] are supported only within the regular queries that are formatted by the library itself.

[Formatting Filters]:https://github.com/vitaly-t/pg-promise#formatting-filters
[Named Parameters]:https://github.com/vitaly-t/pg-promise#named-parameters

**Comment by demian85** [comment]
Great, I just forgot that the `name` property makes it a prepared statement. Thanks.
