### ISSUE TITLE
Document supported version of Q

### ISSUE THREAD

**Issue by santanubasu** [vitaly-t/pg-promise#66]
Thanks for a great library.  I think I found a small bit missing in the docs, it wasn't clear to me which versions of Q were supported as a valid promiseLib.  It turned out that when I tried 0.9.6, a simple query logs an error as follows:

ERROR: [TypeError: Object function (resolve, reject) {
        npm.pg.connect(ctx.cn, function (err, client, done) {
            if (err) {
                $notify.error(ctx.options, err, {
                    cn: ctx.cn
                });
                reject(err);
            } else {
                resolve({
                    client: client,
                    done: function () {
                        done();
                        $notify.disconnect(ctx.options, client);
                    }
                });
                $notify.connect(ctx.options, client);
            }
        });
    } has no method 'done']

whereas using version 1.4.1 works fine.  If I've missed the part of the docs where the supported version is documented, my apologies.  If I haven't, it might be worthwhile adding a note about this.  Q's github page says that that the 1.x and 0.9.x releases are very similar, and I think both meet the requirement of having a resolve() and reject().  That's why I thought they both might be expected to work.

**Comment by vitaly-t** [comment]
The library supports any Promises/A+ compliant library, as stated everywhere. And method `done` isn't part of Promises/A+ at all. It was used as an example for library Bluebird, which implements method `done`.

Also, the example you are referring to is long gone. See the [updated examples](https://github.com/vitaly-t/pg-promise/tree/master/examples). However, it was replaced with `finally`, which is also not part of Promises/A+, but it doesn't matter. The examples are not part of the library itself, they are just samples of the final application, and as such, do not need separate documentation, the API used is already mentioned there.

In all, I wouldn't even use method `done`, it is unnecessary.

**Comment by santanubasu** [comment]
I probably should have provided a minimal test case to demonstrate the issue, here it is:

```
var promise = require('q');
var options = {
    promiseLib: promise
};
var pgp = require('../lib/index.js')(options);
var db = pgp("postgres://postgres:postgres@localhost/postgres");
db.query("select 1;")
    .then(function (data) {
        console.log("DATA:", data);
    })
    .catch(function (error) {
        console.log("ERROR:", error);
    })
```
As you can see there is no done() or finally() here.

The code above reaches then() when Q 1.4.1 is used.  It reaches the catch() when Q 0.9.6 is used.  Is that something you would expect?

**Comment by vitaly-t** [comment]
@santanubasu I had a look at that old version of Q, and it is easy to see that it is absolutely not compliant with the Promises/A+ standard.

Here's what the library's root looks like in 0.9.6:
```javascript
function Q(value) {
    return resolve(value);
}
```
that looks very wrong. And here's what the latest looks like:
```javascript
function promise(resolver) {
    if (typeof resolver !== "function") {
        throw new TypeError("resolver must be a function.");
    }
    var deferred = defer();
    try {
        resolver(deferred.resolve, deferred.reject, deferred.notify);
    } catch (reason) {
        deferred.reject(reason);
    }
    return deferred.promise;
}
```
that's what it should be to be compliant.

I have no way of knowing from which version Q started supporting Promises/A+ standard, you can try to find out that yourself and let other people know here.

In the meantime, this isn't a problem for this library. Even though it does try to detect the compliance, it does it through the signature of the library, it doesn't run tests to determine compliance. I'm not sure if it should though.

**Comment by vitaly-t** [comment]
I might consider improving the detection of the promise compliance, but it would be a bit awkward, because it requires running a series of tests during the library initialization, and while being a low priority, I'm not sure if it is a good idea to begin with.

**Comment by santanubasu** [comment]
Yes, agreed, looks like the issue is with Q's compliance then.  For those viewing this ticket, the version bump that takes Q from breaking to working in the above test case is 1.0.0 to 1.0.1.

**Comment by vitaly-t** [comment]
@santanubasu thanks! :+1:
