### ISSUE TITLE
Is it possible to create a union of multiple prepared statements?

### ISSUE THREAD

**Issue by kylemiller3** [vitaly-t/pg-promise#660]
I'm new to RMDBS and Postgres and I was wondering if there was a easy way to create union statements from PreparedStatements. If not what are my options to make composite select statements using pg-promise?

**Comment by vitaly-t** [comment]
Are you trying to join several SQL statements together, or are you talking about SQL-syntax unions?

Please include an example of what you are trying to achieve.

**Comment by kylemiller3** [comment]
Ok here is what I'm asking about in code (off top of my head untested). I don't think it's related to that SO link.

```Typescript
    export const selectAfterDateStmt: pgp.PreparedStatement = new pgp.PreparedStatement({
        name: 'select all after date',
        text: `select * from table where date > $1`,
    });
    export const selectWithIdStmt: pgp.PreparedStatement = new pgp.PreparedStatement({
        name: 'select all with id',
        text: `select * from table where id = $1`,
    });
```
What I would like to do ideally for instance: ``selectWithIdStmt intersect selectAfterDateStmt`` to get a array filtered by id and after a date so I don't have to write a lot of redundant statements.

**Comment by vitaly-t** [comment]
You can only combine SQL, you cannot combine `PreparedStatement`-s.

**Comment by kylemiller3** [comment]
So my option is concatenation of the command strings with union etc in between then prepare the statement? That actually is quite simple as well and I’m not sure why it slipped my mind.

**Comment by vitaly-t** [comment]
Note that a `PreparedStatement` can contain only a single query. That's PostgreSQL server-side limitation, due to the fact that such a query needs an optimized execution plan, i.e. be `prepared`.
