### ISSUE TITLE
Starting a transaction if none found (txIf?)

### ISSUE THREAD

**Issue by rodgarcialima** [vitaly-t/pg-promise#661]
I was trying to use txIf for this but it didn't work, or I didn't understand the right concept for it

I have two methods.

Method 1:

```js
const getByCnpj = async (cnpj, t) => {
  return await db.txe(t, async t => {
    return await empresasRepository.getByCnpj(cnpj, t);
  });
};
```

Method 2:

```js
const update = async (empresa, t) => {
  return await db.txe(t, async t => {
    return await empresasRepository.update(empresa, t);
  });
};
```

I want my methods on the same transaction, and this is OK, it's already working.
Example 1 (Calling from another service):

```js
const example1 = async cnpj => {
  await db.tx(async t => {
    const emp = await getByCnpj(cnpj, t);
    await update(emp, t);
  });
}
```

But I want to call my services without starting a transaction.
Example 2 (Calling from a controller):
```
exports.empresasGetByCnpj = async (req, res) => {
  res.send(await getByCnpj(req.params.cnpj));
};
```

I extended the db with txe (tx extended):

```js
extend: obj => {
    obj.txe = async (t, cb) =>
      t
        ? await cb(t) // Reuse tran
        : await obj.tx(async t => await cb(t)); // New tran
  },
```

Is this the right way to do it or I'm using txIf the wrong way?

Thank you, and congrats for the amazing job.

Rod

**Comment by vitaly-t** [comment]
> Is this the right way to do it or I'm using txIf the wrong way?

I don't see a single place where you are using [txIf]. And I do not understand the point of the `txe` extension.

[txIf]:https://vitaly-t.github.io/pg-promise/Database.html#txIf

**Comment by rodgarcialima** [comment]
Tried to use the txIf but didn't work.

The txe allows me to call a service method without passing a transaction.

Example:

```
const serviceMethod = (t) => {
  if (t) {
    callAnotherMethod(t);
  } else {
    db.tx(t => {
      callAnotherMethod(t);
    });
  }
}
```

How can I do the above code with txIf?

Thx

**Comment by vitaly-t** [comment]
```js
db.txIf(callAnotherMethod);
```

**Comment by rodgarcialima** [comment]
Maybe I'm using the wrong way
```javascript
const insert = async (empresa, t) => {
  return await db.txIf(async t => {
    return await empresasRepository.insert(empresa, t);
  });
};
```

**Comment by vitaly-t** [comment]
What is `t ` at the top level, in `async (empresa, t)`?

**Comment by rodgarcialima** [comment]
`t` should be a transaction or `null|undefined`. If `null|undefined` it must start a new transaction and pass it to the calling methods.

**Comment by vitaly-t** [comment]
Then your code should be something like this:

```js
const insert = async (empresa, context) => {
  return (context || db).txIf(async t => {
    return empresasRepository.insert(empresa, t);
  });
};
```

**Comment by rodgarcialima** [comment]
This is a test using `(context || db).txIf...`:

![image](https://user-images.githubusercontent.com/1371488/67163027-5584de80-f338-11e9-98b2-11c30ec6ebfc.png)


This is the same test using `txe`:

![image](https://user-images.githubusercontent.com/1371488/67163059-9846b680-f338-11e9-979c-b51dbc357b2d.png)

I think I'm gonna use the `txe`.

Thx

**Comment by vitaly-t** [comment]
Your code didn't look right from beginning, trying to use a task or transaction for executing a single query. That's wrong to begin with, you do not need either. 

And especially when executing multiple inserts, that's going in the wrong direction. See [this question](https://stackoverflow.com/questions/37300997/multi-row-insert-with-pg-promise) to understand how to do multi-row inserts.

**Comment by rodgarcialima** [comment]
I agree with you, but this is just one of my tests.

A more realistic use case would be:
```javascript
const createOrder = async (budgetId, t) => {
  return db.txe(t, async t => {
    const budget = budgetService.getById(budgetid, t);
    const order = orderService.createOrderFromBudget(budget, t);
    dispatchOrderEmail(order, t);
    dispatchDeliveryMsg(order, t);
    ...
    return order;
  });
};
```

And `createOrder` could be called with or without a transaction:

```javascript
const example1 = () => {
  createOrder(12345);
}

const example2 = (t) => {
  db.txe(t, async t=> {
    createOrder(12345, t);
  });
}
```

**Comment by vitaly-t** [comment]
Ok, it is up to you how you use it, according the the actual scenario.

To wrap this up, one uses `txIf`, if you want a task when already in transaction. But if you do not want to create a task when in transaction, then you can use a simple function for it:

```js
async function txe(cb, dbContext) {
    if(dbContext.ctx && dbContext.ctx.inTransaction) {
         // already in transaction;
        return cb(dbContext);
    } else {
        return dbContext.tx(cb);
    }
}
```

Or, a proper way to implement it via the protocol extension:

```js
extend: obj => {
    obj.txe = async cb => obj.ctx && obj.ctx.inTransaction ? cb(obj) : obj.tx(cb);
  },
```

**Comment by rodgarcialima** [comment]
Well, looks like I'm doing something wrong.

I'm extending the protocol with your code:
`obj.txe2 = cb => (obj.ctx && obj.ctx.inTransaction ? cb(obj) : obj.tx(cb));`

![image](https://user-images.githubusercontent.com/1371488/67164022-18bee480-f344-11e9-9b1d-feb00590a11a.png)

**Comment by vitaly-t** [comment]
Actually, it all makes sense, if you start tracking your query calls properly.

You can update your extension to fully use transaction/task parameters like this:

```js
extend(obj) {
    obj.txe = function(options, cb) {
        const args = pgp.utils.taskArgs(arguments); // prepare arguments
        return obj.ctx && obj.ctx.inTransaction ? args.cb(obj) : obj.tx.apply(this, args);
    }
  },
```

The changes we made also make the code properly asynchronous, while the over-use of `await` you had before was synchronizing it. You will see it now, by using this updated `txe`, and passing a string tag into it. Then you will see the actual execution logic/sequence.

**Comment by rodgarcialima** [comment]
Sorry for bugging you but I don't know what I'm doing wrong:

Extension:
![image](https://user-images.githubusercontent.com/1371488/67164822-85d67800-f34c-11e9-8d2d-233df28f993c.png)

Methods:
![image](https://user-images.githubusercontent.com/1371488/67164826-8ec74980-f34c-11e9-8182-befde651747c.png)

Test:
![image](https://user-images.githubusercontent.com/1371488/67164832-9c7ccf00-f34c-11e9-9d08-95cc6543614f.png)
The batch insert is not cool, this is one of the reasons I'm migrating to pg-promise :), and I'm not using it yet.

This is my test result:
![image](https://user-images.githubusercontent.com/1371488/67164887-fd0c0c00-f34c-11e9-8253-561633767bbe.png)

**Comment by vitaly-t** [comment]
I'm not sure I can help any further. It would require seeing the entire code and possibly debug it to understand what you are doing underneath. You will have to examine it yourself, I'm afraid.

**Comment by vitaly-t** [comment]
@rodgarcialima If you have an update, please post it here. But for now, this has been discussed in length, so I'm closing it.
