### ISSUE TITLE
Insert value auto parse from string to integer before insert

### ISSUE THREAD

**Issue by jefftham** [vitaly-t/pg-promise#663]
### Expected behavior
it should be inserted correctly, since the input match the table definition.

### Actual behavior
a columns define as:   phone varchar(255) NULL
insert into table (phone) values ("7194711999");

[![example](https://i.imgur.com/aZSPgOJ.png)](https://i.imgur.com/aZSPgOJ.png)

throw error: "value \"7194711999\" is out of range for type integer"

### Steps to reproduce
define a table with the a column data type as phone varchar(255) NULL
insert a record with as string that contain a big number value

### Environment

* Version of pg-promise: "^9.3.3"
* OS type (Linux/Windows/Mac): Mac
* Version of Node.js: 10.15.3

**Comment by vitaly-t** [comment]
This is a server-side error that clearly tells you that you are using the wrong type for the column. You should check the type properly on the server. Looks like it is actually an integer.

**Comment by jefftham** [comment]
@vitaly-t , you are right, i generate the columns attribute with javasript Object.keys, the order of the insert is out. That's mean the script trying to insert the string to the integer column and violate the constraint.
Thanks for helping

**Comment by vitaly-t** [comment]
@jefftham If you use this library right, you would never need to use `Object.keys` for generating queries. If you show the example, I might be able to show you how to do it the right way.

**Comment by jefftham** [comment]
Thanks @vitaly-t .

I am creating a microservice that accept metadata from the caller and return as, 
`return db[method](sql, bindParams);`

metadata:

```
  {
    sql:
      'INSERT INTO $<schema~>.$<table~> ( $<columns~> ) values ( $<data:csv> ) RETURNING id',
    bindParams: {
      schema: 'bulkorg',
      table: 'bulkorg',
      data: { key:value ...... more than 100 attributes },
    },
    method: 'query',
  }
```

at one point, the `bindParams.data` will be refreshed, so the `bindParams.columns` need to be regenerate.

i am trying to use [pgp.helpers.insert](http://vitaly-t.github.io/pg-promise/helpers.html#.insert), but it is not taking schema.

any suggestion?
thank you.

**Comment by vitaly-t** [comment]
> so the bindParams.columns need to be regenerate.

Filter `~` / `:name` also accepts an array of names, and an object to auto-enumerate properties. You do not need to do it manually.

> i am trying to use pgp.helpers.insert, but it is not taking schema.

It perfectly accepts a schema:

With the columns set:

```js
const cs = new ColumnSet(columns, {table: {schema: 'aaa', table: 'ttt'}});
```

Or with the actual method:

```js
const t = new pgp.helpers.TableName({schema: 'aaa', table: 'ttt'});

pgp.helpers.insert(data, cs, t);
```

**Comment by jefftham** [comment]
Is there a way to refer data object instead of generate columns?

**Comment by vitaly-t** [comment]
> Is there a way to refer data object instead of generate columns?

In a way, yes, depending on your implementation.

**Comment by jefftham** [comment]
1) how to generate columns from data object?
```
const cs = new ColumnSet(columns, {table: {schema: 'aaa', table: 'ttt'}});
```

2) how to generate columns from data object?
```
  {
    sql:
      'INSERT INTO $<schema~>.$<table~> ( $<columns~> ) values ( $<data:csv> ) RETURNING id',
    bindParams: {
      schema: 'dummy',
      table: 'org',
      data: { key:value ...... more than 100 attributes },
    },
    method: 'query',
  }
```

Thank you.

**Comment by vitaly-t** [comment]
First of all, are you working with just one data object or with multiple data objects at the same time?

**Comment by jefftham** [comment]
the first stage is to insert one record. future stage require to insert multiple records

**Comment by vitaly-t** [comment]
> future stage require to insert multiple records

Then you should be using `ColumnSet`.

**Comment by vitaly-t** [comment]
@jefftham Ultimately, you should be using `ColumnSet` for all inserts and updates. And if you are stuck with those, you can ask specific questions, and then I will be able to give specific answers.

Other than that, there are plenty of questions about those helpers on StackOverflow.

**Comment by jefftham** [comment]
Great,  I appreciate it. Thank you.
