### ISSUE TITLE
Make Client extendable within TypeScript

### ISSUE THREAD

**Issue by vitaly-t** [vitaly-t/pg-promise#667]
The library's TypeScript presently exposes `interface IClient` from the underlying driver.

However, the recent updates in the driver allow a dynamic `Client` to be provided by the `Pool`, if such is specified within the connection parameters. See issue #665 

We need to replace `interface IClient` with `class Client`, so it becomes extendable, plus add `Client` option within the connection parameters.

**Comment by vitaly-t** [comment]
Nothing was renamed in the end. There was however thorough incremental revamp of the TypeScript declarations, which should provide full backward compatibility.

See below a complete example of how we can set the connection pool to use our own custom `Client` type. In the example we extend the type to contain the database server version.

```ts
import * as pgPromise from 'pg-promise';

const pgp = pgPromise(/* initialization options */);

/* our custom client class */
class MyClient extends pgp.pg.Client {

    version?: string;

    constructor(config: any) {
        super(config);

        this.connection.on('parameterStatus', (msg: any) => {
            if (msg.parameterName === 'server_version') {
                this.version = msg.parameterValue;
            }
        });
    }
}

const cn = {
    database: 'pg_promise_test',
    user: 'postgres',
    password: 'Harmony1',
    Client: MyClient /* our custom Client type to be used by the connection pool */
};

const db = pgp(cn);

/* just to test the Client type */
db.connect()
    .then(c => {
        // default c type is cast correctly for the client:
        console.log('Server Version:', c.client.version);
        c.done();
    })
    .catch(console.error);
```

**Comment by vitaly-t** [comment]
Released in version 9.3.4

**Comment by JCMais** [comment]
Generics ftw

**Comment by vitaly-t** [comment]
[9.3.5 update](https://github.com/vitaly-t/pg-promise/releases/tag/9.3.5) improves it a little.

**Comment by vitaly-t** [comment]
@realcarbonneau Is there a reason you down-voted the update?

**Comment by realcarbonneau** [comment]
Misclick, sorry, thanks for pointing that out.

**Comment by vitaly-t** [comment]
Added update to the original example. Basically, #673 made the example kind of obsolete, i.e. it still will work, you just no longer would use it for detecting the server version.
