### ISSUE TITLE
feature request: helpers.insert and helper.update add support when property is missing

### ISSUE THREAD

**Issue by jefftham** [vitaly-t/pg-promise#669]
### Expected behavior
`
pgp.helpers.insert([ { x: 'x0' }, { x: 'x1', y: 'y1' } ] , ['x', 'y'] , 'table1' )
`
when the property 'y' is missing in one of the object, replace with null instead of throw error.

expected produce as
`insert into "table1" ("x","y") values('x0',null),('x1','y1')`

### Actual behavior
throw error as "Error: Property 'y' doesn't exist."

### Steps to reproduce
see above

### Environment

* Version of pg-promise: "^9.3.3"
* OS type (Linux/Windows/Mac): Mac
* Version of Node.js: 10.15.3

**Comment by vitaly-t** [comment]
That feature has always been there:

```js
const cs = new pgp.helpers.ColumnSet([
    'x',
    {name: 'y', def: null}
], {table: 'table1'});

pgp.helpers.insert(data);
```

**Comment by jefftham** [comment]
Thanks @vitaly-t  reply promptly.

i have one more question.
how about the update one record? the columns is optional and can be null, eg.
`pgp.helpers.insert({ x: 'x1', y: 'y1' } , null , 'table1' )`
is 
`new pgp.helpers.ColumnSet( null, {table: 'table1'})` work correctly?

**Comment by vitaly-t** [comment]
No, you do not create a `ColumnSet` without columns, because what's the point?

So I'm not certain what you are asking, especially since you are talking about `update`, while calling `insert` method. Please make your question clear.

**Comment by jefftham** [comment]
sorry for the confusion, i mean insert in this case.
thanks for helping. i have solution already. 
as you said, i don't need to create columnset blindly.
