### ISSUE TITLE
Query is returning true even when it should return false

### ISSUE THREAD

**Issue by JaxCavalera** [vitaly-t/pg-promise#67]
My database structure is setup so that  when I run the following query in pgAdmin3 it returns the only row in my users table : ```SELECT * FROM users WHERE username = 'jax';```

however when i try to run the following through pg-promise it tells me that the username is available regardless of what I set the value for 'uname' to : 
```javascript
export function regAble(uname) {
    db.query('SELECT username FROM users WHERE username = $1', uname)
    .then(function() {
        console.log('Username is Available' + uname);
        return true;
    })
    .catch(function(error) {
        console.log('Choose a New Username or Login', error);
        return false;
    });
}
```

I don't understand how that's possible.

**Comment by vitaly-t** [comment]
That sounds strange, something must be missing. I can't see the log to understand what exactly.

Are you using [pg-monitor](https://github.com/vitaly-t/pg-monitor)? That would show you the exact queries being executed.

**Comment by JaxCavalera** [comment]
i'm not i'll grab pg-monitor now

and report back what's actually being queried

**Comment by vitaly-t** [comment]
Ok. Here's an [example]()https://github.com/vitaly-t/pg-promise/blob/master/examples/monitor.js for a quick start ;)

**Comment by JaxCavalera** [comment]
ok this is what it returns in the log with monitor running :
```
11:49:14 connect(postgres@tagged)
11:49:14 SELECT username FROM users WHERE username = jax
11:49:14 error: column "jax" does not exist
         query: SELECT username FROM users WHERE username = jax
11:49:14 disconnect(postgres@tagged)
Choose a New Username or Login { [error: column "jax" does not exist]
  name: 'error',
  length: 96,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '45',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3087',
  routine: 'errorMissingColumn' }
```

**Comment by vitaly-t** [comment]
It doesn't really make sense. The only way such query would be formatted if you were to execure the following query:
```js
db.query('SELECT username FROM users WHERE username = $1^', uname)
```
but you aren't. When $1 variable is used for a text string, it is always wrapped into quotes. The only case it can avoid it is when `uname` is an object that supports custom formatting.

**Comment by JaxCavalera** [comment]
adjusted the query and am using the live variable again (tried hard coding a string value of "jax" n just to check) same result though :
```
db.query('SELECT * FROM users WHERE username = $1^', uname)
```
```
11:57:53 connect(postgres@tagged)
11:57:53 SELECT * FROM users WHERE username = "jax"
11:57:53 error: column "jax" does not exist
         query: SELECT * FROM users WHERE username = "jax"
11:57:53 disconnect(postgres@tagged)
Choose a New Username or Login { [error: column "jax" does not exist]
```

if I change the query to : 
```javascript
export function regAble(uname) {
    db.query('SELECT * FROM users WHERE username = ${name}', {
        name: uname,
    })
```
it returns the following based on what I set "uname" to be
```
12:00:51 connect(postgres@tagged)
12:00:51 SELECT * FROM users WHERE username = '"jax"'
12:00:51 disconnect(postgres@tagged)
Username is Available
12:01:00 connect(postgres@tagged)
12:01:00 SELECT * FROM users WHERE username = '"jaxa"'
12:01:00 disconnect(postgres@tagged)
Username is Available
12:01:05 connect(postgres@tagged)
12:01:05 SELECT * FROM users WHERE username = '"jaasdfadsfaxa"'
12:01:05 disconnect(postgres@tagged)
Username is Available
```

all of those shouldn't be returning as true I would have thought since there is only 1 entry in my db and it's for lowercase "jax"

**Comment by vitaly-t** [comment]
How do you end up executing string like this: `'"jax"'`? The only way I can do it if I have `uname='"jax"'`.

**Comment by JaxCavalera** [comment]
hmm well i did find something, I think I'm getting closer to the problem here, when i remove the "JSON.stringify" from the "uname" variable it comes back as follows :
```
12:07:48 connect(postgres@tagged)
12:07:48 SELECT * FROM users WHERE username = 'jax'
12:07:48 disconnect(postgres@tagged)
Username is Available [object Object]
12:07:58 connect(postgres@tagged)
12:07:58 SELECT * FROM users WHERE username = 'somerand'
12:07:58 disconnect(postgres@tagged)
```
ehm the git repo for this is at :
**where I am sending the request into my Express server**
https://github.com/JaxCavalera/Tagged/blob/master/app/actions/auth-actions.jsx

**server that receives the request**
https://github.com/JaxCavalera/Tagged-DBserver/tree/master/src

**Comment by vitaly-t** [comment]
Hah! You should have used that function! And for the other part - I updated my previous reply ;)

**Comment by JaxCavalera** [comment]
I just don't understand why it returns "available" a.k.a true no matter what I enter.. 
the query should be false if there is no match right?

**Comment by vitaly-t** [comment]
Because this is exactly what your code does:
```js
  .then(function() {
        console.log('Username is Available' + uname);
        return true;
    })
```

**Comment by JaxCavalera** [comment]
but shouldn't that only happen if there are no errors with the query?

**Comment by vitaly-t** [comment]
There are no errors with that query, method `query` successfully returns 0 records, with `data = []`

**Comment by JaxCavalera** [comment]
O.o ehm  but then how do i do a simple do this if no results are found.. do that if a result is found?

**Comment by vitaly-t** [comment]
Depends on what you app logic is there. If you are expecting any number of records, you can call `query`, or `manyOrNone`, or `any`, and then analyze the data:
```js
 .then(function (data) {
    if (data.length) {
        // have records;
    }
})
```
if you are expecting 1 record always, use method `one`, if 1 or 0 records - method `oneOrNone`. See the methods documentation, it is the very basic thing about this library. Did you read [Learn by Example](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example)?

**Comment by JaxCavalera** [comment]
Ohhh so Catch is only catching errors with the actual query being executed.. not errors like.. no results found

so all my logic has to be applied to he returned value (data) and processed inside the ".then(function)"

I think i misunderstood the content in the Learn by Example area

**Comment by vitaly-t** [comment]
Yeah, have another look, it's really quite simple. I'm outa here for now, 2:30am here.

**Comment by JaxCavalera** [comment]
no worries thanks again for your help and time with this, appreciated greatly.
