### ISSUE TITLE
Postgres v11+ Native Stored Procedures

### ISSUE THREAD

**Issue by vitaly-t** [vitaly-t/pg-promise#670]
This features is a follow-up on #665 

---

PostgreSQL v11 introduced support for [stored procedures](https://www.postgresql.org/docs/11/sql-createprocedure.html).

Method [proc] needs to be re-done to account for that. Currently, it just forwards into [func], which executes `SELECT * FROM procName(values)`, and then resolves with one or no value.

This creates a confusion, moving forward, and needs to be changed, so that [proc] would execute the new `CALL procName(values)` instead, and resolve with `null`.

This will be a breaking change, and method [proc] will throw a server-side error, if executed against PostgreSQL server prior to v11. It will be the only version-sensitive method in the library.

[proc]:https://vitaly-t.github.io/pg-promise/Database.html#proc
[func]:https://vitaly-t.github.io/pg-promise/Database.html#func

**Comment by vitaly-t** [comment]
I have done initial implementation in branch [proc](https://github.com/vitaly-t/pg-promise/tree/proc), but Travis CI gave me trouble upgrading PostgreSQL to v11 within [.travis.yml](https://github.com/vitaly-t/pg-promise/blob/master/.travis.yml). And so I cannot include new tests for stored procedures into automated tests.

Any help with this would be welcome! Until then, I'm putting it on hold.

**Comment by vitaly-t** [comment]
While working  on this, found #671

**Comment by realcarbonneau** [comment]
@vitaly-t I have been testing your new proc, but it's not matching up the proc signature, even sending parameters as strings.  I will trace and get back to you with more details.

**Comment by vitaly-t** [comment]
I have tested it here, and it works just fine. Make sure you use the latest from the `proc` branch, which now includes the fix for #671

**Comment by realcarbonneau** [comment]
Works for me:

```
CREATE TABLE test(
  id       SERIAL PRIMARY KEY NOT NULL,
  ts       TIMESTAMP WITH TIME ZONE,
  test_int INTEGER
);

CREATE OR REPLACE PROCEDURE test_proc(in_int INTEGER)
LANGUAGE 'plpgsql'
AS $BODY$
  DECLARE
    -- Nothing
  BEGIN
    -- Insert into Test
    INSERT INTO test (ts, test_int) VALUES (CLOCK_TIMESTAMP(), in_int);
  END
$BODY$;

CREATE OR REPLACE FUNCTION test_func(in_int INTEGER) RETURNS BOOLEAN
LANGUAGE 'plpgsql'
AS $BODY$
  DECLARE
    -- Nothing
  BEGIN
    -- Insert into Test
    INSERT INTO test (ts, test_int) VALUES (CLOCK_TIMESTAMP(), in_int);
    RETURN TRUE;
  END
$BODY$;
```

```
const procResult = await db.proc('test_proc', 3)
const funcResult = await db.func('test_func', 4)
```

```
2019-11-09 14:29:09.065 EST [17916] LOG:  statement: call test_proc(3)
2019-11-09 14:29:09.078 EST [17916] LOG:  statement: select * from test_func(4)
```

![image](https://user-images.githubusercontent.com/29619229/68534201-82a52b00-02ff-11ea-9abd-e69bdaa370ef.png)

**Comment by vitaly-t** [comment]
Great! Also, as per the #671 fix, if you give it name it something like `testProc`, it will be automatically double quoted, i.e. as `CALL "testProc"()`.

**Comment by realcarbonneau** [comment]
Doesn't seem to work for me.

```
CREATE OR REPLACE PROCEDURE testProc(in_int INTEGER)
LANGUAGE 'plpgsql'
AS $BODY$
  DECLARE
    -- Nothing
  BEGIN
    -- Insert into Test
    INSERT INTO test (ts, test_int) VALUES (CLOCK_TIMESTAMP(), in_int);
  END
$BODY$;
```

```
const procResult = await db.proc('test_proc', 3)
const proc2Result = await db.proc('testProc', 4)
const funcResult = await db.func('test_func', 5)
```

```
2019-11-09 15:01:52.142 EST [14864] LOG:  statement: call test_proc(3)
2019-11-09 15:01:52.162 EST [14864] LOG:  statement: call "testProc"(4)
2019-11-09 15:01:52.163 EST [14864] ERROR:  procedure testProc(integer) does not exist at character 6
2019-11-09 15:01:52.163 EST [14864] HINT:  No procedure matches the given name and argument types. You might need to add explicit type casts.
2019-11-09 15:01:52.163 EST [14864] STATEMENT:  call "testProc"(4)
```

**Comment by vitaly-t** [comment]
@realcarbonneau It doesn't work for you because it thinks you declared procedure named `"testProc"`, and not `testProc`. Do you know how camel case works in PostgreSQL? :smile:

**Comment by realcarbonneau** [comment]
Well it works on the db directly, so your call should work also.  

But I know what you mean.  If the coder wrote `camelCase` on the js side, you will identify this and always add quotes around it, instead of asking the coder to follow strictly the string literal `"camelCase"` on both sides.  

If I pass the literal `"char"` to the db, that is different than `char`. I prefer that my strings are not changed.  But it's your choice.  

Either way, I always snake_case on the db side and camelCase in js and use the [case-change](https://github.com/blakeembrey/change-case) if I need to translate.  Therefore I am indifferent on this issue other than from a theoretical perspective that when you do invasive modifications of string literals, it should to be consistent and coherent across your framework.



![image](https://user-images.githubusercontent.com/29619229/68534654-be8ebf00-0304-11ea-8367-0e65dc4410be.png)

**Comment by realcarbonneau** [comment]
You are going to curse! hahaha

FUNCTIONs are case sensitve in quotes, but not PROCEDUREs. See screenshots below.  So the whole thing is useless for PROCEDUREs.

I would always pass the string literal to the db, no changing it, or else the whole this is not coherent.   What are you going to do when a wise guy calls his function "testfunc" litterally?  See the last screenshot.  It becomes a spaghetti mess of logic, documentation an explanations.

![image](https://user-images.githubusercontent.com/29619229/68534940-c51f3580-0308-11ea-9ab4-fe161fb7ba16.png)

![image](https://user-images.githubusercontent.com/29619229/68534928-ade04800-0308-11ea-8cfa-6b63415b86f7.png)

![image](https://user-images.githubusercontent.com/29619229/68535015-9eadca00-0309-11ea-8f90-82ce4bba33c5.png)

**Comment by vitaly-t** [comment]
> Well it works on the db directly, so your call should work also.

Nope. It works directly because you are not using the actual camel case. You need to either use it in both places, or none at all.

**Comment by vitaly-t** [comment]
Published [10.0.0 Beta.0](https://github.com/vitaly-t/pg-promise/releases/tag/10.0.0-Beta.0).

**Comment by realcarbonneau** [comment]
You are correct, there was a problem in my prior test sequences that left a lower case version of the procedure.  I think that I understand that your perspective is that since JS is case-sensitive and that since pg is case-insensitive (technical everything is forced to lower-case), you will preserve the cases of technical names by quoting the strings that contain at least one upper-case when sending them to pg.   There is no specific concept of camelCase in pg, as someone could choose PascalCase or whatever they want.  I assume that you preserve cases into pg for all technical names across your library?  Best practices for pg are to keep everything lower case, such as by using snake_case, but if your camelCase and PascalCase and other miXedCaSe friends are happy, that is what matters! :)

**Comment by vitaly-t** [comment]
>  I think that I understand that your perspective is that since JS is case-sensitive and that since pg is case-insensitive

I'm afraid, you still do not understand it. JavaScript case-sensitivity got nothing to do with it, because we supply function/procedure name as a string always.

> There is no specific concept of camelCase in pg

Actually, there is. Camel-case handling within PostgreSQL is very specific, and I suggest you read about it. Otherwise you keep posting incorrect assumptions.

**Comment by vitaly-t** [comment]
Released in [v10.0.0](https://github.com/vitaly-t/pg-promise/releases/tag/10.0.0).

**Comment by realcarbonneau** [comment]
@vitaly-t [Official PostgreSQL Documentation](https://www.postgresql.org/docs/12/index.html)
[0 results for camelCase](https://www.postgresql.org/search/?u=%2Fdocs%2F12%2F&q=camelCase)
[0 results for camel case](https://www.postgresql.org/search/?u=%2Fdocs%2F12%2F&q=camel+case)

I have never found any reference to camel case in the official documentation.  Of course, there is some discussion of camelCase in the mailling lists and elsewhere on the internet, however, it is always in the greater context of the case-insensitivity of SQL identifiers (SQL:2016 or ISO/IEC 9075:2016) and not specific to camelCase.  Technically, case-insensitivity is actually achieved by the SQL standard folding identifiers to uppercase and postgreSQL folding identifiers to lowercase.

[SQL Syntax - Lexical Structure](https://www.postgresql.org/docs/12/sql-syntax-lexical.html) Section 4.1.1 
"Quoting an identifier also makes it case-sensitive, whereas unquoted names are always folded to lower case. For example, the identifiers FOO, foo, and "foo" are considered the same by PostgreSQL, but "Foo" and "FOO" are different from these three and each other. (The folding of unquoted names to lower case in PostgreSQL is incompatible with the SQL standard, which says that unquoted names should be folded to upper case. Thus, foo should be equivalent to "FOO" not "foo" according to the standard. If you want to write portable applications you are advised to always quote a particular name or never quote it.)"

case-sensitive identifiers are an exception dealt with using quotes and the function [quote_ident(string text)](https://www.postgresql.org/docs/9.0/functions-string.html)

[ISO/IEC 9075:1992](http://www.contrib.andrew.cmu.edu/~shadow/sql/sql1992.txt), page 100
```
4) An <SQL language identifier> is equivalent to an <SQL language
            identifier> in which every letter that is a lower-case letter
            is replaced by the equivalent upper-case letter or letters. This
            treatment includes determination of equivalence, representation
            in the Information and Definition Schemas, representation in the
            diagnostics area, and similar uses."
```

**Comment by vitaly-t** [comment]
Not sure about the original, but there are tons about it on StackOverflow ;)

**Comment by realcarbonneau** [comment]
Ok, tell me if you need help on anything else, testing or coding. :)

I am now running v12, mostly.

**Comment by vitaly-t** [comment]
Thank you! :) I'm all done with #673 - check it out ;)

@realcarbonneau

**Comment by vitaly-t** [comment]
Re-opening, to attempt pg v11 integration yet again.

**Comment by vitaly-t** [comment]
Now the library is finally using PG v11, thanks to @dplewis :smile:

**Comment by vitaly-t** [comment]
Support for stored procedures has been revised in [v10.3.3](https://github.com/vitaly-t/pg-promise/releases/tag/10.3.3).

**Comment by demian85** [comment]
Can someone please explain how to use the .proc method to call a procedure in Postgres v9.x? I updated from pg@7 to the latest version and it is failing when calling .proc. Can I use .func instead? Which should be the proper syntax?
Thanks.

**Comment by vitaly-t** [comment]
@demian85 

> Can someone please explain how to use the .proc method to call a procedure in Postgres v9.x? 

You can't, the API clearly states, that function requires PG v11 or later.

> Can I use .func instead?

Yes, absolutely.
