### ISSUE TITLE
Pool Size Configuration

### ISSUE THREAD

**Issue by jjuutila** [vitaly-t/pg-promise#68]
I was able to pass pooling settings to node-postgres by passing the pool settings in pg-promise connection options. Example:

```
var pgPromiseLib = require('pg-promise');
var pgPromise = pgPromiseLib();
var connectionOptions = {
    host: 'localhost',
    port: 5432,
    database: 'my_db_name',
    user: 'user_name',
    password: 'user_password',
    poolSize: 50,
    poolIdleTimeout: 10000
};
var pg = pgPromise(connectionOptions);
```

I think this a better way to configure pool settings than the solution mentioned here https://github.com/vitaly-t/pg-promise/issues/23 because it doesn't mutate shared state and it adds a possibility to set e.g. `poolSize` per pool.

So my question is: should the possibility to pass pool settings in connection options be a documented feature or is my code based on a bug?

**Comment by vitaly-t** [comment]
From chapter [Connecting](https://github.com/vitaly-t/pg-promise#connecting):

>This library doesn't use any of the connection's details, it simply passes them on to PG when opening a connection. For more details see pg connection parameters in WiKi and implementation.

So if it works for you, it is great. And as far as the documentation goes, there is no denial of such functionality either.

**Comment by vitaly-t** [comment]
Included this question into [FAQ](https://github.com/vitaly-t/pg-promise/wiki/FAQ)
