### ISSUE TITLE
Recover from idle_in_transaction_session_timeout

### ISSUE THREAD

**Issue by tmtron** [vitaly-t/pg-promise#680]
### Expected behavior
After an idle_in_transaction_session_timeout, the used connection will be working properly when used again from the pool.

### Actual behavior
After a statement timeout in transaction, the used connection will be "broken" and new queries will not work. The error-message is `Client has encountered a connection error and is not queryable`

### Steps to reproduce
I've added a [test-case](https://github.com/tmtron/pg-promise/blob/master/test/idle-in-transaction-session-timeout.spec.js#L48) to my project fork

### Environment

* Version of pg-promise: 10.2.1
* OS type (Linux/Windows/Mac): Windows 10
* Version of Node.js: 12.12.0

### Related
* [Stackoverflow: How to handle idle_in_transaction_session_timeout?](https://stackoverflow.com/questions/59193427/how-to-handle-idle-in-transaction-session-timeout)  
* similar issue: #566

### Notes
I thought that adding another check to [isConnectivityError](https://github.com/vitaly-t/pg-promise/blob/master/lib/utils/index.js#L205) for code `25P03` (see [postgres error codes](https://www.postgresql.org/docs/11/errcodes-appendix.html)) should work, but it does not. In this case the `err` parameter has no `code` property, but a `message` string.  
A nasty workaround for now is to check this `message` string:
```
    if (!code && err.message && typeof err.message === 'string') {
        if (err.message.includes('is not queryable')) return true;
    }

```

**Comment by vitaly-t** [comment]
This is from invalid transaction usage, as the author [indicated so himself](https://stackoverflow.com/questions/59162112/what-can-cause-idle-in-transaction-for-begin-statements/59270263#59270263).

**Comment by tmtron** [comment]
I don't see why this issue is closed: IMHO it is clear that pg-postgres is currently not handling the `idle_in_transaction_session_timeout` error correctly: i.e. it must be treated as a connectivity error and the "broken" connection must not be reused. I hope we agree on that.

So maybe you can give me some thints on how to get the error-code (and not just the error-text) in the `isConnectivityError`, I'll try to come up with a PR.

**Comment by vitaly-t** [comment]
I thought the issue was sorted.

**Comment by tmtron** [comment]
Well, the specific issue in our app is fixed.

But I think it's just too easy that such an issue can slip into the application code again in the future. And then it would be great to have the `idle_in_transaction_session_timeout` as a safety-net so that the app can recover automatically. Then the app would still be usable until we find the issue in the code and install the new version.

I'll check node-postgres and their issue-list when I find some time.

**Comment by vitaly-t** [comment]
This is an unusual issue, and is the first time I ever hear about it.

And if you can detect it for a specific transaction code, you can force the physical connection to be released, using the following synthetic approach:

```js
async function specialTransaction() {
    const obj = db.connect(); // manually allocating the connection
    let idleTxIssueFound = false;
    const txData = await obj.tx(async t => {
             // execute the transaction, and detect the idle issue, if possible
             idleTxIssueFound = true; // if found an issue
    });
    // passing true into method `done` will force physical release of the connection
    obj.done(idleTxIssueFound);
    return txData;
}   
```

**Comment by tmtron** [comment]
After checking some code and issues of node-postgres, I think my initial assumption was wrong. We will never receive error-code `25P03` from the database. Instead we only get the error-string from [node-postgres:](https://github.com/brianc/node-postgres/blob/master/lib/client.js#L521):  

>`query.handleError(new Error('Client has encountered a connection error and is not queryable'), this.connection)`

I think whenever this error happens (for whatever reason - not only when `idle_in_transaction_session_timeout`  is used), pg-promise must remove this connection from the pool because it is broken.

Since node-postgres only returns an error string, and no error-code or error-class that can be checken, the only way to handle this case is to check the text of the error-message.

There are many related issues in node-postgres:
* [#1942 node-postgres handles server disconnection differently on macOS and Linux](https://github.com/brianc/node-postgres/issues/1942)
* [#1790 "Client has encountered a connection error and is not queryable" without further info](https://github.com/brianc/node-postgres/issues/1790)
* [#1611 Connection terminated unexpectedly](https://github.com/brianc/node-postgres/issues/1611)

and in node-pg-pool:
* [#673 Connection terminated due to connection timeout / Connection terminated](https://github.com/brianc/node-pg-pool/issues/116)

**Comment by vitaly-t** [comment]
It's a tough one to tackle. I mean, there is not good fix from this end, by the sound of it.

**Comment by tmtron** [comment]
I can also make the test work without checking the error-string and use [`client._queryable`](https://github.com/brianc/node-postgres/blob/master/lib/client.js#L41) instead

e.g. change line [59](https://github.com/vitaly-t/pg-promise/blob/master/lib/connect.js#L59) of function `poolConnect` from
`client.release(kill || client.$connectionError);`
to :
`client.release(kill || client.$connectionError || !client._queryable);`

That is for sure better, but maybe the underscore in the variable name `_queryable` indicates that this variable is private and should not be used?

**Comment by vitaly-t** [comment]
This does look like a hack-fix, i.e. should work in the current implementation of the client, but may get broken later, as we use a private variable.

**Comment by tmtron** [comment]
That's what I think too: maybe the node-postgres guys will make this pubilc: see  [node-postgres #2026](https://github.com/brianc/node-postgres/issues/2026)

**Comment by vitaly-t** [comment]
I think a more appropriate request would be to make the pool automatically release non-queryiable clients. Asking to make a private variable into public isn't a good idea in this case, it's just too low-level for what you are trying to achieve with this.

**Comment by vitaly-t** [comment]
@tmtron Before I make a change, since I cannot reproduce the issue on my side, can you check something for me, please...

When this issue occurs, does the query throw an error? Because if it does, then the best place to amend the code would for `isConnectivityError` function. And if the query does not throw an error, then I will have to amend the `connect` method.

**Comment by tmtron** [comment]
> since I cannot reproduce the issue on my side

Really? So the reproduction [test-case](https://github.com/tmtron/pg-promise/blob/master/test/idle-in-transaction-session-timeout.spec.js) works on your side?  
That's strange: the test case can reproduce the issue on my dev-PC and on GitLab CI.

>When this issue occurs, does the query throw an error? Because if it does, then the best place to amend the code is within isConnectivityError function. 

The[ first query](https://github.com/tmtron/pg-promise/blob/master/test/idle-in-transaction-session-timeout.spec.js#L41) that is run after the timeout will throw the error string `Client has encountered a connection error and is not queryable`.  
As mentioned in the original post, we could handle this in the [isConnectivityError](https://github.com/vitaly-t/pg-promise/blob/master/lib/utils/index.js#L205) function, but since we only get a string it's quite nasty.

The current version of pg-promise will not recover from this and also the [2nd query](https://github.com/tmtron/pg-promise/blob/6d2105c20bcbca5b0d101e74fa85067aa03baf82/test/idle-in-transaction-session-timeout.spec.js#L48) in the test will throw the same error-message (because the broken connection, which is not queryable anymore, is reused).

**Comment by vitaly-t** [comment]
Sorry for the late response. I can indeed see the issue from the test you provided.

[Here I simplified it](https://gist.github.com/vitaly-t/41e9a9bd7e0171587bc602b8f53af5b7), enough to still see the issue.

**Comment by vitaly-t** [comment]
I have created a branch [tx-idle-timeout](https://github.com/vitaly-t/pg-promise/tree/tx-idle-timeout) to experiment with this.

**Comment by tmtron** [comment]
@vitaly-t Thanks for looking into this. Unfortunately I have no idea why the broken connection is not removed and reused in the next query.  
Just note, that this is not urgent for me, since we can live for now with the quick-hacky fix using `client._queryable` as explained in [this comment](https://github.com/vitaly-t/pg-promise/issues/680#issuecomment-565037673) above.

**Comment by vitaly-t** [comment]
@tmtron I think I have solved it with [this commit](https://github.com/vitaly-t/pg-promise/commit/7eca06ab2f21232f9a2512b0f5548a9146df77c6), to force killing every connection that's non-queryable.

**Comment by vitaly-t** [comment]
Released the fix in [v10.3.5](https://github.com/vitaly-t/pg-promise/releases/tag/10.3.5).

**Comment by tmtron** [comment]
@vitaly-t I've just updated to 10.3.5 and it works for me. All our tests are okay.
I think using the "private" `_queryable` property of postgres-node is okay for now, since we have a test-case that will fail, if this property will ever change.  
And we will keep an eye on [node-postgres #2026](https://github.com/brianc/node-postgres/issues/2026)  
Thanks again!

**Comment by zhanghuancs** [comment]
Hi, I upgraded to 10.3.5, and now I did not see error message `Client has encountered a connection error and is not queryable` any more, however, it starts to throw error: `Connection terminated unexpectedly`.

The stacktrace I have in my logs looks like
```
Error: Connection terminated unexpectedly
    at u.<anonymous> (/var/task/webpack:/node_modules/pg/lib/client.js:252:9)
    at Object.onceWrapper (events.js:299:28)
    at u.emit (events.js:210:5)
    at u.emit (domain.js:476:20)
    at Socket.<anonymous> (/var/task/webpack:/node_modules/pg/lib/connection.js:76:10)
    at Socket.emit (events.js:210:5)
    at Socket.EventEmitter.emit (domain.js:476:20)
    at TCP.<anonymous> (net.js:658:12)
```
### Environmen
* Version of pg-promise: 10.3.5
* OS type (Linux/Windows/Mac): Linux
* Version of Node.js: 12.12.24

**Comment by vitaly-t** [comment]
@zhanghuancs That sounds like an issue related to keeping a connection open, which might something to do with your hosting environment. This is not related to the original issue here.

**Comment by vitaly-t** [comment]
@tmtron The underlying driver just took in [the recommended change for dumping non-queryable connections](https://github.com/brianc/node-postgres/pull/2083).

This means the functionality added here will be removed in a new official release that starts using that branch.

**Comment by zhanghuancs** [comment]
> @zhanghuancs That sounds like an issue related to keeping a connection open, which might something to do with your hosting environment. This is not related to the original issue here.

Hi, @vitaly-t Thank you for the response. I'm using AWS Lambda and follow the instruction [here](https://www.jeremydaly.com/reuse-database-connections-aws-lambda/) to reuse database connection using AWS Lambda. This might be the issue related to keeping a connection open as you said. Is there a way in pgpromise that I can get the open connection and kill this specific connection? Besides, is it possible that this issue is related to this [thread](https://github.com/brianc/node-postgres/issues/1942), and it's quoted that the `connection errors (and query errors, from my findings) should be passed to client.release.` If I catch this error, and how can I release the connection? In my API, I just use .task to chain .oneOrNone and .any queries, very similar to the [transaction example] (https://github.com/vitaly-t/pg-promise/blob/master/examples/transaction.js), but I did not execute `.finally(db.$pool.end); ` in the end, as I do not want to exit the app. 

Any help would be appreciated! Thanks.

**Comment by Gustav0ar** [comment]
@vitaly-t Hi, I think there is a regression in this item. I have a big query using this method: https://github.com/vitaly-t/pg-promise/wiki/Data-Imports#massive-inserts with [v10.4.4](https://github.com/vitaly-t/pg-promise/releases/tag/10.4.4), I'm getting this error: `Client has encountered a connection error and is not queryable
`. When I got back to the version that you fixed [v10.3.5](https://github.com/vitaly-t/pg-promise/releases/tag/10.3.5), the query executes without issues

**Comment by vitaly-t** [comment]
@Gustav0ar Could you, please, re-try, using version `10.5.0-beta.0`?

**Comment by Gustav0ar** [comment]
> @Gustav0ar Could you, please, re-try, using the latest Beta version?
> 
> I am currently updating it, before v10.5.0 release.

@vitaly-t Apparently it is working fine with the beta version. I'll update if I find any issues

**Comment by flovilmart** [comment]
@vitaly-t  still seeing the issue on `10.11.0`  Anything we can do to help?
