### ISSUE TITLE
Paramterized query with SIMILAR TO list?

### ISSUE THREAD

**Issue by njlr** [vitaly-t/pg-promise#684]
Is there a syntax to support parametrized queries like this?

```sql
select * from table where lower(value) similar to '%(foo|bar|baz)%';
```

This does not work but hopefully conveys what I am trying to achieve:

```javascript
const terms = [
  'foo',
  'bar',
  'baz',
];

const sql = `
select * from table where lower(value) similar to '%$<terms>%'
`;

const records = await db.query(sql, { terms });
```

The `terms` come from user input, so must be sanitized.

**Comment by boromisp** [comment]
If you want correct results for arbitrary user input, you will need to use some kind of [regexp escaping](https://stackoverflow.com/questions/3446170/escape-string-for-use-in-javascript-regex) adapted to the [SIMILAR TO specific](https://www.postgresql.org/docs/current/functions-matching.html#FUNCTIONS-SIMILARTO-REGEXP) special characters. I don't think there is regexp escaping implemented in this library or in postgresql.

Something like this might work, but please note that I haven't tested this escape pattern, and you will need to use a different one if you use an other pattern matching operator:

```js
function escape(string) {
  return string.replace(/[\\_%|*+?{}()[\]]/g, '\\$&');
}

const terms = [
  'fo*o',
  'b|ar{1,4}',
  'ba%z',
];

const sql = `
select * from table where lower(value) similar to $<terms>
`;

const termsStr = `%(${ terms.map(escape).join('|') })%`;

const records = await db.query(sql, { terms: termsStr });
```

**Comment by vitaly-t** [comment]
@njlr Use [Open Value Filter](https://github.com/vitaly-t/pg-promise#open-values) for that:

```js
const sql = `select * from table where lower(value) similar to '%($<terms:value>)%'`;
const records = await db.any(sql, { terms:  terms.join('|')});
```
