### ISSUE TITLE
Non-blocking streaming with pg-promise

### ISSUE THREAD

**Issue by spimou** [vitaly-t/pg-promise#685]
I am using a node module to connect to an sql database, but when I do streaming, it gets the Node blocking by design. I cannot do a simple GET while its streaming. Streaming has to end, for new requests to work.

I am thinking about changing to PostgreSQL db and using pg-promise to stream. I have used pg-promise in the past, but never did streaming. 

Before I continue, I have to ask : is pg-promise non-blocking while streaming? Also does it give options to pause and resume the stream, in order to process data and not exhaust memory? 

Thank you

**Comment by vitaly-t** [comment]
Please include example of what you are doing, to understand what is blocking.

**Comment by spimou** [comment]
Ok, I am using node v10.16.0 and the [node-mssql](https://github.com/tediousjs/node-mssql) 6.0.1 to connect to an sql DB. 

Here is my code

```
const sql = require('mssql');
const pool = new sql.ConnectionPool(config);
const poolConnect = pool.connect();

const testStream = (ws , id) => {       
    poolConnect.then((pool) => {   
      const request = new sql.Request(pool);
      request.stream = true;   //stream data
      request
      .input('id_param', sql.Int, parseInt(id))
      .query('SELECT * FROM table WHERE id = @id_param ')  

      let rowsToProcess = [];  //save query results pause, proccess them and resume
      let data = [];  //data to send to the client using websockets

      request.on('row', row => {   
        //when a row comes from query, create chunks of 20,pause and process
        rowsToProcess.push(row); 
        if (rowsToProcess.length >= 20) {  
          request.pause();
          processRows();
        } 
      });
  
      request.on('done', () => {      
        //get the last data from query and process
        processRows(); 
        sql.close(); 
      });

      const processRows = () => { 
         console.log('rowsToProcess - ', rowsToProcess.length);
         //process data and send them to client with websockets
          rowsToProcess.forEach((item)=>{ 
                data.push(item.name);   
                data.push(item.surname);   
                data.push(item.age);   
            });    
          ws.send(JSON.stringify({ success:true, message: data }));
          //empty tables to reuse for next chunk and resume to continue
          rowsToProcess = [];
          data = []; 
          request.resume();
      }//processRows 

    }) //poolConnect.then
```

I can stream big amounts of data and I can use pause/resume to process data and not choke the system. 

The problem is that while this code streams data (while I see on my console the `rowsToProcess.length` log ) I can not do any other simple request. Doing a simple GET with Postman will not work unless streaming stops. So this is blocking. Is not asynchronous.

I am asking if pg-promise is non-blocking. In other words if it allows other requests while streaming. 

Also, does it have a pause/resume functionality? 

Thanks

**Comment by vitaly-t** [comment]
This library is non-blocking. Parallel queries can be executed on separate IO-s / connections.

It does not have any pause/resume functionality within the streams.
