### ISSUE TITLE
DB doesn't query when using sql-template-strings

### ISSUE THREAD

**Issue by helloitsm3** [vitaly-t/pg-promise#686]
### Expected behavior
Successfully registered User

### Actual behavior
createUser({email: email@email.com}) >> Error: Option "strings" is not recognized

### Steps to reproduce
```
db.query(
        sql`INSERT INTO users (username, country, email, password) VALUES (${username}, ${country}, ${email}, ${hashedPassword}) RETURNING username, email;`
```
### Environment

* Version of pg-promise: 10.3.1
* OS type (Linux/Windows/Mac): Windows
* Version of Node.js: latest

**Comment by vitaly-t** [comment]
This library does not use template strings, it uses proper query parameters.
