### ISSUE TITLE
Revise driver repackaging

### ISSUE THREAD

**Issue by vitaly-t** [vitaly-t/pg-promise#687]
Revise the latest repackaging of everything in the driver, to see what effect, if any, it may have here.

🔥 🔥 🔥

**Comment by vitaly-t** [comment]
For now, making [10.4.0-beta0](https://github.com/vitaly-t/pg-promise/releases/tag/10.4.0-beta0) available with the latest driver.

**Comment by vitaly-t** [comment]
Many changes are happening in the driver presently. I will revise all the changes when 17.x reaches its end. For now, there's [10.4.0-beta.1](https://github.com/vitaly-t/pg-promise/releases/tag/10.4.0-beta.1) update.

**Comment by vitaly-t** [comment]
While the driver continues to undergo changes that do not inspire confidence, I continue the corresponding updates within versions `10.4.0-beta.x`, with [10.4.0-beta.3](https://github.com/vitaly-t/pg-promise/releases/tag/10.4.0-beta.3) being the latest.

I would urge anyone using it in production to stay away from the beta versions. They can be flimsy, especially in relation to data streaming.

**Comment by vitaly-t** [comment]
After everything, I am beginning ti think that 10.4.0 won't see the light of day, the way it was intended. If anything, it will be v11.0.0 to taking all those humongous changes in the driver, leaving v10 carrying on without updating the driver at all.

**Comment by daveisfera** [comment]
For what my two cents is worth, I'd prefer a version 11 over 10.4 with such big changes

**Comment by vitaly-t** [comment]
@daveisfera It might happen, once the underlying driver settles. For now, it is still undergoing those changes, and those are all available through the beta releases.

**Comment by vitaly-t** [comment]
On second thought, the major breaking changes are coming in v8.0.0 of the driver, so maybe it will be ok to go with 10.4.0 update here, and then with v11.0.0, using v8.0.0 of the driver?...

**Comment by daveisfera** [comment]
Sounds good to me

**Comment by vitaly-t** [comment]
[Release 10.4.0](https://github.com/vitaly-t/pg-promise/releases/tag/10.4.0) concludes this work. Should there be any further problems with the new driver, new issues will be open for that.
