### ISSUE TITLE
Array in query for using with overlap function (&&)

### ISSUE THREAD

**Issue by rogorido** [vitaly-t/pg-promise#690]
I want to execute a query using the overlap function for arrays (&&). Something like this: 
` select * from projects where array['history', 'literature'] && categories;`. (The field categories is text[]). 

Unfortunately I'm not able to create a working parametrized query. I have an array in javascript and I tried the following possibilities passing the array: 

- `SELECT project_id FROM projects WHERE $1 && categories`
- `SELECT project_id FROM projects WHERE array[$1] && categories`
- `SELECT project_id FROM projects WHERE $1:raw && categories`
- `SELECT project_id FROM projects WHERE array[$1:raw] && categories`

I also tried to create an object from the array (`categories = { cats }`) and using then these queries: 

- `SELECT project_id FROM projects WHERE ${categories} && categories`. 
- `SELECT project_id FROM projects WHERE array[${categories}] && categories`. 

But again without success. I'm getting different errors, but in general errors like "(node:81634) UnhandledPromiseRejectionWarning: error: literal de array mal formado: «adultos,literature»" or also "(node:84474) UnhandledPromiseRejectionWarning: TypeError: Invalid Query Result Mask specified.".

What is the correct method to achieve something like this?

I'm using pg-promise 10.3.2 and node 13.5.0.

BTW: thanks for the very useful package.

**Comment by vitaly-t** [comment]
Passing value as is formats it as you expected:
```js
const data = ['history', 'literature'];
await db.any('SELECT project_id FROM projects WHERE $1 && categories', [$1]);
//=> select * from projects where array['history', 'literature'] && categories
```
So what is the issue with that?

**Comment by rogorido** [comment]
thanks for your answer. You're of course right. I forgot to put the square brackets (and was also confused in the cases the array data has only one element...).

Thanks for your help and above all for the package!

**Comment by vitaly-t** [comment]
You're welcome.
