### ISSUE TITLE
jest reports open handlers when connecting with `ssl=true` to a local PostgreSQL (no SSL support), 

### ISSUE THREAD

**Issue by cyrilleverrier** [vitaly-t/pg-promise#694]
### Expected behavior

when testing a connection with `ssl=true` to a local PostgreSQL server (no SSL support), 
`jest` should report OK  

### Actual behavior
when testing a connection with `ssl=true` to a local PostgreSQL server (no SSL support), 
`jest` reports:

```
Jest did not exit one second after the test run has completed.

This usually means that there are asynchronous operations that weren't stopped in your tests. Consider running Jest with `--detectOpenHandles` to troubleshoot this issue.
Done in 61.39s.  
```

### Note

It works fine if the connection string contains:
- correct username and password
- correct username and incorrect password

If fails with :
- correct username and password but with `ssl=true`

### Steps to reproduce

Clone and run minimum test case at:
https://github.com/cyrilleverrier/pgptest

### Environment

* Version of pg-promise: `10.3.5`
* OS type (Linux/Windows/Mac):  `PostgreSQL 9.6.13 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit`
* Version of Node.js: `v13.6.0`

**Comment by vitaly-t** [comment]
This library does not do anything specific to SSL. All specifics would be in the [underlying driver](https://github.com/brianc/node-postgres). Therefore, I suggest trying to chase it there.

**Comment by cyrille-arundo** [comment]
Thank you for your feedback. I created a test case and reported it to the `node-postgres` project:  https://github.com/brianc/node-postgres/issues/2079

**Comment by vitaly-t** [comment]
[Release 10.4.0](https://github.com/vitaly-t/pg-promise/releases/tag/10.4.0) closes this matter, with the fix provided within the driver.

**Comment by cyrille-arundo** [comment]
@vitaly-t Thank you. I verified the fix works well :+1:
