### ISSUE TITLE
error "Segmentation fault (core dumped)" when I add pgNative

### ISSUE THREAD

**Issue by DimaNazdratenko** [vitaly-t/pg-promise#698]
I have some error when I add option {pgNative: true} to initialize pg-promise. When I use node v.8.12.0 all was OK, but when I change it on node v12.15.0 there is a problem.
http://joxi.ru/KAgaxpduX586ym

* Version of pg-promise: 10.4.3
* OS type (Linux/Windows/Mac): Linux
* Version of Node.js: 12.15.0

**Comment by vitaly-t** [comment]
`pg-native` is C++, and needs to be re-built after changing Nodejs version.

**Comment by DimaNazdratenko** [comment]
> `pg-native` is C++, and needs to be re-built after changing Nodejs version. Best is to remove it from `node_modules` folder, and then re-install it.

I do it. I removed node_modules and do npm install when change node version. What interesting when I do npm install on node 8 version and then change on node 12 it working.

**Comment by vitaly-t** [comment]
What error are you getting?

**Comment by DimaNazdratenko** [comment]
> What error are you getting?

http://joxi.ru/KAxlvONc1VakgA

**Comment by vitaly-t** [comment]
Have you tried to delete the entire `node_modules`, and then re-install all?

**Comment by DimaNazdratenko** [comment]
> Have you tried to delete the entire `node_modules`, and then re-install all?

yes. I removed folder node_modules in my project. Then I changed node version and do npm install. And when I start my application this error was happened.

**Comment by vitaly-t** [comment]
I'm not sure what's causing it on your system, you need to research it yourself. See also [this question](https://stackoverflow.com/questions/2346806/what-is-a-segmentation-fault).

This is quite outside the scope here, why `pg-native` refuses to load. And I've never seen that issue before.

**Comment by DimaNazdratenko** [comment]
> I'm not sure what's causing it on your system, you need to research it yourself. See also [this question](https://stackoverflow.com/questions/2346806/what-is-a-segmentation-fault).
> 
> This is quite outside the scope here, why `pg-native` refuses to load. And I've never seen that issue before.

But it happened when I switch ON it in pg-promise. When I switch pgNative to false all is working.

**Comment by vitaly-t** [comment]
When you switch the option on, it tries to load `pg-native`, for some strange reasons.

**Comment by DimaNazdratenko** [comment]
> When you switch the option on, it tries to load `pg-native`, which produces that strange error.

but my method to switch on is normally?
http://joxi.ru/MAjOyKZIxdMxPr

**Comment by DimaNazdratenko** [comment]
> When you switch the option on, it tries to load `pg-native`, which produces that strange error.

Also I discovered that problem was happened FROM node version 10.16.0. On Node version 10.15.3 all is working. 
In description 'pg-native' I found => High performance native bindings between node.js and PostgreSQL via libpq with a simple API.

Then when I opened "libpq" I found this text:
**Note: for Node.js equal or greater to version 10.16.0 you need to have at least OpenSSL 1.1.1 installed.**

Could it be my problem and maybe you could help me decide it?

**Comment by DimaNazdratenko** [comment]
**Updated:** I updated openssl to version 1.1.1 but it still not working. I have no idea how to resolve this :(

**Comment by vitaly-t** [comment]
I'm afraid I cannot help you here. You should ask it against [pg-native](https://github.com/brianc/node-pg-native) project, not this one.

**Comment by DimaNazdratenko** [comment]
> I'm afraid I cannot help you here. You should ask it in [pg-native](https://github.com/brianc/node-pg-native) project, not this one.

but what you mean about use native bindings?
http://joxi.ru/v29BxZocz4EaOA

Could you give example how I need to use pg-native with pg-promise?

**Comment by vitaly-t** [comment]
That does give a perfectly valid example. Why it doesn't work under special Nodejs version, that's another matter, and should be addressed with that library.

**Comment by vitaly-t** [comment]
I'm closing it here, because the issue you are having is really out of scope for this library.

**Comment by DimaNazdratenko** [comment]
> That does give a perfectly valid example. Why it doesn't work under special Nodejs version, that's another matter, and should be addressed with that library.
> 
> And besides, not only that's a third-party library, but it is also one that's known to be flimsy, and with very little support. I would advise, in all fairness, against using it, if you can.

Ok thank you for answers. And the last one question. You told that pg-native not so good, but it gives some performance if I have very load working with postgres. Or this performance not so big? Maybe you know some metrics which show performance with this library and without? Because not I inserted it to project but I am afraid to remove it.

**Comment by vitaly-t** [comment]
It depends on data a lot. There maybe significant difference when dealing with binaries.

But then again, the JavaScript version has been updated many times to catch up, so harder to say when looking at the latest version, takes some bench-marking.
