### ISSUE TITLE
Executing Batch Statements within a Transaction.

### ISSUE THREAD

**Issue by aHumanBeing** [vitaly-t/pg-promise#70]
Hi,  I'm trying to update my db using a forms post action.  I get an error and I need help understanding where I went wrong.
```javascript
var pgp = require('pg-promise')(/*options*/);
var conString = "postgres://blahblahblah/db";
var db = pgp(conString);
...
app.post('/addProviderType', function(req, res, done){
    var obj = {};
    winston.log('debug','add provider type: ' + JSON.stringify(req.body));

    db.tx(function (t) {
        // t = this;
        var queries = [];
        for (var i = 0; i < req.body.providerTypes.length; i++) {
            queries.push(this.any("insert into provider_type(id,active,timestamp,type,provider_id) " +
                    " select nextval ('provider_type_id_seq'),'t',now(),$1,$2 " +
                " where not exists (select * from provider_type where type = $1 and provider_id = $2) returning id",
                [req.body.providerTypes[i], req.body.hproviderid]));
        }
        return this.batch(queries);
    })
        .then(function (data) {
            winston.log('debug',data); // printing transaction result;
            req.body.style = 'success';
            req.body.message = 'Provider type added successfully';
            res.send(req.body);
        })
        .catch(function (error) {
            winston.log('error',error); // printing the error;
            req.body.style = 'error';
            req.body.message = 'Failed to add provider';
            res.send(req.body);
        });
});
```
Results in: 
2015-12-02T16:43:52.960Z - debug: add provider type: {"providerTypes":"1","hproviderid":"22"}
2015-12-02T16:43:52.963Z - error:  TypeError: undefined is not a function

 return this.batch(queries); is where the error is.

**Comment by vitaly-t** [comment]
The only way `this.batch(queries)` would produce error `TypeError: undefined is not a function` is when `this` is not set, but it is set there for sure, and the fact that you use `this` successfully in the previous lines proves that.

Something else is missing, and it is not obvious from the code you provided. Try to narrow the error down to the exact place where the error is being thrown.

**Comment by aHumanBeing** [comment]
The stack points to the pg-promise library. Of course I'll see if there's something else I did:

2015-12-02T21:15:57.652Z - error:  TypeError: undefined is not a function
    at Transaction.<anonymous> (/home/user/IdeaProjects/OASIS/app.js:203:21)
    at invoke (/home/user/IdeaProjects/OASIS/node_modules/pg-promise/lib/index.js:443:29)
    at /home/user/IdeaProjects/OASIS/node_modules/pg-promise/lib/index.js:478:20
    at tryCallOne (/home/user/IdeaProjects/OASIS/node_modules/pg-promise/node_modules/promise/lib/core.js:37:12)
    at /home/user/IdeaProjects/OASIS/node_modules/pg-promise/node_modules/promise/lib/core.js:103:15
    at flush (/home/user/IdeaProjects/OASIS/node_modules/pg-promise/node_modules/promise/node_modules/asap/raw.js:50:29)
    at process._tickCallback (node.js:355:11)

**Comment by vitaly-t** [comment]
I don't know which version of the library you are using, so the code line doesn't tell me anything. Line 443 in the current branch cannot throw such an exception. Try to find the exact line of code that's throwing the error.

**Comment by aHumanBeing** [comment]
It's version 1.7.7.

```javascript
result = ctx.cb.call(obj, obj); // invoking the callback function;
```
of function $transact(ctx, obj)

**Comment by vitaly-t** [comment]
In terms of this library's lifespan, that version is quite ancient! Would you be be able to upgrade to the latest 2.6.4 and see if the issue is there or gone?

**Comment by aHumanBeing** [comment]
Not a problem lol. I'll let you know how it goes.

**Comment by vitaly-t** [comment]
List of breaking changes between 1.x and 2.x: https://github.com/vitaly-t/pg-promise/wiki/2.0-Migration

**Comment by aHumanBeing** [comment]
I believe upgrading helps but I'm struggling to get around a particular issue after modifying the code based on the new library:

```javascript
db.connect()
        .then(function (obj) {
            sco = obj; // save the connection object;
            return sco.query("select count(*) from provider_type p "
            );
        })
        .then(function (obj) {
            recordsTotal = obj[0].count;
            filteredQuery = "select CASE when type = 0 then 'Triage / Screening' " +
                            "when type = 1 then 'Clinical' " +
                            "when type = 2 then 'Prescriber' END as type" +
                            ", active from provider_type p where 1 = 1 ";

            // provider id
            filteredQuery += " and p.provider_id = " + pid;
            filteredQuery += ' order by timestamp desc';
            return sco.query(filteredQuery);
        })
        .then(function (providerTypes) {
            //socket.emit('insuranceProviders', insuranceProviders);
            var returnData = undefined;
            returnData = providerTypes.slice(parseInt(req.query.start),parseInt(req.query.start) + parseInt(req.query.length) + 1);
            if (returnData !== undefined) {
                res.send(JSON.stringify({
                    "draw": parseInt(req.query.draw),
                    "recordsFiltered": providerTypes === undefined ? 0 : providerTypes.length,
                    "recordsTotal": recordsTotal,
                    "data": returnData
                }));
            }
        })
        .catch(function (error) {
            winston.log('error', 'providerTypeData'); // display reason why the call failed;
            winston.log('error', error); // display reason why the call failed;
            res.send(JSON.stringify({
                "draw": parseInt(req.query.draw),
                "recordsFiltered": 0,
                "recordsTotal": 0,
                "data": ''
            }));
        })
        .finally(function () {
            if (sco) {
                sco.done();
            }
        });
```

If I remove the .finally block, I don't get the error but of course I wouldn't do that.

 Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (_http_outgoing.js:335:11)
    at ServerResponse.header (/home/user/IdeaProjects/OASIS/node_modules/express/lib/response.js:700:10)
    at ServerResponse.send (/home/user/IdeaProjects/OASIS/node_modules/express/lib/response.js:154:12)
    at /home/user/IdeaProjects/OASIS/routes/providerTypeData.js:53:21
    at runMicrotasksCallback (node.js:337:7)
    at process._tickCallback (node.js:355:11)

**Comment by vitaly-t** [comment]
Now you are showing an HTTP-related error, which got nothing to do with pg-promise. You will need to figure that out yourself.

Do not use `connect` and `finally` at all, use `task` instead:

```js
function myTask(t) {
    return t.query("select count(*) from provider_type p")
        .then(function () {
            recordsTotal = obj[0].count;
            filteredQuery = "select CASE when type = 0 then 'Triage / Screening' " +
                "when type = 1 then 'Clinical' " +
                "when type = 2 then 'Prescriber' END as type" +
                ", active from provider_type p where 1 = 1 ";

            // provider id
            filteredQuery += " and p.provider_id = " + pid;
            filteredQuery += ' order by timestamp desc';
            return t.query(filteredQuery);
        });
}

db.task(myTask)
    .then(function (providerTypes) {
        //socket.emit('insuranceProviders', insuranceProviders);
        var returnData = undefined;
        returnData = providerTypes.slice(parseInt(req.query.start), parseInt(req.query.start) + parseInt(req.query.length) + 1);
        if (returnData !== undefined) {
            res.send(JSON.stringify({
                "draw": parseInt(req.query.draw),
                "recordsFiltered": providerTypes === undefined ? 0 : providerTypes.length,
                "recordsTotal": recordsTotal,
                "data": returnData
            }));
        }
    })
    .catch(function (error) {
        winston.log('error', 'providerTypeData'); // display reason why the call failed;
        winston.log('error', error); // display reason why the call failed;
        res.send(JSON.stringify({
            "draw": parseInt(req.query.draw),
            "recordsFiltered": 0,
            "recordsTotal": 0,
            "data": ''
        }));
    });
```

**Comment by vitaly-t** [comment]
@aHumanBeing any progress there? I'd like very much to get to the bottom of it :)

**Comment by aHumanBeing** [comment]
What you have provided worked perfect actually, thanks!  I was confused because I saw both tasks and connect mentioned in the docs.  I figured I could still use connect but I suppose not.

**Comment by vitaly-t** [comment]
Both methods should work the same, but tasks were introduced later, making the `connect` approach kind of obsolete, even though it still works. I don't know why it didn't work for you. Something else must have been wrong there.

**Comment by vitaly-t** [comment]
@aHumanBeing I believe the issue is resolved now.
