### ISSUE TITLE
Broken URL referenced in examples

### ISSUE THREAD

**Issue by Mr-Lizard** [vitaly-t/pg-promise#702]
This is referenced at several places in the codebase :

// You can check for all default values in:
// https://github.com/brianc/node-postgres/blob/master/lib/defaults.js

However I believe this URL is no longer valid.  Also, need a DRY-er solution, maybe
a references.txt, then one could say:

// check for all default values in ref [49]

**Comment by Mr-Lizard** [comment]
An example of such a reference is in https://github.com/vitaly-t/pg-promise/blob/master/examples/query.js

Line 24,25.

**Comment by vitaly-t** [comment]
Thanks! The link has been fixed.
