### ISSUE TITLE
How Casting UUID Column in ColumnSet ?

### ISSUE THREAD

**Issue by juliarnasution** [vitaly-t/pg-promise#704]
I'm trying update data using **ColumnSet()** , but always getting  
`error: column "id_urutan" is of type uuid but expression is of type text`.

Yes, I know my `id_urutan` is UUID, but I don't know how to casting `the expression` to UUID.
And when I trying to cast using this code `[{name :'id_urutan',cnd:true, cast:'uuid'},` it get error `cannot cast id_urutan to uuid`

this is my last code for **ColumSet**

    const cs = new dbconfig.pgp.helpers.ColumnSet([{name :'id_urutan',cnd:true, cast:'text'}, 'nomor_ujian_mahasiswa', 'urutan', 'id_station', 'id_tran_sesi_ujian_station'], {table: 'urutan_ujian_mahasiswa'});

thank you.

**Comment by vitaly-t** [comment]
This is an SQL-related issue, how to cast your data, so PostgreSQL can accept it.

You should figure it out by executing a similar query inside pgAdmin. Worst case scenario - ask on StackOverflow. But this is not an issue to be open here.
