### ISSUE TITLE
Customizing Errors

### ISSUE THREAD

**Issue by sulaiman1073** [vitaly-t/pg-promise#705]
I want to customize errors resulting from queries. Right now I'm wrapping the insides of all of my methods with try/catch. At some point I will have nearly a hundred methods across all my repositories, and so would like to avoid unnecessary repetition if possible. Is there a way I could have pg-promise pass any errors it's about to throw to my createDatabaseError function?

```js
// SomeRepository.js

class SomeRepository {
  constructor(db) {
    this.db = db;
  }

  async abc1({ userId }) {
    try {
      return await this.db.none(queries.query1);
    } catch (error) {
      throw createDatabaseError(error);
    }
  }
  async abc2({ userId }) {
    try {
      return await this.db.none(queries.query2);
    } catch (error) {
      throw createDatabaseError(error);
    }
  }
  async abc3({ userId }) {
    try {
      return await this.db.none(queries.query3);
    } catch (error) {
      throw createDatabaseError(error);
    }
  }
}
```
```js
// createDatabaseError.js
const { DatabaseError } = require("./errors");

module.exports = error =>
  new DatabaseError({
    name: error.name,
    message: error.message,
    code: error.code,
    detail: error.detail,
    hint: error.hint,
    position: error.position,
    where: error.where,
    schema: error.schema,
    table: error.table,
    column: error.column,
    dataType: error.dataType,
    constraint: error.constraint,
    result: error.result,
    query: error.query,
    values: error.values,
    received: error.received
  });
```

```js
// DatabaseError.js

class DatabaseError extends Error {
  constructor({
    name,
    message,
    code,
    codeName,
    detail,
    hint,
    position,
    where,
    schema,
    table,
    column,
    dataType,
    constraint,
    result,
    query,
    values,
    received
  }) {
    super(message);
    this.message = message;
    this.name = name || this.constructor.name;
    if (position) this.position = position;
    if (code) {
      this.code = code;
      this.codeName = errorCodes[code];
    }
    if (codeName) this.code = codeName;
    if (detail) this.detail = detail;
    if (hint) this.hint = hint;
    if (position) this.position = position;
    if (where) this.where = where;
    if (schema) this.schema = schema;
    if (table) this.table = table;
    if (column) this.column = column;
    if (dataType) this.dataType = dataType;
    if (constraint) this.constraint = constraint;
    if (result) this.result = result;
    if (query) this.query = query;
    if (values) this.values = values;
    if (received) this.received = received;
    Error.captureStackTrace(this, this.constructor);
  }
}
```

**Comment by vitaly-t** [comment]
What you are doing doesn't look right at all.

Why would you wrap database methods for error handling like that? This is not how this library was meant to be used. Try to explain your way of thinking about this, and then perhaps I will explain where it went wrong :)

**Comment by sulaiman1073** [comment]
Have a services layer with most of the server's logic, and a repositories/DOA layer which services interface with the database through. I wanted to keep the layers separate, such that the services layers would not know about what's happening in the DOA layer, only what it could get from it. So I didn't want to handle query errors in the services layer, except in the few cases where it's appropriate. The other reason I wanted to use this was for better stack traces. Right now, if a query errors out, I can only guess which query was the problem query.

For example:
```
error: column users.usernamex does not exist
      at Connection.parseE (/home/abc/node_modules/pg-promise/node_modules/pg/lib/connection.js:614:13)
      at Connection.parseMessage (/home/abc/node_modules/pg-promise/node_modules/pg/lib/connection.js:413:19)
      at Socket.<anonymous> (/home/abc/node_modules/pg-promise/node_modules/pg/lib/connection.js:129:22)
      at Socket.emit (events.js:210:5)
      at addChunk (_stream_readable.js:308:12)
      at readableAddChunk (_stream_readable.js:289:11)
      at Socket.Readable.push (_stream_readable.js:223:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
    name: 'error',
    length: 170,
    severity: 'ERROR',
    code: '42703',
    detail: undefined,
    hint: 'Perhaps you meant to reference the column "users.username".',
    position: '98',
    internalPosition: undefined,
    internalQuery: undefined,
    where: undefined,
    schema: undefined,
    table: undefined,
    column: undefined,
    dataType: undefined,
    constraint: undefined,
    file: 'parse_relation.c',
    line: '3293',
    routine: 'errorMissingColumn'
  }
```

**Comment by vitaly-t** [comment]
You should not wrap queries into `try->catch` everywhere like that. If they throw an error, it means your system is broken. For that you can provide a generic error handler in the app.

And for query diagnostics, use [pg-monitor], or at the very least - [query] event.

[pg-monitor]:https://github.com/vitaly-t/pg-monitor
[query]:https://vitaly-t.github.io/pg-promise/global.html#event:query

**Comment by sulaiman1073** [comment]
> If they throw an error, it means your system is broken.

What if there's nothing wrong with the queries themselves, but an insertion violated some constraint? The alternative that prevents such errors would require two queries instead of one.
> For that you can provide a generic error handler in the app.

I already am. But when I was not re-throwing errors, the stack track couldn't tell me which query caused the error.
> And for query debugging and diagnostics, use pg-monitor, or at the very least - query event.

I tried logging errors with the error event. It had two problems:
1) Stack trace still doesn't tell me which query caused the error.
2) Can't incorporate it into my logging system. I'm using a logging middleware that logs everything I want to log in one json, when an api request has been serviced or has failed.

**Comment by vitaly-t** [comment]
> an insertion violated some constraint

That means that either your query is wrong, or data in the database.

> The alternative that prevents such errors would require two queries instead of one.

Not true. Those are called upserts, look them up, they are one query.

> the stack track couldn't tell me which query caused the error.

Use the tools for which I provided the links above, and log the queries that error out.

> Stack trace still doesn't tell me which query caused the error.

Event [error] gives you complete error details + the query that caused it. That's how [pg-monitor] can show all those details.

> Can't incorporate it into my logging system.

Follow the advice above. If you still have a particular problem - let me know ;)

[error]:https://vitaly-t.github.io/pg-promise/global.html#event:error
[pg-monitor]:https://github.com/vitaly-t/pg-monitor

**Comment by sulaiman1073** [comment]
> Not true. Those are called upserts, look them up, they are one query.

```sql
CREATE TABLE users (
  id UUID NOT NULL DEFAULT uuid_generate_v4() PRIMARY KEY,
  username CITEXT NOT NULL,
  email CITEXT NOT NULL,
  deleted_at TIMESTAMPTZ
);

CREATE UNIQUE INDEX unique_username ON users (username) WHERE deleted_at IS NULL;
CREATE UNIQUE INDEX unique_email ON users (email) WHERE deleted_at IS NULL;
```

A row in the users table with the username "abc" may or may not exist. If I want to insert new row with that username, I'd have to either:

1) Select from the table and check if the user already exists, then either insert the row or don't.
2) Insert the row into the table. If it turned out the user already exist, query would error out, and I'd handle the error.


> Use the tools for which I provided the links above, and log the queries that error out.

```js
const initOptions = {
  promiseLib: promise,
  error(err, e) {
    console.log("===");
    console.log(err);
    console.log("===");
    console.log(e);
    console.log("===");
  },
  extend(obj, dc) {
    obj.UserRepository = new UserRepository(obj);
  }
};
```
```js
class UserRepository {
  constructor(db) {
    this.db = db;
  }

  async searchUsers({ username }) {
    return this.db.any("SELECT abc", username);
  }
}
```
I know this is a bad query, but I just wanted to show you the stacktrace.

```
===
error: column "abc" does not exist
    at Connection.parseE (/home/***/node_modules/pg-promise/node_modules/pg/lib/connection.js:614:13)
    at Connection.parseMessage (/home/***/node_modules/pg-promise/node_modules/pg/lib/connection.js:413:19)
    at Socket.<anonymous> (/home/***/node_modules/pg-promise/node_modules/pg/lib/connection.js:129:22)
    at Socket.emit (events.js:210:5)
    at addChunk (_stream_readable.js:308:12)
    at readableAddChunk (_stream_readable.js:289:11)
    at Socket.Readable.push (_stream_readable.js:223:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:182:23) {
  name: 'error',
  length: 102,
  severity: 'ERROR',
  code: '42703',
  detail: undefined,
  hint: undefined,
  position: '8',
  internalPosition: undefined,
  internalQuery: undefined,
  where: undefined,
  schema: undefined,
  table: undefined,
  column: undefined,
  dataType: undefined,
  constraint: undefined,
  file: 'parse_relation.c',
  line: '3293',
  routine: 'errorMissingColumn'
}
===
{
  client: Client {
    _events: [Object: null prototype] { error: [Function: onError] },
    _eventsCount: 1,
    _maxListeners: undefined,
    connectionParameters: ConnectionParameters {
      user: 'playnows',
      database: 'playnows',
      port: 5432,
      host: 'localhost',
      binary: false,
      ssl: false,
      client_encoding: '',
      replication: undefined,
      isDomainSocket: false,
      application_name: undefined,
      fallback_application_name: undefined,
      statement_timeout: false,
      idle_in_transaction_session_timeout: false,
      query_timeout: false,
      connect_timeout: 0
    },
    user: 'playnows',
    database: 'playnows',
    port: 5432,
    host: 'localhost',
    replication: undefined,
    _Promise: [Function: Promise],
    _types: TypeOverrides { _types: [Object], text: {}, binary: {} },
    _ending: false,
    _connecting: false,
    _connected: true,
    _connectionError: false,
    _queryable: true,
    connection: Connection {
      _events: [Object: null prototype],
      _eventsCount: 22,
      _maxListeners: undefined,
      stream: [Socket],
      _keepAlive: false,
      _keepAliveInitialDelayMillis: 0,
      lastBuffer: false,
      lastOffset: 0,
      buffer: null,
      offset: 98,
      encoding: 'utf8',
      parsedStatements: {},
      writer: [Object],
      ssl: false,
      _ending: false,
      _mode: 0,
      _emitMessage: false,
      _reader: [Object]
    },
    queryQueue: [],
    binary: false,
    processID: 30837,
    secretKey: -399024827,
    ssl: false,
    _connectionTimeoutMillis: 0,
    serverVersion: '10.12 (Ubuntu 10.12-2.pgdg18.04+1)',
    release: [Function],
    end: [Function],
    activeQuery: null,
    readyForQuery: false,
    hasExecuted: true
  },
  query: 'SELECT abc',
  params: undefined,
  dc: undefined,
  ctx: undefined
}
===

```

**Comment by vitaly-t** [comment]
> I know this is a bad query, but I just wanted to show you the stacktrace.

You should be logging just:

```js
{
    error(err, e) {
        console.log(err.message || err);
        console.log('QUERY:', e.query);
    }
}
```

From those details you should have no problem identifying which query caused the error.

> A row in the users table with the username "abc" may or may not exist. If I want to insert new row with that username, I'd have to either:

> Select from the table and check if the user already exists, then either insert the row or don't.
> Insert the row into the table. If it turned out the user already exist, query would error out, and I'd handle the error.

In the previous message I suggested that you look up what an upsert is, but it looks like you did not.

**Comment by sulaiman1073** [comment]
> In the previous message I suggested that you look up what an upsert is, but it looks like you did not. It is just one query, and quite a simple one, which executes INSERT with ON CONFLICT clause.

My bad, apologies. I thought that you thought that I meant "insert or update", which I didn't. And I had forgot about ON CONFLICT DO NOTHING.

> From those details you should have no problem identifying which query caused the error.

Excellent supplementary info, but would still greatly miss a stacktrace.

When I'm re-throwing the error, I'm getting this:
```
  err: error: column "abc" does not exist
      at module.exports (/home/***/src/helpers/createDatabaseError.js:4:3)
      at UserRepository.searchUsers (/home/***/src/repositories/UserRepository.js:27:13) {
```
`at UserRepository.searchUsers` 
`/UserRepository.js:27:13`

**Comment by vitaly-t** [comment]
> Excellent supplementary info, but would still greatly miss a stacktrace.

That's because you are using the default `Promise`, which is quite basic. Switch over [Bluebird](http://bluebirdjs.com/docs/getting-started.html), which supports [long stack tracing](http://bluebirdjs.com/docs/api/promise.config.html).

**Comment by sulaiman1073** [comment]
I am using Bluebird actually, but have disabled longStackTraces.
```js
promise.config({ longStackTraces: false });
```
http://bluebirdjs.com/docs/api/promise.longstacktraces.html
> Long stack traces imply a substantial performance penalty, around 4-5x for throughput and 0.5x for latency.

bluebird by default disables it for production.

**Comment by vitaly-t** [comment]
Ok, i'm not sure what to reply to this :smile:

**Comment by sulaiman1073** [comment]
I guess. :man_shrugging: 

Thanks for the library, migrated my code to it yesterday. Good stuff. :+1:
