### ISSUE TITLE
Question: Does pg-promise support connection via ssh?

### ISSUE THREAD

**Issue by mariusbob** [vitaly-t/pg-promise#708]
I use Postico to connect to a PostgreSQL database and I connect to it via ssh(check the attached image).
Does pg-promise support this option?

I'm building a Node.JS app which interacts with the database but I need to manually open a ssh connection and do a port-forwarding before connecting to db.
![image](https://user-images.githubusercontent.com/1532570/78041747-c9acbf00-7379-11ea-82b4-fdaa8a5979f5.png)

**Comment by vitaly-t** [comment]
[Why did you re-open this issue here?](https://github.com/brianc/node-postgres/issues/2003).

It is not relevant here, because this library supports exactly what the underlying driver does.
