### ISSUE TITLE
Using Sync Metods in QueryFile

### ISSUE THREAD

**Issue by cyberinvalid** [vitaly-t/pg-promise#709]
Hey @vitaly-t,

First of all, thanks for your library, im new in postgres and it makes my life easier
I looked at class QueryFile and there are sync methods fs.statSync and fs.readFileSync, 
i think this is bad, because it stops main thread, better use callback version or native fs.promises

**Comment by vitaly-t** [comment]
Those are meant to be used during the process start-up only, which makes it irrelevant.

You only load SQL files in when you start the app, and that's it. And if the file changes, they will be re-loaded when in `debug` mode.

**Comment by cyberinvalid** [comment]
Just starting an application is the most important moment and it is wrong to just wait for files from disk. There can also be many such SQL files

**Comment by vitaly-t** [comment]
>  starting an application is the most important moment

Right.
