### ISSUE TITLE
[question] Multitenant application: good way to access multiple databases

### ISSUE THREAD

**Issue by DocBouCou** [vitaly-t/pg-promise#710]
Thank you for your great work. 
I have read through the docs, through some questions of SO (e.g. [https://stackoverflow.com/questions/34382796/where-should-i-initialize-pg-promise](url) ) and, among other things, read these questions : #333 and #662 . 

Here is my problem. I am trying to build a multitenant application, with one database per tenant. On the frontend, I have a SPA. For instance, one user want to save 'some stuff', a fetch post request will be sent to the server, and the server - depending on the session of the user - will ask pg-promise to connect/pool/query to the correct database, and hopefully will save 'some stuff' in the database and finally send the response accordingly to the frontend.

Maybe I missed something, but I am still unsure about the good way to do something like that using pg-promise. 
Should I create a new database object every time a query has to be sent from an user? If I do that, I may end up with many duplicate database(s) object(s). Am I wrong?
So, should I call $pool.end() before I send the response to the frontend? If I do that, it means I will create a new pool/connection object for every request. And, if I understood correctly, this is not good because creating new connection to postgre is an expensive task.
So, what seems best/good to me is to check if the database object I want has already been created (and still exists). Can it be done? If so, how should I do that?
Or maybe I should do something entirely different...?

Cheers,

**Comment by DocBouCou** [comment]
I tried to dig a bit. 
Calling $pool.end() after each query (then create a new database object before each query), definitely makes things slower (a simple one-row-insert get 6.5 times slower according to my test).
So, I will try to check if a database object/pool has been created and still exists. I found $pool.ended and $pool.ending, so I just need to find the good and convenient way to use that. Any idea or example or hint about the way to do that? What would be a good project structure to start?

Thanks,

**Comment by vitaly-t** [comment]
This is quite out of scope here. I would advise that StackOverflow is a better place to ask such questions.

I can only advise that you are making a typical mistake of mixing multiple databases into a multi-tenant architecture. Multi-tenant architecture does not require or imply use of multiple databases, you need only one database, with all users in it.

Supporting multiple databases is a separate task altogether.

**Comment by DocBouCou** [comment]
Thank you for your answer. 
I will see what I can find concerning multi-database support with nodejs/postgre/pg-promise.

**Comment by DocBouCou** [comment]
I have another question, as I am having some other doubts :). 

If, instead of having one database per tenant I try with one schema per tenant. As schemas are within one unique database, I will use the same connection/pool to my database. Thus I should be able to initialize the database connection, once and for all, in its own module file.

Here is my question.
If I do so like below (inspired from your answer in #556 ), using initialization option and database context, will I have as many active/opened pools as schemas/tenants? (I expect at most 2000 tenants)
For instance, should something like that work?

```javascript
const initOptions = {
    schema: (dc) => dc,
};
const pgp = require('pg-promise')(initOptions);

module.exports = function (dc) {
  return pgp(/*connection details*/, dc); //dc is tenant id and schema name
}
```

```javascript
//(...)
const myPgpWithSchema = require('path/to/code/above');

const myschema = myPgpWithSchema(req.session.tenantId);
//(...)
```

Thanks again!

**Comment by vitaly-t** [comment]
It depends on your user architecture. If you want to maintain a separate database scheme for each user, then yes, something like that should work. You then should also use `min` within the connection options, to set the pool size for each user.

That however has some scalability issues again, similar to using multiple databases.

Therefore, a much better approach is as described below...

Each HTTP request is expected to be stamped with the user. You take that user, and execute `SET scheme...` as the first query, and then the query you want. This way you will be able to use just one database object, hence one connection pool, hence proper scalability.

**Comment by DocBouCou** [comment]
Thank you very much for your help, this is definitely what I need! :)

**Comment by vitaly-t** [comment]
@DocBouCou You are welcome!

After a little more thinking, I think there won't be any benefit from a custom task or transaction, you'll be better off using the standard ones, like this:

```ts
await db.task('do-something', async t => {

    // you get pull from the HTTP context:
    const userScheme = 'my_user_scheme';

    // setting the right scheme for the user:
    await t.none('SET search_path TO ${userScheme:name}, public', {userScheme});

    // and then execute all queries here, within the same connection session;

});
```

**Comment by DocBouCou** [comment]
I did a slightly custom task/transaction :) . I initialize the schema in one module, and continue with the other query which can be called from elsewhere: (I did the same with transaction for cases when I do need a transaction)

```javascript
const db = require('./db-connexion'); //where I initialize the connection to the db

module.exports = async function (schemaName, doSomething, param, taskName = 'task_name') {
  return db.task(taskName, async t => {
    await t.none('SET search_path TO ${schemaName:name}', {schemaName});
    const result = await doSomething(t, param);
    return result;
  });
}
```

```javascript
//example of a dosomething function

const PQ = require('pg-promise').ParameterizedQuery;

module.exports = async function(t, param) {
  const add = new PQ(`INSERT (...) RETURNING id`);

  const result1 = await t.one(add, [param.one, param.two, param.three]);
  const result2 = await t.one(add, [param.one, param.two, param.three]);
  const result3 = await t.one(add, [param.one, param.two, param.three]);
  const result4 = await t.one(add, [param.one, param.two, param.three]);
  const result5 = await t.one(add, [param.one, param.two, param.three]);

  return new Promise(function(resolve, reject) {
      resolve([result1, result2, result3, result4, result5]);
  });
}
```

**Comment by vitaly-t** [comment]
Just so, you have so much Promise miss-use in your example...

Instead of

```js
const result = await doSomething(t, param);
return result;
```
you should be doing:

```js
return doSomething(t, param);;
```

Instead of doing multiple add operations:

```js
  const result1 = await t.one(add, [param.one, param.two, param.three]);
  const result2 = await t.one(add, [param.one, param.two, param.three]);
  // etc...
```

you should using a single multi-insert operation, see [this question](https://stackoverflow.com/questions/37300997/multi-row-insert-with-pg-promise).

Instead of doing this:

```js
  return new Promise(function(resolve, reject) {
      resolve([result1, result2, result3, result4, result5]);
  });
```
you should just do this:

```js
return {result1, result2, ...};
```

**Comment by DocBouCou** [comment]
So, good for me that I have shown this code here: we learn from our mistakes, right? ;)
Thanks for having taken the time to answer, I did learn a lot.
