### ISSUE TITLE
Upgrading to v10 throws ssl certificate error

### ISSUE THREAD

**Issue by sophieheb** [vitaly-t/pg-promise#711]
### Expected behavior
Can connect to heroku DATABASE_URL without error

### Actual behavior
Trying to connect to a heroku postgres DATABASE_URL throws a 'self signed certificate error'
Similar to that discussed here: https://github.com/brianc/node-postgres/issues/2009
pg package of which this has a dependency

### Steps to reproduce
Deploy code to heroku with a postgres database add on, or locally try to connect to a heroku postgres string.

### Environment

* Version of pg-promise: V10
* OS type (Linux/Windows/Mac): Mac
* Version of Node.js:12

**Comment by vitaly-t** [comment]
Are you passing in

```json
ssl: {
    rejectUnauthorized: false
  }
```

within the connection details?

**Comment by DiegoRBaquero** [comment]
We have some environments with ssl, some without, passing that option enables ssl, so not a solution for all scenarios

**Comment by vitaly-t** [comment]
I didn't think it was going to break anything. At this point I can only suggest to upgrade the code according to the change, or just use strict-version dependency.

**Comment by DiegoRBaquero** [comment]
For the time being we pinned our dependency. But something that can be done is patching 10.5 to previous driver version (or roll back) and publish 11 with driver@8, allow users to update on their own pace while still receiving patches. If any help is needed, @pagerinc engineers are willing to help.

**Comment by vitaly-t** [comment]
I won't be rolling back the `pg` driver at this point :) v10.5.0 was released 15 day ago, and I wouldn't want to break things further.

**Comment by DiegoRBaquero** [comment]
Well, just keep it in mind for the future. And thanks for being an OSS maintainer :)
