### ISSUE TITLE
Running the same query on multiple databases

### ISSUE THREAD

**Issue by CJxD** [vitaly-t/pg-promise#712]
Hi Vitaly,

I'm attempting to ease the use of the library when it comes to database sharding. In this example, data can be written to multiple Postgres databases for load balancing. When reading data, all databases need to be checked simultaneously.

In order to abstract-away the multiple database reading, there needs to be some modifications to the standard Database object.

I did this in a naive way, manually making a proxy for a Database object (ES6 Proxy doesn't work due to the read-only nature of Database objects) as you can see at the bottom of this issue. It takes multiple Database objects in the constructor, and maps their basic methods (`one`, `many`, etc) to the methods of the proxy.

I was wondering if there's a better way than this, for example, by intercepting the call to `ctx.db.client.query` in order to forward the query to the other databases? I wanted to check the `dc` parameter in the Database constructor, but it doesn't seem to have much documentation.

I'm ignoring the caveat for now that this will mess up any 'order by' or 'group by' effects.

_PgPromiseProxy.js_
```
class PgPromiseProxy {
  constructor(dbs) {
    this.dbs = dbs;
  }

  async none(...args) {
    await Promise.all(this.dbs.map((db) => {
      return db.none(...args);
    }));

    return null;
  }

  async one(...args) {
    const results = await Promise.all(this.dbs.map((db) => {
      return db.oneOrNone(...args);
    }));

    const nonNulls = results.filter(result => result !== null);
    if (nonNulls.length === 0) {
      const err = new pgp.errors.QueryResultError();
      err.message = 'No data returned from the query.';
      err.code = pgp.errors.queryResultErrorCode.noData;
      throw err;
    }
    if (nonNulls.length > 1) {
      const err = new pgp.errors.QueryResultError();
      err.message = 'Multiple rows were not expected.';
      err.code = pgp.errors.queryResultErrorCode.noData;
      throw err;
    }

    return nonNulls[0];
  }

  async oneOrNone(...args) {
    const results = await Promise.all(this.dbs.map((db) => {
      return db.oneOrNone(...args);
    }));

    const nonNulls = results.filter(result => result !== null);
    if (nonNulls.length === 0) {
      return null;
    }
    if (nonNulls.length > 1) {
      const err = new pgp.errors.QueryResultError();
      err.message = 'Multiple rows were not expected.';
      err.code = pgp.errors.queryResultErrorCode.noData;
      throw err;
    }

    return nonNulls[0];
  }

  async many(...args) {
    const results = await Promise.all(this.dbs.map((db) => {
      return db.manyOrNone(...args);
    }));

    const nonNulls = results.filter(result => result !== null);
    if (nonNulls.length === 0) {
      const err = new pgp.errors.QueryResultError();
      err.message = 'No data returned from the query.';
      err.code = pgp.errors.queryResultErrorCode.noData;
      throw err;
    }

    return nonNulls.flat();
  }

  async manyOrNone(...args) {
    const results = await Promise.all(this.dbs.map((db) => {
      return db.manyOrNone(...args);
    }));

    const nonNulls = results.filter(result => result !== null);
    return nonNulls.flat();
  }

  any(...args) {
    return this.manyOrNone(...args);
  }
};
```

**Comment by vitaly-t** [comment]
You just use the right [Database] object, according to which database you need to access, and that's it.

You should not try to wrap existing methods like that's it is a terrible idea that will hinder the performance just as it comes to tasks and transactions.

**Comment by CJxD** [comment]
Selecting the right database object is the clear course for writing, but when it comes to reading, it may either be from a single database, or from all databases at once. In order to avoid the cumbersome task of mapping/reducing the SQL query to all databases at the point-of-use, I was looking for a way to do this without modifying application logic. The idea of sharding should only really exist in the actual implementation of the database.

I don't think it makes sense to extend the Database interface, as doing so would involve changing the names of the functions (I can only imagine something like `oneAllDatabases()`, which wouldn't even make sense if there was only one database in use on a development machine). I hope this makes the notion a bit clearer, and why I am attempting this.

**Comment by vitaly-t** [comment]
It still makes no sense re-implementing methods, and then re-doing their logic for controlling the result and throwing `QueryResultError`.

What would make sense, is re-mapping methods into the list-proxy, while allowing optional in-task and in-transaction execution:

```js
async one(query, args, t) {
    return Promise.all(this.dbs.map(db => (t || db).one(query, args)));
}

async oneOrNone(query, args, t) {
    return Promise.all(this.dbs.map(db => (t || db).oneOrNone(query, args)));
}

// etc.
```
