### ISSUE TITLE
Updating JSONB not working with update helper

### ISSUE THREAD

**Issue by daveisfera** [vitaly-t/pg-promise#714]
### Expected behavior
The method outlined in #560 would work to update a JSONB column with the update helper

### Actual behavior
I get this error:
```
There is a column named \"json_column\" in table \"t\", but it cannot be referenced from this part of the query.
```
And the generated query is:
```
update my_table as t set "json_column"=v."json_column" from (values(1,json_column || '{"number":-1}')) as v("id","json_column") WHERE v."id"=t."id"
```

### Steps to reproduce
Run the following command:
```
const data = [{id: 1, json_column: {number: -1}}];
const cs = new pgp.helpers.columnSet([
    '?id',
    {
        name: 'json_column',
        mod: ':raw',
        init: (c) => `json_column || ${pgp.as.json(c.source.json_column, false)}`,
    }],
    'my_table');
const query = `${pgp.helpers.update(data, cs)} WHERE v."id" = t."id"`;
db.none(query);
```

### Environment

* Version of pg-promise: 10.4.4
* OS type (Linux/Windows/Mac): Alpine 3.11
* Version of Node.js: 12.6.2

**Comment by vitaly-t** [comment]
"Not working" isn't good enough. Please include here what SQL you were expecting to be generated.

**Comment by daveisfera** [comment]
This is the SQL that works:
```
update my_table as t set "json_column"=t."json_column" || v."json_column"::JSONB from (values(1,'{"number":-1}')) as v("id","json_column") WHERE v."id"=t."id"
```

**Comment by vitaly-t** [comment]
Well, this is a step off from the default `UPDATE` logic, which means you cannot use the existing [update] method, and instead create one of your own.

[helpers] namespace already gives you everything.

For example, the most valuable part of the dynamic update is the values, you can generate via [helpers.values]. The rest should be easy.

[helpers]:https://vitaly-t.github.io/pg-promise/helpers.html
[update]:https://vitaly-t.github.io/pg-promise/helpers.html#.update
[helpers.values]:https://vitaly-t.github.io/pg-promise/helpers.html#.values

**Comment by daveisfera** [comment]
For anyone interested, here's what I did:
```
const wheres = flow(
    map((pk) => `v."${pk}"=t."${pk}"`),
    join(' AND '),
)(primaryKey);
const columns = [...map((pk) => `?${pk}`, primaryKey), 'json_column'];
const query =
    `UPDATE my_table AS t ` +
    `SET json_column=t.json_column || v.json_column::JSONB ` +
    `FROM (VALUES${pgp.helpers.makeValues(data, columns)}) ` +
    `AS v(${map((pk) => `"${pk}"`, primaryKey)},json_column) ` +
    `WHERE ${wheres};`;
return db.none(query);
```

**Comment by vitaly-t** [comment]
Updated your own example - changes `makeValues` into `values`, 'cos that's the correct method name.

**Comment by daveisfera** [comment]
Thanks for fixing that.

For the second comment about `columns`, I'm not following. What should be different with the code I sent? Do you mean the list of columns in the `AS v()` part?

**Comment by vitaly-t** [comment]
For example, you used static column assignment with static cast:
```sql
SET json_column=t.json_column || v.json_column::JSONB
```
whereas instead, a generic approach would have been:

```js
const sets = cs.columns.map(c=>`${c.escapedName} = t.${c.escapedName} || v.${c.escapedName}${c.castText}`).join();
```

And then use that with SET:

```js
`SET ${sets} ...`
```

**Comment by daveisfera** [comment]
👍 thanks
