### ISSUE TITLE
queryCallback is not a function

### ISSUE THREAD

**Issue by MikeYermolayev** [vitaly-t/pg-promise#715]
Hi, after I added `query_timeout` to config I constantly receive `queryCallback is not a function` error.
I use stream API:

```
const poolSingleton = pgp({
    connectionString: config.postgresDSN,
    max: config.poolSize,
    query_timeout: config.queryTimeout,
});

const queryStream = (query, onInit) => {
        const queryStream = new QueryStream(toQuery(query));

        return poolSingleton.stream(queryStream, onInit).then((data) => {
            log.info(`Query stream total rows processed: %s`, data.processed);
        });
    }

...

await queryStream(query, (dataStream) => {
    pipeline(
        dataStream.on(`error`, onError),
        JSONStream.stringify(),
        res,
        (err) => {
            if (err) {
                onError(err);
            }
        },
    );
});
```

### Expected behavior
Should not throw with stream API
### Actual behavior
Throw error `queryCallback is not a function`

### Steps to reproduce
 - set query_timeout param in DB config
 - send query using Stream API

### Environment

* Version of pg-promise: 
    "pg-promise": "10.5.0",
    "pg-query-stream": "3.0.4",
* OS type (Linux/Windows/Mac):
    MacOS 10.15.3
* Version of Node.js:
    12.14.1

Thanks in advance!

**Comment by MikeYermolayev** [comment]
FYI: found the root cause https://github.com/brianc/node-postgres/issues/1860

**Comment by vitaly-t** [comment]
That one looks like a keeper.

**Comment by vitaly-t** [comment]
@MikeYermolayev 

So this is a known issue in the dependency - driver, and cannot be addressed from this end.

**Comment by vitaly-t** [comment]
I am closing this issue here, because the corresponding issue in the driver has been open for over a year, without much traction. I do not want to keep issue here open that have no resolution in sight because of the dependency. If there is progress there, we can re-open the issue here.
