### ISSUE TITLE
Enum type array is not converted to array. 

### ISSUE THREAD

**Issue by Virtouzo** [vitaly-t/pg-promise#716]
### Expected behavior
Enum type array on select should be converted to actual array.

Though, if you do something like 

```
SELECT enum_column::text[]
* FROM table;
```

 then the enum array will be returned as array.

### Actual behavior
Returns a string, for example: '{ENUM_VAL1, ENUM_VAL2}'

### Steps to reproduce
Just do a select on a column of enum array type.

### Environment

* Version of pg-promise: 10.5.1
* OS type (Linux/Windows/Mac): Windows 10
* Version of Node.js: 13.7.0

**Comment by vitaly-t** [comment]
This functionality is in the underlying dependencies, is where you should track it.

* [ENUM ARRAY types get parsed as single string](https://github.com/brianc/node-pg-types/issues/56)
* [select an array of enum type](https://github.com/brianc/node-postgres/issues/691)
* and so on.
