### ISSUE TITLE
NodeJS v14 support

### ISSUE THREAD

**Issue by vitaly-t** [vitaly-t/pg-promise#717]
It would appear that some dependencies here have trouble with the newly released NodeJS v14, so it may take some time before this library starts supporting it.

**Comment by vitaly-t** [comment]
See https://github.com/brianc/node-postgres/issues/2170

**Comment by brianc** [comment]
Released a [patch](https://github.com/brianc/node-postgres/pull/2171) for the incompatibility!  Thanks for letting me know. 😄 lmk if you see anything else. 🙏

**Comment by vitaly-t** [comment]
Version [10.5.2](https://github.com/vitaly-t/pg-promise/releases/tag/10.5.2) added support for NodeJS v14.

@brianc Thank you for the patch! 👍
