### ISSUE TITLE
Which is the changelog?

### ISSUE THREAD

**Issue by fundon** [vitaly-t/pg-promise#72]

**Comment by vitaly-t** [comment]
What do you mean? Please provide a description next time.

**Comment by fundon** [comment]
@vitaly-t  I mean that we need a changlog or history file to record changes.

**Comment by fundon** [comment]
Likes https://github.com/nodejs/node/blob/master/CHANGELOG.md https://github.com/npm/npm/blob/master/CHANGELOG.md.

**Comment by vitaly-t** [comment]
Every time I make a new release, I document what has changed. So if you just go through the releases, you will be able to see that.

Beyond that, being a GitHub project, it is easy to see details of each commit.

That's all there is.

**Comment by fundon** [comment]
Yes, I saw the release notes.

But a changelog file that make us clear.

After installed the package, we just need to open the changelog file, `open node_modules/pg-promise/CHANGELOG.md`.

**Comment by fundon** [comment]
> There is also a very abbreviated project history, though it's not much of use.

Okay, I saw.

**Comment by vitaly-t** [comment]
At the moment this project doesn't have a separate changelog like that.
