### ISSUE TITLE
"invalid message" when string contains NUL char code

### ISSUE THREAD

**Issue by evgeni-k** [vitaly-t/pg-promise#720]
### Expected behavior
be able to insert data

### Actual behavior
"invalid message" error is thrown with error code 08P01

### Steps to reproduce
String value contains following record
`"value\0"`

`pgp.helpers.insert(values, columnsSet);`

### Environment

* Version of pg-promise: 10.5.1
* OS type (Linux/Windows/Mac): Mac
* Version of Node.js: 12.6

**Comment by vitaly-t** [comment]
[It is strictly the driver issue](https://github.com/brianc/node-postgres/issues/1115). This library can't, and should not do anything about it.
