### ISSUE TITLE
Formatting query question

### ISSUE THREAD

**Issue by Amp1lfy** [vitaly-t/pg-promise#723]
Hello,

I am wondering how I would write a query that gives me back a response structured like this, have a key contain an array of objects.

[
  data,
  {
    "id": "1",
    "data": [
      {
        "x": "1",
        "y": 2
      },
      {
        "x": "2",
        "y": 2
      }
    ]
  },
  {
    "id": "2",
    "data": [
      {
        "x": "1",
        "y": 12
      }
    ]
  },
  {
    "id": "3",
    "data": [
      {
        "x": "1",
        "y": 21
      },
      {
        "x": "1",
        "y": 30
      }
    ]
  },
  {
    "id": "4",
    "data": [
      {
        "x": "1",
        "y": 50
      }
    ]
  },

Any help would be appreciated or where I can find it in the docs.
Thank you.

**Comment by vitaly-t** [comment]
Please ask questions like these on StackOverflow, properly formatted. This is not the right place.
