### ISSUE TITLE
`Abnormal client.end() call` possibly error caused by pg-pool removing non-idle, idle client

### ISSUE THREAD

**Issue by midgethoen** [vitaly-t/pg-promise#724]
I'v been troubleshooting a weird issue with pg-promise having an `Abnormal client.end() call` error during my automated tests for several hours without much result. 
So, i'm posting this issue early hoping someone can point me in the right direction.

Unfortunately i cant share code to reproduce as the project is quite complex and i havent been able to get the gist of the problem

in my tests i create 2 instances of pg-promise. one as a restricted database user  for the tests and one as root for setting up test conditions.

```js
//pseudo code
let db: any;
export default async function getDb() {
  if (!db) {
    db = pgp(config.POSTGRES_URI);
    db.on;
  }
  return db;
}

let rootDb: any;
export async function getRootDb() {
  if (!rootDb) {
    rootDb = pgp(config.POSTGRES_ROOT_URI);
  }
  return rootDb;
}

```

after each test I truncate a bunch of tables and the aforementioned exception always seems to occur during this operation. however, after which test seems to vary.

so far i'v been able to backtrack the problem to pg-pool removing and 'idle' client which triggers the [client-end-lock](https://github.com/vitaly-t/pg-promise/blob/bb0bea82de67a2d0f86619b871924b90da26c882/lib/connect.js#L122) in pg-promise 

Any information is welcome as i'm looking in to this atm

### Expected behavior
no error

### Actual behavior
throw `Abnormal client.end() call` error

### Steps to reproduce
 unclear

### Environment
 - running in `node:12.16.2` container
 - happens with both `pg-promise@10.5.3` and `pg-promise@10.4.3`
 - happens with both node-postgres and pg-native

**Comment by midgethoen** [comment]
> however, after which test seems to vary.

clarification:
the error consistently occurs after the same test, but which test depends on which tests do run. 
I can also influence this by setting a arbitrary timeout before the tests. which makes sense since the problem seems to be related to pg-pool removing 'idle' clients

**Comment by vitaly-t** [comment]
This means you are running a test that creates a database connection that already exists. You should instead have such tests share the database object, and then there won't be such warning.

Alternatively, if you want complete isolation for each test, you can set a hook at the end of a test file (each test framework allows it), and do `db.$pool.end()` there.

**Comment by midgethoen** [comment]
Thnx for the quick response!

>This means you are running a test that creates a database connection that already exists. You should instead have such tests share the database object, and then there won't be such warning.

so, to be clear. Am i wrong in thinking that i can safely create two separate instances of pg-promise and use them simultaneously?  
in my tests i only ever create the two connections, which i reuse betweem tests.  Ive been working like this without problems for several years. 

as for the other suggestions. complete isolation is not required in my case, but i'd rather not refactor it like that.
Ignoring it during tests is a good option, but id rather not since id like to know about any other regressions that might occur in the future..

I've found that i'm able to work around the problem by setting a high idleTimeout

```js
let db: pgPromise.IMain;
export default async function getDb() {
  if (!db) {
    db = pgp({
      connectionString: config.POSTGRES_URI,
      idleTimeoutMillis: 10e6,
    });
  }
  return db;
}

```

**Comment by vitaly-t** [comment]
> Am i wrong in thinking that i can safely create two separate instances of pg-promise and use them simultaneously?

You can, but you should not, [see this question](https://stackoverflow.com/questions/34382796/where-should-i-initialize-pg-promise).

You can do as you like, of course, I have given you the options to choose from.

**Comment by midgethoen** [comment]
> That is an ugly work-around, IMO, but do as you like.

This is not really helpful without arguments. 

Anyway thanks for the quick help and the awesome library!
Cheers!
