### ISSUE TITLE
Formatting doesn't play well with @> (contains) queries against date/time ranges

### ISSUE THREAD

**Issue by dmfay** [vitaly-t/pg-promise#725]
### Setup

```
CREATE TABLE ranges (
  id SERIAL NOT NULL PRIMARY KEY,
  duration TSTZRANGE
);
```

```
const pgp = require('pg-promise');

(async () => {
  const conn = pgp()({database: 'sandbox'});
  const query = 'SELECT * FROM ranges WHERE duration @> $1';
  const result = await conn.query(query, [new Date()], pgp.queryResult.any);

  console.log(result.length);
})();
```

### What goes wrong

Postgres log:

```
2020-05-13 19:28:59.579 EDT [92952] LOG:  statement: SELECT * FROM ranges WHERE duration @> '2020-05-13T19:28:59.568-04:00'
2020-05-13 19:28:59.580 EDT [92952] ERROR:  malformed range literal: "2020-05-13T19:28:59.568-04:00" at character 40
2020-05-13 19:28:59.580 EDT [92952] DETAIL:  Missing left parenthesis or bracket.
2020-05-13 19:28:59.580 EDT [92952] STATEMENT:  SELECT * FROM ranges WHERE duration @> '2020-05-13T19:28:59.568-04:00'
```
👋 I looked into the code but I'm not sure how you'd want to handle this scenario. `@>` can test both range and scalar values, and if it gets a string rather than (here) a TIMESTAMPTZ it expects the former, e.g. `'[2020-05-13T19:28:59.568-04:00,)'`.

Casting the parameter (`duration @> $1::TIMESTAMPTZ`) does work, but it'd be nice not to have to do that.

**Comment by vitaly-t** [comment]
The purpose of formatting engine is to correctly escape values, according to their type. From your own log, the engine did it correctly, as `'2020-05-13T19:28:59.568-04:00'` is the correct default formatting for the `Date` type.

If you want to change how type `Date` is formatted for you, you can make use of the [Custom Type Formatting] for that.

Handling type casting can only be done on your side, this formatting engine cannot be part of that.

**Comment by dmfay** [comment]
Yeah, the formatter doesn't have enough information to work with and I don't think there's a reasonable way around that. When I tried submitting the query as a `PreparedStatement` I actually got the same error -- node-pg [is converting dates to strings too](https://github.com/brianc/node-postgres/issues/2219).

**Comment by vitaly-t** [comment]
Are you sure that [Custom Type Formatting] can't help you?

You can override globally how `pg-promise` formats `Date` everywhere:

```js
Date.prototype.toPostgres = function() {
    return 'new value';
}
```

or if you want to return a pre-formatted raw string:

```js
Date.prototype.toPostgres = function() {
    return {
        toPostgres: () => `'$1'::typecast` // or you can use pgp.as.format function,
        rawType: true // use result as raw text
    };
}
```

[Custom Type Formatting]:https://github.com/vitaly-t/pg-promise#custom-type-formatting
