### ISSUE TITLE
Lambda + Transaction + task = timeout

### ISSUE THREAD

**Issue by demian85** [vitaly-t/pg-promise#726]
Hello,

I'm not really sure if this is an issue with any of the pg-* modules or something is very wrong with my code, but after spending 48 hours looking into it, I still couldn't come up with a conclusion. I'm having this problem in production right now and no one appears to have a clue what's going on.

To avoid duplicating the question, you can find the details here: https://stackoverflow.com/questions/61898428/lambda-pg-promise-transaction-random-timeout

### Expected behavior
Execute the transaction/task

### Actual behavior
Something keeps waiting and the function times out

### Steps to reproduce
Please check the link above

### Environment

* Version of pg-promise: latest
* OS type (Linux/Windows/Mac): AWS Lambda
* Version of Node.js: 12.x

Thanks for your help.

**Comment by vitaly-t** [comment]
I answered [your question](https://stackoverflow.com/questions/61898428/lambda-pg-promise-transaction-random-timeout) before you even wrote it here. Let's just stick to one place, ok?
