### ISSUE TITLE
Improvement: context for query errors

### ISSUE THREAD

**Issue by elierotenberg** [vitaly-t/pg-promise#728]
On interactive client (e.g. `psql`), when a query contains an error with a known position, the user is prompted with helpful context:

```
> SELECT * FORM 'my_table';
ERROR:  syntax error at or near "FORM"
LINE 1: SELECT * FORM 'my_table';
                 ^
```

However, errors thrown by `pg-protocol`, and therefore by `pg-promise`, only the error string and a `position` is returned, like:

```js
{
  message: 'error: syntax error at or near "FORM"',
  // ...
  position: '9'
}
```

Please note that "context" here is meant as "SQL query context" and not Node stack traces, as this is already covered by other mechanisms (bluebird long stack traces...).

https://github.com/brianc/node-postgres/issues/969 suggests a workaround when using `client.query`, using the numeral position and the prepared query string to extract the line number.

However, when using a `QueryFile`, the prepared `query` can not be accessed directly from the `error` object. It is only possible in the global error handler (`initOptions.onError`).

Skimming through the code it seems like the `query` value is explicitly hidden, making it impossible to produce a context for an error when using a QueryFile: https://github.com/vitaly-t/pg-promise/blob/master/lib/query-file.js#L156

I have implemented a dirty workaround to provide a helpful context string:
```ts
interface IQueryFileError extends Error {
  readonly position?: string;
}

const getLineCol = (
  position: number,
  haystack: string,
): { readonly line: number; readonly column: number } => {
  let line = 0;
  let column = 0;
  for (let k = 0; k < position - 1; k++, column++) {
    const c = haystack.charAt(k);
    if (c === "\n") {
      line++;
      column = 0;
      if (haystack.length > k && haystack.charAt(k) === "\r") {
        k++;
      }
      continue;
    }
  }

  return { line, column };
};

const dangerouslyExtractQueryFileErrorContext = (
  error: IQueryFileError,
  qf: QueryFile,
): null | string => {
  if (!error.position) {
    return null;
  }
  const position = parseInt(error.position);
  const qfString = qf.toString();
  const QUERY_OFFSET_MATCH = `query: "`;
  const queryOffset =
    qfString.indexOf(QUERY_OFFSET_MATCH) + QUERY_OFFSET_MATCH.length;
  const query = qfString.slice(queryOffset);
  const lines = query.split(/\n\r?/);
  const p = getLineCol(position, query);
  const line = lines[p.line];
  return `
${qf.file} L${p.line + 1} C${p.column}:
${line}
${" ".repeat(Math.max(p.column - 1, 0))}^
`;
};

```

For the above example, it would produce the following string:
```
/select.sql L1 C9:
SELECT * FORM 'my_table';
              ^
```

As you can see it calls `qf.toString()` and parses the result to get the actual query... It is probably very brittle and defeats the purpose of hiding `qf._inner.sql` in the first place.

Is there any chance we can implement a helper method, e.g. by adding an optional parameter to `QueryFileError#toString(level, { context: true })`?

I believe the formatting part could belong in the `node-postgres` package family, but we would still need a mechanism to integrate with `QueryFile`.

**Comment by vitaly-t** [comment]
I'm not sure there is enough value in this to warrant a change in the library.

You can add your own error handling, using existing code base:

```ts
const u = require('pg-promise/node_modules/pg-minify/lib/utils');

function getQueryPosition(q: QueryFile, index: number) {
    const query = pgp.QueryFile.prototype[pgp.as.ctf.toPostgres].call(q);
    return u.getIndexPos(query, index);
}
```

And when handling errors:

```ts
catch (err) {
        if (err.position >= 0) {
            console.log('Position:', getQueryPosition(qf, err.position));
        }
    }
```

**Comment by elierotenberg** [comment]
Ok, missed this one 👍 

However `utils` is not exported by `pg-minify` making it kind of dirty to import.
Also `QueryFile.protope[pgp.as.ctf.toPostgres]` is not present in the declaration file, maybe it would be worth adding? I can make a PR for that.

**Comment by vitaly-t** [comment]
> However utils is not exported by `pg-minify` making it kind of dirty to import.
That's an example of work-around for yourself, not meant for general use.

> `QueryFile.protope[pgp.as.ctf.toPostgres]` is not present in the typescript declaration file
Again, it is not meant to be, as it is a hidden extension on the prototype.

> I can make a PR for that.
I do not see the need. It's all just a work-around, not for general use.

**Comment by elierotenberg** [comment]
Ok, I thought it might be useful for better debugging / logging though.

Thanks.

**Comment by vitaly-t** [comment]
Well, one might argue that, for example, this function is so generic, it deserves being in its own module:
https://github.com/vitaly-t/pg-minify/blob/da12e2c24cdafc446deb7efcbdbd5a8d94234267/lib/utils.js#L5

In the end of the day, it is available time versus the end result.

**Comment by elierotenberg** [comment]
I'm sorry to insist on this one but unless I'm wrong neither of our proposed workarounds actually work because the "query" we pull from the `qf` object is before parameter substitution, leading to incorrect position when using parametrized QueryFile with `pgp.QueryFile.prototype[pgp.as.ctf.toPostgres].call(qf)` - the position reported by the error being relative to the actual query after substitution, not the contents of `QueryFile`.

https://github.com/vitaly-t/pg-promise/blob/master/lib/query.js#L70

Parameter substitution for the query actually happens after pulling the interal template string, right before passing it to `ctx.db.client.query`:

https://github.com/vitaly-t/pg-promise/blob/master/lib/query.js#L129

The full `query` is reachable from the global `error` or `query` event handlers provided in `initOptions` (because they get the `ctx` object with the actual query) but not from anywhere in the error stack of `await db.query(qf, values)` because it is not passed to the underlying promise rejection:

https://github.com/vitaly-t/pg-promise/blob/master/lib/query.js#L253

Am I missing something? Is there any chance we could make `ctx` reachable from the local error stack? e.g. by setting `error[pgp.errors.$context] = ctx`?

Thanks for your patience and your help.

**Comment by vitaly-t** [comment]
Are you minifying the query? If so, then you shouldn't.

**Comment by elierotenberg** [comment]
I'm not.

**Comment by vitaly-t** [comment]
It would work as expected, if you were to use prepared statements or parameterized queries. Without them, this library does the query formatting, and separating values from queries within errors.

You could provide your own query method, through extension, and have it store the formatting values, and then provide additional error context. But it all starts to seem like an overkill. So I am beginning to wonder of this all is worth doing at all. You are the first one who asked about it.

**Comment by elierotenberg** [comment]
It would help a lot for debugging! But I guess I'll have to do without it :)
Again, thanks for you amazing work on this lib and your patience on this issue.
