### ISSUE TITLE
could not receive data from client: An existing connection was forcibly closed by the remote host. 

### ISSUE THREAD

**Issue by mehradrishty** [vitaly-t/pg-promise#729]
As far as i understood , the opening and closing of the connections in the db pool is handled automatically by the library. But i am getting an error in the postgres error logs : could not receive data from client: An existing connection was forcibly closed by the remote host. Is it because any of my db connection is left open and is not closed ? How can i handle this because i cannot find any event to close the connection.
Thanks

**Comment by vitaly-t** [comment]
Closing, due to non-response.
