### ISSUE TITLE
Generating dynamic inserts

### ISSUE THREAD

**Issue by aHumanBeing** [vitaly-t/pg-promise#73]
Is there a way to generate inserts dynamically and then run them?  I tried using batch but this created a single insert with specified column as an array.

What I need (may be 1 insert or several):
```
insert into user_location (id,active,timestamp,location_id,provider_id) select nextval ('user_location_id_seq'),'t',now(),$1,$2 
where not exists (select * from user_location where location_id = $1 and provider_id = $2) RETURNING id
```
What was generated (and not what I need):
```
insert into user_location (id,active,timestamp,location_id,provider_id)  select nextval ('user_location_id_seq'),'t',now(),array['2','16'],'22'  where not exists (select * from user_location where location_id = array['2','16'] and provider_id = '22') RETURNING id
```

**Comment by vitaly-t** [comment]
This library doesn't deal in terms of inserts or selects, only in terms of queries, in the most generic way.

Whatever you ask it to execute, the library executes and returns the result, it doesn't offer any logic beyond that.

I don't know what you were expecting that should have been generated, the library provides simple variable formatting, that's all.

>What was generated (and now what I need):

And you showed only one line there,... where is the one that you need?

**Comment by vitaly-t** [comment]
Looks like you are trying to mix up in-server processing with the app formatting, which isn't possible in any library.

**Comment by aHumanBeing** [comment]
I think I'm following.  Basically, I have a select list on the client side and based on the number of options selected, should result in the same amount of records (inserts) generated and executed.

**Comment by aHumanBeing** [comment]
This is what I tried:
``` javascript
function myTask(t) {
        var queries = [];
        stuff.forEach(function (val) {
            queries.push(t.any("insert into user_location (id,active,timestamp,location_id,provider_id) " +
                " select nextval ('user_location_id_seq'),'t',now(),$1,$2 " +
                " where not exists (select * from user_location where location_id = $1 and provider_id = $2) RETURNING id",
                [val, req.body.providerid]));
        });
        return t.batch(queries);
    }
```
...
``` javascript
db.task(myTask)
        .then(function (data) {
})
        .catch(function (error) {
});
```

**Comment by vitaly-t** [comment]
That look fine. Are you saying that `batch` executes only one query? That would only happen if your variable `stuff` contains one element.

**Comment by aHumanBeing** [comment]
Yes it only executes one query.  I'll look again at what I have.

**Comment by aHumanBeing** [comment]
I think it's my fault with the 'stuff' array.  Please disregard.  Sorry.

**Comment by vitaly-t** [comment]
@aHumanBeing not a problem.

On the other note, if you are executing multiple inserts, you may consider doing it as a transaction rather than a task ;)

**Comment by vitaly-t** [comment]
**UPDATE:**
There is lots more the library offers now with the [helpers namespace](http://vitaly-t.github.io/pg-promise/helpers.html) when it comes to automatic query generation for `INSERT` or `UPDATE` operations.
