### ISSUE TITLE
`bigint` unresolved

### ISSUE THREAD

**Issue by SyamSundarKirubakaran** [vitaly-t/pg-promise#730]
<img width="819" alt="sample" src="https://user-images.githubusercontent.com/26897680/83331671-17c83b00-a2b5-11ea-8d10-8a49ffa97b3e.png">

Running `tsc && node build/server.js` throws this error.
Note: I'm using TS 3.8.2 and my code base supports bigint, `"target": "ESNEXT"`
Also installed `@types/pg-promise` as dev dependency. Is there something I'm missing.!?

**Comment by vitaly-t** [comment]
Did you follow [this document](https://github.com/vitaly-t/pg-promise/wiki/BigInt)?

**Comment by SyamSundarKirubakaran** [comment]
Following [this document](https://github.com/vitaly-t/pg-promise/wiki/BigInt) helped. Obviously not a library issue. I just wanted to get my config squared away.! Thanks.!
