### ISSUE TITLE
electron: connect hang on reload

### ISSUE THREAD

**Issue by char101** [vitaly-t/pg-promise#733]
Hi,

So I want to try connecting to postgresql in an electron environment. When electron is launched the application works without problem (i.e. I can get the query results) but when the application is reloaded using electron's `View` -> `Reload` menu the application is stuck when running `db.any` below. When it is reloaded there is an established connection to port 5432 made by electron so it is trying to connect to postgresql but I am not sure why the promise does not resolve.

Also there is no error in the terminal (main process) nor in the browser's console .

### Expected behavior

When using the reload menu on electron I expect a new connection to be made to postgresql.

### Actual behavior

I can see that electron made a new connection to port 5432 when the application is reloaded using the reload menu but the promise (when calling `await db.any`) does not resolve.

### Steps to reproduce

`index.html`
```html
<!doctype html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<title></title>
</head>
<body>
	<div id="app">App</div>
	<script src="script.js"></script>
</body>
</html>
```

`app.js`
```javascript
const pgp = require('pg-promise')();
const db = pgp('postgres://user@host/db');

(async function() {
  console.log('before');
  const result = await db.any('select * from table');
  console.log('after');
  console.log(result, typeof result);
})();
```

### Environment

* Version of pg-promise: 10.5.6 (electron 9.0.4)
* OS type (Linux/Windows/Mac): Windows 10
* Version of Node.js: 14.3.0

**Comment by vitaly-t** [comment]
And where is your error handler? You are missing it completely.

**Comment by char101** [comment]
If you mean the `error` handle option to `pg-promise` I have tried to add it before but there is no error logged. Otherwise any exception should be logged to the browser console of which there is none.

**Comment by char101** [comment]
```javascript
const pgp = require('pg-promise')({
  connect() {
    console.log('connected');
  },
  error(error, e) {
    console.log(error, e);
  },
});
```

When reloaded the `connected` string is logged in the browser console. But the `db.any` promise does not resolve.

**Comment by char101** [comment]
Calling `client.connect` on `node-postgres` also hang on reload so I guess the problem is in the underlying library.

**Comment by char101** [comment]
https://github.com/electron/electron/issues/24126
