### ISSUE TITLE
Clarification on best practice for preventing SQL injection with pg-promise

### ISSUE THREAD

**Issue by csatnic** [vitaly-t/pg-promise#734]
Hi,

I'd like to get some clarification on the best practice for preventing SQL injection when using pg-promise.

In the docs, the only place where I found SQL injection mentioned is in the context of using SQL Names formatting for variable names:

https://github.com/vitaly-t/pg-promise#sql-names

Currently we're storing our queries in external .sql files (using the QueryFile pattern) using this format:

SELECT field1, field2 FROM my_table WHERE id = $[id]

As far as I can tell, this is not exactly the SQL Names approach (or maybe I'm not understanding correctly what SQL Names applies to). We tried to pass some SQL injection string values and it appears that everything passed in as a parameter ends up surrounded by quotes when PostgreSQL executes the query ... so we appear to have some protection as we could not get a SQL injection query to execute and extract data beyond what was allowed.

OWASP guidance says that in general using Parameterized Queries is a way to prevent SQL injection:

https://cheatsheetseries.owasp.org/cheatsheets/SQL_Injection_Prevention_Cheat_Sheet.html

pg-promise does have a ParameterizedQuery class:

http://vitaly-t.github.io/pg-promise/ParameterizedQuery.html

Does it offer any extra protection in terms of SQL injection? (the pg-promise documentation does not specifically mention this topic in the class docs)

We're not currently using ParameterizedQuery ... should we in order to get the best SQL injection protection? Is our QueryFile approach and SQL string format - SELECT field1, field2 FROM my_table WHERE id = $[id] - sufficient or should we use something else?

Thank you.

**Comment by vitaly-t** [comment]
This library implements its own escaping for values, which is safe from SQL injection, while 
`ParameterizedQuery` is doing the same on the server-side. If you opt for the latter, then you won't ve able to use SQL Names or any of the formatting filters.

**Comment by csatnic** [comment]
Would you please consider adding an explanation to the docs of how pg-promise protects against SQL injection - even without using the ParameterizedQuery class for server-side protection? 

OWASP still lists injection as the top security risk in applications ... one of the first things I look at with a new database driver interface is what sort of protection it's giving me and how I have to best use it to take advantage of that.

Thank you.

**Comment by vitaly-t** [comment]
Do not concatenate query values manually, always rely on automatic formatting, and you will avoid SQL injection. That's pretty much the whole idea around SQL injection. How much more extensive do you need?

**Comment by csatnic** [comment]
Ok ... thank you.

**Comment by vitaly-t** [comment]
You are welcome!

It is a common practice when using libraries like this one, to include in your project a very basic test for SQL injection, which should give you a peace of mind.
