### ISSUE TITLE
Property 'spex' does not exist on type 'typeof pgPromise'.

### ISSUE THREAD

**Issue by igorthy** [vitaly-t/pg-promise#737]
Hello,

I'm using the latest pg-promise library.
I was trying to follow the streaming example from **Learn-by-Example** section.
The code below gives typescript error:

> Property 'spex' does not exist on type 'typeof pgPromise'.

```
import Promise from 'bluebird';
import pgp from 'pg-promise';
const options = {
    promiseLib: Promise,
    capSQL: true
};

const cn = 'postgres://testuser:abcdef@127.0.0.1:5433/test_db;
export const db = pgp(options)(cn);
const streamRead = pgp.spex.stream.read; // <--  error here

```

Is it something i'm doing wrong ?

Thank you

**Comment by igorthy** [comment]
Sorry, it was mine Incorrect usage

**Comment by anwarnafa** [comment]
#749
