### ISSUE TITLE
Event loop blocking during db insertion?

### ISSUE THREAD

**Issue by igorthy** [vitaly-t/pg-promise#738]
Hello,

I have a single ts code file written below where I'm reading lines from input file and then inserting groups of 20 rows.
There are around 6000+rows in that file.
Entire operation is wrapped with transaction.
I'm observing some odd behavior...
The transaction takes around second to complete, I see console.log messages appear in terminal.
Then when I would expect the script to exit there is a significant delay for 4-5 seconds and only then the script exits.
I looked on database to see what was happening at the time inserts where done and It seems that it takes time for new rows to arrive specifically  after 'transaction ended' message it took roughly the same time for script delay before exit and final row count to be correct one.

Am I doing something wrong ?
Thanks a lot

```
const columns_def = new pgp.helpers.ColumnSet(['id', 'category', 'subcategory', 'code', 'text'], {table: 'itemlist'});

db.tx(t => {

        function dbSave(objList, enc, cb)
        {
            const sql = pgp.helpers.insert(objList, columns_def);
            t.none(sql)
            .then(data => {
                cb();
            })
            .catch(error => {
                cb(error);
            });
        }
        const dbStream = mississippi.to.obj(dbSave);

        return new Promise((resolve, reject) => {
            mississippi.pipe(
                fs.createReadStream(filePath),
                split2(),
                fileTransform, // custom data transform that returns object with keys according to columns_def ColumnSet
                batch2({size: 20, objectMode: true}),
                dbStream,
                function(err){
                   console.log('finished writing stream');
                    if (err) 
                        reject(err);
                    else
                        resolve();
                }
            );
        });
    })
    .then(value => console.log('transaction ended'))
    .catch(err => {});
```

**Comment by vitaly-t** [comment]
This looks wrong, because your call for `t.none(sql)` isn't chained to the transaction result.

**Comment by igorthy** [comment]
Forgot to mention that I  used pg-monitor to verify that transaction begins and there are so and so inserts and transaction ends.
I'm trying to figure out what's wrong...
As I understand it:
1. **db.tx** is returned a **Promise** which resolves when streaming is done.
The last argument in **pipe** method is callback that invoked when all streams finished.
This is when the above promise is resolved.

2. **mississippi.to.obj(dbSave)** returns write (object) stream that calls **dbSave**.
**dbSave** calls **cb** callback when **t.none(sql)** is resolved to signal it can start process new batch.

I didn't quite get what you mean by:

> t.none(sql) isn't chained to the transaction result

**Comment by igorthy** [comment]
I took the time to rewrite this using **mississippi-promise** library
I agree it is much nicer...but still something is blocking script just before it exists...
It even blocks when the input file is small... 

```
const columns_def = new pgp.helpers.ColumnSet(['id', 'category', 'subcategory', 'code', 'text'], {table: 'itemlist'});

db.tx(t => {

        async function dbSave(objList, enc)
        {
            const sql = pgp.helpers.insert(objList, columns_def);
            await t.none(sql);
        }
        const dbStream = mississippi.to.obj(dbSave);

        return mississippi.pipe(
                fs.createReadStream(filePath),
                split2(),
                fileTransform,
                batch2({size: 20, objectMode: true}),
                dbStream
            );
    })
    .then(value => {})
    .catch(err => {});
```

**Comment by igorthy** [comment]
Even more simplier code still causes a several seconds delay before script exit.
```
db.tx(async t => {
        const items = [
            {id: '1', category: '01', subcategory: '01', code: '0001', text:'text1'},
            {id: '1', category: '01', subcategory: '01', code: '0001', text:'text1'},
            {id: '1', category: '01', subcategory: '01', code: '0001', text:'text1'},
            {id: '1', category: '01', subcategory: '01', code: '0001', text:'text1'},
            {id: '1', category: '01', subcategory: '01', code: '0001', text:'text1'},
            {id: '1', category: '01', subcategory: '01', code: '0001', text:'text1'},
            {id: '1', category: '01', subcategory: '01', code: '0001', text:'text1'},
            {id: '1', category: '01', subcategory: '01', code: '0001', text:'text1'},
            {id: '1', category: '01', subcategory: '01', code: '0001', text:'text1'},
            {id: '1', category: '01', subcategory: '01', code: '0001', text:'text1'},
            {id: '1', category: '01', subcategory: '01', code: '0001', text:'text1'},
            {id: '1', category: '01', subcategory: '01', code: '0001', text:'text1'},
            {id: '1', category: '01', subcategory: '01', code: '0001', text:'text1'},
            {id: '1', category: '01', subcategory: '01', code: '0001', text:'text1'}
         ];

        const sql = pgp.helpers.insert(items, columns_def);
        await t.none(sql);
    }).then(()=>{console.log('done')});
```

**Comment by vitaly-t** [comment]
When you are saying `script` exit, do you mean the transaction exits or the file ends execution?

**Comment by igorthy** [comment]
file ends execution.
I added:
`process.on('exit', () => console.log('exit'))`

When I run script I see almost right away the message:
**done**
then there is a wait of 4-6 seconds and then I see 
**exit**
printed and terminal goes back to prompt

**Comment by vitaly-t** [comment]
In your example, you are not shutting down the connection pool, so a delay is expected then, as per documentation.

**Comment by igorthy** [comment]
Thank you very much, man:):)
Yes, this was the thing
I read really hard all library docs but missed this or forgot about it
Thank you for great support!
