### ISSUE TITLE
Should I get call trees on errors in node v4.2+babel?

### ISSUE THREAD

**Issue by djMax** [vitaly-t/pg-promise#74]
This definitely might not be a problem with pg-promise, but just want to check. I have a bad SQL statement (at this point on purpose, but trying to improve debuggability). Right now the stack on the error has none of my code in it, it's all node and pg code. I thought that promises would normally give more "call tree" type information about where the promise originated. But node 4.2 has native promises, so I'm not sure if somehow that's clashing (and I'm actually using async/await + Babel, so maybe that does too).

**Comment by vitaly-t** [comment]
I don't know what Babel does to the stack tracing, if anything. In my tests when I wanted to see deep stack tracing I used Bluebird for that, which has the best stack tracing, not to mention it is the best promise library all around.
