### ISSUE TITLE
Typing tuple return value from db.task & db.batch

### ISSUE THREAD

**Issue by raine** [vitaly-t/pg-promise#742]
It would be great if `db.task` with `db.batch` inferred types as well as the built-in `Promise.all`, or at least made it possible to pass in type parameters where possible, so that `as` would not have to be used.

```typescript
import pgPromise from 'pg-promise'

export const pgp = pgPromise()

type Db = pgPromise.IBaseProtocol<unknown>
const db = pgp('postgres://localhost:5432/postgres')

const getFoo = (t: Db) =>
  t.one<{ column: number }>('select 1').then((res) => res.column)

const getBar = (t: Db) =>
  t.one<{ column: string }>(`select 'foo'`).then((res) => res.column)

async function main() {
  // https://github.com/microsoft/TypeScript/blob/master/lib/lib.es2015.promise.d.ts#L35-L116
  // Types inferred properly properly:
  const [foo1, bar1] = await Promise.all([getFoo(db), getBar(db)])

  // Typed any:
  const [foo2, bar2] = await db.task((t) => t.batch([getFoo(t), getBar(t)]))

  // Typed but with assertion:
  const [foo3, bar3] = await db.task(
    (t) =>
      (t.batch([getFoo(t), getBar(t)]) as unknown) as Promise<[number, string]>
  )

  // batch() does not take generic type parameters like this but maybe should
  // if full type inference is not possible
  const [foo4, bar4] = await db.task((t) =>
    t.batch<number, string>([getFoo(t), getBar(t)])
  )
}

main()
```

### Environment

* Version of pg-promise: latest
* OS type (Linux/Windows/Mac): mac
* Version of Node.js: 14.2.0

**Comment by vitaly-t** [comment]
For one thing, tasks have always supporyted it:

```ts
await db.task<ReturnType>(t => {
});
```

And for another, `batch` is a legacy that's not really needed today anymore.

**Comment by raine** [comment]
But in your example those are executed sequentially, and not in parallel? Are you suggesting to use `Promise.all` with `db.task` then?

**Comment by vitaly-t** [comment]
That code I showed is not the same as `Promise.all`, it is different, because we are not creating a new promise here, if the previous one fails. That's an important difference.

**Comment by vitaly-t** [comment]
I take it, this is resolved.
