### ISSUE TITLE
Build a pg-promise based on a custom 'pg' module instance

### ISSUE THREAD

**Issue by oguimbal** [vitaly-t/pg-promise#743]
Hi,

I'm building kind of an in-memory postgres database.  ( https://github.com/oguimbal/pg-mem )
It should be useful to anybody (it is to me, at least) who wants to unit test things which access a DB without having to implement endless wrappers for their requests.

I would like to add support to pg-promise like I did for other libs.
The thing is: It seems that you made pretty sure that nobody can mess with your internals. I did not find any way to replace the 'pg' instance used by pgpromise before connecting.

Did I miss something ? Is there a way to build a pg-promise instance based on a custom version of 'pg' ? (i have a simple mock of pg.Client & pg.Pool which sends queries to my in-memory db).

Thanks :)

**Comment by vitaly-t** [comment]
> Is there a way to build a pg-promise instance based on a custom version of 'pg' 

Nope. And it would require a lot of changes to make that possible.

**Comment by oguimbal** [comment]
I think the below snippet would do, if the property was configurable (this throws that the property cannot be redefined).

But i'm not asking you to change your lib for me :) I guess i'll have to implement a mock of your lib then.

Thanks anyway

```typescript
const pgp = require('pg-promise')();
// sadly, I cannot do that (the property is not configurable)
Object.defineProperty(pgp, 'pg', {
    get() {
        return { Pool: something, Client: something };
    }
})
const pdb = pgp({});
```

**Comment by vitaly-t** [comment]
`pg` is set after initialization, and there can be 2 types of objects, one for Javascript Binding, and the other for Native Binding.

**Comment by oguimbal** [comment]
I understand that, but I dont want to interact with 'pg' nor 'pg-native' ... i'm trying to **replace** those by the in-memory version of postgres I built.

FYI [this seems to work](https://github.com/oguimbal/pg-promise/commit/a00a9197fdab029991a7798953699759dc84f7b7) for me 👍 

Anything I am missing ?

I'll use my fork of pg-promise, then.

Thanks, should I close this issue ?

Sample usage:
```javascript
(async () => {
    const db = require('pg-mem').newDb();
    const pg = require ('./lib')({
        customPg: db.adapters.createPg(),
    });
    const con = await pg('whatever');
    await con.connect();
    await con.query('create table test(id text primary key, val jsonb);')
    await con.query(`insert into test values ($1,$2)`, ['a', {data:42}]);
    const got = await con.query('select * from test'); // => i'm OK so far.
})();
```

**Comment by vitaly-t** [comment]
If your project gains sufficient traction in the future, we might revisit it, but for now I wouldn't be making any such change, so yeah, closing it.

**Comment by vitaly-t** [comment]
@oguimbal I have added the commit that you asked for in the beginning, making `pg` modifiable, so you can replace it with a mock. Let me know if you are still interested in this ;)

**Comment by vitaly-t** [comment]
This was published as version `10.8.7`, to let you replace `pg` instance with a mock.

**Comment by vitaly-t** [comment]
@oguimbal You will need to revise [this page](https://github.com/oguimbal/pg-mem/wiki/Libraries-adapters) as well.

And, I would show use of `connect`, this is not how pg-promise is normally used, it manages connections automatically. Use of manual `connect` within the library is a rare use case.

**Comment by vitaly-t** [comment]
@oguimbal Please note that I intentionally did not update the TypeScript declarations for this, because you are not supposed to change `pg` normally, and your case is an exception. And since you are using TypeScript, you will need to re-cast the type into `any`:

```ts
(pgp as any).pg = {}; // replace with a mock-up
```

**Comment by oguimbal** [comment]
Thanks ! I'll update that soon.

**Comment by oguimbal** [comment]
Done.
- `pg-mem@1.6.0`  uses this.
- doc updated

Thanks again :)

**Comment by vitaly-t** [comment]
@oguimbal Excellent! 👍 

Why didn't you just use [semver](https://github.com/npm/node-semver) library? The version check would be just one-liner then.

**Comment by oguimbal** [comment]
I hestitated to do so, but I didnt want to add another needlessly heavy dependency, which will only be used by a fraction of pg-mem users.

**Comment by vitaly-t** [comment]
I had a similar sentiment once, and I wrote a tiny-tiny version of it - [vparse](https://github.com/vitaly-t/vparse).

**Comment by oguimbal** [comment]
Nice, i'll think of it next time 👍 (I must admit i've not searched for a small lib that much)

**Comment by vitaly-t** [comment]
Actually, since your package is for the server-side, I wouldn't bother with the size, and just use `semver` ;)
