### ISSUE TITLE
Create multiple schema, but only one created.

### ISSUE THREAD

**Issue by kangbojk** [vitaly-t/pg-promise#746]
I have a `schema.js` file and use `node schema.js` to create schema for postgresql.

**schema.js**
```
db.none('CREATE TABLE BIG_TABLE();').then(() => {
    console.log('BIG_TABLE schema created');

    db.none('INSERT INTO BIG_TABLE *10000;').then(() => {
        console.log('BIG_TABLE data populated');
    }).catch(err => console.log('Error inserting BIG_TABLE data'));

}).catch(err => {
    console.log('Error creating BIG_TABLE schema', err);
});

db.none('CREATE SMALL_TABLE();').then(() => {
    console.log('SMALL_TABLE schema created');

    db.none('INSERT INTO SMALL_TABLE *10;').then(() => {
        console.log('SMALL_TABLE Data populated');
        pgp.end();
    }).catch(err => console.log('Error inserting SMALL_TABLE data'));

}).catch(err => {
    console.log('Error creating SMALL_TABLE schema', err);
});

```

After successful connection, I use db.none() to run two actions.

First action create a table and insert 10000 rows, which is a relatively slow action.
Second one only insert 10 rows.

### Expected behavior
I expect the two actions both success, but only the first action succeed, second one succeed on creating schema but failed at inserting data.

### Actual behavior

**console log output:**
> BIG_TABLE schema created
> SMALL_TABLE schema created
> Error inserting SMALL_TABLE data
> BIG_TABLE data populated

However, if I change the executing order, inserting data into SMALL_TABLE first, both operation succeed.

**console log output:**
> SMALL_TABLE schema created
> BIG_TABLE schema created
> SMALL_TABLE data populated
> BIG_TABLE data populated

I also tried to use async.series to run these two operations in sequence, but second operation(either insert into small_table or big_table) seemed being skipped.

Could you provide the proper way for creating schema / inserting large data in multiple actions?

Thank you.

### Environment

* Version of pg-promise: 10.5.8
* OS type (Linux/Windows/Mac): Ubuntu server 18.04.4 LTS on VMware
* Version of Node.js: v14.5.0

**Comment by boromisp** [comment]
It would help if you could provide the actual error message, but this is how you can execute async tasks concurrently in Javascript and then do something after the tasks finish.

```js
(async () => {
  await Promise.all([
    db.tx(async (t) => {
      await t.none('CREATE TABLE BIG_TABLE();');         
      console.log('BIG_TABLE schema created'); 
      await t.none('INSERT INTO BIG_TABLE *10000;');
      console.log('BIG_TABLE data populated');     
    }).catch(error => console.error('BIG_TABLE', error)),

    db.tx(async (t) => {
      await t.none('CREATE TABLE SMALL_TABLE();');
      console.log('SMALL_TABLE schema created'); 
      await t.none('INSERT INTO SMALL_TABLE *10;');
      console.log('SMALL_TABLE data populated');
    }).catch(error => console.error('SMALL_TABLE', error)),
  ]);

  pgp.end();
})();

**Comment by vitaly-t** [comment]
@kangbojk You are for some reasons calling `pgp.end();` asynchronously, killing the connection pool. Why would you do that? That's the problem.
