### ISSUE TITLE
THEN function is not working on 'pg-promise'

### ISSUE THREAD

**Issue by msilucifer** [vitaly-t/pg-promise#747]
I want to get the data from PostgreSQL using Node.js.

So I use 'pg-promise' package. But I can't get anything.

```
var pgp = require("pg-promise")( /*options*/ );

var db = pgp("postgres://username:password@localhost:5432/database");

db
    .any('SELECT * FROM mytable')
    .then(function(data) {
        console.log("ABC");
    });
I can't see the output ("ABC") on console(cmd). I am using PostgreSQL 12.0 now.
```

What did I wrong?

### Environment

* Version of pg-promise: 7.3.2
* OS type (Linux/Windows/Mac): Windows
* Version of Node.js: 6.14.5

**Comment by vitaly-t** [comment]
Where's your `catch` handler? You need to read about how to use promises.

**Comment by msilucifer** [comment]
Thanks for your response.
However I inserted catch handler but no error and no output.

**Comment by vitaly-t** [comment]
That's can't be, one or the other would always execute. Perhaps you are not showing the full code here.

**Comment by msilucifer** [comment]
Sorry. I didn't do wrong.
I solved myself.
In windows, it doesn't work but in Linux, it works correctly.
But I want to know the reason. Who can explain it?

**Comment by luisedo97** [comment]
> Sorry. I didn't do wrong.
> I solved myself.
> In windows, it doesn't work but in Linux, it works correctly.
> But I want to know the reason. Who can explain it?

Exactly the same thing happens to me, but in reverse.

**Comment by vitaly-t** [comment]
The original post was for a very old version of the library - 7.3.2, which I wouldn't support anymore.

If it happens when using the latest version of `pg-promise`, then let us know ;)

**Comment by aptuslogic** [comment]
I'm using v9.3.6 and running the following code (basically copied from your example) does not trigger any of the callbacks (error event, .then or .catch).  I've tried a valid connection string and an invalid one.

`	var options = {
	    error: function (error, e) {
	        if (e.cn) {
	            // A connection-related error;
	            console.log("CN:", e.cn);
	            console.log("EVENT:", error.message);
	        }
	    }
	};
	var pgp = require("pg-promise")(options);
	var db = pgp('invalid connection string');
	db.connect()
	    .then(function (obj) {
	        obj.done(); // success, release connection;
	    })
	    .catch(function (error) {
	        console.log("ERROR:", error.message);
	    });
`

**Comment by sriharigr** [comment]
@vitaly-t We are facing a similar issue. _.then()_ nor _.catch()_ gets executed. Did anybody find any resolution? Thanks :)

**Comment by sriharigr** [comment]
Update - We were using v8.5.5 and now after updating to v10.11.1 it is working fine. :)
