### ISSUE TITLE
Error handling will null query statement

### ISSUE THREAD

**Issue by aHumanBeing** [vitaly-t/pg-promise#75]
Considering the code snippet below, if conditions 1 and 2 are false, an error is thrown: Parameter 'query' must be a non-empty text string.

Is there a for the plugin to prevent throwing this error, or is my problem more related to my logic / handling promises?

Thanks

```javascript
function myTask(t) {
                var query;
                if (condition1 === 'true') {
                    query = "select id from table1";
                } else if (condition2 === 'true') {
                    query = "select id from table2";
                }
                return t.query(query)
                .then(function (obj) {
                    if (condition3 === 'true' || condition4 === 'true') {
                        return t.query("select id from table3"
                        );
                    }
                })
                .then(function (obj) {
                    return obj;
                })
            }

db.task(myTask)
                        .then(function (obj) {
})
                        .catch(function (error) {
console.log(error);
                        });
```

**Comment by aHumanBeing** [comment]
Believe I found a solution:
return (condition1 === 'true' || condition2 === 'true' ? t.query(query) : q(undefined))

**Comment by vitaly-t** [comment]
That error can only be thrown if you pass invalid parameter for the query.

>if conditions 1 and 2 are false, an error is thrown: Parameter 'query' must be a non-empty text string.

You are not setting the `query` variable, hence the error. 

I do not know what that `q(undefined)` really does. It depends on what is it you are expecting from the task.

**Comment by aHumanBeing** [comment]
q is from https://github.com/kriskowal/q
A tool for creating and composing asynchronous promises in JavaScript
q(undefined) allows me to create a promise that does nothing really yet allows me to continue with my business logic and not throw an exception if neither condition is true.
