### ISSUE TITLE
Serialization of nested bigint in json(b) results

### ISSUE THREAD

**Issue by Ryu13** [vitaly-t/pg-promise#754]
### Expected behavior
Not exactly sure. After looking through https://github.com/vitaly-t/pg-promise/issues/657 and https://github.com/vitaly-t/pg-promise/wiki/BigInt and given the current state of js with bigint, I suppose I'm looking for a way to ensure any bigint get serialized to String for simplicity. I left the default bigint serializer to string since it's simple and works well-enough minus the json use-case.

Is there a clean way to get json/jsonb (and aggregated e.g. json_agg, jsonb_agg) results such that bigint fields are serialized to a string by pg-promise? I'm trying to avoid manually writing out my queries in a brittle manner (select table1.id::text, table1.item2, table2.id::text as table2_id ...) and would prefer to rely on to_json(table.*) for my more complicated queries where I'd rather just have the entire related object as a nested value.

E.g. I need several different table results around a particular functionality in order to get relevant operation data as well as other data for validation. So simple sample query might be 
```
select to_json(table1.*) as result_json,
   to_json(join_table.*) as result2_json,
   to_json(join_table2.*) as result3_json
left join ... 
from ...
where ... 
etc.
```
but all my nested ids will be serialized to number and my comparison data (for validation) will usually be actual record results (select * from table where ...) and thus be a string. I want a standard mechanism for comparison since just changing this to a loose comparison might as well be a loose comparison everywhere which is not what I want. 

I saw a lot around formatting *for* postgres queries but not a lot *from* postgres results regarding this.

I feel like this can't *really* be done since any necessary information to do a respective cast is lost during json operations by postgres but I'm hoping I'm wrong.

--- 

I suppose I could rework the columns to be named `*_id` and write a custom 114 and 3802 serializer to always convert `id` and `*_id` key values to string versions but I was hoping for a nice clean way to manage this, either in postgres or with this library.

### Actual behavior
int8's are serialized as number regardless of how large they are.

### Steps to reproduce
select any json(b) data such as `to_json(*)`

More complete example:
```
create table fakeTable(id bigint);
insert into fakeTable(id) values (123456789012345678);

db.tx(async t => {
   const query = `select to_json(fakeTable.*) from fakeTable`;
   return t.one(query).catch(...);
});
```

### Environment

* Version of pg-promise: 10.6.2
* OS type (Linux/Windows/Mac): win7/10
* Version of Node.js: 12.18.0

**Comment by vitaly-t** [comment]
I can't quite follow where the actual problem is. In one context you speak of serialization, but then talking about de-serialization issues. Which is is it?

Please reduce your question to what is essential, and add an actual example of what you are doing, the expected + actual results.

**Comment by Ryu13** [comment]
Is there a clean way to get json/jsonb (and aggregated e.g. json_agg, jsonb_agg) results such that bigint fields are converted to a string by pg-promise?

Normally a select will give this as a string when I get them through this lib (If I turn them into BigInt then I need to convert them to string before sending to client anyway) but the json type will have them parsed as 'number'. Now when comparing that json nested id to the record id, strict matches clearly don't work and a loose match here means loose matching everywhere this kind of thing *could* happen and micromanaging those loose comparisons would be exceedingly tedious and ugly.

I offered a possible potential solution to effect what I ultimately need, a consistent method of comparison for my primary key values but I'd like to find something cleaner if possible.

```
I suppose I could rework the columns to be named *_id and write a custom 114 and 3802 transformer to always convert id and *_id key values to string versions but I was hoping for a nice clean way to manage this, either in postgres or with this library.
```

**Comment by vitaly-t** [comment]
This sounds contradictory. You want the library to convert BigInt-s, and leave them as strings at the same time?

I really do not see what yo advise here. Maybe someone else will, if you try asking on StackOverflow.

**Comment by nicholaschiang** [comment]
@vitaly-t I think this is the problem @Ryu13 was describing earlier (that I'm now also encountering):

I have a table `tweets` that has an `id` column that is a `bigint` (or `int8` or whatever you wanna call it):

```pgsql
create table tweets (
  "id" bigint unique not null primary key
);
```

I then use `json_agg(tweets.*)` somewhere in my query and the resulting objects returned by `pg-promise` turn those `tweets.id` columns into JS `numbers` which results in a loss of precision:

```typescript
const rows = await db.any<Tweet>('select json_agg(tweets.*) from tweets group by tweets.id');
console.log(rows[0].id); // This is of type `number` and loses the `bigint` precision.
```

 Instead, `pg-promise` should accurately de-serialize that data into a JS `BigInt` object (i.e. `rows[0].id` should be a `BigInt`).

**Comment by nicholaschiang** [comment]
Here's my current fix:

```typescript
function parseBigInteger(value: string) {
  return BigInt(value);
}

function parseBigIntegerArray(value: string) {
  return array.parse(value, (entry) => parseBigInteger(entry));
}

function parseJson(value: string) {
  /* eslint-disable-next-line @typescript-eslint/no-unsafe-return */
  return JSON.parse(value, (_, val) => {
    if (typeof val === 'number' && !Number.isSafeInteger(val)) 
      return BigInt(val);
    /* eslint-disable-next-line @typescript-eslint/no-unsafe-return */
    return val;
  });
}

function parseJsonArray(value: string) {
  /* eslint-disable-next-line @typescript-eslint/no-unsafe-return */
  return array.parse(value, parseJson);
}

function getPool(): Pool {
  const pgp = pgPromise();
  // Not only do I have to update the type parsers for `int8` but I also have to
  // ensure that JSON `int8` values don't lose precision.
  // @see https://github.com/brianc/node-pg-types/blob/master/lib/textParsers.js#L177-L180
  pgp.pg.types.setTypeParser(20, parseBigInteger);
  pgp.pg.types.setTypeParser(1016, parseBigIntegerArray);
  pgp.pg.types.setTypeParser(114, parseJson);
  pgp.pg.types.setTypeParser(3802, parseJson);
  pgp.pg.types.setTypeParser(199, parseJsonArray);
  pgp.pg.types.setTypeParser(3807, parseJsonArray);
  const pool = pgp(getDatabaseURL());
  return pool;
}
```
