### ISSUE TITLE
use native pg client to create connection

### ISSUE THREAD

**Issue by jefftham** [vitaly-t/pg-promise#755]
I understand that pg-promise is build on top of pg library.
I would like to know to how call pg client to create connection and let pg-promise to use the connection.

I am trying to use AWS RDS Proxy to create the connection directly with pg-promise, but it throws me the error as "Connection terminated unexpectedly".

An alternative method is to use pg client to build connection first.

eg:

```js
const { Client } = require( "pg");
const pgp = require('pg-promise')({ noLocking: true });
const aws = require( "aws-sdk" );


  const token = await getToken(); // get token as password
  const client = new Client({
    host:
      "dev-rds-proxy-tls.proxy-xxxxxxx.ap-southeast-2.rds.amazonaws.com",
    port: 5432,
    ssl: true,
    user: "dev_rds_user",
    database: "master_rds",
    password: token,
  });


const db = pgp( client) // how to use pg client???
```

### Expected behavior
Expected to use pg client for pg-promise

**Comment by vitaly-t** [comment]
> how call pg client to create connection and let pg-promise to use the connection.

Why would you want to do that?

> I am trying to use AWS RDS Proxy to create the connection directly with pg-promise, but it throws me the error as "Connection terminated unexpectedly".

Can you show the code that results in that error?

**Comment by jefftham** [comment]
I understand pg-promise will handle the connection, but it throws error for me.
I have example code to work for native pg client, so i am exploring the possible solution to use RDS proxy for connection.

please refer to this page for example [https://itnext.io/work-with-aws-rds-proxy-9d7e09668080](https://itnext.io/work-with-aws-rds-proxy-9d7e09668080).

Here is how i implement it:-
`
const AWS = require('aws-sdk');
const pg = require('pg-promise')({ noLocking: true });

function getAuthToken({
  hostname ,
  username ,
  region = 'us-east-1',
  port = 5432,
}) {
  const signer = new AWS.RDS.Signer({
    region,
    hostname,
    port,
    username,
  });

function execution(sql, bindParams, method) {
  return function executionHelper(db) {
    return db[method](sql, bindParams);
  };
}

function dbProcess({ sql, bindParams = [], method = 'query' }) {
  return async function dbProcessHelper(cred) {
    const db = pg(cred);

    return db
      .connect({ direct: true })
      .then(execution(sql, bindParams, method))
      .catch(tapError(`Error in execution of postgres query of ${sql}`))
      .finally(db.$pool.end);
  };
}

const event = {
  "sql": "SELECT * FROM $<schema~>.$<table~> WHERE id = $<data.id>",
  "bindParams": {
    "schema": "abcSchema",
    "table": "abcTable",
    "data": {
      "id": "99001f3a-4a13-5cd5-ad58-492f8bac8f80"
    }
  },
  "method": "query"
}

const host = "dev-rds-proxy-tls.proxy-xxxxxxx.ap-southeast-2.rds.amazonaws.com";
const username = "userName"

return Promise.resolve({
    user: username,
    password: getAuthToken({ 
                  hostname : host,
                  username }),
    host,
    database:  "master_rds",
    port: 5432,
    ssl: { rejectUnauthorized: false },
  }).then(dbProcess(event));

`


error:-

{
  "errorType": "Error",
  "errorMessage": "Connection terminated unexpectedly",
  "trace": [
    "Error: Connection terminated unexpectedly",
    "    at Connection.con.once (webpack:///./node_modules/pg/lib/client.js?:252:9)",
    "    at Object.onceWrapper (events.js:286:20)",
    "    at Connection.emit (events.js:198:13)",
    "    at Connection.EventEmitter.emit (domain.js:448:20)",
    "    at TLSSocket.eval (webpack:///./node_modules/pg/lib/connection.js?:131:10)",
    "    at TLSSocket.emit (events.js:203:15)",
    "    at TLSSocket.EventEmitter.emit (domain.js:448:20)",
    "    at endReadableNT (_stream_readable.js:1145:12)",
    "    at process._tickCallback (internal/process/next_tick.js:63:19)"
  ]
}

**Comment by vitaly-t** [comment]
This looks like a connectivity issue with your server. You should check that.

Also, why are you doing `.finally(db.$pool.end)` in your code? You probably shouldn't.

**Comment by jefftham** [comment]
The code work without problem when I use password instead of generate token as password.
I have 2 lambda to proven it. It is not connectivity issue.

Ya, I can change the .finally code

**Comment by vitaly-t** [comment]
Then it is an authentication issue, which is again outside the scope here.

**Comment by jefftham** [comment]
Errrm, you may be right. Let’s close it and open it if needed. Thanks for helping.
