### ISSUE TITLE
Support for Bluebird 2.x discontinued in pg-promise 2.x?

### ISSUE THREAD

**Issue by Maximization** [vitaly-t/pg-promise#76]
While migrating to pg-promise 2.x I noticed that my chained promises would return an undefined error. After some debugging I found out that query methods no longer return promises in combination with Bluebird 2.x. Here's an example of code that would throw an error
```
db.query("select * from users where active=$1", true)
    .then(function (data) {
        return Promise.all([
            data,
            getAsync(data)
        ]);
    })
    .spread(function () {
        // Throws an undefined error at .spread(), never reaches this point
    });
```
I haven't had the time to debug more but before doing that I wanted to ask if support for Bluebird 2.x was discontinued with pg-promise 2.x?

**Comment by vitaly-t** [comment]
This library has no preference or expectations from promise library, and as such it has no dependency on their versions or features.

Only your code can throw an error like that. And i'm guessing something goes wrong inside your `Promise.all` call, possibly inside `getAsync(data)`.

**Comment by Maximization** [comment]
I double checked that the library was initialised with Bluebird. I hadn't made any changes there. I did a console.log of one of the query methods both using Bluebird 2.x and 3.x. Bluebird 3.x would return an unfulfilled Promise and 2.x would return an empty object.

I looked at my Promise.all code and the return object is an unfulfilled Promise. Nothing changed there either. Promise.resolve() would error too as in the following example:
```
db.result(query, values).then(function(result) {
    return Promise.resolve([]);
}).spread(function(result, replies) {
    return res.status(200).end();
}).catch(next);

TypeError: undefined is not a function
        at list (/Users/maxim/Code/backend-v2/server/controllers/news.controller.js:42:6)
```
I use pg-monitor and the error is returned before the query is executed. It seems that db.result immediately returns an empty object which gets populated with the resolved value upon fulfillment.

**Comment by vitaly-t** [comment]
> It seems that db.result immediately returns an empty object which gets populated with the resolved value upon fulfillment.

`db.result` returns a promise immediately, because that's how promises work, they provide data upon fulfillment.

Nothing you described helps to identify the issue. My guess is, it is something very trivial on your side, or else it would have been reported long time ago.

I tried to reproduce the issue in different ways, nothing like this happens.

You can try a replace the call to pgp to a simple promise: `Promise.resolve(data)`, and then chain the rest.

**Comment by vitaly-t** [comment]
Here's a complete test application. Please tell me what do I need to change in it to reproduce the issue:
```js
'use strict';

var promise = require('bluebird'); // v. 2.10.2
var pgpLib = require('pg-promise'); // v. 2.8.5

var options = {
    promiseLib: promise
};

var pgp = pgpLib(options);
var db = pgp('postgres://postgres@localhost/pg_core_test');

db.one("select 123 as value")
    .then(function (data) {
        return promise.all([
            data.value
        ]);
    })
    .spread(function (value) {
        console.log("value:", value);
    });
```

**Comment by Maximization** [comment]
After many hours of debugging I was able to trace the cause of this strange behaviour in my app. I was initialising the pgp library a second time in one of my code files. Here's a reproducible snippet:
```
var Promise = require('bluebird'); // v. 2.10.2
var pgp = require('pg-promise')({ // v. 2.8.5
    promiseLib: Promise
});
var pgp2 = require('pg-promise')();
var db = pgp('postgres://mystyl@localhost/mystyl');

db.result('SELECT 123 AS value').then(function(data) {
  return Promise.all([ data.rows[0].value ]);
}).spread(function(value) {
  console.log('value:', value);
});
```
The reason I was initialising it twice is because I needed one of the conversion helpers, `pgp.as.csv`. I didn't want to export the pgp library on top of the db connection in my db.js file. So instead of this `module.exports = db` have to do something like this:
```
module.exports = {
    db: db,
    pgp: pgp
};
```
That would mean I'll have to change the way I require my db connection in all places of the app. Then I found out that I can have access to the conversion helpers simply by requiring pg-promise, without initialising it.

Another thing learned! Glad I was able to find out the issue. Strangely enough this didn't give me a problem with pg-promise 1.x.

**Comment by Maximization** [comment]
Thank you for your help. I'll close the issue.

**Comment by vitaly-t** [comment]
Glad you have sorted the issue. And yes, all static properties can be found on both the library instance and the initialized instance, which one of the changes introduced in version 2.x, as explained [here]:(https://github.com/vitaly-t/pg-promise/wiki/2.0-Migration#3-queryresult-is-no-longer-global).

See what else changed in the [2.0 Migration](https://github.com/vitaly-t/pg-promise/wiki/2.0-Migration).
