### ISSUE TITLE
Error when using ParameterizedQuery and the $1:csv and $1^ constructs in WHERE

### ISSUE THREAD

**Issue by SakhnoA** [vitaly-t/pg-promise#762]
I can't figure it out. This is an error or I'm using your tool incorrectly.

### Expected behavior
Correct query execution when using ParameterizedQuery and the $1:csv and $1^ constructs in WHERE

### Actual behavior

**1. Make a similar request:**

> let tempArr = await db.any({
>   text: 'SELECT CL.classifier_id_1 as "classifierId", CL.class_id_1 as "classId"\
>       FROM classification_links as CL\
>       WHERE (CL.classifier_id_2, CL.class_id_2) = (20001, 11111200)\
>       ORDER BY CL.classifier_id_1, CL.class_id_1',
>   values: [],
>   rowMode: 'array'
> });

**_Everything is OK_**

**2. Now I'm trying to pass parameters via ($1^), where strParseIds = " 20001, 11111200”**

> tempRowsWithLinks = await db.any({
>     text: 'SELECT CL.classifier_id_1 as "classifierId", CL.class_id_1 as "classId"\
>       FROM classification_links as CL\
>       WHERE (CL.classifier_id_2, CL.class_id_2) = ($1^)\
>       ORDER BY CL.classifier_id_1, CL.class_id_1',
>     values: [strParseIds],
>     rowMode: 'array'
>   }
> );

**_The result is an error (message: syntax error (approximate position: ")"):_**
{
  "length": 149,
  "name": "error",
  "severity": "ОШИБКА",
  "code": "42601",
  "position": "179",
  "file": "scan.l",
  "line": "1149",
  "routine": "scanner_yyerror"
}

**3.  Trying to run the same query, but using ($1: csv) in the condition (parseIds = [20001,11111200]):**

> const ps = new pgp.PreparedStatement({
>   name: 'my-prep-statement',
>   text: 'SELECT CL.classifier_id_1 as "classifierId", CL.class_id_1 as "classId"\
>       FROM classification_links as CL\
>       WHERE (CL.classifier_id_2, CL.class_id_2) = ($1:csv)\
>       ORDER BY CL.classifier_id_1, CL.class_id_1', 
>   values: [parseIds], 
>   rowMode: 'array'
> });
> let aaa = await db.any(ps);

**_The same error, only the text is: "syntax error (approximate position: \":\")"_**

**4. The following request (without using ParameterizedQuery) is executed correctly:**

> await db.any('SELECT CL.classifier_id_1 as "classifierId", CL.class_id_1 as "classId"\
>               FROM classification_links as CL\
>               WHERE (CL.classifier_id_2, CL.class_id_2) = ($1:csv)\
>               ORDER BY CL.classifier_id_1, CL.class_id_1',
>             [parseIds],
>         )

;

### Environment

* Version of pg-promise: 10.7.0
* OS type (Linux/Windows/Mac): Windows 10
* Version of Node.js: 12.18.3

**Comment by vitaly-t** [comment]
See [this question](https://stackoverflow.com/questions/37782423/query-formatting-for-parameterized-queries).
