### ISSUE TITLE
ES7 chaining queries using a map operator

### ISSUE THREAD

**Issue by ralbuquerque95** [vitaly-t/pg-promise#763]
First of all congrats for the awesome lib! I'm currently using it in a new rest API for the first time and I'm amazed. 
I've read the documentation and also took a look at the pg-promise-demo project but now I'm currently having a minor issue with chaining queries using ES7 syntax. 

### Expected behavior
On the code below I have an array that was returned from the previous query and then I try to make another query for each element by using a map operator.

```
list(params: PublisherListParams): any {
        return this.db.task(async (t) => {
            const publishers: Publisher[] = await t.publishers.list({
                limit: params.limit,
                offset: params.offset
            })
            if(params.incSources){
                return publishers.map(async publisher => {
                    publisher.sources = await t.publisherSources.list({
                        publisher_id: +publisher.id
                    })
                })
            }
            return publishers
        })
    }
```

### Actual behavior
The current behavior throws an `Error: Querying against a released or lost connection.`. I've made a little search and I found out that in most of the cases this happens when the connection passed to the task scope is not used. 

### Workaround
I tested to use a for loop and now it works but I'd like to know what am I possibly doing wrong.

Working code:
```
list(params: PublisherListParams): any {
        return this.db.task(async (t) => {
            const publishers: Publisher[] = await t.publishers.list({
                onlyActive: params.onlyActive,
                limit: params.limit,
                offset: params.offset
            })
            if(params.incSources){
                for(let publisher of publishers){
                     publisher.sources = await t.publisherSources.list({
                         publisher_id: +publisher.id,
                     })
                }
            }
            return publishers
        })
    }
```

### Environment

* Version of pg-promise: 10.7.1
* OS type (Linux/Windows/Mac): Linux Min
* Version of Node.js: 14.4.0

**Comment by vitaly-t** [comment]
This line is wrong:

```js
return publishers.map
```

It is not really waited on, and so the inner `await` queries are trying to resolve after the task has completed, hence the error.

**Comment by ralbuquerque95** [comment]
Thank you for the assistance!

**Comment by vitaly-t** [comment]
You are welcome!

b.t.w. I do not understand why people write code like this:

```js
{
                onlyActive: params.onlyActive,
                limit: params.limit,
                offset: params.offset
            }
```
when simply passing in `params` will have the same effect.

**Comment by ralbuquerque95** [comment]
Thanks for the feedback!
I originally did it because params had more information than actually needed for the function. Though by that perspective, It doesn't matter cause it will only use what it might need
