### ISSUE TITLE
Is there a way to use transactions without a callback?

### ISSUE THREAD

**Issue by LordZardeck** [vitaly-t/pg-promise#767]
I mis-understood documentation and thought that using async/await, I could just do `const tx = await db.tx()`. This is actually what'd I'd much rather prefer than to needing a callback. I avoid callbacks as much as possible as they are IMO very dirty and hard to read, especially the more you need. Is there _any_ way to get a reference to the transaction without a callback? This is what I had and what I wish I could do:

```js
async asTransaction(...args) {
    const transaction = await this.db.tx();
    return [transaction, ...args.map(source => new source(transaction))];
}
```

Is there a way to accomplish this? Or am I stuck with callbacks?

**Comment by vitaly-t** [comment]
You are missing the point completely. The callback is what makes the transaction logic possible. It acquires a connection from the pool before the callback, lets you execute all queries against that context, and once the callback has finished, it automatically executes `COMMIT` / `ROLLBACK` based on the result of the callback, and then releases the connection back to the pool.

**Comment by vitaly-t** [comment]
I take it that settles it, so closing.
