### ISSUE TITLE
Not able connect to postgres server configured with scram-sha-256 authentication

### ISSUE THREAD

**Issue by manojbsw** [vitaly-t/pg-promise#768]
### Expected behavior
pg-promise client must connect to posgres server configured with scram-sha-256 authentication method

### Actual behavior
Getting below error while connecting.
_2020-12-16 12:40:47.622 - error: uncaughtException: Unknown authenticationOk message typeMessage { name: 'authenticationOk', length: 23 }
Error: Unknown authenticationOk message typeMessage { name: 'authenticationOk', length: 23 } ï¿½ï¿½ï¿½ at Connection.parseR (/opt/<some_path>/node_modules/pg/lib/connection.js:442:9)
ï¿½ï¿½ï¿½ at Connection.parseMessage (/opt/<some_path>/node_modules/pg/lib/connection.js:358:19)
ï¿½ï¿½ï¿½ at Socket.<anonymous> (/opt/<some_path>/node_modules/pg/lib/connection.js:119:22)_

### Steps to reproduce
1. Install/Configure postgres db server configured with scram-sha-256 authentication method 
2. Try to initialize the connection with connection string having required credentials.

### Environment

* Version of pg-promise: 10.6.1
* OS type (Linux/Windows/Mac): Linux
* Version of Node.js: v12.15.0

**Comment by vitaly-t** [comment]
Looks like a very old issue in the underlying driver, see [#1508](https://github.com/brianc/node-postgres/issues/1508). It was fixed awhile ago, just update to the latest version of 'pg-promise', and it should be fine.

**Comment by manojbsw** [comment]
@vitaly-t  Thanks for your quick reply,  So from [1508](https://github.com/brianc/node-postgres/issues/1508) it looks pg-promise don't support scram-sha-256. Please let me know if I am wrong here.

**Comment by vitaly-t** [comment]
@manojbsw Have you updated to the latest version? It should have been fixed by now.

**Comment by vitaly-t** [comment]
I'm not expecting any traction on this presently, and since it is a non-issue within this library, closing it, at least for now.

**Comment by Afoxcute** [comment]
> Looks like a very old issue in the underlying driver, see [#1508](https://github.com/brianc/node-postgres/issues/1508). It was fixed awhile ago. Update to the latest version of `pg-promise`, and it should be fine.

i updated pg-promise but I am still getting the same error

**Comment by vitaly-t** [comment]
Sometimes update doesn't go through well. Check `console.log(db.$config.version)` to make sure ;) Best is to delete and then install again ;)

**Comment by Afoxcute** [comment]
> Sometimes update doesn't go through well. Check `console.log(db.$config.version)` to make sure ;) Best is to delete and then install again ;)

Sorry, best is to delete what?
