### ISSUE TITLE
How to fail a transaction when update affected 0 rows

### ISSUE THREAD

**Issue by dorongrinstein** [vitaly-t/pg-promise#77]
When updating one table and inserting into another table in the context of a transaction (for example when the update is the main operation and the insert is into an audit table), I'd like the transaction to fail if the update affected zero rows. I can detect zero row update using .result, but I don't know how to do that in the context of a transaction. thanks.

**Comment by vitaly-t** [comment]
```js
db.tx(t=> {
        return t.result("UPDATE table bla-bla")
            .then(result=> {
                if (!result.rowCount) {
                    throw new Error("Ops, not updated anything!");
                }
            });
    })
    .catch(error=> {
        // error.message = "Ops, not updated anything!";
    });
```

**Comment by dorongrinstein** [comment]
amazing response time. THANK YOU!!!

**Comment by vitaly-t** [comment]
You are welcome, and I have updated the answer for completeness ;)

**Comment by dorongrinstein** [comment]
sorry, one more question -- can this be rolled into a batch (multiple part) transaction?

**Comment by vitaly-t** [comment]
Any query can be part of a batch. Can you give an example of what you mean exactly?

**Comment by vitaly-t** [comment]
If you mean something like this, then certainly:
```js
db.tx(t=> {
        var updates = [];
        for (var i = 0; i < 100; i++) {
            updates.push(t.result("UPDATE table bla-bla")
                .then(result=> {
                    if (!result.rowCount) {
                        // 1. throw new Error("Ops, not updated anything!");
                        // 2. return Promise.reject("Ops, not updated anything!");
                    }
                }));
        }
        return t.batch(updates);
    })
    .catch(error=> {
        // 1. error.message = "Ops, not updated anything!";
        // 2. error = "Ops, not updated anything!";
    });
```

**Comment by dorongrinstein** [comment]
var r = db.tx(function(t) {
            t.batch([
                t.none('update foo set field1 = ${f1} where id = ${id}, {f1: 10, id: 1}),
                t.one("insert into foo_audit values ('1', 'abc')")
            ]);
        });

I want the transaction to fail if the update did not affect any rows. thanks

**Comment by vitaly-t** [comment]
Doesn't my example above show exactly that?

**Comment by dorongrinstein** [comment]
I'll check into it in a few. In a meeting now. THANK YOU again for the super prompt response!

**Comment by vitaly-t** [comment]
n.p.

**Comment by dorongrinstein** [comment]
I see what you did there. Perfect! thank you!!

**Comment by dorongrinstein** [comment]
You are a genius!! When you visit L.A., ping me, I owe you a beer!

**Comment by vitaly-t** [comment]
>You are a genius!! When you visit L.A., ping me, I owe you a beer!

If i'm there next time, it will be Florida. Other than that I'm in Dublin, Ireland, the beer is good here too :)

Cheers! :+1:
