### ISSUE TITLE
Support for multi-query files?

### ISSUE THREAD

**Issue by LJNeon** [vitaly-t/pg-promise#770]
I'd rather not have hundreds of `.sql` files for every query, most of which are under 5 lines. It seems much cleaner to group them into 5-10 files based on their use. Would there be any way to do this with the existing `QueryFile`? And if not, would you be willing to add this? I figure it'd be easy to check if a file has multiple queries (they'd all end with a `;`?) and parse into an array of queries accordingly.

**Comment by vitaly-t** [comment]
That functionality has always been there. There is [helpers.concat] to join queries, and there is method [multi] to get multi-query results.

[helpers.concat]:http://vitaly-t.github.io/pg-promise/helpers.html#.concat
[multi]:http://vitaly-t.github.io/pg-promise/Database.html#multi

**Comment by LJNeon** [comment]
Those don't seem useful, as I still wish to execute queries individually. I just wish to use 5-10 `.sql` files to store the queries instead of hundreds.

**Comment by vitaly-t** [comment]
You want to pile queries into one file and then process queries individually nonetheless? This would not make any sense.

**Comment by LJNeon** [comment]
I have over 100 individual queries, what makes no sense from business logic and maintenance PoV is that many separate `.sql` files. Even if organized by folders it's too much. Sorting them into a handful of files based on their use makes it immensely more maintainable. I'm not sure exactly what exactly you mean by business logic in this case, but if I had to guess then I would say it's much easier for a team to work with queries they haven't written themselves this way as well. It's much easier to scroll through a file than it is to dig through folders and subfolders which each contain dozens of files. Comments can be used to add additional information as well.

**Comment by vitaly-t** [comment]
> if I had to guess then I would say it's much easier for a team to work with queries they haven't written themselves this way as well

What works for a team best is to work with all queries in isolation. And this is also best for testing those.

> It's much easier to scroll through a file than it is to dig through folders and subfolders which each contain dozens of files

I would argue the exact opposite. Not only it is much easier to maintain when queries are inside individual files, but the structure this way is also coherent with the code that's using it - one file -> one query -> one reference -> one query method -> one class method (model/business).

**Comment by vitaly-t** [comment]
I'm sorry to say this, but you are digging in the wrong direction, against the principles of isolation and reusability.

I won't be spending any more time arguing about it, I'll spare the time and tell you that you won't find any support for this within this library. Therefore, I am closing this issue.

**Comment by LJNeon** [comment]
> but you are digging in the wrong direction, against the principles of code isolation and reusability.

To be more accurate, I appear to be digging in an opposing direction of your personal principles. You appear to be taking code isolation to an extreme, and I can only agree with moderate application of it. And my code is actually immensely reusable, as will be explained below. I can understand your will to "agree to disagree", but I figure if others ever read this they might be interested, so I'll make a final reply as well.

> What works for a team best is to work with all queries in isolation. And this is also best for testing those. ... it is much easier to maintain when queries are inside individual files

I think it'll be easier to show what I mean with an example,
```toml
[guilds]
select = 'SELECT {0} FROM guilds WHERE id = $1'
update = 'UPDATE guilds SET {0} WHERE id = $1'
insert = 'INSERT INTO guilds({0}) VALUES({1})'
upsert = 'INSERT INTO guilds({0}) VALUES({1}) ON CONFLICT(id) DO UPDATE SET {1}'
prefixes = 'SELECT id, prefix FROM guilds WHERE prefix != NULL'
resetting = '''
SELECT id, roles FROM guilds WHERE resetEvery != 0
  AND current_timestamp() >= resetLast + make_interval(months => resetEvery)
'''
```
This is much easier to maintain and work with compared to a `guilds` subfolder containing 6 files (and I cut out a fair amount of queries from this to avoid a pointlessly large comment). Every table has the generic `select`/`update`/`insert`/etc queries and then specialized queries below, which allows for significant reuse of code for every table. This is also easy to test, as you only need to iterate through each table and try out `select` for a single unit test.

**Comment by vitaly-t** [comment]
The fact that such an idea comes up here for the first time in project's 6-year history should be reassuring that what you are looking for isn't of much value to anybody else. Everyone else is happy with the isolated query approach. I won't be considering this for the feature. If you want it, you will have to implement this on your side, somehow, I can't help you there.

**Comment by vitaly-t** [comment]
Renamed the issue, because this library perfectly supports multi-query files. It is keeping individual queries inside the same file isn't supported, because that's not even SQL syntax, that's something entirely out of scope here.
