### ISSUE TITLE
Question: Combine template-engine with pg-promise for complex queries

### ISSUE THREAD

**Issue by mikicho** [vitaly-t/pg-promise#772]
Few of my queries are complex and dynamic, with query builder it would be like.
In a query builder it'd be like this:
```js
function getPosts(user) {
  const isAdmin = user.isAdmin;
 
  const query = knex.select('*').from('t');
  if (!isAdmin) {
    query.join('permissions'...);
    query.select(['t.*', 'permissions.action']);
  } else { 
    query.select(['t.*', `permissions.action as 'write'`]);
  }

  return await query;
}
```

Now, I know this is a common question ([example](https://stackoverflow.com/questions/57808220/possible-to-add-dynamic-where-clause-with-a-queryfile)).
but I'm wondering if anyone considered to integrate a template-engine with pg-promise instead of string concatenation or the almost static queryfiles.

With template engine (i.e mustache) it will look like that:
```
select t.*, {{#isAdmin}} permissions.action as 'write' {{/isAdmin}} {{^isAdmin}} permissions.action {{/isAdmin}} from t
{{^isAdmin}} join permissions on ... {{/isAdmin}}
```

WDYT? anyone tried it?
Maybe the "almost static" query files capabilities are just fine?

* Version of pg-promise: 10.8.7

**Comment by vitaly-t** [comment]
Query files are dynamic, they are not static. They support any kind of variables, including the ones that you implement via [Custom Type Formatting], and you can even use variables as references to other SQL files, for nested query files.

This gives you all the tools needed for implementing any template engine you want. But such an engine would never part of this library, this library only works with SQL, apart from the [helpers].

[Custom Type Formatting]:https://github.com/vitaly-t/pg-promise#custom-type-formatting
[helpers]:http://vitaly-t.github.io/pg-promise/helpers.html

**Comment by mikicho** [comment]
@vitaly-t Thanks for the quick response!
Can you please give me a small example?
Also, I see this question all over the internet. maybe we should improve our docs in this area? this is pretty high-demand capability and maybe we should be more detailed about it.
Thanks a lot!

**Comment by vitaly-t** [comment]
Example of what - a query engine? I do not write any query engines in addition to what pg-promise does, that's out of scope here.

If you have a specific question, then just ask.

**Comment by mikicho** [comment]
@vitaly-t no.. how to create/construct complex queries the `pg-promise` way.

**Comment by vitaly-t** [comment]
`pg-promise` doesn't really advocate its own way, at least not in general, only for some specific cases. I'm sorry, your question sounds just too generic. It usually takes to try and implement it, and if you have an issue, then you can ask about it.

**Comment by mikicho** [comment]
I'll thanks!

**Comment by mikicho** [comment]
@vitaly-t 
Ok, I created an example of a somewhat complex query.

```
function getComments(filters, isAdmin, overflow) {
    const { version, userId } = filters;

    let condition = '';
    if (!isProjectAdmin) {
      condition = pgp.as.format(`and permissions.version ${exactVersion ? '=' : '>'} $/version/`, { version });
    }

    let queryLimit = '';
    if (!overflow) {
      queryLimit = pgp.as.format('limit $/limit/', { limit });
    }

    let join = '';
    if (!isAdmin) {
      join = pgp.as.format('join permissions on permissions."userId" = users.id and "userId"=$/userId/', { userId });
    }

    let groupBy = '';
    if (!isAdmin) {
      groupBy = pgp.as.format('group by comments.id');
    }

    let select = '';
    if (isAdmin) {
      select = pgp.as.format(`comments.version as "maxVersion", 'write' as permission`);
    } else {
      select = pgp.as.format(`
       permissions."userAction",
        greatest (max(permissions.version) , comments.version ) as "maxVersion"
      `)
    }

    const results = await this.db.manyOrNone(`
      select comments.*, $/select:raw/ from comments
      join posts on posts.id=commnets."postId"
      join users on users.id=posts."userId"
      $/join:raw/
      where (comments.version > $/version/ $/condition:raw/)
      $/groupBy:raw/
      order by "maxVersion"
      $/queryLimit:raw/
    `, { version, condition, queryLimit, select, join, groupBy });

    console.log(results);
}
```

Is there a more elegant way to do construct this query?
Thanks

**Comment by vitaly-t** [comment]
If this code is not reusable, then it is basically it.

If it is reusable, you can implement reusable helpers instead...

*example:* adding `limit` clause:

```js
const limit = step => ({
    rawType: true,
    toPostgres: () => typeof step === 'number' ? pgp.format('LIMIT $1', step) : ''
});
```

Then you replace with `$/queryLimit:raw/` with `$/limit/`, passing it `{limit: limit(123)}`.

And similar stuff for the rest of it.

**Comment by mikicho** [comment]
Thanks!
I've couple of best-practice questions about joins, but I'll open new issues to make it easier to other developers to find them.
