### ISSUE TITLE
Simple update numeric col is set to null

### ISSUE THREAD

**Issue by jubarbie** [vitaly-t/pg-promise#773]
This is the first time I report an issue, I might not do it the right way. I'll try to be as precise as possible.

I have a table with an 'id' and a 'cost' column. I want to update the 'cost' that has a numeric type:
`await db.none('UPDATE product_variants SET cost=$2 WHERE id=$1', [id, cost]);`

But for some reasons I ignore, on some lines it sets the cost to null.

### Expected behavior
The column I wanna set must have the given value, not null.

### Actual behavior
The column is set to null on some lines.
I tried parsing the value to float but without effect.
I also tried generating the query with helper functions:
`const condition = pgp.as.format(' WHERE id = ${id}', data);`
`const query = pgp.helpers.update(data, ['cost'], 'product_variants') + condition;`
`await db.any(query);`
Still not working.

I also printed the generated query to be sure it was correct... and it was.
The most mysterious thing to me is that if I copy/paste the query on pgAdmin it works ! So the problem doesn't come from it.
And it is not that the query isn't applied because if the column had a value before, it will turn to null... 

### Steps to reproduce
This only seems to happen on my production server.
I can't reproduce it locally

### Environment

* Version of pg-promise: 10.4.4
* OS type (Linux/Windows/Mac): Amazon Linux
* Version of Node.js: 8.11.3

**Comment by vitaly-t** [comment]
Handle event [query], log the event, and see when it doesn't work.

Most likely the error is on your side somewhere.

[query]:http://vitaly-t.github.io/pg-promise/global.html#event:query

**Comment by jubarbie** [comment]
I did log the query, it seems ok. And if I copy/paste it to pgAdmin it works. So the query seems to be ok.
`UPDATE "product_variants" SET "cost"=11.28 WHERE id = 123`

I don't get any errors, and I can tell the query is executed because the column value changes.

**Comment by vitaly-t** [comment]
So what's the problem then?

**Comment by jubarbie** [comment]
I pass a number and it sets null

**Comment by vitaly-t** [comment]
That cannot be. Something you are missing.

**Comment by jubarbie** [comment]
It is !

**Comment by jubarbie** [comment]
Just tried to log using the query event. This is what I get (I just edited the id for security reason):
`QUERY: UPDATE "product_variants" SET "cost"='11.27' WHERE shopify_inventory_item_id = 123`
And in my db the value is null.

I know this seems very weird, I really can't understand what's going on.
I'm using pg-promise for few years and I've never faced this issue.

I'll continue invastigating

**Comment by vitaly-t** [comment]
Why `cost` is a string `'11.27'` and not a number?

**Comment by jubarbie** [comment]
I told you I tried to parse it to a float and it doesn't work either.

**Comment by vitaly-t** [comment]
If you run this query from pgAdmin, and get the same result, then the issue is on your side, it is not related to this library.

**Comment by jubarbie** [comment]
When I run this query to pgAdmin it works.

**Comment by vitaly-t** [comment]
This doesn't make much sense, why would it work differently. Try append `RETURNING *` to your query, execute it via `db.any`, see what data you get back.

**Comment by jubarbie** [comment]
Ok now with the `RETURNING *` it worked. Don't know why though

**Comment by vitaly-t** [comment]
That doesn't sound right. The `RETURNING *` clause is what the server returns, as a confirmation of the updated rows. It cannot return one thing, and then do the other, unless you have some triggers there that mess things up.

Anyhow, I don't know what else to suggest, you need to look into that on your side.

**Comment by jubarbie** [comment]
I have no triggers, and you saw my function, very simple.

Thanks anyway
