### ISSUE TITLE
Monkey-patched connect does not return promise

### ISSUE THREAD

**Issue by ThomWright** [vitaly-t/pg-promise#777]
### Expected behavior

`const promise = client.connect()` returns a promise.

### Actual behavior

The promise gets swallowed by `pg-promise` monkey-patching the connect function. I get unhandled rejections when connections fail.

Here: 

```js
pg.Client.prototype.connect = function () {
    const handler = msg => {
        if (msg.parameterName === `server_version`) {
            this.serverVersion = msg.parameterValue;
            this.connection.removeListener(`parameterStatus`, handler);
        }
    };
    this.connection.on(`parameterStatus`, handler);
    originalClientConnect.call(this, ...arguments); // <-- this should return!
};
```

### Steps to reproduce

As above.

### Environment

* Version of pg-promise: 10.8.7
* OS type (Linux/Windows/Mac): Linux
* Version of Node.js: 12.19.1
* Version of pg: 8.5.1

**Comment by vitaly-t** [comment]
That's quite an old code at this point. Interesting that it would have never come up till now...

Did you have an actual issue with this? It was never reported before...

**Comment by ThomWright** [comment]
Yes! I'm also surprised. There's the obvious problem that `await client.connect()` returns immediately, but how we spotted this was that any errors in connecting weren't being caught, giving us unhandled rejections.

**Comment by vitaly-t** [comment]
That makes sense, what doesn't however is that nobody reported it so far.

Anyhow, good catch, I have commit the fix, and will release the update shortly ;)

**Comment by vitaly-t** [comment]
Fixed and released in version 10.9.2 ;)

**Comment by ThomWright** [comment]
Speedy work, thanks.

**Comment by ThomWright** [comment]
Thinking about it, I wonder if while connecting `pg` internally queues any commands (queries, end, etc.) until after the connection is established. It would kind of hide the fact that this wasn't working properly.

**Comment by vitaly-t** [comment]
My thinking was that it wouldn't come up unless you're having connectivity issues. That would explain why the occurrence is so rare, nobody reported it before.

**Comment by luthv** [comment]
I encountered this problem as well when running my app with Apple new M1 chip, the app ran perfectly well with other machine before. Thanks for the great work in finding the cause.
