### ISSUE TITLE
"Open values" (`:value`) formatting filter usage and documentation issues

### ISSUE THREAD

**Issue by jmm** [vitaly-t/pg-promise#778]
Hello,

The documentation for the ["Open Values" (`:value`) formatting filter](https://github.com/vitaly-t/pg-promise/blob/983c2f5a4bc94f9f9347bd06ac363785a09a0c78/README.md#open-values) ends up noting that it's unsafe.

It's also confusing because because A) it starts out saying the value will be escaped, which implies safety, but ends up noting that it's unsafe; and B) it references trailing quotes when it really means enclosing quotes, right?

It's also unnecessary for what it identifies as the primary use case. It says:

> Open values are primarily to be able to compose complete `LIKE`/`ILIKE` dynamic statements in external SQL files, without having to generate them in the code.

And gives these examples of alternatives:

```js
const name = 'John';
const filter = '%' + name + '%';
```

```sql
SELECT * FROM table WHERE name LIKE '%$1:value%')
```

But neither of those approaches is necessary, because you can do:

```sql
SELECT * FROM table WHERE name LIKE CONCAT('%', $1, '%')
```

Considering that it's unsafe, the documentation is confusing, and it's unnecessary, would it not be better to just steer people to a simpler and safe alternative?

**Comment by vitaly-t** [comment]
It is unsafe, because missing enclosing quotes means you can pass in a whole query, as a value, which can open the query to SQL injection.

**Comment by jmm** [comment]
Yes, so since it's unsafe, the documentation is confusing, and it's unnecessary, it seems like it would be a good idea to deprecate that and leave a note in the documentation that the use case is better solved via regular SQL and value interpolation, as illustrated in my example. Do you agree?

Is there some other use case for it that's really compelling? And in comparison to explicitly escaping the value and interpolating it as raw content?

**Comment by vitaly-t** [comment]
Filter `:value` is there mostly to let you easily compose external SQL files that combine complex strings with simple external values. It is a convenience feature to avoid polluting code with static strings that make up a final string in combination with a dynamic value.

**Comment by vitaly-t** [comment]
I take it, this has been answered.
