### ISSUE TITLE
Invalid sql name

### ISSUE THREAD

**Issue by prostgles** [vitaly-t/pg-promise#780]
Thanks a lot Vitaly for developing this library!

After running into a bug and consulting the [documentation](https://vitaly-t.github.io/pg-promise/formatting.html#.name) it looks like `~`, `:name` and `:alias` argument formatting options will do some form of content checking and will return unwanted results for numbers or "*" or other user provided/imported values.

For a more strict approach I propose we add another formatting option (maybe `:identifier` or `:sqlname`) that will only fail when the  `input.toString()` returns an empty string. Otherwise it returns the escaped `input.toString()`.

### Expected behavior
Stable sql name formatting

### Actual behavior
sql name invalid

### Steps to reproduce
`pgp.as.format("$1:name", [333])`

### Environment

* Version of pg-promise:
* OS type (Linux/Windows/Mac):
* Version of Node.js:

**Comment by vitaly-t** [comment]
> and will return unwanted results for numbers or "*" or other user provided/imported values

Can you provide examples of the issues you are having?

**Comment by prostgles** [comment]
Our system uses introspection to allow users to query their data. The system breaks and/or bypasses CRUD security rules when a table or column is named `*` or `  * ` due to the way `:name` works.  Both these values are valid otherwise (but not recommended of course).

The `pgp.as.format("$1:name", [333])` is a much smaller issue which we can skip for now (or bolt onto this one with `.toString()`).

We can manage these cases with some refactoring on our side but maybe such a feature will help other users of pg-promise dealing with dynamic queries. This way we have a secure formatting option that will always return a single double quoted identifier.

Thank you for such a quick reply!

**Comment by vitaly-t** [comment]
> The system breaks and/or bypasses CRUD security rules when a table or column is named * or * (wrapped in spaces)

Breaks how? I don't get it. Asterix isn't supposed to be escaped. What did you expect to happen for `*` as column?

Can you provide examples for your use cases?

> maybe such a feature will help other users of pg-promise dealing with dynamic queries

This is the first time I hear of an issue with the `:name` filter that you refer to, so I don't know who those others would be.

> is a much smaller issue which we can skip for now

I still do not understand how this is an issue, since a number is not a valid SQL identifier.

**Comment by prostgles** [comment]
The following is a list of queries that work on postgres 11.2

```sql
DROP TABLE IF EXISTS "*";
CREATE TABLE "*" (t TEXT, "333" INTEGER, "*" INTEGER);
INSERT INTO "*" ("*") VALUES(12);

SELECT "333", "*", * FROM "*";
```
We do not plan to create such tables/columns but we want to reduce extra defensive coding required to maintain the system reliability when running into such a case.

**Comment by prostgles** [comment]
This means that dynamically generated queries (from user imported data for example) will break:

```ts
const table = "*";

await db.any(SELECT * FROM $1:name, table);
```

**Comment by vitaly-t** [comment]
So, your use cases are basically about situations that nobody in his right mind would ever try, because trying to create a table or column with name `*` or a number just doesn't make any sense.

For this - `await db.any("SELECT * FROM $1:name", table);` just use `:alias` then:

```js
await db.any("SELECT * FROM $1:alias", table);
```

**Comment by vitaly-t** [comment]
The bottom line, if you do not like how some filter works - you can use [Custom Type Formatting]() to create any prefix you want for your values-parameters.

**Comment by prostgles** [comment]
Alias fails for `"my.column"` but it seems this whole issue is too specific for our case so we'll refactor on our end. 

Thanks a lot for helping us out!

**Comment by vitaly-t** [comment]
> Alias fails for "my.column"

The filter works as expected, and as documented. You have an odd test case - you either treat dots as separators, or treat them as just a letter, but you cannot do both at the same time. So you use the filter according to that. Otherwise, you can use your own formatter as I showed in the example above.
