### ISSUE TITLE
How to close connection without destroying pool.

### ISSUE THREAD

**Issue by kingram6865** [vitaly-t/pg-promise#781]
### Expected behavior
After query is completed, close connection without destroying pool

### Actual behavior
"UnhandledPromiseRejectionWarning: Error: Connection pool of the database object has been destroyed."
OR
(node:1103) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [Bus]. Use emitter.setMaxListeners() to increase limit

### Steps to reproduce
db.$pool.end()
OR do not execute this commannd

### Environment
Node

* Version of pg-promise: 10.9.5
* OS type (Linux/Windows/Mac): Linux
* Version of Node.js: v12.11.1

I'm not used to this module. Switched over from postgres.
Used to executing db.end() after each query

**Comment by vitaly-t** [comment]
> Used to executing db.end() after each query

That's not how one uses that library. You are trying to re-apply invalid use of that library here.

You are supposed to release the connection back into the pool, not to try close it.

**Comment by kingram6865** [comment]
> > Used to executing db.end() after each query
> 
> That's not how one uses that library. You are trying to re-apply invalid use of that library here.
> 
> You are supposed to release the connection back into the pool, not to try close it.

Ok. So what is the proper syntax to release the pool?

**Comment by vitaly-t** [comment]
> I'm not clear on how to use the disconnect syntax here.

There is no disconnect syntax, this library manages connections automatically.

> It would be helpful to have a clear example of usage.

* [This project has tons of those, if you try to look around](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example).
* [And so does StackOverflow](https://stackoverflow.com/questions/tagged/pg-promise)
