### ISSUE TITLE
get and format geojson

### ISSUE THREAD

**Issue by npltr62** [vitaly-t/pg-promise#783]
### Expected behavior
i expect to have geojson data like below
> {"type":"FeatureCollection","features":[{"type":"Feature","geometry":{
### Actual behavior
`function get_ctxt_geojson(req, res, next) {
    db.any('select ST_AsGeoJSON(ctxt_geojson.*)::json as features from pdpg.ctxt_geojson')
        .then(function (data) {
            res.status(200)
                .json({
                    type: "FeatureCollection",
                    features: data
                });
        })`
the result is
> {"type":"FeatureCollection","features":[{"features":{"type":"Feature","geometry":{

what should i do to avoid the features column?

### Environment

* Version of pg-promise:10.9.1
* OS type (Linux/Windows/Mac): Windows
* Version of Node.js: 14.15.1

**Comment by vitaly-t** [comment]
This library does not change data returned from the [underlying driver](https://github.com/brianc/node-postgres). And besides, your question looks totally SQL-related, and not for this library at all.
