### ISSUE TITLE
[Question] Suggestion for implementing Bulk "insert or update"

### ISSUE THREAD

**Issue by fluxquantum** [vitaly-t/pg-promise#787]
### Expected behavior
Able to run a db.<query> using a "query" template for merge statements.

### Actual behavior
pg promise helpers only support only inserts or only updates. Not an insert or update (merge / upsert).

### Steps to reproduce
No specific feature bug, would just like guidance on best approach i.e. If there's a way to do this with prepared statements and helpers.

### Environment

* Version of pg-promise: 10.10.2
* OS type (Linux/Windows/Mac): Mac
* Version of Node.js: 10.12.0

**Comment by vitaly-t** [comment]
> pg promise helpers only support only inserts or only updates. Not an insert or update (merge / upsert).

Have you even researched this? There are plenty of upsert examples on StackOverflow.

**Comment by fluxquantum** [comment]
@vitaly-t I was looking to see if there was something along the lines of an explicit upserts feature in the lib. But I think I can follow the strategy discussed here https://github.com/vitaly-t/pg-promise/issues/245 and similarly https://stackoverflow.com/questions/63327528/insert-on-conflict-do-update-using-pg-promise-helpers-for-multi-row-insert-updat. Thanks, appreciate your time.

**Comment by vitaly-t** [comment]
That's one is a good example, yes.
