### ISSUE TITLE
update helper converts undefined to null

### ISSUE THREAD

**Issue by mikicho** [vitaly-t/pg-promise#789]
Maybe this is by design but:

### Expected behavior
Ignore undefined values

### Actual behavior
convert undefined values to null

### Steps to reproduce
pgp.helpers.update({ name: undefined }, null, 'my-table');
//=> UPDATE "my-table" SET "name"=null;

### Environment

* Version of pg-promise: 10.8.7
* OS type (Linux/Windows/Mac): Mac
* Version of Node.js: 14.15.1

**Comment by vitaly-t** [comment]
It is by design, both `null` and `undefined` are formatted as `NULL`.

**Comment by vitaly-t** [comment]
If you use full syntax, with the column-set, you can skip those properties automatically, using [skip](http://vitaly-t.github.io/pg-promise/helpers.Column.html) option, which works for single-row updates.

```ts
const skipUndefCol = name => ({name, skip: c => c.value === undefined});

const cs = new pgp.helpers.ColumnSet([
    skipUndefCol('first'),
    skipUndefCol('second'),
    skipUndefCol('third')
], {table: 'my-table'});

const data = {
    first: undefined,
    second: 123,
    third: 'message'
};

const query = pgp.helpers.update(data, cs);
//=> UPDATE "my-table" SET "second"=123,"third"='message'
```

**Comment by mikicho** [comment]
Thanks!
IMHO, undefined should be ignored by default, but maybe I don't see the whole picture.
This is my solution:
```
pgp.helpers.update({ first, ...(second && { second }) }, undefined, 'my-table')
```

**Comment by vitaly-t** [comment]
> IMHO, undefined should be ignored by default, but maybe I don't see the whole picture.

Yes, you don't. All those query helpers were primarily created for multi-row updates and inserts, SQL syntax for which does not permit any skip logic, i.e. once you've defined a column within SQL, the value is always there, it cannot be skipped.
