### ISSUE TITLE
pgp does not accept connection string

### ISSUE THREAD

**Issue by RichardJECooke** [vitaly-t/pg-promise#79]
Hi, the [documentation](https://github.com/vitaly-t/pg-promise#connecting) says I should be able to say 
```
var db = pgp("postgres://usernabase...");
```
but the code gives me the the error shown in the screenshot below. It looks like connection strings are never accepted, only objects.  Is the documentation wrong or am I missing something trivial?

![untitled](https://cloud.githubusercontent.com/assets/5468805/12329012/e9ba76ca-bae6-11e5-84ee-e9219087390a.png)

**Comment by vitaly-t** [comment]
Duplacate of #39
