### ISSUE TITLE
How to ensure that servername is set (SNI) for logging, proxies, and egress controls

### ISSUE THREAD

**Issue by jschaftenaar** [vitaly-t/pg-promise#790]
### Expected behavior
passing in servername to the ssl object upon connection to set the sni. 

### Actual behavior
The tls connection does not seem to be made with the sni.

### Steps to reproduce
const config = {
  host: 'someserver.test.com',
  port: 12345,
  ssl: { ca: someCACertFile, servername:'someserver.test.com' }
};
const db = pgp(config);

### Environment
* Version of pg-promise:  "version": "10.10.2",
* OS type (Linux/Windows/Mac): Mac
* Version of Node.js: 14

The documentation mentions https://github.com/vitaly-t/pg-promise/wiki/Connection-Syntax the connection syntax which indicates anything from https://nodejs.org/api/tls.html#tls_tls_connect_options_callback can be passed. Hopefully it is as simple as changing how I pass in parameters.

**Comment by vitaly-t** [comment]
This library does not use the configuration details, it passes the entire object on to the [underlying driver](https://github.com/brianc/node-postgres), which has [an issue of its own about it](https://github.com/brianc/node-postgres/issues/2263), which has been open for a long time.

I'm afraid you will have to pester those guys about it. Once it is fixed there, I can quickly update the dependency.

**Comment by vitaly-t** [comment]
Ok, according to some initial feedback from that driver, that issue I looked at might be something else. However, the nature of the issue is within that driver anyway.

**Comment by jschaftenaar** [comment]
Closing this issue, turns out it is not a pg-promise related issue Thank you for your very quick replies.
