### ISSUE TITLE
pg-promise returning results twice

### ISSUE THREAD

**Issue by AlandSleman** [vitaly-t/pg-promise#791]
I have this postgreSQL query, which is 
returning 3 comments ordered by comment_date from 
posts table

```
 const comments = await db
    .one(`with a as 
      (
          SELECT  
           posts.post_id as post_id 
          FROM posts where user_id = $1
          order by post_date desc
          limit 2
      ), b as
      (
          select user_id,
          comment_id,
          post_id,
          comment_date
          , ROW_NUMBER() over (partition by post_id order by comment_date desc) as RowNum
          from post_comments
      ) 
-- SELECT json_agg(each_table_rows)
   --   FROM (
        SELECT * from a 
     INNER JOIN b USING (post_id)
      where b.RowNum <= 3
--)  each_table_rows`,
['user1'] )
```
if i try using (db.one) it will give me this error:
```
QueryResultError {
    code: queryResultErrorCode.multiple
    message: "Multiple rows were not expected."
    received: 6
    query: "with a as
      (
          SELECT
           posts.post_id as post_id
...
```
if i change it to (db.many) it works but...
the result should return  6 rows, but  for some reason it returns the results twice... same results just twice...
```
conlose.log(comments)
--returns 2 arrays for some reason:
--first array:
[
  {
    -- comment no.1
  },
  {
    -- comment no.2
  },
  {
   -- comment no.3
  },
  {
   -- comment no.4
  },
  {
   -- comment no.5
  },
  {
    --comment no.6
  }
]
--second array(I don't want this one )
[
  --same results as first array
]
```

 if i run this query directly against the database using pgadmin it returns results just fine so the problem has to be something with pg-promise

[here is how the result should be](https://extendsclass.com/postgresql/575262f)

**Comment by vitaly-t** [comment]
I think there is something wrong in your code there, but you do not enclose anything reproducible here, so impossible to say for sure.

**Comment by vitaly-t** [comment]
P.S. There is no need posting it here and [on StackOverflow at the same time](https://github.com/vitaly-t/pg-promise/issues/791).

**Comment by AlandSleman** [comment]
Checking my code again...

**Comment by AlandSleman** [comment]
> I think there is something wrong in your code there, but you do not enclose anything reproducible here, so impossible to say for sure. If you include a code example that I can run here, then I can tell you what's wrong.

Check my code again  please.
Also i tried same thing using node-postgres samething happened what do you think the problem is?

**Comment by AlandSleman** [comment]
> P.S. There is no need posting it here and on StackOverflow at the same time ;)
Check my code again please.
Also i tried same thing using node-postgres same thing happened i got result 2 times

**Comment by AlandSleman** [comment]
> I think there is something wrong in your code there, but you do not enclose anything reproducible here, so impossible to say for sure. If you include a code example that I can run here, then I can tell you what's wrong.

Check my code again please. 
Also i tried same thing using node-postgres same thing happened i got result 2 times

**Comment by vitaly-t** [comment]
I can't say, not without a usable example. Try asking that against `node-postgres`, because that's what gives the result back, this library doesn't change that.

**Comment by AlandSleman** [comment]
> I can't say, not without a usable example. Try asking that against `node-postgres`, because that's what gives the result back, this library doesn't change that.

i provided the example

**Comment by vitaly-t** [comment]
You provided neither database schema no data that's in it. That is not a usable example.

**Comment by AlandSleman** [comment]
> You provided neither database schema no data that's in it. That is not a usable example.

no...at the bottom of the post 
[here is how the result should be](https://extendsclass.com/postgresql/575262f)

**Comment by vitaly-t** [comment]
Ok, Tried that, got 6 rows back:

```json
[
  {
    post_id: 'post2',
    user_id: 'user1',
    comment_id: 'comment3',
    comment_date: '55',
    rownum: '1'
  },
  {
    post_id: 'post2',
    user_id: 'user1',
    comment_id: 'comment3',
    comment_date: '55',
    rownum: '1'
  },
  {
    post_id: 'post2',
    user_id: 'user1',
    comment_id: 'comment3',
    comment_date: '55',
    rownum: '2'
  },
  {
    post_id: 'post2',
    user_id: 'user1',
    comment_id: 'comment3',
    comment_date: '55',
    rownum: '2'
  },
  {
    post_id: 'post2',
    user_id: 'user1',
    comment_id: 'comment1',
    comment_date: '33',
    rownum: '3'
  },
  {
    post_id: 'post2',
    user_id: 'user1',
    comment_id: 'comment1',
    comment_date: '33',
    rownum: '3'
  }
]
```

Nothing comes twice back. I don't know what else you are doing in your code that gives you result twice, but it doesn't reproduce.

**Comment by vitaly-t** [comment]
And here's the entire test up, in case you wonder how I tested it...

```js
const pgLib = require('pg-promise');

const initOptions = {};

const pgp = pgLib(initOptions);

const cn = 'postgres://postgres@localhost:5432/test_db';

const db = pgp(cn);

(async function () {

    try {
        const result = await db.many(`with a as 
      (
          SELECT  
           posts.post_id as post_id 
          FROM posts where user_id = 'user1'
          order by post_date desc
          limit 2
      ), b as
      (
          select user_id,
          comment_id,
          post_id,
          comment_date
          , ROW_NUMBER() over (partition by post_id order by comment_date desc) as RowNum
          from post_comments
      ) 
-- SELECT json_agg(each_table_rows)
   --   FROM (
        SELECT * from a 
     INNER JOIN b USING (post_id)
      where b.RowNum <= 3
--)  each_table_rows`);
        console.log(result);
    } catch (e) {
        console.log(e);
    } finally{
        pgp.end();
    }
})();
```

**Comment by AlandSleman** [comment]
> And here's the entire test up, in case you wonder how I tested it...
> 
> ```js
> const pgLib = require('pg-promise');
> 
> const initOptions = {};
> 
> const pgp = pgLib(initOptions);
> 
> const cn = 'postgres://postgres@localhost:5432/test_db';
> 
> const db = pgp(cn);
> 
> (async function () {
> 
>     try {
>         const result = await db.many(`with a as 
>       (
>           SELECT  
>            posts.post_id as post_id 
>           FROM posts where user_id = 'user1'
>           order by post_date desc
>           limit 2
>       ), b as
>       (
>           select user_id,
>           comment_id,
>           post_id,
>           comment_date
>           , ROW_NUMBER() over (partition by post_id order by comment_date desc) as RowNum
>           from post_comments
>       ) 
> -- SELECT json_agg(each_table_rows)
>    --   FROM (
>         SELECT * from a 
>      INNER JOIN b USING (post_id)
>       where b.RowNum <= 3
> --)  each_table_rows`);
>         console.log(result);
>     } catch (e) {
>         console.log(e);
>     } finally{
>         pgp.end();
>     }
> })();
> ```

just a minute let me try this on my project...

**Comment by AlandSleman** [comment]
> And here's the entire test up, in case you wonder how I tested it...

oh wow.... it was totally different issue with my project code... 
I'm sorry for wasting your time for a problem that didn't exist... 
how i can delete this issue? or i should just close it.
