### ISSUE TITLE
ColumnSet - defining json array column

### ISSUE THREAD

**Issue by jkk4999** [vitaly-t/pg-promise#792]
Hello,

I have a Heroku postgres table named 'templates' that has a json[] column named json_array.  I have defined a columnSet and used a configuration object for this property per the documentation example.  My data passes in an array of objects for this column.  In the error, I can see that this property is not included in the output and therefore not being processed properly.

How do I resolve this issue?

Thanks in advance for your help.  This library is awesome!

### Expected behavior
record is inserted in postgres 

### Actual behavior

malformed array literal: "[{"name":"AccountNumber","datatype":"string","sort":"","filter":"","group":false,"aggregration":"","split":false,"formula":""},{"name":"AccountNumber","datatype":"string","sort":"","filter":"","group":false,"aggregration":"","split":false,"formula":""}]"

### Sample code
/*
/api/pgInsertTemplates
*/

module.exports = async function (fastify, options) {
  fastify.post("/", async function (request, reply) {
    const client = fastify.client;

    const db = fastify.db;
    const pgp = fastify.pgp;

    // an array containing 1 element for each template row
    const payload = request.body;

    // adding server properties to the query
    payload.orgid = fastify.userInfo.organizationId;
    payload.owner = fastify.userInfo.userEmail;

    const templatesToInsert = [];

    payload.forEach((element) => {
      const record = {
        id: payload.id,
        orgid: payload.orgid,
        template_name: element.template_name,
        owner: payload.owner,
        is_active: element.is_active,
        is_public: element.is_public,
        json_array: element.json_array,
        description: element.description,
        object: element.object,
      };
      templatesToInsert.push(record);
    });

    const columnSet = new pgp.helpers.ColumnSet(
      [
        "?id",
        "orgid",
        "template_name",
        "owner",
        "is_active",
        "is_public",
        {
          name: "json_array",
          prop: "json_array",
          mod: ":json",
        },
        "description",
        "object",
      ],
      {
        table: { table: "templates" },
      }
    );

    // generating the insert query
    const insert =
      pgp.helpers.insert(templatesToInsert, columnSet) + "RETURNING id";

    // executing the query:
    try {
      let res = await db.none(insert);
      return res;
    } catch (error) {
      console.error(error.message);
      return error;
    }
  });
};

### Environment

* Version of pg-promise:  10.10.2
* OS type (Linux/Windows/Mac): Mac
* Version of Node.js: 16.1.0
*

**Comment by vitaly-t** [comment]
Probably invalid type cast. You need to include output example for your case, so I can tell where's the discrepancy.

**Comment by jkk4999** [comment]
Hello,

I figured out the issue.  Postgres is expecting an array to look like this '{{1,2,3},{4,5,6},{7,8,9}}'.  My json object array looks like this '[{"name":"AccountNumber","datatype":"string","sort":"","filter":"","group":false,"aggregration":"","split":false,"formula":""}]'

The beginning and end [] need to be replaced with {}.

I verified the column datatypes against the application data and its ok.

Here is the output.  The error default property points to this issue.

![pg output](https://user-images.githubusercontent.com/59376742/121791245-d059d780-cbb5-11eb-8282-291495c55b82.png)

I assume pg-promise has functionality to do this.  Appreciate your assistance in this matter.  Below you will find console.log outputs for the data.  I attached the output error for your reference.

>> console.log(templatesToInsert)

[
  {
    id: undefined,
    orgid: '00D5Y000001N7LWUA0',
    template_name: 'test',
    owner: 'jeffreykennedy2011@gmail.com',
    is_active: true,
    is_public: false,
    json_array: [ [Object] ],
    description: 'test',
    object: 'Account'
  }
]

>> console.log( json_array )

[
  {
    name: 'AccountNumber',
    datatype: 'string',
    sort: '',
    filter: '',
    group: false,
    aggregration: '',
    split: false,
    formula: ''
  }
]

pgp insert string >>

insert into "templates"("id","orgid","template_name","owner","is_active","is_public","json_array","description","object") values(null,'00D5Y000001N7LWUA0','test','jeffreykennedy2011@gmail.com',true,false,'[{"name":"AccountNumber","datatype":"string","sort":"","filter":"","group":false,"aggregration":"","split":false,"formula":""}]','test','Account')RETURNING id

**Comment by vitaly-t** [comment]
> Postgres is expecting an array to look like this '{{1,2,3},{4,5,6},{7,8,9}}'. My json object array looks like this '[{"name":"AccountNumber","datatype":"string","sort":"","filter":"","group":false,"aggregration":"","split":false,"formula":""}]'

I don't follow. How do you take an array of objects and get that list of numbers? Your example doesn't add up.

**Comment by vitaly-t** [comment]
@jkk4999 Can you clarify, please?

**Comment by jkk4999** [comment]
Sorry if my post was not clear.  The numbers array was from the Postgres docs on how they store array of JSON.  My insert string was provided that generated the error.

I added a child table to store my template fields, eliminating the need to store an array of JSON in the parent table.

Thanks.
