### ISSUE TITLE
db.done() throws Querying against a released or lost connection error

### ISSUE THREAD

**Issue by shan369** [vitaly-t/pg-promise#795]
### Expected behavior
should not throw error on .done() call.

**Is there any way to check db connection is closed before calling .done() method**

### Actual behavior
getting error while calling .done() method.
**Error: UnhandledPromiseRejectionWarning: Error: Querying against a released or lost connection.**

### Steps to reproduce
below is a small pseudo code to reproduce - 

db.connect()
db.tx() {

}.then() {
  db.done()
}.catch() {
  db.done()
}

### Environment

* Version of pg-promise: 8.6.3
* OS type (Linux/Windows/Mac): Windows
* Version of Node.js: v10.16.0

**Comment by vitaly-t** [comment]
* Why are you calling `db.connect()`?
* What is `db` in the `db.done()` connection?
* You are calling async `.connect()` method without waiting.

**Comment by shan369** [comment]
I am first uisng connectToDb method to establish connection then calling transactionStatementsmethod to execute transactions. Below is the code for it.

.then(() => this.connectToDb())
.then((dbAndConn: any) =>
	this.transactionStatements(
	dbAndConn,
	createTempTable,
	copyToRedShiftCommand,
	createTransactionStatementCommand
	)
)


public connectToDb(): Promise<{}> {
		return new Promise((resolve, reject) => {
			const db = pgp(this.connectionString);
			const dbAndConn = {
				db: "",
				conn: ""
			};
			db.connect()
				.then((conn: any) => {
					dbAndConn.db = db;
					dbAndConn.conn = conn;
					logger.info("Connection Successful");
					return resolve(dbAndConn);
				})
				.catch((error: any) => {
					logger.info("Connection failure");
					return reject(error);
				});
		});
	}
	
	
	public transactionStatements(
		dbAndConn: any,
		createTempTable: string,
		copyToRedShiftCommand: string,
		createTransactionStatementCommand: string
	): Promise<{}> {
		logger.info("Executing Transaction Statements");
		return new Promise((resolve: any, reject: any) => {
			dbAndConn.db
				.tx((transaction: any) => {
					return transaction.batch([
						transaction.none(createTempTable),
						transaction.none(copyToRedShiftCommand),
						transaction.none(createTransactionStatementCommand)
					]);
				})
				.then((result: any) => {
					logger.info("Transaction completed successfully");
					logger.info(result);
					dbAndConn.conn.done();
					this.config.uploadedToRedshift = true;
					return resolve("Upload to RedShift Successful");
				})
				.catch((error: any) => {
					dbAndConn.conn.done();
					logger.info("Transaction failed");
					return reject(error);
				});
		});
	}
	

I get "Transaction completed successfully" message but it is like after 8-10 hours. I suspect the connection is getting closed in between and giving me this error when I'm using dbAndConn.conn.done();

Can you please suggest if anything is happening wrong here?

**Comment by vitaly-t** [comment]
> I am first uisng connectToDb method to establish connection

Why? Why not just run transaction natively?

All those extra promises you are creating is pointless. And expressions like `return resolve()` or `return reject()` do not return anything. I see a bit of misunderstanding there of how promises work.

All you need is:

```js
await db.tx(t => {
    await t.none(createTempTable);
    await t.none(copyToRedShiftCommand);
    await t.none(createTransactionStatementCommand);
});
```

that's all.

**Comment by shan369** [comment]
Ok I will try that out. Thanks a lot @vitaly-t 

Few doubts -  

1. Is there any default timeout for db connection as my transactions sometimes take 8-10 hours to execute?
2. Will the db connection close automatically? Is there no need for  dbAndConn.conn.done() ?

**Comment by vitaly-t** [comment]
> Will the db connection close automatically? Is there no need for dbAndConn.conn.done() ?

The library controls connections automatically. That it's main feature.

You shouldn't have transactions that last 8-10 hours, there is something fundamentally wrong with what you are doing there.

**Comment by shan369** [comment]
I think transactions are taking time due to some locks in the db. I'll figure it out.

The solution you provided seems to be working.

Thanks a lot.
