### ISSUE TITLE
Tasks and temporary views

### ISSUE THREAD

**Issue by rogorido** [vitaly-t/pg-promise#796]
This is just a small question or small request for advice before diving into the topic by myself: I tend to make use of temporary views a lot. As far as I see, this does not work with pg-promise since every connection gets lost. But maybe using tasks I could achieve the same goal. Am I completely wrong? Should I forget the temp views? 

Thanks (and thanks above all for the wonderful piece of software!)

**Comment by vitaly-t** [comment]
> since every connection gets lost

They do not get lost, per se, they are released back into the connection pool :)

> maybe using tasks I could achieve the same goal

Yes, you can.

**Comment by rogorido** [comment]
> > since every connection gets lost
> 
> They do not get lost, per se, they are released back into the connection pool :)

OK, thanks for the explanation! ;-)

> > maybe using tasks I could achieve the same goal 
> Yes, you can.

Perfect! Thanks!
