### ISSUE TITLE
How to run the parallel inserts - massive-insert

### ISSUE THREAD

**Issue by malinda1986** [vitaly-t/pg-promise#797]
I want to run multiple inserts as below, but it does not work, appreciate any help
```
 db.tx('massive-insert', t => {
    return t.sequence((index, data) => {
      return getNextData(index).then(a => {
        if (a) {
          const price_q = pgp.helpers.insert(a.price, cs_product_prices);
          const sales_q = pgp.helpers.insert(a.sales, cs_product_sales);
          return t.batch([price_q, sales_q]).then(() => getNextData(index));
        }
      });
    });
  })
    .then(data => {
      // COMMIT has been executed
      console.log('Total batches:', data.total, ', Duration:', data.duration);
    })
    .catch(error => {
      // ROLLBACK has been executed
      console.log(error);
    });
```

* Version of pg-promise: 10.10.2
* OS type (Linux/Windows/Mac): Mac
* Version of Node.js:v13.12.0

**Comment by vitaly-t** [comment]
> it does not work

You need to be more specific. Also, this kind of issue is best to publish on StackOverflow.

**Comment by vitaly-t** [comment]
You are calling ` t.batch([price_q, sales_q])`, passing it two strings. What do u expect to happen here? :) Nothing! You are not executing any queries in your code at all.

**Comment by vitaly-t** [comment]
[Resolved on StackOverflow](https://stackoverflow.com/questions/68375923/postgres-pg-promise-unable-to-update-multi-rows-missing-from-clause-entry).
