### ISSUE TITLE
Notify/Listen messages getting stuck after processing few thousands

### ISSUE THREAD

**Issue by UJPrasad** [vitaly-t/pg-promise#798]
### Expected behavior
We are using a separate microservice to listen to our pg notify events.

1. How we generate events: Use a trigger and send the new value on update/insert to perform pg_notify
2. How we listen to events: Using code similar to one [mentioned here](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#listen--notify) 
Example: 
```
// index.js of our microservice
const consumeEvents = () => {
  return db
    .connect({ direct: true })
    .then((sco) => {
      console.log('listening to db for changes');
      sco.client.on('notification', (data) => {
        messageHandler.handle(data);
      });
      return Promise.all([
        sco.none('LISTEN $1~', 'upsert_my_table'),
        sco.none('LISTEN $1~', 'deleted_my_table'),
      ]);
    })
    .catch((error) => {
      console.log('Error in connecting to db events:', error);
    });
};

consumeEvents();
``` 

### Actual behavior

This works fine for most of the time; until a sweet spot [not really sure on the issue] from when the newly generated events are stuck; I assume notification is sent to Postgres queue as the write event is a success, but listen is stuck and I don't see any logs from my handler.

### Steps to reproduce
Using the same code; not really sure about the sweet spot which I've mentioned. But we see this issue quite often on our production. 

Also another question: Is this listen query supposed to be in an idle state when I see it in `pg_stat_activity` ?

### Environment

* Version of pg-promise: ^10.5.8
* OS type (Linux/Windows/Mac): Linux (node:12.2 docker container)
* Version of Node.js: v12.2.0

**Comment by vitaly-t** [comment]
What you have here is not enough to reproduce any kind of error. You need to diagnose it better on your side first. Try to find which call gets stuck exactly. And then update this issue accordingly.

**Comment by UJPrasad** [comment]
Hi @vitaly-t thanks for the quick response; For the stucking messages, the handler is not receiving any messages after processing a few thousand; I'm unable to properly debug in which case this happens. Any inputs regarding the same to debug will help a lot.

```
sco.client.on('notification', (data) => {
    // not getting. any messages here
    messageHandler.handle(data);
});
```

**Comment by vitaly-t** [comment]
It could be that your connection is no longer any good, and needs to be re-created, as shown [in the example](https://github.com/vitaly-t/pg-promise/wiki/Robust-Listeners).

**Comment by UJPrasad** [comment]
Got it, let me check this out and see if this is the thing that is causing the issue. Will get back to you in few hours. By the way; will this listener query shows as an idle state in `pg_stat_activity`?

**Comment by vitaly-t** [comment]
> By the way; will this listener query shows as an idle state in `pg_stat_activity`?

Most likely yes. I think your connection dies for some reasons and needs to be re-created.

**Comment by vitaly-t** [comment]
@UJPrasad I fthis has been resolved, then let's close it ;)
