### ISSUE TITLE
Remaining connection slots are reserved for non-replication superuser connections

### ISSUE THREAD

**Issue by kimmobrunfeldt** [vitaly-t/pg-promise#80]
I'm getting an error when executing a simple query `SELECT 1`. This is executed in our monitoring route which is requested ~once in 10 seconds.

We are initializing the connection once in our application like this:
```js
db = pgp(connectionString);
```

and later calling:

```
db.query('SELECT 1')
```

Heroku has a limit of 20 connections to the database but it shouldn't be exceeded. Do you have any pointers how to fix this or debug it further?

Detailed exception:
```
Remaining connection slots are reserved for non-replication superuser connections 
    at Connection.parseE (/app/node_modules/pg/lib/connection.js:539:11) 
    at Connection.parseMessage (/app/node_modules/pg/lib/connection.js:366:17) 
    at TLSSocket.<anonymous> (/app/node_modules/pg/lib/connection.js:105:22) 
    at emitOne (events.js:77:13) 
    at TLSSocket.emit (events.js:169:7) 
    at readableAddChunk (_stream_readable.js:146:16) 
    at TLSSocket.Readable.push (_stream_readable.js:110:10) 
    at TLSWrap.onread (net.js:523:20)
```

**Comment by vitaly-t** [comment]
This issue isn't related to implementation of pg-promise.

A quick search shows the following discussions:

* [Heroku “psql: FATAL: remaining connection slots are reserved for non-replication superuser connections”](http://stackoverflow.com/questions/11847144/heroku-psql-fatal-remaining-connection-slots-are-reserved-for-non-replication)
* [Heroku “psql: FATAL: remaining connection slots are reserved for non-replication superuser connections”](http://stackoverflow.com/questions/13640871/heroku-psql-fatal-remaining-connection-slots-are-reserved-for-non-replication)
* [PostgreSQL ERROR: no more connections allowed](http://serverfault.com/questions/577712/postgresql-error-no-more-connections-allowed)

You should research this yourself. I'm not familiar with this Heroku-related issue, unfortunately.

**Comment by kimmobrunfeldt** [comment]
I have researched and there's nothing more to research on Heroku's part. Was it Heroku or not, I need to somehow see how many Postgres connections this library is creating. So my question is, how can I debug the library's internal behavior? 

I started with the highest level library instead of opening issue to node-postgres or pool because I was assuming you have had to debug the connection pooling when developing this lib.

**Comment by vitaly-t** [comment]
Did you try this? - 

>You might be able to find why you have so many connections by inspecting view pg_stat_activity:
```SELECT * FROM pg_stat_activity```
>Most likely, you have some stray loop that opens new connection(s) without closing it.

from http://stackoverflow.com/questions/13640871/heroku-psql-fatal-remaining-connection-slots-are-reserved-for-non-replication

**Comment by kimmobrunfeldt** [comment]
The activity seems normal when running the query. I might need to open a Heroku support ticket after all.  Our endpoint is as simple as it could and there are no loops or other behavior which could cause this inside our app. Sorry for bothering and thanks for your help!

**Comment by vitaly-t** [comment]
I wish I could help, but it does seem related to Heroku only. If you find out what it is, please let us know here.

**Comment by vitaly-t** [comment]
@kimmobrunfeldt have you figured this one out?

**Comment by kimmobrunfeldt** [comment]
We ended up upgrading our Heroku Postgres plan from free to paid one: Hobby basic. At least we haven't got any errors after the upgrade. We are still monitoring the situation but I have pretty high confidence that it fixed the issue.

**Comment by vitaly-t** [comment]
They may have placed a micro-cap on the number of connections for free plans that it doesn't even work. Whatever it takes to get people to upgrade, is their moto :)

**Comment by kimmobrunfeldt** [comment]
Yep seems like it. That was quite disappointing because in the database management UI, they stated that we were using 1/20 connections when using the free plan. So I assumed we would have 20 connections available.

**Comment by vitaly-t** [comment]
Check out - my latest meditation about the query performance: [Performance Boost](https://github.com/vitaly-t/pg-promise/wiki/Performance-Boost) ;)
