### ISSUE TITLE
Query works in psql but fails in pg-promise

### ISSUE THREAD

**Issue by kingram6865** [vitaly-t/pg-promise#801]
### Expected behavior
Return 3200 rows of data

### Actual behavior
returns []

### Steps to reproduce
In psql the statement
SELECT a.email, b.person_email FROM data b LEFT JOIN users a
WHERE (substring(b.data3 ->> 'data2' from '(?<=iss)(w+)') NOT LIKE substring(b.data2 from '([a-zA-Z]{1,})'))

returns 3200 rows.

The same statement when passed to pg-promise, returns an empty array.
All connections are sound, and a simpler query on the same table given to pg-promise returns all records.

table "data" has a jsonb column containing JSON structure
{
   data1: "One",
   data2: "Two",
   data3: "Three"
}  a connector column person_email, and the column data2

table "users" contains the column objid SERIAL and email

Basic scenario is that a legacy table has parsed JSON into columns (data1, data2). The new column "data3" is a jsonb column
where the JSON is not parsed.

The SQL shows all records where the data3 ->>"data2" key has a value that is not the same as the column data2

### Environment

* Version of pg-promise: 10.10.2
* OS type (Linux/Windows/Mac): Linux
* Version of Node.js: 16.3.0

**Comment by vitaly-t** [comment]
Too many questions like this were open in the past, they all end up being something missed in the query or data or the code. And without any actual data, it is also non-reproducible. I suggest that you search for the issue on your end. I cannot spend time on such data-related problems.

**Comment by kingram6865** [comment]
Ok. If your experience says this is a data problem I will investigate it from that context.

The workaround was to create a temp table from that select and query the temp table with pg-promise
and that worked fine.

I'll try the query event and see if I can track the problem.
