### ISSUE TITLE
Allow table alias in helpers.update

### ISSUE THREAD

**Issue by m1ch4ls** [vitaly-t/pg-promise#805]
My motivation behind this request is so I can use the same conditions for UPDATE and SELECT queries (the SELECT query is using an alias).

### Expected behavior

Allow a way for `helpers.update(...)` to generate `UPDATE "table" AS t_alias SET ...` for a "single" row update. Currently if passed `tableAlias`, it only works for "multirow" update from generated from `values`.

### Actual behavior

There is no way to add a table alias for a "single" row with this helper.

### Steps to reproduce

```js
const SQL = `${helpers.update(input, imageColumnSet, imageColumnSet.table, { tableAlias: 'i' })} WHERE i.id = 123`;
```

The above won't generate `UPDATE "image" AS i SET ...` and therefore the WHERE condition doesn't work.

Here is a patch that respects the` tableAlias` option for "single" row updates. 

```patch
diff --git a/node_modules/pg-promise/lib/helpers/methods/update.js b/node_modules/pg-promise/lib/helpers/methods/update.js
index 5982d72..bc9ec1d 100644
--- a/node_modules/pg-promise/lib/helpers/methods/update.js
+++ b/node_modules/pg-promise/lib/helpers/methods/update.js
@@ -208,9 +208,11 @@ function update(data, columns, table, options, capSQL) {

     checkTable();

-    const query = capSQL ? sql.single.capCase : sql.single.lowCase;
+    const tableAlias = options.tableAlias ? npm.formatting.as.alias(options.tableAlias) : null;
+    const sqlChoice = tableAlias ? sql.single.withAlias : sql.single;
+    const query = capSQL ? sqlChoice.capCase : sqlChoice.lowCase;

-    return format(query, table.name) + format(updates, columns.prepare(data), fmOptions);
+    return format(query, [table.name, tableAlias]) + format(updates, columns.prepare(data), fmOptions);

     function checkTable() {
         if (table && !(table instanceof TableName)) {
@@ -233,6 +235,10 @@ function update(data, columns, table, options, capSQL) {

 const sql = {
     single: {
+        withAlias: {
+          lowCase: `update $1^ as $2^ set `,
+          capCase: `UPDATE $1^ AS $2^ SET `
+        },
         lowCase: `update $1^ set `,
         capCase: `UPDATE $1^ SET `
     },
```

### Environment

* Version of pg-promise: 10.11.0
* OS type (Linux/Windows/Mac): Linux
* Version of Node.js: 16.7.0

**Comment by vitaly-t** [comment]
I cannot consider this important, because single-row inserts and updates are too simple. The `helpers` extension was developed primarily for the multi-row operations.

In case of `UPDATE`, you can easily write your own version of query generation, one that adds an alias.

**Comment by vitaly-t** [comment]
Here's a very simple example:

```ts
function updateWithAlias(data: object, cs: ColumnSet, alias: string) {
    return `UPDATE ${cs.table} AS ${alias} SET ${cs.assignColumns()}`;
}
```
