### ISSUE TITLE
Question: How to INSERT IGNORE using ColumnSet ?

### ISSUE THREAD

**Issue by gaboesquivel** [vitaly-t/pg-promise#807]
Hi

How can I add `IGNORE` directive to my `INSERT` query generated with ColumnSet ?

**Comment by gaboesquivel** [comment]
Ahh found this https://stackoverflow.com/questions/59886373/how-do-i-insert-many-if-it-already-exists-dont-do-anything-with-pg-promise. 

Trying this out

```
const users = […];
const query = pgp.helpers.insert(users, cs) + ' ON DUPLICATE KEY UPDATE';
```

**Comment by vitaly-t** [comment]
Just append `ON CONFLICT DO NOTHING` to your query, and that's it.

**Comment by gaboesquivel** [comment]
Thanks, I actually needed the opposite and update, so I used `pgp.helpers.insert(users, cs) + ON CONFLICT ON CONSTRAINT table_pkey DO UPDATE SET a=EXCLUDED.a b =EXCLUDED.b`

**Comment by vitaly-t** [comment]
There's also [assignColumns](http://vitaly-t.github.io/pg-promise/helpers.ColumnSet.html#assignColumns) method to help with assignments.
