### ISSUE TITLE
How to connect primary and secondary servers ?

### ISSUE THREAD

**Issue by vbalakrishnasolum** [vitaly-t/pg-promise#808]
### It is not working when we give primary and secondary servers. like below
`
postgresql://postgres:postgres@192.168.1.1:5432,192.168.1.2:5433/database1
`

### PostgreSQL

* Version of pg-promise:10.8.1
* OS type (Linux/Windows/Mac): MAC
* Version of Node.js:14.17.0

**Comment by vitaly-t** [comment]
This library does not control anything connection-related, it is done in the [underlying driver](https://github.com/brianc/node-postgres).

**Comment by vbalakrishnasolum** [comment]
Thank you.
