### ISSUE TITLE
Question:  ColumnSet with JSONB fields

### ISSUE THREAD

**Issue by gaboesquivel** [vitaly-t/pg-promise#809]
Hi, I'm struggling a little bit with JSONB fields on using ColumnSet inserts.
I'm trying this out

![image](https://user-images.githubusercontent.com/391270/135548434-830e634b-cdf2-425f-8ca1-4a2ba899d289.png)

and I keep getting `column "authorization" is of type jsonb but expression is of type text[]`. 

do you have any advise?

Best

**Comment by gaboesquivel** [comment]
is it because an Array is not Valid JSONB?

**Comment by gaboesquivel** [comment]
Ok it seems Array of JSONB is supported but it's a dense topic  https://link.medium.com/Dd8u7hwiZjb

**Comment by vitaly-t** [comment]
As far as this library is concerned, it supports `cast` attribute for columns, so you can set type casting. Other than that, the best way is to try executing a single insert via pgAdmin - to see what syntax it actually likes, so you can modify your `ColumnSet` to match that.

In the meantime, you do not need to use `c.source as ChainGraphAction`, you should just pass the source type to the class itself: 

```ts
new pgp.helpers.ColupmnSet<ChainGraphAction>(...)
```

**Comment by gaboesquivel** [comment]
Thanks, I appreciate your work on this lib and the quick replies. 

The problem is I have some fields that arrays of structured data so in db schema that is jsonb. 
The helper wraps the the field on an `ARRAY[]` hence the `is of type jsonb but expression is of type text[]` error.

I solved it by stringifying the jsonb arrays. Eg.

```
    {
      name: 'authorization',
      init: (c) => JSON.stringify(c.source.authorization),
    },
```

**Comment by vitaly-t** [comment]
The correct syntax for this is just `'authorization:json'`, you do not need to use `init` for this.

**Comment by gaboesquivel** [comment]
nice, thanks!
