### ISSUE TITLE
Verify database connection or throw?

### ISSUE THREAD

**Issue by reinvantveer** [vitaly-t/pg-promise#81]
Hi,

Thanks for your nice package. I have a question: while writing tests, I try to check for unsuccessful connections. In a lot of situations, one can't simply assume the availability of the database, one has to test for it. The 
```javascript
var db = pgp(connectionObject);
```
doesn't seem to throw an error. It isn't a promise either. So when I put in garbage in the connectionObject, I expect to be able to test for an 
```javascript
assert.throws(function shouldThrow(){
var db = pgp("postgres://this:is/just:999/silly");

db.query("select '1'::int as number", true)
.then(function(result){console.log(result)})
.catch(
//re-throw error here, you know the deal
);
});
```
(this is probably pseudo-code by the way)

But instead of throwing, it just gives me an empty result. Any ideas on how to reliably test?

Thanks a bunch,
Rein

**Comment by vitaly-t** [comment]
For that you should use [connect](https://github.com/vitaly-t/pg-promise#connect) and [error](https://github.com/vitaly-t/pg-promise#error) events.

See how pg-promise does it when testing itself: 

* https://github.com/vitaly-t/pg-promise/blob/master/test/dbSpec.js#L171
* https://github.com/vitaly-t/pg-promise/blob/master/test/dbSpec.js#L17

When there an error a connection-related error, your event `error` will have property `cn` set. On the context object.

**Comment by vitaly-t** [comment]
Here's a complete application for you:
```js
var options = {
    error: function (error, e) {
        if (e.cn) {
            console.log("Connection:", e.cn);
            console.log("EVENT:", error.message);
        }
    }
};

var pgp = require("pg-promise")(options);

var db = pgp('invalid connection string');

db.connect()
    .catch(function (error) {
        console.log("ERROR", error.message);
    });
```
You would see that the same error is reported within `.catch` and event `error`. In the event you also get `e.cn` - secure connection details (with password hashed, if present).

**Comment by reinvantveer** [comment]
Yes, I'm seeing it thrown. Thanks for the elaborate answer and example!

**Comment by vitaly-t** [comment]
You are welcome!

See my latest meditation on the query performance: [Performance Boost](https://github.com/vitaly-t/pg-promise/wiki/Performance-Boost) ;)

**Comment by vitaly-t** [comment]
Answer to the question was later elaborated here: http://stackoverflow.com/questions/36120435/how-to-ensure-database-connection-before-starting-app-server-with-pg-promise

**Comment by reinvantveer** [comment]
Thanks!

Den mån 21 mar 2016 06:35Vitaly Tomilov <notifications@github.com> skrev:
