### ISSUE TITLE
Design pattern recommendation to load balance queries between multiple replicated databases 

### ISSUE THREAD

**Issue by shaunakv1** [vitaly-t/pg-promise#811]
Hi @vitaly-t ,

This is kind of related to https://github.com/vitaly-t/pg-promise/issues/222 , but as that was closed, wanted to start a new thread for this question. Sorry digging up an old topic.  This is more of a question about the design pattern than a technical issue. 

In the same way as the linked to issue, say I have four copies of the exact same database. Some refer to this as read replicas.  Now the application makes very large number of simultaneous queries that are read-only.  Typically in a one database situation we start a connection pool to it, and pg-promise manages the connections over a connection pool. 

Now say I want to replicate database connections to different copies of the same database. All connections use connection pools. As all queries are read only and data is replicated, in theory this should be possible. What I am looking for is a recommendation for a good design pattern, recommendation on how to go about handling this code, that would fit in the repository pattern. 

Ideally I want to keep the code that makes query generally same, but when we do something like `db.any(sql.offshoreWindEnergyLeases, { aoi: aoi })`  I want to load balance the queries between say database A, B, C and D on connection level.  The code is setup exactly same as  the repository pattern you recommend in the wiki. 

I also realize there are setups like pg-bouncer and citus, but that's not what I am referring to. I would just like to load balance queries over multiple copies of same database.  Each connection will have it's own authentication, pool limit etc.  When the application starts I want to be able to define how many databases are in the load balancing setup. 

I have tried a  few approaches using making connection objects, and then trying to use them in round robin. But I am curious as to how you would recommend designing this code. 

Thanks in advance.

**Comment by vitaly-t** [comment]
You are limited to some 100 maximum physical connections. And if you attempt to increase this number, NodeJS will start falling over, i.e. consuming too much CPU time managing those, which will decrease performance of your app. So, going over 100 is not recommended.

Now, keeping that in mind, once you depart from a single-connection approach, you have to split your maximum connection size among all such shared connections. Typically, those are organized by priority, and their maximum pool size is set up accordingly...

```js
const db = pgp({...max: 30}); // your db object for regular queries
const dbHigh = pgp({...max: 60}); // your db object for high-priority queries
const dbLow = pgp({...max: 10}); // your db object for low-priority queries
```

This was you end up not exceeding 100 maximum connections, while managing pool-access priority in your app according to the business logic of the application.

**Comment by vitaly-t** [comment]
I think I may have misread your post, staying up too late here tonight :) will try again tomorrow...
