### ISSUE TITLE
How to improve QueryFile Initialization Perf ?

### ISSUE THREAD

**Issue by sathishsoundharajan** [vitaly-t/pg-promise#819]
Hi @vitaly-t I'm working in a project which has 39 tables and it has 191+ queries defined in query file. As part of Node.js server start up we initialise all the queries in a global variable so it can be accessed by db-access layer.  The problem we face with this approach is our Node.js server takes long time to start about 35 to 40 seconds.. When we dig deep into it using N|Solid clinic tool. We found out some issues, 1 of the issue is loading all queries as part of server start up takes almost 4 to 5 seconds.

We follow the approach mentioned in this demo https://github.com/vitaly-t/pg-promise-demo/tree/master/JavaScript/db/sql

This is not an issue with respect to the module. We wanted to get your thoughts / community thoughts how are they handling this kind of issue. 

One improvement i can think of is stopping loading the queries as part of app start and initialise just in time the query is used in API's. But i fear that would add performance issue in API' calls. 

Any thoughts on handling this is much appreciated. 

If you have questions on how did we arrived at that 4 to 5 seconds number, it just we added console.time/End before and after query loading :) 

### Environment

* Version of pg-promise: 10.11.1^
* OS type (Linux/Windows/Mac): Mac
* Version of Node.js: 12.16.1

**Comment by vitaly-t** [comment]
Why not just add a lazy-load cache on your side?

**Comment by sathishsoundharajan** [comment]
Thanks @vitaly-t  Didn't knew that..  http://vitaly-t.github.io/pg-promise/Database.html has the info..
