### ISSUE TITLE
import * syntax gives uncaughtException pgPromise is not a function

### ISSUE THREAD

**Issue by mariusa** [vitaly-t/pg-promise#827]
### Expected behavior
Following https://github.com/vitaly-t/pg-promise/blob/master/typescript/README.MD
with nodejs 16
```
import * as pgPromise from 'pg-promise';
const pgp = pgPromise({/* Initialization Options */});
```

### Actual behavior
gives
`ERROR uncaughtException pgPromise is not a function`

### Fix
Changed to 
```
import pgPromise from 'pg-promise';
```
and now it works.

### Environment

* Version of pg-promise: 10.x
* OS type (Linux/Windows/Mac): linux
* Version of Node.js: 16

**Comment by vitaly-t** [comment]
[This has been asked around quite a bit, please check StackOverflow](https://stackoverflow.com/questions/62669894/how-to-import-pg-promise-using-es6-syntax).

**Comment by mariusa** [comment]
But this repo still has the wrong syntax:
https://github.com/vitaly-t/pg-promise/blob/master/typescript/README.MD
