### ISSUE TITLE
Add support for maxLifetimeSeconds connection setting via pg@8.7.3

### ISSUE THREAD

**Issue by hempels** [vitaly-t/pg-promise#828]
Support for a maxLifetimeSeconds connection parameter was added to node-postgres as of [pg@8.7.3](https://github.com/brianc/node-postgres/releases/tag/pg%408.7.3). To be able to leverage the new capability (critical for load-balanced DB environments), we need pg-promise updated as well.

**Comment by m4heshd** [comment]
This update would be amazing.

**Comment by vitaly-t** [comment]
Merged.
