### ISSUE TITLE
Nice lib but....

### ISSUE THREAD

**Issue by khokm** [vitaly-t/pg-promise#831]
Nice library but PLEASE add connection examples to README.
I literally spend about 10 minutes to google how to init connection to database.

**Comment by vitaly-t** [comment]
It is up front in the documentation - http://vitaly-t.github.io/pg-promise

**Comment by birgersp** [comment]
Typescript example

```
import pgPromise from "pg-promise"
const db = pgPromise()(YOUR_CONNECTION_STRING)

// Now you can use the db object like in the docs
```

http://vitaly-t.github.io/pg-promise/index.html
