### ISSUE TITLE
ISSUE REGARDING INSERTION OF STRING IN POSTGRES QUERY

### ISSUE THREAD

**Issue by AryamannTomar** [vitaly-t/pg-promise#838]
### Expected behavior
`CREATE TABLE table_123abc(a date, b text);`

### Actual behavior
`CREATE TABLE table_'123abc'(a date, b text);`

### Steps to reproduce
createTable.sql file with
CREATE TABLE table_${name}(a date, b text);

Function inside users.ts File
async createTable(values: {name: string}): Promise<null> {
    return this.db.none(sql.createTable, {
        name: values.name
    });
}
call this .sql file in main index file by
db.users.createTable({name: '123abc'})

### Environment

* Version of pg-promise: 10.11.1
* OS type (Linux/Windows/Mac): Windows
* Version of Node.js: 12

**Comment by vitaly-t** [comment]
You are supposed to use [Open-Value filter](https://github.com/vitaly-t/pg-promise#open-values):

```js
table_${name:value}
```

**Comment by AryamannTomar** [comment]
Thanks a lot! @vitaly-t
