### ISSUE TITLE
types: interop between Database and Task

### ISSUE THREAD

**Issue by GabenGar** [vitaly-t/pg-promise#839]
### Expected behavior
I wrote a decorator along these lines:
```typescript
import pgPromise from "pg-promise";
const db = pgPromise(...)(...);

function databaseQuery(
  queryFunc: (args: any, databaseContext: typeof db) => Promise<any>
){
  async function queryDatabase(args: any, databaseContext?: typeof db) {
    return queryFunc(args, databaseContext ? databaseContext : db)
  }

 return queryDatabase;
}
```
The idea is to have a query function which can be ran standalone or a part of the multiquery without a need of importing and passing `db` everywhere.

### Actual behavior

When I write a call like this:
```typescript
const queryFunc = databaseQuery(async(args, ctx) => {
  return ctx.one(...)
})

const queryFuncMulti = databaseQuery(async(args, ctx) => {
  const result = await ctx.task(async(task) => {
    return queryFunc(undefined, task)
  })
});
```
I get this error:
```sh
Argument of type 'ITask<{}>' is not assignable to parameter of type 'IDatabase<{}, IClient>'.
  Type 'ITask<{}>' is missing the following properties from type 'IDatabase<{}, IClient>': connect, $config, $cn, $dc, $poolts(2345)
```
As per [docs](https://vitaly-t.github.io/pg-promise/Task.html) `ITask` is a superset of `IDatabase` and therefore should be usable in all contexts `IDatabase` is usable.

So I'd like to know should it even work outside of typescript typings and is there an interface which is a proper subset for both of these interfaces?

### Steps to reproduce
The code above.

### Environment

* Version of pg-promise: 10.11.1
* OS type (Linux/Windows/Mac): GNU/Linux Ubuntu 22
* Version of Node.js: 16

**Comment by vitaly-t** [comment]
I cannot reproduce the issue you describe. But in general, with this library, it is best to never try to separate queries from tasks or transactions that manage the connection for all the underlying queries.

If you can reproduce the exact issue in JavaScript, then maybe there's an issue with the TypeScript declarations. Otherwise, I'm not sure.

**Comment by GabenGar** [comment]
It's not the issue with javascript, but with the typescript types. I kind of fixed it (and it builds and runs just fine) by declaring the context type like this:
```typescript
type IDatabaseContext = Omit<
  typeof database,
  "connect" | "$config" | "$cn" | "$dc" | "$pool"
>;
```
Because all of these keys are not needed within query functions and they are accessible to the decorator anyway if they are really needed.
So I guess the question at hand is this: 
**Is it intentional that `IDatabase` and `ITask` have different signatures?**

Also I don't follow the point of separation, because what I am doing is no different from calling the fetch functions on the `task` argument of the `task()/tx()` callback. And it has the added benefit of being able to run the underlying queries outside of them.
The usecase I had is having paginated collections and their pagination info being separated in the API, but using the same underlying query function: in one endpoint it runs as a task, but in another one as a part of transaction.

**Comment by vitaly-t** [comment]
> Is it intentional that `IDatabase` and `ITask` have different signatures?

Yes. `Database` is the top-level protocol for the database access, while `ITask` represents the database in its connected state, including possible nested sub-tasks and sub-transactions. In that way, they are quite different.

**Comment by GabenGar** [comment]
> because there is a lot of context provided by the library when working with tasks and transactions

And that context is managed by the caller, which knows better if any given call within it is a new transaction or a task, than an input-queryfile-output mapping function. It's either a decorator or writing every single query function as `await db.txIf(async(task) => {})` (which would still require passing the task/transaction to arguments anyway), creating an extra function for no reason.

**Comment by GabenGar** [comment]
> For example, optional parameter logic there is reversed.

The callbacks for both `task()` and `tx()` having the same `ITask` type doesn't help with the confusion either.

> You do not account for the fact that tasks and transactions manage fairly complex dynamic context on nested levels, when a task is executed inside a transaction or verse-versa, and with nested levels of any depth

I just throw all that complex logic away by excluding `task()`, `taskIf()`, `tx()` and `txIf()` from the interface above and make a separate function to start a transaction and pass the context to decorated functions. There is an immediate need to run several queries in a transaction or standalone, but I've yet to see a situation of juggling nested transactions, let alone with tasks on top. Nested transactions not being cancellable in an atomic manner makes them of very limited use when most queries operate on "all or nothing" logic.

What is the certified `pg-promise` way of writing composable query functions then?

**Comment by vitaly-t** [comment]
> I've yet to see a situation of juggling nested transactions

That may be true for you, but it is used a lot by others. Savepoints are very important. Checkout out [my answer here](https://stackoverflow.com/questions/25425944/does-postgres-support-nested-or-autonomous-transactions). And their implementation requires nested logic for calculating correct auto-close names/id-s.

> What is the certified pg-promise way of writing composable query functions then?

Nothing is certified here, per se, but composable queries often are large, and so [Query Files](https://github.com/vitaly-t/pg-promise#query-files) are the best way to handle them. See also [pg-promise-demo](https://github.com/vitaly-t/pg-promise-demo).

**Comment by GabenGar** [comment]
I already use query files, they still require composability because I need to run almost all of them in a single transaction to generate mock data. Think of something like `movies-characters-cast` relations, which are all `many-to-many` relations between each other and I'd rather write `n` fat queries with a lot of conditional filters than `n*n` queries for every combination of those.

**Comment by vitaly-t** [comment]
> I'd rather write `n` fat queries with a lot of conditional filters than `n*n` queries for every combination of those.

That's why people use `${subQuery:raw}` inside query files a lot.
