### ISSUE TITLE
"pg" dependency upgrade

### ISSUE THREAD

**Issue by yaverin** [vitaly-t/pg-promise#841]
### Discussed in https://github.com/vitaly-t/pg-promise/discussions/840

<div type='discussions-op-text'>

<sup>Originally posted by **yaverin** August 25, 2022</sup>
@vitaly-t , Hi! Please let me know, when you are going to update dependent "pg" library version to "pg": "8.8.0" ?
Thanks in advance!</div>

**Comment by vitaly-t** [comment]
Updated.

**Comment by yaverin** [comment]
Thanks!
