### ISSUE TITLE
Await/Async

### ISSUE THREAD

**Issue by jadencarver** [vitaly-t/pg-promise#85]
I've been trying to understand why I can't get a call to PostgreSQL to work correctly using await/async calls.  I have a test application: https://github.com/jadencarver/sean_app/tree/pg-promise - And when you run it `npm start` (using Traceur) it correctly awaits for the `setTimeout` but it then locks up on the SQL call.

The problem isn't unique to pg-promise, as my attempt using `connect-pgclient` fails as well.  I am starting to believe it is an issue with `pg` itself.  Since I'd hope that using an explicit promise implementation might give me more luck, I'm reporting here.

I feel like I must be doing something wrong.  My main objective is to be able to rollback a transaction in a `try/catch` statement instead of forcing my entire app to crash (Yes, I know that's not Node "best practices", but in this situation I say Node.js is stupid to think we should crash the whole server because of an single error).

**Comment by vitaly-t** [comment]
How is it you are using `await` without Babel? `await` is part of ES7, it is not directly supported by Node.js

**Comment by jadencarver** [comment]
I'm using Google's traceur package: https://github.com/google/traceur-compiler - If you look at the index.es5.js file it shows what it transpiles to.  It might be out of date.  I'll update it.  I haven't tried it using Babel, but a friend of mine has and had no luck either.  I understand if it's not supported, I just really want to be able try/catch async code.

**Comment by vitaly-t** [comment]
Well, that example doesn't use pg-promise, it uses something else.

>I just really want to be able try/catch async code.

`.then` and `.catch` in promises is what already does it for you.

**Comment by jadencarver** [comment]
Yes.  I just updated the compiled version.  It was out of date from my earlier attempt.  The `.then` call works, which is how I'm proving to myself that I didn't do anything wrong - so it's just await/async not working for SQL.  Experimental features are experimental I guess, but it would do wonders to clean up transactions in Node.js.

**Comment by vitaly-t** [comment]
As per my previous post, transactions in pg-promise are fully automatic, you do not need to do anything extra, just use method [tx](http://vitaly-t.github.io/pg-promise/Database.html#.tx) to execute them.

**Comment by vitaly-t** [comment]
Here's a complete application for example: https://github.com/vitaly-t/pg-promise/blob/master/examples/transaction.js

**Comment by jadencarver** [comment]
Do you have an example that uses a generator?  I think that will help me figure out what's wrong.  Technically, I haven't even gotten to the transaction part, because I can't get await/async to work for even a single query.

**Comment by vitaly-t** [comment]
I posted it above. Here again: https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#tasks

**Comment by jadencarver** [comment]
Got it, thank you!

**Comment by vitaly-t** [comment]
N.P.

Just to note that in this library transactions are tasks that automatically execute `BEGIN`/`COMMIT`/`ROLLBACK`.

**Comment by vitaly-t** [comment]
And as for your misfortune with Babel, see this post: http://stackoverflow.com/questions/33624104/how-do-i-setup-babel-6-with-node-js-to-use-es6-in-my-server-side-code
