### ISSUE TITLE
IClient.release() has no return type annotation

### ISSUE THREAD

**Issue by Lehks** [vitaly-t/pg-promise#854]
Pretty much what it says in the title. The method `IClient.release()` lacks a return type annotation. Recently, TypeScript has started to raise an error because of this (I am not entirely sure why).

**Comment by Lehks** [comment]
I just looked up the history of the file `pg-subset.d.ts` and it seems like commit 6ace7 is the culprit. The `release()` declaration was added by that commit.

**Comment by IvanPizhenko** [comment]
I also facing this issue.

**Comment by vitaly-t** [comment]
Addressed in [v10.15.4](https://github.com/vitaly-t/pg-promise/releases/tag/10.15.4) update. Please check and close the issue, if ok :wink:

**Comment by Lehks** [comment]
Can confirm, it works now.
