### ISSUE TITLE
Query re: WARNING: Creating a duplicate database object for the same connection

### ISSUE THREAD

**Issue by vivekhRF** [vitaly-t/pg-promise#857]
We are using pg-promise package of version **8.4.5**  in our node js AWS Lambdas. We have hundreds of Lambdas running on nodejs and using the same package to talk to our postgres database in RDS. We are just wondering if this is something that needs to be worried about or can be ignored. Will there be any performance impacts and are there any best practices for establishing the connection. Here is how we are establishing the connection 

`
        
    const pgp = require('pg-promise')(initOptions);
	
    exports.handler = function (event, context,callback) {

	 const cn = {
		"host":HOST,
		"user":USER,
		"password":PASSWORD,
		"database":DATABASE,
		"keepAlive": false,
		"max":0,
		"min":0,
		"idleTimeoutMillis":100
	};
    const db = pgp(cn);
    db.connect()
        .then(obj => {
            db.func('usr.get_user_by_email', [email])
        .then(data => {
            console.log('DATA:', data); 
            obj.done(); 
            callback(null, JSON.parse(JSON.stringify(data)));
        })
        .catch(error => {
            obj.done(); 
            console.log('ERROR:', error); 
        });
        
            
        })
        .catch(error => {
            console.log('ERROR:', error.message || error);
        });

	};
`

### Environment

* Version of pg-promise: 8.4.5
* OS type (Linux/Windows/Mac): AWS 
* Version of Node.js: Node.js 12.x

**Comment by vivekhRF** [comment]
I am fairly new to the team. We do have a backlog item for updating but it has not been prioritized yet.

**Comment by vitaly-t** [comment]
Closign as duplicate.
