### ISSUE TITLE
Named parameters not working when using QueryFile

### ISSUE THREAD

**Issue by jordansnyder** [vitaly-t/pg-promise#86]
I have an INSERT query with named parameters, and the query works when I put the query string directly in the db.one(...) call. But when I use QueryFile to load a sql file, I get the following error:

`{
  "message": "syntax error at or near \"$\"",
  "stack": "error: syntax error at or near \"$\"\n    at Connection.parseE (/Users/josnyder15/Dev/mq-iot-edge/node_modules/pg/lib/connection.js:539:11)\n    at Connection.parseMessage (/Users/josnyder15/Dev/mq-iot-edge/node_modules/pg/lib/connection.js:366:17)\n    at Socket.<anonymous> (/Users/josnyder15/Dev/mq-iot-edge/node_modules/pg/lib/connection.js:105:22)\n    at emitOne (events.js:77:13)\n    at Socket.emit (events.js:169:7)\n    at readableAddChunk (_stream_readable.js:146:16)\n    at Socket.Readable.push (_stream_readable.js:110:10)\n    at TCP.onread (net.js:523:20)",
  "name": "error",
  "length": 83,
  "severity": "ERROR",
  "code": "42601",
  "position": "77",
  "file": "scan.l",
  "line": "1053",
  "routine": "scanner_yyerror"
}`

My sql query is:

`insert into device_tokens (device_token, device_type, org_id, uid) values ($<token>, $<type>, $<orgId>, $<userId>) returning device_token`

I'm able to use QueryFile for a simple select query that does not have any named parameters, so QueryFile does not seem to be the obvious culprit.

**Comment by jordansnyder** [comment]
Stupid mistake on my part, I was calling

`return t.one(app.services.datastore.pg._sql('insertDeviceTokenRecord.sql', paramObject));`

when it should be 

`return t.one(app.services.datastore.pg._sql('insertDeviceTokenRecord.sql'), paramObject);`

**Comment by vitaly-t** [comment]
If you are really using `QueryFile` like this:
```js
return t.one(app.services.datastore.pg._sql('insertDeviceTokenRecord.sql'), paramObject);
```
that is wrong, because as per documentation [here](https://github.com/vitaly-t/pg-promise#query-files):

>You should only create a single instance of QueryFile per file, and then use that instance throughout the application.

and [here](http://vitaly-t.github.io/pg-promise/QueryFile.html):

>For any given SQL file you should only create a single instance of this class throughout the application.

Also see [pg-promise-demo](https://github.com/vitaly-t/pg-promise-demo) for a good example of how it should be used, although it is mostly highlighted [here](http://vitaly-t.github.io/pg-promise/QueryFile.html) as well.

**Comment by jordansnyder** [comment]
Thanks I appreciate the advice...I have seen that, but this is development code just to get things working at a basic level. I will be refactoring today and building a module to load the files, similar to what your examples show.

js
