### ISSUE TITLE
Add https:// to link in About section

### ISSUE THREAD

**Issue by roessland** [vitaly-t/pg-promise#865]
On the front page of the GitHub repo, the homepage/documentation link is `http://vitaly-t.github.io/pg-promise`.

Please add `https://` to the URL to very slightly improve security and to remove `Not Secure` complaints by browsers.

<img width="534" alt="image" src="https://user-images.githubusercontent.com/210712/212858042-6d41820c-a9b3-4342-9f1c-8e6cc5b1366f.png">

**Comment by vitaly-t** [comment]
Done.

**Comment by roessland** [comment]
Wow, that was quick 🥇 Thanks!
