### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by jcristovao** [vitaly-t/pg-promise#87]
Hey,

I don't know if anybody else would appreciate this, but being a TypeScript adept I endeded up doing some definitions for this library.

They're in alpha stage, without 100% coverage - but enough for the more common cases:

https://github.com/jcristovao/pg-promise/blob/master/pg-promise.d.ts

Is this something that you might consider including on pg-promise itself, or should I do it in a separate repo? (I think it might still be a bit too soon to submit them to DefinitelyTyped)..

Thanks
João

**Comment by vitaly-t** [comment]
All the different dialects is a matter of personal preference. I for one, never used TypeScript, always stick to the JavaScript.

Some libraries do include more than one dialect in the same project, others publish them as separate repos. In this case, since I'm not a TypeScript developer at all, the second one seems more appropriate. I would be in no position to support it anyway.

I will have no problem listing it on the project's main page.

**Comment by jcristovao** [comment]
Alright! I'll let you know as soon as I publish it.
Thanks

**Comment by vitaly-t** [comment]
Alright. I just went through the script, it looks definitely out of my experience, although I think it is still missing many things there...

Just a few examples:
* queryResult type
* task/tx interface
* QueryResultError type
* TransactionMode type

It is easier to see by looking at the [API](http://vitaly-t.github.io/pg-promise/index.html).

**Comment by vitaly-t** [comment]
@jcristovao I just noticed that the version you are trying to convert to TypeScript is quite old, and most importantly, it is prior to [3.0.5](https://github.com/vitaly-t/pg-promise/releases/tag/v.3.0.5), which saw major code restructuring.

I would suggest relying either on the very latest release or the current master branch.

**Comment by jcristovao** [comment]
Yes, I am quite aware it is missing some stuff, that's part of the reason I am open sourcing it - I don't need those features right now, but perhaps someone else might want to help :)

Regarding the 3.0.5, yes, you are right, and I had forgot about that... oh well, perhaps next week I'll have some time to take a new look at it!

**Comment by vitaly-t** [comment]
@jcristovao any progress there? ;)

**Comment by jcristovao** [comment]
Not really, I think it will still take me somedays till I look at this again :(

**Comment by vitaly-t** [comment]
@jcristovao left a comment here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8421
