### ISSUE TITLE
Using Promise.all inside tx() causes inconsistent data state

### ISSUE THREAD

**Issue by alexeych0** [vitaly-t/pg-promise#894]
### Expected behavior

No data committed into the database if any error thrown inside the transaction block `db.tx`

### Actual behavior

Some changes are committed although the transaction is rollbacked

```
db_test=# select * from public.test;
-[ RECORD 1 ]
value | 6
```

### Steps to reproduce

SQL DDL:

```sql
create table public.test (
    value int
);
```

Node.js code:

```js
const pgp = require('pg-promise')();
const db = pgp({
    host: 'localhost',
    port: 5432,
    user: 'postgres',
    password: '123',
    database: 'db_test',
    ssl: false,
});


const insertQuery = "insert into public.test (value) VALUES (${v});";

(async () => {
    let values = Array(10).fill().map((e, index) => index + 1);

    try {
        db.tx('my-transaction', async (t) => {
            await Promise.all(values.map(async (v) => {
                await new Promise(resolve => setTimeout(resolve, 1000));

                if (v == 5) {
                    throw new Error('test');
                }
                await t.query(insertQuery, {v});
            }));
        });
    } catch (error) {
        console.log('Error', error);
    }

    await new Promise(resolve => setTimeout(resolve, 10000));

})();

```

### Environment

* Version of pg-promise: ^11.5.4
* OS type (Linux/Windows/Mac): Mac OS Sonoma
* Version of Node.js: v18.16.0

**Comment by vitaly-t** [comment]
`Promise.all` is not compatible with transaction logic, as [explained here](https://github.com/vitaly-t/pg-promise/wiki/Common-Mistakes#tasks-versus-rootdirect-queries).

**Comment by alexeych0** [comment]
Thank you for the link, but it doesn't explain the encountered behaviour.

Does every promise of `Promise.all` inside the `tx` function allocate different database connection? If not, then `v == 6` shouldn't has been inserted, since the failed promise is run inside the same transaction. If yes, then why `v == 6`**only** is inserted, but `v == 7,8,9` are not?

**Comment by vitaly-t** [comment]
You have timer there, you have `Promise.all`, that's a lot of an asynchronous race, I wouldn't try to make sense out of what values appear first and why.

**Comment by vitaly-t** [comment]
I'm closing the issue, because it is no issue here, just invalid use of transactions.

**Comment by alexeych0** [comment]
It seems like the whole problem is caused by `.map()` function. Since the `Error` is thrown inside its callback, there is no way for `tx()` method to know about it.

Couple of two different cases.

#### Case 1

I removed the timeout and used `Promise.allSettled` instead of `Promise.all`

```
await db.tx(async t => {
    await Promise.allSettled(values.map(async (v) => {
        console.log('v', v);
        if (v == 5) {
            throw new Error('test');
        }
        return t.query(insertQuery, {v});
    }));
});
```

The output is that every value is inserted except `v == 5`

#### Case 2.

Collecting all the promises in the array and then using `for` loop.

```
await db.tx(async t => {
    let queries = [];

    for (let v of values) {
        queries.push(new Promise(async (resolve, reject) => {
            await new Promise(resolve => setTimeout(resolve, 1000));

            if (v == 5) {
                throw new Error('test');
            }
            await t.query(insertQuery, {v});
            resolve();
        }));
    }
}

await Promise.all(queries);
```

The output is as expected - nothing is inserted. It works well even with `Promise.all` instead of `Promise.allSettled` and even with the timeout inside the promise.

**Comment by vitaly-t** [comment]
It's good that you found the culprit. Async code inside transaction can get quite complicated.
