### ISSUE TITLE
A question about the query

### ISSUE THREAD

**Issue by milabs** [vitaly-t/pg-promise#90]
Hello,

Is it possible to use the following construction:

```
var values = {
  a: 1, b: true, c: 'hello'
};

db.query("INSERT INTO table (%KEYS%) VALUES (%VALS%)", values) ...
```

By `%KEYS` and `%VALS%` I meant the `values` object keys and their values that automatically binds to the query.

**Comment by vitaly-t** [comment]
Not directly. But this library has very powerful query formatting engine, using which you can easily generate any kind of queries dynamically.

```js
var pgp = require('pg-promise');

function insert(table, values) {
    var keys = Object.keys(values);
    return pgp.as.format('INSERT INTO $1~($2^) VALUES($3^)', [
        table,
        keys.map(p=>pgp.as.name(p)).join(', '),
        keys.map(p=>'${' + p + '}').join(', ')
    ]);
}

var values = {
    a: 1, b: true, c: 'hello'
};

var query = insert('Table Name', values);
console.log(query);
```
Output:
```
INSERT INTO "Table Name"("a", "b", "c") VALUES(${a}, ${b}, ${c})
```

**Comment by milabs** [comment]
Thanks for the explanation. It's really powerful. Why not to add this helper function to the library? Don't think that my case is unique...

**Comment by vitaly-t** [comment]
> Why not to add this helper function to the library?

Too many variations, it is not generic enough.

Examples:

* insert that returns a raw/value would end with something like `RETURNING *`/`RETURNING id`
* insert that uses an internal `SELECT` as the source of values
* multi-value insert, see [Performance Boost](https://github.com/vitaly-t/pg-promise/wiki/Performance-Boost)

**Comment by milabs** [comment]
OK, but wouldn't it useful to have something like `pgp.as.keys()` and `pgp.as.vals()`? Anyway, as your answer has the solution it would be nice to have faq/wiki reference for that.

**Comment by vitaly-t** [comment]
Those would have little value as separate functions.

For example:

```js
function getKeyNames(values) {
    return Object.keys(values).map(k => pgp.as.name(k)).join(', ');
}
```

But the important part would be to use the same list of keys (sometimes you may want to filter them).

Anyway, I'll think about it.

**Comment by milabs** [comment]
Just for the possible supposition of query formatting it may be useful to have something like:

```
db.query("INSERT INTO table(@1~keys) VALUES(@1~vals)", obj)
```
Where `@1~keys` and `@1~vals` is the first object's keys and their values. Strictly speaking, `~keys` and `~vals` are not needed there, but check for paired `@1` / `@1` tokens required.

**Comment by vitaly-t** [comment]
This library doesn't support syntax like `@1~keys`. It supports syntax `$1~` for inserting an sql name/identifier. The current syntax allows easy custom formatting, see [Custom Type Formatting](https://github.com/vitaly-t/pg-promise#custom-type-formatting).

The current formatting is already advanced enough, most users don't use all its nice features. I wouldn't consider advancing it further.

**Comment by milabs** [comment]
Ok

**Comment by vitaly-t** [comment]
There is a further progress with this in [4.0.6 update](https://github.com/vitaly-t/pg-promise/releases/tag/v.4.0.6) ;)

**Comment by vitaly-t** [comment]
**UPDATE:**
There is lots more the library offers now with the [helpers namespace](http://vitaly-t.github.io/pg-promise/helpers.html) when it comes to automatic query generation for `INSERT` or `UPDATE` operations.

**Comment by vitaly-t** [comment]
Syntax for SQL Names has been extended in [v.5.2.1](https://github.com/vitaly-t/pg-promise/releases/tag/v.5.2.1), to support enumeration of keys.

**Comment by vitaly-t** [comment]
Within the latest release, filter `:csv` / `:list` will enumerate values. See [CSV Filter](https://github.com/vitaly-t/pg-promise#csv-filter).

```js
const obj = {first: 123, second: 'text'};
db.none('INSERT INTO table($1:name) VALUES($1:csv)', [obj])
//=> INSERT INTO table("first","second") VALUES(123,'text')
```
