### ISSUE TITLE
BUG - JSON and JSONB cast on update helper

### ISSUE THREAD

**Issue by thar0x29a** [vitaly-t/pg-promise#901]
### Scenario
We have a table with 2 fields (id, content), where content is an jsonb field which we need to update from time to time.

### Expected behavior
Wed call `pgp.helpers.update` with our data rows and column set. We will get an String simular to 
```sql
update "table" as t 
set "uid"=v."uid","content"=v."content"::jsonb
from (values('the uid value', '{"foo":"baa"}'))
```

### Actual behavior
```sql
update "table" as t 
set "uid"=v."uid","content"=v."content"
from (values('the uid value', '{"foo":"baa"}'))
```
The jsonb cast is missed behind `content` is missed. This leads to an jsonb expected but string found error. It is missed even if our column set:

1. has the mod `:json`
2. has the cast `jsonb` 

or both. 

### Steps to reproduce
As written above. No rocket science, but I could prepare an full example if really, really needed.
In the end the whole error is easy to understand. To me it looks like this is an use case that simply had not been covered. Since it's solution is simply adding an cast to the set I dont expect it to be a big thing eighter. 

### Environment
Linux NodeJS v12.22.9, but should not matters since this seems to be an logic issue. 

* Version of pg-promise:  11.5.4
* OS type (Linux/Windows/Mac):  Linux
* Version of Node.js: v12.22.9

**Comment by vitaly-t** [comment]
If you specify the casting in the source ColumnSet, it works just fine. Must be something wrong in your code. Please include a complete code example.

**Comment by thar0x29a** [comment]
```js
const cols = ['uid', {name:"content", mod:":json", cast:"jsonb"}, '?key'];
const cs = new pgp.helpers.ColumnSet(cols, {table:{table, schema}});
let rows = [{uid:'abc', key:'abc', content:{foo:'baa'}}];

const q = pgp.helpers.update(rows, cs);
```
In the original def content was just given as string. So without any additional parameters. 
Due to the update strategy you open this value field with all the row contents. Content is a string there. And thats okay with me. But without a cast I run into that error.

**Comment by thar0x29a** [comment]
Okay. Im Sorry. It seems that the "cast" really did the job. Just on another position then where I thought. Thanks for that tesponse
