### ISSUE TITLE
json formatting issue on update

### ISSUE THREAD

**Issue by MathiasHaudgaard** [vitaly-t/pg-promise#902]
Hello there. Thanks for this awesome library you've built. 
I have a problem updating a jsonb column in postgres.

### Steps to reproduce

I have the following code where I try to update the column `attributes` with a json array. 

```typescript
const cs = new pgp.helpers.ColumnSet(
      [
        '?id1',
        '?id2',
        '?id3',
        {
          name: 'attributes',
          mod: ':json',
        },
      ],
      {
        table: 'myTable',
      }
    );
    const query = pgp.helpers.update(requestObjs, cs)
     + ' WHERE v.id1 = t.id1 AND v.id2 = t.id2 AND v.id3 = t.id3';
    const res = await db.none(query);
```

the data I used for testing:

```json
[
    {
        "id1": 1,
        "id2": 2,
        "id3": 3,
        "attributes": [{"bob": 1}]
    }

]
```

### Expected behavior
I expected the result to update the rows where it matches the ids. I've used `{name: 'attributes',mod: ':json'}` with the insert method which worked out fine. 

### Actual behavior
I get the following error:
`ERROR	error: column "attributes" is of type jsonb but expression is of type text`
It seems like the formatting is not working as expected but I might be wrong.

### Environment

* Version of pg-promise: 11.5.0
* OS type (Linux/Windows/Mac): Linux (runs on an aws lambda function)
* Version of Node.js: 16

**Comment by vitaly-t** [comment]
You need to figure out what in the final query isn't as expected, before any suggestion is possible.

**Comment by MathiasHaudgaard** [comment]
Well, it isn't expected that the query throws the error since I expected the formatting to work. It seems like the formatting doesn't work for the update() method, but I might be wrong. It works for the insert() method though.

**Comment by vitaly-t** [comment]
> Well, it isn't expected that the query throws the error since I expected the formatting to work. It seems like the formatting doesn't work for the update()

You provide invalid input for `ColumnSet`, you get errors thrown for thus incorrect query. The formatting works as specified.

**Comment by vitaly-t** [comment]
Closing due to lack of details. Invalid formatting can only be addressed based on query vs expectation, which the euthor did not provide.
