### ISSUE TITLE
How to connect to serverless redshift using IAM permissions

### ISSUE THREAD

**Issue by bstienstra** [vitaly-t/pg-promise#909]
I'm trying to connect pg-promise to a serverless redshift instance and I cannot figure out how to do it. 

Serverless redshift uses role based authentication.

I can assume the identity of a role that can access Redshift using the Redshift dataAPI.  

I can call GetCredentialsCommand( {"dbName":"srvls2","durationSeconds":3600,"workgroupName":"serverless-redshift-workgroup"}
{
  "host": "serverless-redshift-workgroup.[REDACTED].us-east-1.redshift-serverless.amazonaws.com",
  "port": 5439,
  "database": "srvls2",
  "user": "IAMR:redshift-test-role-srvls2",
  "ssl": true
}

The User is basically the role my lambda is running under.  I'm not sure how to use this info in pg-promise.

This is what I currently have:

const dbc = pgp( {  capSQL: true, } );
const cn = {
			 	host: this.config.host,   
			 	port: this.config.port,
			 	database: this.tenantId,
			 	user: response.user,           // returned from GetCredentialsCommand 
			 	ssl: true,
			 };
this.connection = dbc(cn);

The result of this connection attempt is always 
error: IAM authentication failed for user "IAMR:redshift-test-role-srvls2"

I feel like I should have to pass in the credentials from the assume role command into pgp somehow.

**Comment by vitaly-t** [comment]
This library simply passes all connection details into the [underlying driver](https://github.com/brianc/node-postgres). I suggest inquiring against that library instead. And I am not familiar with your environment to advise anyway.

**Comment by vitaly-t** [comment]
Closing, as there was no response, plus it is not very applicable here.
