### ISSUE TITLE
A question about the batch queries

### ISSUE THREAD

**Issue by milabs** [vitaly-t/pg-promise#91]
Is it possible to pipeline results of queries while running in batch mode?

For example, let's suppose that I have 2 queries:
```
INSERT INTO users (name) VALUES ("vasya") RETURNING id;
INSERT INTO nicknames (user,nickname) VALUES (${vasyaId},"pupkin");
```

So the question is about possibility of using `id` from the first query in the second query without needing of explicit pass the value to the query?

```
var q1 = db.one("INSERT INTO users (name) VALUES ($1) RETURNING id", "vasya");
var q2 = db.one("INSERT INTO nicknames (user,nickname) VALUES ($1, $2)", [ first_query_row.id?, "pupkin"] );

db.batch([q1, q2]);

```

**Comment by milabs** [comment]
The question is no longer actual for me as I've found the [workflows](https://github.com/vitaly-t/pg-promise/wiki/Workflows) wiki page. Tasks are great.

**Comment by vitaly-t** [comment]
See [Tasks examples](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#tasks). Specifically the ES6 generator version is nice ;)

**Comment by vitaly-t** [comment]
P.S. Since you've just started looking through the library, have a look at [pg-promise-demo](https://github.com/vitaly-t/pg-promise-demo) ;)

**Comment by milabs** [comment]
Thanks. Great library.
