### ISSUE TITLE
Cannot read properties of undefined (reading 'split')

### ISSUE THREAD

**Issue by matanelMor01** [vitaly-t/pg-promise#910]
### Expected behavior
cypress should be able to connect to postgres server using pg-promise

### Actual behavior
Test fails - Cannot read properties of undefined (reading 'split') in [node_modules/pg-promise/lib/index.js:11:16](http://localhost:53260/__/#)

### Environment

* Version of pg-promise: 11.5.4
* OS type (Linux/Windows/Mac): Mac
* Version of Node.js: v20.10.0

**Comment by vitaly-t** [comment]
What is cypress? What tests are failing? Not of this library, I presume. I don't understand why you opened this issue here instead of that cypress, whatever it is. There is nothing here to procede with.
