### ISSUE TITLE
pgp.as.format adds additional parenthesis around variable

### ISSUE THREAD

**Issue by izhyvaiev** [vitaly-t/pg-promise#918]
### Expected behavior

`pgp.as.format('ST_MakePoint($1, $2)', [-73.9825681, 40.7313474])'` outputs `'ST_MakePoint(-73.9825681, 40.7313474)'`

### Actual behavior

`pgp.as.format('ST_MakePoint($1, $2)', [-73.9825681, 40.7313474])'` outputs `'ST_MakePoint((-73.9825681), 40.7313474)'`

### Steps to reproduce

call `pgp.as.format('ST_MakePoint($1, $2)', [-73.9825681, 40.7313474])'` 

### Environment

* Version of pg-promise: 11.5.5
* OS type (Linux/Windows/Mac): Linux and Windows confirmed. Mac - not tested
* Version of Node.js: reproduces on both 18.16.0 and 18.19.1

**Comment by vitaly-t** [comment]
This is the now expected behavior, as per [this fix](https://github.com/vitaly-t/pg-promise/discussions/911).
