### ISSUE TITLE
Vulnerabilty: Sql injection when using columnset. 

### ISSUE THREAD

**Issue by adambeck7** [vitaly-t/pg-promise#919]
### Expected behavior
When I send a payload of `"example_user_id'||pg_sleep(1)--"` I would expect it to be parameterized and as such inserted harmlessly into my table. 

### Actual behavior
pg_sleep is executed and my postgres db goes to sleep. 

### Steps to reproduce
```js
        const stagingValues = [{ uid: "example_user_id'||pg_sleep(1)--" }];
        const stagingCs = new pgp.helpers.ColumnSet(
          ["uid"],
          {
            table: {
              table: "test",
              schema: "public",
            },
          }
        );
        const query = pgp.helpers.insert(stagingValues, stagingCs);

        try {
          await pool.any(query);
        } catch (error) {
          console.log("error writing to postgres", error);
        }
```

I very well may not be composing my query properly so let me know if it's a _me_ problem. 

### Environment

* Version of pg-promise: 11.5.5
* OS type (Linux/Windows/Mac): Mac
* Version of Node.js: 16.13.0

**Comment by vitaly-t** [comment]
I tried your example, and it just executes fine, and that string appears in the table, no issues there. 

There must be something else.

**Comment by adambeck7** [comment]
You're correct, it does appear in the database, but if you watch the sessions in pgAdmin, it does go to sleep, so it seems like it's acknowledging the command, no? 

![Screenshot 2024-04-03 at 3 17 16 PM](https://github.com/vitaly-t/pg-promise/assets/18033909/5a5da7c2-ffa5-46a6-8438-0ec662b690b2)

**Comment by adambeck7** [comment]
Also, sorry, here is the query string produced. 
`INSERT INTO "public"."test"("uid") VALUES('example_user_id''||pg_sleep(1)--')`

**Comment by adambeck7** [comment]
If I remove the trailing single quote after `example_user_id` the db does not go to sleep.

**Comment by vitaly-t** [comment]
I have tried various things, according to what you wrote here, and I cannot reproduce the issue :|

**Comment by vitaly-t** [comment]
> What node version and pg version are you running

Node v20.11.0, pg-promise v11.5.5, PostgreSql server v14, v16

**Comment by adambeck7** [comment]
And are you running it logged in as the postgres superuser/root?  (I know this wouldn't be best practice, just wanted to make sure your postgres user has the permissions needed to trigger the sleep) 

Once I get into work, I'll build the standalone app to confirm. Thanks!

**Comment by vitaly-t** [comment]
I am connecting to the database using the default `postgres` admin user.

**Comment by adambeck7** [comment]
I set up the new project, and it indeed doesn't happen. I'm at a loss as to how it is happening in the other, since the config and execution are exactly the same. Closing the issue, sorry about that.
