### ISSUE TITLE
formatting columns as a different type

### ISSUE THREAD

**Issue by nlf** [vitaly-t/pg-promise#92]
what i mean by this, is that if you need to format a variable in a query as something other than what pg-promise guesses that data is, it's difficult.

say you have a table with a json/jsonb column named "names", and you'd like to store an array of strings to that column. you can't do `INSERT INTO "table" ("names") VALUES ($[names_param])` because pg-promise formats the array as a type of `text[]` rather than `json`, which for the majority of cases is probably correct. however, if you're storing an array in a json column it will fail because postgres can't coerce `text[]` to `json`.

you can work around this by either running `JSON.stringify()` on the `names_param` first, which then causes the query to pass the value as text and postgres will coerce that to json without issue. you can also use the `pg.as.json` method to format the parameter, also ahead of time. it's annoying, but it works.

what i would be interested in seeing, is some way of passing the format to be used for a column as part of the query. we already have `$[param]` for standard formatting, and `$[param^]` for raw values, what if we had something like `$[param:json]` to tell pg-promise that this value should be formatted as json?

**Comment by vitaly-t** [comment]
What you are describing has been available for a while, as [Custom Type Formatting](https://github.com/vitaly-t/pg-promise#custom-type-formatting).

You simply wrap your non-standard types into a self-formatting class or object.

Example:
```js
var pgp = require('pg-promise');

function MyJsonArray(data) {
    this._rawDBType = true;
    this.formatDBType = function () {
        return pgp.as.json(data);
    }
}

var test = new MyJsonArray([1, 'two']);

var s = pgp.as.format("FORMAT: $1", test);

console.log(s);
```
Output:
```
FORMAT: '[1,"two"]'
```

**Comment by nlf** [comment]
I don't see how extending the object is any better than running JSON.stringify on it. Both require manual modification of the input parameters. What I'm talking about is enabling the definition of that format in the query instead.

**Comment by vitaly-t** [comment]
>Both require manual modification of the input parameters

No, see the code example again. The custom type formatting doesn't require any manual modification, its result is the output of the standard variables, as shown in the example.

**Comment by nlf** [comment]
I mean the parameters being input, in your example 'test'. Doing asJsonArray(test) is no different than doing JSON.stringify(test). I don't always have control over the input parameter, but I do have control over the query. If I can set the format type in the query it would make things much simpler

**Comment by vitaly-t** [comment]
What you are looking for is exactly the manual mode, while what I suggested is the automatic mode hence the confusion...

Perhaps in your case the manual call to `as.json` is the best option then. It is not likely that I would be extending the manual formatting overrides, too many variations. Custom Type Formatting is what's usable in most cases, yours is quite unique, if you can't simply extend the array object once you get the data.

**Comment by nlf** [comment]
The current manual mode operates on the *input*, I want to define the formatting in the *query*. For example:

Instead of
`query('INSERT INTO "table" ("column") VALUES ($[value])', { value: pgp.as.json(input) })`
note that the formatting is done in the *input parameters*

I want to do
`query('INSERT INTO "table" ("column") VALUES ($[value:json])', { value: input })`
note how in this case I'm specifying the format for the column as part of the *query* rather than manipulating the input parameters.

**Comment by vitaly-t** [comment]
I know what you mean, but this isn't supported as of now, not sure if will ever be. It's all manual formatting, just from a different side.

**Comment by nlf** [comment]
would you accept a pull request adding this feature?

**Comment by vitaly-t** [comment]
I would do it myself (since I do everything with lots of tests + documentation), if I thought of it as a necessity, not quite sold on that one :)

**Comment by nlf** [comment]
where this came up for me was in using the SQL file feature. i have several SQL files that do an INSERT (very similar to the example above, where i have a JSON column that i'm storing an array in). I'm passing user input straight to these SQL files with a simple method.

without the ability to specify the format of a parameter in the query itself, i have to document and inform users that they must stringify or otherwise format their input before passing it to the method. this is incredibly unfriendly for the user, so i was hoping to come up with a solution at the pg-promise level that would resolve my concerns as well as hopefully helping someone else out further down the road.

if you think it's not worth adding, i'll have to implement it on my end and wrap all the calls to the SQL files with another method to adjust the formatting.

**Comment by vitaly-t** [comment]
By any chance can this be remedied by the recent addition of the partial formatting support?

It was introduced in [version 3.2.0](https://github.com/vitaly-t/pg-promise/releases/tag/v.3.2.0).

If it is just a sub-parameter within your SQL file, then it is exactly what parameter `params` solves in the latest release of the [QueryFile](http://vitaly-t.github.io/pg-promise/QueryFile.html).

**Comment by nlf** [comment]
the partial formatting is applied before the user's input though, isn't it? the documentation says it's for static parameters. the parameters i need to apply specific formatting to are dynamic and passed in by the user

**Comment by vitaly-t** [comment]
yeah, those are static once, to be applied only after loading the SQL.

**Comment by nlf** [comment]
yeah, so that wouldn't work for my use case then

**Comment by vitaly-t** [comment]
Ok, maybe the partial formatting itself will be of help at least. You can pre-format the query dynamically now (in fact as many times as needs to be). That's the last ace I can throw back at ya :)

**Comment by nlf** [comment]
but doing so i still need to manually specify the format for the user's input, don't i?

**Comment by vitaly-t** [comment]
yep.

**Comment by nlf** [comment]
so that still leaves me in the same position, having to alter the user's input or require them to do it themselves. doesn't really help.

**Comment by vitaly-t** [comment]
looks that way ;)

**Comment by vitaly-t** [comment]
@nlf I have extended the formatting syntax with the following additions:

* `:raw` = `^`
* `:name` = `~`
* `:json` - is what you were looking for.

The code has been checked in for 2.3.1, but it still needs a number of tests. Not sure when I will finalize the tests.

**Comment by nlf** [comment]
Wow, thanks! I thought I was going to have to do it in my own code this morning. This is great!

Curious what your thoughts are about having one of these options for every format? Seems like if one is supported might as well support them all

**Comment by vitaly-t** [comment]
I don't see why suddenly change data types into something else. JSON is a special case, I think.

**Comment by nlf** [comment]
I agree, it just seemed nice for consistency purposes. I do have a use case for a :csv but everything else is simple enough it's not needed

**Comment by vitaly-t** [comment]
CSV - that is interesting...

**Comment by nlf** [comment]
i use it for IN queries, like:

`query('SELECT * FROM "table" WHERE "some_column" IN ($[items])', { items: pgp.as.csv(['one', 'two', 'three']) })`

**Comment by vitaly-t** [comment]
This has been released as [version 3.2.1](https://github.com/vitaly-t/pg-promise/releases/tag/v.3.2.1)

Both `:json` and `:csv` are supported.

Do not mind the broken build status, Travis CI is down at the moment.

**Comment by nlf** [comment]
awesome! thank you!

**Comment by vitaly-t** [comment]
you are welcome!

**Comment by vitaly-t** [comment]
@nlf I gave it some serious refactoring within [version 3.2.2](https://github.com/vitaly-t/pg-promise/releases/tag/v.3.2.2) ;)

**Comment by vitaly-t** [comment]
@nlf how did you get along with that change? Is everything working for you as expected?

**Comment by nlf** [comment]
Yes, it's working perfectly. Thanks again

**Comment by vitaly-t** [comment]
@nlf that's good :) I went through all the recent changes you made but didn't see any use of this new syntax, that's why I asked. Did I somehow miss it or is it still in the pipeline?

**Comment by nlf** [comment]
it's being used in raw queries in a private project that consumes muckraker, so yeah you won't be able to see it here. i can definitely verify it's working perfectly though

**Comment by vitaly-t** [comment]
@nlf I hope [this new feature](https://github.com/vitaly-t/pg-promise/releases/tag/v.3.3.0) won't affect your library ;)

**Comment by WestleyArgentum** [comment]
Thank you both so much for going through all of this -- just ran into the need for `:json`, super pleased it exists now

**Comment by vitaly-t** [comment]
F.Y.I. Important breaking change in [v6.5.0](https://github.com/vitaly-t/pg-promise/releases/tag/v.6.5.0).
