### ISSUE TITLE
Issue with Postgres Version 16

### ISSUE THREAD

**Issue by abelabbesnabi** [vitaly-t/pg-promise#929]
There seems to be an issue using pg-promise against a Postgres database version 16

{
  "error": "error: no pg_hba.conf entry for host \"*.*.*.*\", user \"*\", database \"*\", no encryption",
  "length": 169,
  "severity": "FATAL",
  "code": "28000",
  "detail": undefined,
  "hint": undefined,
  "position": undefined,
  "internalPosition": undefined,
  "internalQuery": undefined,
  "where": undefined,
  "schema": undefined,
  "table": undefined,
  "column": undefined,
  "dataType": undefined,
  "constraint": undefined,
  "file": "auth.c",
  "line": "542",
  "routine": "ClientAuthentication",
  "code": 5,
  "route": {
    "version": 1,
    "key": "getSettings",
    "func": "public.\"getSettings\"",
    "params": {
      "params": "[Object]"
    }
  }
}

**Comment by vitaly-t** [comment]
That's your local connection configuration issue, and is not applicable to this driver.

**Comment by abelabbesnabi** [comment]
Tryed it both locally and on AWS. Postgres v.16 doesn't work.

**Comment by vitaly-t** [comment]
This library includes CI that runs against PostgreSQL v16, without issues. As I posted earlier, your issues are with the connection details for your hosting.
