### ISSUE TITLE
pgp.helpers.insert: table should accept fully qualified name as a string

### ISSUE THREAD

**Issue by jmealo** [vitaly-t/pg-promise#931]
### Expected behavior

```javascript 
pgp.helpers.insert(..., ..., 'schema.table'); 
pgp.helpers.insert(..., ..., 'database.schema.table');
```

If fully qualified table names aren't allowed, this should throw telling you to pass it as an object.

### Actual behavior
The entire table name is quoted, causing hard to track down issues about the relation not existing.

### Steps to reproduce
Try to pass a fully qualified table name as a string.

### Environment

* Version of pg-promise: latest
* OS type (Linux/Windows/Mac): Mac
* Version of Node.js: 20

**Comment by vitaly-t** [comment]
Dots are allowed within table names, so there is nothing to throw an error about. You just need to use `TableName` object when `schema.table` are used.

Also, there is no such thing as `database.schema.table` in PostgreSQL. Databases are represented only by the connection.

**Comment by vitaly-t** [comment]
And you can always use your own way of processing table names like that. Below is an example of splitting such table names:

```ts
function _T(data: TemplateStringsArray) {
    const [schema, table] = data[0].split('.');
    return {table: {table, schema}};
}
```

Usage example:

```ts
const cs = new pgp.helpers.ColumnSet([
    'id', 'name'
], _T`schema.table`);
```

**Comment by jmealo** [comment]
So it doesn't support fully qualified names? The kind that work via the SQL interface? You introduced your own incompatible with the actual database API? 

https://www.postgresql.org/docs/current/ddl-schemas.html

**Comment by vitaly-t** [comment]
This library does not parse schema from table for query generation, which is not needed there. And it handles `schema` separately, because it is needed for easy separation when any schema override is used, so it can be switched easily.

In your comments, you seem to tie together unrelated things, for something that you want. I gave the solution to your original post - use of `TableName` type to wrap table + schema easily.

**Comment by jmealo** [comment]
@vitaly-t: Thanks for your patience. I have a fever and troubleshooting this took longer than I'd like. I guess there's no good option to avoid this foot canon. Your implementation is pragmatic. Closing now.

**Comment by vitaly-t** [comment]
Following this, I included helper [_TN](https://vitaly-t.github.io/pg-promise/helpers.html#._TN) into v11.7.0 of the driver :wink:
