### ISSUE TITLE
Adjust Margin for Sidebar and Content Area in Documentation Site

### ISSUE THREAD

**Issue by SahilDhingraa** [vitaly-t/pg-promise#938]
issue:
![image](https://github.com/vitaly-t/pg-promise/assets/92306979/ae1611ec-0701-4cdb-8c55-0eef24f4fdce)

**Comment by vitaly-t** [comment]
Could you, please, provide details of the environment? I want to be able to reproduce the issue. Simply adding the extra margin created way too large a margin on my Windows machine, that doesn't look right, so I had to roll the change back.

**Comment by SahilDhingraa** [comment]
my screen size is 1920x1080px

**Comment by vitaly-t** [comment]
You can re-open it, if you find a better solution; closing it for now.
