### ISSUE TITLE
cast datatype for anyelement parameter in stored procedures?

### ISSUE THREAD

**Issue by jl-** [vitaly-t/pg-promise#94]
Hello @vitaly-t ,
Is there a way to support casting the datatype of parameter passed to a stored procedures? Say I have a function in plpgsql
```sql
CREATE OR REPLACE FUNCTION get_account_details(
  col_name text, col_value anyelement,
  query_limit integer DEFAULT 10, query_offset integer DEFAULT 0,
  OUT account jsonb,  OUT profile jsonb
) AS $$
DECLARE
  command text;
BEGIN
  RAISE NOTICE 'col_name is %', col_name;
  RAISE NOTICE 'col_value is %', col_value;

  command := '
    SELECT
        row_to_json(a.*), row_to_json(p.*)
      FROM accounts a
      LEFT JOIN profiles p
        ON p.account_id = a.id
      WHERE
        a.%I = %L
        LIMIT %L OFFSET %L;
  ';
  EXECUTE format(command, col_name, col_value, query_limit, query_offset) INTO account, profile;
END;
$$ LANGUAGE plpgsql;
```

In psql command line:
```sql
-- works as expected
-- { account: { id: 1, username: 'someone' }, profile: { account_id: 1}}
SELECT get_account_details('id', 1);
SELECT get_account_details('username', 'someone'::text);

-- but this fails with unknown type
SELECT get_account_details('username', 'someone');
```
With pg-promise, 
```javascript
function test(col_name, col_value) {
  const params = [col_name, col_name === 'id' ? +col_value : col_value];
  return db.func('get_account_details', params, qrm.one);
}

test('id', 1)
// { account: { id: 1, username: 'someone' }, profile: { account_id: 1}}

test('username', 'someone') 
// failed with error: [error: could not determine polymorphic type because input has type "unknown"]
```
---

I guess here is the only way to make a type casting explicitly, and I tried:
```
 return db.one(`select get_account_details('${col_name}', '${col_value}'::text) as result`);
```
and it did return the data, but as a wrong structured string without the top 'account' and 'profile':
```json
{"result":"(\"{\"\"id\"\": 1, \"\"username\"\": \"\"someone\"}\",\"{\"\"account_id\"\": 1}\")"}
```
How can I get the result as a object with the 'account' and 'profile' wrapping?

Is there any workaround for this? I read through [the README for func](https://github.com/vitaly-t/pg-promise#functions-and-procedures) and search issues, but no luck.

Am I missing something?
Any tips? Thanks sincerely!

**Comment by vitaly-t** [comment]
You are mostly correct, and the only part that you are missing is not even related to the library, it is related to the difference in PostgreSQL of presenting results for the two cases:

* `SELECT FunctionName(...)`
* `SELECT * FROM FunctionName(...)`

You need to use the latter to get what you are expecting. Run the same commands against PGSQL, and you will understand the difference.

**Comment by jl-** [comment]
New to PostgreSQL, Long way to go..
You are right, `SELECT * FROM ...` works as expected, and I see the difference now. 
Thanks so much! :+1:

**Comment by vitaly-t** [comment]
N.P. ;)

**Comment by vitaly-t** [comment]
P.S.

About code like this one:
```js
return db.one(`select get_account_details('${col_name}', '${col_value}'::text) as result`);
```
you should never concatenate column values like this, because es6 template strings know nothing about proper formatting for postgresql, only the library knows how to do it. You will end up breaking your queries very often otherwise.

**Comment by jl-** [comment]
Thanks for reminding me of this, I'll definitely keep it in mind for any value formatting. :clap:

**Comment by vitaly-t** [comment]
This might be of help also: [Invalid query formatting with manual string concatenation and ES6 template strings](https://github.com/vitaly-t/pg-promise/wiki/Common-Mistakes#invalid-query-formatting-with-manual-string-concatenation-and-es6-template-strings)

**Comment by jl-** [comment]
After going through [pg.as.*](https://github.com/vitaly-t/pg-promise#conversion-helpers) and some of the source code in [formatting.js](https://github.com/vitaly-t/pg-promise/blob/master/lib/formatting.js), now I have a clearer view of the great formatting support with this lib. 
Tips listed in [Common Mistakes](https://github.com/vitaly-t/pg-promise/wiki/Common-Mistakes#invalid-query-formatting-with-manual-string-concatenation-and-es6-template-strings) are really helpful, I should definitely try out pg-monitor next. :100:
