### ISSUE TITLE
The upgrade to 11.9 broke my app in ways I can't quite understand.

### ISSUE THREAD

**Issue by paulhill** [vitaly-t/pg-promise#940]
### Expected behavior
npm upgrade from 11.8.0 to 11.9.0 with no impact.

### Actual behavior
Tests making calls to the database with zero values for decimals return null instead of zero, breaking tests.

### Steps to reproduce
Sorry I don't have a standalone use case. I'm still trying to understand what is happening.
It's very reproducable for me. Upgrade boom fails, downgrade, all is well. I'll try to find out more.

### Environment

* Version of pg-promise: 11.9.0
* OS type (Mac):
* Version of Node.js: 20

**Comment by paulhill** [comment]
On further inspection it appears that values being written as 0 that are going through TypeORM come back as null. 
And yes, it's very strange that upgrading pg-promise broke a call that isn't going through pg-promise but TypeORM. 
Perhaps it has something to do with the postgrsql driver update. It's super repeatable though. No other change other than the pg-promise version bump from all good to meltdown.
I'll keep digging.

**Comment by paulhill** [comment]
I've narrowed it down to decimals with zero values returning as nulls.
Still trying to figure out why.

**Comment by vitaly-t** [comment]
I'm confused how TypeORM and pg-promise can be both involved into this, they are two completely independent frameworks, they do not use each other.

**Comment by paulhill** [comment]
Yes, I know. It's hard to determine the link. Best I can figure is some shared transitive dependency has changed that is causing decimals with zero values to return as null. It's not a change in pg-promise logic so I wouldn't blame you if you said not your problem. I bring it up just because it is the pg-promise update that triggers it, and you might get folks have the same issue. It's pretty corner case. It's just where decimals used to return as zero they now return as null. I dug around in the dependency tree trying to upgrade things explicitly but can't seem to get the behaviour to revert.

**Comment by paulhill** [comment]
Ok I was able to reproduce the error with pg-promise 11.8 so it's some other dependency issue that I just tripped over during the upgrade. I'll close this issue.

**Comment by paulhill** [comment]
spoke too soon, reverting back to 11.8 and cleaning out the package lock fixed the issue again.

**Comment by paulhill** [comment]
After more digging it turns out it has to do with the typeParser setup. Something has changed there.

**Comment by vitaly-t** [comment]
I have looked into pg-types changes history, and I can see that nothing changed there in the last 6 months.

**Comment by vitaly-t** [comment]
> After more digging it turns out it has to do with the typeParser setup. Something has changed there.

It might be helpful to others to publish what you find before closing the issue? :wink:

**Comment by vitaly-t** [comment]
@paulhill Did you manage to get to the bottom of it?
