### ISSUE TITLE
Invalid or missing stream object: pg-query-stream >= v4.6.0 was expected

### ISSUE THREAD

**Issue by Le-dawn** [vitaly-t/pg-promise#943]
### Expected behavior
run pg-query-stream successfully

### Actual behavior
My code
```
const csv = CsvWriter();
const file = fs.createWriteStream(`./csv/${fileId}`);
const qs = new QueryStream(sql);
await db.stream(qs, s => {
    s.pipe(csv).pipe(file);
});
csv.end()
```
it gives this error
```
error TypeError: Invalid or missing stream object: pg-query-stream >= v4.6.0 was expected
    at t.exports (D:\project\server\nodejs\postgres-new\apps\postgres-new\.next\server\chunks\312.js:1:45026)
    at f.h (D:\project\server\nodejs\postgres-new\apps\postgres-new\.next\server\chunks\312.js:1:42396)
    at f.<anonymous> (D:\project\server\nodejs\postgres-new\apps\postgres-new\.next\server\chunks\312.js:1:44496)
    at D:\project\server\nodejs\postgres-new\apps\postgres-new\.next\server\chunks\312.js:1:10866
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async m (D:\project\server\nodejs\postgres-new\apps\postgres-new\.next\server\app\api\app\exportCsv\route.js:1:1315)
    at async D:\project\server\nodejs\postgres-new\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:34666
    at async eS.execute (D:\project\server\nodejs\postgres-new\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:25813)
    at async eS.handle (D:\project\server\nodejs\postgres-new\node_modules\next\dist\compiled\next-server\app-route.runtime.prod.js:6:35920)
    at async doRender (D:\project\server\nodejs\postgres-new\node_modules\next\dist\server\base-server.js:1377:42)
```

### Steps to reproduce

When I run in the dev environment(`npm run dev`), it is normal.

When I run in the prod environment(`npm run build` and `npm run start`), it gives this error

### Environment

* Version of pg-promise: 11.9.1
* OS type (Linux/Windows/Mac): Windows
* Version of Node.js: v20.16.0
* Version of pg-query-stream: 4.7.0

**Comment by vitaly-t** [comment]
That means your project uses but doesn't list `pg-query-stream` in the dependencies. This library has it in DEV dependencies, to run tests against it. If you are using that library, you must add to the list pf dependancies.

**Comment by Le-dawn** [comment]
I made sure it's in the dependencies:
![image](https://github.com/user-attachments/assets/0c864d94-730b-4d15-b93f-95ca3a992a96)
I found the following code in the pg-promise/lib/stream.js, I guess this is the reason, because the class name will be changed after executing npm run build, but I don't know how to solve it, thanks
![image](https://github.com/user-attachments/assets/6c3610cc-3391-4b43-9d40-b89ec86b70c6)

**Comment by vitaly-t** [comment]
This library requires that `pg-query-stream` version that you use is the same as the one it's tested against. The error log tells you that it is looking for `v4.6.0`, in accordance with the pg-promise version that you are using ;)

**Comment by vitaly-t** [comment]
There may be a breaking change in that stream library again, as before. Just switch to v4.6.0, and it should be fine ;)

**Comment by Le-dawn** [comment]
I actually tried to upgrade from version 4.6.0 to version 4.7.0, but these two versions do not work. Need your help, thanks
![image](https://github.com/user-attachments/assets/f88f20b1-e1bc-45ca-bc68-8b41cb4ff83e)

**Comment by vitaly-t** [comment]
If it works in DEV but not in PROD, that means only one thing - the right dependency is missing, somehow.

**Comment by Le-dawn** [comment]
I have also tried removing node_modules and .next but that didn't work either ;(

**Comment by Le-dawn** [comment]
I tried adding a console.log between
```
const qs = new QueryStream(sql);
```
and
```
await db.stream(qs, s => {
      s.pipe(csv).pipe(file);
    });
```
to print out the QueryStream constructor name, like the following image
![image](https://github.com/user-attachments/assets/832ded83-4ace-4176-9c63-7812cdddfe23)

and I got this result
![image](https://github.com/user-attachments/assets/203535bf-60a4-437d-853a-109784197f99)

so I guess this is the reason, thanks

**Comment by Le-dawn** [comment]
I changed the code to
```
    const csv = CsvWriter();
    const file = fs.createWriteStream(`./csv/${fileId}`);
    const qs = new QueryStream(sql);
    const client = await db.$pool.connect()
    const stream = await client.query(qs) as any
    stream.on('end', client.release)
    stream.pipe(csv).pipe(file)
    csv.end()
```
and it works in PROD

**Comment by vitaly-t** [comment]
That code is leaking connections when you call ` db.$pool.connect()` and never release it. I will check later what's wrong in general there.

**Comment by Le-dawn** [comment]
I think at `stream.on('end', client.release)` it will release the connections. any help. thanks
