### ISSUE TITLE
support for PoolClient

### ISSUE THREAD

**Issue by xyn22** [vitaly-t/pg-promise#946]
The documentation lacks support for connection pooling.

I use `query` on `PoolClient`:

```
const pool = new Pool({
  host,
  port,
  user,
  password,
  database,
});
const client = pool.connect();
client.query('SELECT stuff FROM table WHERE id = $1;', [1]);

```
Version of pg-promise: 11.10.1

**Comment by vitaly-t** [comment]
There is no connection pooling. This library manages it automatically, so you don't have to.

Other than then, the internal pool is exposed via [Database.$pool](https://vitaly-t.github.io/pg-promise/Database.html#$pool), but that's just for integration purposes, with external libraries.
