### ISSUE TITLE
Generators Examples

### ISSUE THREAD

**Issue by esetnik** [vitaly-t/pg-promise#95]
Can you provide an example of using generators with transactions to execute multiple generator functions inside a transaction?

**Comment by vitaly-t** [comment]
Is [this one](https://github.com/vitaly-t/pg-promise/wiki/Learn-by-Example#tasks) not good enough?
;)

**Comment by esetnik** [comment]
Hi, I was hoping for one using `db.tx` in conjunction with `this.batch` and two generator functions.

```

**Comment by vitaly-t** [comment]
What is the point of such an example?

You use generators inside transaction to simplify the dependency sequence. But when you need to execute a batch, you just execute it directly.

If you describe what it is you are trying to do, then I should be able to advise as to how to do this properly.

**Comment by esetnik** [comment]
The example above was definitely contrived. My use case is to ensure that a sequence of inserts occurs in entirety or not at all. I'd prefer to use several functions to separate out the complicated logic and processing required to prepare for the inserts. I was hoping to do as you've demonstrated above.

A few questions:
1. Is it required to return `yield this.any` instead of `this.none` when using generators even if there is no result?
2. is it possible to pass data into `a()` and `b()` by capture?
3. Is it possible to `yield` the entire transaction so that a generator-based framework like koa can easily   initiate the transaction without consuming the promised result?

**Comment by vitaly-t** [comment]
1. No
2. Not sure what you mean
3. yes, you can yield anything that returns a promise.

Generators support within pg-promise is limited to what you can run immediately inside a task or transaction.

If you want a wider support for the new async syntax, using `async` and `wait`, you should use `babel` or something like that. This is what people are using here.

**Comment by esetnik** [comment]
Yeah it's totally true that I can accomplish this without the use of generators I was just hoping to use the cleaner syntax to avoid promise hell.

**Comment by vitaly-t** [comment]
Promises were created to solve the callback hell, and if you code it right, promise is is very easy to read and maintain. Take a shot when you get it working, I will have a look to see if there is a better/simpler way ;)
