### ISSUE TITLE
using query files to create multiple records

### ISSUE THREAD

**Issue by tkellen** [vitaly-t/pg-promise#97]
Assume you have this input:
```js
const data = [
  ['Minnesota', 'MN'],
  ['Vermont', 'VT']
];
```

Is there any plan to support generating this kind of SQL?
```sql
INSERT INTO state (name, abbr) VALUES ('Minnesota', 'MN'), ('Vermont', 'VT')
```

**Comment by vitaly-t** [comment]
Did you see this? - [Performance Boost](https://github.com/vitaly-t/pg-promise/wiki/Performance-Boost)

**Comment by tkellen** [comment]
Ah! No, I haven't. This seems like exactly what I was looking for. Thanks!

**Comment by vitaly-t** [comment]
You are welcome! :)

**Comment by vitaly-t** [comment]
There is a further progress with this in [4.0.6 update](https://github.com/vitaly-t/pg-promise/releases/tag/v.4.0.6) ;)

**Comment by tkellen** [comment]
Radddddd. Are you on twiter? I just posted this; https://twitter.com/tkellen/status/728670878989422592

**Comment by vitaly-t** [comment]
Cheers! I keep working on documentation and tests. Any technical feedback would be nice ;)
