### ISSUE TITLE
best structure practice for db items that belong to another item?

### ISSUE THREAD

**Issue by Ashtonian** [vitaly-t/pg-promise#98]
Hello!

Awesome library I especially love https://github.com/vitaly-t/pg-promise-demo, https://github.com/vitaly-t/pg-promise/wiki/Performance-Boost and https://github.com/vitaly-t/pg-promise/wiki/Common-Mistakes. I really wish every major library did this, learned loads just by reviewing those. 

This is more of a design/best practices question I was hoping you would be able to spare your time and answer. If I had an entity that had many entities, for example an item with many images, which of course translates to a one to many table relationship -> how would you recommend structuring the repositories based on the advance demo project? In the example above I can think of three design thoughts and I don't really see a loss from the business logic/side of things.

* The child item(images) are all managed through the parent item repo and all code related is included in there. 
* The child item(images) has its own repo with all the potential methods there, that then gets called by the parent repo. 
* Two repos, one for managing the child items in relation to their parent, and one that manages all. 

I would really appreciate your thoughts on this or any reference material you would be able to point me to?

**Comment by vitaly-t** [comment]
The answer you are looking for isn't really about this library, it is about the repository pattern, and the way it applies to full-scale applications.

You start with table-level repositories that implement basic operations like shown in that demo app.

Then you write higher-level repositories, so-called business-level/logic repositories that encompass the logic of your application and/or the table relationship.

For example, if your database has tables `USERS`->`SALES`->`PRODUCTS`, you can add repository `Purchase` that will use other repositories and perhaps have its own direct access to implement the process of selling products.

**Comment by Ashtonian** [comment]
Thanks for the response! Based on that information and the advance demo app you provided the basic repo pattern, I have some questions on the implementation.

Where you would expose that higher level repository - In that example would you inject dependent repositories into the other ones?

``` javascript
 extend: obj => {
        obj.childRepo = repos.child(obj)
        obj.parentRepo= repos.parent(obj,repos.child(obj));
    }
```

or would you just do it at a higher level? 
``` javascript
 extend: obj => {
        obj.ChildRepo = repos.child(obj)
        obj.parentRepo= repos.products(obj);
    }
```

Model.js:
``` javascript
var parentRepo= require('parentRepo.js')
var childRepo = require('childRepo.js')
module.exports = {
    Add: item => parentRepo.add(item).then(childRepo.add(item.children)
 // TODO: somehow convert to batch or .tx
};
``` 

I'd like to be able to keep the table/relationship code in one place and use a transaction when inserting into multiple tables, and I'm having a hard time of seeing what an actual implementation of that would look like in javascript as this is all very new to me. 

On a similar note - what would be the best practice for exposing the pgp library to one of the repos as in that example project, without adding circular dependencies or adding another  `require('pg-promise')` statement to the repo itself. Adding another require statement would work but seems like there is a better way. 

``` javascript
var options = {
    promiseLib: promise,

    extend: obj => {
       // TODO: injecting it here is circular
        obj.users = repos.users(obj,pgp);
        obj.products = repos.products(obj);
    }

};

var config = {
    host: 'localhost',
    port: 5432,
    database: 'pg-promise-demo',
    user: 'postgres'
};

var pgp = require('pg-promise')(options);
```

**Comment by vitaly-t** [comment]
The repositories are completely independent of each other, and you add all of them within event `extend` in the same way.

**Comment by vitaly-t** [comment]
I'm closing this issue now. If you still have questions, StackOverflow is a better place to ask them, as I may not always have the time, and this place is mostly to report bugs or make change requests.
